### ISSUE TITLE
Code of Princess EX

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#101]
#### Current on `master` :

* Build Version :1.0.1963

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 113
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
```

**Comment by GoffyDude** [comment]
## Code of Princess EX

#### Current on `master` : 1.0.3975

Corrupt and missing graphics. All cutscenes are black screen with choppy audio. A button and + button are your friend in skipping through to get in-game, where graphics are still corrupt and missing.


#### Screenshots :
![2020-03-23 16_51_03-Ryujinx 1 0 3975 _ Code of Princess EX _ 010034E005C9C000](https://user-images.githubusercontent.com/62343878/77370652-fbdd7180-6d26-11ea-8a59-9ed8edb218d1.png)
![2020-03-23 16_51_08-Ryujinx 1 0 3975 _ Code of Princess EX _ 010034E005C9C000](https://user-images.githubusercontent.com/62343878/77370658-fd0e9e80-6d26-11ea-83be-bd149baf643f.png)
![2020-03-23 16_51_37-Ryujinx 1 0 3975 _ Code of Princess EX _ 010034E005C9C000](https://user-images.githubusercontent.com/62343878/77370659-fda73500-6d26-11ea-9f46-a6e5f9b116e0.png)
![2020-03-23 16_51_47-Ryujinx 1 0 3975 _ Code of Princess EX _ 010034E005C9C000](https://user-images.githubusercontent.com/62343878/77370663-fe3fcb80-6d26-11ea-9c76-a4829449e82f.png)
![2020-03-23 16_51_55-Ryujinx 1 0 3975 _ Code of Princess EX _ 010034E005C9C000](https://user-images.githubusercontent.com/62343878/77370702-13b4f580-6d27-11ea-8b9e-1b4980d860ca.png)
![2020-03-23 16_52_00-Ryujinx 1 0 3975 _ Code of Princess EX _ 010034E005C9C000](https://user-images.githubusercontent.com/62343878/77370711-1adc0380-6d27-11ea-9050-35b36e0851f9.png)
![2020-03-23 16_52_49-Ryujinx 1 0 3975 _ Code of Princess EX _ 010034E005C9C000](https://user-images.githubusercontent.com/62343878/77370758-23ccd500-6d27-11ea-9a84-fc4d48695b9c.png)
![2020-03-23 16_53_14-Ryujinx 1 0 3975 _ Code of Princess EX _ 010034E005C9C000](https://user-images.githubusercontent.com/62343878/77370779-35ae7800-6d27-11ea-95db-314fdd9a78b6.png)


#### Log file :

[CoPEX.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4372274/CoPEX.zip)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6635

**Comment by EmulationFanatic** [comment]
Updated
