### ISSUE TITLE
Phoenix Wright: Ace Attorney Trilogy

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1011]
#### Current on `master` : 1.0.4383

- Takes several minutes to boot.
- Seems to play properly after that, but crashed a few minutes into gameplay.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32 width, Int32 height, Int32 depth, Int32 levels, Int32 layers, Int32 blockWidth, Int32 blockHeight, Int32 bytesPerPixel, Int32 gobBlocksInY, Int32 gobBlocksInZ, Int32 gobBlocksInTileX, SizeInfo sizeInfo, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.Texture\LayoutConverter.cs:line 233
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 475
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 326
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(CopyTexture copyTexture) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 315
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyTexture(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyTexture.cs:line 98
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 337
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-04-30 10_59_39-Ryujinx 1 0 4383 - Phoenix Wright_ Ace Attorney Trilogy v1 0 0 (0100CB000A142000](https://user-images.githubusercontent.com/62343878/80738578-7e99df00-8ad2-11ea-809e-4f468cb5f646.png)
![2020-04-30 10_59_57-Ryujinx 1 0 4383 - Phoenix Wright_ Ace Attorney Trilogy v1 0 0 (0100CB000A142000](https://user-images.githubusercontent.com/62343878/80738580-7f327580-8ad2-11ea-8c88-0751080797bb.png)
![2020-04-30 11_00_04-Ryujinx 1 0 4383 - Phoenix Wright_ Ace Attorney Trilogy v1 0 0 (0100CB000A142000](https://user-images.githubusercontent.com/62343878/80738593-85285680-8ad2-11ea-8ffb-bec63bb28ac2.png)
![2020-04-30 11_01_03-Ryujinx 1 0 4383 - Phoenix Wright_ Ace Attorney Trilogy v1 0 0 (0100CB000A142000](https://user-images.githubusercontent.com/62343878/80738617-8b1e3780-8ad2-11ea-9a3a-5709e1c2f0a8.png)
![2020-04-30 11_03_54-Ryujinx 1 0 4383 - Phoenix Wright_ Ace Attorney Trilogy v1 0 0 (0100CB000A142000](https://user-images.githubusercontent.com/62343878/80738621-8d809180-8ad2-11ea-8cd0-2fff0cf10367.png)

#### Log file :

[PWAAT.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4559897/PWAAT.zip)

**Comment by tonyunreal** [comment]
## Phoenix Wright: Ace Attorney Trilogy (0100CB000A142000)

#### Game Update Version : 1.0.1

#### Current on `master` : 1.0.6604

I played through the first chapter of the first game, haven't experienced any crash or other issues.

#### Hardware Specs : 

##### CPU: i7-8700B
##### GPU: AMD Radeon RX Vega 64
##### RAM: 32GB

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Sinsinkuga** [comment]
Hi there! noob question– this was the most reliable-looking thing i found on playing AA on mac through ryujinx. Where can I find the full game download?
