### ISSUE TITLE
20XX

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#102]
#### Current on `master` :

* Build Version :1.0.1963

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 113
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
```

**Comment by HorrorTroll** [comment]
Updated

**Comment by benderscruffy** [comment]
needs an update

**Comment by LukeWarnut** [comment]
## 20XX

#### Game Update Version : 1.1.0

#### Current on `master` : 1.0.6604

Goes ingame with multiple graphical issues.
 - Game is inverted during the intro and title screen, but swaps to looking as intended during the loading screen after the title.
 - The playable character is invisible.
 - Menus and UI suffer from graphical and transparency issues.

#### Hardware Specs : 

##### CPU: AMD Ryzen 5 2600
##### GPU: NVIDIA GTX 1660 SUPER
##### RAM: 16GB

#### Screenshots :

![image](https://user-images.githubusercontent.com/65521430/108429156-98491600-720d-11eb-9f49-1562b7ae7154.png)
![image](https://user-images.githubusercontent.com/65521430/108429175-9f702400-720d-11eb-9167-c1b714bb7f5e.png)
![image](https://user-images.githubusercontent.com/65521430/108429238-b57de480-720d-11eb-9e6b-4f1eea4b8606.png)
![image](https://user-images.githubusercontent.com/65521430/108429265-bdd61f80-720d-11eb-8f0f-8085d6fc00b1.png)
![image](https://user-images.githubusercontent.com/65521430/108429291-c3cc0080-720d-11eb-8a06-205838fa6cae.png)
![image](https://user-images.githubusercontent.com/65521430/108429320-c890b480-720d-11eb-81d9-5a2beaa68888.png)

#### Log file :

[20XX.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6006201/20XX.log)

**Comment by EmulationFanatic** [comment]
Updated, thanks!

**Comment by Niwu34** [comment]
## 20XX

#### Game Update Version : *1.1.0*

#### Current on `master` : *1.0.6895*

Goes ingame with multiple graphical issues.

- Game is inverted during the intro and title screen, but swaps to looking as intended during the loading screen after the title.
- The playable character is invisible.

#### Hardware Specs : 

##### CPU: *Ryzen 5 3600*
##### GPU: *Rx 570*
##### RAM: *32GB*


#### Screenshots :
![Bildschirmfoto von 2021-05-28 08-34-52](https://user-images.githubusercontent.com/67392333/119940542-a4244100-bf8f-11eb-9483-ecd745b847c4.png)
![Bildschirmfoto von 2021-05-28 08-25-59](https://user-images.githubusercontent.com/67392333/119940550-a8e8f500-bf8f-11eb-818b-b5c9e9129e3e.png)

**Comment by Niwu34** [comment]
## 20XX

#### Game Update Version : *1.1.0*

#### Current on `master` : *1.1.191*

*The Game Boots fine and plays at high fps.
The colors are wrong (Red instead of blue) [See Screenshots below] & The gameplay is flipped*


#### Hardware Specs : 

##### CPU: *Ryzen 5 5600x*
##### GPU: *Nvidia 2080Ti*
##### RAM: *32Gb*

#### Screenshots :
Ryu:
![image](https://user-images.githubusercontent.com/67392333/180666422-7ad62099-c176-464d-bc2c-b5fe199271ee.png)

Switch:
![image](https://user-images.githubusercontent.com/67392333/180666574-86c4981d-7dfd-4026-af83-46e69edd6285.png)

Ryu:
![image](https://user-images.githubusercontent.com/67392333/180666729-0abe839c-99ae-49be-a7cd-1b338f52db84.png)

Switch:
![image](https://user-images.githubusercontent.com/67392333/180666671-649a2118-44a3-4515-918a-f7da08e6edc3.png)

**Comment by marcelo4768** [comment]
the same problem here =(

**Comment by F1ReB4LL** [comment]
Colors were fixed in 1.1.731 by https://github.com/Ryujinx/Ryujinx/pull/4717
The game is still rendered upside-down, though.

![ryujinx_20xx1](https://user-images.githubusercontent.com/39680140/236622542-9e7ef2b3-db66-4422-8542-1c1b6682bb70.png)

**Comment by F1ReB4LL** [comment]
Fixed in 1.1.970 by https://github.com/Ryujinx/Ryujinx/pull/4673

![ryujinx_20xx2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/ccf2efbd-54e2-4156-b53d-96a9cba75d84)
![ryujinx_20xx3](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/e819545d-7794-4080-be20-f11e640ccd01)

**Comment by Niwu34** [comment]
## 20XX

#### Game Update Version : *1.1.0*

#### Current on `master` : *1.1.986*

The Game Boots and plays at high fps!
The resolution scaler works as intended.
Vulkan & OpenGL were tested


#### Hardware Specs : 

##### CPU: *I5 13600k*
##### GPU: *Nvidia 3090*
##### RAM: *32Gb*

#### Screenshots :
![Menu](https://github.com/Ryujinx/Ryujinx-Games-List/assets/67392333/ae21d529-e084-4482-9fc1-252616a13386)
![Inagme](https://github.com/Ryujinx/Ryujinx-Games-List/assets/67392333/4eb04f0d-692a-4baf-8054-b5ea01774fbb)
![Base Area Native Res](https://github.com/Ryujinx/Ryujinx-Games-List/assets/67392333/c91cee1f-c78d-4c22-98c9-afa6670acbd2)
![Base Area 4x Res](https://github.com/Ryujinx/Ryujinx-Games-List/assets/67392333/4571710f-2eef-419c-8f63-d22a4a5f692c)
