### ISSUE TITLE
Cartoon Network Battle Crashers

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#103]
#### Current on `master` :

* Build Version :1.0.1963

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 113
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
```

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## Cartoon Network: Battle Crashers

#### Current on `master` : 1.0.3937

Boots with corrupted splash screens.
Follows up with music playing at a black screen which turns into a corrupt title screen. Pressing A takes you to a black screen with music playing again.
Pressing A again seems to have an effect in the log, but emulation remains a black screen with music for several minutes.
Eventually a cutscene appears with some frames of it corrupt. This eventually takes you to a map/level selection screen with some corrupt graphics. Pressing A here and there seems to keep moving things forward.
Ultimately the level loads with corrupt graphics, repeatedly hangs for 10-15 seconds, and keeps trying to load itself, letting you get a few feet ahead. 
This game tries very hard to work and the audio is smooth throughout, but just doesn't render graphics correctly yet (or fast enough).
Unable to progress past a certain part of the level that requires visible prompts to move forward.

#### Screenshots :

![2020-03-22 07_20_44-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250679-33f19100-6c0f-11ea-9f5e-5db703f9ac28.png)
![2020-03-22 07_21_09-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250680-3522be00-6c0f-11ea-891b-7347ba1c65c5.png)
![2020-03-22 07_22_19-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250681-35bb5480-6c0f-11ea-9666-f0547e5aa3c6.png)
![2020-03-22 07_24_20-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250685-3bb13580-6c0f-11ea-9fc5-85d9e20cab27.png)
![2020-03-22 07_24_32-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250691-423fad00-6c0f-11ea-8ac4-e21cacf25bd5.png)
![2020-03-22 07_25_04-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250705-4ec40580-6c0f-11ea-9061-5f38f0d51f00.png)
![2020-03-22 07_25_47-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250715-571c4080-6c0f-11ea-96df-576367a92ce6.png)
![2020-03-22 07_26_49-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250719-5f747b80-6c0f-11ea-80df-743a600463b4.png)
![2020-03-22 07_27_10-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250720-60a5a880-6c0f-11ea-953b-40826eb6da8a.png)
![2020-03-22 07_29_14-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250721-63a09900-6c0f-11ea-9795-581cb668a4d3.png)
![2020-03-22 07_30_12-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250723-67342000-6c0f-11ea-956b-3c7b2df872c3.png)
![2020-03-22 07_30_51-Ryujinx 1 0 3937 _ Cartoon Network_ Battle Crashers _ 0100085003A2A000](https://user-images.githubusercontent.com/62343878/77250729-6a2f1080-6c0f-11ea-9d02-715ce7303162.png)

#### Log file :
[CNBC.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4365296/CNBC.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6631

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6906

**Comment by EmulationFanatic** [comment]
Updated
