### ISSUE TITLE
Danmaku Unlimited 3

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#104]
#### Current on `master` :

* Build Version :1.0.1963

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 113
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
```

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## Danmaku Unlimited 3

#### Current on `master` : 1.0.3937

Game launches and is responsive in menus apart from a brief pause while launching the tutorial.
Once in the tutorial, graphical output is upside-down and corrupt, making it impossible to complete.


#### Screenshots :
![2020-03-22 08_41_33-Ryujinx 1 0 3937 _ Danmaku Unlimited 3 _ 0100417007F78000](https://user-images.githubusercontent.com/62343878/77252453-8a63cd00-6c19-11ea-94a9-57bb6e6fe3e4.png)
![2020-03-22 08_42_02-Ryujinx 1 0 3937 _ Danmaku Unlimited 3 _ 0100417007F78000](https://user-images.githubusercontent.com/62343878/77252459-92bc0800-6c19-11ea-8f56-8039fa3916bf.png)
![2020-03-22 08_43_22-Ryujinx 1 0 3937 _ Danmaku Unlimited 3 _ 0100417007F78000](https://user-images.githubusercontent.com/62343878/77252461-9780bc00-6c19-11ea-995a-e58423980fc4.png)


#### Log file :

[DanmakuUnlimited3.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4365432/DanmakuUnlimited3.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by GoffyDude** [comment]
## Danmaku Unlimited 3

#### Current on `master` : 1.0.4593

Game now allows you through menus properly and into in-game, where there is very minor graphical corruption, and a chance of crashing while loading the first level. Game crashes a minute after starting the level otherwise.

```
HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 423
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 268
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 97
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 98
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
#### Screenshots :

![2020-05-22 02_42_28-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652381-c2b46700-9bda-11ea-9069-5be8946cc662.png)
![2020-05-22 02_42_33-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652399-cb0ca200-9bda-11ea-967b-f6e54fb9f62e.png)
![2020-05-22 02_42_36-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652407-cf38bf80-9bda-11ea-84e1-d00e10ad8fe5.png)
![2020-05-22 02_42_39-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652422-d52ea080-9bda-11ea-9350-545996d1b0d4.png)
![2020-05-22 02_42_59-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652435-d95abe00-9bda-11ea-926f-e4d0df6597ce.png)
![2020-05-22 02_44_01-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652436-d9f35480-9bda-11ea-8a6c-50412107405b.png)
![2020-05-22 02_44_24-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652452-e24b8f80-9bda-11ea-83a5-87f614e009aa.png)
![2020-05-22 02_44_37-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652476-e8da0700-9bda-11ea-80ad-86ff9ffc67a7.png)
![2020-05-22 02_45_34-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652495-ef687e80-9bda-11ea-84f2-1da70f11653d.png)
![2020-05-22 02_47_01-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652513-f7c0b980-9bda-11ea-8cbc-65c3acfa9c35.png)
![2020-05-22 03_11_30-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652534-fd1e0400-9bda-11ea-942b-98f40ea658f1.png)
![2020-05-22 03_12_45-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652547-00b18b00-9bdb-11ea-8b6a-a423a0cc32a3.png)
![2020-05-22 03_13_41-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652564-0909c600-9bdb-11ea-855b-d57919fe2050.png)
![2020-05-22 03_14_26-Ryujinx 1 0 4593 - Danmaku Unlimited 3 v1 1 0 (0100417007F78000) (64-bit)](https://user-images.githubusercontent.com/62343878/82652582-132bc480-9bdb-11ea-8e77-f8e419079363.png)


#### Log file :

[DanmakuUnlimited.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4667166/DanmakuUnlimited.zip)

**Comment by GoffyDude** [comment]
Updated

**Comment by benderscruffy** [comment]
didnt crash for me got pretty far

**Comment by EmulationFanatic** [comment]
Updated
