### ISSUE TITLE
Megaman Legacy Collection Vol.1

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#105]
#### Current on `master` :

* Build Version :1.0.1963

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 113
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
```

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## Mega Man Legacy Collection

#### Current on `master` : 1.0.3937

Game launches initial CAPCOM title screen upside-down and then crashes. Including debug log here.

```
| Audio OpenAudioOutImpl: Invalid sample rate!
```


#### Screenshots :

![2020-03-22 06_40_57-Ryujinx 1 0 3937 _ Mega Man Legacy Collection _ 01002D4007AE0000](https://user-images.githubusercontent.com/62343878/77249651-4b794b80-6c08-11ea-86dd-cbb176ec320a.png)

#### Log file :

[MMLC_debug.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4365227/MMLC_debug.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by benderscruffy** [comment]
goes ingame now but all graphics are inverted

**Comment by benderscruffy** [comment]
please update

**Comment by EmulationFanatic** [comment]
@benderscruffy you can submit your own gamedb test updates by replying to threads with a new issue template filled out, too, instead of asking others to do it for you.
Updated.

**Comment by EmulationFanatic** [comment]
Same issue on 1.0.6906
