### ISSUE TITLE
Sparkle ZERO

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#106]
#### Current on `master` :

* Build Version :1.0.1963

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 113
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
```

**Comment by GoffyDude** [comment]
## Sparkle Zero

#### Current on `master` : 1.0.3969

Game is playable with occasional low FPS.

#### Screenshots :

![2020-03-23 11_37_40-Ryujinx 1 0 3969 _ Sparkle Zero _ 0100E4F00AE14000](https://user-images.githubusercontent.com/62343878/77346430-d8510180-6cfb-11ea-8cd5-0913b3bb9e3f.png)
![2020-03-23 11_38_15-Ryujinx 1 0 3969 _ Sparkle Zero _ 0100E4F00AE14000](https://user-images.githubusercontent.com/62343878/77346437-db4bf200-6cfb-11ea-87f2-1ec4448d00be.png)
![2020-03-23 11_38_40-Ryujinx 1 0 3969 _ Sparkle Zero _ 0100E4F00AE14000](https://user-images.githubusercontent.com/62343878/77346445-ddae4c00-6cfb-11ea-8e23-851cb79867ae.png)
![2020-03-23 11_43_45-Ryujinx 1 0 3969 _ Sparkle Zero _ 0100E4F00AE14000](https://user-images.githubusercontent.com/62343878/77346455-e010a600-6cfb-11ea-9f50-a4972e757d08.png)


#### Log file :

[SparkleZero.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4371053/SparkleZero.zip)

**Comment by B3astTech** [comment]
Updated
