### ISSUE TITLE
Animal Crossing New Horizons

### ISSUE THREAD

**Issue by a63d** [Ryujinx/Ryujinx-Games-List#1064]
I have 4GB of ram and Intel Core i5-2400 CPU.
Ryujinx 1.0.7692
Game Update 1.2.0
System Version: 10.0.1
Nothing is in the device save directory.
The game doesn't start at all. It's only a black screen and the console says:

**Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at OpenTK.Graphics.OpenGL.GL.ScissorIndexed(Int32, Int32, Int32, Int32, Int32)
   at Ryujinx.Graphics.OpenGL.Pipeline.SetScissor(Int32, Int32, Int32, Int32, Int32)
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateScissorState(Ryujinx.Graphics.Gpu.State.GpuState)
   at Ryujinx.Graphics.Gpu.Engine.Methods.Clear(Ryujinx.Graphics.Gpu.State.GpuState, Int32)
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(Ryujinx.Graphics.MethodParams)
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(Ryujinx.Graphics.Gpu.State.GpuState, Ryujinx.Graphics.Gpu.State.GpuState, Int32)
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[], Ryujinx.Graphics.Gpu.State.GpuState, Ryujinx.Graphics.Gpu.State.GpuState)
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[], Int32, Int32, Ryujinx.Graphics.Gpu.ShadowRamControl, Ryujinx.Graphics.Gpu.State.GpuState, Ryujinx.Graphics.Gpu.State.GpuState)
   at Ryujinx.Graphics.Gpu.NvGpuFifo+CachedMacro.Execute(Int32[], Ryujinx.Graphics.Gpu.ShadowRamControl, Ryujinx.Graphics.Gpu.State.GpuState, Ryujinx.Graphics.Gpu.State.GpuState)
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(Ryujinx.Graphics.MethodParams)
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32)
   at Ryujinx.Graphics.Gpu.DmaPusher.Step()
   at Ryujinx.Ui.GlRenderer.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()**

After a while, the whole emulator crashes.

**Comment by AcK77** [comment]
Closed in favor of #250
