### ISSUE TITLE
War Theatre

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1067]
#### Current on `master` : 1.0.4479

- Game loads to menus quickly, where sound effects loop repeatedly. These anomalies continue in-game, where emulation freezes every few seconds with FPS dropping and sound stopping. 
- During guided dialogue, there is graphical corruption with what appears to be a blur filter being applied, and missing or incorrectly tiled textures on objects.
- As the in-game portion initializes, Ryujinx crashes.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentException: Invalid floating point type "0".
   at Ryujinx.Graphics.Shader.Instructions.InstEmitHelper.GetSrcB(EmitterContext context, FPType floatType) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Instructions\InstEmitHelper.cs:line 60
   at Ryujinx.Graphics.Shader.Instructions.InstEmit.F2I(EmitterContext context) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Instructions\InstEmitConversion.cs:line 93
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(ReadOnlySpan`1 code, TranslatorCallbacks callbacks, TranslationFlags flags, ShaderConfig& config, Int32& size) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 210
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateGraphicsShader(GpuState state, ShaderStage stage, UInt64 gpuVa, UInt64 gpuVaA)
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 130
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 830
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 123
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 118
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 498
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 102
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-05-04 06_14_14-Ryujinx 1 0 4479 - War Theatre v1 0 0 (010084D00A134000) (64-bit)](https://user-images.githubusercontent.com/62343878/80965451-c5881d00-8dcf-11ea-9ef9-d7a4a0dbc873.png)
![2020-05-04 06_15_10-Ryujinx 1 0 4479 - War Theatre v1 0 0 (010084D00A134000) (64-bit)](https://user-images.githubusercontent.com/62343878/80965453-c620b380-8dcf-11ea-96f8-b6ace2178f8c.png)
![2020-05-04 06_16_15-Ryujinx 1 0 4479 - War Theatre v1 0 0 (010084D00A134000) (64-bit)](https://user-images.githubusercontent.com/62343878/80965468-d0db4880-8dcf-11ea-86b6-75ba7cdaf799.png)
![2020-05-04 06_17_41-Ryujinx 1 0 4479 - War Theatre v1 0 0 (010084D00A134000) (64-bit)](https://user-images.githubusercontent.com/62343878/80965489-d8025680-8dcf-11ea-8fb9-c12c9188fdf9.png)
![2020-05-04 06_19_06-Ryujinx 1 0 4479 - War Theatre v1 0 0 (010084D00A134000) (64-bit)](https://user-images.githubusercontent.com/62343878/80965512-e18bbe80-8dcf-11ea-992b-a06a7ae53591.png)
![2020-05-04 06_20_01-Ryujinx 1 0 4479 - War Theatre v1 0 0 (010084D00A134000) (64-bit)](https://user-images.githubusercontent.com/62343878/80965542-ebadbd00-8dcf-11ea-8589-910b88e114fb.png)

#### Log file :

[WarTheatre.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4574578/WarTheatre.zip)

**Comment by benderscruffy** [comment]
using 1.0.6127
still has the graphics glitches
goes ingame and doesnt crash out

**Comment by EmulationFanatic** [comment]
Updated
