### ISSUE TITLE
Sparkle 2

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#107]
#### Current on `master` :

* Build Version :1.0.1963

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 113
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
```

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## Sparkle 2

#### Current on `master` : 1.0.3937

Choppy audio through initial splash screen and then is playable through the first level, though the controls are extremely sensitive which make the game quite difficult.
Hangs at a loading screen after finishing the first level (see final screenshot.


#### Screenshots :

![2020-03-22 06_10_23-Ryujinx 1 0 3937 _ Sparkle 2 _ 010028D0045CE000](https://user-images.githubusercontent.com/62343878/77249141-ac9f2000-6c04-11ea-8388-4a5365a6e4f1.png)
![2020-03-22 06_10_40-Ryujinx 1 0 3937 _ Sparkle 2 _ 010028D0045CE000](https://user-images.githubusercontent.com/62343878/77249143-af9a1080-6c04-11ea-901a-2afc9f33be39.png)
![2020-03-22 06_11_16-Ryujinx 1 0 3937 _ Sparkle 2 _ 010028D0045CE000](https://user-images.githubusercontent.com/62343878/77249147-b32d9780-6c04-11ea-9585-7d85c6b526d3.png)
![2020-03-22 06_12_33-Ryujinx 1 0 3937 _ Sparkle 2 _ 010028D0045CE000](https://user-images.githubusercontent.com/62343878/77249154-bd4f9600-6c04-11ea-87e6-e9d0379f883b.png)
![2020-03-22 06_13_37-Ryujinx 1 0 3937 _ Sparkle 2 _ 010028D0045CE000](https://user-images.githubusercontent.com/62343878/77249162-c80a2b00-6c04-11ea-9654-26bb11b223f5.png)


#### Log file :

[Sparkle2.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4365194/Sparkle2.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by benderscruffy** [comment]
doesnt crash anymore
goes to next level

**Comment by EmulationFanatic** [comment]
Updated
