### ISSUE TITLE
Vesta

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1070]
#### Current on `master` : 1.0.4479

- Loads intro splash screens and lands at title screen.
- Starting a new game triggers a black screen cutscene, which can be skipped by pressing B.
- Skipping the cutscene or waiting for it to finish results in a crash.

```
HLE.HostThread.4 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.InvalidOperationException: Function entry point is not contained in a block.
   at ARMeilleure.Decoders.Optimizations.TailCallRemover.RunPass(UInt64 entryAddress, List`1 blocks) in C:\projects\ryujinx\ARMeilleure\Decoders\Optimizations\TailCallRemover.cs:line 22
   at ARMeilleure.Decoders.Decoder.DecodeFunction(IMemoryManager memory, UInt64 address, ExecutionMode mode, Boolean highCq) in C:\projects\ryujinx\ARMeilleure\Decoders\Decoder.cs:line 138
   at ARMeilleure.Translation.Translator.Translate(UInt64 address, ExecutionMode mode, Boolean highCq) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 149
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 127
   at ARMeilleure.Instructions.NativeInterface.GetFunctionAddress(UInt64 address) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 404
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 98
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
#### Screenshots :

![2020-05-04 07_42_00-Ryujinx 1 0 4479 - Vesta v1 0 0 (010057B00712C000) (64-bit)](https://user-images.githubusercontent.com/62343878/80972213-16e9d980-8ddb-11ea-8ac3-b2c0c518d6fb.png)
![2020-05-04 07_42_02-Ryujinx 1 0 4479 - Vesta v1 0 0 (010057B00712C000) (64-bit)](https://user-images.githubusercontent.com/62343878/80972214-17827000-8ddb-11ea-82fb-751fbd85ca1f.png)
![2020-05-04 07_42_34-Ryujinx 1 0 4479 - Vesta v1 0 0 (010057B00712C000) (64-bit)](https://user-images.githubusercontent.com/62343878/80972216-181b0680-8ddb-11ea-9f64-e2a008980c82.png)
![2020-05-04 07_42_38-Ryujinx 1 0 4479 - Vesta v1 0 0 (010057B00712C000) (64-bit)](https://user-images.githubusercontent.com/62343878/80972221-18b39d00-8ddb-11ea-944b-2e1740c2538b.png)

#### Log file :

[Vesta.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4574985/Vesta.zip)

**Comment by benderscruffy** [comment]
using 1.0.5644
still the same issue
[vesta.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5509391/vesta.zip)

**Comment by EmulationFanatic** [comment]
Updated
