### ISSUE TITLE
Levelhead

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1076]
#### Current on `master` : 4481

game crashes on launch
```
Last error returned.
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.HLE.Exceptions.ServiceNotImplementedException: The service call is not implemented.

Service Command: Ryujinx.HLE.HOS.Services.Nv.INvDrvServices: 6 (GetStatus)

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00399530 Sub000000000c717530
   sdk:0x003978e4 Sub000000000c7158e4
   sdk:0x0039af98 Sub000000000c718f98
   sdk:0x00397144 nv::GetGraphicsMemoryInfo(nv::MemoryInfo*)
   main:0x0139a7ec Sub000000000939e7ec
   main:0x01291fec Sub0000000009295fec
   main:0x0134b4e0 Sub000000000934f4e0
   main:0x0134b8d8 Sub000000000934f8d8
   main:0x013bfef4 Sub00000000093c3ef4
   main:0x013c0464 nnMain
   sdk:0x0009857c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  06 00 00 00 00 00 00 00   SFCI············
00000010   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.Nv.INvDrvServices.GetStatus(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nv\INvDrvServices.cs:line 392
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```

#### Log file :
[levelhead.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4575504/levelhead.log)

**Comment by GoffyDude** [comment]
Needs update

**Comment by SeraUX** [comment]
## Levelhead

#### Current on `master` : 1.0.4573

Boots to the menu but crashes with an missing service error

```
Last error returned.
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IRequest: 21

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0028f8b8 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc:
:detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>,
 nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> >, 4ul, 12ul, false>, std::
__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif
::detail::BufferArgumentInfo<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSess
ionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf:
:cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientA
rgumentType<4ul, 4ul, void>, unsigned int)
   sdk:0x0028f0b4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::nifm::detail::IRequest, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBas
e<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::nifm::detail::IRequest, nn::sf::cmif::client::detail::Process
ModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_GetAppletInfo(nn::sf::Out<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::s
f::OutBuffer const&, unsigned int)
   sdk:0x0028ce7c nn::nifm::detail::RequestClient::PrepareLibraryApplet(nn::applet::LibraryAppletHandle*)
   sdk:0x00292864 nn::nifm::PrepareHandlingNetworkRequestResult(nn::nifm::RequestHandle, nn::applet::LibraryAppletHandle*)
   sdk:0x002947c8 nn::nifm::NetworkConnection::HandleNetworkRequestErrorResult()
   sdk:0x00293024 nn::nifm::HandleNetworkRequestErrorResult()
   sdk:0x611a3e5654 Sub0000006126763654
   main:0x012cfce4 Sub00000000092d3ce4
   main:0x012d132c Sub00000000092d532c
   main:0x01142aec Sub0000000009146aec
   main:0x005bfdb8 Sub00000000085c3db8
   main:0x008fd828 Sub0000000008901828
   main:0x01131cec Sub0000000009135cec
   main:0x01131e9c Sub0000000009135e9c
   main:0x01177b8c Sub000000000917bb8c
   main:0x0117781c Sub000000000917b81c
   main:0x01280ca0 Sub0000000009284ca0
   main:0x0117384c Sub000000000917784c
   main:0x01142ca0 Sub0000000009146ca0
   main:0x000f6624 Sub00000000080fa624
   main:0x00ef2310 Sub0000000008ef6310
   main:0x01131cec Sub0000000009135cec
   main:0x01131e9c Sub0000000009135e9c
   main:0x01177b8c Sub000000000917bb8c
   main:0x0117781c Sub000000000917b81c
   main:0x012923fc Sub00000000092963fc
   main:0x0129196c Sub000000000929596c
   main:0x01291ec8 Sub0000000009295ec8
   main:0x013c05d0 nnMain
   sdk:0x0009857c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Buffer Information:
        ReceiveBuff:
        Position: 0x000000000d18225c Size: 0x0000000000001000 Flags: 0

Raw Request Data:
00000000   01 00 14 00 03 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  15 00 00 00 00 00 00 00   SFCI············
00000020   03 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000030   10 00 00 00                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ry
ujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)

```

#### Screenshots :
![2020-05-17-094904_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82138905-44477600-9824-11ea-898a-693a89049e0d.png)

#### Log file :
[levelhead.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4639850/levelhead.log)

**Comment by GoffyDude** [comment]
Updated

**Comment by SeraUX** [comment]
## LevelHead

#### Game Update Version : 0.52.13

#### Current on `master` : 1.0.4829

**First try**
Game crashed with an opcode error while in the main menu.
```
Unhandled exception. Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000c42e640 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
```

**Second try**
Game went past the menu, but crashed after the cutscene. Other problem I noticed was audio being out of sync with the video.
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 423
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 268
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 97
```

#### Hardware Specs :

##### CPU: i3 7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti
##### RAM: 8GB

#### Outstanding Issues:



#### Screenshots :

![07_04_40-09:40:19](https://user-images.githubusercontent.com/62521228/86507876-c511ff80-bddb-11ea-8505-351ff3253b18.png)
![07_04_44-09:44:31](https://user-images.githubusercontent.com/62521228/86507881-c6dbc300-bddb-11ea-91bf-ffd6cb89f202.png)
![07_04_46-09:46:29](https://user-images.githubusercontent.com/62521228/86507884-c7745980-bddb-11ea-8bba-fe5ab5f46f1b.png)
![07_04_46-09:46:39](https://user-images.githubusercontent.com/62521228/86507885-c80cf000-bddb-11ea-991d-d891d5cf024d.png)
![07_04_46-09:46:56](https://user-images.githubusercontent.com/62521228/86507886-c8a58680-bddb-11ea-8c3a-3fcb0062ffa3.png)


#### Log file :

[levelhead.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4872256/levelhead.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by benderscruffy** [comment]
goes ingame now
![level](https://user-images.githubusercontent.com/2696404/96331738-57d86080-1092-11eb-938c-fbf6ef3575e2.PNG)

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by EmulationFanatic** [comment]
@benderscruffy 

Please do not delete and repost comments in order to generate more bot alerts.

Updated.
