### ISSUE TITLE
Sparkle Unleashed

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#108]
#### Current on `master` :

* Build Version :1.0.1963

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 113
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
```

**Comment by GoffyDude** [comment]
## Sparkle Unleashed

#### Current on `master` : 1.0.3957

Game launches into menus and briefly stays alive during the tutorial, then displays corrupt grahpics and crashes.

```
ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:01:21.741 | HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x0004305c nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   sdk:0x00043114 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, char const*, ...)
   sdk:0x000431a4 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   sdk:0x003c4428 __nnmusl_WaitThread
   main:0x00146228 Sub000000000814a228
   main:0x00155a74 Sub0000000008159a74
   main:0x00182688 Sub0000000008186688
   main:0x00182830 Sub0000000008186830
   sdk:0x000686b4 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000ac Sub00000000080000ac
```

#### Screenshots :
![2020-03-23 10_49_43-Ryujinx 1 0 3957 _ Sparkle Unleashed _ 01000DC007E90000](https://user-images.githubusercontent.com/62343878/77341385-4265a880-6cf4-11ea-87fb-3140b6d2d1b6.png)
![2020-03-23 10_50_10-Ryujinx 1 0 3957 _ Sparkle Unleashed _ 01000DC007E90000](https://user-images.githubusercontent.com/62343878/77341392-45609900-6cf4-11ea-8b08-6edd087ca1fe.png)
![2020-03-23 10_50_27-Ryujinx 1 0 3957 _ Sparkle Unleashed _ 01000DC007E90000](https://user-images.githubusercontent.com/62343878/77341406-4abde380-6cf4-11ea-89c7-b53acfb3b454.png)
![2020-03-23 10_50_34-](https://user-images.githubusercontent.com/62343878/77341448-57423c00-6cf4-11ea-8f9c-c7e561119057.png)

#### Log file :

[SparkleUnleashed.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4370787/SparkleUnleashed.zip)

**Comment by B3astTech** [comment]
Updated thanks

**Comment by EmulationFanatic** [comment]
Updated
