### ISSUE TITLE
WWE 2K18

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1084]
#### Current on `master` : 1.0.4485

Game loads to initial menus and then either deadlocks at the "Press Any Button" to continue screen, or crashes when pressing a button with the error below.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: Unable to delete file C:\Users\<redacted.\AppData\Roaming\Ryujinx\bis\user\save\0000000000000336\1
   at LibHac.FsSystem.LocalFileSystem.EnsureDeleted(FileSystemInfo entry)
   at LibHac.FsSystem.LocalFileSystem.DeleteDirectoryInternal(DirectoryInfo dir, Boolean recursive)
   at LibHac.FsSystem.LocalFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.SynchronizeDirectory(U8Span dest, U8Span src)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.Initialize(Boolean isPersistentSaveData, Boolean isUserSaveData)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.CreateNew(DirectorySaveDataFileSystem& created, IFileSystem baseFileSystem, Boolean isPersistentSaveData, Boolean isUserSaveData)
   at LibHac.FsService.Creators.SaveDataFileSystemCreator.Create(IFileSystem& fileSystem, ISaveDataExtraDataAccessor& extraDataAccessor, IFileSystem sourceFileSystem, UInt64 saveDataId, Boolean allowDirectorySaveData, Boolean useDeviceUniqueMac, SaveDataType type, ITimeStampGenerator timeStampGenerator)
   at LibHac.FsService.FileSystemProxyCore.OpenSaveDataFileSystem(IFileSystem& fileSystem, SaveDataSpaceId spaceId, UInt64 saveDataId, String saveDataRootPath, Boolean openReadOnly, SaveDataType type, Boolean cacheExtraData)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystemImpl(IFileSystem& fileSystem, UInt64& saveDataId, SaveDataSpaceId spaceId, SaveDataAttribute& attribute, Boolean openReadOnly, Boolean cacheExtraData)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystem3(IFileSystem& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute, Boolean openReadOnly)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystem2(IFileSystem& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute, Boolean openReadOnly)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystem(IFileSystem& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute)
   at Ryujinx.HLE.HOS.Services.Fs.IFileSystemProxy.OpenSaveDataFileSystem(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Fs\IFileSystemProxy.cs:line 244
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```
#### Screenshots :
![2020-05-05 06_25_17-Ryujinx 1 0 4485 - WWE 2K18 v1 00 (010009800203E000) (64-bit)](https://user-images.githubusercontent.com/62343878/81066525-7b1fa280-8e9a-11ea-8baa-f77c83b40867.png)
![2020-05-05 06_25_36-Ryujinx 1 0 4485 - WWE 2K18 v1 00 (010009800203E000) (64-bit)](https://user-images.githubusercontent.com/62343878/81066531-7ce96600-8e9a-11ea-8174-3d4d792b8bdc.png)
![2020-05-05 06_25_49-Ryujinx 1 0 4485 - WWE 2K18 v1 00 (010009800203E000) (64-bit)](https://user-images.githubusercontent.com/62343878/81066536-7eb32980-8e9a-11ea-999d-3afbffa74114.png)
![2020-05-05 06_25_58-Ryujinx 1 0 4485 - WWE 2K18 v1 00 (010009800203E000) (64-bit)](https://user-images.githubusercontent.com/62343878/81066554-870b6480-8e9a-11ea-90a7-4f6de8149b8d.png)
![2020-05-05 06_27_39-Ryujinx 1 0 4485 - WWE 2K18 v1 00 (010009800203E000) (64-bit)](https://user-images.githubusercontent.com/62343878/81066587-91c5f980-8e9a-11ea-98ee-dc03da48db13.png)

#### Log file :

[WWE2K18.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4580772/WWE2K18.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Raditya1704** [comment]
Game Update Version : 1.0.4

Current on master : 1.1.1058

Graphics Backend : Vulkan

Crashes after showing some text

Hardware Specs :

CPU: Apple M1

GPU: Apple M1 7 Core
