### ISSUE TITLE
I AM SETSUNA

### ISSUE THREAD

**Issue by frykillr** [Ryujinx/Ryujinx-Games-List#109]
#### Current on `master` : 1.0.1963

Not Booting

```
Unhandled Exception: System.ArgumentException: BlendFactor "0" is not valid!
```

   at Ryujinx.Graphics.Gal.OpenGL.OGLEnumConverter.GetBlendFactor(GalBlendFactor BlendFactor) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLEnumConverter.cs:line 394
   at Ryujinx.Graphics.Gal.OpenGL.OGLPipeline.SetBlendState(Int32 Index, BlendState New, BlendState Old) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLPipeline.cs:line 448
   at Ryujinx.Graphics.Gal.OpenGL.OGLPipeline.Bind(GalPipelineState New) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLPipeline.cs:line 267
   at Ryujinx.Graphics.NvGpuEngine3d.DispatchRender(NvGpuVmm Vmm, GalPipelineState State) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 815
   at Ryujinx.Graphics.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 128
   at Ryujinx.Graphics.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 84
   at Ryujinx.Graphics.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 173
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 120
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

[Setsuna.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/2572417/Setsuna.txt)

**Comment by HorrorTroll** [comment]
Updated

**Comment by frykillr** [comment]
Super BomberMan R haas the same error.

```Unhandled Exception: System.ArgumentException: BlendFactor "0" is not valid!
   at Ryujinx.Graphics.Gal.OpenGL.OGLEnumConverter.GetBlendFactor(GalBlendFactor BlendFactor) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLEnumConverter.cs:line 394
   at Ryujinx.Graphics.Gal.OpenGL.OGLPipeline.SetBlendState(Int32 Index, BlendState New, BlendState Old) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLPipeline.cs:line 448
   at Ryujinx.Graphics.Gal.OpenGL.OGLPipeline.Bind(GalPipelineState New) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLPipeline.cs:line 267
   at Ryujinx.Graphics.NvGpuEngine3d.DispatchRender(NvGpuVmm Vmm, GalPipelineState State) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 815
   at Ryujinx.Graphics.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 128
   at Ryujinx.Graphics.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 84
   at Ryujinx.Graphics.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 173
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 120
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()```

[Bomber.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/2572953/Bomber.txt)

**Comment by gdkchan** [comment]
One issue per game please. Also this is fixed on the PR mentioned here (all unity games will show the same error otherwise).

**Comment by AcK77** [comment]
Need an update.

**Comment by B3astTech** [comment]
Current on angel:

- Build Version : 1.0.3390

The game goes in-game, Plays and renders very well but as soon as you go to save point and save the game softlocks there at that point, But you can bypass the save point and continue playing the game. I have noticed that the animations of the leafs on the trees and the grass that are in motion are really fast compared to how it is on the switch.

**Screenshots:**
![1](https://user-images.githubusercontent.com/45114656/71778294-e2ffc400-2f60-11ea-84bc-ebc1d262f727.png)

![2](https://user-images.githubusercontent.com/45114656/71778296-e8f5a500-2f60-11ea-9fe7-0dfa293d8ec1.png)

![3](https://user-images.githubusercontent.com/45114656/71778299-ebf09580-2f60-11ea-8db6-37a9cbea49b9.png)

![4](https://user-images.githubusercontent.com/45114656/71778302-f1e67680-2f60-11ea-8923-81257b12dab1.png)

![5](https://user-images.githubusercontent.com/45114656/71778309-01fe5600-2f61-11ea-87c4-26891140b664.png)

![6](https://user-images.githubusercontent.com/45114656/71778310-062a7380-2f61-11ea-8c36-479f1cd15cee.png)

![1](https://user-images.githubusercontent.com/45114656/71778537-214ab280-2f64-11ea-9765-aa4f6f1852ff.png)

![2](https://user-images.githubusercontent.com/45114656/71778525-f2344100-2f63-11ea-9342-03222062087e.png)

![3](https://user-images.githubusercontent.com/45114656/71778542-30316500-2f64-11ea-8cb4-df8c1e88269e.png)

![4](https://user-images.githubusercontent.com/45114656/71778545-33c4ec00-2f64-11ea-84f0-8782a5412813.png)

![1](https://user-images.githubusercontent.com/45114656/71778588-b2218e00-2f64-11ea-854e-91abd05b1e97.png)

**Comment by AcK77** [comment]
Updated. Thanks!

**Comment by GoffyDude** [comment]
## I AM SETSUNA.

#### Current on `master` : 1.0.4193

- On first launch the game crashed, while loading splash screens, with no specific error in the log.

- On second launch the game loaded properly and played well. 

- I was able to save the game with no deadlock/softlock as the last review on 1.0.3390 had mentioned as an issue.

- The trees do seem to move too fast and certain objects bounce in place (see GIF below), but other than that the game is fully playable.

#### Screenshots :

![2020-04-14 06_40_47-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79227969-f357f280-7e1d-11ea-996d-09a740f4dace.png)
![2020-04-14 06_44_18-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79227979-f94dd380-7e1d-11ea-9cdb-ed549abef350.png)
![2020-04-14 06_45_26-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228000-023ea500-7e1e-11ea-9044-eab5af4fde67.png)
![2020-04-14 06_46_43-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228022-0a96e000-7e1e-11ea-8917-857446a0965d.png)
![2020-04-14 06_47_14-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228044-12568480-7e1e-11ea-92c6-a7fc329e8556.png)
![2020-04-14 06_48_31-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228075-1b475600-7e1e-11ea-819b-da129a2040b7.png)
![2020-04-14 06_50_57-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228103-24d0be00-7e1e-11ea-9dc6-423b4af29e3f.png)
![2020-04-14 06_51_17-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228125-2dc18f80-7e1e-11ea-8390-f0cf296fa4cd.png)
![2020-04-14 06_51_29-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228159-3ade7e80-7e1e-11ea-92e7-2f345e502162.png)
![2020-04-14 06_51_37-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228185-429e2300-7e1e-11ea-9290-abe7e5978f55.png)
![2020-04-14 06_51_48-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228205-4af65e00-7e1e-11ea-9d4f-193050a84c81.png)
![2020-04-14 06_52_23-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228219-521d6c00-7e1e-11ea-8e03-19eff332e826.png)
![2020-04-14 06_53_15-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228238-59dd1080-7e1e-11ea-8c80-b4ff16a71fec.png)
![2020-04-14 06_53_44-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228255-62354b80-7e1e-11ea-9539-b34df7ceeeae.png)
![2020-04-14 06_54_05-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228284-6e210d80-7e1e-11ea-9ec6-ccf56b2692d0.png)
![2020-04-14 06_55_35-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228326-78430c00-7e1e-11ea-8659-aa8a062f00b2.png)
![2020-04-14 06_55_58-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228327-78430c00-7e1e-11ea-8c9f-3357c7f1d5eb.png)
![2020-04-14 06_58_19-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228342-7da05680-7e1e-11ea-8b63-0bf1c25a4d64.png)
![2020-04-14 06_59_43-Ryujinx 1 0 4193 - I am Setsuna  v1 0 0 (0100849000BDA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79228362-84c76480-7e1e-11ea-8cac-8acd6f52ccbf.png)

#### GIF:
![Objects](https://user-images.githubusercontent.com/62343878/79228399-93ae1700-7e1e-11ea-9714-f07198cd54be.gif)


#### Log file :

[Uploading IAMSETSUNA.zip…]()

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by 64ghost** [comment]
Game Update Version : 1.1.0
Current on master : 1.0.7108

After intro  freeze black screen

[Ryujinx_1.0.7108_2021-11-28_15-00-11.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7613389/Ryujinx_1.0.7108_2021-11-28_15-00-11.log)
