### ISSUE TITLE
Lego City Undercover

### ISSUE THREAD

**Issue by frykillr** [Ryujinx/Ryujinx-Games-List#110]
#### Current on `master` : 1.0.1693

Goes to titlescreen and after starting a save it stay infinitly until crash at loading screen with moving background.

Also game is rendred in top left of the screen.

```
Unhandled Exception: System.NotImplementedException: Per component types are not implemented!```
   at Ryujinx.Graphics.Texture.ImageUtils.ConvertTexture(GalTextureFormat Format, GalTextureType RType, GalTextureType GType, GalTextureType BType, GalTextureType AType, Boolean ConvSrgb) in C:\projects\ryujinx\Ryujinx.Graphics\Texture\ImageUtils.cs:line 155
   at Ryujinx.Graphics.Texture.TextureFactory.GetImageFormat(Int32[] Tic) in C:\projects\ryujinx\Ryujinx.Graphics\Texture\TextureFactory.cs:line 98
   at Ryujinx.Graphics.Texture.TextureFactory.MakeTexture(NvGpuVmm Vmm, Int64 TicPosition) in C:\projects\ryujinx\Ryujinx.Graphics\Texture\TextureFactory.cs:line 15
   at Ryujinx.Graphics.NvGpuEngine3d.UploadTexture(NvGpuVmm Vmm, Int32 TexIndex, Int32 TextureHandle) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 570
   at Ryujinx.Graphics.NvGpuEngine3d.UploadTextures(NvGpuVmm Vmm, GalPipelineState State, Int64[] Keys) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 545
   at Ryujinx.Graphics.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 123
   at Ryujinx.Graphics.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 84
   at Ryujinx.Graphics.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 173
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 120
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[lego.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/2572853/lego.txt)
![lego city top left rendering only](https://user-images.githubusercontent.com/7881098/48363252-81e9a280-e673-11e8-9fe1-dc09da5b4506.PNG)

**Comment by gdkchan** [comment]
Please follow the correct formatting for the issue.

**Comment by AcK77** [comment]
Need an update.

**Comment by GoffyDude** [comment]
## Lego City Undercover

#### Current on `master` : 1.0.3937

Never loads. Continually outputs error seen below every 20 seconds.

```
HLE.HostThread.0 KernelSvc PrintResult: SetHeapSize64 returned error ResLimitExceeded.
```

#### Log file :

[LegoCityUndercover.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4362113/LegoCityUndercover.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by notliam1** [comment]
Game faces insane stuttering when camera pans too quickly still, would remove playable and would replace it with ingame,
spces are i9-12900k, 3090, 32GB ram.

**Comment by berturion** [comment]
I agree, I have a radeon 6700 XT, Ryzen 5800X, 32GB of RAM.
It stutters a lot, I stopped playing this game in Ryujinx because of that.
"Ingame" is more appropriate I think.
