### ISSUE TITLE
Zombillie

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1107]
#### Current on `master` : 1.0.4507

Crashes as you are starting a level.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32 width, Int32 height, Int32 depth, Int32 levels, Int32 layers, Int32 blockWidth, Int32 blockHeight, Int32 bytesPerPixel, Int32 gobBlocksInY, Int32 gobBlocksInZ, Int32 gobBlocksInTileX, SizeInfo sizeInfo, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.Texture\LayoutConverter.cs:line 233
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 479
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 330
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(RtColorState colorState, Int32 samplesInX, Int32 samplesInY) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 398
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateRenderTargetState(GpuState state, Boolean useControl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 326
   at Ryujinx.Graphics.Gpu.Engine.Methods.Clear(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodClear.cs:line 16
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 498
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 97
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-05-07 07_48_25-Ryujinx 1 0 4507 - Zombillie v1 0 0 (0100CD300A1BA000) (64-bit)](https://user-images.githubusercontent.com/62343878/81302279-63c9ec00-9037-11ea-9f4a-e43e5a641e92.png)
![2020-05-07 07_48_44-Ryujinx 1 0 4507 - Zombillie v1 0 0 (0100CD300A1BA000) (64-bit)](https://user-images.githubusercontent.com/62343878/81302282-64fb1900-9037-11ea-9c6a-42413d888be9.png)
![2020-05-07 07_48_59-Ryujinx 1 0 4507 - Zombillie v1 0 0 (0100CD300A1BA000) (64-bit)](https://user-images.githubusercontent.com/62343878/81302301-6e848100-9037-11ea-92ca-4f4620c0f919.png)
![2020-05-07 07_49_04-Ryujinx 1 0 4507 - Zombillie v1 0 0 (0100CD300A1BA000) (64-bit)](https://user-images.githubusercontent.com/62343878/81302327-77755280-9037-11ea-92fd-8bd6ce28e56e.png)
![2020-05-07 07_49_14-Ryujinx 1 0 4507 - Zombillie v1 0 0 (0100CD300A1BA000) (64-bit)](https://user-images.githubusercontent.com/62343878/81302341-7fcd8d80-9037-11ea-9268-10cd431cc35e.png)
![2020-05-07 07_49_19-Ryujinx 1 0 4507 - Zombillie v1 0 0 (0100CD300A1BA000) (64-bit)](https://user-images.githubusercontent.com/62343878/81302377-86f49b80-9037-11ea-8d51-3a6af8ed3b40.png)

#### Log file :

[Zombillie.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4593324/Zombillie.zip)

**Comment by EmulationFanatic** [comment]
Updated
