### ISSUE TITLE
Mega Man X

### ISSUE THREAD

**Issue by frykillr** [Ryujinx/Ryujinx-Games-List#111]
#### Current on `master` : 1.0.1963

* Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*

Doesn't boot.

```
Unhandled Exception: System.NotImplementedException: irs IIrSensorServer: 311
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx Context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 83
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch Ns, Process Process, MemoryManager Memory, KSession Session, IpcMessage Request, Int64 CmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 33
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.ProcessIpcRequest(Object State) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


```

#### Log file :
[MMX.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/2573053/MMX.txt)

**Comment by HorrorTroll** [comment]
Updated

**Comment by AcK77** [comment]
Need an update.

**Comment by GoffyDude** [comment]
## Mega Man X Legacy Collection

#### Current on `master` : 1.0.3937

Game crashes on launch because of 
https://github.com/Ryujinx/Ryujinx/issues/648

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Controller applet is not implemented.
```

#### Outstanding Issues:
https://github.com/Ryujinx/Ryujinx/issues/648


#### Log file :

[MMXLC.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4361372/MMXLC.zip)

**Comment by B3astTech** [comment]
Need's Updated

**Comment by benderscruffy** [comment]
using 1.0.5942
doesnt crash out anymore when using in-game menus to exit a game (- button and follow menu options)
only errors i see in log now is
HLE.HostThread.4 AudioRenderer Update: Unmap of memory pool (address: 0x101cb91000, size 0x5a000) failed!
HLE.HostThread.4 AudioRenderer Update: Unmap of memory pool (address: 0x101f217000, size 0x2000) failed!
[Ryujinx_2020-12-04_12-16-15.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5640603/Ryujinx_2020-12-04_12-16-15.zip)
