### ISSUE TITLE
Super Bomberman R

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#112]
```Unhandled Exception: System.ArgumentException: BlendFactor "0" is not valid!
   at Ryujinx.Graphics.Gal.OpenGL.OGLEnumConverter.GetBlendFactor(GalBlendFactor BlendFactor) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLEnumConverter.cs:line 394
   at Ryujinx.Graphics.Gal.OpenGL.OGLPipeline.SetBlendState(Int32 Index, BlendState New, BlendState Old) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLPipeline.cs:line 448
   at Ryujinx.Graphics.Gal.OpenGL.OGLPipeline.Bind(GalPipelineState New) in C:\projects\ryujinx\Ryujinx.Graphics\Gal\OpenGL\OGLPipeline.cs:line 267
   at Ryujinx.Graphics.NvGpuEngine3d.DispatchRender(NvGpuVmm Vmm, GalPipelineState State) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 815
   at Ryujinx.Graphics.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 128
   at Ryujinx.Graphics.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 84
   at Ryujinx.Graphics.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 173
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 120
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()```

### Log
[Bomber.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/2572953/Bomber.txt)

Originally posted by @frykillr

**Comment by AcK77** [comment]
Need an update.

**Comment by GoffyDude** [comment]
## Super Bomberman R

#### Current on `master` : 1.0.3937

Game loads through menus but crashes after selecting battle mode. 
On 2nd try I tried Story mode, which  launches but loads a black screen, and then crashes after the cutscene audio/subtitles. Skipping has the same outcome.

Selecting Battle mode:
```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Error applet is not implemented.
```
Selecting Story Mode:
```Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.HLE.HOS.Services.Nv.Types.NvIoctlNotImplementedException: The ioctl is not implemented.

Device File: NvHostCtrlDeviceFile
```


#### Screenshots :
![2020-03-20 10_13_41-Ryujinx 1 0 3937 _ SUPER BOMBERMAN R _ 01007AD00013E000](https://user-images.githubusercontent.com/62343878/77184970-354b7e00-6a96-11ea-94b9-e95fe031c490.png)
![2020-03-20 10_14_03-Ryujinx 1 0 3937 _ SUPER BOMBERMAN R _ 01007AD00013E000](https://user-images.githubusercontent.com/62343878/77184979-39779b80-6a96-11ea-8b3a-2c5a44c085e9.png)
![2020-03-20 10_16_10-Ryujinx 1 0 3937 _ SUPER BOMBERMAN R _ 01007AD00013E000](https://user-images.githubusercontent.com/62343878/77185001-43010380-6a96-11ea-93ba-ef6a2490b749.png)
![2020-03-20 10_16_22-Ryujinx 1 0 3937 _ SUPER BOMBERMAN R _ 01007AD00013E000](https://user-images.githubusercontent.com/62343878/77185010-45635d80-6a96-11ea-94d7-02bb09cc8251.png)
![2020-03-20 10_16_27-Ryujinx 1 0 3937 _ SUPER BOMBERMAN R _ 01007AD00013E000](https://user-images.githubusercontent.com/62343878/77185014-46948a80-6a96-11ea-8eb6-b164c37a561e.png)
![2020-03-20 10_16_32-Ryujinx 1 0 3937 _ SUPER BOMBERMAN R _ 01007AD00013E000](https://user-images.githubusercontent.com/62343878/77185016-472d2100-6a96-11ea-9f85-914023862823.png)
![2020-03-20 10_16_47-Ryujinx 1 0 3937 _ SUPER BOMBERMAN R _ 01007AD00013E000](https://user-images.githubusercontent.com/62343878/77185023-48f6e480-6a96-11ea-992a-fcdf6148edfa.png)
![2020-03-20 10_30_40-Ryujinx 1 0 3937 _ SUPER BOMBERMAN R _ 01007AD00013E000](https://user-images.githubusercontent.com/62343878/77185029-4b593e80-6a96-11ea-873f-03399e056ed9.png)


#### Log file :
[SuperBombermanR.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4360737/SuperBombermanR.zip)
[SuperBombermanR2ndTry.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4360764/SuperBombermanR2ndTry.zip)

**Comment by GoffyDude** [comment]
## Super Bomberman R

#### Current on `master` : 1.0.4383

- Game now is able to be played at a high FPS in Story Mode.
- Cutscenes are black screen (nvdec)
- Battle mode still crashes with unimplemented error applet.


#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/632

#### Screenshots :

![2020-04-30 14_53_50-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760153-b1a19a00-8af5-11ea-9f40-e02404132c6a.png)
![2020-04-30 14_54_00-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760158-b36b5d80-8af5-11ea-9702-da358f284140.png)
![2020-04-30 14_54_09-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760164-b5352100-8af5-11ea-8f0f-fb0c204460e6.png)
![2020-04-30 14_54_26-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760173-b7977b00-8af5-11ea-930f-091e32711302.png)
![2020-04-30 14_54_42-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760178-b8c8a800-8af5-11ea-81b4-1f1694af53e7.png)
![2020-04-30 14_59_17-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760186-bb2b0200-8af5-11ea-883b-c7275fdee33b.png)
![2020-04-30 15_00_03-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760194-bf571f80-8af5-11ea-888e-baeddfbfbca7.png)
![2020-04-30 15_00_23-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760196-bfefb600-8af5-11ea-961f-639edf1fb162.png)
![2020-04-30 15_00_28-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760207-c2eaa680-8af5-11ea-88a6-04adcf4ca29c.png)
![2020-04-30 15_00_51-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760220-cc740e80-8af5-11ea-88c0-c2a98f0b8159.png)
![2020-04-30 15_01_23-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760231-d3028600-8af5-11ea-95e0-9b299a28873c.png)
![2020-04-30 15_01_29-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760242-d7c73a00-8af5-11ea-9bfa-0517c2feb2fc.png)
![2020-04-30 15_02_00-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760278-e1e93880-8af5-11ea-8810-9df33c26179f.png)
![2020-04-30 15_02_05-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760317-ee6d9100-8af5-11ea-8151-4d95e234b27e.png)
![2020-04-30 15_02_15-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760352-fcbbad00-8af5-11ea-9738-17a20bfffa2b.png)
![2020-04-30 15_03_53-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760373-09400580-8af6-11ea-8d59-204711af5b62.png)
![2020-04-30 15_04_11-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760399-13fa9a80-8af6-11ea-8c0a-500584177a80.png)
![2020-04-30 15_04_37-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760421-1d840280-8af6-11ea-8920-d90b196251b1.png)
![2020-04-30 15_05_40-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760451-2bd21e80-8af6-11ea-908b-8614758ce6b0.png)
![2020-04-30 15_05_44-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760495-3be9fe00-8af6-11ea-98fa-f47ded7c2745.png)
![2020-04-30 15_08_35-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760520-45736600-8af6-11ea-87a4-75ad14d2eeec.png)
![2020-04-30 15_08_43-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760558-515f2800-8af6-11ea-8f20-0dd18a228846.png)
![2020-04-30 15_11_38-Ryujinx 1 0 4383 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/80760588-5c19bd00-8af6-11ea-83c1-65c94210a9df.png)


#### Log file :

[SuperBombermanR.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4561395/SuperBombermanR.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by GoffyDude** [comment]
Needs update

**Comment by EmulationFanatic** [comment]
## Super Bomberman R

#### Current on `master` : 1.0.4675

- Cutscenes have nvdec issue
- Story Mode plays beautifully
- Battle Mode still crashes with the new error below.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Error applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Applets\AppletManager.cs:line 32
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\SystemAppletProxy\ILibraryAppletCreator.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Screenshots :

![2020-06-04 05_29_40-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83751990-02407180-a625-11ea-9422-38598b78442c.png)
![2020-06-04 05_31_02-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83751993-02d90800-a625-11ea-929b-077cacd645c5.png)
![2020-06-04 05_31_06-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83751996-040a3500-a625-11ea-8710-ca5bda9c2332.png)
![2020-06-04 05_31_17-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83752000-05d3f880-a625-11ea-9cc8-e8b6287fc064.png)
![2020-06-04 05_31_24-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83752005-079dbc00-a625-11ea-9cfd-662b0d010280.png)
![2020-06-04 05_31_49-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83752008-09677f80-a625-11ea-87ac-cc9efafa4b98.png)
![2020-06-04 05_37_00-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83752605-091bb400-a626-11ea-862d-7d2ad14d1946.png)
![2020-06-04 05_37_14-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83752609-0c16a480-a626-11ea-8ca2-6aa34983a838.png)
![2020-06-04 05_38_08-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83752621-1173ef00-a626-11ea-9767-ad54aa1f4e20.png)
![2020-06-04 05_38_10-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83752643-1a64c080-a626-11ea-81d1-99882a14f850.png)
![2020-06-04 05_39_14-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83752662-2486bf00-a626-11ea-99df-9d7a66821d11.png)
![2020-06-04 05_39_16-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83752693-2f415400-a626-11ea-9bd5-a68e737c7efe.png)
![2020-06-04 05_41_04-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83752718-3a947f80-a626-11ea-8b9e-082527498359.png)
![2020-06-04 05_41_12-Ryujinx 1 0 4675 - SUPER BOMBERMAN R v1 4 2 (01007AD00013E000) (64-bit)](https://user-images.githubusercontent.com/62343878/83752747-441de780-a626-11ea-98ff-549ba8e747ac.png)

#### Log file :

[SBR.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4729657/SBR.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
