### ISSUE TITLE
Megaman 11

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#113]
Unhandled Exception: System.NotImplementedException: irs IIrSensorServer: 311
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx Context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 83
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch Ns, Process Process, MemoryManager Memory, KSession Session, IpcMessage Request, Int64 CmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 33
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.ProcessIpcRequest(Object State) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---

_Originally posted by @frykillr in https://github.com/Ryujinx/Ryujinx-Games-List/issues/89#issuecomment-437966040_

**Comment by HorrorTroll** [comment]
Updated

**Comment by AcK77** [comment]
Need an update.

**Comment by GoffyDude** [comment]
## Mega Man 11

#### Current on `master` : 1.0.3937

Loads flawless cutscene, then choppy audio at title screen. Graphics in next cutscene are good, except for a particularly disturbing glitch that removes Roll's eyes and Mega Man's face, then his eyes (see screenshots). 
Cutscenes seem to have issues sometimes not rendering graphics.
Playable otherwise.

#### Screenshots :

![2020-03-20 12_50_31-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197725-4f438b80-6aab-11ea-85f1-fbcfcb083fca.png)
![2020-03-20 12_50_59-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197739-52d71280-6aab-11ea-9595-b4e7d3ee63b5.png)
![2020-03-20 12_51_25-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197744-55396c80-6aab-11ea-93a1-7b7f8c94a4c3.png)
![2020-03-20 12_51_47-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197752-579bc680-6aab-11ea-9ce4-e1b8bea5f821.png)
![2020-03-20 12_52_02-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197756-58ccf380-6aab-11ea-8766-42ee4024ce00.png)
![2020-03-20 12_53_25-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197763-59fe2080-6aab-11ea-9736-26f6e3d46f97.png)
![2020-03-20 12_53_33-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197767-5a96b700-6aab-11ea-9bbb-f976c79f8a99.png)
![2020-03-20 12_54_44-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197773-5cf91100-6aab-11ea-97fe-336d4dcce07b.png)
![2020-03-20 12_54_59-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197779-5f5b6b00-6aab-11ea-986f-3a3af4dcce20.png)
![2020-03-20 12_58_42-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197787-61252e80-6aab-11ea-939d-ff08c2834765.png)
![2020-03-20 12_59_03-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197796-64b8b580-6aab-11ea-8d9d-3af0f72330e3.png)
![2020-03-20 12_59_16-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197801-66827900-6aab-11ea-8c08-00b8e6108ca5.png)
![2020-03-20 12_59_41-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197799-65e9e280-6aab-11ea-8f23-2e85c41cddb5.png)
![2020-03-20 12_59_51-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197802-67b3a600-6aab-11ea-83e1-c7d2004f592e.png)
![2020-03-20 13_01_39-Ryujinx 1 0 3937 _ Mega Man 11 _ 0100B0C0086B0000](https://user-images.githubusercontent.com/62343878/77197808-6aae9680-6aab-11ea-82a0-3690d9d8eb9a.png)


#### Log file :

[MM11.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4361430/MM11.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
