### ISSUE TITLE
NAMCO MUSEUM ARCADE PAC

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1133]
#### Current on `master` : 1.0.4532

- Loads and allows selection of embedded games, though the embedded arcade games have clipping and graphical oddities that prevent them from being playable. 
- Game crashes when exiting Pac-Man Championship Edition 2 to go back to the title screen.

```
HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000dcf7000 
(opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 128
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 98
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-05-09 05_18_27-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472718-2e4c0c80-91b7-11ea-9e20-3dcc4da8bbd9.png)
![2020-05-09 05_20_54-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472720-2ee4a300-91b7-11ea-8dab-d00df80c9ea6.png)
![2020-05-09 05_22_47-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472721-30ae6680-91b7-11ea-82be-51a2d756fbc8.png)
![2020-05-09 05_24_55-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472723-32782a00-91b7-11ea-83d6-a084c8228eaa.png)
![2020-05-09 05_25_34-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472724-373cde00-91b7-11ea-9fbb-848f79bdeb67.png)
![2020-05-09 05_25_44-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472727-3dcb5580-91b7-11ea-96e0-b4a4dad5c0ad.png)
![2020-05-09 05_26_12-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472735-46239080-91b7-11ea-8915-8196f650ff13.png)
![2020-05-09 05_26_21-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472741-4885ea80-91b7-11ea-8ab1-b767f3893ffb.png)
![2020-05-09 05_26_56-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472749-4b80db00-91b7-11ea-8dfc-6ac885235583.png)
![2020-05-09 05_27_27-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472753-4e7bcb80-91b7-11ea-8a53-503c3e0e4ece.png)
![2020-05-09 05_27_47-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472755-520f5280-91b7-11ea-9406-2a19ea84db5b.png)
![2020-05-09 05_32_17-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472759-550a4300-91b7-11ea-82b6-351f139e5995.png)
![2020-05-09 05_33_03-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472782-59cef700-91b7-11ea-80b6-704c18771588.png)
![2020-05-09 05_33_09-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472793-62bfc880-91b7-11ea-99ed-719db822fdd1.png)
![2020-05-09 05_33_47-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472796-694e4000-91b7-11ea-80be-293c5f5a3543.png)
![2020-05-09 05_34_11-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472800-6f442100-91b7-11ea-85c6-5061ac1510ce.png)
![2020-05-09 05_34_23-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472801-6fdcb780-91b7-11ea-86be-33f772f9b5e0.png)
![2020-05-09 05_35_13-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472803-710de480-91b7-11ea-8d40-a7337e07af25.png)
![2020-05-09 05_35_38-Ryujinx 1 0 4532 - NAMCO MUSEUM ARCADE PAC v1 0 0 (0100DAA00AEE6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81472808-79661f80-91b7-11ea-9290-b30f74688e21.png)

#### Log file :

[NMAP.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4603380/NMAP.zip)

**Comment by EmulationFanatic** [comment]
Updated
