### ISSUE TITLE
Pokémon: Let's Go, Eevee!

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#115]
#### Current on `master` :

* Build Version : 1.0.1977

```
00:00:06.358 | 0010 ServiceAm SetTerminateResult: Result = 0x0000f001 (2001-0120).
00:00:06.392 | 0010 Cpu PrintStackTrace: Guest stack trace:
 sdk:0x0004c780 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
 sdk:0x0004c844 Sub000000000b458844
 sdk:0x000aa2ec Sub000000000b4b62ec
 main:0x000048bc nnMain
 sdk:0x000849bc nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
 rtld:0x000000ac Sub00000000080000ac

Unhandled Exception: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.SvcBreak(CpuThreadState ThreadState) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 254
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SvcHandler.cs:line 116
   at Sub000000000b4e589c(CpuThreadState , MemoryManager )
   at ChocolArm64.Translator.ExecuteSubroutineA64(CpuThreadState state, MemoryManager memory, Int64 position) in C:\projects\ryujinx\ChocolArm64\Translator.cs:line 69
   at ChocolArm64.CpuThread.<>c__DisplayClass14_0.<.ctor>b__0() in C:\projects\ryujinx\ChocolArm64\CpuThread.cs:line 36
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

Fix that, and then crash:
```
Unhandled Exception: System.NotImplementedException: vi:m IApplicationDisplayService: 2102
```
https://reswitched.github.io/SwIPC/ifaces.html#nn::visrv::sf::IApplicationDisplayService(2102)

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: hid IHidServer: 525
```
https://reswitched.github.io/SwIPC/ifaces.html#nn::hid::IHidServer(525)

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: hwopus
```

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: hwopus IHardwareOpusDecoder: 4
```
https://switchbrew.org/wiki/Audio_services#DecodeInterleavedWithPerfOld

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: bt
```
https://reswitched.github.io/SwIPC/ifaces.html#nn::bluetooth::IBluetoothDriver

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: btm
```
https://reswitched.github.io/SwIPC/ifaces.html#nn::btm::IBtm

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: btm:u
```
https://switchbrew.org/wiki/BTM_services#btm:u

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: btm:u IBtm(Unknown): 0
```
*Because btm:u is not document yet, so i say at unknown!*

Bypass that, and then crash:
```
00:00:37.396 | 0008 ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:00:37.833 | 0008 Cpu PrintGuestStackTrace: Guest stack trace:
 [Application] sdk:0x0004c77c nn::diag::detail::VAbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, std::__va_list)
 [Application] sdk:0x0004c840 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, char const*, ...)
 [Application] sdk:0x0004c8dc nn::diag::detail::AbortImpl(char const*, char const*, char const*, int)
 [Application] sdk:0x00254814 nn::btm::user::AcquireBleScanEvent(nn::os::SystemEventType*)
 [Application] main:0x00113a08 Sub0000000008117a08
 [Application] main:0x00344374 Sub0000000008348374
 [Application] main:0x003441b4 Sub00000000083481b4
 [Application] main:0x0000610c Sub000000000800a10c
 [Application] main:0x00039318 Sub000000000803d318
 [Application] main:0x000048fc nnMain
 [Application] sdk:0x000849b8 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
 [Application] rtld:0x000000a8 Sub00000000080000a8

Unhandled Exception: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.SvcBreak(CpuThreadState ThreadState) in D:\Games\Ryujinx-Kernel\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 263
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.SvcCall(Object sender, InstExceptionEventArgs e) in D:\Games\Ryujinx-Kernel\Ryujinx.HLE\HOS\Kernel\SvcHandler.cs:line 114
   at Sub000000000b4e089c(CpuThreadState , MemoryManager )
   at ChocolArm64.Translator.ExecuteSubroutineA64(CpuThreadState state, MemoryManager memory, Int64 position) in D:\Games\Ryujinx-Kernel\ChocolArm64\Translator.cs:line 69
   at ChocolArm64.CpuThread.<>c__DisplayClass14_0.<.ctor>b__0() in D:\Games\Ryujinx-Kernel\ChocolArm64\CpuThread.cs:line 36
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```
#### Pull requests needed :

https://github.com/Ryujinx/Ryujinx/pull/201
https://github.com/Ryujinx/Ryujinx/pull/491

**Comment by gdkchan** [comment]
Updated with lastest test results.

**Comment by ogniK5377** [comment]
For reference, yuzu is getting the same issues so I'm sticking this here to be consistent with information and a reference to check what has/hasn't been tried yet

https://github.com/yuzu-emu/yuzu/issues/1715

**Comment by gdkchan** [comment]
Already fixed (https://github.com/Ryujinx/Ryujinx/pull/201#issuecomment-439581151).

**Comment by ogniK5377** [comment]
Good catch!

**Comment by jduncanator** [comment]
Updated to reflect current status in master.

**Comment by HorrorTroll** [comment]
Updated to current status in master.

**Comment by HorrorTroll** [comment]
Updated

**Comment by HorrorTroll** [comment]
Updated!

**Comment by CNamor** [comment]
For me the game crashes and the last thing on the logs is that the nps is loading. Any clues? @HorrorTroll

**Comment by B3astTech** [comment]
Need's Updated - It's [Opposite](https://github.com/Ryujinx/Ryujinx-Games-List/issues/327) Has seen a pretty big diffrence

**Comment by GoffyDude** [comment]
## Pokémon: Let's Go, Eevee!

#### Current on `master` : 1.0.3957

Intro cutscene is black with choppy audio and cannot be skipped, but does eventually land at the language selection screen. 
Right after the language selection screen, the welcome intro is missing graphical effect and animation seems too fast.
Once in-game, while indoors, animation is too fast: probably about twice as fast as it should be. Outdoors, speed seems accurate.
FPS stays quite low for the most part, but is playable.


#### Screenshots :

![2020-03-23 06_33_04-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319241-15a19900-6cd4-11ea-995a-ec8694c0bb86.png)
![2020-03-23 06_33_12-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319248-19cdb680-6cd4-11ea-9902-d6416f010443.png)
![2020-03-23 06_33_18-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319253-1d613d80-6cd4-11ea-8509-5f096d7bfa13.png)
![2020-03-23 06_35_08-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319256-1df9d400-6cd4-11ea-8242-e6bcae2400a8.png)
![2020-03-23 06_35_45-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319262-1fc39780-6cd4-11ea-9a74-97df6daf20d1.png)
![2020-03-23 06_35_47-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319273-24884b80-6cd4-11ea-9631-20fe51400c5e.png)
![2020-03-23 06_37_19-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319281-281bd280-6cd4-11ea-9949-def068efea50.png)
![2020-03-23 06_37_48-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319289-2e11b380-6cd4-11ea-83e2-08fcb2679f41.png)
![2020-03-23 06_38_09-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319295-34a02b00-6cd4-11ea-967b-2ddbbccc0d10.png)
![2020-03-23 06_38_20-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319311-3c5fcf80-6cd4-11ea-9264-86f0481bb6bc.png)
![2020-03-23 06_40_26-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319319-4386dd80-6cd4-11ea-8a62-022a2b32735d.png)
![2020-03-23 06_41_15-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319338-4bdf1880-6cd4-11ea-91d3-625091200d20.png)
![2020-03-23 06_44_49-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319359-54cfea00-6cd4-11ea-9c8d-676d1045ce6e.png)
![2020-03-23 06_56_50-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319387-5e595200-6cd4-11ea-9360-c1d1f71e4f97.png)
![2020-03-23 06_58_35-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319410-67e2ba00-6cd4-11ea-9244-5f9fc39e8292.png)
![2020-03-23 06_58_37-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319425-703af500-6cd4-11ea-8282-65c1309237e7.png)
![2020-03-23 06_59_02-Ryujinx 1 0 3957 _ Pokémon_ Let's Go, Eevee! _ 0100187003A36000](https://user-images.githubusercontent.com/62343878/77319452-78933000-6cd4-11ea-89da-2405df453289.png)


#### Log file :

[PLGE.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4369459/PLGE.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by Kevaoon** [comment]
Hey, I just downloaded Lets go Eevee but cant seem to get past the 'Press a button on the controller you want to use' screen. I tried pressing every button on my xbox controller and my keyboard but nothing seems to work. Do you have any advice to get past this? Thanks.

**Comment by AcK77** [comment]
This is for games compatibility!
If you needs support please goes to our discord server. Thanks.

**Comment by Kevaoon** [comment]
Oh sorry! I'm new to all this, may I ask where your discord server link is?

**Comment by AcK77** [comment]
https://discord.gg/N2FmfVc

**Comment by Somiraina** [comment]
I can't find the option "browse" when I want to add game

**Comment by Koori-ux** [comment]
Игра вылетает когда надо вести имя, как можно решить эту проблему?

**Comment by Koori-ux** [comment]
Подскажите как исправить ошибку, когда эмулятор вылетает при вводе имени, а уже потом удаляйте, пожалуйста...

**Comment by Thog** [comment]
@Koori-ux If you need support, thanks to join our [discord](https://discord.gg/N2FmfVc) and ask your question over there in English please.
This issue is for tracking of confirmed bugs.

**Comment by r3dsi9n** [comment]
how ldn works on this?

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Swaaam22** [comment]
Unfortunately, Ryujinx does not support handheld mode. I would be happy if this was added in a future update
