### ISSUE TITLE
Leisure Suit Larry: Wet Dreams Don't Dry

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1156]
#### Current on `master` : 1.0.4536

Crashes in cutscenes after initiating a game.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32 width, Int32 height, Int32 depth, Int32 levels, Int32 layers, Int32 blockWidth, Int32 blockHeight, Int32 bytesPerPixel, Int32 gobBlocksInY, Int32 gobBlocksInZ, Int32 gobBlocksInTileX, SizeInfo sizeInfo, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.Texture\LayoutConverter.cs:line 233
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 479
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 330
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(RtColorState colorState, Int32 samplesInX, Int32 samplesInY) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 398
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateRenderTargetState(GpuState state, Boolean useControl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 326
   at Ryujinx.Graphics.Gpu.Engine.Methods.Clear(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodClear.cs:line 16
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 498
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 97
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
#### Screenshots :

![2020-05-11 13_49_17-Ryujinx 1 0 4536 - Leisure Suit Larry - Wet Dreams Don't Dry v1 0 0 (0100A8E00CA](https://user-images.githubusercontent.com/62343878/81605655-07e0c980-938f-11ea-8da6-10b8c4be1343.png)
![2020-05-11 13_49_47-Ryujinx 1 0 4536 - Leisure Suit Larry - Wet Dreams Don't Dry v1 0 0 (0100A8E00CA](https://user-images.githubusercontent.com/62343878/81605669-0ca57d80-938f-11ea-8531-467399eac97f.png)
![2020-05-11 13_51_25-Ryujinx 1 0 4536 - Leisure Suit Larry - Wet Dreams Don't Dry v1 0 0 (0100A8E00CA](https://user-images.githubusercontent.com/62343878/81605680-10d19b00-938f-11ea-956c-ba973366f2c4.png)

#### Log file :

[LSLWDDD.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4611781/LSLWDDD.zip)

**Comment by SeraUX** [comment]
## Leisure Suit Larry: Wet Dreams Don't Dry

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.5003

Goes ingame, and crashes during gameplay.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Ryujinx.Graphics.Texture.LayoutConverter.<ConvertLinearToBlockLinear>g__Convert|5_0[[System.UInt64, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Span`1<Byte>, System.ReadOnlySpan`1<Byte>, <>c__DisplayClass5_0 ByRef, <>c__DisplayClass5_1 ByRef, <>c__DisplayClass5_2 ByRef)
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Ryujinx.Graphics.Texture.SizeInfo, System.ReadOnlySpan`1<Byte>)
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu()
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory()
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(Ryujinx.Graphics.Gpu.Image.TextureInfo, Ryujinx.Graphics.Gpu.Image.TextureSearchFlags)
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(Ryujinx.Graphics.Gpu.State.CopyTexture, Boolean)
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyTexture(Ryujinx.Graphics.Gpu.State.GpuState, Int32)
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(Ryujinx.Graphics.MethodParams, Ryujinx.Graphics.Gpu.ShadowRamControl)
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(Ryujinx.Graphics.MethodParams)
   at Ryujinx.Graphics.Gpu.DmaPusher.Step()
   at Ryujinx.Ui.GlRenderer.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs : 

##### CPU: i3-7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Screenshots :

![Screenshot at 2020-07-23 19-50-13](https://user-images.githubusercontent.com/62521228/88321497-92469180-cd1f-11ea-824c-1c3c6b5d9363.png)
![Screenshot at 2020-07-23 19-50-34](https://user-images.githubusercontent.com/62521228/88321504-94105500-cd1f-11ea-98c2-bab8e77bf324.png)
![Screenshot at 2020-07-23 19-51-31](https://user-images.githubusercontent.com/62521228/88321508-95418200-cd1f-11ea-8fe8-ea249575f7c9.png)
![Screenshot at 2020-07-23 19-52-47](https://user-images.githubusercontent.com/62521228/88321514-970b4580-cd1f-11ea-88af-5bf9e308c440.png)
![Screenshot at 2020-07-23 19-54-27](https://user-images.githubusercontent.com/62521228/88321515-983c7280-cd1f-11ea-84cf-cf73366b3d2e.png)

#### Log file :

[leisure-suite-larry.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4967952/leisure-suite-larry.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
