### ISSUE TITLE
L.A. Noire

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1180]
#### Current on `master` : 1.0.4544

Loads through initial menus slowly and then crashes.
May need a savefile and possibly udpated version of the game at this time, according to some reports on Discord.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.Gpu.NvGpuFifo.SendMacroCodeData(Int32 index, Int32 data) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 155
   at Ryujinx.Graphics.Gpu.Engine.Methods.SendMacroCodeData(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodFifo.cs:line 32
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-05-12 15_45_14-Ryujinx 1 0 4544 - L A  Noire v1 0 (0100830004FB6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81749886-b6f1d380-9469-11ea-8bfd-beb7e137ed64.png)
![2020-05-12 15_45_48-Ryujinx 1 0 4544 - L A  Noire v1 0 (0100830004FB6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81749898-ba855a80-9469-11ea-9456-1aca3ce8083c.png)
![2020-05-12 15_47_22-Ryujinx 1 0 4544 - L A  Noire v1 0 (0100830004FB6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81749900-bb1df100-9469-11ea-8861-d0b4d8d0255f.png)
![2020-05-12 15_50_51-Ryujinx 1 0 4544 - L A  Noire v1 0 (0100830004FB6000) (64-bit)](https://user-images.githubusercontent.com/62343878/81749906-c07b3b80-9469-11ea-8e59-581ff236f848.png)

#### Log file :

[LANoire.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4618659/LANoire.zip)

**Comment by Thog** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
