### ISSUE TITLE
GOD EATER 3

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1197]
#### Current on `master` : 1.0.4548

Crashes on launch.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Vi.RootService.IApplicationDisplayService: 2460

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00398d60 nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 0l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l> >, 16ul, 16ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 0l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<8ul, 8ul>, nn::sf::cmif::client::OutRawClientArgumentType<8ul, 8ul>, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, unsigned int)
   sdk:0x00394864 nn::sf::cmif::client::detail::CmifProxyImpl<nn::visrv::sf::IApplicationDisplayService, nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6>, nn::sf::MemoryResourceAllocationPolicy, nn::visrv::sf::IApplicationDisplayService>::_nn_sf_sync_GetIndirectLayerImageRequiredMemoryInfo(nn::sf::Out<long, void>, nn::sf::Out<long, void>, long, long)
   sdk:0x0039cee0 nn::vi::GetIndirectImageMemoryRequirement(unsigned long*, unsigned long*, int, int)
   sdk:0x00374a6c nn::swkbd::detail::InlineKeyboardImpl::GetImageMemoryRequirement(unsigned long*, unsigned long*)
   main:0x00de5324 Sub0000000008de9324
   main:0x00e4195c Sub0000000008e4595c
   main:0x00e4d67c Sub0000000008e5167c
   main:0x00e4d830 Sub0000000008e51830
   main:0x00e4d830 Sub0000000008e51830
   main:0x00d85678 Sub0000000008d89678
   main:0x00d8d07c Sub0000000008d9107c
   main:0x00e8f964 Sub0000000008e93964
   sdk:0x0031d4d8 Sub00000000130c34d8
   sdk:0x00321938 Sub00000000130c7938
   ??? Sub0000000000000000

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  9C 09 00 00 00 00 00 00   SFCI···········
00000010   00 05 00 00 00 00 00 00  D0 02 00 00 00 00 00 00   ········Ð·······
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```
#### Log file :

[GodEater3.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4625136/GodEater3.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by cybercjt** [comment]
I've tested this game.
Graphical bugs aside I encountered a minor bug on character creation section.
Under "Codename"  (which is your in-game name) if you try to input something it defaults to "Ryujinx" and  the Software Keyboard never pops up, you can't change it no matter what.
While "Name" is completely fine and the Software Keyboard works properly.

**Comment by EmulationFanatic** [comment]
@cybercjt during my testing I did not encounter that issue. Were you in fullscreen, by chance? Here you can see the name I entered during testing:
![image](https://user-images.githubusercontent.com/62343878/108087434-abed5480-7034-11eb-9acd-bdaa90b5487c.png)

**Comment by cybercjt** [comment]
@EmulationFanatic You got it all backwards, "Name" works fine.
It's the "Codename" tab, if you try to enter a text it always defaults to "Ryujinx" and Software Keyboard never pops up.

**Comment by EmulationFanatic** [comment]
My mistake @cybercjt . Not enough caffeine yet XD. I'll check momentarily.

**Comment by EmulationFanatic** [comment]
On a deeper look, this is actually a swkbd/inline kb issue. Thanks for the heads up! We will keep digging.

**Comment by cybercjt** [comment]
Will be tuning in, will still randomly test this game out until LDN finally supports it so we could test it's Local Multiplayer which is a unique feature for the Switch (kinda like GE:Burst and GE2:RB) compared to its PC/PS/XB versions that only has Online Multiplayer.

**Comment by EmulationFanatic** [comment]
@cybercjt you can use this build for now to name your own codename, while the issue is worked on.  https://w.ryujinx.org/dl/1.0.6543

**Comment by cybercjt** [comment]
@EmulationFanatic thanks for the heads up sir!

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6906

**Comment by EmulationFanatic** [comment]
Updated
