### ISSUE TITLE
Friday the 13th: Killer Puzzle

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1212]
#### Current on `master` : 1.0.4571

Loaded to the first level and then crashed.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32 width, Int32 height, Int32 depth, Int32 levels, Int32 layers, Int32 blockWidth, Int32 blockHeight, Int32 bytesPerPixel, Int32 gobBlocksInY, Int32 gobBlocksInZ, Int32 gobBlocksInTileX, SizeInfo sizeInfo, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.Texture\LayoutConverter.cs:line 233
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 479
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 330
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(RtColorState colorState, Int32 samplesInX, Int32 samplesInY) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 398
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateRenderTargetState(GpuState state, Boolean useControl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 326
   at Ryujinx.Graphics.Gpu.Engine.Methods.Clear(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodClear.cs:line 16
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 498
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 97
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
#### Screenshots :

![2020-05-15 06_09_00-Ryujinx 1 0 4571 - Friday the 13th_ Killer Puzzle v1 0 0 (010003F00BD48000) (64-](https://user-images.githubusercontent.com/62343878/82049155-1bcc4a00-9673-11ea-91a1-5ad65b53faac.png)
![2020-05-15 06_09_06-Ryujinx 1 0 4571 - Friday the 13th_ Killer Puzzle v1 0 0 (010003F00BD48000) (64-](https://user-images.githubusercontent.com/62343878/82049157-1c64e080-9673-11ea-8b57-19757082445e.png)
![2020-05-15 06_10_03-Ryujinx 1 0 4571 - Friday the 13th_ Killer Puzzle v1 0 0 (010003F00BD48000) (64-](https://user-images.githubusercontent.com/62343878/82049169-2090fe00-9673-11ea-9dcc-7d43550e60fe.png)
![2020-05-15 06_10_10-Ryujinx 1 0 4571 - Friday the 13th_ Killer Puzzle v1 0 0 (010003F00BD48000) (64-](https://user-images.githubusercontent.com/62343878/82049180-2686df00-9673-11ea-8b38-7e5f8e09dd86.png)
![2020-05-15 06_11_13-Ryujinx 1 0 4571 - Friday the 13th_ Killer Puzzle v1 0 0 (010003F00BD48000) (64-](https://user-images.githubusercontent.com/62343878/82049202-2be42980-9673-11ea-92d8-5fa94d67ae5e.png)
![2020-05-15 06_11_17-Ryujinx 1 0 4571 - Friday the 13th_ Killer Puzzle v1 0 0 (010003F00BD48000) (64-](https://user-images.githubusercontent.com/62343878/82049211-2edf1a00-9673-11ea-9877-42fc5cdf11db.png)

#### Log file :

[F13thKP.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4634276/F13thKP.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
