### ISSUE TITLE
Gotcha Racing 2nd

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1226]
#### Current on `master` : 1.0.4571

Allows you all the way through menus and then crashes when trying to start a race.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32 width, Int32 height, Int32 depth, Int32 levels, Int32 layers, Int32 blockWidth, Int32 blockHeight, Int32 bytesPerPixel, Int32 gobBlocksInY, Int32 gobBlocksInZ, Int32 gobBlocksInTileX, SizeInfo sizeInfo, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.Texture\LayoutConverter.cs:line 233
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 479
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 330
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(RtColorState colorState, Int32 samplesInX, Int32 samplesInY) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 398
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateRenderTargetState(GpuState state, Boolean useControl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 326
   at Ryujinx.Graphics.Gpu.Engine.Methods.Clear(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodClear.cs:line 16
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 498
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 97
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-05-15 10_04_24-Ryujinx 1 0 4571 - Gotcha Racing 2nd v1 0 0 (0100E8D007E16000) (64-bit)](https://user-images.githubusercontent.com/62343878/82071944-09163d00-9694-11ea-9d46-6edb346b3ca2.png)
![2020-05-15 10_05_07-Ryujinx 1 0 4571 - Gotcha Racing 2nd v1 0 0 (0100E8D007E16000) (64-bit)](https://user-images.githubusercontent.com/62343878/82071963-103d4b00-9694-11ea-933c-3ac9a981fb1e.png)
![2020-05-15 10_05_19-Ryujinx 1 0 4571 - Gotcha Racing 2nd v1 0 0 (0100E8D007E16000) (64-bit)](https://user-images.githubusercontent.com/62343878/82071967-12070e80-9694-11ea-85b2-c27ad93a5d25.png)
![2020-05-15 10_06_11-Ryujinx 1 0 4571 - Gotcha Racing 2nd v1 0 0 (0100E8D007E16000) (64-bit)](https://user-images.githubusercontent.com/62343878/82071970-13383b80-9694-11ea-9295-5e617c0ddc73.png)
![2020-05-15 10_06_27-Ryujinx 1 0 4571 - Gotcha Racing 2nd v1 0 0 (0100E8D007E16000) (64-bit)](https://user-images.githubusercontent.com/62343878/82071978-1501ff00-9694-11ea-8fc2-547bb8a2fbfe.png)

#### Log file :

[GotchaRacing2nd.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4635540/GotchaRacing2nd.zip)

**Comment by EmulationFanatic** [comment]
Updated
