### ISSUE TITLE
Flip Wars

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1229]
#### Current on `master` : 1.0.4571

Loads to title screen and then indicates controller has been disconnected. While trying to rectify through input settings, received the crash error below.

```
GUI.WindowThread Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Ryujinx.Ui.GlRenderer.UpdateFrame() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 367
   at Ryujinx.Ui.GlRenderer.MainLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 361
   at Ryujinx.Ui.GlRenderer.Start() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 205
   at Ryujinx.Ui.MainWindow.CreateGameWindow(Switch device) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 473
   at Ryujinx.Ui.MainWindow.<>c__DisplayClass48_0.<LoadApplication>b__1() in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 424
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-05-15 17_41_58-Ryujinx 1 0 4571 - Flip Wars v1 0 2 (010095A004040000) (64-bit)](https://user-images.githubusercontent.com/62343878/82104539-92e5fa80-96d4-11ea-819f-2c3efd2c9800.png)
![2020-05-15 17_42_24-Ryujinx 1 0 4571 - Flip Wars v1 0 2 (010095A004040000) (64-bit)](https://user-images.githubusercontent.com/62343878/82104541-94afbe00-96d4-11ea-8871-9d96b4ef31e1.png)

#### Log file :

[FlipWars.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4637496/FlipWars.zip)

**Comment by benderscruffy** [comment]
still an issue using 1.0.7112

**Comment by MutantAura** [comment]
Can anyone try out https://github.com/Ryujinx/Ryujinx/pull/3247 to check if this fixes the issue :)

**Comment by MutantAura** [comment]
Fully playable as of 1.1.93.

NVIDIA:
![image](https://user-images.githubusercontent.com/44103205/166263100-4997a7e0-8a10-4bf7-bfe5-6893e56a959c.png)

AMD: 
![image](https://user-images.githubusercontent.com/44103205/166263153-62bd1729-1200-4091-a358-dc178f755541.png)
