### ISSUE TITLE
Crash while saving New Horizons

### ISSUE THREAD

**Issue by danielocdh** [Ryujinx/Ryujinx-Games-List#1235]
#### Current on `master` : 1.0.4573

Emulator randomly crashes while saving, can be at any point sometimes even at the first save while starting the game.

```
01:18:55.719 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: Unable to delete file C:\Users\xxx\AppData\Roaming\Ryujinx\bis\system\save\8000000000000001\_
   at LibHac.FsSystem.LocalFileSystem.EnsureDeleted(FileSystemInfo entry)
   at LibHac.FsSystem.LocalFileSystem.DeleteDirectoryInternal(DirectoryInfo dir, Boolean recursive)
   at LibHac.FsSystem.LocalFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.SynchronizeDirectory(U8Span destPath, U8Span sourcePath)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.<CommitImpl>g__SynchronizeWorkingDir|45_1()
   at LibHac.FsSystem.Utility.RetryFinitelyForTargetLocked(Func`1 function)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.CommitImpl()
   at LibHac.Fs.FileSystemBase.Commit()
   at LibHac.FsService.Impl.MultiCommitManager.CommitContextManager.SetCommittedProvisionally()
   at LibHac.FsService.Impl.MultiCommitManager.CommitImpl(IFileSystem contextFileSystem)
   at LibHac.FsService.Impl.MultiCommitManager.Commit()
   at Ryujinx.HLE.HOS.Services.Fs.IMultiCommitManager.Commit(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Fs\IMultiCommitManager.cs:line 30
   --- End of inner exception stack trace ---
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx-Games-List/issues/622 (similar on Titan Quest)
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1084 (similar on WWE 2K18)

#### Log file :

[Ryujinx_2020-05-16_21-42-06.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4639636/Ryujinx_2020-05-16_21-42-06.log)

#### history:
I have been having this issue since Patreon version acnh3 or maybe before that, it constitutes around 98% of my crashes, it happened on game version 1.1.4 and 1.2.0 with firmware 9.20 and 10.0.1 (with older versions of the game and firmware too but not sure which ones)

**Comment by GoffyDude** [comment]
Come to discord for assistance on this.
Closing in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/250

**Comment by danielocdh** [comment]
This seemed to be fixed by running Ryujinx as administrator, but then happened again when upgrading to 1.0.4596 even when running as administrator
