### ISSUE TITLE
Slayin 2

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1245]
#### Current on `master` : 1.0.4573

Game boots to the menu, but with broken audio and graphics(they are inverted). Trying to get in game results in an crash

```
00:01:56.050 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument
was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in /home/space/Documents/Games/Switch/master-git/Ryujinx.Memory/MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in /home/space/Documents/Games/Switch/master-git/Ryujinx.Cpu/MemoryManager.cs:line 423
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in /home/space/Documents/Games/Switch/master-git/Ryujinx.Cpu/MemoryManager.cs:line 268
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in /home/space/Documents/Games/Switch/master-git/Ryujinx.Cpu/MemoryManager.cs:line 177
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in /home/space/Documents/Games/Switch/master-git/Ryujinx.Cpu/MemoryManager.cs:line 97
```

#### Screenshots :

![2020-05-18-095250_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82188315-fdbe4e00-98ed-11ea-8db6-50d2d8e306bd.png)

#### Log file :
[slayin-2.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4642816/slayin-2.log)

**Comment by benderscruffy** [comment]
goes ingame now
graphics are still inverted
![slayin 2](https://user-images.githubusercontent.com/2696404/96222913-a963eb00-0fbf-11eb-9024-0087b7d389bf.PNG)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6906

**Comment by benderscruffy** [comment]
using 1.1.341
graphics are right way up now and no graphic glitches

**Comment by GamerzHell9137** [comment]
### Game Name
Slayin 2

### Game Update Version

v1.0.0

### Emulator Build Version

1.1.1287

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 3600*
- ##### GPU: *NVIDIA RTX 3060 TI*
- ##### GPU Driver version: *546.33*
- ##### RAM: *16GB*

### Game State

Runs and plays with no issues.

### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/09a5120e-ec51-447c-afab-ffc529d8582e)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/755e10df-77b9-4c50-9628-6e09b80f7358)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/1fe8d1b3-95de-4158-993f-4910f09f47b6)


### Log File

_No response_
