### ISSUE TITLE
Tales of the Tiny Planet

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx-Games-List#125]
#### Current on `master` :

* Build 1.0.2038

Game boots to menu, and can go in-game. Performance is extremely low.

#### Screenshots :

![image](https://user-images.githubusercontent.com/1518948/48688655-47f04180-ec1b-11e8-9574-0c21d81f0f0d.png)

![image](https://user-images.githubusercontent.com/1518948/48688661-4cb4f580-ec1b-11e8-867a-f4c766b1311d.png)

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## Tales of the Tiny Planet

#### Current on `master` : 1.0.3937

Loads title screen/menu  and then crashes when trying to start a level.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32 width, Int32 height, Int32 depth, Int32 levels, Int32 layers, Int32 blockWidth, Int32 blockHeight, Int32 bytesPerPixel, Int32 gobBlocksInY, Int32 gobBlocksInZ, Int32 gobBlocksInTileX, SizeInfo sizeInfo, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.Texture\LayoutConverter.cs:line 215
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 473
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 324
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(RtColorState colorState, Int32 samplesInX, Int32 samplesInY) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 387
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateRenderTargetState(GpuState state, Boolean useControl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 276
   at Ryujinx.Graphics.Gpu.Engine.Methods.Clear(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodClear.cs:line 60
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 74
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, GpuState shadowState, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 497
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 131
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 98
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 154
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 212
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 187
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 329
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-03-22 08_04_58-Ryujinx 1 0 3937 _ Tales of the Tiny Planet _ 0100408007078000](https://user-images.githubusercontent.com/62343878/77251445-00fdcc00-6c14-11ea-96ed-f0e86b509f59.png)
![2020-03-22 08_02_21-Ryujinx 1 0 3937 _ Tales of the Tiny Planet _ 0100408007078000](https://user-images.githubusercontent.com/62343878/77251446-02c78f80-6c14-11ea-994b-8d8549ff94a7.png)
![2020-03-22 08_02_28-Ryujinx 1 0 3937 _ Tales of the Tiny Planet _ 0100408007078000](https://user-images.githubusercontent.com/62343878/77251448-03f8bc80-6c14-11ea-8046-4964eab39de0.png)
![Uploading 2020-03-22 08_05_37-Ryujinx 1.0.3937 _ Tales of the Tiny Planet _ 0100408007078000.png…]()

#### Log file :

[TOTTP.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4365352/TOTTP.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by GoffyDude** [comment]
## Tales of the Tiny Planet

#### Current on `master` : 1.0.4390

Launches and now goes in-game, renders accurately and is playable, though may be slow at times.

#### Screenshots :

![2020-04-30 18_01_48-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770189-d9502c80-8b0c-11ea-88a6-cee4538cb17c.png)
![2020-04-30 18_02_04-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770191-d9e8c300-8b0c-11ea-9cea-0df1108fac6e.png)
![2020-04-30 18_02_09-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770200-e10fd100-8b0c-11ea-81ad-0da23d13ebde.png)
![2020-04-30 17_56_59-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770206-e836df00-8b0c-11ea-85c2-85c433c9dfe3.png)
![2020-04-30 17_57_08-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770218-ef5ded00-8b0c-11ea-9e5e-e4a8ad5c3da4.png)
![2020-04-30 17_57_23-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770226-f258dd80-8b0c-11ea-8754-e46a8ea68b71.png)
![2020-04-30 17_57_31-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770232-f553ce00-8b0c-11ea-834c-e6e078b370c6.png)
![2020-04-30 17_58_09-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770242-fc7adc00-8b0c-11ea-9529-33ce9381eef8.png)
![2020-04-30 17_58_15-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770255-043a8080-8b0d-11ea-9011-07c24c300af3.png)
![2020-04-30 17_58_38-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770260-07357100-8b0d-11ea-9257-93b45f6aaa2a.png)
![2020-04-30 17_59_05-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770273-0e5c7f00-8b0d-11ea-8fed-fbfb9362f0d0.png)
![2020-04-30 17_59_42-Ryujinx 1 0 4390 - Tales of the Tiny Planet v1 1 2 (0100408007078000) (64-bit)](https://user-images.githubusercontent.com/62343878/80770280-11576f80-8b0d-11ea-94b5-688760c90174.png)


#### Log file :

[TOTTP.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4561947/TOTTP.zip)

**Comment by EmulationFanatic** [comment]
Updated
