### ISSUE TITLE
Gem Smashers

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1258]
#### Current on `master` : 1.0.4573

Game loads to corrupt intro splashes and intermittently corrupt menu screens before crashing when you try to start a new game.

```
HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.MarkRegionAsModified(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 432
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 163
   at Ryujinx.Cpu.MemoryManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 118
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 98
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-05-18 09_47_52-Ryujinx 1 0 4573 - Gem Smashers v1 0 0 (01001A4008192000) (64-bit)](https://user-images.githubusercontent.com/62343878/82233764-bafc7600-98ed-11ea-91ef-05fdf4c423b5.png)
![2020-05-18 09_48_30-Ryujinx 1 0 4573 - Gem Smashers v1 0 0 (01001A4008192000) (64-bit)](https://user-images.githubusercontent.com/62343878/82233778-c059c080-98ed-11ea-93cf-e68422454f0a.png)
![2020-05-18 09_48_49-Ryujinx 1 0 4573 - Gem Smashers v1 0 0 (01001A4008192000) (64-bit)](https://user-images.githubusercontent.com/62343878/82233814-c9e32880-98ed-11ea-8138-16ac3b3363dc.png)
![2020-05-18 09_52_40-Ryujinx 1 0 4573 - Gem Smashers v1 0 0 (01001A4008192000) (64-bit)](https://user-images.githubusercontent.com/62343878/82233841-d49dbd80-98ed-11ea-8883-e1685afec33e.png)
![2020-05-18 09_53_41-Ryujinx 1 0 4573 - Gem Smashers v1 0 0 (01001A4008192000) (64-bit)](https://user-images.githubusercontent.com/62343878/82233885-dff0e900-98ed-11ea-8bc6-18b1b173202e.png)
![2020-05-18 09_54_08-Ryujinx 1 0 4573 - Gem Smashers v1 0 0 (01001A4008192000) (64-bit)](https://user-images.githubusercontent.com/62343878/82233899-e7b08d80-98ed-11ea-9c8d-3c8b09447c21.png)
![2020-05-18 09_54_19-Ryujinx 1 0 4573 - Gem Smashers v1 0 0 (01001A4008192000) (64-bit)](https://user-images.githubusercontent.com/62343878/82233927-ef703200-98ed-11ea-9f9a-458773539ebb.png)

#### Log file :

[GemSmashers.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4645228/GemSmashers.zip)

**Comment by benderscruffy** [comment]
goes ingame now with corrupt graphics

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
