### ISSUE TITLE
Octopath Traveler

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx-Games-List#126]
#### Current on `master` :

* Build 1.0.2038

```
Unhandled Exception: System.NotImplementedException: fsp-srv IFileSystemProxy: 53
```

https://reswitched.github.io/SwIPC/ifaces.html#nn::fssrv::sf::IFileSystemProxy(53)

#### Screenshots :

![image](https://user-images.githubusercontent.com/1518948/48689520-16797500-ec1f-11e8-8976-e1b975285018.png)

#### Log file :

```
00:05:25.974 | 0007 ServiceNv Free: Deleted map 47!
00:06:00.767 | 0007 ServiceAm EnsureSaveData: Stubbed.
00:06:03.288 | 0007 ServiceAudio SetAudioDeviceOutputVolumeAuto: Stubbed.
00:06:03.335 | 0007 ServiceAudio SetAudioDeviceOutputVolumeAuto: Stubbed.
00:06:03.357 | 0007 ServiceAudio SetAudioDeviceOutputVolumeAuto: Stubbed.

Unhandled Exception: System.NotImplementedException: fsp-srv IFileSystemProxy: 53
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx Context) in Ryujinx.HLE\HOS\Services\IpcService.cs:line 83
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch Ns, Process Process, MemoryManager Memory, KSession Session, IpcMessage Request, Int64 CmdPtr) in Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 33
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.ProcessIpcRequest(Object State) in Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by AcK77** [comment]
Need an update.

**Comment by jduncanator** [comment]
Updated. Goes to menu, however it appears to be stuck loading forever.

**Comment by B3astTech** [comment]
Updated

**Comment by r3ntonboy** [comment]
It goes ingame now!

![Anotación 2020-04-20 121055](https://user-images.githubusercontent.com/35672114/79768660-7935db00-8301-11ea-85b2-3cfa6217eccf.jpg)
![Anotación 2020-04-20 121108](https://user-images.githubusercontent.com/35672114/79768676-7c30cb80-8301-11ea-823b-4dc61ac9b859.jpg)
![Anotación 2020-04-20 121236](https://user-images.githubusercontent.com/35672114/79768682-7dfa8f00-8301-11ea-9964-e6e27dd5e530.jpg)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
## Octopath Traveler

#### Current on `master` : 1.0.4697

*Game loads and plays on non-Pascal hardware. Graphics begin to have major problems when you leave the cathedral and it crashes shortly after.

```
HLE.HostThread.2 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Kingship, PID: 81
   sdk:0x0004305c nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   sdk:0x00043114 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, char const*, ...)
   sdk:0x0008f7fc nn::os::detail::InternalConditionVariableImplByHorizon::TimedWait(nn::os::detail::InternalCriticalSection*, nn::os::detail::TimeoutHelper const&)
   sdk:0x00086824 nn::os::WaitEvent(nn::os::EventType*)
   main:0x000e7744 Sub00000000080eb744
   main:0x000e166c Sub00000000080e566c
   main:0x000e12bc Sub00000000080e52bc
   main:0x000e088c Sub00000000080e488c
   main:0x00c797ac Sub0000000008c7d7ac
   main:0x00c776c4 Sub0000000008c7b6c4
   main:0x0087551c Sub000000000887951c
   main:0x00758898 Sub000000000875c898
   main:0x000d182c Sub00000000080d582c
   main:0x000d3b4c Sub00000000080d7b4c
   sdk:0x0008a8a8 Sub000000000eeec8a8
   sdk:0x0008e958 Sub000000000eef0958
   ??? Sub0000000000000000
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-06-14 08_37_29-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596502-70521900-ae1b-11ea-96bc-efddb84d904c.png)
![2020-06-14 08_37_37-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596504-70eaaf80-ae1b-11ea-9b52-a610cbcbf382.png)
![2020-06-14 08_37_46-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596508-75af6380-ae1b-11ea-85d9-3f0efe79e645.png)
![2020-06-14 08_37_48-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596509-75af6380-ae1b-11ea-805f-5ec01758c1b3.png)
![2020-06-14 08_37_51-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596510-75af6380-ae1b-11ea-88ff-4dbf777c46c6.png)
![2020-06-14 08_37_55-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596511-7647fa00-ae1b-11ea-8ffd-e9847af78dd0.png)
![2020-06-14 08_38_07-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596515-77792700-ae1b-11ea-8f3b-7748dd808666.png)
![2020-06-14 08_38_17-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596516-7811bd80-ae1b-11ea-9c20-b5105c5936d0.png)
![2020-06-14 08_38_46-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596521-7fd16200-ae1b-11ea-8c41-e9cd59c1db3f.png)
![2020-06-14 08_39_09-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596525-89f36080-ae1b-11ea-9214-34361b702a7b.png)
![2020-06-14 08_39_56-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596528-95468c00-ae1b-11ea-8837-45c8e7db7ab5.png)
![2020-06-14 08_41_21-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596532-9972a980-ae1b-11ea-845e-a360fc888bfa.png)
![2020-06-14 08_41_26-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596541-a099b780-ae1b-11ea-805b-8ecefbebf11c.png)
![2020-06-14 08_41_39-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596551-a68f9880-ae1b-11ea-92cf-0f0ad9d0e7d6.png)
![2020-06-14 08_41_54-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596554-ad1e1000-ae1b-11ea-87c1-8d2381a3095b.png)
![2020-06-14 08_42_52-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596559-b60ee180-ae1b-11ea-90c4-1eb9e990a0dc.png)
![2020-06-14 08_43_07-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596563-bb6c2c00-ae1b-11ea-83f9-bdb8ba7a43ab.png)
![2020-06-14 08_43_22-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596564-bc04c280-ae1b-11ea-8dfd-6aab5e888743.png)
![2020-06-14 08_43_25-Ryujinx 1 0 4697 - OCTOPATH TRAVELER v1 0 0 (010057D006492000) (64-bit)](https://user-images.githubusercontent.com/62343878/84596572-c9ba4800-ae1b-11ea-812f-6b488a9ad4ac.png)


#### Log file :

[OP.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4776640/OP.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Tellilum** [comment]
## Octopath Traveler
#### Game Update Version : 1.0.0

#### Build Version : 1.0.5251

Game runs pretty poorly outdoors, inside buildings however, the framerate will climb up. If memory serves me correctly, the water textures are slightly broken at the Aleport Docks. The minimap is also broken as well.

```
Last error returned.
N/A
```

#### Hardware Specs : 

##### CPU: i5-9400
##### GPU: AMD RADEON 4GB RX570 OC
##### RAM: 16GB


#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx-Games-List/issues/126

#### Screenshots :

![Screenshot (15)](https://user-images.githubusercontent.com/59491721/91677447-b52f4700-eb10-11ea-835b-dbaba54ee4f2.png)
![Screenshot (16)](https://user-images.githubusercontent.com/59491721/91677451-b6607400-eb10-11ea-9721-adf9e97213e2.png)
![Screenshot (17)](https://user-images.githubusercontent.com/59491721/91677453-b791a100-eb10-11ea-9d97-29823c15df98.png)
![Screenshot (12)](https://user-images.githubusercontent.com/59491721/91677454-b95b6480-eb10-11ea-9623-97f2cb25d456.png)
![Screenshot (13)](https://user-images.githubusercontent.com/59491721/91677457-b9f3fb00-eb10-11ea-83dd-15e78d571710.png)
![Screenshot (14)](https://user-images.githubusercontent.com/59491721/91677461-bc565500-eb10-11ea-8f4c-3bfb16c998b9.png)

#### Log file :

[Ryujinx_2020-08-30_22-23-06.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5148031/Ryujinx_2020-08-30_22-23-06.log)
