### ISSUE TITLE
Fury Unleashed

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1260]
#### Current on `master` : 1.0.4573

boots to the menu, but crashes when you try to get ingame

```
Last error returned.
00:05:52.047 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 10

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00381e78 nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 33, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 34, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<2, 33, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> >, 16ul, 12ul, true>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 33, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 34, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<2, 33, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, unsigned int)
   sdk:0x00380d08 Sub000000000cf71d08
   sdk:0x0037f138 Sub000000000cf70138
   main:0x018743a4 Sub00000000098783a4
   main:0x0185cdac Sub0000000009860dac
   main:0x00bac714 Sub0000000008bb0714
   main:0x00bac534 Sub0000000008bb0534
   main:0x00748edc Sub000000000874cedc
   main:0x0099024c Sub000000000899424c
   main:0x00994f00 Sub0000000008998f00
   main:0x009989ec Sub000000000899c9ec
   main:0x011026e8 Sub00000000091066e8
   main:0x010fdde0 Sub0000000009101de0
   main:0x006f3dac Sub00000000086f7dac
   main:0x0007a52c Sub000000000807e52c
   main:0x0184d91c Sub000000000985191c
   main:0x01829680 Sub000000000982d680
   main:0x01850cb8 Sub0000000009854cb8
   sdk:0x003344b8 Sub000000000cf254b8
   sdk:0x00338984 Sub000000000cf29984
   ??? Sub0000000000000000

Buffer Information:
	PtrBuff:
	[0] Position: 0x0000000116724110 Size: 0x000000000000001b
	[1] Position: 0x000000014025a0b0 Size: 0x0000000000000000
	SendBuff:
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
	ReceiveBuff:
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
	RecvListBuff:
	Position: 0x000000014025a0d8 Size: 0x0000000000000200

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0A 00 00 00 00 00 00 00   SFCI············
00000010   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  00 02 00 00 D8 A0 25 40   ············Ø %@
00000030   01 00 00 02                                        ····            

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Screenshots :

![05-18_20:08:06](https://user-images.githubusercontent.com/62521228/82245643-a5b23680-9943-11ea-8641-3e42742b49d7.png)

#### Log file :
[fury-unleashed.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4645832/fury-unleashed.log)

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by SeraUX** [comment]
Updated
