### ISSUE TITLE
TaniNani

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1261]
#### Current on `master` : 1.0.4573

game crashes on boot.

```
Last error returned.
Unhandled exception. Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1154
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 47
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 125
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
```

#### Log file :
[taninani.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4646860/taninani.log)

**Comment by benderscruffy** [comment]
needs an update

**Comment by SeraUX** [comment]
On my side, the state of the game is still the same

**Comment by AcK77** [comment]
Needs update
