### ISSUE TITLE
Atelier Escha and Logy Tasogare no Sora no Renkinjutsushi DX

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1262]
#### Current on `master` : 1.0.4573

The game has nvdec cutscenes, but they can be skipped. Trying to skip them, can result in a crash 50% of the time. When the game doesn't crash, it plays really well.
Turning on ignore missing services seems to bypass that crash and the game doesn't have problems with it on.
```
Latest error:
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Audio.AudioOutManager.IAudioOut: 10

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0006cc9c nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 0l> >, 0ul, 8ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 0l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<8ul, 8ul>, unsigned int)
   sdk:0x00095464 Sub000000000981e464
   sdk:0x0009a320 nn::audio::GetAudioOutPlayedSampleCount(nn::audio::AudioOut const*)
   main:0x005478c4 Sub000000000854b8c4
   main:0x0054778c Sub000000000854b78c
   sdk:0x003344b8 Sub0000000009abd4b8
   sdk:0x00338984 Sub0000000009ac1984
   ??? Sub0000000000000000

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0A 00 00 00 00 00 00 00   SFCI············
00000010   00 00 00 00 00 00 00 00  07 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```
#### Screenshots :

![05-18_23:57:44](https://user-images.githubusercontent.com/62521228/82263707-c68a8400-9963-11ea-8ff5-58a147d353a3.png)
![05-18_23:59:07](https://user-images.githubusercontent.com/62521228/82263722-cc806500-9963-11ea-82f2-5d38fdbad8ba.png)
![05-19_00:11:38](https://user-images.githubusercontent.com/62521228/82264570-73193580-9965-11ea-8941-850c2875eb81.png)
![05-19_00:11:45](https://user-images.githubusercontent.com/62521228/82264576-76142600-9965-11ea-914c-a47b6cccc067.png)

#### Log file :

[Atelier Escha and Logy Tasogare no Sora no Renkinjutsushi DX.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4647133/Atelier.Escha.and.Logy.Tasogare.no.Sora.no.Renkinjutsushi.DX.log)

**Comment by SeraUQ** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
