### ISSUE TITLE
Operencia The Stolen Sun

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1274]
#### Current on `master` : 1.0.4573

Game boots to the menu, has really messed up graphics, and crashes when trying to get ingame

```
Last error returned.
00:02:25.116 | HLE.HostThread.2 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1154
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 63
Unhandled exception. Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1154
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 63
```

#### Screenshots :

![05-19_14:42:43](https://user-images.githubusercontent.com/62521228/82328420-21fa5780-99e0-11ea-90f3-bd031bc2ea8c.png)
![05-19_14:43:13](https://user-images.githubusercontent.com/62521228/82328428-245cb180-99e0-11ea-86ba-eae19a7ddec0.png)

#### Log file :

[operencia-the-stolen-sun.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4650543/operencia-the-stolen-sun.log)

**Comment by EmulationFanatic** [comment]
Updated
