### ISSUE TITLE
DRAGON BALL FighterZ

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#129]
#### Current on `master` :

* Build Version : 1.0.2053

```
Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

Implement that, and then crash when go in-game:
```
Unhandled Exception: System.NotImplementedException: pctl IParentalControlService: 1001
```
https://reswitched.github.io/SwIPC/ifaces.html#nn::pctl::detail::ipc::IParentalControlService(1001)

#### Pull requests needed :

https://github.com/Ryujinx/Ryujinx/pull/443

#### Screenshots :

![image](https://user-images.githubusercontent.com/24840279/48904014-ac1b3b80-ee8f-11e8-8277-21559b49a095.png)
![image](https://user-images.githubusercontent.com/24840279/48904768-07e6c400-ee92-11e8-8ab9-bfdaa928d9fa.png)
![image](https://user-images.githubusercontent.com/24840279/48904881-7297ff80-ee92-11e8-9677-6a5afa4db636.png)
![image](https://user-images.githubusercontent.com/24840279/48905503-55643080-ee94-11e8-8a04-ed295557034e.png)
![image](https://user-images.githubusercontent.com/24840279/48906108-0fa86780-ee96-11e8-9906-65d451790dfd.png)
![image](https://user-images.githubusercontent.com/24840279/48906120-1a62fc80-ee96-11e8-84b2-8b27ca47af95.png)
![image](https://user-images.githubusercontent.com/24840279/48906528-56e32800-ee97-11e8-8708-d4dc69a578aa.png)
![image](https://user-images.githubusercontent.com/24840279/48906535-619dbd00-ee97-11e8-95f0-3ae690274e1d.png)
![image](https://user-images.githubusercontent.com/24840279/48906778-2d76cc00-ee98-11e8-8676-91842314f770.png)
![image](https://user-images.githubusercontent.com/24840279/48906818-40899c00-ee98-11e8-8b29-66f74677a19c.png)
![image](https://user-images.githubusercontent.com/24840279/48907121-23090200-ee99-11e8-8489-d7f07e2454c1.png)
![image](https://user-images.githubusercontent.com/24840279/48907435-ff928700-ee99-11e8-9b4e-9c6758ae6cdc.png)
![image](https://user-images.githubusercontent.com/24840279/48908039-c8bd7080-ee9b-11e8-9eae-a3a94d910698.png)
![image](https://user-images.githubusercontent.com/24840279/48908228-441f2200-ee9c-11e8-97c4-198113db49f3.png)
![image](https://user-images.githubusercontent.com/24840279/48908429-bf80d380-ee9c-11e8-861c-bf2c6ac214a4.png)
![image](https://user-images.githubusercontent.com/24840279/48909143-12f42100-ee9f-11e8-99fd-252f6efe39d9.png)
![image](https://user-images.githubusercontent.com/24840279/48910093-a6c6ec80-eea1-11e8-88ad-d488864ae384.png)

**Comment by AcK77** [comment]
On master it's throw 
```
 Unhandled exception caught: System.NotImplementedException: Unsupported texture target type: TextureBuffer
   at Ryujinx.Graphics.Gal.OpenGL.OglTexture.Create(Int64 key, Byte[] data, GalImage image) in Ryujinx.Graphics\Gal\OpenGL\OglTexture.cs:line 308
   at Ryujinx.Graphics.GpuResourceManager.PrepareSendTexture(NvGpuVmm vmm, Int64 position, GalImage newImage) in Ryujinx.Graphics\GpuResourceManager.cs:line 130
   at Ryujinx.Graphics.Graphics3d.NvGpuEngine3d.UploadTexture(NvGpuVmm vmm, Int32 textureHandle) in Ryujinx.Graphics\Graphics3d\NvGpuEngine3d.cs:line 709
   at Ryujinx.Graphics.Graphics3d.NvGpuEngine3d.UploadTextures(NvGpuVmm vmm, GalPipelineState state, Int64[] keys) in Ryujinx.Graphics\Graphics3d\NvGpuEngine3d.cs:line 647
   at Ryujinx.Graphics.Graphics3d.NvGpuEngine3d.VertexEndGl(NvGpuVmm vmm, GpuMethodCall methCall) in Ryujinx.Graphics\Graphics3d\NvGpuEngine3d.cs:line 132
   at Ryujinx.Graphics.Graphics3d.NvGpuEngine3d.CallMethod(NvGpuVmm vmm, GpuMethodCall methCall) in Ryujinx.Graphics\Graphics3d\NvGpuEngine3d.cs:line 98
   at Ryujinx.Graphics.Graphics3d.MacroInterpreter.Send(NvGpuVmm vmm, Int32 value) in Ryujinx.Graphics\Graphics3d\MacroInterpreter.cs:line 413
   at Ryujinx.Graphics.Graphics3d.MacroInterpreter.Step(NvGpuVmm vmm, Int32[] mme) in Ryujinx.Graphics\Graphics3d\MacroInterpreter.cs:line 193
   at Ryujinx.Graphics.Graphics3d.MacroInterpreter.Execute(NvGpuVmm vmm, Int32[] mme, Int32 position, Int32 param) in Ryujinx.Graphics\Graphics3d\MacroInterpreter.cs:line 88
   at Ryujinx.Graphics.Graphics3d.NvGpuFifo.Call3dMethod(NvGpuVmm vmm, GpuMethodCall methCall) in Ryujinx.Graphics\Graphics3d\NvGpuFifo.cs:line 161
   at Ryujinx.Graphics.Graphics3d.NvGpuFifo.CallMethod(NvGpuVmm vmm, GpuMethodCall methCall) in Ryujinx.Graphics\Graphics3d\NvGpuFifo.cs:line 91
   at Ryujinx.Graphics.DmaPusher.CallMethod(Int32 argument) in Ryujinx.Graphics\DmaPusher.cs:line 188
   at Ryujinx.Graphics.DmaPusher.Step() in Ryujinx.Graphics\DmaPusher.cs:line 93
   at Ryujinx.GlScreen.RenderLoop() in Ryujinx\Ui\GLScreen.cs:line 69
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by AcK77** [comment]
Need an update.

**Comment by B3astTech** [comment]
Need's a Update

**Comment by GoffyDude** [comment]
## DRAGON BALL FighterZ

#### Current on `master` : 1.0.3937

After a couple minutes of attempting to load, game appears to hang completely. Including a 5-minute debug log reveals processes still running the whole time.

Normal log:
```
GUI.RenderLoop Gpu PrintLog: Shader translator: Invalid instruction at 0x000088 (0xF0F0000034170000).
```

Debug log:
```
HLE.HostThread.5 KernelSvc PrintArguments: WaitProcessWideKeyAtomic64 mutexAddress: 0x10116B8DEC, condVarAddress: 0x10116B8DF0, handle: 0x00130020, timeout: 0x00989513
```
#### Log file :
[DBFZ.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4364196/DBFZ.zip)
[DBFZ_debug.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4364198/DBFZ_debug.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
## Dragon Ball FighterZ

#### Current on `master` : 1.0.4686

Has nvdec cutscene issue after starting a new game. This cannot be skipped.
Has online functionality that will crash the game if selected.
Otherwise game loads through menus and to in-game with significant corruption of colors and missing graphical textures. Once in a battle, the corruption remains and the FPS dips into single digits, making this game unplayable.

#### Screenshots :

![2020-06-13 05_32_42-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567898-1ed15d80-ad39-11ea-86e5-9137528c7b38.png)
![2020-06-13 05_33_23-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567904-27c22f00-ad39-11ea-839c-e12f3a0de606.png)
![2020-06-13 05_35_34-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567907-2ee93d00-ad39-11ea-85f4-ee1b038e3812.png)
![2020-06-13 05_36_34-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567908-2f81d380-ad39-11ea-9b18-b0dfa6bd1fbe.png)
![2020-06-13 05_36_50-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567909-30b30080-ad39-11ea-9bdc-263934d768b9.png)
![2020-06-13 05_37_23-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567911-33adf100-ad39-11ea-9d42-731e915020d5.png)
![2020-06-13 05_38_08-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567916-390b3b80-ad39-11ea-82b6-1cb3a9871d37.png)
![2020-06-13 05_39_05-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567920-3dcfef80-ad39-11ea-9629-17581138d5cb.png)
![2020-06-13 05_40_35-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567923-40324980-ad39-11ea-8476-1c6ed92563b4.png)
![2020-06-13 05_41_26-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567924-41fc0d00-ad39-11ea-9536-b161626dcd3e.png)
![2020-06-13 05_43_26-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567929-46282a80-ad39-11ea-87b3-0dfb5aab7dfc.png)
![2020-06-13 05_43_29-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567930-488a8480-ad39-11ea-9543-987784663952.png)
![2020-06-13 05_43_43-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567932-4aecde80-ad39-11ea-92b9-b92412c7667a.png)
![2020-06-13 05_44_01-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567935-52ac8300-ad39-11ea-9f87-6531fc487e8d.png)
![2020-06-13 05_44_17-Ryujinx 1 0 4686 - DRAGON BALL FighterZ v01 00 (0100A250097F0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84567936-56d8a080-ad39-11ea-9983-87e5e9e6db69.png)


#### Log file :


[DBFZ.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4774525/DBFZ.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by ryulovesjinx** [comment]
The game is almost in a perfect state, at least in my machine. Tried multiple builds and all the same red screen/flickering on chars selection and loading.

As requested by @EmulationFanatic (thanks by the way), I have retested the game (Ryzen 3600 - GTX 670 - 16GB Ram) with OpenGL Logs None. 
On console, no errors was thrown by terminal during the characters select screen and loading.
But before entering the screen this error was showed:

(before chars selection)
00:02:11.795 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x1078ee0000, size 0x1380000) failed!
00:02:11.796 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x1078ee0000, size 0x1380000) failed!
00:02:11.796 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x1078ee0000, size 0x1380000) failed!
00:02:11.796 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x1078ee0000, size 0x1380000) failed!
00:02:11.796 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x1078ee0000, size 0x1380000) failed!

![Screenshot from 2021-06-01 17-41-35](https://user-images.githubusercontent.com/85196112/120387974-e8ea0800-c300-11eb-9e27-e7bcf46124ac.png)

(before loading screen)

00:08:49.552 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.553 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.553 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.553 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.553 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.553 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.553 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.554 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.554 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.554 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.554 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.554 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.555 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.555 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.555 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.555 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.555 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.555 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.556 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.556 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.556 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.556 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.556 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x106dd10000, size 0x1280000) failed!
00:08:49.571 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 86!

![Screenshot from 2021-06-01 17-44-50](https://user-images.githubusercontent.com/85196112/120388283-4aaa7200-c301-11eb-896e-9c1f29a7311b.png)

**Comment by ryulovesjinx** [comment]
In the lastest PRs, I've noticed that frame rate drops start to occur while performing a combo or releasing a special attack. Frame rates goes from 58 fps to 38...20 fps. Anyone noticed that (@AcK77 , @EmulationFanatic, may you take a lookk) ? Possible a regression took place ?

**Comment by EmulationFanatic** [comment]
What do you mean by "the latest PRs"? Are you referring to behavior on the master build? Did the fps drops even out after playing for a couple of minutes?

**Comment by ryulovesjinx** [comment]
@EmulationFanatic, you are correct, in the master build. Some commits before, the game had no fps drops. The fps drops while performing combos or releasing a special attack in the middle of the battle. I've tried in Practice Mode, and one or 2 minutes after performing various combos, the drops start. It is like while you add more hits, the drops start to get bigger. You can see below the FPS while the HITS are getting higher. 

![Screenshot from 2021-06-11 13-14-08](https://user-images.githubusercontent.com/85196112/121717153-40356880-cab7-11eb-9da0-a052b41be9a2.png)
![Screenshot from 2021-06-11 13-15-41](https://user-images.githubusercontent.com/85196112/121717165-43305900-cab7-11eb-956a-0381d34500cc.png)
![Screenshot from 2021-06-11 13-15-53](https://user-images.githubusercontent.com/85196112/121717174-46c3e000-cab7-11eb-9132-2cd0c5472caf.png)
