### ISSUE TITLE
Gato Roboto

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1299]
#### Current on `master` : 1.0.4593

Crashed after 10 minutes of trying to load.

```
HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x004f6358 __nnmusl_GetTlsValue
   sdk:0x004a8394 Sub000000000af89394
   subsdk0:0x0096183c Sub00000000096e383c
   subsdk0:0x00a5711c Sub00000000097d911c
   subsdk0:0x00a56bfc Sub00000000097d8bfc
   subsdk0:0x00a4c784 Sub00000000097ce784
   subsdk0:0x00a4ccc8 Sub00000000097cecc8
   subsdk0:0x00a55530 Sub00000000097d7530
   subsdk0:0x00957300 Sub00000000096d9300
   subsdk0:0x00a2ca38 Sub00000000097aea38
   subsdk0:0x009ef864 Sub0000000009771864
   subsdk0:0x0063b140 Sub00000000093bd140
   main:0x001688b8 Sub000000000816c8b8
   main:0x00130384 Sub0000000008134384
   main:0x000b877c Sub00000000080bc77c
   main:0x00036880 Sub000000000803a880
   main:0x000391d8 Sub000000000803d1d8
   main:0x00038d48 Sub000000000803cd48
   main:0x00041b38 Sub0000000008045b38
   main:0x00041c5c Sub0000000008045c5c
   main:0x000a31fc Sub00000000080a71fc
   main:0x000a174c Sub00000000080a574c
   main:0x0012c1d0 Sub00000000081301d0
   main:0x0012d234 Sub0000000008131234
   main:0x0012d440 Sub0000000008131440
   main:0x0012e384 Sub0000000008132384
   main:0x000d2b6c Sub00000000080d6b6c
   main:0x000d2f34 Sub00000000080d6f34
   main:0x00026c44 nnMain
   sdk:0x00289efc nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:10:50.941 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1154
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 63
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 98
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```
#### Log file :

[GR.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4657199/GR.zip)

**Comment by benderscruffy** [comment]
needs an update

**Comment by SeraUX** [comment]
On my side, the state of the game hasn't changed from the latest report.

**Comment by LukeWarnut** [comment]
Same status in 1.0.6575

**Comment by benderscruffy** [comment]
same status in 1.0.7096

**Comment by benderscruffy** [comment]
using 1.1.16
goes ingame now
![ryujinx_capture_2022-02-05_09-49-41](https://user-images.githubusercontent.com/2696404/152624317-378855c5-c216-41c5-a550-9b641d75d18b.png)
![ryujinx_capture_2022-02-05_09-49-52](https://user-images.githubusercontent.com/2696404/152624318-8ceebd02-6aef-42bd-b13b-39f842b67935.png)
![ryujinx_capture_2022-02-05_09-52-14](https://user-images.githubusercontent.com/2696404/152624319-ee26e46c-f0a0-401e-9152-33bbac3c71af.png)
![ryujinx_capture_2022-02-05_09-53-08](https://user-images.githubusercontent.com/2696404/152624322-22fb8a18-28f2-4ffe-815b-4f4ba8b2b9ba.png)
![ryujinx_capture_2022-02-05_09-53-48](https://user-images.githubusercontent.com/2696404/152624324-4e15a4ba-dc76-44cc-b83a-207d26fffb4f.png)

**Comment by felipevc13** [comment]
the game has missing textures and graphical artifacts on some screens
