### ISSUE TITLE
Arcade Archives VS. SUPER MARIO BROS.

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#130]
#### Current on `master` :

* Build Version : 1.0.2073

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Services.Aud.AudioRenderer.VoiceContext.GetBufferData(MemoryManager Memory, Int32 MaxSamples, Int32& SamplesCount) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Aud\AudioRenderer\VoiceContext.cs:line 82
   at Ryujinx.HLE.HOS.Services.Aud.AudioRenderer.IAudioRenderer.AppendMixedBuffer(Int64 Tag) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Aud\AudioRenderer\IAudioRenderer.cs:line 325
   at Ryujinx.HLE.HOS.Services.Aud.AudioRenderer.IAudioRenderer.UpdateAudio() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Aud\AudioRenderer\IAudioRenderer.cs:line 304
   at Ryujinx.HLE.HOS.Services.Aud.AudioRenderer.IAudioRenderer.RequestUpdateAudioRenderer(ServiceCtx Context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Aud\AudioRenderer\IAudioRenderer.cs:line 213
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx Context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 96
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch Device, KProcess Process, MemoryManager Memory, KSession Session, IpcMessage Request, Int64 CmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 33
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.ProcessIpcRequest(Object State) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 236
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by AcK77** [comment]
Need an update.

**Comment by HorrorTroll** [comment]
Updated

**Comment by GoffyDude** [comment]
## Arcade Archives VS. SUPER MARIO BROS.

#### Current on `master` : 1.0.4006

Menu audio sound effect loops repeatedly until trying to start a game where it crashes due to the error below.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00053e9c nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)4> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> > >::ProcessWithOutObjects(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)4> > >::ProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*)
   sdk:0x000aea00 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::baas::IManagerBase, nn::sf::cmif::client::CmifDomainProxy<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)4> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::baas::IManagerForApplication>::_nn_sf_sync_EnsureIdTokenCacheAsync(nn::sf::Out<nn::sf::SharedPointer<nn::account::detail::IAsyncContext>, void>)
   sdk:0x000b7b70 nn::account::EnsureNetworkServiceAccountIdTokenCacheAsync(nn::account::AsyncContext*, nn::account::UserHandle const&)
   main:0x000a44f0 Sub00000000080a84f0
   main:0x00086c38 Sub000000000808ac38
   main:0x00085914 Sub0000000008089914
   main:0x000856b0 Sub00000000080896b0
   main:0x000851d4 Sub00000000080891d4
   main:0x00085bcc Sub0000000008089bcc
   main:0x0007f42c Sub000000000808342c
   main:0x0007f0ec Sub00000000080830ec
   main:0x0007f25c Sub000000000808325c
   main:0x0007f078 Sub0000000008083078
   main:0x00028a40 Sub000000000802ca40
   main:0x000284ec Sub000000000802c4ec
   main:0x00007350 Sub000000000800b350
   main:0x0002b578 Sub000000000802f578
   main:0x0002e198 Sub0000000008032198
   main:0x0000060c Sub000000000800460c
   sdk:0x000686b4 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000ac Sub00000000080000ac
```


#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![2020-03-25 08_05_59-Ryujinx 1 0 4006 _ Arcade Archives VS  SUPER MARIO BROS  _ 010021D00812A000](https://user-images.githubusercontent.com/62343878/77545204-b11b4100-6e6f-11ea-9362-7ebadab677fd.png)


#### Log file :

[AAVSSMB.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4381366/AAVSSMB.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by SeraUX** [comment]
## Arcade Archives VS. SUPER MARIO BROS

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.5191

Game crashes with an missing service error after trying to go past the first menu.
```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 6

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x000a78d0 nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)4, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 6, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> >, 16ul, 12ul, true>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 6, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, nn::sf::cmif::client::InRawClientArgumentType<1ul, 1ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, unsigned int)
   sdk:0x000a7098 Sub000000000a4b9098
   sdk:0x000a648c Sub000000000a4b848c
   main:0x000defd8 Sub00000000080e2fd8
   main:0x000ec9b8 Sub00000000080f09b8
   main:0x000f14c4 Sub00000000080f54c4
   main:0x00071d40 Sub0000000008075d40
   sdk:0x0008a8a8 Sub000000000a49c8a8
   sdk:0x0008e958 Sub000000000a4a0958
   ??? Sub0000000000000000

Buffer Information:
        SendBuff:
        Position: 0x0000001190f60cfc Size: 0x0000000000000023 Flags: 0
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        Position: 0x0000001190f607e0 Size: 0x0000000000000400 Flags: 0
        ReceiveBuff:
        Position: 0x0000000008fed0b0 Size: 0x0000000000001000 Flags: 0

Raw Request Data:
00000000   53 46 43 49 00 00 00 00  06 00 00 00 00 00 00 00   SFCI············
00000010   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Hardware Specs :

##### CPU: i3-7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/637

#### Screenshots :

![22-09-40_18-08-20](https://user-images.githubusercontent.com/62521228/90560577-99868100-e19f-11ea-8b98-ad479737ded7.png)

#### Log file :

[aa-vs-super-mario.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5092573/aa-vs-super-mario.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
