### ISSUE TITLE
Ion Fury

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1309]
#### Current on `master` : 1.0.4593

Game crashes on launch

```
Last error returned.
00:01:42.020 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.NotImplementedException: Unknown MRS 0xD53BE040 at 0x000000000835F3CC.
   at ARMeilleure.Instructions.InstEmit.Mrs(ArmEmitterContext context) in C:\projects\ryujinx\ARMeilleure\Instructions\InstEmitSystem.cs:line 47
   at ARMeilleure.Translation.Translator.EmitAndGetCFG(ArmEmitterContext context, Block[] blocks) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 234
   at ARMeilleure.Translation.Translator.Translate(UInt64 address, ExecutionMode mode, Boolean highCq) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 149
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 127
   at ARMeilleure.Instructions.NativeInterface.GetFunctionAddress(UInt64 address) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 404

```

#### Log file :

[ion-fury.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4666817/ion-fury.log)

**Comment by GoffyDude** [comment]
## Ion Fury

#### Current on `master` : 1.0.4613

Crashes on launch.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Audio.IAudioInManager: 4
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1056

#### Log file :

[IF.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4682702/IF.zip)

**Comment by GoffyDude** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6895

**Comment by benderscruffy** [comment]
using 1.0.7107
goes ingame now
but ingame it is a black screen with music playing
![ryujinx_capture_2021-11-24_14-24-36](https://user-images.githubusercontent.com/2696404/143186267-0599afda-1816-4519-abdf-6317a80232e8.png)
![ryujinx_capture_2021-11-24_14-24-41](https://user-images.githubusercontent.com/2696404/143186274-22045efc-993a-4fdf-84e8-f8fd85e05a14.png)
![ryujinx_capture_2021-11-24_14-24-50](https://user-images.githubusercontent.com/2696404/143186278-bce636f5-35f9-4e36-a397-f6462b29096a.png)

**Comment by F1ReB4LL** [comment]
## Ion Fury

#### Game Update Version : *1.07.1*

#### Current on `master` : *1.1.208*

#### Graphics Backend : *Both Vulkan and OpenGL*

*The Voidpoint dev intro is played very slow (3-4 FPS). The rest looks OK if using an OpenGL backend, haven't noticed any obvious issues. If using a Vulkan backend, most of the sprites are surrounded with black striped rectangles.*

```
Last error returned: No errors shown
```

#### Hardware Specs : 

##### CPU: *i5-11400H*
##### GPU: *NVIDIA RTX 3050*
##### RAM: *24GB*

#### Screenshots :

![ryujinx_ifr0](https://user-images.githubusercontent.com/39680140/183275670-90567639-9855-445d-8b21-267c80f796c8.png)
![ryujinx_ifr1](https://user-images.githubusercontent.com/39680140/183275672-313ceecd-399e-4bc6-a098-3330929b9379.png)
![ryujinx_ifr2](https://user-images.githubusercontent.com/39680140/183275676-cd53560b-ddb8-4720-876c-5719d5dcfa06.png)
![ryujinx_ifr3](https://user-images.githubusercontent.com/39680140/183275678-6ecb9118-0919-4c99-a97d-fa512177238a.png)
![ryujinx_ifr4](https://user-images.githubusercontent.com/39680140/183275683-d92504c9-5d7f-4061-a833-6836d19b031c.png)
![ryujinx_ifr5](https://user-images.githubusercontent.com/39680140/183275685-2fe3a3d1-023f-470d-9542-9a46f6578251.png)
![ryujinx_ifr6](https://user-images.githubusercontent.com/39680140/183275687-671dbce1-3370-4d43-835f-3becc88f2834.png)
![ryujinx_ifr7](https://user-images.githubusercontent.com/39680140/183275691-fe191030-e024-4c53-94b5-4ce2fb02a42d.png)
![ryujinx_ifr8](https://user-images.githubusercontent.com/39680140/183275693-86cc573d-fa4f-4bc6-8d79-22ffb22ee569.png)

Vulkan:
![ryujinx_ifr4](https://user-images.githubusercontent.com/39680140/183275715-02169670-8c02-4ed2-a29d-5b9c930ffaa8.png)
![ryujinx_ifr5](https://user-images.githubusercontent.com/39680140/183275718-326769c7-aa08-42e6-80fd-70606604aa15.png)
![ryujinx_ifr7](https://user-images.githubusercontent.com/39680140/183275721-f8d78dfe-6530-4c07-945e-63fab636bfb3.png)
![ryujinx_ifr8](https://user-images.githubusercontent.com/39680140/183275723-1e31605c-6e07-4b0e-916b-dd1f82093704.png)
![ryujinx_ifr9](https://user-images.githubusercontent.com/39680140/183275724-2ed236f8-c410-43ea-90f6-1ba29ac1a984.png)

**Comment by MetrosexualGarbodor** [comment]
Updated.
