### ISSUE TITLE
Void Bastards

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1310]
#### Current on `master` : 1.0.4593

Game crashes when you get ingame after a minute of gameplay

```
Last error returned.
00:04:46.056 | GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32 width, Int32 height, Int32 depth, Int32 levels, Int32 layers, Int32 blockWidth, Int32 blockHeight, Int32 bytesPerPixel, Int32 gobBlocksInY, Int32 gobBlocksInZ, Int32 gobBlocksInTileX, SizeInfo
sizeInfo, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.Texture\LayoutConverter.cs:line 233
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 463
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 328
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(RtColorState colorState, Int32 samplesInX, Int32 samplesInY) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 398
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateRenderTargetState(GpuState state, Boolean useControl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 326
   at Ryujinx.Graphics.Gpu.Engine.Methods.Clear(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodClear.cs:line 16
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 498
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 97
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![05_22_03-11:03:47](https://user-images.githubusercontent.com/62521228/82651586-a2a59780-9c1c-11ea-9284-8ce360ac3441.png)
![05_22_04-11:04:30](https://user-images.githubusercontent.com/62521228/82651595-a507f180-9c1c-11ea-8fbf-9700fd92686a.png)
![05_22_05-11:05:10](https://user-images.githubusercontent.com/62521228/82651614-a9cca580-9c1c-11ea-9feb-3a21cac73a24.png)
![05_22_06-11:06:03](https://user-images.githubusercontent.com/62521228/82651621-acc79600-9c1c-11ea-9801-0cdb9e821bb3.png)
![05_22_06-11:06:51](https://user-images.githubusercontent.com/62521228/82651626-ae915980-9c1c-11ea-966f-aa5c612c6339.png)

#### Log file :

[void-bastards.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4667103/void-bastards.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
