### ISSUE TITLE
SNK HEROINES Tag Team Frenzy

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1328]
#### Current on `master` : 1.0.4593

Game crashes on boot

```
Last error returned.
00:00:26.744 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Friend.ServiceCreator.IFriendService: 10700

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00127760 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)4> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn
::sf::cmif::detail::BufferArgumentInfo<0, 26, 64ul>, nn::sf::cmif::detail::InRawArgumentInfo<16ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l> >, 24ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 26, 64ul>, nn::sf::cmif::det
ail::InRawArgumentInfo<16ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::deta
il::MessageType)4> > >::ProxyBaseObject*, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<16ul, 8ul, void>, nn::sf::cmif::client::InRawClientArgumentType<1ul, 1ul, void>, unsigned int)
   sdk:0x00125af4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::friends::detail::ipc::IFriendService, nn::sf::cmif::client::CmifDomainProxy<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::Messag
eType)4> > >, nn::sf::MemoryResourceAllocationPolicy, nn::friends::detail::ipc::IFriendService>::_nn_sf_sync_GetPlayHistoryRegistrationKey(nn::sf::Out<nn::friends::PlayHistoryRegistrationKey, void>, nn::account::Uid const&, bool)
   sdk:0x0011da7c nn::friends::GetPlayHistoryRegistrationKey(nn::friends::PlayHistoryRegistrationKey*, nn::account::Uid const&, bool)
   sdk:0x0011dacc nn::friends::GetPlayHistoryRegistrationKey(nn::friends::PlayHistoryRegistrationKey*, bool)
   main:0x003b5cb0 Sub00000000083b9cb0
   main:0x003b57a8 Sub00000000083b97a8
   main:0x002d85b8 Sub00000000082dc5b8
   main:0x002d9168 Sub00000000082dd168
   main:0x002d7acc Sub00000000082dbacc
   sdk:0x00091b48 Sub000000001017ab48
   sdk:0x00095b24 Sub000000001017eb24
   ??? Sub0000000000000000

Buffer Information:
        RecvListBuff:
        Position: 0x00000010110b58d0 Size: 0x0000000000000040

Raw Request Data:
00000000   01 00 28 00 02 00 00 00  00 00 00 00 00 00 00 00   ··(·············
00000010   53 46 43 49 00 00 00 00  CC 29 00 00 00 00 00 00   SFCI····Ì)······
00000020   00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00   ················
00000030   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000040   D0 58 0B 11 10 00 40 00                            ÐX····@·

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

#### Log file :

[snk-heroines-tag-team-frenzy.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4668544/snk-heroines-tag-team-frenzy.log)

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by SeraUX** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
