### ISSUE TITLE
Shining Resonance Refrain

### ISSUE THREAD

**Issue by acceleratorlastorder** [Ryujinx/Ryujinx-Games-List#133]
#### Current on `master` :

*Build Version : *(1.0.2090)**

Screen stays black there is no intro or menu shown before the exception.

Last error returned.
`Unhandled Exception: System.NotImplementedException: fsp-srv IFileSystemProxy: 53`

https://reswitched.github.io/SwIPC/ifaces.html#nn::fssrv::sf::IFileSystemProxy(53)

#### Log file :
```00:01:04.510 | 0007 ServiceNv Create: Created map 453 with size 0x00400000!
00:01:04.576 | 0007 ServiceNv Create: Created map 454 with size 0x000a8000!
00:01:04.672 | 0007 ServiceNv Free: Deleted map 454!
00:01:04.673 | 0007 ServiceNv Free: Deleted map 453!
00:01:06.526 | 0007 ServiceNv Create: Created map 453 with size 0x00400000!
00:01:06.594 | 0007 ServiceNv Create: Created map 454 with size 0x00010000!
00:01:06.665 | 0007 ServiceNv Free: Deleted map 454!
00:01:06.666 | 0007 ServiceNv Free: Deleted map 453!
00:01:14.691 | 0007 ServiceAm EnsureSaveData: Stubbed.

Unhandled Exception: System.NotImplementedException: fsp-srv IFileSystemProxy: 53
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx Context) in Ryujinx.HLE\HOS\Services\IpcService.cs:line 83
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch Device, KProcess Process, MemoryManager Memory, KSession Session, IpcMessage Request, Int64 CmdPtr) in Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 33
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.ProcessIpcRequest(Object State) in Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 236
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by HorrorTroll** [comment]
Updated some screenshot :ok_hand:

**Comment by AcK77** [comment]
Need an update.

**Comment by GoffyDude** [comment]
## Shining Resonance Refrain

#### Current on `master` : 1.0.3937

Black screen/missing graphics intro w/ music playing. This can be skipped with the + button, leading to the title screen. 
Loading a game works properly but cutscenes do not render any graphics. In-game graphics contain minor corruption/inaccuracies. Playable otherwise.


```
GUI.RenderLoop Gpu PrintLog: Shader translator: Invalid instruction at 0x0003F8 (0xF0F0000034170000).
```

#### Screenshots :

![2020-03-21 09_09_18-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229712-0fd17980-6b55-11ea-8a12-74b519c950de.png)
![2020-03-21 09_09_25-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229715-106a1000-6b55-11ea-9799-2dc0ca39aba9.png)
![2020-03-21 09_11_02-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229716-106a1000-6b55-11ea-84ed-88c309816f05.png)
![2020-03-21 09_11_29-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229730-18c24b00-6b55-11ea-9ac0-10420fc044f8.png)
![2020-03-21 09_11_43-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229735-21b31c80-6b55-11ea-8cd5-cb27b751110a.png)
![2020-03-21 09_12_05-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229749-28419400-6b55-11ea-871e-da84d0692324.png)
![2020-03-21 09_13_06-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229750-28da2a80-6b55-11ea-9070-ddc78b42c643.png)
![2020-03-21 09_13_15-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229757-31326580-6b55-11ea-9960-b8664165fb77.png)
![2020-03-21 09_13_37-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229765-3b546400-6b55-11ea-81ab-5e0558baf5d6.png)
![2020-03-21 09_15_25-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229770-460ef900-6b55-11ea-99b7-42242f892676.png)
![2020-03-21 09_16_02-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229773-4c9d7080-6b55-11ea-9855-752df6004398.png)
![2020-03-21 09_16_09-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229774-558e4200-6b55-11ea-8714-421cb454b5c1.png)
![2020-03-21 09_16_15-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229779-5f17aa00-6b55-11ea-9343-b0abce3925ff.png)
![2020-03-21 09_17_14-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229782-68a11200-6b55-11ea-9c50-bbdaf30cbdf6.png)
![2020-03-21 09_18_02-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229790-70f94d00-6b55-11ea-853c-12e784b1fb9b.png)
![2020-03-21 09_18_10-Ryujinx 1 0 3937 _ Shining Resonance Refrain _ 01009A5009A9E000](https://user-images.githubusercontent.com/62343878/77229796-78205b00-6b55-11ea-9cfa-9a6eaf6c1dc0.png)


#### Log file :

[ShiningResonanceRefrain.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4363172/ShiningResonanceRefrain.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by benderscruffy** [comment]
using 1.0.6020
show cut-scenes now 
no problems so far

**Comment by EmulationFanatic** [comment]
Updated
