### ISSUE TITLE
Child of Light

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1356]
#### Current on `master` : 1.0.4609

Crashes on launch. Error shows only in the console.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at OpenTK.Graphics.OpenGL.GL.DrawArrays(OpenTK.Graphics.OpenGL.PrimitiveType, Int32, Int32)
   at Ryujinx.Graphics.OpenGL.Pipeline.DrawImpl(Int32, Int32, Int32, Int32)
   at Ryujinx.Graphics.OpenGL.Pipeline.Draw(Int32, Int32, Int32, Int32)
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(Ryujinx.Graphics.Gpu.State.GpuState, Int32)
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(Ryujinx.Graphics.MethodParams, Ryujinx.Graphics.Gpu.ShadowRamControl)
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(Ryujinx.Graphics.Gpu.State.GpuState, Int32)
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[], Ryujinx.Graphics.Gpu.State.GpuState)
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[], Int32, Int32, Ryujinx.Graphics.Gpu.ShadowRamControl, Ryujinx.Graphics.Gpu.State.GpuState)
   at Ryujinx.Graphics.Gpu.NvGpuFifo+CachedMacro.Execute(Int32[], Ryujinx.Graphics.Gpu.ShadowRamControl, Ryujinx.Graphics.Gpu.State.GpuState)
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(Ryujinx.Graphics.MethodParams)
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32)
   at Ryujinx.Graphics.Gpu.DmaPusher.Step()
   at Ryujinx.Ui.GlRenderer.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[CoL.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4673537/CoL.zip)

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by EmulationFanatic** [comment]
Still crashes here.

**Comment by benderscruffy** [comment]
![child](https://user-images.githubusercontent.com/2696404/95982335-97b10500-0e52-11eb-9ce9-b4702dec79b4.PNG)

**Comment by EmulationFanatic** [comment]
I have another PC with an AMD GPU I can test on. Perhaps that's the difference.

**Comment by benderscruffy** [comment]
@EmulationFanatic  any luck getting this to run yet

**Comment by EmulationFanatic** [comment]
Updated
