### ISSUE TITLE
Super Smash Bros. Ultimate

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#136]
#### Current on `master` :

* Build Version : 1.0.2123

```
Unhandled Exception: System.NotImplementedException: vi:m IApplicationDisplayService: 2102
```

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: friend:u IServiceCreator: 1
```

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: bcat:u IDeliveryCacheStorageService: 10
```

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: mii:e
```

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: nifm IGeneralService: 1
```

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: nifm IGeneralService: 21
```

Implement that, and then crash:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.Gal.Shader.GlslDecompiler.GetAttrTempName(ShaderIrOperAbuf Abuf) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Gal\Shader\GlslDecompiler.cs:line 877
   at Ryujinx.Graphics.Gal.Shader.GlslDecompiler.PrintNode(ShaderIrBlock Block, ShaderIrNode Node, String Identation) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Gal\Shader\GlslDecompiler.cs:line 638
   at Ryujinx.Graphics.Gal.Shader.GlslDecompiler.PrintNodes(ShaderIrBlock Block, ShaderIrNode[] Nodes) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Gal\Shader\GlslDecompiler.cs:line 574
   at Ryujinx.Graphics.Gal.Shader.GlslDecompiler.PrintBlockScope(ShaderIrBlock[] Blocks, String Name) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Gal\Shader\GlslDecompiler.cs:line 560
   at Ryujinx.Graphics.Gal.Shader.GlslDecompiler.Decompile() in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Gal\Shader\GlslDecompiler.cs:line 170
   at Ryujinx.Graphics.Gal.OpenGL.OGLShader.ShaderStageFactory(IGalMemory Memory, Int64 Position, Int64 PositionB, Boolean IsDualVp, GalShaderType Type) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Gal\OpenGL\OGLShader.cs:line 69
   at Ryujinx.Graphics.Gal.OpenGL.OGLShader.<>c__DisplayClass12_0.<Create>b__0(Int64 Stage) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Gal\OpenGL\OGLShader.cs:line 39
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Ryujinx.Graphics.Gal.OpenGL.OGLShader.Create(IGalMemory Memory, Int64 Key, GalShaderType Type) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Gal\OpenGL\OGLShader.cs:line 39
   at Ryujinx.Graphics.Graphics3d.NvGpuEngine3d.UploadShaders(NvGpuVmm Vmm) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Graphics3d\NvGpuEngine3d.cs:line 319
   at Ryujinx.Graphics.Graphics3d.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, GpuMethodCall MethCall) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Graphics3d\NvGpuEngine3d.cs:line 113
   at Ryujinx.Graphics.Graphics3d.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, GpuMethodCall MethCall) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Graphics3d\NvGpuEngine3d.cs:line 81
   at Ryujinx.Graphics.Graphics3d.MacroInterpreter.Send(NvGpuVmm Vmm, Int32 Value) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Graphics3d\MacroInterpreter.cs:line 411
   at Ryujinx.Graphics.Graphics3d.MacroInterpreter.Step(NvGpuVmm Vmm, Int32[] Mme) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Graphics3d\MacroInterpreter.cs:line 193
   at Ryujinx.Graphics.Graphics3d.MacroInterpreter.Execute(NvGpuVmm Vmm, Int32[] Mme, Int32 Position, Int32 Param) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Graphics3d\MacroInterpreter.cs:line 83
   at Ryujinx.Graphics.Graphics3d.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, GpuMethodCall MethCall) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Graphics3d\NvGpuFifo.cs:line 161
   at Ryujinx.Graphics.Graphics3d.NvGpuFifo.CallMethod(NvGpuVmm Vmm, GpuMethodCall MethCall) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\Graphics3d\NvGpuFifo.cs:line 91
   at Ryujinx.Graphics.DmaPusher.CallMethod(Int32 Argument) in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\DmaPusher.cs:line 183
   at Ryujinx.Graphics.DmaPusher.Step() in D:\Games\Ryujinx-SSBU\Ryujinx.Graphics\DmaPusher.cs:line 90
   at Ryujinx.GlScreen.RenderLoop() in D:\Games\Ryujinx-SSBU\Ryujinx\Ui\GLScreen.cs:line 67
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

Fix that, and then crash:
```
Unhandled Exception: System.NotImplementedException: time:u IStaticService: 400
```

Implement that, and then crash:
```
Unhandled Exception: System.NotImplementedException: appletOE IApplicationFunctions: 26
```

*I'm using GTX 950M (which it's use GM107 the first Maxwell generation, doesn't support gl_ViewportIndex). So i drop the issue at here, need someone try and help me complete this issue. Thanks for reading this*

#### Pull requests needed :

https://github.com/Ryujinx/Ryujinx/pull/529

#### Screenshots :

![image](https://user-images.githubusercontent.com/24840279/49594083-ad785800-f9a7-11e8-995e-1c2ec88fbe5d.png)
![image](https://user-images.githubusercontent.com/24840279/49717104-83b18080-fc88-11e8-995a-3200e32e925a.png)
![image](https://user-images.githubusercontent.com/24840279/49717112-890ecb00-fc88-11e8-96d6-d6bfee7f79be.png)
![image](https://user-images.githubusercontent.com/24840279/49717125-9330c980-fc88-11e8-834d-9c32d1a61975.png)
![image](https://user-images.githubusercontent.com/24840279/49717127-96c45080-fc88-11e8-8f4b-4a93279c07fe.png)
![image](https://user-images.githubusercontent.com/24840279/49717137-9deb5e80-fc88-11e8-90b8-75180c32f117.png)
![image](https://user-images.githubusercontent.com/24840279/49717166-b2c7f200-fc88-11e8-9309-7221ba429383.png)

**Comment by AlexLavoie42** [comment]
I'm running a 1070, so I will try and see what I can do.

**Comment by AcK77** [comment]
Needs an update!

**Comment by ReaperOfSouls1909** [comment]
![BF7269E0-4928-4BBF-AF3C-084B10480422](https://user-images.githubusercontent.com/18043258/76041362-48a00a80-5f28-11ea-8e07-bdefc2905812.jpeg)
Boots on master with a save and ignored services on t-pose effects 7.0.0 and massive flicker build 1.0.3841

**Comment by Thog** [comment]
Reported by a user on discord, possible regression on version 1.0.4114 (game version tested 3.0.0, 6.1.1 and 7.0.0)

Happens in training mode and on title screen apparently.

Logs: [Ryujinx_2020-04-03_09-04-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4427675/Ryujinx_2020-04-03_09-04-28.log)

**Comment by drunlade** [comment]
### Verison 1.0.4593
* Boots
* Intro video doesn't work
* Menus work correctly
* Game is playable, but suffers slowdown & stutter (shader compilation I guess?)
* Many shader errors in logs
* Various graphical glitches (spiky polygons, etc)

**Comment by Leischii** [comment]
Super Smash Bros Ultimate

Version 8.0.0

Master, Build 4829

The game is playable but not perfect. The game doesn't have any crashes when it comes to playing the base game (Normal smash fights with "ignore missing services" enabled), World of Light and other features not tested.

Hardware Specs : 

CPU: Amd Ryzen 5 3600 6x 3,6 Ghz 
GPU: Geforce Gtx 950
RAM: 16 Gb

Issues:

- Intro video (and maybe other videos if there are) don't render --> blackscreen until it's over or skipped

- Vertex explosions all over the screen while playing. How bad it is seems to be based on how expensive the character is (means less vertex explosions for a character like mario than for a character like ice climbers since the character is two in one)
Reference: Video 1 and 2

- Every character (One you haven't fought before) needs to use all his abilitys once before they stop causing extreme freezes and stutters (Propably fine afterwards because of PPTC). Makes "challenger approaching" always hard due to a lot of freezes.

- Marios Special-Up attack (The one that makes him spawn coins when he hits an enemy with it) sometimes spawns purple coins instead of yellow ones.

Screenshots:

https://i.gyazo.com/0bb39c0e26571dfe9cf73d8ce3ff8146.jpg
https://i.gyazo.com/fc123d482966f43139e473980de8c0e4.jpg
https://i.gyazo.com/463bebef0730abdda8249024de36b990.jpg
https://i.gyazo.com/b130273da67cbb40031aa6fb2e3a0b15.jpg

Video:

https://i.gyazo.com/29ad2e1433696c67a51ae8af3305a2bd.mp4
https://i.gyazo.com/ced6b1f7128ea82e6cae779a0e66d920.mp4

Log file :

[Ryujinx_2020-07-04_16-34-48.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4873053/Ryujinx_2020-07-04_16-34-48.log)

Additonal Info:

-Once initial loading for characters is done, the game runs most of the time with stable 60 fps. Just a few stutters here and there.

- No save file required. Not sure when this got fixed. Currently unlocked 7 characters with approching challengers without a single crash. Ignore missing services is activated.

- No T-poses anymore

**Comment by thomas11311** [comment]
the "mario up special purple coin" thing is intended.
that's part of the real game.
https://www.reddit.com/r/smashbros/comments/ajlx80/why_does_marios_up_b_make_purple_coins_sometimes/

**Comment by greggameplayer** [comment]
https://github.com/Ryujinx/Ryujinx/issues/1233

**Comment by EmulationFanatic** [comment]
@greggameplayer that crash only happens if you try to go online, which is not supported anyway.

**Comment by greggameplayer** [comment]
@EmulationFanatic for me it happened when booting the game

**Comment by drunlade** [comment]
@greggameplayer Did you happen to be using the experimental LDN2 branch with LAN mode enabled? Just a thought that that could cause bonus network access that otherwise wouldn't take place.

**Comment by greggameplayer** [comment]
@drunlade yes, i enabled lan mode

**Comment by EmulationFanatic** [comment]
@greggameplayer it is advised to disable LAN mode unless you are using a game that supports it.

**Comment by greggameplayer** [comment]
@EmulationFanatic i doesn't know that you have to disable this setting to use games which doesn't support it

**Comment by EmulationFanatic** [comment]
It doesn't cause issues with all games when left on. But in general it's best to leave it off unless it's being actively used.

**Comment by superbros45** [comment]
is the world of light mode playable? i've used several other emulator but the world of lights mode just not playable

**Comment by Leischii** [comment]
Super Smash Bros Ultimate
Version 10.1.0
Master, Build 1.0.6324

The game is working pretty good, almost perfect. Once shaders are generated, fps are pretty much stable 60 fps. No reproducable crashes I was able to find (World of light not tested).

Hardware Specs :
CPU: Amd Ryzen 5 3600 6x 3,6 Ghz
GPU: Geforce Gtx 950
RAM: 16 Gb

Issues:
- When you start the game, the intro video and main menu will have some stuttering in the beginning. This stops after around 20 seconds. 
Example: 
Menu Lagging: https://i.gyazo.com/57834671f3016b1060c3aed5888dee4d.mp4
Menu not lagging: https://i.gyazo.com/55d815795a8ab2f947d05fa0ce7f8b56.mp4
(Info for developers: The problem occurs since around the time shader cache was added to Ryujinx, tho it also happens on builds early than that. Disabling shader cache seems to help with that problem, doesn't happen on every boot without it) 

- After a match there is a high chance for the game to drop to 0 fps and 0% fifo for some time, forcing you to wait a few minutes between matches. Pressing buttons seems to help sometimes.
Example: https://i.gyazo.com/5994b839ccadeee16e8a917b982461c4.mp4

- Due to some problems with the gpu memory managment, the game will crash at random points. Usually the chance for it to crash increases the longer your game is opened.

- Minecraft Steve has some graphic glitches where the ores in his crafting menu are pixelated and not recognizable. Doesn't affect gameplay.

- Random texture corruptions can happen, but are VERY unlikely. Only saw it once
Example: https://i.gyazo.com/f6dddc05f12bf09b0080b47955d791f5.png

Additonal Infos:
- Works in ldn2. I recommend preloading shaders, but starting without and using each ability once works aswell in most cases (But you will experience stutters and freezes)

- Annoying bugs that have been fixed: T-poses, most shader freezes, vertex explosions.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by NSgopi2001** [comment]
super smash bros ultimate spirits adventure keep crashing help pls

**Comment by drunlade** [comment]
@NSgopi2001 This isn't the right place for such comments. This page is for detailed compatibility reporting, as seen above in previous comments.

I'd suggest checking the discord server or a forum somewhere. However, the likely response is going to be along the lines of "This is an experimental emulator, many games are very likely to crash and there's not a lot you can do about it".

**Comment by EmulationFanatic** [comment]
Spirits/adventure mode simply doesn't work yet in the emulator. No mystery or unexpected behavior there.

**Comment by LukeWarnut** [comment]
When going into Vault > Sounds > Music, selecting a song, then exiting while the song is still playing, the game will crash with a missing service error.

```
00:02:03.827 |E| HLE.OsThread.5 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ICommonStateGetter: 52

Guest Stack Trace:
Process: Service, PID: 82

Raw Request Data:
00000000   01 00 11 00 05 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  34 00 00 00 00 00 00 00   SFCI····4·······
00000020   00 00 00 00 00 00 00 00  00 00 00 00               ············    

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 148
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by UND3RD0G5335** [comment]
is it possible to play online?

**Comment by drunlade** [comment]
> is it possible to play online?

I'm not a dev, but pretty sure the answer is "No" and you won't ever be able to. Online is where Ninty lawyers live ;)

LDN on the other hand, I imagine support for that is coming along.

**Comment by defunky** [comment]
Boots ingame and can access menu, pressing anything under smash menu causes black screen.
Using 1.0.6819 with Smash v11.0.0

**Comment by sidoka-contact** [comment]
boots ingame and can access menu, but pressing anything under smash sub menu, like smash button, still causes black screen,
using 1.0.6896 with smash v11.0.1,
[the crash message](https://github.com/Ryujinx/Ryujinx-Games-List/files/6565416/smash.n.crash.txt),

**Comment by EmulationFanatic** [comment]
@defunky and @sidoka-contact you need a save file to bypass this

**Comment by sidoka-contact** [comment]
@EmulationFanatic oh thank you kind sir

**Comment by meisiek** [comment]
With version 1.0.0, no DLC and "ignore missing services" adventure mode fights are working. Without "ignore missing services" it still crashes when entering a fight.
I saved the game and changed back to version 11.0.1 and it still works.
After that I added all DLCs and can still enter the fight in adventure mode.

Very strange. It is as if the save game from version 1.0 and maybe the cached shaders and PPC prevents further crashes when entering a fight.

**Comment by MutantAura** [comment]
Matches with above 3 players will have "instant" loads in subsequent games after the first. 
Video below shows Ryujinx 1.0.6946, a TTC PR based on said version, yuzu 1848 also exhibiting this behaviour (control) and real hardware: https://www.youtube.com/watch?v=-B-s9zhB7sU

Effect is seen in 4, 5, 6, 7 and 8 player matches. When switching to 3 or 1v1 matches the effect can no longer be seen and regular load times return.

**Comment by Arekkusuda** [comment]
## Super Smash Bros Ultimate

#### Game Update Version : 12.0.0

#### Current on `master` : 1.0.6961

The game is playable. That is it, playable. I wouldn't call it enjoyable. It stutters and freezes, a lot, and I mean,  A LOT. The intro, the character select menu. The first battle couldn't even be called playable. It stabilizes a little after some fights, but it still stutters and freezes too much for it being enjoyable. There was also a little bug where Yoshi's arm stretched out of stage

#### Fixed Issues:
World of Light and Spirit Board are now playable
The big freeze after matches didn't happen to me in any of my matches
Minecraft Steve graphic glitches are fixed now

#### Hardware Specs : 

#### CPU: Intel Core i5-9300H
#### GPU: NVIDIA GTX 1660 Ti Max-Q
#### RAM: 8 GB

#### Screenshots :

![Ryujinx_iZLSqDdSQo](https://user-images.githubusercontent.com/83657761/125212005-a86a9c00-e267-11eb-98de-46d167160980.png)

![Ryujinx_3aClAzqeyq](https://user-images.githubusercontent.com/83657761/125212007-aa345f80-e267-11eb-9d1b-01df3d3f52c8.jpg)

![Ryujinx_whFVZ4g4wB](https://user-images.githubusercontent.com/83657761/125212011-ae607d00-e267-11eb-8df2-e1ee576a5392.jpg)

**Comment by ljmerza** [comment]
> @EmulationFanatic oh thank you kind sir

what save file did you use to get this working?

**Comment by Nakata2021** [comment]
Game not loading after update to 1.0.7000
Error code: 2002-000
![Captura de tela 2021-08-17 205649](https://user-images.githubusercontent.com/89110851/129815559-5c8a517f-5f24-4de4-b4dc-7ae741e7d1d3.jpg)
7

**Comment by VegaBiggs** [comment]
1.0.7047 (and before) For some reason, the game won't show up in my library even though it is an XCI like most of my other games and it works on Yuzu.
It's a v10.1.0+All DLC version of 17 102 691 Ko if it can help.

**Comment by StrixKruiboh** [comment]
https://youtu.be/7Lz9RgEUr1k
In order to replicate pick Ness or Lucas and use PK star storm on fountain of dreams.
[Ryujinx_1.1.282_2022-09-29_18-51-39.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9679590/Ryujinx_1.1.282_2022-09-29_18-51-39.log)

**Comment by Xalavar** [comment]
Smash replays that weren't saved in Ryujinx cannot be played. Additionally, Smash replays that were saved in Ryujinx can't be played in other emulators.

I.e. I backed up some Smash replays (not videos) from my Switch and imported them into Ryujinx. They show up in the game and I can play them, but the replays stop after the first few seconds. 
Both versions of Smash match, and so do the replays they were saved from.

**Comment by Blackdemize** [comment]
I have a problem after beating a CPU (Computer) in a match , A new challenger name  Ken from SF will show up which causes my game to lag/stick then Ryujinx would come off for itself and whenever i start it over and i fight and win against CPU it keep's doing it over and over again other than that everything works fine.

If there is any tips to stop it from happening it would help me a lot.

**Comment by zrksyd** [comment]
On my Intel GPU, Vulkan runs way better than OpenGL. However, using the Vulkan backend and picking the Boxing Ring stage will cause Ryujinx to close. Right before Ryujinx closes, this error will appear:
![image](https://user-images.githubusercontent.com/6856627/200201665-633aa2c3-0ad2-445c-9714-8cbb8c518ebd.png)


Here is my log from Vulkan:
[Ryujinx_1.1.338_2022-11-06_18-18-25.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9947091/Ryujinx_1.1.338_2022-11-06_18-18-25.log)

I tried using OpenGL just to see if that hard crash would occur. Although it does not crash, it does appear like this:
![image](https://user-images.githubusercontent.com/6856627/200200700-63fb129c-ba67-43ca-81ce-548dddfbfc4d.png)

Here is my log from my OpenGL experiment:
[Ryujinx_1.1.338_2022-11-06_18-04-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9947060/Ryujinx_1.1.338_2022-11-06_18-04-44.log)

**Comment by CentinelaYT** [comment]
How i can downland it?

**Comment by elchoma01** [comment]
After downloading 16000 shaders with ryusak, Ryujinx is just unable to load the game, crashing when it has compiled the first 6400. The game can run again when I purge the shader cache. 

I´m testting this in a M1 Pro Mac. Same issue trying with the first version of the game or 3.0. 
Ryujinx 1.1.0.
Ryusak 1.6

**Comment by zed213** [comment]
Currently have a problem with keeping a constant 60 fps due to stutters despite having a fully built shader cache. I've read something about NRO causing stutters in smash, but that was in the February 2022 Report and it had no solutions posted. Was this issue ever addressed again and fixed or is it still an ongoing problem?

**Comment by Huffee** [comment]
Having an issue with Joker's Arsene powerup, whenever it's on screen the game's framerate drops heavily going from stable 120fps (even in 4 player matches) to sometimes 70-80 (in 2 player matches) during certain moves, even after loading the shaders/NROs.

This is of course using the 120fps mod since my pc can keep above 60 even when Arsene is on screen but I assume it would be problematic on less powerful PCs at the game's native framerate.

If needed the steps necessary to reproduce are:
In the main menu select games and more > training.
Pick any stage, select Joker as your character and press start.
Pause the game, select "Other Settings" and under "P1 Damage %" set it to 999 (by pressing left)
This should activate Arsene for a short time.

I would also like to add that a fix to the NRO stutter situation would be very appreciated, a pull request that fixed it exists but it never got merged to the main branch.

**Comment by Finebouche** [comment]
hi and thank you for the development of Ruyjinx.

I have a minor issue concerning loading time at start. The full shader compilation takes a hell of a time. Is there a way to speed up this compilation or to do it once and for all ?

**Comment by taiwan-king** [comment]
game crash on boot
[Ryujinx_1.1.1217_2024-03-03_13-14-27.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14471864/Ryujinx_1.1.1217_2024-03-03_13-14-27.log)

**Comment by BOB5941** [comment]
Game crashes on boot in Vulkan, however it works perfectly in OpenGL

Hardware:
CPU: i5-1135G7
GPU: Intel Iris Xe
RAM: 12Gb

**Comment by DevilAXE** [comment]
I have an rx580 and an i5-3570K cpu and many games run correctly on my pc except smash bros which loads with its logo at startup and then stays on a black screen. The only notable error in the log is "HLE.OsThread.11 SurfaceFlincher OnTransact: Error returned by transaction Disconnect: Bad Value".

**Comment by bananadonut** [comment]
Similar to Bob, game crashes on vulkan after getting to the menu. OpenGL laggy a ton for me

Hardware:
CPU: amd 5800x3d
GPU: amd 7800xt
RAM: 16gb
[Ryujinx_1.1.1223_2024-03-11_02-15-15.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14556195/Ryujinx_1.1.1223_2024-03-11_02-15-15.log)

**Comment by Okamiissun** [comment]
Ryujinx crash on fight start
Hardware
Os win 11
Cpu i7-12700f
Gpu nvidia geoforce 4070
Ram 32gb
[Ryujinx_1.1.1277_2024-04-11_04-12-42.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14944468/Ryujinx_1.1.1277_2024-04-11_04-12-42.log)

**Comment by TheFunIsInfinite** [comment]
Every time i try to open smash, it never opens, it simply crashes ryujinx

**Comment by mrTerryBogard** [comment]
Good day!
Last 2 updates exactly. I don't update often, so I can't trace when it started. But since I updated to the previous version of Ruyjinx and noticed that this is the case for me. But this is confirmed by other players.

After the previous update, Super Smash Bros. started to slow down. Ultimate. Ryujinx in the menu shows a stable approximately 30 FPS. If there are no drawdowns when choosing arenas, then these same 30 FPS begin when choosing a player. The change in speed of SSBU is noticeable. But what’s more, during the battle the average FPS is 10-15, which gives noticeable drawdowns.

What did you do with the update?

**Comment by DGHoed** [comment]
Whenever I start smash on the emulator, i get this error message and a crash...
![image_2024-06-16_110952093](https://github.com/Ryujinx/Ryujinx-Games-List/assets/172961493/61fc3150-f543-41ca-9b5d-091e5ba7666a)

**Comment by TheFrenchToast7** [comment]
where is the download link???

why not make it obvious where it is, its literally the most important part of the post XO

**Comment by HackMeMan** [comment]
Spirit mode works now. Same for the Steve glitch. The intro doesn't bug for me. Only issues that still happen for me is the 0 FPS during loading bug and the VRAM filling up (possible memory leak?)

**Comment by Feenikscythe** [comment]
In Adventure mode, I am experiencing semi frequent crashes in adventure mode. every time but once it has occurred as a spirit battle was loading or finishing (not in battle). the one other time was in the middle of a battle but i didn't think to grab a log of that one specific time. attaching my most recent log here. 
[Ryujinx_1.1.1386_2024-09-14_17-46-29.log](https://github.com/user-attachments/files/17004016/Ryujinx_1.1.1386_2024-09-14_17-46-29.log)

**Comment by Feenikscythe** [comment]
just had it happen in the middle of battle again. here's the log
[Ryujinx_1.1.1386_2024-09-14_18-31-31.log](https://github.com/user-attachments/files/17004033/Ryujinx_1.1.1386_2024-09-14_18-31-31.log)
