### ISSUE TITLE
Moero Chronicle Hyper

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1362]
#### Current on `master` : 1.0.4613

Game crashes on boot

```
Last error returned.
00:00:15.482 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000002f11cc4 (opcode 0xf2c0617f) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
```
#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1005
#### Log file :

[moero-chronicle-hyper.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4677451/moero-chronicle-hyper.log)

**Comment by EmulationFanatic** [comment]
Closing in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/182
