### ISSUE TITLE
Crossing Souls

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1364]
#### Current on `master` : 1.0.4613

Has nvdec cutscene issue on intro and after starting a new game. This cannot be skipped.
Otherwise was fully playable until crashing about 14 minutes in.

```
HLE.HostThread.9 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetRef[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 207
   at ARMeilleure.Instructions.NativeInterface.ReadVector128Exclusive(UInt64 address) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 258
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 98
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-05-25 12_11_14-Ryujinx 1 0 4613 - Crossing Souls v1 0 0 (0100B1E00AA56000) (64-bit)](https://user-images.githubusercontent.com/62343878/82835942-ae929300-9e82-11ea-85e2-f609815fa843.png)

![2020-05-25 12_12_03-Ryujinx 1 0 4613 - Crossing Souls v1 0 0 (0100B1E00AA56000) (64-bit)](https://user-images.githubusercontent.com/62343878/82835890-902c9780-9e82-11ea-961f-839614d2da90.png)
![2020-05-25 12_12_24-Ryujinx 1 0 4613 - Crossing Souls v1 0 0 (0100B1E00AA56000) (64-bit)](https://user-images.githubusercontent.com/62343878/82835895-91f65b00-9e82-11ea-8552-2879d2e1c3a2.png)
![2020-05-25 12_17_58-Ryujinx 1 0 4613 - Crossing Souls v1 0 0 (0100B1E00AA56000) (64-bit)](https://user-images.githubusercontent.com/62343878/82835896-91f65b00-9e82-11ea-8234-357ce3224927.png)
![2020-05-25 12_18_51-Ryujinx 1 0 4613 - Crossing Souls v1 0 0 (0100B1E00AA56000) (64-bit)](https://user-images.githubusercontent.com/62343878/82835902-93278800-9e82-11ea-944b-bd3fc2812b17.png)
![2020-05-25 12_19_07-Ryujinx 1 0 4613 - Crossing Souls v1 0 0 (0100B1E00AA56000) (64-bit)](https://user-images.githubusercontent.com/62343878/82835905-9458b500-9e82-11ea-993e-8b6a3e68a95e.png)
![2020-05-25 12_21_01-Ryujinx 1 0 4613 - Crossing Souls v1 0 0 (0100B1E00AA56000) (64-bit)](https://user-images.githubusercontent.com/62343878/82835907-94f14b80-9e82-11ea-9848-d7fccfb75b8c.png)
![2020-05-25 12_21_06-Ryujinx 1 0 4613 - Crossing Souls v1 0 0 (0100B1E00AA56000) (64-bit)](https://user-images.githubusercontent.com/62343878/82835910-96227880-9e82-11ea-9d80-bfece5a93584.png)
![2020-05-25 12_21_14-Ryujinx 1 0 4613 - Crossing Souls v1 0 0 (0100B1E00AA56000) (64-bit)](https://user-images.githubusercontent.com/62343878/82835913-9753a580-9e82-11ea-9e02-9387d181946f.png)

#### Log file :

[CS.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4678449/CS.zip)

**Comment by EmulationFanatic** [comment]
Updated
