### ISSUE TITLE
Groove Coaster: Wai Wai Party!!!!

### ISSUE THREAD

**Issue by LingFeng-bbben** [Ryujinx/Ryujinx-Games-List#1365]
#### Current on `master` : 1.0.4613

Game loaded successfully but start getting stucked in tutorial. The memory amount of the game started to grow quickly and crash at almost 10G. 

Error when memory started to grow.
```
00:01:00.841 | HLE.HostThread.0 KernelSvc PrintResult: ResetSignal64 returned error InvalidHandle.
```
Last error returned.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.VoiceContext.UpdateBuffer(MemoryManager memory) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\VoiceContext.cs:line 143
```

**Comment by SuperOkazaki** [comment]
Just reporting in to say that as of Ryujinx 1.0.5182, the game is perfectly playable with little to no bugs and at fullspeed, using version 1.0.2 of the game.

AMD R9 3900X
RTX 2070

**Comment by EmulationFanatic** [comment]
Updated

**Comment by thomeval** [comment]
Tested with the 1.0.0-ldn2.1 build. It is possible to host and join a local wireless room, but attempting to start a game will cause a crash for players that aren't the host.

Stack Trace:
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Ryujinx.HLE.HOS.Services.Ldn.UserServiceCreator.RyuLdn.Proxy.LdnProxySocket.Connect(EndPoint remoteEP) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\Ldn\UserServiceCreator\RyuLdn\Proxy\LdnProxySocket.cs:line 290
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient.Connect(ServiceCtx context) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\Sockets\Bsd\IClient.cs:line 751
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 114
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 216
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\project\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Ryujinx.HLE.HOS.Services.Ldn.UserServiceCreator.RyuLdn.Proxy.LdnProxySocket.Connect(EndPoint remoteEP) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\Ldn\UserServiceCreator\RyuLdn\Proxy\LdnProxySocket.cs:line 290
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient.Connect(ServiceCtx context) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\Sockets\Bsd\IClient.cs:line 751
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 114
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 216
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\project\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\project\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by thomeval** [comment]
Tested with the 1.0.0-ldn2.4 build. The results are the same as mentioned above with the ldn2.1 build.
