### ISSUE TITLE
Minecraft Dungeons

### ISSUE THREAD

**Issue by Seker-0** [Ryujinx/Ryujinx-Games-List#1368]
#### Current on `master` : 1.0.4613

The game crashes after passing through the game introduction page
intro will be nvdec, you can't skip it You must wait until you reach the game menu page

```
HLE.HostThread.2 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000a270d28 (opcode 0x6e30c800) is undefined!
```

#### Screenshots : 
![MD](https://user-images.githubusercontent.com/35269098/82900716-25b14f80-9f87-11ea-9755-09fc207407c1.jpg)

#### Logs : 
[MD.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4682144/MD.log)

**Comment by SeraUX** [comment]
## Game Name

#### Current on `master` : 1.0.4682

On the first try without ignore missing services enabled, game crashed with missing service error 


```
00:00:38.069 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Ssl.SslService.ISslContext: 4

Guest Stack Trace:
Process: Dungeons, PID: 81
   sdk:0x002bc340 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> >, 4ul, 8ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<8ul, 8ul>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, unsigned int)
   sdk:0x002bafb4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::ssl::sf::ISslContext, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatefulAllocationPolicy<nn::sf::ExpHeapAllocator>, nn::ssl::sf::ISslContext, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_ImportServerPki(nn::sf::Out<unsigned long, void>, nn::sf::InBuffer const&, nn::ssl::sf::CertificateFormat)
   sdk:0x002b7288 nn::ssl::Context::ImportServerPki(unsigned long*, char const*, unsigned int, nn::ssl::CertificateFormat)
   main:0x02f760b0 Sub000000000af7a0b0
   main:0x033902dc lws_context_init_client_ssl
   main:0x03381280 lws_create_vhost
   main:0x03381734 lws_create_context
   main:0x02f7425c Sub000000000af7825c
   main:0x02f76b18 Sub000000000af7ab18
   main:0x00f9bee0 Sub0000000008f9fee0
   main:0x00f9c1c0 Sub0000000008fa01c0
   main:0x02f9f698 Sub000000000afa3698
   main:0x02f9f584 Sub000000000afa3584
   main:0x00f9bee0 Sub0000000008f9fee0
   main:0x00f9bcb0 Sub0000000008f9fcb0
   main:0x00375e50 Sub0000000008379e50
   main:0x00375ccc Sub0000000008379ccc
   main:0x003755dc Sub00000000083795dc
   main:0x003754b4 Sub00000000083794b4
   main:0x00f9bee0 Sub0000000008f9fee0
   main:0x00fe5584 Sub0000000008fe9584
   main:0x00ff27d4 Sub0000000008ff67d4
   main:0x00ff2218 Sub0000000008ff6218
   main:0x000080f0 Sub000000000800c0f0
   main:0x00002f20 Sub0000000008006f20
   main:0x0000f414 Sub0000000008013414
   sdk:0x000c14a8 Sub0000000010df34a8
   sdk:0x000c58b4 Sub0000000010df78b4
   ??? Sub0000000000000000

Buffer Information:
        SendBuff:
        Position: 0x00000009c22e0000 Size: 0x000000000003782a Flags: 0

Raw Request Data:
00000000   01 00 14 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  04 00 00 00 00 00 00 00   SFCI············
00000020   01 00 00 00 00 00 00 00  2A 78 03 00 00 00 00 00   ········*x······
00000030   00 00 00 00                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

On the second try with ignore missing services enabled, I got to the menu after waiting for the unskippable nvdec cutscene, but then it immediately crashed
```
00:06:11.357 | HLE.HostThread.2 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1154
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 63

```
#### Outstanding Issues:



#### Screenshots :

![06_05_42-17:42:44](https://user-images.githubusercontent.com/62521228/83897747-4a12e600-a756-11ea-95b7-0aa272a4414b.png)


#### Log file :

[md.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4737236/md.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by nutellabrot155** [comment]
Crash at loading screeen

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6909

**Comment by zyjking** [comment]
Game cannot be started, and the following error message is displayed

![image](https://user-images.githubusercontent.com/37742023/150663534-4e08569c-e0c0-4494-801e-ca52ea1c96de.png)

When loading the unpacked game, another error occurred

![image](https://user-images.githubusercontent.com/37742023/150663601-aa4cac50-a010-4157-85c6-974c5951afb8.png)

Game version: 1.12.2.0

Logfile:
[nsp.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7919675/nsp.log)
[unpacked game.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7919676/unpacked.game.log)

**Comment by TioBenLoko** [comment]
Minecraft Dungeons (01006C100EC08000) , BUG IN LANGUAGE BR-PT.

The brazilian portuguese language is not working. Please check, because the game already has the Brazilian Portuguese language natively, but not working in Ryujinx.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by vamsiac** [comment]
It says p2 to join by pressing L button, but on pressing L on p2 and p3 not able to join.
I already made sure p2 and p3 controllers are connected to Ryujinx.

**Comment by LeaveNhA** [comment]
## Minecraft Dungeons
#### Game Update Version : 1.0.0.6.0
#### Current on `master` : 1.1.1069
#### Graphics Backend : Vulkan

#### Hardware Specs :
##### CPU: M1 Max
##### GPU: M1 Max
##### RAM: 64GB

##### Comment:

Not working, even I can't reach the menu.

**Comment by Falke85** [comment]
Crash on creeper lvl loading screen with "ErrorOutOfDeviceMemory"
tryed with opengl, crashes too, with ram overload end system crash
tutorial lvl runs smooth

my system: 12gb vram 4070ti, 32 gb ram
firmware 18.0
game v. 1.17
Ryujinx_1.1.1297


00:02:21.413 |G| HLE.OsThread.22 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 141s
    ProgramName: Dungeons-Switch-Shipping
    Thread: GameThread
    Filename: D:\BuildAgent\work\e73f2f4964dd839f\Engine\Source\Runtime\Core\Private\Switch\SwitchPlatformMisc.cpp
    Line: 109
    Function: LocalPrint
    Message: ### NAV CHECK ACTOR BP_Flowerpatch_265  is nav relevant, should it be? if not it will be bloating the nav memory

00:02:34.276 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 414089 bytes, profiled functions: 142717).
00:02:37.649 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".

**Comment by Benroads** [comment]
Same issue as above, was able to run through tutorial level with no issues. Attempting to load another level from camp hangs and then crashes a few moments after. With OpenGL it seems to launch the level but lots of performance and stability issues. 

My system:
Windows 10 Version 22H2 (OS Build 19045.4529)
i9 12900K
32GB DDR5 @ 6000
3080 10GB VRAM

Game version 1.17.0.0
Ryujinx version 1.1.1340
