### ISSUE TITLE
RPG Maker MV

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#139]
#### Current on `master` :

* Build Version : 1.0.2234

```
Unhandled Exception: System.NotImplementedException: Ryujinx.HLE.HOS.Services.Vi.IApplicationDisplayService: 2102
```

After that, it's crash
```
 [Application] sdk:0x00225a08 nn::audio::RequestUpdateAudioRenderer(nn::audio::AudioRendererHandle, nn::audio::AudioRendererConfig const*)
 [Application] main:0x01dcac84 Sub0000000009dcec84
 [Application] sdk:0x000af8f4 Sub000000000c9898f4
 [Application] sdk:0x000b3c54 Sub000000000c98dc54
 [Application] sdk:0xfffffffff3725ffc Subfffffffffffffffc


Unhandled Exception: ChocolArm64.Exceptions.VmmPageFaultException: Tried to access unmapped address 0x0000000000008054!
   at ChocolArm64.Memory.MemoryManager.HandleNullPteWrite(Int64 position) in D:\Games\Ryujinx-port\ChocolArm64\Memory\MemoryManager.cs:line 746
   at ChocolArm64.Memory.MemoryManager.WriteUInt32(Int64 position, UInt32 value) in D:\Games\Ryujinx-port\ChocolArm64\Memory\MemoryManager.cs:line 442
   at Sub000000000cafad1c(CpuThreadState , MemoryManager , UInt64 , UInt64 , UInt64 )
   at Sub000000000cafad1c_Dispatch(CpuThreadState , MemoryManager )
   at ChocolArm64.Translator.ExecuteSubroutineA64(CpuThreadState state, MemoryManager memory, Int64 position) in D:\Games\Ryujinx-port\ChocolArm64\Translator.cs:line 69
   at ChocolArm64.CpuThread.<>c__DisplayClass14_0.<.ctor>b__0() in D:\Games\Ryujinx-port\ChocolArm64\CpuThread.cs:line 36
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

#### Pull requests needed :

https://github.com/Ryujinx/Ryujinx/pull/550
https://github.com/Ryujinx/Ryujinx/pull/529/commits/1fe2b366bad03f8676d7914b63e94c167a836f67

#### Screenshots :

![image](https://user-images.githubusercontent.com/24840279/50587149-58990600-0eaf-11e9-943d-9476647f9d73.png)
![image](https://user-images.githubusercontent.com/24840279/50587265-c0e7e780-0eaf-11e9-9730-679a418c991c.png)

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## RPGMaker MV

#### Current on `master` : 1.0.3957

Tried several times and game crashes while loading intros or once it reaches the main menu. Including debug log here.


#### Screenshots :

![2020-03-23 07_12_28-Ryujinx 1 0 3957 _ RPGMAKER MV _ 010033C00985E000](https://user-images.githubusercontent.com/62343878/77321606-091f3f80-6cd8-11ea-8950-9f39af14ec7b.png)
![2020-03-23 07_12_50-Ryujinx 1 0 3957 _ RPGMAKER MV _ 010033C00985E000](https://user-images.githubusercontent.com/62343878/77321611-0a506c80-6cd8-11ea-9063-cc7185e9d0bf.png)
![2020-03-23 07_13_18-Ryujinx 1 0 3957 _ RPGMAKER MV _ 010033C00985E000](https://user-images.githubusercontent.com/62343878/77321612-0a506c80-6cd8-11ea-83b4-a4bdb6bebf7f.png)
![2020-03-23 07_17_56-Ryujinx 1 0 3957 _ RPGMAKER MV _ 010033C00985E000](https://user-images.githubusercontent.com/62343878/77321613-0ae90300-6cd8-11ea-9b59-09438b7672ca.png)


#### Log file :

[RPGMakerMV_Debug.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4369650/RPGMakerMV_Debug.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
