### ISSUE TITLE
SNK 40th Anniversary Collection

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#140]
#### Current on `master` :

* Build Version : 1.0.2234

```
Unhandled Exception: System.NotImplementedException: Ryujinx.HLE.HOS.Services.Vi.IApplicationDisplayService: 2102
```

After that, it's crash:
```
Unhandled Exception: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: position
   at ChocolArm64.Memory.MemoryManager.ReadBytes(Int64 position, Int64 size) in D:\Games\Ryujinx-port\ChocolArm64\Memory\MemoryManager.cs:line 338
   at Ryujinx.Graphics.Graphics3d.NvGpuEngine3d.UploadVertexArrays(NvGpuVmm Vmm, GalPipelineState State) in D:\Games\Ryujinx-port\Ryujinx.Graphics\Graphics3d\NvGpuEngine3d.cs:line 755
   at Ryujinx.Graphics.Graphics3d.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, GpuMethodCall MethCall) in D:\Games\Ryujinx-port\Ryujinx.Graphics\Graphics3d\NvGpuEngine3d.cs:line 121
   at Ryujinx.Graphics.Graphics3d.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, GpuMethodCall MethCall) in D:\Games\Ryujinx-port\Ryujinx.Graphics\Graphics3d\NvGpuEngine3d.cs:line 87
   at Ryujinx.Graphics.Graphics3d.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, GpuMethodCall MethCall) in D:\Games\Ryujinx-port\Ryujinx.Graphics\Graphics3d\NvGpuFifo.cs:line 144
   at Ryujinx.Graphics.Graphics3d.NvGpuFifo.CallMethod(NvGpuVmm Vmm, GpuMethodCall MethCall) in D:\Games\Ryujinx-port\Ryujinx.Graphics\Graphics3d\NvGpuFifo.cs:line 91
   at Ryujinx.Graphics.DmaPusher.CallMethod(Int32 Argument) in D:\Games\Ryujinx-port\Ryujinx.Graphics\DmaPusher.cs:line 188
   at Ryujinx.Graphics.DmaPusher.Step() in D:\Games\Ryujinx-port\Ryujinx.Graphics\DmaPusher.cs:line 136
   at Ryujinx.GlScreen.RenderLoop() in D:\Games\Ryujinx-port\Ryujinx\Ui\GLScreen.cs:line 67
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

#### Pull requests needed :

https://github.com/Ryujinx/Ryujinx/pull/550
https://github.com/Ryujinx/Ryujinx/pull/529/commits/1fe2b366bad03f8676d7914b63e94c167a836f67

**Comment by HorrorTroll** [comment]
Updated

**Comment by jduncanator** [comment]
Updated

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## SNK 40th Anniversary Collection

#### Current on `master` : 1.0.3937

Game loads and is playable, however there is occasional minor graphical corruption/glitchy flashing textures in menus and the legacy games inside (some of this occurred in the real arcade hardware too). Can be slow at times.

#### Screenshots :
![2020-03-22 13_52_52-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259279-12f86280-6c46-11ea-823a-79ca037aaf3b.png)
![2020-03-22 13_52_57-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259280-14298f80-6c46-11ea-991f-884b00b374d3.png)
![2020-03-22 13_53_02-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259281-14298f80-6c46-11ea-9a22-13de78598ceb.png)
![2020-03-22 13_53_09-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259282-14c22600-6c46-11ea-8dd7-c96898d69993.png)
![2020-03-22 13_53_15-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259283-155abc80-6c46-11ea-998c-2960bb0279a7.png)
![2020-03-22 13_53_32-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259284-1855ad00-6c46-11ea-83b4-96f84a381c9f.png)
![2020-03-22 13_53_59-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259286-20ade800-6c46-11ea-9144-46c706d21db1.png)
![2020-03-22 13_54_10-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259296-26a3c900-6c46-11ea-891f-9fe1cee405c0.png)
![2020-03-22 13_54_26-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259298-299eb980-6c46-11ea-8402-a30237161ffd.png)
![2020-03-22 13_59_03-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259300-2d324080-6c46-11ea-8d8e-4fed989fb68b.png)
![2020-03-22 13_59_33-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259303-328f8b00-6c46-11ea-9a2c-6f8cc234fcc1.png)
![2020-03-22 13_59_58-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259305-33c0b800-6c46-11ea-9348-115cc89da153.png)
![2020-03-22 14_00_17-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259313-3cb18980-6c46-11ea-98da-c5c6f41a364c.png)
![2020-03-22 14_00_34-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259320-44712e00-6c46-11ea-9df7-8ea53460d935.png)
![2020-03-22 14_01_41-Ryujinx 1 0 3937 _ SNK 40th Anniversary Collection _ 01004AB00AEF8000](https://user-images.githubusercontent.com/62343878/77259329-4c30d280-6c46-11ea-9d2f-f3016a26de4b.png)



#### Log file :
[SNK40.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4366257/SNK40.zip)

**Comment by B3astTech** [comment]
Updated Thanks

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
