### ISSUE TITLE
Arcade Archives PUNCH-OUT!!

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1434]
#### Current on `master` : 1.0.4613

Loads to initial menu and then crashes with the error below after trying to start the game.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![2020-05-26 13_10_09-Ryujinx 1 0 4613 - Arcade Archives PUNCH-OUT!! v1 0 0 (01001530097F8000) (64-bit](https://user-images.githubusercontent.com/62343878/82940597-51fea900-9f52-11ea-8ef9-a87052271a94.png)

#### Log file :

[AAPO.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4684492/AAPO.zip)

**Comment by SeraUX** [comment]
## Arcade Archives PUNCH-OUT!!

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.5191

Game crashes with an missing service error after trying to go past the first menu.
```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 6

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x000af064 nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)4, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 6, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> >, 16ul, 12ul, true>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 6, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, nn::sf::cmif::client::InRawClientArgumentType<1ul, 1ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, unsigned int)
   sdk:0x000ae82c Sub0000000009f6482c
   sdk:0x000adb64 Sub0000000009f63b64
   main:0x000ad27c Sub00000000080b127c
   main:0x000bc360 Sub00000000080c0360
   main:0x000c0ecc Sub00000000080c4ecc
   main:0x000725f0 Sub00000000080765f0
   sdk:0x00091b48 Sub0000000009f47b48
   sdk:0x00095b24 Sub0000000009f4bb24
   ??? Sub0000000000000000

Buffer Information:
        SendBuff:
        Position: 0x0000001190960cfc Size: 0x0000000000000023 Flags: 0
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        Position: 0x00000011909607e0 Size: 0x0000000000000400 Flags: 0
        ReceiveBuff:
        Position: 0x00000000090210b0 Size: 0x0000000000001000 Flags: 0

Raw Request Data:
00000000   53 46 43 49 00 00 00 00  06 00 00 00 00 00 00 00   SFCI············
00000010   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Hardware Specs :

##### CPU: i3-7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/637

#### Screenshots :

![22-37-51_18-08-20](https://user-images.githubusercontent.com/62521228/90563063-88d80a00-e1a3-11ea-9fee-a67e59b5362f.png)

#### Log file :

[aa-punch-out.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5092706/aa-punch-out.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
