### ISSUE TITLE
Arcade Archives NINJA GAIDEN

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1437]
#### Current on `master` : 1.0.4613

Loads to initial menu and then crashes with the error below after trying to start the game.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![2020-05-26 13_19_06-Ryujinx 1 0 4613 - Arcade Archives NINJA GAIDEN v1 0 0 (01003EF00D3B4000) (64-bi](https://user-images.githubusercontent.com/62343878/82941401-83c43f80-9f53-11ea-8747-2f67d13ea475.png)

#### Log file :

[AANG.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4684516/AANG.zip)

**Comment by SeraUX** [comment]
## Arcade Archives NINJA GAIDEN

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.5191

Game crashes with an missing service error after trying to go past the first menu.
```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 12

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0036976c nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 34, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<4, 33, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 12l> >, 16ul, 16ul, true>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 34, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<4, 33, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 12l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, unsigned int)
   sdk:0x0036823c Sub000000000a3ee23c
   sdk:0x003671cc Sub000000000a3ed1cc
   main:0x00064620 Sub0000000008068620
   main:0x00024dc8 Sub0000000008028dc8
   main:0x00029c88 Sub000000000802dc88
   main:0x00006204 Sub000000000800a204
   sdk:0x0031d3b8 Sub000000000a3a33b8
   sdk:0x00321818 Sub000000000a3a7818
   ??? Sub0000000000000000

Buffer Information:
        PtrBuff:
        [0] Position: 0x000000000976a0b0 Size: 0x0000000000000000
        SendBuff:
        Position: 0x00000011d2bdbcfc Size: 0x0000000000000023 Flags: 0
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        Position: 0x000000000976a0d8 Size: 0x0000000000000400 Flags: 0
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        ReceiveBuff:
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        RecvListBuff:
        Position: 0x000000000976a4f8 Size: 0x0000000000001000

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0C 00 00 00 00 00 00 00   SFCI············
00000010   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  00 10 00 00 F8 A4 76 09   ············ø¤v·
00000030   00 00 00 10                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Hardware Specs :

##### CPU: i3-7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1233

#### Screenshots :

![22-51-28_18-08-20](https://user-images.githubusercontent.com/62521228/90564297-7232b280-e1a5-11ea-9bf9-f1244ba5a38d.png)

#### Log file :

[aa-ninja-gaiden.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5092789/aa-ninja-gaiden.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
