### ISSUE TITLE
Arcade Archives Kid Niki Radical Ninja

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1441]
#### Current on `master` : 1.0.4613

Loads to initial menu and then crashes with the error below after trying to start the game.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![2020-05-26 13_31_36-Ryujinx 1 0 4613 - Arcade Archives Kid Niki Radical Ninja v1 0 0 (010010B008A360](https://user-images.githubusercontent.com/62343878/82942493-42cd2a80-9f55-11ea-99af-7f9f348d7e77.png)

#### Log file :

[AAKNRN.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4684578/AAKNRN.zip)

**Comment by SeraUX** [comment]
## Arcade Archives Kid Niki Radical Ninja

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.5191

Game crashes with an missing service error after trying to go past the first menu.
```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 6

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x000a78d0 nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)4, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 6, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> >, 16ul, 12ul, true>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 6, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, nn::sf::cmif::client::InRawClientArgumentType<1ul, 1ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, unsigned int)
   sdk:0x000a7098 Sub000000000afa1098
   sdk:0x000a648c Sub000000000afa048c
   main:0x0014d6bc Sub00000000081516bc
   main:0x0015b09c Sub000000000815f09c
   main:0x0015fba8 Sub0000000008163ba8
   main:0x000797fc Sub000000000807d7fc
   sdk:0x0008a8a8 Sub000000000af848a8
   sdk:0x0008e958 Sub000000000af88958
   ??? Sub0000000000000000

Buffer Information:
        SendBuff:
        Position: 0x0000001191960cfc Size: 0x0000000000000023 Flags: 0
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        Position: 0x00000011919607e0 Size: 0x0000000000000400 Flags: 0
        ReceiveBuff:
        Position: 0x000000000914b0b0 Size: 0x0000000000001000 Flags: 0

Raw Request Data:
00000000   53 46 43 49 00 00 00 00  06 00 00 00 00 00 00 00   SFCI············
00000010   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Hardware Specs :

##### CPU: i3-7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/637

#### Screenshots :

![23-12-12_18-08-20](https://user-images.githubusercontent.com/62521228/90566189-57ae0880-e1a8-11ea-83ab-1323e6a3c63b.png)

#### Log file :

[aa-kid-niki-radical-ninja.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5092884/aa-kid-niki-radical-ninja.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.1.182
