### ISSUE TITLE
Arcade Archives HEROIC EPISODE

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1443]
#### Current on `master` : 1.0.4613

Crashes on launch without displaying any graphics.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.VoiceContext.GetBufferData(MemoryManager memory, Int32 maxSamples, Int32& samplesCount) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\VoiceContext.cs:line 70
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.AppendMixedBuffer(Int64 tag) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 370
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.UpdateAudio() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 348
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.RequestUpdateAudioRenderer(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 226
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Log file :

[AAHE.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4684628/AAHE.zip)

**Comment by SeraUX** [comment]
## Arcade Archives HEROIC EPISODE

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.5191

Game crashes with an missing service error after trying to go past the first menu.
```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 6

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x000af064 nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)4, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 6, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> >, 16ul, 12ul, true>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 6, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, nn::sf::cmif::client::InRawClientArgumentType<1ul, 1ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, unsigned int)
   sdk:0x000ae82c Sub0000000009e7582c
   sdk:0x000adb64 Sub0000000009e74b64
   main:0x000b066c Sub00000000080b466c
   main:0x000bf750 Sub00000000080c3750
   main:0x000c42bc Sub00000000080c82bc
   main:0x000759e0 Sub00000000080799e0
   sdk:0x00091b48 Sub0000000009e58b48
   sdk:0x00095b24 Sub0000000009e5cb24
   ??? Sub0000000000000000

Buffer Information:
        SendBuff:
        Position: 0x00000012038dbcfc Size: 0x0000000000000023 Flags: 0
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        Position: 0x00000012038db7e0 Size: 0x0000000000000400 Flags: 0
        ReceiveBuff:
        Position: 0x00000000090120b0 Size: 0x0000000000001000 Flags: 0

Raw Request Data:
00000000   53 46 43 49 00 00 00 00  06 00 00 00 00 00 00 00   SFCI············
00000010   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
#### Hardware Specs :

##### CPU: i3-7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/637

#### Screenshots :

![23-17-47_18-08-20](https://user-images.githubusercontent.com/62521228/90566692-313c9d00-e1a9-11ea-8c18-50564f6235bf.png)

#### Log file :


[aa-heroic-episode.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5092900/aa-heroic-episode.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
