### ISSUE TITLE
Arcade Archives DONKEY KONG

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1446]
#### Current on `master` : 1.0.4613

Loads to initial menu and then crashes with the error below after trying to start the game.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![2020-05-26 13_52_25-Ryujinx 1 0 4613 - Arcade Archives DONKEY KONG v1 0 0 (0100E9E00B052000) (64-bit](https://user-images.githubusercontent.com/62343878/82944345-3eeed780-9f58-11ea-8e04-86668cae5e63.png)

#### Log file :

[AADK.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4684698/AADK.zip)

**Comment by SeraUX** [comment]
## Arcade Archives DONKEY KONG

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.5191

Game crashes with an missing service error after trying to go past the first menu.
```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 6

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x000af064 nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)4, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 6, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> >, 16ul, 12ul, true>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 6, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, nn::sf::cmif::client::InRawClientArgumentType<1ul, 1ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, unsigned int)
   sdk:0x000ae82c Sub0000000009e0182c
   sdk:0x000adb64 Sub0000000009e00b64
   main:0x000af1b8 Sub00000000080b31b8
   main:0x000be29c Sub00000000080c229c
   main:0x000c2e08 Sub00000000080c6e08
   main:0x0007452c Sub000000000807852c
   sdk:0x00091b48 Sub0000000009de4b48
   sdk:0x00095b24 Sub0000000009de8b24
   ??? Sub0000000000000000

Buffer Information:
        SendBuff:
        Position: 0x0000001190760cfc Size: 0x0000000000000023 Flags: 0
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        Position: 0x00000011907607e0 Size: 0x0000000000000400 Flags: 0
        ReceiveBuff:
        Position: 0x0000000008f2e0b0 Size: 0x0000000000001000 Flags: 0

Raw Request Data:
00000000   53 46 43 49 00 00 00 00  06 00 00 00 00 00 00 00   SFCI············
00000010   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Hardware Specs :

##### CPU: i3-7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/637

#### Screenshots :

![23-23-43_18-08-20](https://user-images.githubusercontent.com/62521228/90567169-0acb3180-e1aa-11ea-9121-c53149272568.png)

#### Log file :

[aa-donkey-kong.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5092934/aa-donkey-kong.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by LukeWarnut** [comment]
## Arcade Archives DONKEY KONG

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.6798

Game now goes past initial menu and ingame. Game and settings function well, but audio from the emulated game does not play on either backend. Menus play audio as intended,

#### Hardware Specs : 

##### CPU: AMD Ryzen 5 2600
##### GPU: NVIDIA GTX 1660 SUPER
##### RAM: 16GB

#### Screenshots :

![image](https://user-images.githubusercontent.com/65521430/112363141-8c88bd80-8cab-11eb-9c53-a60f14c22792.png)
![image](https://user-images.githubusercontent.com/65521430/112363156-914d7180-8cab-11eb-978e-8bbd6c87cdee.png)
![image](https://user-images.githubusercontent.com/65521430/112363168-93afcb80-8cab-11eb-893c-366b303b7dd3.png)

#### Log file :

[AADonkeyKong.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6199600/AADonkeyKong.log)
