### ISSUE TITLE
LIMBO

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#145]
#### Current on `master` :

* Build Version : 1.0.2287

```
Unhandled Exception: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000000200008 (opcode 0xe3500000) is undefined!
```

Add that, and then crash

```
Unhandled Exception: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000020191c (opcode 0xe3003101) is undefined!
```

#### Pull requests needed :

https://github.com/Ryujinx/Ryujinx/pull/565

**Comment by AcK77** [comment]
Needs an update!

**Comment by HorrorTroll** [comment]
Updated!

**Comment by valx76** [comment]
After some tests, it's missing at least the following 32-bits instructions to catch the menu:

- VBIC *(the one mentioned above)*
- VSRA
- VTST

Maybe the following two as well (need check):

- VCVT
- VQMOVN

**Comment by Kryptuq** [comment]
Game Runs now with https://github.com/Ryujinx/Ryujinx/pull/2242 but has some Audio Issues:

![unknown](https://user-images.githubusercontent.com/68452851/115996709-b56cdd00-a5e0-11eb-82f2-c7cad6975060.png)
![unknown (1)](https://user-images.githubusercontent.com/68452851/115996711-b736a080-a5e0-11eb-969d-ec93a91b3437.png)
![unknown (2)](https://user-images.githubusercontent.com/68452851/115996713-ba319100-a5e0-11eb-9f21-6f019d7d3a7e.png)

Audio Issue:

https://user-images.githubusercontent.com/68452851/115996726-c61d5300-a5e0-11eb-83b5-353076d7bd4e.mp4

**Comment by wickedr0se** [comment]
![Screenshot_219](https://user-images.githubusercontent.com/32614215/165957230-1eeefd34-85ea-4bc9-b4b6-640e600bc9e4.png)

using vulkan and 1.1.106
loading screen then crash

[Ryujinx_1.1.0+47aa773_2022-04-29_20-45-47.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8591222/Ryujinx_1.1.0%2B47aa773_2022-04-29_20-45-47.log)

```
00:00:18.705 |E| HLE.GuestThread.20 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000003d94b0 (opcode 0xf2f10f70) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1104
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
```

**Comment by Djipi71** [comment]
Test on 1.1.494

The game aways crash  :(

**Comment by AcK77** [comment]
Needs an update
