### ISSUE TITLE
Anima: Arcane Edition

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1466]
#### Current on `master` : 1.0.4654

Has nvdec issue after trying to start a new game. Once it completes or is skipped, the game crashes.
Other issues included vertex explosions in early menus.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.HorizonResultException: ResultFsInvalidIvfcHash (2002-4604): Hash error!
   at LibHac.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination)
   at LibHac.Fs.StorageBase.Read(Int64 offset, Span`1 destination)
   at LibHac.FsSystem.CachedStorage.ReadBlock(CacheBlock block, Int64 index)
   at LibHac.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.FsSystem.CachedStorage.ReadImpl(Int64 offset, Span`1 destination)
   at LibHac.Fs.StorageBase.Read(Int64 offset, Span`1 destination)
   at LibHac.FsSystem.HierarchicalIntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination)
   at LibHac.Fs.StorageBase.Read(Int64 offset, Span`1 destination)
   at LibHac.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at LibHac.FsSystem.StreamStorage.ReadImpl(Int64 offset, Span`1 destination)
   at LibHac.Fs.StorageBase.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 20
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Screenshots :

![2020-05-28 06_07_09-Ryujinx 1 0 4654 - Anima_ Arcane Edition v1 0 3 (010033F00B3FA000) (64-bit)](https://user-images.githubusercontent.com/62343878/83139717-095a0380-a0aa-11ea-877d-ada8fb45a4c0.png)
![2020-05-28 06_07_15-Ryujinx 1 0 4654 - Anima_ Arcane Edition v1 0 3 (010033F00B3FA000) (64-bit)](https://user-images.githubusercontent.com/62343878/83139719-09f29a00-a0aa-11ea-83d2-85732ce68553.png)
![2020-05-28 06_07_41-Ryujinx 1 0 4654 - Anima_ Arcane Edition v1 0 3 (010033F00B3FA000) (64-bit)](https://user-images.githubusercontent.com/62343878/83139723-0b23c700-a0aa-11ea-95c5-5b642dc98e53.png)
![2020-05-28 06_08_42-Ryujinx 1 0 4654 - Anima_ Arcane Edition v1 0 3 (010033F00B3FA000) (64-bit)](https://user-images.githubusercontent.com/62343878/83139741-12e36b80-a0aa-11ea-9c19-354f185cac15.png)
![2020-05-28 06_08_48-Ryujinx 1 0 4654 - Anima_ Arcane Edition v1 0 3 (010033F00B3FA000) (64-bit)](https://user-images.githubusercontent.com/62343878/83139751-1840b600-a0aa-11ea-91ed-d6bfa147df99.png)

#### Log file :

[AAE.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4695405/AAE.zip)

**Comment by EmulationFanatic** [comment]
Updated
