### ISSUE TITLE
AngerForce: Reloaded for Nintendo Switch

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1480]
#### Current on `master` : 1.0.4654

Loads through initial intro splashes and then crashes.
Note: the error below was seen only in the console; it did not appear in the log.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.Cpu.CpuContext.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass129_0.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-05-28 08_56_43-Ryujinx 1 0 4654 - AngerForce_ Reloaded for Nintendo Switch v1 0 0 (010001E00A5F](https://user-images.githubusercontent.com/62343878/83158909-9f9a2380-a0c2-11ea-8033-ab3489175996.png)
![2020-05-28 08_56_57-Ryujinx 1 0 4654 - AngerForce_ Reloaded for Nintendo Switch v1 0 0 (010001E00A5F](https://user-images.githubusercontent.com/62343878/83158913-a032ba00-a0c2-11ea-8b2d-174a4da53fcc.png)

#### Log file :

[AFRfNS.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4696433/AFRfNS.zip)

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
