### ISSUE TITLE
Slay the Spire

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1498]
#### Current on `master` : 1.0.4665

Game loads into a corrupt initial title screen, and it only gets worse from there. Navigating the menu is almost impossible due to not being able to see which button to press to advance toward starting a game.
Technically it goes in-game, but is certainly not playable.

#### Screenshots :

![2020-05-29 04_12_25-Ryujinx 1 0 4665 - Slay the Spire v1 0 (010026300BA4A000) (64-bit)](https://user-images.githubusercontent.com/62343878/83249241-885f4280-a163-11ea-87c8-dcb3dbb4bb6e.png)
![2020-05-29 04_12_55-Ryujinx 1 0 4665 - Slay the Spire v1 0 (010026300BA4A000) (64-bit)](https://user-images.githubusercontent.com/62343878/83249242-8a290600-a163-11ea-9013-3f95be59225b.png)
![2020-05-29 04_13_02-Ryujinx 1 0 4665 - Slay the Spire v1 0 (010026300BA4A000) (64-bit)](https://user-images.githubusercontent.com/62343878/83249257-901ee700-a163-11ea-8343-dbd6e40e2af1.png)
![2020-05-29 04_13_22-Ryujinx 1 0 4665 - Slay the Spire v1 0 (010026300BA4A000) (64-bit)](https://user-images.githubusercontent.com/62343878/83249284-9a40e580-a163-11ea-9e18-8c3ac72f419d.png)
![2020-05-29 04_13_29-Ryujinx 1 0 4665 - Slay the Spire v1 0 (010026300BA4A000) (64-bit)](https://user-images.githubusercontent.com/62343878/83249336-aaf15b80-a163-11ea-9733-b667a162fb1a.png)
![2020-05-29 04_13_53-Ryujinx 1 0 4665 - Slay the Spire v1 0 (010026300BA4A000) (64-bit)](https://user-images.githubusercontent.com/62343878/83249339-ab89f200-a163-11ea-8c92-bef08504a809.png)
![2020-05-29 04_18_20-Ryujinx 1 0 4665 - Slay the Spire v1 0 (010026300BA4A000) (64-bit)](https://user-images.githubusercontent.com/62343878/83249367-b17fd300-a163-11ea-8ad0-a7fa49539789.png)
![2020-05-29 04_18_38-Ryujinx 1 0 4665 - Slay the Spire v1 0 (010026300BA4A000) (64-bit)](https://user-images.githubusercontent.com/62343878/83249376-b47ac380-a163-11ea-90ba-d710f9611121.png)

#### Log file :

[StS.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4701194/StS.zip)

**Comment by LukeWarnut** [comment]
Game is rendering a little better on the latest update (Ryu & the game itself). Still isn't playable as text is still unreadable.

Booting without an update causes a crash with this error:
```
00:01:29.204 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 37
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 139
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by EmulationFanatic** [comment]
Updated

**Comment by felipevc13** [comment]
The game has some font letters missing from the interface
