### ISSUE TITLE
Shovel Knight: Treasure Trove

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1500]
#### Current on `master` : 1.0.4665

Game loads and plays perfectly.

#### Screenshots :

![2020-05-29 04_27_15-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251089-57344180-a166-11ea-989f-8796fdb5948a.png)
![2020-05-29 04_27_22-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251091-58fe0500-a166-11ea-8290-ba719d67d81c.png)
![2020-05-29 04_27_53-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251094-5a2f3200-a166-11ea-81b5-9a0c38844530.png)
![2020-05-29 04_27_56-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251095-5ac7c880-a166-11ea-93ca-a74c34b480d1.png)
![2020-05-29 04_28_18-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251111-5e5b4f80-a166-11ea-91d6-a71a99fa88f1.png)
![2020-05-29 04_28_33-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251113-5ef3e600-a166-11ea-990a-447943f639c0.png)
![2020-05-29 04_29_03-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251117-60251300-a166-11ea-9cd2-a4fad040df8f.png)
![2020-05-29 04_30_00-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251122-62876d00-a166-11ea-92f9-1cc296b34ba3.png)
![2020-05-29 04_33_31-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251127-64513080-a166-11ea-8718-2aa32f01b372.png)
![2020-05-29 04_34_18-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251135-661af400-a166-11ea-9cc3-cf1e8191a312.png)
![2020-05-29 04_34_39-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251140-674c2100-a166-11ea-8676-3b2db482ed79.png)
![2020-05-29 04_35_21-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251143-67e4b780-a166-11ea-9ff7-cb46898cdb7f.png)
![2020-05-29 04_37_00-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251148-6adfa800-a166-11ea-9133-36d31cc060ad.png)
![2020-05-29 04_37_54-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251154-6d420200-a166-11ea-96cb-bee5ae397986.png)
![2020-05-29 04_38_45-Ryujinx 1 0 4665 - Shovel Knight_ Treasure Trove v3 00 (010057D0021E8000) (64-bi](https://user-images.githubusercontent.com/62343878/83251158-6e732f00-a166-11ea-812e-afd07a68955a.png)

#### Log file :

[SKTT.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4701309/SKTT.zip)

**Comment by LukeWarnut** [comment]
Crashing at startup again. (1.0.6551)

```
00:00:02.034 |E| GUI.RenderLoop Application : Unhandled exception caught: System.ArgumentException: Value does not fall within the expected range.
   at Ryujinx.Graphics.Gpu.Shader.CachedGpuAccessor.GetTextureDescriptor(Int32 handle) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\CachedGpuAccessor.cs:line 148
   at Ryujinx.Graphics.Gpu.Shader.TextureDescriptorCapableGpuAccessor.QueryIsTextureRectangle(Int32 handle) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\TextureDescriptorCapableGpuAccessor.cs:line 94
   at Ryujinx.Graphics.Shader.Translation.Rewriter.RewriteTextureSample(LinkedListNode`1 node, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Rewriter.cs:line 143
   at Ryujinx.Graphics.Shader.Translation.Rewriter.RunPass(BasicBlock[] blocks, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Rewriter.cs:line 35
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(FunctionCode[] functions, ShaderConfig config, ShaderProgramInfo& shaderProgramInfo) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 75
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.Initialize() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 60
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 387
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
[Ryujinx_1.0.6551_2021-02-14_13-15-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5978223/Ryujinx_1.0.6551_2021-02-14_13-15-54.log)

**Comment by EmulationFanatic** [comment]
> Crashing at startup again. (1.0.6551)
> 
> ```
> 00:00:02.034 |E| GUI.RenderLoop Application : Unhandled exception caught: System.ArgumentException: Value does not fall within the expected range.
>    at Ryujinx.Graphics.Gpu.Shader.CachedGpuAccessor.GetTextureDescriptor(Int32 handle) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\CachedGpuAccessor.cs:line 148
>    at Ryujinx.Graphics.Gpu.Shader.TextureDescriptorCapableGpuAccessor.QueryIsTextureRectangle(Int32 handle) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\TextureDescriptorCapableGpuAccessor.cs:line 94
>    at Ryujinx.Graphics.Shader.Translation.Rewriter.RewriteTextureSample(LinkedListNode`1 node, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Rewriter.cs:line 143
>    at Ryujinx.Graphics.Shader.Translation.Rewriter.RunPass(BasicBlock[] blocks, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Rewriter.cs:line 35
>    at Ryujinx.Graphics.Shader.Translation.Translator.Translate(FunctionCode[] functions, ShaderConfig config, ShaderProgramInfo& shaderProgramInfo) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 75
>    at Ryujinx.Graphics.Gpu.Shader.ShaderCache.Initialize() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 60
>    at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 387
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> ```
> 
> [Ryujinx_1.0.6551_2021-02-14_13-15-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5978223/Ryujinx_1.0.6551_2021-02-14_13-15-54.log)

Purge the shader cache and it should work again. If it crashes again on the 2nd boot after purging, that would mean the game has bindless textures and will not work reliably until the shader cache implementation is modified to account for said textures.

**Comment by LukeWarnut** [comment]
> Purge the shader cache and it should work again. If it crashes again on the 2nd boot after purging, that would mean the game has bindless textures and will not work reliably until the shader cache implementation is modified to account for said textures.

Thanks. Working again now.
