### ISSUE TITLE
SolDivide for Nintendo Switch

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1523]
#### Current on `master` : 1.0.4665

Crashes on launch.

```
HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000021bdf94 (opcode 0xf2c0617f) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 98
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1005

#### Log file :

[SfNS.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4705977/SfNS.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by SeraUX** [comment]
## SolDivide for Nintendo Switch 

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.5173

Game now renders graphics but they flicker a lot making it hard to play and the audio is still distorted

#### Hardware Specs : 

##### CPU: i3-7300
##### GPU:  NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Screenshots :

![2020-08-13 19_26_11](https://user-images.githubusercontent.com/62521228/90167031-6f961e80-dd9b-11ea-909e-b881dc3e88d2.png)
![2020-08-13 19_26_20](https://user-images.githubusercontent.com/62521228/90167033-702eb500-dd9b-11ea-89e6-c631c61b98fb.png)
![2020-08-13 19_26_25](https://user-images.githubusercontent.com/62521228/90167047-73c23c00-dd9b-11ea-9c6c-3fe1a88e8408.png)
![2020-08-13 19_26_32](https://user-images.githubusercontent.com/62521228/90167055-76bd2c80-dd9b-11ea-9f9d-e1002ba647b6.png)
![2020-08-13 19_26_44](https://user-images.githubusercontent.com/62521228/90167072-7b81e080-dd9b-11ea-8551-ca6db7e62e54.png)
![2020-08-13 19_27_34](https://user-images.githubusercontent.com/62521228/90167091-7fadfe00-dd9b-11ea-91ff-7a9a6956329f.png)
![2020-08-13 19_27_45](https://user-images.githubusercontent.com/62521228/90167104-83da1b80-dd9b-11ea-9095-5461c71a07b7.png)
![2020-08-13 19_29_16](https://user-images.githubusercontent.com/62521228/90167120-88063900-dd9b-11ea-8ce1-f6f0f4d7e424.png)

#### Log file :

[soldivide.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5070520/soldivide.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by SeraUQ** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
