### ISSUE TITLE
## Marvel Ultimate Alliance 3: The Black Order

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1535]
#### Current on `master` : 1.0.4665

Crashes on launch after trying to load for a couple of minutes. Note: the error below was seen only in the console; it did not exist in the log.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.TranslatedFunction.Execute(ARMeilleure.State.ExecutionContext)
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.Cpu.CpuContext.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass129_0.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[MUA3TBO.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4708112/MUA3TBO.zip)

**Comment by mikhaelcool7** [comment]
Game update: 4.0.1 on the master build: 1.0.6903 gives the exact same results. Making the game difficult to play as the graphical artifacts heavily block your view during combat and your eyes get really tired due to the constant flickering.

**Comment by igniz02** [comment]
> 
> 
> Game update: 4.0.1 on the master build: 1.0.6903 gives the exact same results. Making the game difficult to play as the graphical artifacts heavily block your view during combat and your eyes get really tired due to the constant flickering.

me too!

**Comment by ugurkanates** [comment]
i wish game worked well

**Comment by igniz02** [comment]
It's still not normal

**Comment by Cheezballjones** [comment]
This game has received a MAJOR update and is now playable for the first portion of the game without Vertex Explosions - As of Master 1.0.7038. 

That being said, I was progressing to Kingpin's Office in Shadowland and came across more Vertex Explosions that renders the next part Unplayable.

https://user-images.githubusercontent.com/89695758/133726139-0a69fdf1-3734-4be2-9885-3d5cd35518f0.mp4

I'm running the game with no mods on version 4.0.1.

Hardware Specs :
CPU: Intel Core i5 9600k
GPU: NVIDIA GTX 2070
RAM: 16GB

**Comment by Logandros** [comment]
Not sure if it's just me but I see a major regression with 1.0.7065 (completely black play field following opening cutscene).

![ryujinx_capture_2021-10-07_19-54-11](https://user-images.githubusercontent.com/24375543/136477370-dde1e7e5-a209-4e54-8a1c-27155a70f6e3.png)

Ryujinx Version: 1.0.7065
Operating System: Microsoft Windows 10.0.22471 (X64)
CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz ; 16 logical
RAM: Total 65466 MB ; Available 55558 MB
Using Firmware Version: 12.0.3
NVIDIA Corporation NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2 (4.6.0 NVIDIA 510.10)

**Comment by gdkchan** [comment]
It is working fine here:
![image](https://user-images.githubusercontent.com/5624669/136478118-c135e43b-943f-430f-a808-15ac0d3addfd.png)
Maybe try to purge your shader cache (or you can just disable it temporarily just to see if thats the issue).

**Comment by Logandros** [comment]
I can confirm that my issue was Windows and driver related, reverting back to NVIDIA 472.12 from 510.10 fixed my issue. My apologies for the confusion.

**Comment by adnan-travar** [comment]
Game Update Version : 1.0.0
Current on master : 1.1.10

Hardware Specs :
CPU: Ryzen 7 5800X
GPU: AMD Vega 64
RAM: 16GB
Radeon Software version: 22.1.1

Screenshots :
![ryujinx_capture_2022-01-27_19-56-53](https://user-images.githubusercontent.com/68653902/151426934-9a16b75b-93d0-4fc0-8604-3654e16c361d.png)


 I'd attach my log file but it's too big because I wasn't sure which logging options to enable, so I enabled all of them...

**Comment by GamerzHell9137** [comment]
Game works fine on latest master. Only issue is that at the beginning of the game, the game freezes for a solid 2-3 mins on a syncpoint, after which it plays fine. Erratic FPS. Can drops around 15 and go up to 60 FPS (with mod).
![image](https://user-images.githubusercontent.com/2002038/153697028-0c4e4cf7-14e3-460f-a888-ef7d264a0ad1.png)

**Comment by Revanov** [comment]
Game version: 401
Ryujinx version: 1.1.147
i5 10600kf, rtx 3070, 32gb 3600, win10. 

Playable with extreme FPS drops during skill use and battle. Certain levels like avengers tower also cause extreme fps drop.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by kmetininan** [comment]
i5 12400F
32 gb ram
rtx 3060 12 gb

docked mode,game version 4.01

trying to open with opengl, only black screen and lots of error on the log:
 
[Ryujinx_1.1.283_2022-10-01_10-21-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9689937/Ryujinx_1.1.283_2022-10-01_10-21-33.log)

**Comment by EmulationFanatic** [comment]
> latest master version.
> 
> i5 12400F 32 gb ram rtx 3060 12 gb
> 
> docked mode,game version 4.01
> 
> trying to open with opengl, only black screen and lots of error on the log:
> 
> [Ryujinx_1.1.283_2022-10-01_10-21-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9689937/Ryujinx_1.1.283_2022-10-01_10-21-33.log)

It's working fine here on an RTX 3080 Ti on OpenGL.
![image](https://user-images.githubusercontent.com/62343878/193405282-b8f5de31-ca4e-4938-bcba-d4b653da65d0.png)

From your logs...Turn off OpenGL debug logging. It is definitely causing all of the log errors and almost certainly causing the black screen on your PC.
![image](https://user-images.githubusercontent.com/62343878/193405252-e816be1a-b5e1-4ad5-b2db-83f00a61054f.png)

**Comment by kmetininan** [comment]
> > latest master version.
> > i5 12400F 32 gb ram rtx 3060 12 gb
> > docked mode,game version 4.01
> > trying to open with opengl, only black screen and lots of error on the log:
> > [Ryujinx_1.1.283_2022-10-01_10-21-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9689937/Ryujinx_1.1.283_2022-10-01_10-21-33.log)
> 
> It's working fine here on an RTX 3080 Ti on OpenGL. ![image](https://user-images.githubusercontent.com/62343878/193405282-b8f5de31-ca4e-4938-bcba-d4b653da65d0.png)
> 
> From your logs...Turn off OpenGL debug logging. It is definitely causing all of the log errors and almost certainly causing the black screen on your PC. ![image](https://user-images.githubusercontent.com/62343878/193405252-e816be1a-b5e1-4ad5-b2db-83f00a61054f.png)

you are right. I just restored nvidia 3d settings and it is working.thanks.

**Comment by Boba194230** [comment]
On steam Deck. Ryujinx v.1.1.284  Game version 4.01 Terrible black artifacts everywhere Open GL and Vulkan

**Comment by Boba194230** [comment]
Tried again on the latest builds and it’s the same problems

**Comment by will197** [comment]
> On steam Deck. Ryujinx v.1.1.284 Game version 4.01 Handheld Mode and Docked: Terrible black artifacts everywhere Open GL and Vulkan. Loaded here from a switch save. Still performs better than yuzu though so this will most likely be the best platform for running this on steam deck just the artifacts mainly is the issue. 

Getting the same

**Comment by BoogieBoard** [comment]
> 

Also getting the same issue

**Comment by BlazeFielding** [comment]
Ryujinx closes on the Mysterio boss. Any ideas?

**Comment by BoogieBoard** [comment]
Has anyone been able to play this on the Steam Deck? I am having a difficult time getting the game going. It shows but the a lot of artifacts.

**Comment by BlazeFielding** [comment]
Friends, help. The emulator crashes without an error on the mysterio boss.

**Comment by Boba194230** [comment]
Just figured I’d let everyone know, it works fine on yuzu now, I was able to play an almost perfectly solid 30fps with no graphical glitches a bit into the game(attilan mission)

**Comment by zopzop76** [comment]
> Game Update Version : 1.0.0 and 4.0.1 Current on master : 1.1.369
> 
> Hardware Specs : CPU: Ryzen 7 5800X GPU: AMD Vega 64 RAM: 16GB Radeon Software version: 22.10.3 and 22.11.1
> 
> ![image](https://user-images.githubusercontent.com/68653902/203293752-ebc28649-75a4-4c2e-aaa4-6b9f6c8516ea.png)
> 
> Performance is ok but I still get major artifacting. Happens on both Vulkan and OpenGL.
> 
> [Ryujinx_1.1.369_2022-11-22_11-34-02.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10066585/Ryujinx_1.1.369_2022-11-22_11-34-02.log)
> 
> Edit 2023-01-30: I've tested this on my new 7900XT card, no change whatsoever, aka still getting artifacting same as before.

This seems to be an AMD issue.  I can confirm that I get the same issue you are experiencing on my RX 6400.  Yet when I use my lowly Nvidia Quadro K620 the game runs just fine.  In fact it runs at 30fps (which is the native max FPS) like 90% of the time.  AMD has such garbage drivers :(

**Comment by GamerzHell9137** [comment]
### Game Name

Marvel Ultimate Alliance 3: The Black Order

### Game Update Version

v1.0.0

### Emulator Build Version

1.1.773

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 3600*
- ##### GPU: *NVIDIA RTX 3060 Ti*
- ##### RAM: *16GB*

### Game State

Game plays, looks and runs as intended.

### Screenshots
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/d8ba35b1-4bd0-40ae-81ee-2a91e97e3db8)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/c3fba647-051c-4586-9cb4-b918fe1807ac)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/0372727a-233d-45e7-a837-439c4f219c4d)

### Log File

_No response_

**Comment by gdkchan** [comment]
Can you attach a save to allow reproducing the issue? Also can it be reproduced without needing to finish said battle?

**Comment by pfnieto** [comment]
Yes, here's the save.
[save.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/11679984/save.zip)
I don't think you can reproduce it without the first battle, since Misterio spawns right after you defeat the first 3, without a cutscene or anything like that to separate them.

**Comment by pfnieto** [comment]
Game Update Version: v4.0.1
Emulator Build Version: 1.1.896
Graphics Backend: OpenGL
Hardware Specs:

    CPU: Ryzen 7 5800X3D
    GPU: NVIDIA RTX 3080
    RAM: 32GB

I'd previously mentioned that you could avoid the crash wne Mysterio spawns by switching toOpenGL. As of build 1.1.896, this no longer seems to be the case, as it now crashes at that same exact spot on it, just like Vulkan, rendering progression impossible.
Here's the log file:
[Ryujinx_1.1.896_2023-06-16_08-57-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11770504/Ryujinx_1.1.896_2023-06-16_08-57-23.log)
And the save data just before the fight:
[save.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/11770508/save.zip)

The way to trigger the crash is:
1. Go to main menu, press continue
2. Press the orange button to open the door in front of you, head in
3. Fight the 3 bosses until a cutscene triggers part 2 of the fight
4. Defeat the 3 bosses, each will get captured
5. Once they're all down, Mysterio will appear and the game'll crash

**Comment by yonigold1** [comment]
On MacOS (at least for me) I cannot get past the title screen it just won’t do anything when I press any of the arrows on the arrow pad. Music still plays and when adding the game updates the change log on the title screen is usable. Anyone else experiencing this?

**Comment by gdkchan** [comment]
Can you test if the issue still happens on OpenGL and Vulkan on latest version @pfnieto?

**Comment by pfnieto** [comment]
Haven't tried OpenGL yet, but can confirm that the crash is gone on Vulkan as of the newest update, which means the entirety of the base game can now be completed without crashes. There's some visual bugs in some missions but nothing that stops progression.
Will test the DLC soon to see if that can be completed too.

**Comment by Toranks** [comment]
Crash with OpenGL and Vulkan when I start Avengers Tower scene on the story.  I've tried numerous different configurations, and nothing seems to work.

Here is the log and savegame to try.

[save00.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/14285404/save00.zip)

[Ryujinx_1.1.1192_2024-02-14_15-05-21.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14285406/Ryujinx_1.1.1192_2024-02-14_15-05-21.log)
