### ISSUE TITLE
The Elder Scrolls V: Skyrim

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#1536]
#### Current on `master` : 1.0.4665

Boots to title screen and hangs almost immediately.

#### Screenshots :

![2020-05-31 12_00_09-Ryujinx 1 0 4665 - The Elder Scrolls V_ Skyrim v1 0 12 517175 (01000A10041EA000)](https://user-images.githubusercontent.com/62343878/83364135-26b5f880-a35c-11ea-82d6-6d17a394c467.png)
![2020-05-31 12_00_18-Ryujinx 1 0 4665 - The Elder Scrolls V_ Skyrim v1 0 12 517175 (01000A10041EA000)](https://user-images.githubusercontent.com/62343878/83364136-27e72580-a35c-11ea-9339-96bc0119eff1.png)
![2020-05-31 12_01_18-Ryujinx 1 0 4665 - The Elder Scrolls V_ Skyrim v1 0 12 517175 (01000A10041EA000)](https://user-images.githubusercontent.com/62343878/83364139-287fbc00-a35c-11ea-917f-585085b56dfb.png)

#### Log file :

[TESVS.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4708594/TESVS.zip)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6895

**Comment by MetrosexualGarbodor** [comment]
Needs an update.

**Comment by MutantAura** [comment]
Game Update Version : 1.0.12.517175
Current on master : 1.1.137

Goes in-game and seems playable so-far. Only completed tutorial.
Some lighting can flicker on the floor but I'm unsure if this was due to playing with the resolution scaler.

Hardware Specs :
CPU: Ryzen 7 5600X
GPU: NVIDIA RTX 3070
RAM: 32GB

![ryujinx_capture_2022-06-03_00-17-48](https://user-images.githubusercontent.com/44103205/171753893-875ed4ee-b4c6-4bff-bee1-c8d5187649e8.png)
![ryujinx_capture_2022-06-03_00-11-41-min](https://user-images.githubusercontent.com/44103205/171753985-ae315dcf-d78d-4e59-b5ec-ef00bd3c5fdf.png)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by nsklaus** [comment]
game runs and plays very nicely, but crashes frequently. i'm getting the same error as the opening post on this entry (audio error, index out of bound of array exception):

```
00:15:18.981 |E| AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.DataSourceHelper.ProcessWaveBuffers(IVirtualMemoryManager memoryManager, Span`1 outputBuffer, WaveBufferInformation& info, Span`1 wavebuffers, VoiceUpdateState& voiceState, UInt32 targetSampleRate, Int32 sampleCount) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Dsp/DataSourceHelper.cs:line 142
   at Ryujinx.Audio.Renderer.Dsp.Command.DataSourceVersion2Command.Process(CommandList context) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Dsp/Command/DataSourceVersion2Command.cs:line 88
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Dsp/Command/CommandList.cs:line 116
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Dsp/AudioProcessor.cs:line 182
   at System.Threading.Thread.StartCallback()
```

tested on  m2pro (macbook 2023), 
firmware version: 16.0.3, 
ryujinx version: 1.1.1015
skyrim version: 1.1.177.3285177 (ReleaseFinal)

**Comment by juvenn** [comment]
It happens with latest version as well. Other than that, game renders exceptionally well.

```
Firmware: 18.1.0
Ryujinx: 1.1.1345
Skyrim: 1.1.14.534571
```

<details>

<summary>Error stack</summary>

```
00:17:46.217 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 18
00:17:46.217 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 19
00:17:46.240 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075 ; isAtRest: True}
00:17:46.241 |E| AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.DataSourceHelper.ProcessWaveBuffers(IVirtualMemoryManager memoryManager, Span`1 outputBuffer, WaveBufferInformation& info, Span`1 wavebuffers, VoiceUpdateState& voiceState, UInt32 targetSampleRate, Int32 sampleCount) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Dsp/DataSourceHelper.cs:line 49
   at Ryujinx.Audio.Renderer.Dsp.Command.AdpcmDataSourceCommandVersion1.Process(CommandList context) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Dsp/Command/AdpcmDataSourceCommandVersion1.cs:line 60
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Dsp/Command/CommandList.cs:line 116
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Audio/Renderer/Dsp/AudioProcessor.cs:line 207
   at System.Threading.Thread.StartCallback()
```

</details>

<details>

<summary>Startup profile</summary>

```
00:00:00.167 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.171 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.171 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.172 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.172 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.173 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.173 |I| Configuration LogValueChange: PreferredGpu set to: 0x106B_0xE0203EF
00:00:00.173 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.174 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.174 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.174 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.178 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.178 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.178 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.178 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.178 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.178 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.178 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.178 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.178 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.179 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.179 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.180 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMapped
00:00:00.180 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.180 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.180 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.181 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.182 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1345
00:00:00.184 |N| Application Print: Operating System: macOS 14.2.1 (23C71) (Arm64)
00:00:00.184 |N| Application Print: CPU: Apple M1 Pro ; 10 logical
00:00:00.185 |N| Application Print: RAM: Total 32 GiB ; Available 10.2 GiB
00:00:00.187 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.187 |N| Application PrintSystemInfo: Launch Mode: UserProfile
```
</details>
