### ISSUE TITLE
Risk of Rain 2

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1538]
#### Current on `master` : 1.0.4665

The menu screen has a lot of vertex explosions. Trying to get ingame results in a crash.

```
00:03:56.680 | ServiceNifm GetCurrentIpConfigInfo: Console's local IP is "192.168.1.5".
00:03:56.823 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: The information requested is unavailable on the current platform.
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties.get_IsDynamicDnsEnabled()
   at Ryujinx.HLE.HOS.Services.Nifm.StaticService.Types.DnsSetting..ctor(IPInterfaceProperties interfaceProperties) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nifm\StaticService\Types\DnsSetting.cs:line 16
   at Ryujinx.HLE.HOS.Services.Nifm.StaticService.IGeneralService.GetCurrentIpConfigInfo(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nifm\StaticService\IGeneralService.cs:line 90
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: The information requested is unavailable on the current platform.
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties.get_IsDynamicDnsEnabled()
   at Ryujinx.HLE.HOS.Services.Nifm.StaticService.Types.DnsSetting..ctor(IPInterfaceProperties interfaceProperties) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nifm\StaticService\Types\DnsSetting.cs:line 16
   at Ryujinx.HLE.HOS.Services.Nifm.StaticService.IGeneralService.GetCurrentIpConfigInfo(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nifm\StaticService\IGeneralService.cs:line 90
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Screenshots :

![06_01_35-00:35:54](https://user-images.githubusercontent.com/62521228/83364260-5850b300-a3a0-11ea-9ab2-e563647f6fb5.png)
![06_01_37-00:37:05](https://user-images.githubusercontent.com/62521228/83364261-5a1a7680-a3a0-11ea-9d08-06bb7be46866.png)

#### Log file :

[risk-of-rain-2.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4708606/risk-of-rain-2.log)

**Comment by benderscruffy** [comment]
goes ingame now
but everything is rainbow colours

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Shock9616** [comment]
Game crashes after selecting something on the main menu on MacOS. Tested on the original MacOS release and a self-built copy of the latest version (v1.1.1+0 at the time of writing).
[Ryujinx_1.1.1+0_2023-03-20_18-42-29.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11024299/Ryujinx_1.1.1%2B0_2023-03-20_18-42-29.log)

**Comment by gdkchan** [comment]
Works fine on my 2020 MacBook Air.
<img width="1392" alt="Captura de Tela 2023-03-21 às 09 00 47" src="https://user-images.githubusercontent.com/5624669/226600301-ed78bd9c-2f1f-4c26-b29f-df84a334ce23.png">
Built https://github.com/Ryujinx/Ryujinx/commit/17620d18db8d4a67e4b917596c760107d26fadc5

**Comment by muermo** [comment]
I have the system configuration in Spain - Europe, but the game does not come out in Spanish, the language that is included in the game.
Ryujinx Version 1.1.1217
