### ISSUE TITLE
Pushy and Pully in Blockland

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1541]
#### Current on `master` : 1.0.4665

Game played fine until I finished the session and then it crashed crashed with an missing service error at the highscore screen.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IRequest: 21

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00288ec8 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> >, 4ul, 12ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, unsigned int)
   sdk:0x002886c4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::nifm::detail::IRequest, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::nifm::detail::IRequest, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_GetAppletInfo(nn::sf::Out<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::sf::OutBuffer const&, unsigned int)
   sdk:0x00286478 nn::nifm::detail::RequestClient::PrepareLibraryApplet(nn::applet::LibraryAppletHandle*)
   sdk:0x0028be74 nn::nifm::PrepareHandlingNetworkRequestResult(nn::nifm::RequestHandle, nn::applet::LibraryAppletHandle*)
   sdk:0x0028de38 nn::nifm::NetworkConnection::HandleNetworkRequestErrorResult()
   sdk:0x0028c634 nn::nifm::HandleNetworkRequestErrorResult()
   main:0x01e14a18 Sub0000000009e18a18
   main:0x01e13bc4 Sub0000000009e17bc4
   main:0x01e13ed0 Sub0000000009e17ed0
   sdk:0x000cfb48 Sub000000000b96eb48
   sdk:0x000d4314 Sub000000000b973314
   ??? Sub0000000000000000

Buffer Information:
        ReceiveBuff:
        Position: 0x000000119fbb5e3c Size: 0x0000000000001000 Flags: 0

Raw Request Data:
00000000   01 00 14 00 03 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  15 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000030   00 00 00 00                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Screenshots :

![06_01_46-00:46:42](https://user-images.githubusercontent.com/62521228/83364547-4d971d80-a3a2-11ea-9245-05643ed4b5e5.png)
![06_01_47-00:47:02](https://user-images.githubusercontent.com/62521228/83364548-4e2fb400-a3a2-11ea-85a3-f389692bdece.png)
![06_01_47-00:47:26](https://user-images.githubusercontent.com/62521228/83364549-4e2fb400-a3a2-11ea-9ee1-8a51408bb602.png)
![06_01_47-00:47:37](https://user-images.githubusercontent.com/62521228/83364550-4ec84a80-a3a2-11ea-8212-f92f2597936f.png)
![06_01_47-00:47:46](https://user-images.githubusercontent.com/62521228/83364551-4f60e100-a3a2-11ea-8786-c08c9cff55d0.png)
![06_01_51-00:51:36](https://user-images.githubusercontent.com/62521228/83364552-4f60e100-a3a2-11ea-8e82-f82c561de7de.png)
![06_01_52-00:52:36](https://user-images.githubusercontent.com/62521228/83364554-4ff97780-a3a2-11ea-90d2-1f3a1a6aeada.png)
![06_01_52-00:52:54](https://user-images.githubusercontent.com/62521228/83364555-4ff97780-a3a2-11ea-952d-3c2e396db50c.png)
![06_01_53-00:53:14](https://user-images.githubusercontent.com/62521228/83364557-538cfe80-a3a2-11ea-84f0-16c9433b418a.png)

#### Log file :

[pushy-and-pully-in-blockland.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4708639/pushy-and-pully-in-blockland.log)

**Comment by SeraUX** [comment]
## Pushy and Pully in Blockland

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.4829

Game works without any problems found.

#### Hardware Specs :

##### CPU: i3 7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti
##### RAM: 8GB

#### Screenshots :

![07_04_03-10:03:55](https://user-images.githubusercontent.com/62521228/86508193-6bf79b00-bdde-11ea-87c3-55bbbbce6abe.png)
![07_04_04-10:04:15](https://user-images.githubusercontent.com/62521228/86508194-6d28c800-bdde-11ea-8130-854d3a470094.png)
![07_04_04-10:04:22](https://user-images.githubusercontent.com/62521228/86508196-6d28c800-bdde-11ea-8797-389a39efc4f6.png)
![07_04_04-10:04:41](https://user-images.githubusercontent.com/62521228/86508197-6dc15e80-bdde-11ea-95ea-837a0d204e56.png)
![07_04_04-10:04:52](https://user-images.githubusercontent.com/62521228/86508199-6e59f500-bdde-11ea-89cb-4618767fe89e.png)
![07_04_05-10:05:01](https://user-images.githubusercontent.com/62521228/86508200-6e59f500-bdde-11ea-850c-19eb365c2925.png)
![07_04_05-10:05:25](https://user-images.githubusercontent.com/62521228/86508201-6ef28b80-bdde-11ea-92bb-9ee01be44b67.png)
![07_04_05-10:05:44](https://user-images.githubusercontent.com/62521228/86508203-6f8b2200-bdde-11ea-99ed-6cb33d32de46.png)
![07_04_05-10:05:55](https://user-images.githubusercontent.com/62521228/86508204-6f8b2200-bdde-11ea-8c9f-06f4afa5e4e6.png)
![07_04_06-10:06:10](https://user-images.githubusercontent.com/62521228/86508205-7023b880-bdde-11ea-96ed-6cacbfa4bb76.png)

#### Log file :

[papib.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4872277/papib.log)

**Comment by EmulationFanatic** [comment]
Updated
