### ISSUE TITLE
LEGO Harry Potter Collection

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1608]
#### Current on `master` : 1.0.4675

Game loads through menus to select an embedded game but crashes when attempting to actually start a game.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: Unable to delete file C:\Users\<REDACTED>\AppData\Roaming\Ryujinx\bis\user\save\000000000000051e\1
   at LibHac.FsSystem.LocalFileSystem.EnsureDeleted(FileSystemInfo entry)
   at LibHac.FsSystem.LocalFileSystem.DeleteDirectoryInternal(DirectoryInfo dir, Boolean recursive)
   at LibHac.FsSystem.LocalFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.SynchronizeDirectory(U8Span destPath, U8Span sourcePath)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.Initialize(Boolean isPersistentSaveData, Boolean canCommitProvisionally)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.CreateNew(DirectorySaveDataFileSystem& created, IFileSystem baseFileSystem, Boolean isPersistentSaveData, Boolean canCommitProvisionally)
   at LibHac.FsService.Creators.SaveDataFileSystemCreator.Create(IFileSystem& fileSystem, ISaveDataExtraDataAccessor& extraDataAccessor, IFileSystem sourceFileSystem, UInt64 saveDataId, Boolean allowDirectorySaveData, Boolean useDeviceUniqueMac, SaveDataType type, ITimeStampGenerator timeStampGenerator)
   at LibHac.FsService.FileSystemProxyCore.OpenSaveDataFileSystem(IFileSystem& fileSystem, SaveDataSpaceId spaceId, UInt64 saveDataId, String saveDataRootPath, Boolean openReadOnly, SaveDataType type, Boolean cacheExtraData)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystemImpl(IFileSystem& fileSystem, UInt64& saveDataId, SaveDataSpaceId spaceId, SaveDataAttribute& attribute, Boolean openReadOnly, Boolean cacheExtraData)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystem3(IFileSystem& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute, Boolean openReadOnly)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystem2(IFileSystem& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute, Boolean openReadOnly)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystem(IFileSystem& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute)
   at Ryujinx.HLE.HOS.Services.Fs.IFileSystemProxy.OpenSaveDataFileSystem(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Fs\IFileSystemProxy.cs:line 244
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Log file :

[LHPC.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4726740/LHPC.zip)

**Comment by benderscruffy** [comment]
looks like they are both stuck on a loading screen now

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Beckham012** [comment]
Any way to fix the issue?

**Comment by Luis-v3** [comment]
Tengo el mismo problema no puedo poner los Objetos Lego en el Lugar Indicado.
![Desktop Screenshot 2022 02 22 - 16 17 26 83](https://user-images.githubusercontent.com/100239782/155220944-b45dc9d0-5299-45ed-811f-a888a8fe65ee.png)

**Comment by EmulationFanatic** [comment]
Same status on 1.1.205

**Comment by Darkcranio95** [comment]
You can progress as of 2024 latest, but here are graphical bugs, flickering of textures on both backends it looks like a graphics card is dying, sometimes chinese characters pop in, strange.
