### ISSUE TITLE
HyperParasite

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1614]
#### Current on `master` : 1.0.4675

Game crashes with an missing service error.

```
00:00:19.417 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Ns.IAddOnContentManager: 8

Guest Stack Trace:
Process: HyperParasi, PID: 81
   sdk:0x000a094c nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutHandleArgumentInfo<0, 1> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutHandleArgumentInfo<0, 1> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::OutHandleClientArgumentType, unsigned int)
   sdk:0x0013bfd4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::aocsrv::detail::IAddOnContentManager, nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6>, nn::sf::MemoryResourceAllocationPolicy, nn::aocsrv::detail::IAddOnContentManager, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_GetAddOnContentListChangedEvent(nn::sf::Out<nn::sf::NativeHandle, void>)
   sdk:0x0013ba84 nn::aoc::GetAddOnContentListChangedEvent(nn::os::SystemEvent*)
   main:0x00831b08 Sub0000000008835b08
   main:0x0083a9b0 Sub000000000883e9b0
   sdk:0x000cfb48 Sub000000000f085b48
   sdk:0x000d4314 Sub000000000f08a314
   ??? Sub0000000000000000

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  08 00 00 00 00 00 00 00   SFCI············
00000010   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Ns.IAddOnContentManager: 8

Guest Stack Trace:
Process: HyperParasi, PID: 81
   sdk:0x000a094c nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutHandleArgumentInfo<0, 1> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutHandleArgumentInfo<0, 1> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::OutHandleClientArgumentType, unsigned int)
   sdk:0x0013bfd4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::aocsrv::detail::IAddOnContentManager, nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6>, nn::sf::MemoryResourceAllocationPolicy, nn::aocsrv::detail::IAddOnContentManager, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_GetAddOnContentListChangedEvent(nn::sf::Out<nn::sf::NativeHandle, void>)
   sdk:0x0013ba84 nn::aoc::GetAddOnContentListChangedEvent(nn::os::SystemEvent*)
   main:0x00831b08 Sub0000000008835b08
   main:0x0083a9b0 Sub000000000883e9b0
   sdk:0x000cfb48 Sub000000000f085b48
   sdk:0x000d4314 Sub000000000f08a314
   ??? Sub0000000000000000

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  08 00 00 00 00 00 00 00   SFCI············
00000010   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

#### Pull requests needed :

https://github.com/Ryujinx/Ryujinx/pull/1221

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/636

#### Log file :

[hyperparasite.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4732503/hyperparasite.log)

**Comment by EmulationFanatic** [comment]
Needs update

**Comment by SeraUX** [comment]
## HyperPrasite

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.4740

Game crashes on boot with an segfault error on every try.

#### Hardware Specs :

##### CPU: i3 7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti
##### RAM: 8GB

#### Log file :

[hyperparasite.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4809621/hyperparasite.log)

**Comment by EmulationFanatic** [comment]
## HyperParasite

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.4740

Crashes either when the nvdec cutscene begins, or after skipping it while trying to load the next content.

```
Message: '[2020.06.21-21.17.16:000][266]LowLevelFatalError [File:Unknown] [Line: 1155] 
GameThread timed out waiting for RenderThread aft'

00:04:18.512 | ServiceLm Log: Guest log:
 Log level: Info
 Message: 'er 120.00 secs'

00:04:18.542 | ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:04:19.290 | HLE.HostThread.3 Cpu PrintGuestStackTrace: Guest stack trace:
Process: HyperParasi, PID: 81
   sdk:0x00054e10 Sub000000000f00ae10
   sdk:0x00054ed8 Sub000000000f00aed8
   sdk:0x00054f70 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   main:0x0082b8a0 Sub000000000882f8a0
   main:0x007cfe98 Sub00000000087d3e98
   main:0x00ddabfc Sub0000000008ddebfc
   main:0x0000be68 Sub000000000800fe68
   main:0x00013b08 Sub0000000008017b08
   sdk:0x000cfb48 Sub000000000f085b48
   sdk:0x000d4314 Sub000000000f08a314
   ??? Sub0000000000000000
```

#### Hardware Specs : 

##### CPU: i5-6600K
##### GPU: NVIDIA GT 740SC
##### RAM: 16GB


#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-06-21 15_14_55-Ryujinx 1 0 4740 - HyperParasite v1 0 0 (010061400ED90000) (64-bit)](https://user-images.githubusercontent.com/62343878/85235485-84c18300-b3d2-11ea-8ee4-886e6dd9c4b9.png)


#### Log file :
[HP.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4810277/HP.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same issue with 1.0.6215

**Comment by EmulationFanatic** [comment]
Updated
