### ISSUE TITLE
Uta no Prince-sama Amazing Aria & Sweet Serenade LOVE

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1621]
#### Current on `master` : 1.0.4682

Game crashes on boot.

```
00:00:54.088 | GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 423
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 143
   at Ryujinx.Graphics.Gpu.Engine.Methods.FinishTransfer() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 79
   at Ryujinx.Graphics.Gpu.Engine.Methods.LoadInlineData(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 66
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 105
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 497
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 183
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 102
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CachedMacro.Execute(Int32[] mme, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 73
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 218
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 262
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[uta-no-prince-sama.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4739709/uta-no-prince-sama.log)

**Comment by benderscruffy** [comment]
using 1.1.21
goes ingame now
no problems so far
![ryujinx_capture_2022-02-09_16-45-56](https://user-images.githubusercontent.com/2696404/153159158-0d3de55e-85ce-470c-9cb2-29f8932765a1.png)
![ryujinx_capture_2022-02-09_16-45-59](https://user-images.githubusercontent.com/2696404/153159162-f3ffbecb-543c-4edc-8336-c13077b45fef.png)
![ryujinx_capture_2022-02-09_16-46-03](https://user-images.githubusercontent.com/2696404/153159165-ad2042c0-7351-4b10-b99f-fa4743eed9dc.png)
![ryujinx_capture_2022-02-09_16-46-15](https://user-images.githubusercontent.com/2696404/153159167-49447f39-54dc-4279-8f64-a1b94b4903be.png)
![ryujinx_capture_2022-02-09_16-46-28](https://user-images.githubusercontent.com/2696404/153159188-7f990898-3057-4434-9d9d-acadaf05ed51.png)
![ryujinx_capture_2022-02-09_16-46-34](https://user-images.githubusercontent.com/2696404/153159217-0d59e909-6e9c-4818-8155-4d9d84b46888.png)
![ryujinx_capture_2022-02-09_16-47-32](https://user-images.githubusercontent.com/2696404/153159223-f7d6dfbf-094b-4965-ab15-d56be977fda4.png)
![ryujinx_capture_2022-02-09_16-47-41](https://user-images.githubusercontent.com/2696404/153159231-3b71dd8d-00c7-4b31-96b1-a8f0eebadccf.png)
![ryujinx_capture_2022-02-09_16-47-50](https://user-images.githubusercontent.com/2696404/153159237-6a778ece-23a1-439d-973d-2a6906500dfb.png)
![ryujinx_capture_2022-02-09_16-47-57](https://user-images.githubusercontent.com/2696404/153159247-43fe402f-2286-4b9f-a346-03cd602bd220.png)
![ryujinx_capture_2022-02-09_16-48-19](https://user-images.githubusercontent.com/2696404/153159257-bb26b654-7886-4eff-88ef-6a6779afc469.png)
![ryujinx_capture_2022-02-09_16-48-28](https://user-images.githubusercontent.com/2696404/153159270-2e56212a-107d-4408-8279-ce3fd599f9b6.png)
![ryujinx_capture_2022-02-09_16-48-34](https://user-images.githubusercontent.com/2696404/153159279-ea03b8a3-5fdb-49f4-8e1c-0ecf8a7a2afe.png)
![ryujinx_capture_2022-02-09_16-48-40](https://user-images.githubusercontent.com/2696404/153159293-474c7fcc-023b-4078-8e12-7dfb6d05139d.png)
