### ISSUE TITLE
Ghost Blade HD

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1625]
#### Current on `master` : 1.0.4682

Game crashes on boot with an missing service error.

```
00:00:15.284 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IRequest: 21

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00316198 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> >, 4ul, 12ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, unsigned int)
   sdk:0x00315994 nn::sf::cmif::client::detail::CmifProxyImpl<nn::nifm::detail::IRequest, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::nifm::detail::IRequest, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_GetAppletInfo(nn::sf::Out<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::sf::OutBuffer const&, unsigned int)
   sdk:0x003137ec nn::nifm::detail::RequestClient::PrepareLibraryApplet(nn::applet::LibraryAppletHandle*)
   sdk:0x00318fe4 nn::nifm::PrepareHandlingNetworkRequestResult(nn::nifm::RequestHandle, nn::applet::LibraryAppletHandle*)
   sdk:0x0031aad8 nn::nifm::NetworkConnection::HandleNetworkRequestErrorResult()
   sdk:0x003197c4 nn::nifm::HandleNetworkRequestErrorResult()
   main:0x00024cf8 Sub0000000008028cf8
   main:0x000245dc Sub00000000080285dc
   main:0x0006e080 Sub0000000008072080
   main:0x0002cc28 Sub0000000008030c28
   main:0x00029840 Sub000000000802d840
   main:0x00000378 nnMain
   sdk:0x00296c9c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Buffer Information:
        ReceiveBuff:
        Position: 0x000000000ad9eb1c Size: 0x0000000000001000 Flags: 0

Raw Request Data:
00000000   01 00 14 00 03 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  15 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  00 00 01 00 00 00 03 00   ················
00000030   00 00 03 00                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/671

#### Log file :

[ghost-blade.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4741006/ghost-blade.log)

**Comment by SeraUX** [comment]
## Ghost Blade HD

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.4829

Game crashes with an missing service error.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x001fbe90 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> > >::ProcessWithOutObjects(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*)
   sdk:0x0003fd54 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::baas::IManagerBase, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::baas::IManagerForApplication, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_EnsureIdTokenCacheAsync(nn::sf::Out<nn::sf::SharedPointer<nn::account::detail::IAsyncContext>, void>)
   sdk:0x0004a718 nn::account::EnsureNetworkServiceAccountIdTokenCacheAsync(nn::account::AsyncContext*, nn::account::UserHandle const&)
   main:0x00027f44 Sub000000000802bf44
   main:0x00027e58 Sub000000000802be58
   main:0x000280f0 Sub000000000802c0f0
   main:0x00075454 Sub0000000008079454
   sdk:0x00329e88 Sub000000000a2ece88
   sdk:0x0032e294 Sub000000000a2f1294
   ??? Sub0000000000000000

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  02 00 00 00 00 00 00 00   SFCI············
00000020   01 00 00 00 00 00 00 00  00 FD 53 BB 11 00 04 00   ·········ýS»····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Hardware Specs :

##### CPU: i3 7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti
##### RAM: 8GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Log file :

[ghost-blade-hd.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4872239/ghost-blade-hd.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
