### ISSUE TITLE
DEADLY PREMONITION Origins

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1634]
#### Current on `master` : 1.0.4683

Has nvdec cutscene issue on intro. Crashes after trying to launch the game from the menu.

```
HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000005eb410 (opcode 0xf3f90760) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 98
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-06-08 08_25_53-Ryujinx 1 0 4683 - DEADLY PREMONITION Origins v1 0 0 (0100EBE00F22E000) (32-bit)](https://user-images.githubusercontent.com/62343878/84042391-3cca4700-a962-11ea-91c6-53c65c441f31.png)
![2020-06-08 08_27_12-Ryujinx 1 0 4683 - DEADLY PREMONITION Origins v1 0 0 (0100EBE00F22E000) (32-bit)](https://user-images.githubusercontent.com/62343878/84042395-3dfb7400-a962-11ea-9534-57dcdf080544.png)
![2020-06-08 08_28_16-Ryujinx 1 0 4683 - DEADLY PREMONITION Origins v1 0 0 (0100EBE00F22E000) (32-bit)](https://user-images.githubusercontent.com/62343878/84042399-3dfb7400-a962-11ea-91db-3a7f21fb987a.png)
![2020-06-08 08_28_50-Ryujinx 1 0 4683 - DEADLY PREMONITION Origins v1 0 0 (0100EBE00F22E000) (32-bit)](https://user-images.githubusercontent.com/62343878/84042404-405dce00-a962-11ea-9188-b9479bca1f3e.png)
![2020-06-08 08_28_57-Ryujinx 1 0 4683 - DEADLY PREMONITION Origins v1 0 0 (0100EBE00F22E000) (32-bit)](https://user-images.githubusercontent.com/62343878/84042415-4489eb80-a962-11ea-9731-d36cca012823.png)

#### Log file :

[DPO.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4746573/DPO.zip)

**Comment by riperiperi** [comment]
The instruction listed is fixed in this PR:
https://github.com/Ryujinx/Ryujinx/pull/1300

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by plcharriere** [comment]
Game randomly freezes on version 1.1.1072
macOS, M1 Pro 16GB

[Ryujinx_1.1.1072_2023-11-08_15-37-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13301151/Ryujinx_1.1.1072_2023-11-08_15-37-46.log)


<img width="1204" alt="image" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/48135922/18c7c372-6d8a-498e-b2ae-83cf0057a5cb">

**Comment by NineKain** [comment]
The game does drop heavily in frames in the overworld, almost hitting 15fps on a fairly powerful machine.
[Ryujinx_1.1.1226_2024-03-13_23-09-26.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14594573/Ryujinx_1.1.1226_2024-03-13_23-09-26.log)

**Comment by X0Reactor** [comment]
Just wanted to add this: The framerate dropping isn't a Ryu problem, but an actual game problem. On the Switch console, visit the town during the day and drive towards the community center. When you start getting close, the framerate will drop to around 15-20 fps. Even when overclocking my Switch, the framerate drops still happen.
