### ISSUE TITLE
DOOM 2

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1645]
#### Current on `master` : 1.0.4683

Has nvdec cutscene issue on intro. This can be skipped. Crashes after cutscene is over or is skipped.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IRequest: 21
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/671

#### Log file :

[D2.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4753332/D2.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by LukeWarnut** [comment]
## DOOM 2

#### Game Update Version : 1.0.6

#### Current on `master` : 1.0.6798

1.0.0:
Game proceeds to the title screen, but cannot progress without connection to bethesda.net

1.0.6:
Game crashes on startup.
```
00:00:57.120 |E| HLE.GuestThread.39 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: va=0x1547A034FFFFFF92, size=0x0000000000000008
   at Ryujinx.Cpu.MemoryManager.AssertValidAddressAndSize(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 567
   at Ryujinx.Cpu.MemoryManager.SignalMemoryTracking(UInt64 va, UInt64 size, Boolean write) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 678
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 150
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 141
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs : 

##### CPU: AMD Ryzen 5 2600
##### GPU: NVIDIA GTX 1660 SUPER
##### RAM: 16GB

#### Screenshots :

![image](https://user-images.githubusercontent.com/65521430/112372106-bfd04a00-8cb5-11eb-9b59-6f2166a57a0c.png)

#### Log file :

[D2-1.0.0.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6199981/D2-1.0.0.log)
[D2-1.0.6.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6199984/D2-1.0.6.log)

**Comment by LukeWarnut** [comment]
## DOOM 2

#### Game Update Version : 1.0.0 / 1.0.6 / 1.0.7

#### Current on `master` : 1.0.6906

1.0.0:
Game proceeds to the title screen, but cannot progress without connection to bethesda.net

1.0.6:
Game crashes on startup.

1.0.7:
Game plays flawlessly at a high FPS.

_Error from 1.0.6:_
```
00:00:27.519 |E| HLE.GuestThread.40 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFD9FA774F000.
00:00:27.573 |E| HLE.GuestThread.40 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in C:\projects\ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 214
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 171
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1038
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs : 

##### CPU: AMD Ryzen 5 2600
##### GPU: NVIDIA GTX 1660 SUPER
##### RAM: 16GB

#### Screenshots :

1.0.0:
![](https://cdn.discordapp.com/attachments/684131856433807401/850099505218846741/unknown.png)
1.0.7:
![](https://cdn.discordapp.com/attachments/684131856433807401/850099853413580840/unknown.png)
![](https://cdn.discordapp.com/attachments/684131856433807401/850100006697959474/unknown.png)
![image](https://user-images.githubusercontent.com/65521430/120704776-03e58500-c485-11eb-9329-a3d6c33d3fdb.png)
![image](https://user-images.githubusercontent.com/65521430/120704806-0ba52980-c485-11eb-99ae-15aeb8a74f9e.png)
![image](https://user-images.githubusercontent.com/65521430/120704816-0f38b080-c485-11eb-87e1-eedb7eedcfbe.png)

#### Log file :

[DOOM2-100.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6594060/DOOM2-100.log)
[DOOM2-106.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6594061/DOOM2-106.log)
[DOOM2-107.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6594062/DOOM2-107.log)

**Comment by EmulationFanatic** [comment]
Updated, thanks!
