### ISSUE TITLE
Mortal Kombat 11

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#165]
#### Current on `master` :

* Build Version : 1.0.2590

```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.ISelfController: 91
```

Implement that, and then crash:
```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Time.IStaticService: 20
```

Implement that, and then crash:
```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Fspsrv.IFileSystemProxy: 62
```

#### Pull requests needed :

https://github.com/Ryujinx/Ryujinx/pull/672

#### Outstanding Issues:

- https://github.com/Ryujinx/Ryujinx/issues/615
- https://github.com/Ryujinx/Ryujinx/issues/616

**Comment by EmulationFanatic** [comment]
Updated

**Comment by ryulovesjinx** [comment]
Maybe a regression on this one ?

**Game do not boot at all.**

Without hacks; (Ignore missing services OFF):

00:00:06.763 |E| HLE.OsThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Fs.IFileSystemProxy: 34

Guest Stack Trace:
Process: Service, PID: 92

Raw Request Data:
00000000   01 00 12 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  22 00 00 00 00 00 00 00   SFCI····"·······
00000020   00 00 00 00 00 00 00 00  00 00 00 00               ············    

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

With hacks; (Ignore missing services ON):

00:00:07.048 |E| HLE.OsThread.15 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: DataErase applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system)
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system)
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by codbugpatrol** [comment]
On 1.0.7066, games enters the battle and vertex explosions appear.
Videos are not fluid.

![image](https://user-images.githubusercontent.com/85196112/136639285-b0f11c68-5f2b-4613-a440-6ae50b974970.png)
![image](https://user-images.githubusercontent.com/85196112/136639291-0342a3bc-7df4-4b92-b163-515e180f3729.png)
![image](https://user-images.githubusercontent.com/85196112/136639329-5bfb07d7-cc9a-4666-b8fd-7bf2a7a4645a.png)
![image](https://user-images.githubusercontent.com/85196112/136639332-1390ea4e-1d80-4e3f-ace3-0515e2ccc69e.png)

00:03:05.564 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000048 (0x50F41BA060170407).
00:03:05.565 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x0002D0 (0x50F41BA06FF70407).
00:03:05.565 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x0002D8 (0x50F01BA00017040F).
00:03:05.565 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x0002E8 (0x50F01BA000270417).
00:03:05.565 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000328 (0x50F01BA000370407).
00:03:05.566 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000090 (0x50F01BA00027030F).
00:03:05.566 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x0000A8 (0x50F01BA000170307).
00:03:05.566 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x0000B8 (0x50F01BA000370317).
00:03:05.566 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x0000C8 (0x50F41BA06FF7031F).

[Ryujinx_1.0.7066_2021-10-08_22-31-09.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7314803/Ryujinx_1.0.7066_2021-10-08_22-31-09.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by momoids** [comment]
Mortal Kombat 11 Ultimate

Game Update Version : (1.0.26)

Emulator Build Version : ryujinx-1.1.254-win_x64

Graphics Backend : Vulkan or OpenGL
when I play MK 11 with (update 1.0.26) the Scorpion spear does not appear, but in the base version (1.0.0) it appears normally! Another problem I noticed was that even using Upscale there is no resolution increase effectively! (I'm not native English!)

bugs not fixed to date: no upscale; Scorpion's spear disappears in ultimate version;
![image](https://user-images.githubusercontent.com/70231770/189360097-d588ebfd-3ba0-4b52-859f-0d9f1dcdf607.png)
![image](https://user-images.githubusercontent.com/70231770/189360155-bbf64f44-ec1f-4f94-bdbc-443e47fc1bd3.png)
![image](https://user-images.githubusercontent.com/70231770/189360209-334869f2-0493-4414-aff8-bc53e0a17b66.png)
![image](https://user-images.githubusercontent.com/70231770/189360236-ab2b5d0c-7116-42a6-8a26-ed93e018a1da.png)
![image](https://user-images.githubusercontent.com/70231770/189360269-8c24054a-960f-48c3-a638-8c89a0c70586.png)
![image](https://user-images.githubusercontent.com/70231770/189360300-5c9cef42-4cda-44e9-99fa-811c57179442.png)

Ryujinx version: ryujinx-1.1.254-win_x64

Game version: update 1.0.26

System Specs:

OS: Windows10 x64
CPU: Ryzen 1600x
GPU: GTX 1060 6GB
RAM: 32 GB
Applied Mods : No

**Comment by jonas418** [comment]
Emulator crashes when using Vulkan and performing Raiden's Friendship.
If I switch to OpenGL it works as intended.
I'll upload both Vulkan and OpenGL logs below for comparison.

Also MK11 runs quite sluggish with Vulkan compared to OpenGL.
Almost slow motion feeling from time to time.

Mortal Kombat 11 Update v1.0.26

Ryujinx Version: 1.1.272
Microsoft Windows 10.0.19044 (X64)
CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz ; 12 logical
RAM: Total 32708 MB ; Available 22579 MB
GPU: NVIDIA GeForce GTX 1080 Ti (Vulkan v1.3.205, Driver v516.59.0.0)

Last part of the crash log reads:
00:03:39.417 |G| HLE.OsThread.16 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 219s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Game Thread'
    ProgramName: 'MK11Game-Retail'
    Message: '         Log: [12121][ 5095] Package Raiden_Friendship_ScriptAssets done loading (Completed)'

00:03:39.430 |G| HLE.OsThread.16 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 219s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'Game Thread'
    ProgramName: 'MK11Game-Retail'
    Message: '    SyncWait: [12122][ 5096] [LockStepSyncWait] LockStepSyncWaitBegin: Dismemberment and Texture Streaming [SKIP]'

00:03:41.104 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 223
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\SyncManager.cs:line 46
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_4(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 62
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 130
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 107
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 399
   at System.Threading.Thread.StartCallback()

[Ryujinx_1.1.272_2022-09-16_02-27-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9579774/Ryujinx_1.1.272_2022-09-16_02-27-54.log)
[Ryujinx_1.1.272_2022-09-16_02-39-12_OpenGL.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9579779/Ryujinx_1.1.272_2022-09-16_02-39-12_OpenGL.log)

**Comment by KarenNscmnto** [comment]
OS: Windows 11
CPU: Ryzen 5600G
GPU: XFX RX580 (Driver 23.9.1)
RAM: 16 GB
GAME VER: 1.0.26

No one shadow glitch anymore, Solid 60 FPS on x2 resolution except on "Kronika's Hourglass" stage where FPS is very very low 5~17 FPS on any resolution scale.

**Comment by jonas418** [comment]
Retried Raiden's friendship with emulator version 1.1.1032. Still crashing when using vulkan.
[Ryujinx_1.1.1032_2023-09-27_21-28-24_crash.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12743106/Ryujinx_1.1.1032_2023-09-27_21-28-24_crash.log)

On the positive side vulkan has gotten a huge performance increase in this game since my last post over a year ago.
However, I do agree with KarenNscmnto in the post above. There are some heavy slowdowns in Kronika's Hourglass stage.

Some observations
* When starting the emulator and game fresh and do a first battle at the hourglass stage I get around 55 fps.
* Playing some other stages against other opponents - all normal. Solid 60 fps
* Going back to the hourglass stage after a few other battles, the FIFO ramps up to 99.5% and emulator drops down to between 40-50 fps.

Ryujinx Version: 1.1.1032
Operating System: Microsoft Windows 10.0.19044 (X64)
CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz ; 12 logical
RAM: Total 32708 MiB ; Available 21471 MiB
GPU: NVIDIA GeForce GTX 1080 Ti (Vulkan v1.3.242, Driver v536.23.0.0)

**Comment by 995qa** [comment]
retest
