### ISSUE TITLE
INSTANT SPORTS

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1676]
#### Current on `master` : 1.0.4686

Game loads and plays, curiously needing to use the right D-pad button for selection/confirmation to move through menus and in-game.
Crashed after quitting to the main menu.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32 width, Int32 height, Int32 depth, Int32 levels, Int32 layers, Int32 blockWidth, Int32 blockHeight, Int32 bytesPerPixel, Int32 gobBlocksInY, Int32 gobBlocksInZ, Int32 gobBlocksInTileX, SizeInfo sizeInfo, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.Texture\LayoutConverter.cs:line 233
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 479
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 330
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(RtDepthStencilState dsState, Size3D size, Int32 samplesInX, Int32 samplesInY) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 447
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateRenderTargetState(GpuState state, Boolean useControl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 319
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 124
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 118
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 498
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 102
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-06-10 16_29_42-Ryujinx 1 0 4686 - INSTANT SPORTS v1 0 0 (010099700D750000) (64-bit)](https://user-images.githubusercontent.com/62343878/84326097-73a68580-ab39-11ea-8d29-e0014ae1b77d.png)
![2020-06-10 16_30_50-Ryujinx 1 0 4686 - INSTANT SPORTS v1 0 0 (010099700D750000) (64-bit)](https://user-images.githubusercontent.com/62343878/84326102-743f1c00-ab39-11ea-989b-ce45c0c9efe1.png)
![2020-06-10 16_31_09-Ryujinx 1 0 4686 - INSTANT SPORTS v1 0 0 (010099700D750000) (64-bit)](https://user-images.githubusercontent.com/62343878/84326109-76a17600-ab39-11ea-9c3b-4e7cbfc3d57c.png)
![2020-06-10 16_38_21-Ryujinx 1 0 4686 - INSTANT SPORTS v1 0 0 (010099700D750000) (64-bit)](https://user-images.githubusercontent.com/62343878/84326115-7b662a00-ab39-11ea-87ed-422f943273e1.png)
![2020-06-10 16_39_11-Ryujinx 1 0 4686 - INSTANT SPORTS v1 0 0 (010099700D750000) (64-bit)](https://user-images.githubusercontent.com/62343878/84326134-828d3800-ab39-11ea-94d5-b4df8e8d55b1.png)
![2020-06-10 16_39_46-Ryujinx 1 0 4686 - INSTANT SPORTS v1 0 0 (010099700D750000) (64-bit)](https://user-images.githubusercontent.com/62343878/84326144-89b44600-ab39-11ea-907b-d4d9e00ac864.png)

#### Log file :

[IS.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4761639/IS.zip)

**Comment by EmulationFanatic** [comment]
Updated
