### ISSUE TITLE
Arcade Archives VS. GRADIUS

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1678]
#### Current on `master` : 1.0.4686

Crashes after going through initial menu to launch embedded game.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![2020-06-10 16_54_35-Ryujinx 1 0 4686 - Arcade Archives VS  GRADIUS v1 0 0 (01004EC00E634000) (64-bit](https://user-images.githubusercontent.com/62343878/84326915-3e029c00-ab3b-11ea-9382-0f440904a74d.png)
![2020-06-10 16_54_40-Ryujinx 1 0 4686 - Arcade Archives VS  GRADIUS v1 0 0 (01004EC00E634000) (64-bit](https://user-images.githubusercontent.com/62343878/84326916-3f33c900-ab3b-11ea-9533-9d9601f32def.png)

#### Log file :

[AAVSG.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4761653/AAVSG.zip)

**Comment by SeraUX** [comment]
## Arcade Archives VS. GRADIUS

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.5191

Loads to initial menu and then crashes with the error below after trying to start the game.
```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 12

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0036976c nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 34, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<4, 33, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 12l> >, 16ul, 16ul, true>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 34, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<4, 33, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 12l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, unsigned int)
   sdk:0x0036823c Sub0000000009c5c23c
   sdk:0x003671cc Sub0000000009c5b1cc
   main:0x00064620 Sub0000000008068620
   main:0x00024dc8 Sub0000000008028dc8
   main:0x00029c88 Sub000000000802dc88
   main:0x00006204 Sub000000000800a204
   sdk:0x0031d3b8 Sub0000000009c113b8
   sdk:0x00321818 Sub0000000009c15818
   ??? Sub0000000000000000

Buffer Information:
        PtrBuff:
        [0] Position: 0x0000000008fe00b0 Size: 0x0000000000000000
        SendBuff:
        Position: 0x00000011d23dbcfc Size: 0x0000000000000023 Flags: 0
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        Position: 0x0000000008fe00d8 Size: 0x0000000000000400 Flags: 0
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        ReceiveBuff:
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        RecvListBuff:
        Position: 0x0000000008fe04f8 Size: 0x0000000000001000

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0C 00 00 00 00 00 00 00   SFCI············
00000010   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  00 10 00 00 F8 04 FE 08   ············ø·þ·
00000030   00 00 00 10                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Hardware Specs :

##### CPU: i3-7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1233

#### Screenshots :

![23-55-38_18-08-20](https://user-images.githubusercontent.com/62521228/90569575-6a2b4080-e1ae-11ea-9351-9eca3b81dcb1.png)

#### Log file :

[aa-vs-gradius.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5093051/aa-vs-gradius.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
