### ISSUE TITLE
Toki

### ISSUE THREAD

**Issue by zemzema** [Ryujinx/Ryujinx-Games-List#169]
#### Current on `master` :

Build Version : 1.0.2624

```
Last error returned.
Unhandled Exception: System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #12': Pointers cannot reference marshaled structures.  Use ByRef instead.
```
00:00:00.431 | 0001 Loader LoadStaticObjects: Loading image 3 at 0x000000000b7d6000...
00:00:00.520 | 0001 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #12': Pointers cannot reference marshaled structures.  Use ByRef instead.
   at OpenTK.Platform.X11.Functions.XCreateWindow(IntPtr display, IntPtr parent, Int32 x, Int32 y, Int32 width, Int32 height, Int32 border_width, Int32 depth, Int32 xclass, IntPtr visual, IntPtr valuemask, XSetWindowAttributes* attributes)
   at OpenTK.Platform.X11.X11GLNative..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device)
   at OpenTK.Platform.X11.X11Factory.CreateNativeWindow(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device)
   at OpenTK.NativeWindow..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device)
   at OpenTK.NativeWindow..ctor(Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device)
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext, Boolean isSingleThreaded)
   at Ryujinx.GlScreen..ctor(Switch device, IGalRenderer renderer) in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 51
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 91

Unhandled Exception: System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #12': Pointers cannot reference marshaled structures.  Use ByRef instead.
   at OpenTK.Platform.X11.Functions.XCreateWindow(IntPtr display, IntPtr parent, Int32 x, Int32 y, Int32 width, Int32 height, Int32 border_width, Int32 depth, Int32 xclass, IntPtr visual, IntPtr valuemask, XSetWindowAttributes* attributes)
   at OpenTK.Platform.X11.X11GLNative..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device)
   at OpenTK.Platform.X11.X11Factory.CreateNativeWindow(Int32 x, Int32 y, Int32 width, Int32 height, String title, GraphicsMode mode, GameWindowFlags options, DisplayDevice device)
   at OpenTK.NativeWindow..ctor(Int32 x, Int32 y, Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device)
   at OpenTK.NativeWindow..ctor(Int32 width, Int32 height, String title, GameWindowFlags options, GraphicsMode mode, DisplayDevice device)
   at OpenTK.GameWindow..ctor(Int32 width, Int32 height, GraphicsMode mode, String title, GameWindowFlags options, DisplayDevice device, Int32 major, Int32 minor, GraphicsContextFlags flags, IGraphicsContext sharedContext, Boolean isSingleThreaded)
   at Ryujinx.GlScreen..ctor(Switch device, IGalRenderer renderer) in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 51
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 91

**Comment by HorrorTroll** [comment]
Closed! This issue from OpenTK/Linux
