### ISSUE TITLE
Resolutiion

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1690]
#### Current on `master` : 1.0.4686

Game crashes before going to the main menu.

```
00:02:55.553 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 423
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 268
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 97
```

#### Log file :

[resolutiion.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4763987/resolutiion.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6850
