### ISSUE TITLE
Arcade Archives PLUS ALPHA

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1694]
#### Current on `master` : 1.0.4686

Game boots to the menu, but crashes when you try to go ingame.

```
00:00:40.426 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IRequest: 21

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00288ec8 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail:
:CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::BufferArgumentInf
o<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> >, 4ul, 12ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail:
:OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessi
onManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>
, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, unsigned int)
   sdk:0x002886c4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::nifm::detail::IRequest, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::
sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::nifm::detail::IRequest, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_GetAppletInfo(nn::sf::O
ut<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::sf::OutBuffer const&, unsigned int)
   sdk:0x00286478 nn::nifm::detail::RequestClient::PrepareLibraryApplet(nn::applet::LibraryAppletHandle*)
   sdk:0x0028be74 nn::nifm::PrepareHandlingNetworkRequestResult(nn::nifm::RequestHandle, nn::applet::LibraryAppletHandle*)
   sdk:0x0028de38 nn::nifm::NetworkConnection::HandleNetworkRequestErrorResult()
   sdk:0x0028c634 nn::nifm::HandleNetworkRequestErrorResult()
   main:0x00009894 Sub000000000800d894
   main:0x00009804 Sub000000000800d804
   sdk:0x000cfb48 Sub000000000a150b48
   sdk:0x000d4314 Sub000000000a155314
   ??? Sub0000000000000000

Buffer Information:
        ReceiveBuff:
        Position: 0x0000001193dbad9c Size: 0x0000000000001000 Flags: 0

Raw Request Data:
00000000   01 00 14 00 03 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  15 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 80 00 00  00 00 01 00 00 00 03 00   ···············
00000030   00 00 03 00                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/671

#### Screenshots :

![06_11_34-20:34:37](https://user-images.githubusercontent.com/62521228/84426330-51893200-ac23-11ea-936a-334c1ddbfc24.png)

#### Log file :

[AA-PA.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4766670/AA-PA.log)

**Comment by SeraUX** [comment]
## Arcade Archives PLUS ALPHA

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.4829

Game works good, but audio can get messed up and start repeating a sound until you stop emulation.

#### Hardware Specs :

##### CPU: i3 7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti
##### RAM: 8GB

#### Screenshots :

![07_04_33-22:33:39](https://user-images.githubusercontent.com/62521228/86520663-64b8a780-be47-11ea-811b-0d401c801af4.png)
![07_04_33-22:33:40](https://user-images.githubusercontent.com/62521228/86520665-65513e00-be47-11ea-8e9e-2a6b8de913b4.png)
![07_04_34-22:34:35](https://user-images.githubusercontent.com/62521228/86520666-65e9d480-be47-11ea-8b4b-4a4542bf4c1a.png)
![07_04_34-22:34:47](https://user-images.githubusercontent.com/62521228/86520667-66826b00-be47-11ea-84b3-5d225814f50f.png)
![07_04_34-22:34:53](https://user-images.githubusercontent.com/62521228/86520669-671b0180-be47-11ea-90fc-32db03850bd5.png)
![07_04_34-22:34:57](https://user-images.githubusercontent.com/62521228/86520671-684c2e80-be47-11ea-9c6b-c4d931661e20.png)
![07_04_35-22:35:23](https://user-images.githubusercontent.com/62521228/86520673-68e4c500-be47-11ea-8e04-62ca8badbd4a.png)
![07_04_35-22:35:26](https://user-images.githubusercontent.com/62521228/86520676-697d5b80-be47-11ea-9eca-68a34b35205a.png)
![07_04_35-22:35:33](https://user-images.githubusercontent.com/62521228/86520678-6aae8880-be47-11ea-811a-b37f89e138ce.png)
![07_04_37-22:37:26](https://user-images.githubusercontent.com/62521228/86520680-6b471f00-be47-11ea-8358-38799d7774d0.png)
![07_04_37-22:37:43](https://user-images.githubusercontent.com/62521228/86520681-6bdfb580-be47-11ea-811f-6f65869fb21c.png)


#### Log file :

[aa-plus-alpha.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4873816/aa-plus-alpha.zip)

**Comment by EmulationFanatic** [comment]
Updated
