### ISSUE TITLE
Cytus α

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#170]
#### Current on `master` :

* Build Version : 1.0.2624

```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.ISelfController: 91
```

Implement that, and then crash:
```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Time.IStaticService: 20
```

Implement that, and then crash:
```
CurrentDomain_UnhandledException: Unhandled exception caught: System.NotImplementedException: c004481d (NvHostChannelIoctl)
   at Ryujinx.HLE.HOS.Services.Nv.NvHostChannel.NvHostChannelIoctl.ProcessIoctl(ServiceCtx context, Int32 cmd) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.HLE\HOS\Services\Nv\NvHostChannel\NvHostChannelIoctl.cs:line 42
```

Implement that, and then crash:
```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Acc.IAccountService: 140
```

Implement that, and then crash:
```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Acc.IAccountService: 150
```

```
CurrentDomain_UnhandledException: Unhandled exception caught: System.NotImplementedException: 40040007 (NvHostChannelIoctl)
   at Ryujinx.HLE.HOS.Services.Nv.NvHostChannel.NvHostChannelIoctl.ProcessIoctl(ServiceCtx context, Int32 cmd) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.HLE\HOS\Services\Nv\NvHostChannel\NvHostChannelIoctl.cs:line 42
```

#### Pull requests needed :

https://github.com/Ryujinx/Ryujinx/pull/672

#### Screenshots :
![image](https://user-images.githubusercontent.com/24840279/57018562-41480a80-6c4e-11e9-8fa4-2d55e7144d9e.png)
![image](https://user-images.githubusercontent.com/24840279/57018674-96841c00-6c4e-11e9-8599-0832fe707796.png)
![image](https://user-images.githubusercontent.com/24840279/57018725-b9aecb80-6c4e-11e9-8cc4-a1d4465deaea.png)
![image](https://user-images.githubusercontent.com/24840279/57018751-ca5f4180-6c4e-11e9-9403-431866bfeb21.png)
![image](https://user-images.githubusercontent.com/24840279/57018817-fb3f7680-6c4e-11e9-89bf-36fe1852ea4f.png)
![image](https://user-images.githubusercontent.com/24840279/57018909-45285c80-6c4f-11e9-9179-d806ae14929e.png)
![image](https://user-images.githubusercontent.com/24840279/57018926-55403c00-6c4f-11e9-9fc3-1df073cbab6a.png)
![image](https://user-images.githubusercontent.com/24840279/57019009-7acd4580-6c4f-11e9-9a7d-06f837ee3e87.png)
![image](https://user-images.githubusercontent.com/24840279/57019024-8a4c8e80-6c4f-11e9-8ec5-11cc359cc86c.png)
![image](https://user-images.githubusercontent.com/24840279/57019112-b23bf200-6c4f-11e9-8020-0a027dde0ca2.png)
![image](https://user-images.githubusercontent.com/24840279/57019122-b9630000-6c4f-11e9-846d-1cb3d99064b3.png)
![image](https://user-images.githubusercontent.com/24840279/57019132-c54ec200-6c4f-11e9-9c95-d060a18a2998.png)
![image](https://user-images.githubusercontent.com/24840279/57019191-f6c78d80-6c4f-11e9-847b-e1a03c2941a5.png)

#### Outstanding Issues:
- https://github.com/Ryujinx/Ryujinx/issues/615
- https://github.com/Ryujinx/Ryujinx/issues/616
- https://github.com/Ryujinx/Ryujinx/issues/666
- https://github.com/Ryujinx/Ryujinx/issues/667
- https://github.com/Ryujinx/Ryujinx/issues/668
- https://github.com/Ryujinx/Ryujinx/issues/678

**Comment by B3astTech** [comment]
Need's a Update

**Comment by GoffyDude** [comment]
## Cytus α

#### Current on `master` : 1.0.4593

Has nvdec cutscene issue just before each level starts.
Otherwise it is playable. There is a small graphical bug preventing the silkscreened background from showing in each level; instead there is just a solid gray color.

#### Screenshots :

![2020-05-23 03_52_59-Ryujinx 1 0 4593 - Cytus α v1 0 1 (010063100B2C2000) (64-bit)](https://user-images.githubusercontent.com/62343878/82727929-bb5c8e80-9caa-11ea-938b-0dae0c742d4f.png)
![2020-05-23 03_53_20-Ryujinx 1 0 4593 - Cytus α v1 0 1 (010063100B2C2000) (64-bit)](https://user-images.githubusercontent.com/62343878/82727932-c0214280-9caa-11ea-9582-333dd4efe935.png)
![2020-05-23 03_53_44-Ryujinx 1 0 4593 - Cytus α v1 0 1 (010063100B2C2000) (64-bit)](https://user-images.githubusercontent.com/62343878/82727933-c2839c80-9caa-11ea-9129-19017edc952d.png)
![2020-05-23 03_53_56-Ryujinx 1 0 4593 - Cytus α v1 0 1 (010063100B2C2000) (64-bit)](https://user-images.githubusercontent.com/62343878/82727936-c6172380-9caa-11ea-94db-2510378a98c9.png)
![2020-05-23 03_59_01-Ryujinx 1 0 4593 - Cytus α v1 0 1 (010063100B2C2000) (64-bit)](https://user-images.githubusercontent.com/62343878/82727938-cfa08b80-9caa-11ea-832d-294a637e583f.png)
![2020-05-23 04_00_55-Ryujinx 1 0 4593 - Cytus α v1 0 1 (010063100B2C2000) (64-bit)](https://user-images.githubusercontent.com/62343878/82727939-d0392200-9caa-11ea-847d-d5c435403336.png)
![2020-05-23 04_01_06-Ryujinx 1 0 4593 - Cytus α v1 0 1 (010063100B2C2000) (64-bit)](https://user-images.githubusercontent.com/62343878/82727943-d0d1b880-9caa-11ea-8848-7629d59ffaf4.png)
![2020-05-23 04_02_29-Ryujinx 1 0 4593 - Cytus α v1 0 1 (010063100B2C2000) (64-bit)](https://user-images.githubusercontent.com/62343878/82727947-d5966c80-9caa-11ea-8198-8c5ca8eb241c.png)
![2020-05-23 04_04_03-Ryujinx 1 0 4593 - Cytus α v1 0 1 (010063100B2C2000) (64-bit)](https://user-images.githubusercontent.com/62343878/82727953-e0510180-9caa-11ea-9b6c-c28fa72ba88c.png)
![2020-05-23 04_04_26-Ryujinx 1 0 4593 - Cytus α v1 0 1 (010063100B2C2000) (64-bit)](https://user-images.githubusercontent.com/62343878/82727955-e21ac500-9caa-11ea-8928-74a9a402dbe7.png)


#### Log file :

[Cytus.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4671527/Cytus.zip)

**Comment by GoffyDude** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
