### ISSUE TITLE
Nurse Love Syndrome

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1714]
#### Current on `master` : 1.0.4686

Game loads, plays at low fps and crashes with an missing opcode error mid gameplay. 

```
00:02:32.911 | HLE.HostThread.16 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000299673f0 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
```
#### Screenshots :

![06_12_51-18:51:29](https://user-images.githubusercontent.com/62521228/84528705-74c5e700-ace0-11ea-9e7f-c936724fca6b.png)
![06_12_52-18:52:40](https://user-images.githubusercontent.com/62521228/84528722-7c858b80-ace0-11ea-92dc-7654a48edfbe.png)
![06_12_53-18:53:02](https://user-images.githubusercontent.com/62521228/84528743-83ac9980-ace0-11ea-9b44-72ab109319b8.png)
![06_12_54-18:54:10](https://user-images.githubusercontent.com/62521228/84528759-8b6c3e00-ace0-11ea-81fb-12e53519afd8.png)
![06_12_54-18:54:22](https://user-images.githubusercontent.com/62521228/84528769-8effc500-ace0-11ea-985d-4f6b67e08ef1.png)

#### Log file :

[nurse-love-syndrome.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4772233/nurse-love-syndrome.log)

**Comment by EmulationFanatic** [comment]
Updated
