### ISSUE TITLE
GRID Autosport

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1736]
#### Current on `master` : 1.0.4697

Crashes on launch.

```
HLE.HostThread.0 KernelSvc Break: Debugger triggered.
00:00:06.570 | HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x004c7380 Sub000000000c14f380
   sdk:0x004c9fb0 __cxa_get_exception_ptr
   sdk:0x004c9f1c Sub000000000c151f1c
   main:0x004e31f0 Sub00000000084e71f0
   main:0x004ec640 Sub00000000084f0640
   main:0x0053b61c Sub000000000853f61c
   main:0x0050bd58 Sub000000000850fd58
   main:0x00000154 Sub0000000008004154
   rtld:0x000007e4 Sub00000000080007e4
   sdk:0x0029da28 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:00:06.582 | HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x00519c10 __nnmusl_GetTlsValue
   sdk:0x004cbd84 Sub000000000c153d84
   sdk:0x004b1f88 Sub000000000c139f88
   sdk:0x004c7380 Sub000000000c14f380
   sdk:0x004c9fb0 __cxa_get_exception_ptr
   sdk:0x004c9f1c Sub000000000c151f1c
   main:0x004e31f0 Sub00000000084e71f0
   main:0x004ec640 Sub00000000084f0640
   main:0x0053b61c Sub000000000853f61c
   main:0x0050bd58 Sub000000000850fd58
   main:0x00000154 Sub0000000008004154
   rtld:0x000007e4 Sub00000000080007e4
   sdk:0x0029da28 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:00:06.584 | HLE.HostThread.2 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:00:06.797 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1154
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 47
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 129
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 98
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[GA.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4783476/GA.zip)

**Comment by benderscruffy** [comment]
same issue using 1.0.7106

**Comment by EmulationFanatic** [comment]
Updated

**Comment by LeRutY** [comment]
It´s not possible to access the "change controls" menu, it just goes back to the main controls menu

**Comment by LeRutY** [comment]
"Help" is also affected. Opened a github issue on the main ryujinx page https://github.com/Ryujinx/Ryujinx/issues/4502
