### ISSUE TITLE
Remi Lore

### ISSUE THREAD

**Issue by zemzema** [Ryujinx/Ryujinx-Games-List#174]
#### Current on `master` :

* Build Version : * 1.0.2651

*Describe the current game state here.*
Game crash on boot.
```
Last error returned.
at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 86
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 37
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 140
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Log file :

* [Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/3234213/Ryujinx.log)

**Comment by AcK77** [comment]
Need an update.

**Comment by EmulationFanatic** [comment]
## RemiLore

#### Current on `master` : 1.0.4675

Game takes roughly 8 minutes to load to title screen and then deadlocks.

#### Screenshots :

![2020-06-04 06_58_03-Ryujinx 1 0 4675 - RemiLore v1 0 0 (010095900B436000) (64-bit)](https://user-images.githubusercontent.com/62343878/83760726-9402ab80-a632-11ea-8dc0-c6e0acaa05e1.png)
![2020-06-04 07_09_50-Ryujinx 1 0 4675 - RemiLore v1 0 0 (010095900B436000) (64-bit)](https://user-images.githubusercontent.com/62343878/83760728-949b4200-a632-11ea-9aef-16e1be14a1c7.png)


#### Log file :

[RemiLore.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4730204/RemiLore.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
