### ISSUE TITLE
Overpass

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1746]
#### Current on `master` : 1.0.4697

Takes 4 minutes to load to title screen, and then crashes when trying to race.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: You must call the Bind method before performing this operation.
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient.RecvFrom(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Sockets\Bsd\IClient.cs:line 529
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Screenshots :

![2020-06-16 05_18_32-Ryujinx 1 0 4697 - Overpass v1 0 0 (01008EA00E816000) (64-bit)](https://user-images.githubusercontent.com/62343878/84769222-b7aee580-af92-11ea-979b-57ddc5713bfe.png)
![2020-06-16 05_18_39-Ryujinx 1 0 4697 - Overpass v1 0 0 (01008EA00E816000) (64-bit)](https://user-images.githubusercontent.com/62343878/84769223-b8477c00-af92-11ea-96c3-ca66d8c7fd67.png)
![2020-06-16 05_19_38-Ryujinx 1 0 4697 - Overpass v1 0 0 (01008EA00E816000) (64-bit)](https://user-images.githubusercontent.com/62343878/84769224-b8e01280-af92-11ea-8ff0-06a2b973a177.png)
![2020-06-16 05_22_07-Ryujinx 1 0 4697 - Overpass v1 0 0 (01008EA00E816000) (64-bit)](https://user-images.githubusercontent.com/62343878/84769225-b8e01280-af92-11ea-81a6-5db6cf75fd0c.png)
![2020-06-16 05_22_22-Ryujinx 1 0 4697 - Overpass v1 0 0 (01008EA00E816000) (64-bit)](https://user-images.githubusercontent.com/62343878/84769243-c1384d80-af92-11ea-97bb-f84d28b26dfa.png)

#### Log file :

[Overpass.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4786281/Overpass.zip)

**Comment by EmulationFanatic** [comment]
Same status in 1.0.6769

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6895

**Comment by benderscruffy** [comment]
same status on 1.0.7097
00:03:49.460 |E| HLE.OsThread.5 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: You must call the Bind method before performing this operation.
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient.RecvFrom(ServiceCtx context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[Ryujinx_1.0.7098_2021-11-05_18-43-18.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7482504/Ryujinx_1.0.7098_2021-11-05_18-43-18.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
