### ISSUE TITLE
Skyhill

### ISSUE THREAD

**Issue by zemzema** [Ryujinx/Ryujinx-Games-List#175]
#### Current on `master` :

* Build Version : * 1.0.2651

Game crash on boot.
```
Last error returned.
at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 86
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 37
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 140
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Log file :

* [Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/3234235/Ryujinx.log)

**Comment by AcK77** [comment]
Need an update.

**Comment by AcK77** [comment]
Updated.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
