### ISSUE TITLE
Atelier Shallie: Alchemists of the Dusk Sea DX

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1756]
#### Current on `master` : 1.0.4697

Game boots to the menu, has nvdec cutscenes and crashes with an missing service error during the cutscene when you start a new game.

```
00:04:24.434 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Audio.AudioOutManager.IAudioOut: 10

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0006cc9c nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 0l> >, 0ul, 8ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 0l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<8ul, 8ul>, unsigned int)
   sdk:0x00095464 Sub00000000096c4464
   sdk:0x0009a320 nn::audio::GetAudioOutPlayedSampleCount(nn::audio::AudioOut const*)
   main:0x0052a054 Sub000000000852e054
   main:0x00529f1c Sub000000000852df1c
   sdk:0x003344b8 Sub00000000099634b8
   sdk:0x00338984 Sub0000000009967984
   ??? Sub0000000000000000

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0A 00 00 00 00 00 00 00   SFCI············
00000010   00 00 00 00 00 00 00 00  07 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


```

#### Screenshots :

![06_16_17-16:17:31](https://user-images.githubusercontent.com/62521228/84786909-a2b37000-afed-11ea-9b63-f5efee80a6fe.png)
![06_16_18-16:18:22](https://user-images.githubusercontent.com/62521228/84786914-a515ca00-afed-11ea-9fe4-18eed2d6bc93.png)

#### Log file :

[Atelier-Shallie.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4787083/Atelier-Shallie.log)

**Comment by SeraUQ** [comment]
Updated
