### ISSUE TITLE
Valkyria Chronicles 4

### ISSUE THREAD

**Issue by zemzema** [Ryujinx/Ryujinx-Games-List#176]
#### Current on `master` :

* Build Version : * 1.0.2651

Game crash on boot.
```
Last error returned.
 at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 86
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 37
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 140
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Log file :

* [Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/3234254/Ryujinx.log)

**Comment by AcK77** [comment]
Need an update.

**Comment by GoffyDude** [comment]
## Valkyria Chronicles 4

#### Current on `master` : 1.0.4444

- Loads to intro splash screens, where there are a pair of black screen cutscenes (nvdec) that can be skipped with the A button.
- Once a new game is started, there are several unskippable black screen cutscenes. Audio can be heard clearly, and once it ends, the subtitles catch up over the next several minutes.
- In-game FPS is low, sometimes extremely low. There are also some major graphical anomalies like blue character/overlay colors and grass artifacts, but the game can be played through.

#### Screenshots :

![2020-05-03 13_53_05-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80924942-62ec3e00-8d49-11ea-9b34-bb1a845ee65f.png)
![2020-05-03 13_54_21-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80924945-64b60180-8d49-11ea-8dd3-85e0f0c447a1.png)
![2020-05-03 13_55_04-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80924946-67b0f200-8d49-11ea-970f-10e04e5210e5.png)
![2020-05-03 14_04_51-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80924947-68498880-8d49-11ea-9c53-faf7ad897c5e.png)
![2020-05-03 14_05_21-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80924953-739cb400-8d49-11ea-9316-3afcee282e97.png)
![2020-05-03 14_06_14-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80924964-7e574900-8d49-11ea-956b-ce9d24baaef7.png)
![2020-05-03 14_06_31-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80924984-89aa7480-8d49-11ea-90aa-fb6baa804118.png)
![2020-05-03 14_07_24-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80924991-95963680-8d49-11ea-81c6-fbdf9aa59aa5.png)
![2020-05-03 14_08_15-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80924997-a0e96200-8d49-11ea-9aea-7c645364979e.png)
![2020-05-03 14_10_31-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80925009-acd52400-8d49-11ea-9aa1-a0784ce86114.png)
![2020-05-03 14_12_43-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80925017-b8c0e600-8d49-11ea-8e69-51b647c02d1b.png)
![2020-05-03 14_13_38-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80925021-c6766b80-8d49-11ea-9a38-fe8cd7ee9105.png)
![2020-05-03 14_15_49-Ryujinx 1 0 4444 - Valkyria Chronicles 4 v1 0 0 (01005C600AC68000) (64-bit)](https://user-images.githubusercontent.com/62343878/80925027-cf673d00-8d49-11ea-9458-b2f9a1a0f991.png)


#### Log file :

[VC4.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4571531/VC4.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
