### ISSUE TITLE
Genkai Tokki Moero Crystal H

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1769]
#### Current on `master` : 1.0.4709

Game crashes with an missing opcode error.
```
00:00:14.963 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000037e89e8 (opcode 0xf3fc2170) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
```

#### Log file :

[moero.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4792122/moero.log)

**Comment by SeraUX** [comment]
## Genkai Tokki Moero Crystal H

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.5171

same as https://github.com/Ryujinx/Ryujinx-Games-List/issues/182 the game only displays a black screen without responding to anything

#### Hardware Specs : 

##### CPU: i3-7300
##### GPU:  NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Log file :

[GTMCH.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5069788/GTMCH.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by benderscruffy** [comment]
using 1.1.16
still the same problem

**Comment by gdkchan** [comment]
Needs an update.

**Comment by SilverBeamx** [comment]
The game is playable, altough graphics are not rendering in the 3D sections of the game (ie. Dungeons). Only the 2D Sprite elements rendered on top of it are present. Moreover, performance is also poor (15-20 fps), which further plummets to around 2-3 fps depending on where the player is looking in the (blank) 3D environment. Here's a screenshot of the issue:
![moeroBug](https://user-images.githubusercontent.com/44263986/171993764-07085aae-7bbd-47b1-a100-1d1d671938bd.png)

And here is the save near the affected area:
[MoeroSave.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/8837391/MoeroSave.zip)

**Comment by gdkchan** [comment]
I will update the main post  once you provide an updated report, since this issue should be already fixed. Thank you.

**Comment by SilverBeamx** [comment]
All the graphical issues seem to be fixed as of 1.1.142

Played a bit and everything seems to be behaving correctly, although this game appears to be unbelievably heavy on the emulator, showing poor performance compared to other more "graphically intensive" games. (Everything cited here is of course relative to my machine)

**Comment by MetrosexualGarbodor** [comment]
Updated the tags but it would be really nice if someone could provide a more detailed report.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by SilverBeamx** [comment]
The info seems to be incorrect. I have just tested this in 1.1.299 and can confirm that the slowdowns are not Vulkan specific. FIFO is at 99% during dungeons either with OGL or Vulkan.

**Comment by SilverBeamx** [comment]
On my system with an 8600k and a 1060 6G, dungeon performance varies wildly. It shows lows of 20 and highs of 45 fps. Performance seem to be affected by what the camera is looking at, albeit a bit randomly. Sometimes it is smooth whilst looking down long corridors, while other times it grinds to a halt whilst looking to a wall. Altough, it generally performs better when the player is directly looking at a wall annd there isn't an open room/walls with holes in sight.

**Comment by EmulationFanatic** [comment]
> The info seems to be incorrect. I have just tested this in 1.1.299 and can confirm that the slowdowns are not Vulkan specific. FIFO is at 99% during dungeons either with OGL or Vulkan.

I didn't have any noticeable slowdowns on OpenGL.

**Comment by EmulationFanatic** [comment]
> On my system with an 8600k and a 1060 6G, dungeon performance varies wildly. It shows lows of 20 and highs of 45 fps. Performance seem to be affected by what the camera is looking at, albeit a bit randomly. Sometimes it is smooth whilst looking down long corridors, while other times it grinds to a halt whilst looking to a wall. Altough, it generally performs better when the player is directly looking at a wall and there isn't an open room/wall with holes in sight. On the contrary to what was reported, i happen to get stabler and more consist performance in Vulkan, but it might just be my bias speaking.

Here's a recording of OpenGL gameplay, with the FPS pegged at 60 the whole time. As you can see, FIFO peaks for a split second around halfway through the video in the low 60% range, but averages somewhere around 20%.

https://youtu.be/WTcylXy6X2g

**Comment by BonryuX** [comment]
Were the touch controls tested? Currently my mouse clicks do not translate to taps on vulkan or OGL.
