### ISSUE TITLE
Crystal Crisis

### ISSUE THREAD

**Issue by zemzema** [Ryujinx/Ryujinx-Games-List#177]
#### Current on `master` :

* Build Version : * 1.0.2651

Game crash on boot.
```
Last error returned.
 at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 86
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 37
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 140
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

#### Log file :

* [Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/3234363/Ryujinx.log)

**Comment by AcK77** [comment]
Need an update.

**Comment by GoffyDude** [comment]
## Crystal Crisis

#### Current on `master` : 1.0.4609

Has nvdec issue on intro. This can be skipped.
Crashes randomly either on launch or while navigating menus, with a memory access violation error.

#### Screenshots :

![2020-05-23 04_32_20-Ryujinx 1 0 4609 - Crystal Crisis v1 0 (0100972008234000) (64-bit)](https://user-images.githubusercontent.com/62343878/82728868-70457a00-9cb0-11ea-8d98-e93113cf2d66.png)
![2020-05-23 04_32_39-Ryujinx 1 0 4609 - Crystal Crisis v1 0 (0100972008234000) (64-bit)](https://user-images.githubusercontent.com/62343878/82728872-74719780-9cb0-11ea-8116-bf1ba6e308ec.png)
![2020-05-23 04_32_50-](https://user-images.githubusercontent.com/62343878/82728873-75a2c480-9cb0-11ea-8151-b7f883517639.png)


#### Log file :

[CC.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4671601/CC.zip)

**Comment by GoffyDude** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
