### ISSUE TITLE
Modern Combat Blackout

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1770]
#### Current on `master` : 1.0.4709

Crashes on launch.

```
mulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 128
   at Ryujinx.Cpu.MemoryManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 119
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient.WriteSockAddr(ServiceCtx context, Int64 bufferPosition, IPEndPoint endPoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Sockets\Bsd\IClient.cs:line 216
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient.WriteSockAddr(ServiceCtx context, Int64 bufferPosition, BsdSocket socket, Boolean isRemote) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Sockets\Bsd\IClient.cs:line 226
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient.Accept(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Sockets\Bsd\IClient.cs:line 675
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

#### Log file :

[MCB.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4792269/MCB.zip)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6807
