### ISSUE TITLE
Forager

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1771]
#### Current on `master` : 1.0.4709

Game has inverted graphics
trying to get ingame results in a crash.

```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyBuffer(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyBuffer.cs:line 64
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```
#### Screenshots :

![06_17_02-14:02:54](https://user-images.githubusercontent.com/62521228/84896372-23cd3e80-b0a4-11ea-802d-21615d68a5b2.png)
![06_17_03-14:03:59](https://user-images.githubusercontent.com/62521228/84896374-23cd3e80-b0a4-11ea-98dc-eebbef259436.png)
![06_17_04-14:04:09](https://user-images.githubusercontent.com/62521228/84896375-2465d500-b0a4-11ea-8e7e-ba2d2802a61c.png)

#### Log file :
[forager.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4792351/forager.zip)

**Comment by LukeWarnut** [comment]
## Forager

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.6575

Game now renders correctly, but crashes when trying to go in-game.

```
00:02:29.455 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 292
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 267
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyBuffer(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyBuffer.cs:line 109
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 436
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs : 

##### CPU: *(e.g. i7-6700)*
##### GPU: *(e.g. NVIDIA RTX 2070)*
##### RAM: *(e.g. 16GB)*

#### Screenshots :

![image](https://user-images.githubusercontent.com/65521430/107999042-7f91f380-6fb4-11eb-9c36-de9266785b34.png)
![image](https://user-images.githubusercontent.com/65521430/107999047-84ef3e00-6fb4-11eb-8a5f-be57c4f6ead7.png)
![image](https://user-images.githubusercontent.com/65521430/107999055-8a4c8880-6fb4-11eb-92b5-61b14ea56949.png)

#### Log file :

[Forager.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5984417/Forager.log)

**Comment by EmulationFanatic** [comment]
Updated, thanks!

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6895

**Comment by benderscruffy** [comment]
change the status please
