### ISSUE TITLE
SYNAPTIC DRIVE

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1779]
#### Current on `master` : 1.0.4728

Crashes after pressing A at title screen.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IRequest: 21
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/671

#### Screenshots :
![2020-06-19 07_08_27-Ryujinx 1 0 4728 - SYNAPTIC DRIVE v1 0 0 (0100D8400DAF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/85135804-ef6c9600-b1fb-11ea-83b2-55ef0eafd782.png)
![2020-06-19 07_08_50-Ryujinx 1 0 4728 - SYNAPTIC DRIVE v1 0 0 (0100D8400DAF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/85135806-f0052c80-b1fb-11ea-879d-9517be5b5260.png)
![2020-06-19 07_09_03-Ryujinx 1 0 4728 - SYNAPTIC DRIVE v1 0 0 (0100D8400DAF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/85135809-f09dc300-b1fb-11ea-8127-01beae678c7e.png)

#### Log file :

[SD.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4804740/SD.zip)

**Comment by SeraUX** [comment]
## SYNAPTIC DRIVE

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.4829

Crashes with an missing service error after trying to move past the title screen.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0006a210 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> > >::ProcessWithOutObjects(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*)
   sdk:0x0010bf84 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::baas::IManagerBase, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::baas::IManagerForApplication, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_EnsureIdTokenCacheAsync(nn::sf::Out<nn::sf::SharedPointer<nn::account::detail::IAsyncContext>, void>)
   sdk:0x001173b8 nn::account::EnsureNetworkServiceAccountIdTokenCacheAsync(nn::account::AsyncContext*, nn::account::UserHandle const&)
   main:0x02dde248 Sub000000000ade2248
   main:0x0164a000 Sub000000000964e000
   main:0x01d4170c Sub0000000009d4570c
   main:0x01d8ca44 Sub0000000009d90a44
   main:0x01d8f01c Sub0000000009d9301c
   main:0x012f6218 Sub00000000092fa218
   main:0x000d9a6c Sub00000000080dda6c
   main:0x01b2434c Sub0000000009b2834c
   main:0x01f232b4 Sub0000000009f272b4
   main:0x01f17648 Sub0000000009f1b648
   main:0x023d45d4 Sub000000000a3d85d4
   main:0x023d4154 Sub000000000a3d8154
   main:0x023d4ce8 Sub000000000a3d8ce8
   main:0x023d7450 Sub000000000a3db450
   main:0x01e12e34 Sub0000000009e16e34
   main:0x012f6218 Sub00000000092fa218
   main:0x000d9a6c Sub00000000080dda6c
   main:0x01b2434c Sub0000000009b2834c
   main:0x01f232b4 Sub0000000009f272b4
   main:0x01f17648 Sub0000000009f1b648
   main:0x023d45d4 Sub000000000a3d85d4
   main:0x023d4154 Sub000000000a3d8154
   main:0x023d41f8 Sub000000000a3d81f8
   main:0x020d2ec0 Sub000000000a0d6ec0
   main:0x01f9a018 Sub0000000009f9e018
   main:0x01f9a04c Sub0000000009f9e04c
   main:0x01f9a2f4 Sub0000000009f9e2f4
   main:0x01f1292c nnMain
   sdk:0x0009857c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  02 00 00 00 00 00 00 00   SFCI············
00000020   01 00 00 00 00 00 00 00  00 80 68 0E 00 00 04 00   ·········h·····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Hardware Specs :

##### CPU: i3 7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti
##### RAM: 8GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![07_04_53-23:53:50](https://user-images.githubusercontent.com/62521228/86521510-0ba24100-be52-11ea-82ba-745fa6da5d33.png)
![07_04_54-23:54:14](https://user-images.githubusercontent.com/62521228/86521512-0cd36e00-be52-11ea-9926-a795b9e39dfc.png)
![07_04_54-23:54:32](https://user-images.githubusercontent.com/62521228/86521513-0d6c0480-be52-11ea-9886-0fcfbc5ccbae.png)
![07_04_54-23:54:35](https://user-images.githubusercontent.com/62521228/86521514-0e9d3180-be52-11ea-8ba9-fcc07cff6deb.png)

#### Log file :

[synaptic-drive.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4874000/synaptic-drive.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
