### ISSUE TITLE
XCOM 2 Collection

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1780]
#### Current on `master` : 1.0.4728

Crashes on launch.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IAccountServiceForApplication: 131
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1267

#### Log file :

[XC2C.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4804763/XC2C.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6807

**Comment by benderscruffy** [comment]
same status on 1.0.7096

**Comment by KuznetsovVN** [comment]
same status on 1.0.7116

**Comment by meisiek** [comment]
I've got more luck with XCOM 2 Version 1.03. It goes into the menu and I can start a new game. But it crashes with an undefined opcode exception after the intro video:

`00:04:24.540 |E| HLE.GuestThread.17 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000090b75e0 (opcode 0x4e21b804) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1083
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1052
`

**Comment by gdkchan** [comment]
Open an issue on https://github.com/Ryujinx/Ryujinx/issues for the missing instruction.

**Comment by meisiek** [comment]
Ok.

**Comment by meisiek** [comment]
I don't think it's really a missing instruction. If I enter 4e21b804 into https://armconverter.com/?disasm, it gives the following result for ARM64:
.BYTE 0x4e, 0x21, 0xb8, 0x04

[Ryujinx_1.0.7116_2021-12-06_12-22-16 - Kopie.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7660426/Ryujinx_1.0.7116_2021-12-06_12-22-16.-.Kopie.log)

**Comment by gdkchan** [comment]
`04 b8 21 4e` -> `fcvtms v4.4s, v0.4s`

**Comment by meisiek** [comment]
Oh, the order is reversed. It seems I have much to learn...
I'll open the issue.

**Comment by meisiek** [comment]
Will be fixed after PR https://github.com/Ryujinx/Ryujinx/pull/2937 gets merged:

![grafik](https://user-images.githubusercontent.com/24993330/147408110-6501641a-1d50-4d4f-8d3b-c637d3b44d6d.png)
![grafik](https://user-images.githubusercontent.com/24993330/147408124-746f583c-ad08-45e5-8c7e-6db36a815d5e.png)
![grafik](https://user-images.githubusercontent.com/24993330/147408135-623aae50-29bb-41bc-9ccb-1d9cc614d32e.png)
![grafik](https://user-images.githubusercontent.com/24993330/147408060-5a56cf71-f567-41e9-865c-153f499c3c49.png)
![grafik](https://user-images.githubusercontent.com/24993330/147408071-fe2289dc-9fe6-48bb-b80b-4e1c9db5404f.png)
![grafik](https://user-images.githubusercontent.com/24993330/147408092-07196412-8864-453b-bc72-772ef4c35c34.png)

**Comment by meisiek** [comment]
"War of the chosen" doesn't start. Could be something wrong with my dump:
```
00:00:00.001 |I| .NET ThreadPool Worker Gpu : Backend Threading (Auto): True
00:00:00.041 |N| .NET ThreadPool Worker Application LoadApplication: Using Firmware Version: 13.0.0
00:00:00.041 |I| .NET ThreadPool Worker Application LoadApplication: Loading as NSP.
00:00:00.041 |E| .NET ThreadPool Worker Loader LoadNsp: Unable to load NSP: Could not find Main NCA
```

**Comment by EmulationFanatic** [comment]
Somehow none of the people who posted about this game booting mentioned the need for a save file. The game does not boot without one, as the web applet is missing. Changing back to status-nothing.
