### ISSUE TITLE
BioShock Infinite: The Complete Edition

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1791]
#### Current on `master` : 1.0.4728

Only spams messages in the console forever at a black screen and then crashed with the error below.

```
HLE.HostThread.41 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.InvalidOperationException: Thread scheduled in more than one core!
   at Ryujinx.HLE.HOS.Kernel.Threading.KScheduler.ContextSwitch() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\HleScheduler.cs:line 32
   at Ryujinx.HLE.HOS.Kernel.Threading.KCriticalSection.Leave() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KCriticalSection.cs:line 90
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.HandlePostSyscall() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 401
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 63
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[BITCE.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4807844/BITCE.zip)

**Comment by benderscruffy** [comment]
using 1.0.7094
nothing but a black screen
Spams applet errors

**Comment by matiashuarta** [comment]
same applet error today using update 1.0.2
