### ISSUE TITLE
Super Mario Maker 2

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#180]
#### Current on `master` :

* Build Version : 1.0.2784

```
CurrentDomain_UnhandledException: Unhandled exception caught: System.NotImplementedException: c004481d (NvHostChannelIoctl)
   at Ryujinx.HLE.HOS.Services.Nv.NvHostChannel.NvHostChannelIoctl.ProcessIoctl(ServiceCtx context, Int32 cmd) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.HLE\HOS\Services\Nv\NvHostChannel\NvHostChannelIoctl.cs:line 42
```

Bypass that, and then crash:
```
CurrentDomain_UnhandledException: Unhandled exception caught: System.NotImplementedException: android.gui.IGraphicBufferProducer 2
   at Ryujinx.HLE.HOS.Services.Android.NvFlinger.ProcessParcelRequest(ServiceCtx context, Byte[] parcelData, Int32 code) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.HLE\HOS\Services\Vi\NvFlinger.cs:line 185
```

Bypass that, and then crash:
```
Unhandled Exception: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.ICommonStateGetter: 66
```

Bypass that, and then crash:
```
00:02:01.398 | 0014 ServiceAudio GetAudioRendererWorkBufferSize: Library Revision 0x37564552 is not supported!
00:02:01.700 | 0020 ServiceAm SetTerminateResult: Result = 0x00000499 (2153-0002).
00:02:03.680 | 0022 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x0017ed38 nn::diag::detail::VAbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, nn::diag::MetaLogContext const&, char const*, std::__va_list)
   sdk:0x0017ee04 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, char const*, ...)
   sdk:0x0008f408 nn::audio::GetAudioRendererWorkBufferSize(nn::audio::AudioRendererParameter const&)
   main:0x0156cff8 Sub0000000009570ff8
   main:0x01569b78 Sub000000000956db78
   main:0x00f67ad0 Sub0000000008f6bad0
   main:0x00f67498 Sub0000000008f6b498
   main:0x014bc474 Sub00000000094c0474
   main:0x00f36580 Sub0000000008f3a580
   main:0x00f3b798 Sub0000000008f3f798
   main:0x014bc0e4 Sub00000000094c00e4
   main:0x014dd89c Sub00000000094e189c
   main:0x014dcb84 Sub00000000094e0b84
   sdk:0x00329e84 Sub000000000a979e84
   sdk:0x0032e290 Sub000000000a97e290
   sdk:0xfffffffff59afffc Subfffffffffffffffc
```

#### Outstanding Issues:
- https://github.com/Ryujinx/Ryujinx/issues/666
- 
- 
-

**Comment by HorrorTroll** [comment]
Updated

**Comment by GoffyDude** [comment]
## Super Mario Maker 2

#### Current on `master` : 1.0.4390

Game now boots, loads through all menus and rendering graphics quickly and accurately in-game.
The only thing that doesn't work is course world/coursebot, due to no online functionality.
Otherwise game is completely playable.

#### Screenshots :

![2020-05-01 06_03_00-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805669-e81ef980-8b75-11ea-912b-73c11ff2a3b5.png)
![2020-05-01 06_03_08-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805671-e9502680-8b75-11ea-87c7-c722fedf8083.png)
![2020-05-01 06_04_19-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805672-e9502680-8b75-11ea-8189-c5e0f08d22de.png)
![2020-05-01 06_05_37-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805689-f0773480-8b75-11ea-9b15-0a0b2fae684e.png)
![2020-05-01 06_06_26-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805693-f66d1580-8b75-11ea-8dfc-8295cefc46c4.png)
![2020-05-01 06_07_50-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805699-fa993300-8b75-11ea-93c2-d1e403b0e8be.png)
![2020-05-01 06_08_35-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805708-fec55080-8b75-11ea-9cf9-5b0d88e94e86.png)
![2020-05-01 06_08_47-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805716-038a0480-8b76-11ea-94f7-8f347ae6fb48.png)
![2020-05-01 06_09_28-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805717-04bb3180-8b76-11ea-832e-e1ab8111b154.png)
![2020-05-01 06_10_09-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805726-08e74f00-8b76-11ea-9459-8436ecd9d779.png)
![2020-05-01 06_10_21-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805737-0e449980-8b76-11ea-8ac7-92083014c7ab.png)
![2020-05-01 06_11_40-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805750-156ba780-8b76-11ea-873e-2ccf756cec3d.png)
![2020-05-01 06_12_58-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805757-1b618880-8b76-11ea-8f6d-bdecaa340f6b.png)
![2020-05-01 06_13_38-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805762-1dc3e280-8b76-11ea-95bf-9cb52d38be21.png)
![2020-05-01 06_15_00-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805774-21f00000-8b76-11ea-80aa-c5d113da0d5f.png)
![2020-05-01 06_15_23-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805784-26b4b400-8b76-11ea-9b1a-61bf67160f7c.png)
![2020-05-01 06_16_04-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805788-29170e00-8b76-11ea-8657-c2f184f5baee.png)
![2020-05-01 06_18_51-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805791-29afa480-8b76-11ea-90b4-af7b43ab3216.png)
![2020-05-01 06_21_26-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805793-2ae0d180-8b76-11ea-9238-0ee07dbb9e00.png)
![2020-05-01 06_22_16-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805795-2b796800-8b76-11ea-80e1-fffb322975a4.png)
![2020-05-01 06_23_09-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805796-2ddbc200-8b76-11ea-830b-558bca42359b.png)
![2020-05-01 06_24_09-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805801-33390c80-8b76-11ea-9394-d12ba48c84a4.png)
![2020-05-01 06_24_55-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805808-3633fd00-8b76-11ea-8431-a1969f1f9565.png)
![2020-05-01 06_26_06-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805817-3df3a180-8b76-11ea-8297-1bedc33bc39d.png)
![2020-05-01 06_28_15-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805827-421fbf00-8b76-11ea-8ff4-6f8f12004bce.png)
![2020-05-01 06_32_13-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805830-4350ec00-8b76-11ea-9b4e-7a0006f2e0d5.png)
![2020-05-01 06_32_43-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805843-4b109080-8b76-11ea-832f-a78282541386.png)
![2020-05-01 06_33_46-Ryujinx 1 0 4390 - SUPER MARIO MAKER 2 v1 0 0 (01009B90006DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/80805855-52d03500-8b76-11ea-82f3-1e200449238c.png)


#### Log file :

[SMM2.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4564161/SMM2.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by abourdos** [comment]
Is there online functionality or no? Because there is an online tag, but at the top of this page there is this 


> Game now boots, loads through all menus and rendering graphics quickly and accurately in-game.
> **The only thing that doesn't work is course world/coursebot, due to no online functionality.**
> Otherwise game is completely playable.

**Comment by EmulationFanatic** [comment]
@abourdos please hover over the online label to see what it is meant to indicate.

**Comment by Tarnadas** [comment]
I updated my Super Mario Maker 2 save file editor to also scan for an existing Ryujinx save folder:
https://github.com/Tarnadas/smmdb-client/releases

Also I would like to mention, that thumbnail creation is broken and you cannot change a level's name.

**Comment by elliotlolen** [comment]
Can you play online curse world?

**Comment by OmniAdachi** [comment]
is there a way to get the course bot working or would i have to download individual worlds and levels?

**Comment by Rady12366** [comment]
How to build a 2 player level in Super Mario Maker 2?

**Comment by FnfMasterDom2** [comment]
wait. HOW DO I DOWNLOAD THIS

**Comment by pandasv30** [comment]
download where,

**Comment by alakaikalili347** [comment]
Where is the download

**Comment by yell0wsuit** [comment]
Using the res scaler makes some sprites blurry (ground sprite is the most noticeable). Affects any world mode that are sprite-based (SMW, SMB1/3). Tested on version 1.1.738 using Vulkan & OpenGL backend. GPUs: NVIDIA & Intel.

2x:
![image](https://user-images.githubusercontent.com/5692900/235282882-713a31de-4577-44aa-b7bb-f04ceea227d0.png)

Native:
![image](https://user-images.githubusercontent.com/5692900/235282976-6b733fc5-b84a-4a49-8c62-65e147d324f2.png)

**Comment by lopin90** [comment]
how do i download the file im new to emulating

**Comment by Moonif** [comment]
The latest update (version 1.1.1072), fixed the crash on MacOS, now the game works perfectly.

**Comment by onion108** [comment]
Super Mario Maker 2 (ver. 1.0.0) is crashing on M1 MacBook Pro after a while in Ryujinx 1.1.1115 (which is the latest update as I'm writing this issue)

Crash Report: https://gist.github.com/onion108/6e471d61a02d3f2836f3ba765e4d5c9d

**Comment by onion108** [comment]
> Super Mario Maker 2 (ver. 1.0.0) is crashing on M1 MacBook Pro after a while in Ryujinx 1.1.1115 (which is the latest update as I'm writing this issue)
> 
> Crash Report: [gist.github.com/onion108/6e471d61a02d3f2836f3ba765e4d5c9d](https://gist.github.com/onion108/6e471d61a02d3f2836f3ba765e4d5c9d)

Update: It only appears when Hypervisor is enabled on macOS. It seems to be not appeared as I disabled Hypervisor

**Comment by DominicBrauer** [comment]
> Using the res scaler makes some sprites blurry (ground sprite is the most noticeable). Affects any world mode that are sprite-based (SMW, SMB1/3). Tested on version 1.1.738 using Vulkan & OpenGL backend. GPUs: NVIDIA & Intel.

Is there any fix for this problem? Even on Native the textures are blurry and/or show this grid pattern

**Comment by cddude** [comment]
Game crashes if Hypervisor is not off.  Otherwise seems to work well at least in Story Mode.  If you go into Course Maker it crashes.

Ryujinx 1.1.1345
Game version 3.0.3
Mac mini M2 Pro 16GB RAM

**Comment by Ryzen0904** [comment]
Where can we download the game for Ryujinx?

**Comment by xLeYoUsSeF** [comment]
how can i get the game?
