### ISSUE TITLE
限界凸記 モエロクロニクル Ｈ

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#182]
#### Current on `master` :

* Build Version : 1.0.2784

```
Unhandled Exception: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000020191c (opcode 0xe6c31002) is undefined!
```

**Comment by AcK77** [comment]
Needs an update!

**Comment by SeraUX** [comment]
## Moero Chronicle Hyper

#### Current on `master` : 1.0.4682

Game crashes on boot.

```
Last error returned.
00:00:15.482 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000002f11cc4 (opcode 0xf2c0617f) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
```
#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1005

#### Log file :

[moero-chronicle-hyper.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4742191/moero-chronicle-hyper.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by SeraUX** [comment]
## Moero Chronicle Hyper

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.5171

Game stays on a black screen without reacting to anything and without sound, while the logs only spam the `GetActualVibrationValue` stubs

#### Hardware Specs : 

##### CPU: i3-7300
##### GPU:  NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Log file :

[moero-chronicle-hyper.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5069450/moero-chronicle-hyper.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6807

**Comment by gdkchan** [comment]
Needs an update.

**Comment by Drakensangs** [comment]
#### Game Update Version : 02

#### Current on `master` : 1.1.142

The game boots and runs alright during the VN section, but once the town menu is opens up, the backgrounds are upside down. Entering the first dungeon causes the framerate to drop to around 7 to 8 FPS and the entire dungeon is upside down. Also, increasing the resolution causes black lines to appear on characters during VN sections.


#### Hardware Specs : 

##### CPU: Ryzen 5 3600
##### GPU: RX 6600 XT
##### RAM: 16GB

#### Screenshots :

This the game running at native resolution during the first VN section. Everything works fine at the moment.

![nolines](https://user-images.githubusercontent.com/51763452/172181741-5f3c3623-ffee-4439-b919-9f9d8cda7496.png)

Now with the resolution set to 2x, you can see thin black lines appear on the girl and on the protagonist if you look closely at his hair.

![lines](https://user-images.githubusercontent.com/51763452/172181976-6f75d196-bc27-4eef-8a62-9ae00a1dc4fe.png)

Native:

![nolines1](https://user-images.githubusercontent.com/51763452/172182060-2183de92-5607-4ebd-9319-6ca68abf989f.png)

2x:

![lines1](https://user-images.githubusercontent.com/51763452/172182083-bdd28ebe-f6a6-4609-805e-07704b63fa4e.png)

Here's what the backgrounds look like once the town menu opens up:

![upsidedown](https://user-images.githubusercontent.com/51763452/172182232-68e97bde-da8a-4b3d-b83a-45f059e249ec.png)

World map:

![upsidedown1](https://user-images.githubusercontent.com/51763452/172182280-8c3841fa-59e6-4482-a062-7afb4c7c9d1a.png)

Event inside the first dungeon. The dungeon itself is upside down now and the framerate took a massive hit.

![dungeonupsidedownframerate](https://user-images.githubusercontent.com/51763452/172182365-b1fcf62b-e184-4f19-8038-1a020f03cfb2.png)

Once the event is over, everything is still upside down and the framerate is still destroyed.

![dungeonupsidedownframerate1](https://user-images.githubusercontent.com/51763452/172182722-53203e30-2e9e-44c9-a600-6e799bc73c5a.png)

**Comment by gdkchan** [comment]
As of version 1.1.144, the upside down issue should be fixed. Performance should be better too.

**Comment by Drakensangs** [comment]
Town menu, world map and dungeon sections all look as they should now. No more upside down problems. Performance hasn't changed though, once entering the dungeon it's still very slow.

Town menu:
![Untitled0](https://user-images.githubusercontent.com/51763452/173206159-5f59fbdb-da98-45fb-b86a-8aea16965125.png)

World map:
![Untitled11](https://user-images.githubusercontent.com/51763452/173206203-ef6ceae5-0de3-432e-b7f2-16ece7ab3528.png)

Dungeon:
![Untitled](https://user-images.githubusercontent.com/51763452/173206080-97a3efc4-acee-4100-ace2-36756f6fcd93.png)
![Untitled1](https://user-images.githubusercontent.com/51763452/173206083-2e558ecb-53b1-48e2-9de1-9e4a43181581.png)

**Comment by wolfing** [comment]
Same thing happens to me, NVidia GTX 1070.  Here's a screenshot of the player in the same map position, one looking to an open area and one after turning left and looking at the wall.
![image](https://user-images.githubusercontent.com/808485/184083064-bcf57973-ffe2-4920-82a3-03057cf25592.png)
![image](https://user-images.githubusercontent.com/808485/184083161-eb684f7d-ec6c-4c59-a846-9e7cfd466a56.png)
