### ISSUE TITLE
SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1821]
#### Current on `master` : 1.0.4751

Crashes at initial splash screen.

```
UI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Graphics.Gpu.Memory.MemoryAccessor.Read[T](UInt64 gpuVa) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryAccessor.cs:line 56
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(IGpuAccessor gpuAccessor, Block block, UInt64 limitAddress, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 219
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(IGpuAccessor gpuAccessor, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 76
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, ShaderConfig& config, Int32& size) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 84
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateGraphicsShader(GpuState state, ShaderStage stage, UInt64 gpuVa, UInt64 gpuVaA) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 345
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 140
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 867
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 124
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 118
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 498
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 102
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-06-22 19_11_06-Ryujinx 1 0 4751 - SpongeBob SquarePants_ Battle for Bikini Bottom - Rehydrated ](https://user-images.githubusercontent.com/62343878/85349920-f37b0b00-b4bc-11ea-8d7c-8d4ae0e00523.png)

#### Log file :

[SSBfBBR.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4816418/SSBfBBR.zip)

**Comment by albfan** [comment]
This patch allow to reach the game:

```
diff --git i/Ryujinx.Cpu/MemoryManager.cs w/Ryujinx.Cpu/MemoryManager.cs
index 75ecca1c..03ae33b5 100644
--- i/Ryujinx.Cpu/MemoryManager.cs
+++ w/Ryujinx.Cpu/MemoryManager.cs
@@ -180,10 +180,10 @@ namespace Ryujinx.Cpu
             }
             catch (InvalidMemoryRegionException)
             {
-                if (_invalidAccessHandler == null || !_invalidAccessHandler(va))
+                /*if (_invalidAccessHandler == null || !_invalidAccessHandler(va))
                 {
                     throw;
-                }
+                }*/
             }
         }
 
@@ -344,10 +344,10 @@ namespace Ryujinx.Cpu
             }
             catch (InvalidMemoryRegionException)
             {
-                if (_invalidAccessHandler == null || !_invalidAccessHandler(va))
+                /*if (_invalidAccessHandler == null || !_invalidAccessHandler(va))
                 {
                     throw;
-                }
+                }*/
             }
         }
 
diff --git i/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs w/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs
index 8866cd25..2bf03111 100644
--- i/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs
+++ w/Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs
@@ -417,7 +417,10 @@ namespace Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions
                 return vector;
             }
 
-            Append(ApplyScaling(AssemblePVector(pCount)));
+           try {
+                Append(ApplyScaling(AssemblePVector(pCount)));
+           } catch (ArgumentOutOfRangeException e) {
+           }
 
             string AssembleDerivativesVector(int count)
             {
```

but lot of textures remain black.

**Comment by Freshmichaelj** [comment]
Any updates??

**Comment by GamerzHell9137** [comment]
@Freshmichaelj Download the latest version and check it

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6909

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Mateus109** [comment]
Textures flicker on nightly macOS build (e.g. 1.1.970) but not on stable 1.1.0 release.
![Untitled](https://github.com/Ryujinx/Ryujinx-Games-List/assets/11629946/600f6588-e3a6-48af-9869-4e91bfdd450d)

**Comment by piplup55** [comment]
the camera in game will move randomly if direct mouse input is enabled similar can be seen in [SpongeBob SquarePants The Cosmic Shake](https://github.com/Ryujinx/Ryujinx-Games-List/issues/1821)
![btw_i_use_arch_191823](https://github.com/Ryujinx/Ryujinx-Games-List/assets/100526773/1fe3b527-a677-4bf9-97bc-9e4ea76ae850)
https://youtu.be/_4vKhmP-O9g
