### ISSUE TITLE
Sleep Tight

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1822]
#### Current on `master` : 1.0.4751

Loads through menus and then plays with a white gameplay screen, making the game unplayable. Subsequent tries through the menu resulted in a crash.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 285
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 326
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureInfo info, TextureSearchFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 565
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 35
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 217
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 156
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 266
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 118
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 498
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 102
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-06-23 06_32_28-Ryujinx 1 0 4751 - Sleep Tight v0 0 0 (01004AC0081DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/85404544-52bc3800-b51c-11ea-97d2-1ea317eeb9d1.png)
![2020-06-23 06_36_14-Ryujinx 1 0 4751 - Sleep Tight v0 0 0 (01004AC0081DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/85404554-594aaf80-b51c-11ea-9b12-bce8c500f8dc.png)
![2020-06-23 06_36_22-Ryujinx 1 0 4751 - Sleep Tight v0 0 0 (01004AC0081DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/85404579-5fd92700-b51c-11ea-9481-06ef257a06a1.png)
![2020-06-23 06_37_08-Ryujinx 1 0 4751 - Sleep Tight v0 0 0 (01004AC0081DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/85404585-62d41780-b51c-11ea-9b23-a732d7bcebd0.png)
![2020-06-23 06_37_28-Ryujinx 1 0 4751 - Sleep Tight v0 0 0 (01004AC0081DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/85404595-67003500-b51c-11ea-846d-34b2ca1027f0.png)
![2020-06-23 06_37_37-Ryujinx 1 0 4751 - Sleep Tight v0 0 0 (01004AC0081DC000) (64-bit)](https://user-images.githubusercontent.com/62343878/85404596-6798cb80-b51c-11ea-891b-936f66ebb73f.png)

#### Log file :

[ST.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4819393/ST.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6794

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6910

**Comment by EmulationFanatic** [comment]
Updated
