### ISSUE TITLE
Invisigun Reloaded

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1836]
#### Current on `master` : 1.0.4761

Crashes on launch.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IRequest: 21
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/671

#### Log file :

[IR.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4826553/IR.zip)

**Comment by SeraUX** [comment]
## Invisigun Reloaded

#### Game Update Version : 1.7.11

#### Current on `master` : 1.0.4829

Game crashes on boot.

```Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: The information requested is unavailable on the current platform.
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties.get_IsDynamicDnsEnabled()
   at Ryujinx.HLE.HOS.Services.Nifm.StaticService.Types.DnsSetting..ctor(IPInterfaceProperties interfaceProperties) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nifm\StaticService\Types\DnsSetting.cs:line 16
   at Ryujinx.HLE.HOS.Services.Nifm.StaticService.IGeneralService.GetCurrentIpConfigInfo(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nifm\StaticService\IGeneralService.cs:line 90
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Hardware Specs :

##### CPU: i3 7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti
##### RAM: 8GB

#### Log file :

[invisigun-reloaded.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4873297/invisigun-reloaded.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6910
