### ISSUE TITLE
Super Neptunia RPG

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#184]
#### Current on `master` :

* Build Version : 1.0.2784

```
CurrentDomain_UnhandledException: Unhandled exception caught: System.NotImplementedException: c004481d (NvHostChannelIoctl)
   at Ryujinx.HLE.HOS.Services.Nv.NvHostChannel.NvHostChannelIoctl.ProcessIoctl(ServiceCtx context, Int32 cmd) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.HLE\HOS\Services\Nv\NvHostChannel\NvHostChannelIoctl.cs:line 42
```

Bypass that, and then crash:
```
00:01:41.585 | 0058 ServiceAudio GetAudioRendererWorkBufferSize: Library Revision 0x36564552 is not supported!
00:01:41.685 | 0015 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000008e6a594 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1048
   at Sub0000000008e6a594(CpuThreadState , MemoryManager )
   at ChocolArm64.Translation.Translator.ExecuteSubroutine(CpuThreadState state, Int64 position) in D:\Games\Ryujinx-HorrorTroll\ChocolArm64\Translation\Translator.cs:line 59
   at ChocolArm64.Translation.Translator.ExecuteSubroutine(CpuThread thread, Int64 position) in D:\Games\Ryujinx-HorrorTroll\ChocolArm64\Translation\Translator.cs:line 51
   at ChocolArm64.CpuThread.<>c__DisplayClass14_0.<.ctor>b__0() in D:\Games\Ryujinx-HorrorTroll\ChocolArm64\CpuThread.cs:line 35
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

#### Outstanding Issues:
- https://github.com/Ryujinx/Ryujinx/issues/666
- https://github.com/Ryujinx/Ryujinx/issues/707

**Comment by AcK77** [comment]
Needs an update.

**Comment by HorrorTroll** [comment]
Updated

**Comment by Thog** [comment]
Need update

**Comment by GoffyDude** [comment]
## Super Neptunia RPG

#### Current on `master` : 1.0.4390

- Emulation starts with a black screen cutscene (nvdec).
- Loads menus properly
- In-game graphics seem to be rendered accurately
- Game runs slowly, but can be played through.

#### Screenshots :

![Image 2020 05 01, 10 05 05](https://user-images.githubusercontent.com/62343878/80822782-ac495b80-8b98-11ea-81bd-9a33db6d6edf.png)
![Image 2020 05 01, 10 05 13](https://user-images.githubusercontent.com/62343878/80822801-b4a19680-8b98-11ea-96c7-0cf29b9b3164.png)
![Image 2020 05 01, 10 05 18](https://user-images.githubusercontent.com/62343878/80822818-bc613b00-8b98-11ea-8fbd-2b6a2b259b88.png)
![Image 2020 05 01, 10 05 26](https://user-images.githubusercontent.com/62343878/80822830-c08d5880-8b98-11ea-82db-6a96fe4bfa8e.png)
![Image 2020 05 01, 10 05 00 (2)](https://user-images.githubusercontent.com/62343878/80822838-c5520c80-8b98-11ea-85dd-b74b204ec7e5.png)
![Image 2020 05 01, 10 05 31](https://user-images.githubusercontent.com/62343878/80822846-c97e2a00-8b98-11ea-82e4-1cad69024362.png)
![Image 2020 05 01, 10 05 10](https://user-images.githubusercontent.com/62343878/80822858-cdaa4780-8b98-11ea-9e71-8ea82da75522.png)
![Image 2020 05 01, 10 05 44](https://user-images.githubusercontent.com/62343878/80822872-d1d66500-8b98-11ea-8669-684e7ef8ab86.png)
![Image 2020 05 01, 10 05 09](https://user-images.githubusercontent.com/62343878/80822884-d733af80-8b98-11ea-8d0a-cb0fb1e1dc81.png)
![Image 2020 05 01, 10 05 34](https://user-images.githubusercontent.com/62343878/80822892-db5fcd00-8b98-11ea-99eb-14af96c8b21c.png)
![Image 2020 05 01, 10 05 05 (2)](https://user-images.githubusercontent.com/62343878/80822913-e286db00-8b98-11ea-8e9a-3d08a75cf193.png)
![Image 2020 05 01, 10 05 11](https://user-images.githubusercontent.com/62343878/80822918-e581cb80-8b98-11ea-9b61-4e49b3735caf.png)
![Image 2020 05 01, 10 05 48](https://user-images.githubusercontent.com/62343878/80822924-e9155280-8b98-11ea-98ce-e90b2010fe01.png)
![Image 2020 05 01, 10 05 38](https://user-images.githubusercontent.com/62343878/80822932-ed417000-8b98-11ea-9732-78be88bdc9d9.png)


#### Log file :

[SuperNeptuniaRPG.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4565331/SuperNeptuniaRPG.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6407

**Comment by EmulationFanatic** [comment]
Updated
