### ISSUE TITLE
Outbuddies DX

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1853]
#### Current on `master` : 1.0.4761

Crashes on launch.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 423
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 143
   at Ryujinx.Graphics.Gpu.Engine.Methods.FinishTransfer() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 79
   at Ryujinx.Graphics.Gpu.Engine.Methods.LoadInlineData(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 66
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 497
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 183
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 102
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[ODX.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4833920/ODX.zip)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6455

**Comment by benderscruffy** [comment]
please change status

**Comment by F1ReB4LL** [comment]
## Outbuddies DX

#### Game Update Version : *1.0.4d*

#### Current on `master` : *1.1.207*

#### Graphics Backend : *Both Vulkan and OpenGL*

*Looks OK, haven't noticed any of the previously described issues.*

```
Last error returned: No errors shown
```

#### Hardware Specs : 

##### CPU: *i5-11400H*
##### GPU: *NVIDIA RTX 3050*
##### RAM: *24GB*

#### Screenshots :

![ryujinx_odx1](https://user-images.githubusercontent.com/39680140/182964119-52ba76b1-42b9-40ca-894b-80333c65e1e0.png)
![ryujinx_odx2](https://user-images.githubusercontent.com/39680140/182964083-34b80c68-4fa4-48c9-86ba-196820a7c428.png)
![ryujinx_odx3](https://user-images.githubusercontent.com/39680140/182964010-e45d5a74-5c84-46dc-8e0d-35af540af0d4.png)
![ryujinx_odx5](https://user-images.githubusercontent.com/39680140/182964031-e7e69a06-dd48-4821-bf93-5923b03ff985.png)
![ryujinx_odx6](https://user-images.githubusercontent.com/39680140/182964141-d056a92a-e9ed-4d9b-b357-ccd8f9cb35e0.png)
![ryujinx_odx7](https://user-images.githubusercontent.com/39680140/182964039-85745b56-1845-4b45-b17e-f792527487a7.png)
