### ISSUE TITLE
Mr. DRILLER DrillLand

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1854]
#### Current on `master` : 1.0.4767

Has nvdec cutscene issue on intro. Otherwise loads to menus properly and then crashes after trying to start a new game.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: 0 applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Applets\AppletManager.cs:line 32
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\SystemAppletProxy\ILibraryAppletCreator.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
00:01:49.610 | ServiceHid GetNpadJoyHoldType: Stubbed. appletResourceUserId: 0 - JoyHold: Horizontal
```

#### Screenshots :

![2020-06-26 07_33_52-Ryujinx 1 0 4767 - Mr  DRILLER DrillLand v1 0 0 (0100DCA011262000) (64-bit)](https://user-images.githubusercontent.com/62343878/85863040-cad66800-b77f-11ea-8af2-17221506d5e0.png)
![2020-06-26 07_34_10-Ryujinx 1 0 4767 - Mr  DRILLER DrillLand v1 0 0 (0100DCA011262000) (64-bit)](https://user-images.githubusercontent.com/62343878/85863044-cb6efe80-b77f-11ea-83c1-f86b93b5c081.png)
![2020-06-26 07_34_13-Ryujinx 1 0 4767 - Mr  DRILLER DrillLand v1 0 0 (0100DCA011262000) (64-bit)](https://user-images.githubusercontent.com/62343878/85863046-cc079500-b77f-11ea-8aa4-0d4b4a375655.png)
![2020-06-26 07_34_25-Ryujinx 1 0 4767 - Mr  DRILLER DrillLand v1 0 0 (0100DCA011262000) (64-bit)](https://user-images.githubusercontent.com/62343878/85863049-cdd15880-b77f-11ea-9f38-b1f916fe4c09.png)
![2020-06-26 07_34_44-Ryujinx 1 0 4767 - Mr  DRILLER DrillLand v1 0 0 (0100DCA011262000) (64-bit)](https://user-images.githubusercontent.com/62343878/85863052-cf9b1c00-b77f-11ea-8e33-1da4b6edd2ed.png)

#### Log file :

[MDD.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4837244/MDD.zip)

**Comment by EmulationFanatic** [comment]
Updated
