### ISSUE TITLE
Blazing Chrome

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#187]
#### Current on `master` :

* Build Version : 1.0.2840

```
Unhandled Exception: System.NotImplementedException: nvdrv INvDrvServices: 6
```

Fix that, it's boot more furthur. And then show a corrupt texture in a second then crash. Maybe graphic was overload and can't handle. So i contain the log on here

#### Outstanding Issues:
- https://github.com/Ryujinx/Ryujinx/issues/635

#### Log file :
[Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/3388641/Ryujinx.log)

**Comment by GoffyDude** [comment]
Needs update

**Comment by EmulationFanatic** [comment]
## Blazing Chrome

#### Current on `master` : 1.0.4675

Game now boots and goes through menus, but crashes while displaying the tutorial.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 423
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 143
   at Ryujinx.Graphics.Gpu.Memory.MemoryAccessor.Write(UInt64 gpuVa, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryAccessor.cs:line 107
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 14
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-06-04 07_16_29-Ryujinx 1 0 4675 - Blazing Chrome v1 0 0 (0100C2700C252000) (64-bit)](https://user-images.githubusercontent.com/62343878/83761515-a9c4a080-a633-11ea-8e30-cd5f5698203b.png)
![2020-06-04 07_16_34-Ryujinx 1 0 4675 - Blazing Chrome v1 0 0 (0100C2700C252000) (64-bit)](https://user-images.githubusercontent.com/62343878/83761520-aa5d3700-a633-11ea-920d-d633fde88b2d.png)
![2020-06-04 07_16_52-Ryujinx 1 0 4675 - Blazing Chrome v1 0 0 (0100C2700C252000) (64-bit)](https://user-images.githubusercontent.com/62343878/83761523-aa5d3700-a633-11ea-94a6-0f35fa723b88.png)
![2020-06-04 07_17_05-Ryujinx 1 0 4675 - Blazing Chrome v1 0 0 (0100C2700C252000) (64-bit)](https://user-images.githubusercontent.com/62343878/83761525-aaf5cd80-a633-11ea-82fa-f6bfb5357fdc.png)
![2020-06-04 07_17_16-Ryujinx 1 0 4675 - Blazing Chrome v1 0 0 (0100C2700C252000) (64-bit)](https://user-images.githubusercontent.com/62343878/83761530-ab8e6400-a633-11ea-9cc8-a0cc9d5a8452.png)
![2020-06-04 07_17_34-Ryujinx 1 0 4675 - Blazing Chrome v1 0 0 (0100C2700C252000) (64-bit)](https://user-images.githubusercontent.com/62343878/83761531-ac26fa80-a633-11ea-8875-0211de479e19.png)

#### Log file :

[BC.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4730255/BC.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by EmulationFanatic** [comment]
Updated
