### ISSUE TITLE
Puchitto kurasutā

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1883]
#### Current on `master` : 4767

Crashes with an missing service error when you try to go past the main menu.

```
Last error returned.
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IRequest: 21

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0028f8b8 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> >, 4ul, 12ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 6, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, unsigned int)
   sdk:0x0028f0b4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::nifm::detail::IRequest, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::nifm::detail::IRequest, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_GetAppletInfo(nn::sf::Out<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::sf::Out<unsigned int, void>, nn::sf::OutBuffer const&, unsigned int)
   sdk:0x0028ce7c nn::nifm::detail::RequestClient::PrepareLibraryApplet(nn::applet::LibraryAppletHandle*)
   sdk:0x00292864 nn::nifm::PrepareHandlingNetworkRequestResult(nn::nifm::RequestHandle, nn::applet::LibraryAppletHandle*)
   sdk:0x002947c8 nn::nifm::NetworkConnection::HandleNetworkRequestErrorResult()
   sdk:0x00293024 nn::nifm::HandleNetworkRequestErrorResult()
   main:0x00d446e8 Sub0000000008d486e8
   main:0x00d7739c Sub0000000008d7b39c
   sdk:0x000c7058 Sub000000000bbce058
   sdk:0x000cb524 Sub000000000bbd2524
   ??? Sub0000000000000000

Buffer Information:
        ReceiveBuff:
        Position: 0x00000011f1acce4c Size: 0x0000000000001000 Flags: 0

Raw Request Data:
00000000   01 00 14 00 03 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  15 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000030   00 00 00 00                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/671

#### Screenshots :

![06_27_14-21:14:05](https://user-images.githubusercontent.com/62521228/85930331-b8f9df80-b8bb-11ea-9f1e-d37a31723373.png)
![06_27_14-21:14:18](https://user-images.githubusercontent.com/62521228/85930332-b9927600-b8bb-11ea-9420-b43ce25aa6c6.png)

#### Log file :

[puchitto-karasuta.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4841110/puchitto-karasuta.log)

**Comment by SeraUX** [comment]
## Puchitto kurasutā

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.4829

Game worked fine without problems found.

#### Hardware Specs :

##### CPU: i3 7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti
##### RAM: 8GB

#### Screenshots :

![07_04_29-18:29:19](https://user-images.githubusercontent.com/62521228/86517063-2c54a180-be26-11ea-87b1-874704ea9fab.png)
![07_04_29-18:29:39](https://user-images.githubusercontent.com/62521228/86517064-2ced3800-be26-11ea-9184-3ef68f8cbb72.png)
![07_04_30-18:30:01](https://user-images.githubusercontent.com/62521228/86517065-2eb6fb80-be26-11ea-8187-3b5845879fbc.png)
![07_04_30-18:30:12](https://user-images.githubusercontent.com/62521228/86517066-3080bf00-be26-11ea-940b-9c272ebe4d8a.png)
![07_04_30-18:30:28](https://user-images.githubusercontent.com/62521228/86517068-31b1ec00-be26-11ea-8390-5fbdcc9082df.png)
![07_04_31-18:31:13](https://user-images.githubusercontent.com/62521228/86517069-32e31900-be26-11ea-9f78-af8ed03eea55.png)
![07_04_31-18:31:23](https://user-images.githubusercontent.com/62521228/86517071-34144600-be26-11ea-9111-97f845906b6a.png)
![07_04_32-18:32:54](https://user-images.githubusercontent.com/62521228/86517073-35457300-be26-11ea-90a4-1b923cff8a96.png)
![07_04_35-18:35:07](https://user-images.githubusercontent.com/62521228/86517075-370f3680-be26-11ea-883a-b5485773c6f1.png)
![07_04_38-18:38:12](https://user-images.githubusercontent.com/62521228/86517076-38406380-be26-11ea-971e-83137cc4f3f7.png)

#### Log file :

[puchitto-kurasuta.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4873249/puchitto-kurasuta.log)
