### ISSUE TITLE
IxSHE Tell

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1893]
#### Current on `master` : 1.0.4767

Graphics dont render at all, but you can interact with the game. When you try to get ingame, it crashes

```Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyBuffer(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyBuffer.cs:line 64
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[ixshe-tell.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4841347/ixshe-tell.log)

**Comment by yuwenhua653** [comment]
Current on master : 1.0.6587
Now the game can enter normally and the graphics can be rendered, but the game crashes after running for a period of time
Screenshots :
![image](https://user-images.githubusercontent.com/30205483/108170374-0ff74200-7135-11eb-8fc2-9f4e82c88510.png)
![2021-02-17 152710](https://user-images.githubusercontent.com/30205483/108170466-2a312000-7135-11eb-9dec-9e36bc557567.png)
[IxSHE Tell.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5993964/IxSHE.Tell.log)

**Comment by EmulationFanatic** [comment]
Updated
