### ISSUE TITLE
Monster Farm

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1894]
#### Current on `master` : 1.0.4767

Game crashes with an missing opcode error.

```
00:00:17.064 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000431ec90 (opcode 0xf25201f0) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
```

#### Pull requests needed :

https://github.com/Ryujinx/Ryujinx/pull/1192
https://github.com/Ryujinx/Ryujinx/pull/1326

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/671

#### Log file :

[monster-farm.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4842046/monster-farm.log)

**Comment by SeraUQ** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
