### ISSUE TITLE
SEGA AGES Puyo Puyo

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1901]
#### Current on `master` : 1.0.4767

Game has audio problems and crashes with an missing service error after finishing the matches.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00061a20 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> > >::ProcessWithOutObjects(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*)
   sdk:0x000df0b4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::baas::IManagerBase, nn::sf::cmif::client::CmifDomainProxy<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::baas::IManagerForApplication>::_nn_sf_sync_EnsureIdTokenCacheAsync(nn::sf::Out<nn::sf::SharedPointer<nn::account::detail::IAsyncContext>, void>)
   sdk:0x000e9b68 nn::account::EnsureNetworkServiceAccountIdTokenCacheAsync(nn::account::AsyncContext*, nn::account::UserHandle const&)
   main:0x003b3e74 nn::pia::nex::NexService::PreLoginProcess(nn::pia::wan::InitializeInternetSetting const*)
   main:0x0034f2d8 nn::pia::framework::LoginJob::PreLoginProcess()
   main:0x00344d60 nn::pia::common::StepSequenceJob::ExecuteCore()
   main:0x0033eeb8 nn::pia::common::Job::Execute(bool)
   main:0x0033ff8c nn::pia::common::Scheduler::Dispatch(unsigned int)
   main:0x0034ab94 nn::pia::framework::Framework::Update()
   main:0x001954b0 NetworkModule::update()
   main:0x0019b58c MParallelTaskSet::OnTask()
   main:0x001d85a4 MLooper::Run(MTask*)
   main:0x00000540 M2Main(int, char**)
   main:0x001f9a10 M2BootStrap()
   sdk:0x000849bc nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000ac Sub00000000080000ac

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  02 00 00 00 00 00 00 00   SFCI············
00000020   01 00 00 00 00 00 00 00  00 BC 5D 0D 00 00 04 00   ·········¼]·····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![06_29_09-17:09:17](https://user-images.githubusercontent.com/62521228/86024291-195c5e80-ba2d-11ea-9d46-5d1265045a8f.png)
![06_29_09-17:09:29](https://user-images.githubusercontent.com/62521228/86024308-1e211280-ba2d-11ea-8e7e-1a19826f32d3.png)
![06_29_09-17:09:48](https://user-images.githubusercontent.com/62521228/86024322-22e5c680-ba2d-11ea-9c7c-425469942554.png)
![06_29_09-17:09:58](https://user-images.githubusercontent.com/62521228/86024338-27aa7a80-ba2d-11ea-8817-8eafe5b9dc29.png)
![06_29_10-17:10:03](https://user-images.githubusercontent.com/62521228/86024350-2bd69800-ba2d-11ea-9404-0b5630f7e9ff.png)
![06_29_10-17:10:14](https://user-images.githubusercontent.com/62521228/86024359-2ed18880-ba2d-11ea-84f6-0922f5dbb089.png)
![06_29_10-17:10:51](https://user-images.githubusercontent.com/62521228/86024368-32650f80-ba2d-11ea-948b-f5c82bbebccb.png)
![06_29_14-17:14:22](https://user-images.githubusercontent.com/62521228/86024385-3729c380-ba2d-11ea-91c6-36747965fdcf.png)
![06_29_15-17:15:12](https://user-images.githubusercontent.com/62521228/86024399-3c870e00-ba2d-11ea-891a-aa8e43e4fcba.png)
![06_29_15-17:15:32](https://user-images.githubusercontent.com/62521228/86024417-43158580-ba2d-11ea-856e-99cf18e99708.png)

#### Log file :

[sega-ages-puyo-puyo.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4846455/sega-ages-puyo-puyo.log)

**Comment by SeraUX** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
