### ISSUE TITLE
Kissed by the Baddest Bidder

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1907]
#### Current on `master` : 1.0.4767

Game crashes on launch with an missing service error.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IAccountServiceForApplication: 131

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0010ac68 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 10, 0ul> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 10, 0ul> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::BufferClientArgumentType, unsigned int)
   sdk:0x0010a920 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::IAccountServiceForApplication, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::IAccountServiceForApplication, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_ListOpenContextStoredUsers(nn::sf::OutArray<nn::account::Uid> const&)
   sdk:0x00108c20 nn::account::ListPushedOpenUsers(nn::account::Uid*, int)
   sdk:0x00108a28 nn::account::PopOpenUsers(int*, nn::account::UserHandle*, int)
   main:0x0014d380 Sub0000000008151380
   main:0x0014d2c8 Sub00000000081512c8
   main:0x0013df88 Sub0000000008141f88
   main:0x00455ce8 Sub0000000008459ce8
   main:0x00510644 Sub0000000008514644
   main:0x0052c358 Sub0000000008530358
   main:0x00510968 Sub0000000008514968
   main:0x0050fe74 Sub0000000008513e74
   main:0x00511098 Sub0000000008515098
   main:0x0050bc1c Sub000000000850fc1c
   main:0x002a39c0 Sub00000000082a79c0
   main:0x002e64b8 Sub00000000082ea4b8
   main:0x002e6270 Sub00000000082ea270
   main:0x0004f230 nnMain
   sdk:0x0009857c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Buffer Information:
        RecvListBuff:
        Position: 0x000000000a96b6b0 Size: 0x0000000000000080

Raw Request Data:
00000000   01 00 10 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  83 00 00 00 00 00 00 00   SFCI···········
00000020   00 00 00 00 00 00 00 00  80 00 00 00 B0 B6 96 0A   ···········°¶·
00000030   00 00 80 00                                        ···

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1267

#### Log file :

[kissed-by-the-baddest-bidder.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4853251/kissed-by-the-baddest-bidder.log)

**Comment by Kaizen-mini** [comment]
**Game Update Version :** 1.0.2

**Current on `master` : Commit Id *or* Build Version :** 1.0.5396

This game runs smoothly now, audio, video, text, menus are great; except all in-game screens have white background, images can't be shown.

**Screenshots :**

![Ryujinx_oADXWDInld](https://user-images.githubusercontent.com/71459954/93797037-e90c1100-fc65-11ea-9e89-7ca90aa1aae6.png)
![Ryujinx_28qLaLljBg](https://user-images.githubusercontent.com/71459954/93797065-f1fce280-fc65-11ea-894d-1b606d0a027f.png)
![Ryujinx_5UREqj7p1L](https://user-images.githubusercontent.com/71459954/93797082-f75a2d00-fc65-11ea-9608-04a3510f85dc.png)
![Ryujinx_RFBSHnQWTM](https://user-images.githubusercontent.com/71459954/93797145-0c36c080-fc66-11ea-881d-8e181f5aa02a.png)
![Ryujinx_K74Y3krq0c](https://user-images.githubusercontent.com/71459954/93797254-31c3ca00-fc66-11ea-9c02-a291699ea2a7.png)
![Ryujinx_XBWy41aLhL](https://user-images.githubusercontent.com/71459954/93797271-37211480-fc66-11ea-9ee7-37ed48cf5f6f.png)
![Ryujinx_PYgYzM0ziz](https://user-images.githubusercontent.com/71459954/93797316-4738f400-fc66-11ea-9fa4-bd37da58d38d.png)

**Log file :**
[Ryujinx_2020-09-21_23-20-43.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5256885/Ryujinx_2020-09-21_23-20-43.log)

**Comment by EmulationFanatic** [comment]
Updated
