### ISSUE TITLE
Super Street: Racer

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1918]
#### Current on `master` : Commit Id *or* Build Version : 1.0.4767

Crashes at the graphically corrupt title screen after pressing any button.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Error applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Applets\AppletManager.cs:line 32
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\SystemAppletProxy\ILibraryAppletCreator.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-07-01 17_34_09-Ryujinx 1 0 4767 - Super Street_ Racer v1 0 0 (0100FB400F54E000) (64-bit)](https://user-images.githubusercontent.com/62343878/86300841-65400c80-bbc1-11ea-9531-acaf0f0dafe4.png)
![2020-07-01 17_34_18-Ryujinx 1 0 4767 - Super Street_ Racer v1 0 0 (0100FB400F54E000) (64-bit)](https://user-images.githubusercontent.com/62343878/86300843-65d8a300-bbc1-11ea-823f-ffa08a2a5092.png)
![2020-07-01 17_34_23-Ryujinx 1 0 4767 - Super Street_ Racer v1 0 0 (0100FB400F54E000) (64-bit)](https://user-images.githubusercontent.com/62343878/86300849-6a9d5700-bbc1-11ea-8aa8-37e560b94cec.png)

#### Log file :

[SSR.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4861280/SSR.zip)

**Comment by EmulationFanatic** [comment]
Updated
