### ISSUE TITLE
Digimon Story Cyber Sleuth: Complete Edition

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1938]
#### Current on `master` : 1.0.4847

Boots to upside-down menus that also contain some corrupt graphics, and then crashes when trying to go in-game.

```
HLE.HostThread.7 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 423
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 268
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 97
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
00:09:53.194 | HLE.HostThread.8 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 97
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-07-05 09_52_18-Ryujinx 1 0 4847 - Digimon Story Cyber Sleuth_ Complete Edition v1 0 0 (010014E0](https://user-images.githubusercontent.com/62343878/86536647-809f6600-bea6-11ea-8415-48f1aa5394ad.png)
![2020-07-05 09_52_52-Ryujinx 1 0 4847 - Digimon Story Cyber Sleuth_ Complete Edition v1 0 0 (010014E0](https://user-images.githubusercontent.com/62343878/86536649-81d09300-bea6-11ea-85dc-0fdaf654ed4f.png)
![2020-07-05 09_55_16-Ryujinx 1 0 4847 - Digimon Story Cyber Sleuth_ Complete Edition v1 0 0 (010014E0](https://user-images.githubusercontent.com/62343878/86536651-839a5680-bea6-11ea-8d4e-d550cd5ad0f6.png)
![2020-07-05 09_55_23-Ryujinx 1 0 4847 - Digimon Story Cyber Sleuth_ Complete Edition v1 0 0 (010014E0](https://user-images.githubusercontent.com/62343878/86536654-85fcb080-bea6-11ea-8607-79a2305953f9.png)
![2020-07-05 09_57_32-Ryujinx 1 0 4847 - Digimon Story Cyber Sleuth_ Complete Edition v1 0 0 (010014E0](https://user-images.githubusercontent.com/62343878/86536657-872ddd80-bea6-11ea-81b9-35c7b3950d7a.png)
![2020-07-05 09_59_30-Ryujinx 1 0 4847 - Digimon Story Cyber Sleuth_ Complete Edition v1 0 0 (010014E0](https://user-images.githubusercontent.com/62343878/86536661-8e54eb80-bea6-11ea-9d0e-398b2ebeddbe.png)

#### Log file :

[DSCSCE.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4875200/DSCSCE.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by gdkchan** [comment]
Needs an update.

**Comment by EmulationFanatic** [comment]
Updated
