### ISSUE TITLE
Kill la Kill - IF

### ISSUE THREAD

**Issue by DrHacknik** [Ryujinx/Ryujinx-Games-List#194]
#### Current on `master` :

* Commit Id *or* Build Version : 1.0.2909

Unimplemented services, does not go ingame; crashes after about 3mins or so.

Last error returned:
```
00:01:47.226 | 0011 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: c004481d
   at Ryujinx.HLE.HOS.Services.Nv.NvHostChannel.NvHostChannelIoctl.ProcessIoctl(ServiceCtx context, Int32 cmd) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nv\NvHostChannel\NvHostChannelIoctl.cs:line 42
   at Ryujinx.HLE.HOS.Services.Nv.INvDrvServices.ProcessIoctl(ServiceCtx context, Int32 cmd, IoctlProcessor processor) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nv\INvDrvServices.cs:line 210
   at Ryujinx.HLE.HOS.Services.Nv.INvDrvServices.Ioctl(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nv\INvDrvServices.cs:line 80
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, IMemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 37
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 140
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Log file :

[Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/3570752/Ryujinx.log)

**Comment by AcK77** [comment]
Updated.

**Comment by DrHacknik** [comment]
Updated

_Tested on GTX 1050 Ti_

**Comment by Thog** [comment]
Need update

**Comment by EmulationFanatic** [comment]
## Kill la Kill - IF

#### Current on `master` : 1.0.4683

Game now loads and plays at a high FPS.

#### Screenshots :

![2020-06-09 07_56_18-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84160970-fe00c380-aa2b-11ea-8a7c-adc8139b339b.png)
![2020-06-09 07_59_50-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84160971-ff31f080-aa2b-11ea-8644-c2dfcfd6f7e7.png)
![2020-06-09 08_00_33-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84160973-ffca8700-aa2b-11ea-8460-ea49fe247e8a.png)
![2020-06-09 08_00_47-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84160979-00fbb400-aa2c-11ea-80f4-f194b27e4926.png)
![2020-06-09 08_01_34-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84160982-00fbb400-aa2c-11ea-8f71-ee62d42a8d58.png)
![2020-06-09 08_02_06-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161010-0822c200-aa2c-11ea-937a-ad38c0011a78.png)
![2020-06-09 08_02_29-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161023-0ce77600-aa2c-11ea-9690-f13a1e95ac90.png)
![2020-06-09 08_02_32-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161042-1375ed80-aa2c-11ea-8bce-1c4935a9e920.png)
![2020-06-09 08_03_18-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161056-17097480-aa2c-11ea-8422-b763c9b545b4.png)
![2020-06-09 08_04_53-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161061-183aa180-aa2c-11ea-9e01-c7955b14d1f9.png)
![2020-06-09 08_08_45-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161089-212b7300-aa2c-11ea-887d-31c1ac28f2ca.png)
![2020-06-09 08_13_25-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161109-2a1c4480-aa2c-11ea-87c2-7bf0d0bd656c.png)
![2020-06-09 08_19_09-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161138-30122580-aa2c-11ea-8346-6ca31886020e.png)
![2020-06-09 08_19_28-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161166-36080680-aa2c-11ea-9819-e0fbb78ea862.png)
![2020-06-09 08_19_49-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161181-3c967e00-aa2c-11ea-9e8b-3d6847fbcf9c.png)
![2020-06-09 08_20_38-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161202-4324f580-aa2c-11ea-8afa-21ae17e6dc09.png)
![2020-06-09 08_22_30-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161224-47e9a980-aa2c-11ea-9551-da4dccf139bb.png)
![2020-06-09 08_23_04-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161239-4b7d3080-aa2c-11ea-8144-797aaff1e449.png)
![2020-06-09 08_25_08-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161261-53d56b80-aa2c-11ea-81f0-f4a9337faf1b.png)
![2020-06-09 08_25_56-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161291-5b951000-aa2c-11ea-8fad-d6e4acf4e77e.png)
![2020-06-09 08_26_11-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161317-62bc1e00-aa2c-11ea-894f-222af4f5f063.png)
![2020-06-09 08_26_20-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161329-6780d200-aa2c-11ea-807d-0b31ce09578a.png)
![2020-06-09 08_26_56-Ryujinx 1 0 4683 - Kill la Kill The Game - IF v1 0 0 (0100A3F00C536000) (64-bit)](https://user-images.githubusercontent.com/62343878/84161359-6d76b300-aa2c-11ea-9727-00aeb42d9562.png)


#### Log file :

[KlKIF.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4752824/KlKIF.zip)

**Comment by EmulationFanatic** [comment]
Updated
