### ISSUE TITLE
Sub Level Zero: Redux

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1948]
#### Current on `master` : 1.0.4847

Tried three times to get in-game:
First attempt deadlocked in early splash screens.
Second attempt crashed in the menus.
The third attempt the game loaded and played flawlessly.

```
HLE.HostThread.6 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetRef[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 207
   at ARMeilleure.Instructions.NativeInterface.ReadVector128Exclusive(UInt64 address) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 258
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-07-05 15_16_15-Ryujinx 1 0 4847 - Sub Level Zero_ Redux v1 0 (0100E6400BCE8000) (64-bit)](https://user-images.githubusercontent.com/62343878/86542676-09cd9180-bed5-11ea-8017-777c500dc3e6.png)
![2020-07-05 15_20_14-Ryujinx 1 0 4847 - Sub Level Zero_ Redux v1 0 (0100E6400BCE8000) (64-bit)](https://user-images.githubusercontent.com/62343878/86542677-0a662800-bed5-11ea-90a2-d3a37a6f4003.png)
![2020-07-05 15_20_29-Ryujinx 1 0 4847 - Sub Level Zero_ Redux v1 0 (0100E6400BCE8000) (64-bit)](https://user-images.githubusercontent.com/62343878/86542680-0df9af00-bed5-11ea-9c06-5b7d2aa34230.png)
![2020-07-05 15_29_17-Ryujinx 1 0 4847 - Sub Level Zero_ Redux v1 0 (0100E6400BCE8000) (64-bit)](https://user-images.githubusercontent.com/62343878/86542682-12be6300-bed5-11ea-9e33-232cc66dc2ca.png)
![2020-07-05 15_29_25-Ryujinx 1 0 4847 - Sub Level Zero_ Redux v1 0 (0100E6400BCE8000) (64-bit)](https://user-images.githubusercontent.com/62343878/86542683-15b95380-bed5-11ea-9296-551aed8721b6.png)
![2020-07-05 15_29_39-Ryujinx 1 0 4847 - Sub Level Zero_ Redux v1 0 (0100E6400BCE8000) (64-bit)](https://user-images.githubusercontent.com/62343878/86542684-1651ea00-bed5-11ea-813a-7e76ae882591.png)
![2020-07-05 15_30_22-Ryujinx 1 0 4847 - Sub Level Zero_ Redux v1 0 (0100E6400BCE8000) (64-bit)](https://user-images.githubusercontent.com/62343878/86542685-1651ea00-bed5-11ea-9ae8-5da4569d3aaa.png)
![2020-07-05 15_30_59-Ryujinx 1 0 4847 - Sub Level Zero_ Redux v1 0 (0100E6400BCE8000) (64-bit)](https://user-images.githubusercontent.com/62343878/86542686-19e57100-bed5-11ea-99d2-387839fa57d1.png)
![2020-07-05 15_31_34-Ryujinx 1 0 4847 - Sub Level Zero_ Redux v1 0 (0100E6400BCE8000) (64-bit)](https://user-images.githubusercontent.com/62343878/86542688-1eaa2500-bed5-11ea-956d-b64deefd7228.png)
![2020-07-05 15_31_47-Ryujinx 1 0 4847 - Sub Level Zero_ Redux v1 0 (0100E6400BCE8000) (64-bit)](https://user-images.githubusercontent.com/62343878/86542689-21a51580-bed5-11ea-8c77-b1cc7256d45d.png)
![2020-07-05 15_33_41-Ryujinx 1 0 4847 - Sub Level Zero_ Redux v1 0 (0100E6400BCE8000) (64-bit)](https://user-images.githubusercontent.com/62343878/86542691-28cc2380-bed5-11ea-9a8f-961e6be81c26.png)

#### Log file :

[SLZR.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4875709/SLZR.zip)

**Comment by EmulationFanatic** [comment]
Updated
