### ISSUE TITLE
Skullgirls: 2nd Encore - 010046B00DE62000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1965]
#### Current on `master` : 1.0.5049

Game now loads to splash screens and then crashes.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 455
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 143
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 gpuVa, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 97
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 16
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 142
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 68
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots: 

![2020-07-27 17_14_24-Ryujinx 1 0 5049 - Skullgirls_ 2nd Encore v1 0 0 (010046B00DE62000) (64-bit)](https://user-images.githubusercontent.com/62343878/88601004-db068f00-d02c-11ea-88b7-258a847a6c96.png)

#### Log file :

[S2E.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4985063/S2E.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6847

**Comment by EmulationFanatic** [comment]
Updated
