### ISSUE TITLE
Spirit Hunter: NG

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#1968]
#### Current on `master` : 1.0.4864

Game crashes with an missing opcode error.

```
Unhandled exception. Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000031102c (opcode 0xeeb71a40) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
```

#### Log file :

[spirit-hunter-ng.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4890369/spirit-hunter-ng.log)

**Comment by benderscruffy** [comment]
using 1.0.5837
still an issue
[Ryujinx_2020-11-28_17-11-02.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5610320/Ryujinx_2020-11-28_17-11-02.zip)

**Comment by EmulationFanatic** [comment]
Updated
