### ISSUE TITLE
Dusk Diver

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1982]
#### Current on `master` : 1.0.4880

Game plays some audio and then loads to initial splash screen where it promptly crashes.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 285
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 503
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureInfo info, TextureSearchFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 726
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 35
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 219
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 156
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 274
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 143
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 498
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 102
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 180
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-07-09 14_25_32-Ryujinx 1 0 4880 - Dusk Diver v1 0 0 (010011C00E636000) (64-bit)](https://user-images.githubusercontent.com/62343878/87087947-347b5b00-c1f1-11ea-9431-bf0271f4ee48.png)

#### Log file :

[DD.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4899372/DD.zip)

**Comment by benderscruffy** [comment]
using 1.0.7098
goes ingame now but missing ingame graphics (unreal engine)
![ryujinx_capture_2021-11-06_10-55-05](https://user-images.githubusercontent.com/2696404/140604140-032699b4-1a71-45ac-9672-da0e79b003aa.png)
![ryujinx_capture_2021-11-06_16-59-33](https://user-images.githubusercontent.com/2696404/140604144-a49e44d5-684e-4e64-b393-3c5f373799cf.png)
![ryujinx_capture_2021-11-06_16-59-38](https://user-images.githubusercontent.com/2696404/140604145-231aac55-85dc-4a43-b4ee-3a62bc7b381d.png)
![ryujinx_capture_2021-11-06_16-59-43](https://user-images.githubusercontent.com/2696404/140604146-a1d032d9-b0fa-4c50-ae25-5d73f566c2ca.png)
![ryujinx_capture_2021-11-06_17-00-25](https://user-images.githubusercontent.com/2696404/140604147-9c111ffd-9995-4530-8b96-eb140cf80e94.png)
![ryujinx_capture_2021-11-06_17-00-32](https://user-images.githubusercontent.com/2696404/140604148-f5c58942-10fa-4b21-b51c-cbc603693160.png)
