### ISSUE TITLE
Horror Pinball Bundle

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#1985]
#### Current on `master` : 1.0.4880

Crashes while navigating early menus that had a very low FPS.

```
HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.InvalidOperationException: Function entry point is not contained in a block.
   at ARMeilleure.Decoders.Optimizations.TailCallRemover.RunPass(UInt64 entryAddress, List`1 blocks) in C:\projects\ryujinx\ARMeilleure\Decoders\Optimizations\TailCallRemover.cs:line 22
   at ARMeilleure.Decoders.Decoder.Decode(IMemoryManager memory, UInt64 address, ExecutionMode mode, Boolean highCq, Boolean singleBlock) in C:\projects\ryujinx\ARMeilleure\Decoders\Decoder.cs:line 142
   at ARMeilleure.Translation.Translator.Translate(IMemoryManager memory, JumpTable jumpTable, UInt64 address, ExecutionMode mode, Boolean highCq) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 232
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 174
   at ARMeilleure.Instructions.NativeInterface.GetIndirectFunctionAddress(UInt64 address, UInt64 entryAddress) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 426
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-07-09 15_03_19-Ryujinx 1 0 4880 - Horror Pinball Bundle v1 0 0 (0100E4200FA82000) (64-bit)](https://user-images.githubusercontent.com/62343878/87090740-ac4b8480-c1f5-11ea-87ce-b69cec8c3480.png)
![2020-07-09 15_04_29-Ryujinx 1 0 4880 - Horror Pinball Bundle v1 0 0 (0100E4200FA82000) (64-bit)](https://user-images.githubusercontent.com/62343878/87090756-b2416580-c1f5-11ea-8cc5-64287dc84fe5.png)

#### Log file :

[HPB.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4899526/HPB.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6895

**Comment by benderscruffy** [comment]
same status on 1.0.7111

**Comment by EmulationFanatic** [comment]
No longer slow but still crashes with a CPU-related error on 1.1.268
