### ISSUE TITLE
Love Letter from Thief X

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2019]
#### Current on `master` : 1.0.4906

Game crashes on boot with an missing service error.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IAccountServiceForApplication: 131

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00114114 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 10, 0ul> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 10, 0ul> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::BufferClientArgumentType, unsigned int)
   sdk:0x00113dd0 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::IAccountServiceForApplication, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::IAccountServiceForApplication, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_ListOpenContextStoredUsers(nn::sf::OutArray<nn::account::Uid> const&)
   sdk:0x0011203c nn::account::ListPushedOpenUsers(nn::account::Uid*, int)
   sdk:0x00111e48 nn::account::PopOpenUsers(int*, nn::account::UserHandle*, int)
   main:0x001493d0 Sub000000000814d3d0
   main:0x00149318 Sub000000000814d318
   main:0x0013b300 Sub000000000813f300
   main:0x00463668 Sub0000000008467668
   main:0x005a8a1c Sub00000000085aca1c
   main:0x005c47bc Sub00000000085c87bc
   main:0x005a8da8 Sub00000000085acda8
   main:0x005a8264 Sub00000000085ac264
   main:0x005a9548 Sub00000000085ad548
   main:0x005a401c Sub00000000085a801c
   main:0x002a6110 Sub00000000082aa110
   main:0x002ead68 Sub00000000082eed68
   main:0x002eab04 Sub00000000082eeb04
   main:0x0004ec1c nnMain
   sdk:0x000a11ec nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Buffer Information:
        RecvListBuff:
        Position: 0x000000000af7a6f0 Size: 0x0000000000000080

Raw Request Data:
00000000   01 00 10 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  83 00 00 00 00 00 00 00   SFCI···········
00000020   00 00 00 00 00 00 00 00  80 00 00 00 F0 A6 F7 0A   ···········ð¦÷·
00000030   00 00 80 00                                        ···

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1267

#### Log file :

[love-letter-from-thief-x.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4908486/love-letter-from-thief-x.log)

**Comment by Kaizen-mini** [comment]
**Current on `master` : Commit Id *or* Build Version :** 1.0.5391

This game runs smoothly now. The only problem is...most images in-game (apart from menu, such as background, characters) are just displayed as the "Menu" icon image. It even multiplies itself, slides and moves to front/back when different characters speak or the scene changes. And the background behind choices seem to be the choices' pattern itself.

**Screenshots :**

![Ryujinx_AqymxWDKtN](https://user-images.githubusercontent.com/71459954/93720691-d685cf00-fbb4-11ea-8ad5-2651aaf68724.png)
![Ryujinx_7XmIs4EPyf](https://user-images.githubusercontent.com/71459954/93720696-ddacdd00-fbb4-11ea-8462-2c3c85e6d8f9.png)
![Ryujinx_Cy3W4XtoXU](https://user-images.githubusercontent.com/71459954/93720698-e1406400-fbb4-11ea-951b-45a1c2bf5bba.png)
![Ryujinx_yXJqrGX85j](https://user-images.githubusercontent.com/71459954/93720704-e6051800-fbb4-11ea-8b9d-f8831fb44019.png)
![Ryujinx_CK4s4I1kB1](https://user-images.githubusercontent.com/71459954/93720707-e9989f00-fbb4-11ea-979d-a136e36ed053.png)
![Ryujinx_pwaqxgCBFY](https://user-images.githubusercontent.com/71459954/93720710-ec938f80-fbb4-11ea-8f72-9e188ebb4e9e.png)

**Log file :**
[Ryujinx_2020-09-21_02-36-27.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5252484/Ryujinx_2020-09-21_02-36-27.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by chiriesz** [comment]
The graphics are still broken on this game

**Comment by gdkchan** [comment]
> The graphics are still broken on this game

Have you tried with https://github.com/Ryujinx/Ryujinx/pull/3001#issuecomment-1013764503 ? (Assuming you're not trying to run this on macOS).

**Comment by chiriesz** [comment]
I tried it out and so far it's working perfectly!

**Comment by gdkchan** [comment]
> I just want to post a small update. I tried a few more older Voltage games on the latest version as well as this version: [Ryujinx/Ryujinx#3001 (comment)](https://github.com/Ryujinx/Ryujinx/pull/3001#issuecomment-1013764503)
> 
> One such game is My Last First Kiss. The game loads but sometimes the backgrounds are black and other times they show properly. The character sprites often don't update properly with changing expressions and sometimes when another character enters a scene or when a scene changes, the previous speaker's sprite becomes stuck on the screen. There are also times when there's an old sprite stuck on the screen and the current speaker's sprite never displays, meanwhile other times the sprites become layered over each other in a big mess.

Thanks for reporting this issue. It should have been fixed now, if you wish, you can download the newer version on the same link that I posted before.
