### ISSUE TITLE
SEGA AGES Gain Ground

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2021]
#### Current on `master` : 1.0.4906

Game has buggy audio, and crashed after finishing a match with an missing service crash

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00061a20 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> > >::ProcessWithOutObjects(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*)
   sdk:0x000df0b4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::baas::IManagerBase, nn::sf::cmif::client::CmifDomainProxy<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::baas::IManagerForApplication>::_nn_sf_sync_EnsureIdTokenCacheAsync(nn::sf::Out<nn::sf::SharedPointer<nn::account::detail::IAsyncContext>, void>)
   sdk:0x000e9b68 nn::account::EnsureNetworkServiceAccountIdTokenCacheAsync(nn::account::AsyncContext*, nn::account::UserHandle const&)
   main:0x00208950 MAccountNXImpl::OpenNetUser()
   main:0x001841cc LeaderboardImpl::Initialize(PSBObject const*)
   main:0x00125aa4 int Sqrat::SqMember<SQLeaderboard, bool>::Func1<SQPSBObject*>(SQVM*)
   main:0x000f7d0c SQVM::CallNative(SQNativeClosure*, int, int, SQObjectPtr&, bool&)
   main:0x000f6af4 SQVM::Execute(SQObjectPtr&, int, int, int, SQObjectPtr&, unsigned int, SQVM::ExecutionType)
   main:0x000d480c sq_wakeupvm
   main:0x00135be0 sqobject::Thread::_main(long)
   main:0x00135fd8 sqobject::Thread::main(void (*)(sqobject::ObjectInfo, void*), void*)
   main:0x0018ada8 MProcess::OnTask()
   main:0x0018ab6c MParallelTaskSet::OnTask()
   main:0x0018ab6c MParallelTaskSet::OnTask()
   main:0x001c79f4 MLooper::Run(MTask*)
   main:0x00000464 M2Main(int, char**)
   main:0x001e8ff0 M2BootStrap()
   sdk:0x000849bc nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000ac Sub00000000080000ac

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  02 00 00 00 00 00 00 00   SFCI············
00000020   01 00 00 00 00 00 00 00  00 69 74 0B 00 00 04 00   ·········it·····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![07_12_48-14:48:09](https://user-images.githubusercontent.com/62521228/87246769-acdf5780-c44f-11ea-9ee0-d4e7f8afcea1.png)
![07_12_48-14:48:29](https://user-images.githubusercontent.com/62521228/87246770-af41b180-c44f-11ea-852c-d244bd1ecf22.png)
![07_12_48-14:48:35](https://user-images.githubusercontent.com/62521228/87246772-b072de80-c44f-11ea-8e6b-998d47cada45.png)
![07_12_49-14:49:23](https://user-images.githubusercontent.com/62521228/87246773-b1a40b80-c44f-11ea-9f80-9f1410c8d739.png)
![07_12_49-14:49:25](https://user-images.githubusercontent.com/62521228/87246776-b36dcf00-c44f-11ea-92b3-38ecc394d0c7.png)
![07_12_50-14:50:41](https://user-images.githubusercontent.com/62521228/87246778-b5379280-c44f-11ea-9313-de4ecb64584f.png)

#### Log file :

[sega-ages-gain-ground.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4908502/sega-ages-gain-ground.log)

**Comment by SeraUX** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
