### ISSUE TITLE
SEGA AGES Wonder Boy: Monster Land

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2023]
#### Current on `master` : 1.0.4906

Audio is broken, and game crashed when finishing the session with an missing service crash.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x001f14e0 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> > >::ProcessWithOutObjects(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*)
   sdk:0x0003ff74 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::baas::IManagerBase, nn::sf::cmif::client::CmifDomainProxy<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::baas::IManagerForApplication>::_nn_sf_sync_EnsureIdTokenCacheAsync(nn::sf::Out<nn::sf::SharedPointer<nn::account::detail::IAsyncContext>, void>)
   sdk:0x0004af38 nn::account::EnsureNetworkServiceAccountIdTokenCacheAsync(nn::account::AsyncContext*, nn::account::UserHandle const&)
   main:0x0010c660 MAccountNXImpl::OpenNetUser()
   main:0x001162a4 LeaderboardImpl::Initialize(PSBObject const*)
   main:0x001af6c4 int Sqrat::SqMember<SQLeaderboard, bool>::Func1<SQPSBObject*>(SQVM*)
   main:0x0014b85c SQVM::CallNative(SQNativeClosure*, int, int, SQObjectPtr&, bool&)
   main:0x00148a04 SQVM::Execute(SQObjectPtr&, int, int, int, SQObjectPtr&, unsigned int, SQVM::ExecutionType)
   main:0x0012190c sq_wakeupvm
   main:0x00150d40 sqobject::Thread::_main(long)
   main:0x00151144 sqobject::Thread::main(void (*)(sqobject::ObjectInfo, void*), void*)
   main:0x00075d78 MProcess::OnTask()
   main:0x00075b3c MParallelTaskSet::OnTask()
   main:0x00075b3c MParallelTaskSet::OnTask()
   main:0x000b5c50 MLooper::Run(MTask*)
   main:0x00000478 M2Main(int, char**)
   main:0x000d80e0 M2BootStrap()
   sdk:0x0028a72c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  02 00 00 00 00 00 00 00   SFCI············
00000020   01 00 00 00 00 00 00 00  00 C8 21 0C 00 00 04 00   ·········È!·····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![07_12_00-15:00:42](https://user-images.githubusercontent.com/62521228/87246999-4d824700-c451-11ea-8b56-d5c4019b72d1.png)
![07_12_00-15:00:47](https://user-images.githubusercontent.com/62521228/87247001-4eb37400-c451-11ea-9018-62e2a379622c.png)
![07_12_01-15:01:07](https://user-images.githubusercontent.com/62521228/87247003-4fe4a100-c451-11ea-88c2-bc09875aad47.png)
![07_12_01-15:01:15](https://user-images.githubusercontent.com/62521228/87247004-507d3780-c451-11ea-8f68-5e575217b225.png)
![07_12_01-15:01:45](https://user-images.githubusercontent.com/62521228/87247005-5115ce00-c451-11ea-9e37-a428b7f8b0ee.png)
![07_12_02-15:02:12](https://user-images.githubusercontent.com/62521228/87247007-51ae6480-c451-11ea-8fcc-753d6eba6cdc.png)
![07_12_02-15:02:50](https://user-images.githubusercontent.com/62521228/87247008-5246fb00-c451-11ea-9902-8150e265c758.png)
![07_12_03-15:03:57](https://user-images.githubusercontent.com/62521228/87247009-52df9180-c451-11ea-97e4-ab9ee0359a3d.png)

#### Log file :

[sega-ages-wonder-boy-monster-land.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4908528/sega-ages-wonder-boy-monster-land.log)

**Comment by SeraUX** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
