### ISSUE TITLE
STURMWIND EX

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2028]
#### Current on `master` : 1.0.4906

Crashes on launch.

```
HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000010df9e8 (opcode 0xf3fc2170) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1343

#### Log file :

[SE.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4908618/SE.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
No more black boxes but otherwise the same status on 1.0.6910

**Comment by F1ReB4LL** [comment]
## STURMWIND EX

#### Game Update Version : *1.0.0.2*

#### Current on `master` : *1.1.207*

#### Graphics Backend : *Both Vulkan and OpenGL*

*Looks OK, haven't noticed the issues described earlier.

If you reset a current level from the ingame menu, the music stops playing, is it a bug of the game itself, maybe? Happens on another popular emu as well (I don't have a real Switch to test).*

```
Last error returned: No errors shown
```

#### Hardware Specs : 

##### CPU: *i5-11400H*
##### GPU: *NVIDIA RTX 3050*
##### RAM: *24GB*

#### Screenshots :

![ryujinx_stx1](https://user-images.githubusercontent.com/39680140/182972185-19f27dee-fb8d-40f9-b8ac-7f98bad5ee05.png)
![ryujinx_stx2](https://user-images.githubusercontent.com/39680140/182972193-8270155a-7f17-4788-97d1-48431d513ffc.png)
![ryujinx_stx2-2](https://user-images.githubusercontent.com/39680140/182972201-3f775748-f355-4958-a2fc-b4900df3c8ad.png)
![ryujinx_stx3](https://user-images.githubusercontent.com/39680140/182972212-13575077-3caa-482b-ac4f-f15a58bd1af2.png)
![ryujinx_stx4](https://user-images.githubusercontent.com/39680140/182972220-5049a693-d70c-4c1e-b78e-e331c980eec4.png)
![ryujinx_stx5](https://user-images.githubusercontent.com/39680140/182972224-c5387f2c-605a-4c9c-9096-88ff9b11e3de.png)

**Comment by EmulationFanatic** [comment]
Updated, thanks!
