### ISSUE TITLE
SEGA AGES Alex Kidd in Miracle World

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2029]
#### Current on `master` : 1.0.4906

Audio messed up, and crashes when trying to submit the highscore.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00061a20 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> > >::ProcessWithOutObjects(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*)
   sdk:0x000df0b4 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::baas::IManagerBase, nn::sf::cmif::client::CmifDomainProxy<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::baas::IManagerForApplication>::_nn_sf_sync_EnsureIdTokenCacheAsync(nn::sf::Out<nn::sf::SharedPointer<nn::account::detail::IAsyncContext>, void>)
   sdk:0x000e9b68 nn::account::EnsureNetworkServiceAccountIdTokenCacheAsync(nn::account::AsyncContext*, nn::account::UserHandle const&)
   main:0x001db3e0 MAccountNXImpl::OpenNetUser()
   main:0x0015690c LeaderboardImpl::Initialize(PSBObject const*)
   main:0x000f7f64 int Sqrat::SqMember<SQLeaderboard, bool>::Func1<SQPSBObject*>(SQVM*)
   main:0x000ca1cc SQVM::CallNative(SQNativeClosure*, int, int, SQObjectPtr&, bool&)
   main:0x000c8fb4 SQVM::Execute(SQObjectPtr&, int, int, int, SQObjectPtr&, unsigned int, SQVM::ExecutionType)
   main:0x000a6ccc sq_wakeupvm
   main:0x001080a0 sqobject::Thread::_main(long)
   main:0x00108498 sqobject::Thread::main(void (*)(sqobject::ObjectInfo, void*), void*)
   main:0x0015d4e8 MProcess::OnTask()
   main:0x0015d2ac MParallelTaskSet::OnTask()
   main:0x0015d2ac MParallelTaskSet::OnTask()
   main:0x0019a134 MLooper::Run(MTask*)
   main:0x00000468 M2Main(int, char**)
   main:0x001bb730 M2BootStrap()
   sdk:0x000849bc nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000ac Sub00000000080000ac

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  02 00 00 00 00 00 00 00   SFCI············
00000020   01 00 00 00 00 00 00 00  00 49 0D 0B 00 00 04 00   ·········I······

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![07_12_57-15:57:27](https://user-images.githubusercontent.com/62521228/87248295-09934000-c459-11ea-8152-dd443e72d404.png)
![07_12_57-15:57:37](https://user-images.githubusercontent.com/62521228/87248297-0ac46d00-c459-11ea-98f1-4c2671ef6a24.png)
![07_12_57-15:57:50](https://user-images.githubusercontent.com/62521228/87248298-0bf59a00-c459-11ea-854d-242046f366aa.png)
![07_12_57-15:57:54](https://user-images.githubusercontent.com/62521228/87248299-0c8e3080-c459-11ea-9906-16a179ea71d7.png)

#### Log file :

[sega-ages-alex-kidd.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4908615/sega-ages-alex-kidd.log)

**Comment by SeraUX** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
