### ISSUE TITLE
REKT

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2038]
#### Current on `master` : 1.0.4906

Loaded and played fine until the level was finished, which caused a crash.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Error applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Applets\AppletManager.cs:line 32
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\SystemAppletProxy\ILibraryAppletCreator.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Screenshots :

![2020-07-12 10_13_43-Ryujinx 1 0 4906 - REKT v1 9 12 (0100F1900B144000) (64-bit)](https://user-images.githubusercontent.com/62343878/87251589-fc129180-c429-11ea-8abd-6d5d20e7e8d4.png)
![2020-07-12 10_14_55-Ryujinx 1 0 4906 - REKT v1 9 12 (0100F1900B144000) (64-bit)](https://user-images.githubusercontent.com/62343878/87251592-fddc5500-c429-11ea-9d67-d9bf0ac60aca.png)
![2020-07-12 10_15_16-Ryujinx 1 0 4906 - REKT v1 9 12 (0100F1900B144000) (64-bit)](https://user-images.githubusercontent.com/62343878/87251593-ff0d8200-c429-11ea-9c49-50fb6c74eabc.png)
![2020-07-12 10_15_45-Ryujinx 1 0 4906 - REKT v1 9 12 (0100F1900B144000) (64-bit)](https://user-images.githubusercontent.com/62343878/87251595-003eaf00-c42a-11ea-97c8-e1d95f3031ca.png)
![2020-07-12 10_16_36-Ryujinx 1 0 4906 - REKT v1 9 12 (0100F1900B144000) (64-bit)](https://user-images.githubusercontent.com/62343878/87251596-02a10900-c42a-11ea-8127-80311463af57.png)
![2020-07-12 10_16_50-Ryujinx 1 0 4906 - REKT v1 9 12 (0100F1900B144000) (64-bit)](https://user-images.githubusercontent.com/62343878/87251597-046acc80-c42a-11ea-8a53-579817be48ad.png)
![2020-07-12 10_17_42-](https://user-images.githubusercontent.com/62343878/87251603-07fe5380-c42a-11ea-900d-e80763ae2395.png)

#### Log file :

[REKT.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4908828/REKT.zip)

**Comment by EmulationFanatic** [comment]
Updated
