### ISSUE TITLE
Detective Jinguji Saburo Prism of Eyes

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2040]
#### Current on `master` : 1.0.4906

Game crashes with an missing opcode error on boot.

```
Unhandled exception. Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000893c614 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
```

#### Log file :

[Detective Jinguji Saburo Prism of Eyes.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4909337/Detective.Jinguji.Saburo.Prism.of.Eyes.log)

**Comment by Kaizen-mini** [comment]
Hello, I tried this game on Ryujinx latest version. Hopefully someone from the team can have a look and update the labels!

**Game Update Version :** 1.0.2

**Current on `master` : Commit Id *or* Build Version :** 1.0.5480

Game runs fine, everything works but there can be a little lag here and there.

**Hardware Specs :** 

CPU: i5-6600K
GPU: NVIDIA GeForce GT 730
RAM: 16GB

**Screenshots :**

![Ryujinx_YNosIryR6q](https://user-images.githubusercontent.com/71459954/94968043-65d2a100-052a-11eb-8aa9-9953cafb0144.png)
![Ryujinx_Jm1cZBIeb8](https://user-images.githubusercontent.com/71459954/94968053-69febe80-052a-11eb-8b6e-5ed3c424b793.png)
![Ryujinx_uHTpMl2Ej5](https://user-images.githubusercontent.com/71459954/94968066-708d3600-052a-11eb-9762-4ae2b7c54119.png)
![Ryujinx_wZp3dNUj9G](https://user-images.githubusercontent.com/71459954/94968103-80a51580-052a-11eb-83a2-8f76503934bc.png)
![Ryujinx_wt6tmFG2iU](https://user-images.githubusercontent.com/71459954/94968160-a29e9800-052a-11eb-8d89-7efd906172fc.png)
![Ryujinx_R5ozSvfpXS](https://user-images.githubusercontent.com/71459954/94968118-87338d00-052a-11eb-9c41-7d0a1fc7ad8b.png)
![Ryujinx_YHjR0zEPRc](https://user-images.githubusercontent.com/71459954/94968193-b0541d80-052a-11eb-9def-3856ea1d3367.png)
![Ryujinx_BWb5gRPpDc](https://user-images.githubusercontent.com/71459954/94968234-c1049380-052a-11eb-924a-d3af5c8253c8.png)
![Ryujinx_4LWLdpL5mx](https://user-images.githubusercontent.com/71459954/94968242-c661de00-052a-11eb-90d3-4f6b91004069.png)
![Ryujinx_1PDxABlCiN](https://user-images.githubusercontent.com/71459954/94968300-dc6f9e80-052a-11eb-9c23-654f3a7c7f69.png)
![Ryujinx_U4d9KqUf6V](https://user-images.githubusercontent.com/71459954/94968310-e1345280-052a-11eb-8c75-69740353fd62.png)
![Ryujinx_ctA0s4XUUy](https://user-images.githubusercontent.com/71459954/94968335-eabdba80-052a-11eb-8352-5a4d6c676ab5.png)

**Log file :**
[Ryujinx_2020-10-03_01-30-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5320188/Ryujinx_2020-10-03_01-30-46.log)

**Comment by SeraUX** [comment]
Updated
