### ISSUE TITLE
Gunka o haita neko

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2047]
#### Current on `master` : 1.0.4914

Crashes with an missing service error while booting.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ISelfController: 69

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0007457c nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<1ul, 1ul, 0l> >, 0ul, 1ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<1ul, 1ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<1ul, 1ul>, unsigned int)
   sdk:0x0012c774 nn::sf::cmif::client::detail::CmifProxyImpl<nn::am::service::ISelfController, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::am::service::ISelfController, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_IsAutoSleepDisabled(nn::sf::Out<bool, void>)
   sdk:0x00143360 nn::applet::IsAutoSleepDisabled()
   main:0x001c0c5c Sub00000000081c4c5c
   main:0x001c1c48 Sub00000000081c5c48
   main:0x00017f18 Sub000000000801bf18
   main:0x001b9da4 Sub00000000081bdda4
   sdk:0x000d4468 nn::os::detail::CallFiberFunction(nn::os::FiberType* (*)(void*), void*)

Raw Request Data:
00000000   01 00 10 00 06 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  45 00 00 00 00 00 00 00   SFCI····E·······
00000020   53 46 43 49 01 00 00 00  01 00 00 00 00 00 00 00   SFCI············

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Log file :

[gunka-o-haita-neko.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4912325/gunka-o-haita-neko.log)

**Comment by SeraUX** [comment]
Updated
