### ISSUE TITLE
Labyrinth of the Witch

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2050]
#### Current on `master` : 1.0.4914

Game played well during the first floor, but crashed soon after getting to the second floor with an missing opcode error.

```
Unhandled exception. Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000009450a94 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
Aborted (core dumped)
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1340

#### Screenshots :

![07_13_33-17:33:07](https://user-images.githubusercontent.com/62521228/87324161-028b3100-c530-11ea-9d84-2f75c682054f.png)
![07_13_34-17:34:19](https://user-images.githubusercontent.com/62521228/87324164-04ed8b00-c530-11ea-8e6c-b38995362b45.png)
![07_13_34-17:34:34](https://user-images.githubusercontent.com/62521228/87324167-05862180-c530-11ea-8c24-822fe685751b.png)
![07_13_34-17:34:38](https://user-images.githubusercontent.com/62521228/87324170-061eb800-c530-11ea-843b-591bca99a0c6.png)
![07_13_34-17:34:47](https://user-images.githubusercontent.com/62521228/87324173-06b74e80-c530-11ea-928c-0777910a7442.png)
![07_13_34-17:34:52](https://user-images.githubusercontent.com/62521228/87324175-074fe500-c530-11ea-9fde-c4afd8d8782c.png)
![07_13_35-17:35:15](https://user-images.githubusercontent.com/62521228/87324178-07e87b80-c530-11ea-8e35-f563adf07b01.png)
![07_13_35-17:35:58](https://user-images.githubusercontent.com/62521228/87324181-08811200-c530-11ea-8f32-cfdb1506cac9.png)
![07_13_36-17:36:30](https://user-images.githubusercontent.com/62521228/87324182-0919a880-c530-11ea-919a-390c63f124ec.png)

#### Log file :

[labyrinth-of-the-witch.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4913514/labyrinth-of-the-witch.log)

**Comment by EmulationFanatic** [comment]
Updated
