### ISSUE TITLE
GRISAIA PHANTOM TRIGGER 01&02

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2058]
#### Current on `master` : 1.0.4921

Game crashes on boot with an missing service error.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ISelfController: 100

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0007d570 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l> >, 1ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<1ul, 1ul, 0l> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<1ul, 1ul, void>, unsigned int)
   sdk:0x0012c888 nn::sf::cmif::client::detail::CmifProxyImpl<nn::am::service::ISelfController, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::am::service::ISelfController, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_SetAlbumImageTakenNotificationEnabled(bool)
   sdk:0x0029a120 nn::oe::EnableAlbumImageTakenNotification()
   main:0x001dd1f0 nnMain
   sdk:0x000a1d9c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Raw Request Data:
00000000   01 00 11 00 06 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  64 00 00 00 00 00 00 00   SFCI····d·······
00000020   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000030   00 00 00 00                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1065

#### Log file :

[grisaia-phantom-trigger.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4914914/grisaia-phantom-trigger.log)

**Comment by SeraUX** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
