### ISSUE TITLE
STAY COOL, KOBAYASHI-SAN! A RIVER RANSOM STORY

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2060]
#### Current on `master` : 1.0.4921

Loaded and played at a high FPS until crashing midway through the first level.

```
mulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.VoiceContext.GetBufferData(MemoryManager memory, Int32 maxSamples, Int32& samplesCount) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\VoiceContext.cs:line 70
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.AppendMixedBuffer(Int64 tag) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 372
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.UpdateAudio() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 346
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.RequestUpdateAudioRenderer(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 228
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Screenshots :

![2020-07-13 14_30_50-Ryujinx 1 0 4921 - STAYCOOL,KOBAYASHI-SAN!_A RIVER CITY RANSOM STORY v1 0 0 (010](https://user-images.githubusercontent.com/62343878/87351492-c0a1c100-c516-11ea-8c01-0490e9f2f4c3.png)
![2020-07-13 14_31_05-Ryujinx 1 0 4921 - STAYCOOL,KOBAYASHI-SAN!_A RIVER CITY RANSOM STORY v1 0 0 (010](https://user-images.githubusercontent.com/62343878/87351494-c13a5780-c516-11ea-86a7-2fa274ff668d.png)
![2020-07-13 14_33_39-Ryujinx 1 0 4921 - STAYCOOL,KOBAYASHI-SAN!_A RIVER CITY RANSOM STORY v1 0 0 (010](https://user-images.githubusercontent.com/62343878/87351497-c26b8480-c516-11ea-922a-0db1f322b977.png)
![2020-07-13 14_34_11-Ryujinx 1 0 4921 - STAYCOOL,KOBAYASHI-SAN!_A RIVER CITY RANSOM STORY v1 0 0 (010](https://user-images.githubusercontent.com/62343878/87351500-c4cdde80-c516-11ea-9655-354fd13046fe.png)
![2020-07-13 14_34_17-Ryujinx 1 0 4921 - STAYCOOL,KOBAYASHI-SAN!_A RIVER CITY RANSOM STORY v1 0 0 (010](https://user-images.githubusercontent.com/62343878/87351503-c5667500-c516-11ea-919d-c8eca6e8e37d.png)
![2020-07-13 14_34_20-Ryujinx 1 0 4921 - STAYCOOL,KOBAYASHI-SAN!_A RIVER CITY RANSOM STORY v1 0 0 (010](https://user-images.githubusercontent.com/62343878/87351505-c5ff0b80-c516-11ea-8fb1-a344abd18a16.png)
![2020-07-13 14_35_30-Ryujinx 1 0 4921 - STAYCOOL,KOBAYASHI-SAN!_A RIVER CITY RANSOM STORY v1 0 0 (010](https://user-images.githubusercontent.com/62343878/87351507-c697a200-c516-11ea-9fb7-44d526aa7fd8.png)
![2020-07-13 14_36_08-Ryujinx 1 0 4921 - STAYCOOL,KOBAYASHI-SAN!_A RIVER CITY RANSOM STORY v1 0 0 (010](https://user-images.githubusercontent.com/62343878/87351520-c9929280-c516-11ea-9a2d-fb62a1b24b39.png)
![2020-07-13 14_37_08-Ryujinx 1 0 4921 - STAYCOOL,KOBAYASHI-SAN!_A RIVER CITY RANSOM STORY v1 0 0 (010](https://user-images.githubusercontent.com/62343878/87351522-cac3bf80-c516-11ea-904c-edcb11e6f26a.png)
![2020-07-13 14_37_45-Ryujinx 1 0 4921 - STAYCOOL,KOBAYASHI-SAN!_A RIVER CITY RANSOM STORY v1 0 0 (010](https://user-images.githubusercontent.com/62343878/87351528-cb5c5600-c516-11ea-9b78-aded7b735830.png)
![2020-07-13 14_38_07-Ryujinx 1 0 4921 - STAYCOOL,KOBAYASHI-SAN!_A RIVER CITY RANSOM STORY v1 0 0 (010](https://user-images.githubusercontent.com/62343878/87351531-cbf4ec80-c516-11ea-824d-ccbc698d5411.png)
![2020-07-13 14_39_10-](https://user-images.githubusercontent.com/62343878/87351533-cc8d8300-c516-11ea-81eb-599e33166dfd.png)

#### Log file :

[SCKARRS.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4914998/SCKARRS.log)

**Comment by EmulationFanatic** [comment]
Updated
