### ISSUE TITLE
OMG Zombies!

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2069]
#### Current on `master` : 1.0.4921

crashes with an error every time on boot.

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.OpenGL.Pipeline.DrawIndexed(Int32 indexCount, Int32 instanceCount, Int32 firstIndex, Int32 firstVertex, Int32 firstInstance) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Pipeline.cs:line 330
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 119
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 105
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 495
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 217
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 101
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CachedMacro.Execute(Int32[] mme, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 73
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 213
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 309
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 217
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[omg-zombies.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4916730/omg-zombies.log)

**Comment by benderscruffy** [comment]
crashes on the title screen now

**Comment by benderscruffy** [comment]
crashes on the title screen now

**Comment by SeraUX** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
