### ISSUE TITLE
Saboteur II: Avenging Angel

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2072]
#### Current on `master` : 1.0.4921

Game crashes on launch with an missing opcode error.

```
Unhandled exception. Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000087029e4 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1340

#### Log file :

[saboteur-ii-avenging-angel.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4916992/saboteur-ii-avenging-angel.log)

**Comment by SeraUQ** [comment]
Same status on 1.0.6421
