### ISSUE TITLE
Speed Brawl

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2077]
#### Current on `master` : 1.0.4921

Game crashes on boot.

```
00:00:57.835 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: The information requested is unavailable on the current platform.
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties.get_IsDynamicDnsEnabled()
   at Ryujinx.HLE.HOS.Services.Nifm.StaticService.Types.DnsSetting..ctor(IPInterfaceProperties interfaceProperties) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nifm\StaticService\Types\DnsSetting.cs:line 16
   at Ryujinx.HLE.HOS.Services.Nifm.StaticService.IGeneralService.GetCurrentIpConfigInfo(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nifm\StaticService\IGeneralService.cs:line 90
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Log file :

[speed-brawl.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4917628/speed-brawl.log)

**Comment by AcK77** [comment]
Updated
