### ISSUE TITLE
The Legend of Zelda: Links Awakening

### ISSUE THREAD

**Issue by plantysnake** [Ryujinx/Ryujinx-Games-List#208]
#### Current on `master` :

Build Version : 1.0.3164

*Describe the current game state here.*

Nothing.

## Last error returned:
```
CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> SoundIOSharp.SoundIOException: incompatible device
   at SoundIOSharp.SoundIOOutStream.Open() in C:\projects\ryujinx\Ryujinx.Audio\Native\libsoundio\SoundIOOutStream.cs:line 190
   at Ryujinx.Audio.SoundIo.SoundIoAudioTrack.Open(Int32 sampleRate, Int32 channelCount, ReleaseCallback callback, SoundIOFormat format) in C:\projects\ryujinx\Ryujinx.Audio\Renderers\SoundIo\SoundIoAudioTrack.cs:line 115
   at Ryujinx.Audio.SoundIoAudioOut.OpenTrack(Int32 sampleRate, Int32 channels, ReleaseCallback callback) in C:\projects\ryujinx\Ryujinx.Audio\Renderers\SoundIo\SoundIoAudioOut.cs:line 85
   at Ryujinx.HLE.HOS.Services.Audio.IAudioOutManager.OpenAudioOutImpl(ServiceCtx context, Int64 sendPosition, Int64 sendSize, Int64 receivePosition, Int64 receiveSize) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\IAudioOutManager.cs:line 150
   at Ryujinx.HLE.HOS.Services.Audio.IAudioOutManager.OpenAudioOut(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\IAudioOutManager.cs:line 34
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 154
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Log file :

[Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/3801873/Ryujinx.log)

**Comment by Thog** [comment]
Edited the issue to reflect the issue found in the error log.

**Comment by B3astTech** [comment]
Updated

**Comment by BennyAlex** [comment]
hello,
my game starts but I have blackscreen, can only hear audio.
The title screen doesnt show up and pressing L+R dosnt work too.

**Comment by Korashia** [comment]
Game boots and was able to pass the intro graphics are quite off 
![Ryujinx_D2asSfPTFG](https://user-images.githubusercontent.com/43104317/90728536-e8084e00-e279-11ea-8590-c83a17eab0fd.png)

**Comment by resadent** [comment]
The game is working great, almost fullspeed (50-55fps) on a pc with nvidia gtx 1060 and amd r5 3600. Ive only played game for ~10 minutes, only gfx error Ive found is the chain chomp missing.

**Comment by EliasM108** [comment]
![image](https://user-images.githubusercontent.com/51413997/99952540-7ebc3d80-2d88-11eb-809b-e07596f32d7f.png)
![image](https://user-images.githubusercontent.com/51413997/99952551-8380f180-2d88-11eb-9390-137dd263f829.png)

Log file:
[Ryujinx_2020-11-23_12-28-05.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5582310/Ryujinx_2020-11-23_12-28-05.log)

The gameplay is slow when wandering in areas with a lot of enemies. The screen flickers constantly and breaks graphics. The blur bug is not present any more.

**Comment by bigfatbrowncat** [comment]
Ryujinx Version: 1.0.6260

Currently the game is flickering in the first room. And after some time it crashes...

The log:
[Ryujinx_1.0.6260_2021-01-09_17-13-57.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5791298/Ryujinx_1.0.6260_2021-01-09_17-13-57.log)

The flickering video:
https://user-images.githubusercontent.com/317189/104095168-648dde80-52a6-11eb-8a43-f7d79976ff5f.mp4

The firmware is 10.0.0

**Comment by GamerzHell9137** [comment]
So far so good!
Only thing is ChompChomps being white and the game sometimes freezes while the audio is still going.

``
00:04:11.045 |I| Ptc Save: Saved Profiling Info (size: 158157 bytes, profiled functions: 50426).
00:04:13.832 |I| HLE.OsThread.5 ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:04:14.176 |I| HLE.GuestThread.30 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x001824a0 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   sdk:0x00182564 Sub000000000aeb9564
   sdk:0x00182600 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   sdk:0x003399c8 nn::os::detail::InternalConditionVariableImplByHorizon::Wait(nn::os::detail::InternalCriticalSection*)
   sdk:0x0032e464 nn::os::WaitConditionVariable(nn::os::ConditionVariableType*, nn::os::MutexType*)
   sdk:0x004b1184 std::__1::__libcpp_condvar_wait(std::__libcxx_shim::__libcxx_shim_ver_1::__libcxx_shim_condition_variable*, std::__libcxx_shim::__libcxx_shim_ver_1::__libcxx_shim_mutex*)
   sdk:0x00460618 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)
   main:0x00008c38 Sub000000000800cc38
   main:0x00006830 Sub000000000800a830
   main:0x00008494 Sub000000000800c494
   sdk:0x003344b8 Sub000000000b06b4b8
   sdk:0x00338984 Sub000000000b06f984
   ??? Sub0000000000000000


00:04:14.177 |W| HLE.GuestThread.15 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:04:14.177 |W| HLE.GuestThread.17 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:04:14.177 |W| HLE.GuestThread.18 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:04:14.177 |W| HLE.GuestThread.19 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:04:14.177 |W| HLE.GuestThread.20 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:04:14.177 |W| HLE.GuestThread.24 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:04:14.177 |W| HLE.GuestThread.27 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:04:14.177 |W| HLE.GuestThread.29 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:04:14.177 |W| HLE.GuestThread.31 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:04:14.177 |W| HLE.GuestThread.33 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.``

**Comment by megajosewii23** [comment]
The  chain chomp is white but the rest of the game render fine, but with Vsync active the game runs slow, witthout it runs fine 
![Publish Screenshot 2021 02 15 - 19 50 28 24](https://user-images.githubusercontent.com/79127714/108018381-6d23b400-6fcc-11eb-8e54-5d3734467f16.png)PC spects i3 9100f,GTX 1650,16 ram DDR4 3000mhz

**Comment by trlkly** [comment]
Testing using the 1.0.0 version of the game. 

I do not see any differences from @megajosewii23's report. The texture for Bow-Wow (the chain chomp to the left of the house at the beginning of the game) is still white instead of black, and Vsync must be disabled to get decent framerates, but otherwise the game runs fine. 

(The game shows that it's running at as low as 30fps, but the actual gameplay seems to be running at full speed, except whenever it has to load a shader.) 

![image](https://user-images.githubusercontent.com/5460654/115240867-cb146b00-a0e5-11eb-9811-1ec021571ce8.png)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by AlastorAlex** [comment]
YO this is Fixed! 
![imagen](https://user-images.githubusercontent.com/70239365/133951938-2668a373-9c69-42bd-9e54-1cfc07444008.png)

**Comment by AlastorAlex** [comment]
Can confirm i have teh Same issues as mrjo118

**Comment by mrjo118** [comment]
There is also an issue with the shadows on Tal Tal Heights outside the dungeon for Level 7. See attached video. This looks to have been an issue in v1.0.6892 as well as in v1.0.7073. This happens all the time regardless of whether PPTC cache is enabled or not

[Uploading bandicam 2021-10-17 23-48-15-091.zip…]()

**Comment by Eatitup86** [comment]
Latest version seems to cause the entire game to run at an unplayable framerate.

**Comment by Immersion95** [comment]
It is crashing with AMD Vulkan and increased scaling. It works greatly at native.

**Comment by yasumi2136** [comment]
whether with Vulkan or OpenGL, the emulator crashes at boot.

Ryujinx version : 1.1.309
Graphic cards : NVIDIA GeForce GTX 1080
CPU : AMD Ryzen 7 1800X
RAM : 24GB

**Comment by EmulationFanatic** [comment]
> whether with Vulkan or OpenGL, the emulator crashes at boot.
> 
> Ryujinx version : 1.1.309 Graphic cards : NVIDIA GeForce GTX 1080 CPU : AMD Ryzen 7 1800X RAM : 24GB

Come to Discord for support - this game works fine.

**Comment by Immersion95** [comment]
> > whether with Vulkan or OpenGL, the emulator crashes at boot.
> > Ryujinx version : 1.1.309 Graphic cards : NVIDIA GeForce GTX 1080 CPU : AMD Ryzen 7 1800X RAM : 24GB
> 
> Come to Discord for support - this game works fine.

It definitely doesn't work on Vulkan - Res x 2 - AMD GPU 6xx0 cards.

**Comment by EmulationFanatic** [comment]
> > > whether with Vulkan or OpenGL, the emulator crashes at boot.
> > > Ryujinx version : 1.1.309 Graphic cards : NVIDIA GeForce GTX 1080 CPU : AMD Ryzen 7 1800X RAM : 24GB
> > 
> > 
> > Come to Discord for support - this game works fine.
> 
> It definitely doesn't work on Vulkan - Res x 2 - AMD GPU 6xx0 cards.

Yes, we saw your earlier report. Whether a game "works fine" or not is indicative of testing on default settings. Res scaling is an enhancement not included on the Switch console therefore it is not included in compatibility testing. You are, of course, free to continue posting comments about res scaling issues for any games you notice it on.

**Comment by loureirolino** [comment]
> > > > whether with Vulkan or OpenGL, the emulator crashes at boot.
> > > > Ryujinx version : 1.1.309 Graphic cards : NVIDIA GeForce GTX 1080 CPU : AMD Ryzen 7 1800X RAM : 24GB
> > > 
> > > 
> > > Come to Discord for support - this game works fine.
> > 
> > 
> > It definitely doesn't work on Vulkan - Res x 2 - AMD GPU 6xx0 cards.
> 
> Yes, we saw your earlier report. Whether a game "works fine" or not is indicative of testing on default settings. Res scaling is an enhancement not included on the Switch console therefore it is not included in compatibility testing. You are, of course, free to continue posting comments about res scaling issues for any games you notice it on.

Passing by justo to inform I'm having the same issues as well. I'm using default config with the regular resolution (720p/1080p) on Vulkan API, the game just crashes before starting. Build 1.1.328 on AMD graphics card 22.10.1

**Comment by MetrosexualGarbodor** [comment]
@loureirolino a crash report is worthless without a log.

**Comment by MetrosexualGarbodor** [comment]
Updated.

**Comment by Immersion95** [comment]
> It is crashing with AMD Vulkan and increased scaling. It works at native.
> 
> [Zelda.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9559363/Zelda.log)

It works with Intel iGPU fyi but not AMD.

**Comment by Gimpy3887** [comment]
## The Legend of Zelda: Link's Awakening

#### Game Update Version: 1.01

#### Emulator Build Version: 1.1.0-MACOS1

#### Graphics Backend: Vulkan

#### Hardware Specs: 

##### CPU: M1
##### GPU: Integrated 8-Core
##### RAM: 16GB

The game tends to lag; this occurs very early on during the opening cutscene where the game transitions to the mountains, later in the gameplay it continues to be a chronic issue exchanging between speed ups and lag. You can see it happening when I cut the grass in the field.

#### Video:

https://user-images.githubusercontent.com/26771892/204184645-3bf102c3-b07d-492c-8ab6-60ce81fcf06a.mp4

#### Log file:
[Ryujinx_ 1.1.0-macos1_2022-11-27_21-22-37.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10100151/Ryujinx_.1.1.0-macos1_2022-11-27_21-22-37.log)

**Comment by wraithxiv** [comment]
Using Ryujinx on 14" M1 Mac Book Pro
16 Gigs of memory
MacOS 13.0.1

The game locks up during the final cut scene.  Here is a screen shot where it freezes everytime.
![Screen Shot 2022-12-06 at 12 44 19 AM](https://user-images.githubusercontent.com/5904675/206103127-98317285-3910-417e-88b3-23ea0c2d1b63.png)

Here is my log file.
[Ryujinx_ 1.1.0-macos1_2022-12-06_23-44-58.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10173312/Ryujinx_.1.1.0-macos1_2022-12-06_23-44-58.log)

This may not seem like a big issue, but I would like to eventually be able to do the end of game save.
This might matter more for players going for the "Perfect" ending.

**Comment by Immersion95** [comment]
> > It is crashing with AMD Vulkan and increased scaling. It works at native.
> > [Zelda.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9559363/Zelda.log)
> 
> It works with Intel iGPU fyi but not AMD.

It now renders perfectly if upscaled in AMD. Only remaining problem for me is the choppy opening scene

**Comment by Jay-M1** [comment]
Using Ryujinx 1.1.977 on Windows 10 System

Specs:
Ryzen 5 3600
GTX 1060 6GB
16 GB RAM

Link's Awakening Game version 1.0.1

I am halfway through the story, and the game runs very smoothly at consistent 60fps. There was not a single crash yet.
