### ISSUE TITLE
Mary Skelter 2

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2081]
#### Current on `master` : 1.0.4921

Game loads and plays at a high FPS.

#### Screenshots :

![2020-07-14 05_52_56-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423696-f20ea100-c597-11ea-91bc-a41620ff4ad4.png)
![2020-07-14 05_53_02-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423699-f2a73780-c597-11ea-9ff1-03cc8b92a24b.png)
![2020-07-14 05_53_37-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423705-f3d86480-c597-11ea-87df-19010ca615b4.png)
![2020-07-14 05_53_40-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423707-f470fb00-c597-11ea-8cd7-66a82517a6eb.png)
![2020-07-14 05_53_45-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423710-f5a22800-c597-11ea-995a-cfa74429314f.png)
![2020-07-14 05_53_56-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423720-fc309f80-c597-11ea-9957-d98500c63bf0.png)
![2020-07-14 05_54_40-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423743-0783cb00-c598-11ea-8800-b4521598d496.png)
![2020-07-14 05_54_53-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423761-110d3300-c598-11ea-812e-3928b0f79c4a.png)
![2020-07-14 05_55_45-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423771-15395080-c598-11ea-85c8-87ef9de3ca74.png)
![2020-07-14 05_56_57-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423795-1d918b80-c598-11ea-9174-e938cc3eed41.png)
![2020-07-14 05_57_08-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423808-25e9c680-c598-11ea-991f-134545f5c998.png)
![2020-07-14 05_57_20-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423835-300bc500-c598-11ea-8562-1e872aa8a95a.png)
![2020-07-14 05_57_28-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423855-3ac65a00-c598-11ea-91a4-7e3e3eb57dd2.png)
![2020-07-14 05_59_27-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423871-4285fe80-c598-11ea-9661-bec6038089a2.png)
![2020-07-14 06_04_06-Ryujinx 1 0 4921 - Mary Skelter 2 v1 0 0 (01003DE00C95E000) (64-bit)](https://user-images.githubusercontent.com/62343878/87423886-4c0f6680-c598-11ea-87c4-703492b85b9c.png)

#### Log file :

[MS2.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4918687/MS2.zip)

**Comment by anon342** [comment]
Game Version: 1.0.0 and 1.0.4 (tested with both)
Ryujinx Version : 1.0.6976

Ryujinx consistently crashes during dialogue shortly after the start of chapter 2.

Hardware Specs :
CPU: i5-6500
GPU: NVIDIA GTX 770
RAM: 16GB


00:10:55.779 |E| HLE.GuestThread.14 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFE940219F000.
00:10:55.796 |E| HLE.GuestThread.14 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

[Ryujinx_1.0.6976_2021-08-02_12-01-14.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6918371/Ryujinx_1.0.6976_2021-08-02_12-01-14.log)
[Ryujinx_1.0.6976_2021-08-02_11-11-19.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6918372/Ryujinx_1.0.6976_2021-08-02_11-11-19.log)

**Comment by Stepperer** [comment]
Same error here at the start of Ch2

Ryujinx Version : 1.0.7096


Hardware Specs :
CPU: Ryzen 5 2600
GPU: NVIDIA GTX 1060
RAM: 16GB

00:30:37.608 |I| HLE.GuestThread.16 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000008
	X[01]:	0x0000001199b22df0 (SP:-0x0090)
	X[02]:	0x0000000000000002
	X[03]:	0x000000102e179250
	X[04]:	0x0000000000000438
	X[05]:	0x0000000000000001
	X[06]:	0x0000000000000001
	X[07]:	0x0000000000000000
	X[08]:	0x00000000080d0a40 (main:0xcca40)	=> 
	X[09]:	0x0000000000000001
	X[10]:	0x0000000000000001
	X[11]:	0x0000000000000003
	X[12]:	0x000000003f800000
	X[13]:	0x000000003f800000
	X[14]:	0x000000003f800000
	X[15]:	0x0000000000000000
	X[16]:	0x0000001199b22b10 (SP:-0xfffffffffffffdb0)
	X[17]:	0x0000001199b22b18 (SP:-0xfffffffffffffdb8)
	X[18]:	0x0000001199b22b24 (SP:-0xfffffffffffffdc4)
	X[19]:	0x0000000000000002
	X[20]:	0x0000001199b22df0 (SP:-0x0090)
	X[21]:	0x0000001199b22df0 (SP:-0x0090)
	X[22]:	0x0000000000000001
	X[23]:	0x0000000008d82a80
	X[24]:	0x0000000000000004
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x0000001199b22da0 (SP:-0x0040)
	LR:	0x00000000080d0a78 (main:0xcca78)	=> 
	SP:	0x0000001199b22d60 (SP)
	PC:	0x0000000000000000


00:30:37.608 |E| HLE.GuestThread.16 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000001808D2A000.
00:30:37.636 |E| HLE.GuestThread.16 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by MutantAura** [comment]
Can either of you post a save file with the steps required to reproduce?

**Comment by Stepperer** [comment]
https://drive.google.com/file/d/1Ck42h_XM3KBTleJkEX8lXcsNtLCtG4wp/view?usp=sharing

Load FILE2 Ch2. NEW LIBER
Go to Rescue Center, where EVENT tag is
View two long cut scenes. Unfortunately you cannot save after the first, game loads the next one not giving you a chance to save (
After morning cames and Otsu starts to talk with Hameln, the game will blink and crash

**Comment by anon342** [comment]
A workaround is skipping all dialogue/cutscenes with a brown filter (not fastfowarding). 

I am up to the final boss and the game seems stable everywhere except during these "brown filter" dialogue bits which will flicker and cause a crash with the above error. Increasing page file, using 6GB ram hack, and changing render to vulkan all seemed to have no effect on the crash.

**Comment by LuxEtUmbra0** [comment]
The bug still exists in 1.0.7135. From my tests on another cutscene (chapter 2, after returning to the base with Little Mermaid, skip the first 2 cutscenes, and on the 3rd it's where where it happens) using "System->Memory Manager Mode": Software have the better chances to see the entire cutscene without crashing, the other options always crashed for me.

Using the attached save file it's easily reproducible, just navigates the menu to base and watch the cutscenes, the 1st and 2nd can be skipped.

[MS2saveCrash.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/7836041/MS2saveCrash.zip)

**Comment by Marko944** [comment]
I'm facing the same issue: when a flashback cutscene starts (normal cutscene with brown filter), after some seconds (<10s usually) it crashes, I have attached both logs from
Steam Deck (it crashes later): [Ryujinx_1.1.121_2022-05-16_08-19-50.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8699463/Ryujinx_1.1.121_2022-05-16_08-19-50.log)
PC with AMD GPU (it crashes almost as soon as it starts): [Ryujinx_1.1.129_2022-05-16_12-42-38.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8699468/Ryujinx_1.1.129_2022-05-16_12-42-38.log)
You can see the version number on both logs file names.
 
I don't think it's important but the same issue is present on Yuzu, it doesn't crashes but it hangs infinitely.

Here is a savegame: [0.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/8699482/0.zip)
The issue is that you can't just load the savegame and reproduce the crash, you are forced to play 5/10 minutes as there are no closer save points.
Every cutscene can be skipped with R until you get the flashback one where it crashes. There is a walkthrough on youtube [here](https://youtu.be/qfWaFBPB6vs?list=PLajS2QRqbVNRQ6XxJ9QrCJNhFLPRCk1S5&t=2251) that shows where to start from the attached savegame and [this other](https://youtu.be/X2ZavRyxjsM?list=PLajS2QRqbVNRQ6XxJ9QrCJNhFLPRCk1S5&t=204) where it crashes.


![Ryujinx_ueJ91GlA5A](https://user-images.githubusercontent.com/866831/168588381-85c63520-1247-4a6a-abc4-fa588894019c.jpg)

**Comment by EmulationFanatic** [comment]
Needs an update/re-test.

**Comment by Muji26** [comment]
Tested it today. Still crashes at the same scene.

**Comment by Cerzel** [comment]
The problem is still present as of Ryujinx version 1.1.1011.
