### ISSUE TITLE
Juicy Realm

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2083]
#### Current on `master` : 1.0.4921

Game loads and renders in single digit FPS, making the game very difficult to play.

#### Screenshots :

![2020-07-14 06_14_11-Ryujinx 1 0 4921 - Juicy Realm v2 3 0 (0100C7600F654000) (64-bit)](https://user-images.githubusercontent.com/62343878/87424802-d4423b80-c599-11ea-9cc6-00c6f1529bfb.png)
![2020-07-14 06_15_11-Ryujinx 1 0 4921 - Juicy Realm v2 3 0 (0100C7600F654000) (64-bit)](https://user-images.githubusercontent.com/62343878/87424813-dc01e000-c599-11ea-8dfa-900707cde905.png)
![2020-07-14 06_15_44-Ryujinx 1 0 4921 - Juicy Realm v2 3 0 (0100C7600F654000) (64-bit)](https://user-images.githubusercontent.com/62343878/87424831-e7550b80-c599-11ea-999f-9caa4e4f0fe3.png)
![2020-07-14 06_16_53-Ryujinx 1 0 4921 - Juicy Realm v2 3 0 (0100C7600F654000) (64-bit)](https://user-images.githubusercontent.com/62343878/87424844-ef14b000-c599-11ea-8c1b-cd0c0b4a3824.png)
![2020-07-14 06_17_13-Ryujinx 1 0 4921 - Juicy Realm v2 3 0 (0100C7600F654000) (64-bit)](https://user-images.githubusercontent.com/62343878/87424862-f8058180-c599-11ea-8530-810ae2478d5b.png)
![2020-07-14 06_17_43-Ryujinx 1 0 4921 - Juicy Realm v2 3 0 (0100C7600F654000) (64-bit)](https://user-images.githubusercontent.com/62343878/87424879-02278000-c59a-11ea-827c-8f3b069c25f5.png)

#### Log file :

[JR.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4918758/JR.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by F1ReB4LL** [comment]
## Juicy Realm

#### Game Update Version : *3.0.10*

#### Current on `master` : *1.1.597*

#### Graphics Backend : *Both Vulkan and OpenGL*

*Unplayable - the game field becomes invisible almost instantly, leaving only HUD on the screen. Also crashes randomly.*

```
Last error returned: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1873
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3380
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270
```

#### Hardware Specs : 

##### CPU: *i5-11400H*
##### GPU: *NVIDIA RTX 3050*
##### RAM: *24GB*


#### Screenshots :

![ryujinx_jrl1](https://user-images.githubusercontent.com/39680140/215328006-2a704d73-83de-4ee8-bce4-699e4f21614f.png)
![ryujinx_jrl2](https://user-images.githubusercontent.com/39680140/215328016-36efbe99-eace-407e-8be3-6c63ce34b546.png)
![ryujinx_jrl3](https://user-images.githubusercontent.com/39680140/215328024-adf17d50-0779-465c-815c-59be9023c95d.png)
![ryujinx_jrl5](https://user-images.githubusercontent.com/39680140/215328028-ec70b19b-0d1e-4eea-99e3-6b5f63142052.png)
![ryujinx_jrl4](https://user-images.githubusercontent.com/39680140/215328034-28106039-c86c-4364-8e55-768ac9462baa.png)


#### Log file :

[Ryujinx_1.1.597_2023-01-29_15-54-19.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10529813/Ryujinx_1.1.597_2023-01-29_15-54-19.log)

**Comment by gdkchan** [comment]
Why are you testing this on SoftwarePageTable memory manager mode?

**Comment by F1ReB4LL** [comment]
> Why are you testing this on SoftwarePageTable memory manager mode?

Because its description sounds like the most accurate compared to "Host (fast)" and "Host unchecked (fastest, unsafe)"?

Anyway, the invisible field problem seems to be solved in 1.1.606 by https://github.com/Ryujinx/Ryujinx/pull/4350 (always happens for me on 1.1.605 and earlier, never happens on 1.1.606 and later).

https://user-images.githubusercontent.com/39680140/220437635-0ec57380-3de3-4690-b356-f96fb52eb2a9.mp4
https://user-images.githubusercontent.com/39680140/220437660-eb64e1c7-285a-412e-b946-0ec8e7a70646.mp4
