### ISSUE TITLE
JUST DANCE 2020

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2095]
#### Current on `master` : 1.0.4912

Crashes on launch without an error in the log.

#### Log file :

[JD2020.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4919272/JD2020.log)

**Comment by thomeval** [comment]
The game crashes on launch using the current version (1.0.6250) as well. Ryujinx prints this exception to the console when crashing, but it doesn't get written to the log file:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by thomeval** [comment]
As of version 1.0.6732, the following is logged when attempting to boot this game:

```
00:00:17.132 |I| HLE.GuestThread.26 Cpu PrintGuestStackTrace: Guest stack trace:
Process: JustDance2020, PID: 92
   main:0x008f0514 Sub00000000088f4514
   main:0x00905ce4 Sub0000000008909ce4
   sdk:0x00329e88 Sub0000000009cb0e88
   sdk:0x0032e294 Sub0000000009cb5294
   ??? Sub0000000000000000


00:00:17.132 |E| HLE.GuestThread.26 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x000000000BFFFFFF.
00:00:17.183 |E| HLE.GuestThread.26 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 452
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 287
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 147
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 141
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by justjdfanofficial** [comment]
Uploading Snapchat-2122511237.mp4…

For me it works freezed only for few seconds

**Comment by MutantAura** [comment]
I'll update the status but some screenshots would be useful for future reference!

**Comment by thomeval** [comment]
Although the game is quite playable now, it suffers from https://github.com/Ryujinx/Ryujinx/issues/2104 like other games in the series. Probably best to label this as "status-ingame" for now.

Here are some screenshots:

![JD-2020-1](https://user-images.githubusercontent.com/11618454/150791632-45407239-b744-4790-9cdc-7debab7e9d6b.png)
![JD-2020-2](https://user-images.githubusercontent.com/11618454/150791642-12c9d9e7-1113-458d-a430-81ed561facb6.png)
![JD-2020-3](https://user-images.githubusercontent.com/11618454/150791654-a7871661-8f72-4404-8eb6-ad1f23c029a8.png)
![JD-2020-4](https://user-images.githubusercontent.com/11618454/150791659-9208000f-fc9d-4f5f-9243-b4d0a7f82890.png)
