### ISSUE TITLE
The Savior's Gang

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2098]
#### Current on `master` : 1.0.4921

Crashes in early splash screens.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IGeneralService: 5

Guest Stack Trace:
Process: TheSaviorsG, PID: 81
   sdk:0x0030a3e8 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 26, 380ul> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 26, 380ul> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::BufferClientArgumentType, unsigned int)
   sdk:0x003088c8 nn::sf::cmif::client::detail::CmifProxyImpl<nn::nifm::detail::IGeneralService, nn::sf::cmif::client::CmifDomainProxy<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::nifm::detail::IGeneralService>::_nn_sf_sync_GetCurrentNetworkProfile(nn::sf::Out<nn::nifm::detail::sf::NetworkProfileData, void>)
   sdk:0x0030d6dc nn::nifm::GetCurrentNetworkProfile(nn::nifm::NetworkProfileData*)
   sdk:0x0030dd44 nn::nifm::GetCurrentProxySetting(nn::nifm::ProxySetting*)
   main:0x011fefb4 Sub0000000009202fb4
   main:0x011fe89c Sub000000000920289c
   main:0x011f6184 Sub00000000091fa184
   main:0x0019907c Sub000000000819d07c
   main:0x00190aa4 Sub0000000008194aa4
   main:0x001a915c Sub00000000081ad15c
   main:0x001ad90c Sub00000000081b190c
   main:0x005f0cd4 Sub00000000085f4cd4
   main:0x006d9df4 Sub00000000086dddf4
   main:0x006df3a0 Sub00000000086e33a0
   main:0x006da408 Sub00000000086de408
   main:0x006da244 Sub00000000086de244
   main:0x006da408 Sub00000000086de408
   main:0x005f0cd4 Sub00000000085f4cd4
   main:0x006db5dc Sub00000000086df5dc
   main:0x016e4a70 Sub00000000096e8a70
   main:0x016e4664 Sub00000000096e8664
   main:0x0202335c Sub000000000a02735c
   main:0x01a01168 Sub0000000009a05168
   main:0x02008db4 Sub000000000a00cdb4
   main:0x01f72d9c Sub0000000009f76d9c
   main:0x01f706d4 Sub0000000009f746d4
   main:0x019eb59c Sub00000000099ef59c
   main:0x00009224 Sub000000000800d224
   main:0x00014314 Sub0000000008018314
   sdk:0x0031d3b8 Sub000000000e9043b8
   sdk:0x00321818 Sub000000000e908818
   ??? Sub0000000000000000

Buffer Information:
	RecvListBuff:
	Position: 0x00000012091cd3d0 Size: 0x000000000000017c

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  05 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  D0 D3 1C 09 12 00 7C 01   ········ÐÓ····|·

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/643
https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-07-14 08_27_15-Ryujinx 1 0 4921 - The Savior's Gang v1 0 1 (01002BA00C7CE000) (64-bit)](https://user-images.githubusercontent.com/62343878/87437958-33a94700-c5ac-11ea-9546-6a9a4736b42b.png)

#### Log file :

[TSG.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4919366/TSG.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6910

**Comment by EmulationFanatic** [comment]
Updated
