### ISSUE TITLE
Amoeba Battle - Microscopic RTS Action

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2110]
#### Current on `master` : 1.0.4921

Game crashes on launch with an missing service error.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IGeneralService: 5

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x003165d8 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 26, 380ul> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 26, 380ul> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::BufferClientArgumentType, unsigned int)
   sdk:0x00314aa8 nn::sf::cmif::client::detail::CmifProxyImpl<nn::nifm::detail::IGeneralService, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::nifm::detail::IGeneralService, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_GetCurrentNetworkProfile(nn::sf::Out<nn::nifm::detail::sf::NetworkProfileData, void>)
   sdk:0x003198cc nn::nifm::GetCurrentNetworkProfile(nn::nifm::NetworkProfileData*)
   sdk:0x00319f74 nn::nifm::GetCurrentProxySetting(nn::nifm::ProxySetting*)
   main:0x0023eccc Sub0000000008242ccc
   main:0x002379f4 Sub000000000823b9f4
   main:0x00236a54 Sub000000000823aa54
   main:0x00222c6c Sub0000000008226c6c
   main:0x00222960 Sub0000000008226960
   main:0x001f6474 Sub00000000081fa474
   main:0x0006165c Sub000000000806565c
   main:0x00219774 nnMain
   sdk:0x00296c9c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Buffer Information:
        RecvListBuff:
        Position: 0x000000000b2b25b0 Size: 0x000000000000017c

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  05 00 00 00 00 00 00 00   SFCI············
00000020   01 00 00 00 00 00 00 00  B0 25 2B 0B 00 00 7C 01   ········°%+···|·

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/643

#### Log file :

[amoeba-battle.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4919698/amoeba-battle.log)

**Comment by EmulationFanatic** [comment]
Updated
