### ISSUE TITLE
Alien: Isolation

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2114]
#### Current on `master` : 1.0.4921

Crashes on launch.

```
ProgramName: 'AlienIsolation'
 Message: 'ECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning):'

00:00:07.085 | ServiceLm Log: Guest log:
 Log level: Info
 Time: 4s
 Line: 0
 Filename: ''
 Function: ''
 Module: ''
 Thread: 'MainThread'
 ProgramName: 'AlienIsolation'
 Message: ''

00:00:07.086 | HLE.HostThread.0 KernelSvc Break: Debugger triggered.
00:00:07.388 | HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x004c7380 Sub000000000d9b3380
   sdk:0x004c9fb0 __cxa_get_exception_ptr
   sdk:0x004c9f1c Sub000000000d9b5f1c
   main:0x00492da0 Sub0000000008496da0
   main:0x0049c1e0 Sub00000000084a01e0
   main:0x004eb1bc Sub00000000084ef1bc
   main:0x004bb8f8 Sub00000000084bf8f8
   main:0x00000154 Sub0000000008004154
   rtld:0x000007e4 Sub00000000080007e4
   sdk:0x0029da28 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:00:07.400 | HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x00519c10 __nnmusl_GetTlsValue
   sdk:0x004cbd84 Sub000000000d9b7d84
   sdk:0x004b1f88 Sub000000000d99df88
   sdk:0x004c7380 Sub000000000d9b3380
   sdk:0x004c9fb0 __cxa_get_exception_ptr
   sdk:0x004c9f1c Sub000000000d9b5f1c
   main:0x00492da0 Sub0000000008496da0
   main:0x0049c1e0 Sub00000000084a01e0
   main:0x004eb1bc Sub00000000084ef1bc
   main:0x004bb8f8 Sub00000000084bf8f8
   main:0x00000154 Sub0000000008004154
   rtld:0x000007e4 Sub00000000080007e4
   sdk:0x0029da28 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:00:07.405 | HLE.HostThread.2 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:00:07.450 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1154
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 47
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 129
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Log file :

[AI.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4919814/AI.log)

**Comment by Doctorwho1909** [comment]
[Ryujinx_2020-08-29_21-33-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5146157/Ryujinx_2020-08-29_21-33-23.log)
1.0.5246 also not a ue4 game seems to fail at ```00:00:04.877 |G| ServiceLm Log: Guest Log:
  Log level: Info
    Time: 3s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'MainThread'
    ProgramName: 'AlienIsolation'
    Message: 'terminating with uncaught exception of type google::protobuf::FatalException: CH'```

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
