### ISSUE TITLE
Kairobotica

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2121]
#### Current on `master` : 1.0.4921

Goes ingame, but crashes with an missing opcode error soon after.

```
Unhandled exception. Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000089ca494 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1114
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 71
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1340

#### Screenshots :

![07_14_41-18:41:06](https://user-images.githubusercontent.com/62521228/87453054-42224d80-c602-11ea-9992-6bbe30534fb9.png)
![07_14_41-18:41:40](https://user-images.githubusercontent.com/62521228/87453056-43537a80-c602-11ea-89bf-ca1634a4df26.png)
![07_14_42-18:42:29](https://user-images.githubusercontent.com/62521228/87453058-43ec1100-c602-11ea-8c55-dca5a9385b40.png)
![07_14_43-18:43:15](https://user-images.githubusercontent.com/62521228/87453060-4484a780-c602-11ea-98ee-1b249034e159.png)
![07_14_43-18:43:37](https://user-images.githubusercontent.com/62521228/87453062-451d3e00-c602-11ea-9c03-5f6f9f064aca.png)

#### Log file :

[kairobotica.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4920060/kairobotica.log)

**Comment by benderscruffy** [comment]
played it for a while and it didnt crash
![kairo](https://user-images.githubusercontent.com/2696404/99900826-1409f400-2ced-11eb-937b-0eb589e0dba8.PNG)

**Comment by EmulationFanatic** [comment]
Updated
