### ISSUE TITLE
Waifu Uncovered

### ISSUE THREAD

**Issue by Seker-0** [Ryujinx/Ryujinx-Games-List#2137]
#### Current on `master` : 1.0.4941

The game crashes after the first mission.

```
00:04:18.059 | GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.Gpu.Image.Texture.SetScale(Single scale) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 410
   at Ryujinx.Graphics.Gpu.Image.Texture.Flush() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 614
   at Ryujinx.Graphics.Gpu.Image.TextureManager.Flush(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 1012
   at Ryujinx.Graphics.Gpu.Engine.Methods.LaunchDma(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 48
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 180
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs :

GPU : 1060
CPU : I5 8400
RAM : 16GB

#### Screenshots :

![bandicam 2020-07-16 22-10-27-948](https://user-images.githubusercontent.com/35269098/87689946-07134c00-c7b3-11ea-8c72-e2ccc75c4c24.jpg)
![bandicam 2020-07-16 22-09-27-636](https://user-images.githubusercontent.com/35269098/87689962-0b3f6980-c7b3-11ea-99e4-5e503557b2e6.jpg)
![bandicam 2020-07-16 22-11-00-770](https://user-images.githubusercontent.com/35269098/87689975-0ed2f080-c7b3-11ea-9eaf-42d2becab02f.jpg)
![bandicam 2020-07-16 22-11-10-316](https://user-images.githubusercontent.com/35269098/87689983-12ff0e00-c7b3-11ea-8809-0b0198f5dd81.jpg)
![bandicam 2020-07-16 22-12-02-851](https://user-images.githubusercontent.com/35269098/87689991-16929500-c7b3-11ea-8b87-797fc66e624a.jpg)

#### Logs :

[WU.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4932443/WU.log)

**Comment by luongvansu** [comment]
fgg

**Comment by SeraUX** [comment]
## Waifu Uncovered

#### Game Update Version : 1.0.3

#### Current on `master` : 1.0.5155

Game crashes on start

```
00:01:05.128 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Graphics.Gpu.Memory.Buffer.SynchronizeMemory(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 128
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.GetBuffer(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 765
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CommitGraphicsBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 511
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 299
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 273
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 67
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 59
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 334
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs : 

##### CPU: i3-7300
##### GPU:  NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Log file :

[waifu-uncovered.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5069314/waifu-uncovered.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by SeraUX** [comment]
## Waifu Uncovered

#### Game Update Version : 1.0.3

#### Current on `master` : 1.0.5173

Game now boots, but crashes during a level.

```
00:03:42.129 |E| GUI.RenderLoop Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.Gpu.Image.Texture.SetScale(Single scale) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 410
   at Ryujinx.Graphics.Gpu.Image.Texture.Flush() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 614
   at Ryujinx.Graphics.Gpu.Image.TextureManager.Flush(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 1012
   at Ryujinx.Graphics.Gpu.Engine.Methods.LaunchDma(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 48
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 334
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs : 

##### CPU: i3-7300
##### GPU:  NVIDIA Corporation GeForce GTX 1050 Ti/PCIe/SSE2
##### RAM: 8GB

#### Screenshots :

![2020-08-13 18_01_50](https://user-images.githubusercontent.com/62521228/90158603-7cad1080-dd8f-11ea-8d68-08bf80d61b50.png)
![2020-08-13 18_02_10](https://user-images.githubusercontent.com/62521228/90158617-820a5b00-dd8f-11ea-9a3e-8561c3acf2fa.png)
![2020-08-13 18_02_22](https://user-images.githubusercontent.com/62521228/90158626-859de200-dd8f-11ea-9b75-bbb99d0e2dc5.png)
![2020-08-13 18_02_40](https://user-images.githubusercontent.com/62521228/90158634-8898d280-dd8f-11ea-811d-a7b6ec27fc04.png)

#### Log file :

[waifu-uncovered.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5070103/waifu-uncovered.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Cronos-0** [comment]
Update doesn't crash anymore.

**Comment by Cronos-0** [comment]
should change status Now it's fully playable
