### ISSUE TITLE
Paper Mario The Origami King

### ISSUE THREAD

**Issue by teszNU** [Ryujinx/Ryujinx-Games-List#2138]
#### Current on `master` : Commit Id *or* Build Version : 1.0.4901

*Describe the current game state here.*

```
this game running fine, but fps is very low.

and known errors:
00:01:25.341 | ServiceMm SetAndWait: Stubbed. id: 1 - value: 4294966296 - timeout: -1

00:12:50.212 | ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...

```

#### Screenshots :
![layout1](https://user-images.githubusercontent.com/61547678/87733989-e0c9cc80-c803-11ea-9121-217f3c97826a.png)
![layout2](https://user-images.githubusercontent.com/61547678/87734004-ec1cf800-c803-11ea-8f2e-c6f2e98e3099.png)
![layout3](https://user-images.githubusercontent.com/61547678/87734017-f4753300-c803-11ea-98eb-e930746b3c0c.png)
![layout4](https://user-images.githubusercontent.com/61547678/87734026-fdfe9b00-c803-11ea-91f9-0c1bc3d8a8ed.png)

#### Log file :
[Ryujinx_2020-07-17_07-20-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4934976/Ryujinx_2020-07-17_07-20-54.log)

**Comment by KylianJay** [comment]
Just saved my game, restarted Ryujinx and getting an error that crashes Ryujinx.
[Ryujinx_2020-07-17_21-33-10.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4939877/Ryujinx_2020-07-17_21-33-10.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by kossirk** [comment]
Game Update Version : 1.0.0
Current on master : 1.0.5126
Game crash on load screen. Invalid memory access at virtual address 0x000000000000000A.

Hardware Specs :
CPU: HexaCore AMD Ryzen 5 3500, 4100 MHz (41 x 100)
GPU: GeForce GTX 1060 6GB
RAM: 16GB
[Ryujinx_2020-08-04_21-59-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5026072/Ryujinx_2020-08-04_21-59-54.log)

**Comment by JoachimFlottorp** [comment]
Paper Mario The Origami King

1.0.0

#### Current on `master` : 1.0.5131

Game shows the rainbow circle. "Loading Screen" for a few seconds and then crashes.

#### Hardware Specs : 

##### CPU: *AMD Ryzen 5 2600*
##### GPU: *NVIDIA Geforce 1060 6GB*
##### RAM: *8 GB*


[Ryujinx_2020-08-06_15-33-51.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5035094/Ryujinx_2020-08-06_15-33-51.log)

**Comment by Teotia444** [comment]
<details>Got crashed at very end of the game when <summary>Spoiler warning</summary>
  
  You may save Bowser and when you enter in the buffet room it keep crashing 
</details>

**Comment by exoduscl** [comment]
> Spoiler warning

**Any news about this crash?** I'm currently playing it I'm starting level 3 and I had just 1 random crash, but nothing else and the game runs perfectly with no audio problems.

i7 10700, 16GB ram, RTX 2060

**Comment by riperiperi** [comment]
Need a log to debug the crash. It's unlikely that any of us have played through _any_ game all the way through on the emulator ourselves.

**Comment by exoduscl** [comment]
> Need a log to debug the crash. It's unlikely that any of us have played through _any_ game all the way through on the emulator ourselves.

Thanks I'll keep on playing to check if there's any issue and report back with the log, for now I'm on world/level 3 without problems (just one random crash that did not repeat).

**Comment by exoduscl** [comment]
I just found a game breaking bug where an action does not activate and you cannot advance in the game. You can see in the following video how nothing happens when entering the spring (it should regenerate your energy and activate a conversation that allows you to keep on advancing):

https://youtu.be/tI0HFdU2Xdw

I transfered the save to YUZU in order to see if the same happened and as I thought, the spring regenerated Mario's energy and I was able to advance:

https://youtu.be/xsGSdTTdvcY

I attach the save that leaves you right before the problem occurs
http://www.mediafire.com/file/1whag8k4i42z6bv/Origami_king_save_with_game_breaking_bug_in_Riujinx.7z/file

PS: sorry for any mistake, first time posting a bug in here and English is not my first language, please let me know if you need anything else

**Comment by SeraUQ** [comment]
@exoduscl 
thx for the report, I'll try reproducing the bug on my side when I get the time

**Comment by SeraUQ** [comment]
@exoduscl I wasnt able to reproduce the bug
![00:28:03-11_26_20](https://user-images.githubusercontent.com/62521228/100291628-99f09e00-2f7e-11eb-9408-bae5e511574a.png)

**Comment by exoduscl** [comment]
Thank you for your time!, what can be the cause of it on my end?

1.- The resolution? (i'm using 4k)
2.- The update of the game? (I haven't installed any update)
3.- I'm using the new shader cache implementation
4.- The file extension of the game? (using NSP)

This is the other config I'm using:
![image](https://user-images.githubusercontent.com/69265795/100294550-de237480-2f65-11eb-8e84-32efbc5f454b.png)
![image](https://user-images.githubusercontent.com/69265795/100294684-4c683700-2f66-11eb-8d13-3b6dedeb37bc.png)
![image](https://user-images.githubusercontent.com/69265795/100294582-f5faf880-2f65-11eb-908f-12e07c2ce98d.png)

**I'll try moving options around to see if I can pass that part, the spring seems to be deactivated every time I need to use it (later in the game you have to go back and it doesn't work either).**

Thanks again for your time!

**Comment by exoduscl** [comment]
Hi @SeraUQ I have an update:

**I discovered that the problem only happens when using a joystick to control the game,** I tried with an Xbox One and a PS4 controller (wired and wireless) and got the same result (conversation not triggering) **as soon as I disconnect the controller  the game proceeds as it should**, take a look at this video please:

https://youtu.be/rLDc3eHeshw

I hope this helps, please let me know if you could reproduce it.

**Comment by exoduscl** [comment]
Ok, I finished the game and there's only 2 important issues, the directx related bug I commented earlier (please check the post right above this one) and a crash near the ending that prevents you from finishing the game.

I attach everything needed to investigate the crash: 

1.- A save right before the crash
2.- A save right after the crash (in case someone comes here looking for a solution)
3.- A log of the crash.

I hope this helps in order to fix both issues.

[Origami king Ryujinx.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5686196/Origami.king.Ryujinx.zip)

![Paper Mario Finished Ryujinx](https://user-images.githubusercontent.com/69265795/102035512-4c0dcf80-3d9f-11eb-89d8-206ec7503036.png)

**Comment by Dunge** [comment]
Hello, first time reporting here, I hope I do this correctly.

Game Version : 1.0.0
Ryujinx version : 1.0.6604

Hardware Specs :
CPU: i7-8700
GPU: NVIDIA RTX 2070
RAM: 32GB

Outstanding Issues:
I played for a few hours without any issue. The first time I died the game "froze" in the loading screen. But I would still see a frame of the loading icon moves from time to time, so I let it run, and after over 15minutes it went through and resumed! Dying a second time did not reproduce the error.

A bit later, I was about halfway through the "Earth Vellumental Temple" level and the software crashed and instant closed. Looking at the log files I have this exception stack trace:

```
01:30:59.845 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000F9198B000.
01:30:59.946 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 292
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 463
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 287
   at Ryujinx.Graphics.Gpu.Memory.Buffer.LoadRegion(UInt64 mAddress, UInt64 mSize) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 316
   at Ryujinx.Memory.Tracking.MultiRegionHandle.QueryModified(UInt64 address, UInt64 size, Action`2 modifiedAction, Int32 sequenceNumber) in C:\projects\ryujinx\Ryujinx.Memory\Tracking\MultiRegionHandle.cs:line 111
   at Ryujinx.Graphics.Gpu.Memory.Buffer.SynchronizeMemory(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 146
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CreateBufferAligned(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 514
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.TranslateAndCreateBuffer(UInt64 gpuVa, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 436
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.SetVertexBuffer(Int32 index, UInt64 gpuVa, UInt64 size, Int32 stride, Int32 divisor) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 182
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateVertexBufferState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 821
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateIndexBufferState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 785
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 124
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 71
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 40
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 436
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Dunge** [comment]
Another crash with Ruyjinx 1.0.6769 now.

This time it happens every single time (4 on 4 now) when entering Bowser's Castle after the Shangri-Spa level where there's a massive brawl between two enemy groups.

Since the callstack is about audio, I guess I'll try to bypass the room with sound disabled.

```
00:02:27.522 |E| AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.DataSourceHelper.ProcessWaveBuffers(IVirtualMemoryManager memoryManager, Span`1 outputBuffer, WaveBufferInformation info, UInt32 targetSampleRate, Int32 sampleCount) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\DataSourceHelper.cs:line 71
   at Ryujinx.Audio.Renderer.Dsp.Command.AdpcmDataSourceCommandVersion1.Process(CommandList context) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\AdpcmDataSourceCommandVersion1.cs:line 77
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\CommandList.cs:line 98
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 220
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by poudink** [comment]
I am unable to progress past the loading screen that follows the first scene of the opening cutscene.

**Comment by FaeTalan** [comment]
Will we see the resolution scaling for Paper Mario working any time soon? Together with the "disable sharpening" mod, it would become the ideal way to play this beautiful game.

**Comment by exoduscl** [comment]
The gamebreaking crash near the ending is still there, I attach the save just before the crash and log:

https://github.com/Ryujinx/Ryujinx-Games-List/files/5686196/Origami.king.Ryujinx.zip

**Comment by poudink** [comment]
The status should probably be downgraded to ingame, then.

**Comment by SirJoe71** [comment]
Game Update Version : 1.0.1
Current on master : 1.1.11+c52158b

Game loads and plays pegged at the 30FPS cap. Audio is a bit rough at times, but does not interfere with game play.
Hardware Specs :
CPU: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz ; 6 logical
GPU: NVIDIA GTX 1060
RAM: 16GB
Outstanding Issues:

water rendering is black (with the vulkan sperimental versione of emulator of july it renders correctly)

Screenshots :

Last version of emulator 1.10.1

![papermario_opengl](https://user-images.githubusercontent.com/9558989/151581878-2b38d4b5-a8b7-46a8-ab75-8b26f282c1ed.png)

vulkan version :1.1.0

![papermario_vulkan](https://user-images.githubusercontent.com/9558989/151582407-09a0c1e8-fc20-4954-b7e9-c083327bc8d8.png)

**Comment by MetrosexualGarbodor** [comment]
Needs an update.

**Comment by codyzhou04** [comment]
I'm trying to get past beginning and for some reason I can't pull with the thousand fold arms in the room with bowser. I disabled motion and rumble controls because I only have a keyboard. It's strange because it worked for the introductory jail cell where you first find the arms. It lets me grab on but doesn't do anything when i move my w a s d controls.

![image](https://user-images.githubusercontent.com/100049505/160266720-311e705e-8261-4721-85e1-fbcb8f01655e.png)

**Comment by codyzhou04** [comment]
Game version: 1.0.1 
Ryujinx version: 1.1.85
CPU: Intel i7-3770
GPU: Nvidia GTX 1650
RAM: 24GB 

I'm trying to get past the beginning but for some reason it doesn't allow me to pull with the arms in the room where you discover bowser. It allows me to latch on but I can't actually move them while they're latched on. I disabled motion and rumble controls because I don't have a keyboard. What's really weird is that it works in the first room. I've tried restarting.
![image](https://user-images.githubusercontent.com/100049505/160266778-f7dfb89e-09d1-45e6-9f10-8a3ae3150301.png)

**Comment by user670** [comment]
#### Game Update Version :
1.0.0

#### Current on `master` : Commit Id *or* Build Version :
1.1.106

*Describe the current game state here.*

Mostly playable at full speed. Some lag spikes in some boss fights.

***Consistent crash*** at one particular point in the story. Traceback below:

```
00:02:09.662 |E| AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.DataSourceHelper.ProcessWaveBuffers(IVirtualMemoryManager memoryManager, Span`1 outputBuffer, WaveBufferInformation& info, Span`1 wavebuffers, VoiceUpdateState& voiceState, UInt32 targetSampleRate, Int32 sampleCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\DataSourceHelper.cs:line 66
   at Ryujinx.Audio.Renderer.Dsp.Command.AdpcmDataSourceCommandVersion1.Process(CommandList context) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\AdpcmDataSourceCommandVersion1.cs:line 75
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\CommandList.cs:line 142
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 225
```
(the in-game event in question: after entering Bowser's castle for the first time in chapter 5, some Bowser's minions rush into the castle and knock down Mario and his companions, and crash happens after that, likely as the character try to stand up.)

#### Hardware Specs : 

##### CPU: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
##### GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU
##### RAM: 16GB
*Note: the device is a laptop, not desktop.*

#### Log file :
[Ryujinx_1.1.106_2022-04-24_13-41-10.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8549091/Ryujinx_1.1.106_2022-04-24_13-41-10.log)

**Comment by SirBlobman** [comment]
Audio crashes seem to be fixed by this PR, further testing needed:
[Ryujinx #3653](https://github.com/Ryujinx/Ryujinx/pull/3653)

**Comment by rtgs** [comment]
Crash still occurs in Bowser's castle near end game, tested on firmware 15.0.0 and 15.0.1. Mac mini M2

**Comment by onceler21** [comment]
> The game crashed once reaching the big city on the first chapter: [Ryujinx_1.1.763_2023-05-08_16-17-24.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11422402/Ryujinx_1.1.763_2023-05-08_16-17-24.log)

I had similar "ErrorOutOfDeviceMemory" crashes until I enabled texture recompression. I have had no issues since then (but haven't reached chapter 5 yet)

**Comment by onceler21** [comment]
Looks like the audio crash in chapter 5 mentioned above is still happening. Apart from that, and having to enable texture recompression, everything has run smoothly (with only the expected pauses for shader compilation)

Game Version: 1.0.1
Ryujinx version: 1.1.808

Hardware: Aya Neo Geek
CPU: AMD Ryzen 7 6800U
GPU: Radeon 680M (integrated)
RAM: 16G

Crash log: [Ryujinx_1.1.808_2023-05-20_14-35-58.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11521690/Ryujinx_1.1.808_2023-05-20_14-35-58.log)

The relevant section seems to be
```
01:03:37.871 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 22
01:03:37.872 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 23
01:03:37.872 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 18
01:03:37.872 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 19
01:03:37.872 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 22
01:03:37.872 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 23
01:03:37.932 |E| AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.DataSourceHelper.ProcessWaveBuffers(IVirtualMemoryManager memoryManager, Span`1 outputBuffer, WaveBufferInformation& info, Span`1 wavebuffers, VoiceUpdateState& voiceState, UInt32 targetSampleRate, Int32 sampleCount) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Audio\Renderer\Dsp\DataSourceHelper.cs:line 49
   at Ryujinx.Audio.Renderer.Dsp.Command.AdpcmDataSourceCommandVersion1.Process(CommandList context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Audio\Renderer\Dsp\Command\AdpcmDataSourceCommandVersion1.cs:line 58
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Audio\Renderer\Dsp\Command\CommandList.cs:line 116
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 182
```

**Comment by SixelAlexiS90** [comment]
I played in the desert for another couple of hours without texture recompression and it was a crash fest.
I have 6GB of VRAM and by monitoring it it seems that the memory fails to be "flushed" since in some cases goes up to 5GB, then you change zone and it goes back to 2GB, then you keep playing and it goes to 5.6GB and at that point, if you change zone again (a big one like a city) it hangs in the loading and crash.
Maybe there are issues on managing the VRAM flush with this game or in general under Vulkan.

Usually before the crashes I get those heavy stutters (that aren't cache related) during traversal, this is the error I get:

```
00:57:24.389 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
00:57:29.198 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
00:57:32.619 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
00:57:37.325 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:57:38.325 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 450911 took more than 1000ms, resuming execution...
00:57:40.286 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
00:58:05.636 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
00:58:08.139 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:58:09.021 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
00:58:12.981 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 107309 bytes, profiled functions: 32050).
00:58:42.984 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 107311 bytes, profiled functions: 32050).
00:59:12.980 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 107310 bytes, profiled functions: 32050).
00:59:42.980 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 107311 bytes, profiled functions: 32050).
01:00:03.141 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
01:00:42.980 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 107309 bytes, profiled functions: 32050).
01:01:02.935 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
01:01:05.621 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
01:01:31.805 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
01:01:36.012 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
01:01:37.011 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 480982 took more than 1000ms, resuming execution...
01:01:39.157 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
01:01:42.980 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 107340 bytes, profiled functions: 32058).
01:02:02.191 |S| HLE.OsThread.22 ServiceAcc StoreSaveDataThumbnail: Stubbed. 
01:02:12.980 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 107342 bytes, profiled functions: 32058).
01:02:23.823 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 182
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map, Boolean isBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 58
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, Device device, TextureCreateInfo info, Single scaleFactor, Auto`1 foreignAllocation) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 149
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 116
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 447
```

And as you can see after that I get the usual "ErrorOutOfDeviceMemory" that lead to the crash.
If you restart the game right away you won't get most of those stutters, they get worse the more you play but since the VRAM doesn't get "full" in a linear way, I don't know why at some point it does while other times it just get flush while you play.

After that point I've enable the "texture recompression" like suggested by @onceler21 and indeed it doesn't crash anymore, I still get quite heavy stutters (a bit worse as well now) when I load some zones for the first time during that session (again, not shader cache related) and the overall VRAM usage seems lower.
Now if I have to load an heavy zone after playing for some time, it hangs up the loading for various seconds but instead of crashing, the loading goes through.

So yeah, it's a solution but something is weird with the VRAM usage on this one, or maybe it's a spread problem that in this case is more evident?

**Comment by spkpal** [comment]
I am having problems getting past boswer castle because of a audio rendering problem on paper mario origami king on this ryujinx emulator, because it keeps crashing at that part

**Comment by dtlucario** [comment]
![Paper Mario_ The Origami King_2024-08-09_19-09-57](https://github.com/user-attachments/assets/793a053b-4488-41cb-acdd-5e0580b6686b)
![Paper Mario_ The Origami King_2024-08-09_19-10-01](https://github.com/user-attachments/assets/1cf37b50-7205-4304-b68a-5a4335890b54)

Some odd Graphical Glitching going on. Ryu version 1.1.1373,

![image](https://github.com/user-attachments/assets/d53e26e3-bb08-4661-95b9-dae55a36a17d)
