### ISSUE TITLE
Strike Force - War on Terror

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2156]
#### Current on `master` : 1.0.5044

Crashes on launch.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 317
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Read[T](UInt64 gpuVa) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 58
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(IGpuAccessor gpuAccessor, Block block, UInt64 limitAddress, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 219
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(IGpuAccessor gpuAccessor, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 76
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, ShaderConfig& config, Int32& size, FeatureFlags& featureFlags) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 89
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 19
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateGraphicsShader(GpuState state, ShaderStage stage, UInt64 gpuVa, UInt64 gpuVaA) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 365
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 140
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 941
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 120
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 67
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 497
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 102
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 142
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 68
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[SFWoT.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4977516/SFWoT.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by benderscruffy** [comment]
using 1.0.7107
goes ingame now
![ryujinx_capture_2021-11-24_16-04-03](https://user-images.githubusercontent.com/2696404/143199082-018bb1e8-37d3-4fed-81cb-46465efae4f7.png)
![ryujinx_capture_2021-11-24_16-06-25](https://user-images.githubusercontent.com/2696404/143199088-57cc7afd-ac68-4df4-8db7-97728752b452.png)
![ryujinx_capture_2021-11-24_16-06-42](https://user-images.githubusercontent.com/2696404/143199095-bd935083-2b3a-45ae-b25a-265ac14368ec.png)
![ryujinx_capture_2021-11-24_16-06-59](https://user-images.githubusercontent.com/2696404/143199105-f8083d9d-3d10-4b28-8c8a-4d13898a8da3.png)
![ryujinx_capture_2021-11-24_16-07-46](https://user-images.githubusercontent.com/2696404/143199118-c8d7f350-37e1-4a8a-ae5a-34e3bd4c3244.png)
![ryujinx_capture_2021-11-24_16-08-14](https://user-images.githubusercontent.com/2696404/143199128-80baf4a1-8936-470a-957a-f9d9a02615c3.png)
