### ISSUE TITLE
Earthfall: Alien Horde

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2161]
#### Current on `master` : 1.0.5044

Crashes in early nvdec splash screens.

```
Ryujinx.NvdecProcessor Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 317
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Cpu.MemoryManager.GetWritableRegion(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 209
   at Ryujinx.Graphics.Nvdec.Image.SurfaceWriter.Write(MemoryManager gmm, ISurface surface, UInt32 lumaOffset, UInt32 chromaOffset) in C:\projects\ryujinx\Ryujinx.Graphics.Nvdec\Image\SurfaceWriter.cs:line 39
   at Ryujinx.Graphics.Nvdec.H264Decoder.Decode(NvdecDevice device, ResourceManager rm, NvdecRegisters& state) in C:\projects\ryujinx\Ryujinx.Graphics.Nvdec\H264Decoder.cs:line 17
   at Ryujinx.Graphics.Nvdec.NvdecDevice.Decode(CodecId codecId) in C:\projects\ryujinx\Ryujinx.Graphics.Nvdec\NvdecDevice.cs:line 48
   at Ryujinx.Graphics.Device.DeviceState`1.Write(Int32 offset, Int32 data) in C:\projects\ryujinx\Ryujinx.Graphics.Device\DeviceState.cs:line 89
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\projects\ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-07-26 06_38_49-Ryujinx 1 0 5044 - Earthfall_ Alien Horde v1 0 0 (0100DFC00E472000) (64-bit)](https://user-images.githubusercontent.com/62343878/88479562-40635e80-cf0d-11ea-905d-48ddd1af1951.png)

#### Log file :

[EAH.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4977626/EAH.log)

**Comment by benderscruffy** [comment]
using 1.0.7104
goes ingame now
with graphic glitches ingame
![ryujinx_capture_2021-11-14_12-05-49](https://user-images.githubusercontent.com/2696404/141667635-b43dd52d-357d-49b5-ab26-421f6b7aefdb.png)
![ryujinx_capture_2021-11-14_12-06-03](https://user-images.githubusercontent.com/2696404/141667637-af63e8f8-97fa-4953-a72c-2085caf474d2.png)
![ryujinx_capture_2021-11-14_12-06-24](https://user-images.githubusercontent.com/2696404/141667639-505d11ae-58dd-4340-9093-843c2ecdc7f6.png)
![ryujinx_capture_2021-11-14_12-06-33](https://user-images.githubusercontent.com/2696404/141667643-71de957d-76ee-41e4-b8f1-a53d48126529.png)
![ryujinx_capture_2021-11-14_12-11-11](https://user-images.githubusercontent.com/2696404/141667647-46413217-8079-403f-b676-d8ac7301cd1a.png)
![ryujinx_capture_2021-11-14_12-11-37](https://user-images.githubusercontent.com/2696404/141667652-852aee0d-90ee-44ac-b916-ad09d9edd760.png)

**Comment by EmulationFanatic** [comment]
Updated
