### ISSUE TITLE
Black Future '88

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2171]
#### Current on `master` : 1.0.5044

Game loads and plays smoothly, but crashes shortly after starting a game.

```
HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 455
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 300
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 177
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 97
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1154
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-07-26 15_38_27-Ryujinx 1 0 5044 - Black Future '88 v1 0 0 (010049000B69E000) (64-bit)](https://user-images.githubusercontent.com/62343878/88490663-619e6c00-cf5a-11ea-985b-05e331239932.png)
![2020-07-26 15_39_14-Ryujinx 1 0 5044 - Black Future '88 v1 0 0 (010049000B69E000) (64-bit)](https://user-images.githubusercontent.com/62343878/88490665-62cf9900-cf5a-11ea-96e9-cbc56e1c5aae.png)
![2020-07-26 15_39_32-Ryujinx 1 0 5044 - Black Future '88 v1 0 0 (010049000B69E000) (64-bit)](https://user-images.githubusercontent.com/62343878/88490668-65ca8980-cf5a-11ea-95f1-df8842f8a7f0.png)
![2020-07-26 15_39_50-Ryujinx 1 0 5044 - Black Future '88 v1 0 0 (010049000B69E000) (64-bit)](https://user-images.githubusercontent.com/62343878/88490674-6a8f3d80-cf5a-11ea-8057-932718b90d13.png)
![2020-07-26 15_40_31-Ryujinx 1 0 5044 - Black Future '88 v1 0 0 (010049000B69E000) (64-bit)](https://user-images.githubusercontent.com/62343878/88490679-6ebb5b00-cf5a-11ea-9911-0aa2bf56bb8c.png)
![2020-07-26 16_02_07-Ryujinx 1 0 5044 - Black Future '88 v1 0 0 (010049000B69E000) (64-bit)](https://user-images.githubusercontent.com/62343878/88490680-6ebb5b00-cf5a-11ea-898f-667dd2f0bf5c.png)
![2020-07-26 16_02_13-Ryujinx 1 0 5044 - Black Future '88 v1 0 0 (010049000B69E000) (64-bit)](https://user-images.githubusercontent.com/62343878/88490681-73800f00-cf5a-11ea-94ea-1e401c3494e2.png)
![2020-07-26 16_02_29-Ryujinx 1 0 5044 - Black Future '88 v1 0 0 (010049000B69E000) (64-bit)](https://user-images.githubusercontent.com/62343878/88490685-7a0e8680-cf5a-11ea-9af0-3dec2ba8a2e2.png)
![2020-07-26 16_02_48-Ryujinx 1 0 5044 - Black Future '88 v1 0 0 (010049000B69E000) (64-bit)](https://user-images.githubusercontent.com/62343878/88490686-80046780-cf5a-11ea-9a91-24c12ca556be.png)

#### Log file :

[BF88.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4978763/BF88.zip)

**Comment by EmulationFanatic** [comment]
Updated
