### ISSUE TITLE
Amnesia: Collection

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2175]
#### Current on `master` : 1.0.5049

Game boots to main menu but crashes after selecting any of the embedded games.

```
00:00:31.511 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at Ryujinx.HLE.HOS.Services.Lm.LogService.ILogger.ReadEncodedInt(BinaryReader reader) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Lm\LogService\ILogger.cs:line 22
   at Ryujinx.HLE.HOS.Services.Lm.LogService.ILogger.Log(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Lm\LogService\ILogger.cs:line 35
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 178
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Screenshots :

![2020-07-28 15_12_33-Ryujinx 1 0 5049 - Amnesia_ Collection v1 0 0 (01003CC00D0BE000) (64-bit)](https://user-images.githubusercontent.com/62343878/88722792-16649480-d0e5-11ea-937d-55a2df95759d.png)

#### Log file :

[AC.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4991205/AC.log)

**Comment by Djipi71** [comment]
Update : Now amnesia go Ingame : Graphics issues and no fullspeed:

![Sans titre-1](https://user-images.githubusercontent.com/35375131/106352128-15552f80-62e1-11eb-8ada-113cb701f923.png)

Here's the LOG:
[Ryujinx_1.0.6455_2021-01-30_09-50-40.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5897648/Ryujinx_1.0.6455_2021-01-30_09-50-40.log)

**Comment by benderscruffy** [comment]
using 1.0.7108
all go ingame but graphics are all messed up or black screen with music or voices
![ryujinx_capture_2021-11-26_16-37-00](https://user-images.githubusercontent.com/2696404/143552479-34ca7491-b63e-4848-8113-211a3dab661b.png)
![ryujinx_capture_2021-11-26_16-37-11](https://user-images.githubusercontent.com/2696404/143552484-ab28310b-5c8b-4f67-a430-6a7e9b5579be.png)
![ryujinx_capture_2021-11-26_16-37-36](https://user-images.githubusercontent.com/2696404/143552491-333f63ba-71f5-4a84-98cb-094eccfb517e.png)
![ryujinx_capture_2021-11-26_16-40-36](https://user-images.githubusercontent.com/2696404/143552505-7c8c4d5f-3bb7-43bf-a839-9aae17f47105.png)

**Comment by EmulationFanatic** [comment]
Updated
