### ISSUE TITLE
Fire Emblem Warriors

### ISSUE THREAD

**Issue by MastTerGolf** [Ryujinx/Ryujinx-Games-List#218]
#### Current on `master` : 1.0.3494

* Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*

*Describe the current game state here.*

#### Screenshots : 
![bandicam 2020-01-14 20-48-31-420](https://user-images.githubusercontent.com/35269098/72355470-1c32f380-371a-11ea-9295-d9b9383fe187.jpg)
![bandicam 2020-01-14 20-48-35-606](https://user-images.githubusercontent.com/35269098/72355477-22c16b00-371a-11ea-8699-813d429142e7.jpg)
![bandicam 2020-01-14 20-48-45-249](https://user-images.githubusercontent.com/35269098/72355482-26ed8880-371a-11ea-97aa-aad2663ef83f.jpg)

#### Log file : 
[Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4059800/Ryujinx.log)

**Comment by B3astTech** [comment]
Updated

**Comment by GoffyDude** [comment]
Needs update

**Comment by GoffyDude** [comment]
## Fire Emblem Warriors

#### Current on `master` : 1.0.4548

Crashes when trying to start new game with the new error below.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.HLE.HOS.Services.Nv.Types.NvIoctlNotImplementedException: The ioctl is not implemented.

Device File: NvHostGpuDeviceFile

Ioctl (0x80804816)
	Number: 0x00000016
	Type: 0x00000048
	Size: 0x00000080
	Direction: Write
Guest Stack Trace:
Process: Application, PID: 81
   subsdk3:0x0000e418 Sub000000000a713418
   subsdk3:0x0000d280 Sub000000000a712280
   subsdk3:0x0000f870 NvOsDrvIoctl
   subsdk3:0x0003812c Sub000000000a73d12c
   subsdk3:0x000356f8 Sub000000000a73a6f8
   subsdk3:0x00089b30 Sub000000000a78eb30
   subsdk3:0x0008bc1c Sub000000000a790c1c
   subsdk3:0x00089a60 Sub000000000a78ea60
   main:0x008c2270 Sub00000000088c8270
   main:0x00981dcc Sub0000000008987dcc
   main:0x00981c6c Sub0000000008987c6c
   main:0x0097e900 Sub0000000008984900
   main:0x007bc7b0 Sub00000000087c27b0
   main:0x0068fac4 Sub0000000008695ac4
   main:0x0068f15c Sub000000000869515c
   main:0x007a6624 Sub00000000087ac624
   main:0x007a54f8 Sub00000000087ab4f8
   main:0x00978594 Sub000000000897e594
   sdk:0x00082ecc Sub000000000a963ecc
   sdk:0x00085cd8 Sub000000000a966cd8
   ??? Sub0000000000000000


   at Ryujinx.HLE.HOS.Services.Nv.INvDrvServices.Ioctl(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nv\INvDrvServices.cs:line 270
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

#### Log file :

[FEW.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4624614/FEW.zip)

**Comment by GoffyDude** [comment]
Updated

**Comment by voidcat0** [comment]
Ryujinx Version: 1.0.5837
Operating System: Microsoft Windows 10.0.17763 (X64)
CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Total RAM: 16325 MB
Using Firmware Version: 10.2.0
PPTC on - Shader cache on - Multicore on - 2x scaling on

Got three crash logs

First log: [Ryujinx_2020-11-28_19-41-23 - FEW first - crash after 2 sec ingame.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5611098/Ryujinx_2020-11-28_19-41-23.-.FEW.first.-.crash.after.2.sec.ingame.log)
First boot of the game, crashed after a couple of seconds ingame. It had super low performance, most likely due to shader caching. I tried giving it some time via the pause menu, but that didn't help and it crashed as soon as I continued. The pause menu itself was at 60 FPS.

Second log: [Ryujinx_2020-11-28_19-50-02 - FEW second - crash during load.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5611101/Ryujinx_2020-11-28_19-50-02.-.FEW.second.-.crash.during.load.log)
A crash during loading, after selecting continue, at ~40% progress.

Third log: [Ryujinx_2020-11-28_19-54-00 - FEW third crash after 15 seconds.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5611100/Ryujinx_2020-11-28_19-54-00.-.FEW.third.crash.after.15.seconds.log)
Nearly identical to the first log, but I managed to run around a bit trying to avoid overloading the shader generation with fancy effects from attacks. As the game was running rather smoothly I attacked some of the enemies and the game crashed again.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by voidcat0** [comment]
> 
> 
> Updated

Definitely **not** playable. Still crashes in battles up to Ryujinx 6521. Sometimes in seconds, sometimes in minutes.

**Comment by gdkchan** [comment]
> 
> 
> > Updated
> 
> Definitely **not** playable. Still crashes in battles up to Ryujinx 6521. Sometimes in seconds, sometimes in minutes.

This is not helpful at all, at least include a log and more information about the crash.

**Comment by voidcat0** [comment]
> 
> 
> > > Updated
> > 
> > 
> > Definitely **not** playable. Still crashes in battles up to Ryujinx 6521. Sometimes in seconds, sometimes in minutes.
> 
> This is not helpful at all, at least include a log and more information about the crash.

Nothing (apart from the version of Ryujinx) changed from the last report I did some comments up above. Same behaviour, same symptoms.

**Comment by EmulationFanatic** [comment]
> > > > Updated
> > > 
> > > 
> > > Definitely **not** playable. Still crashes in battles up to Ryujinx 6521. Sometimes in seconds, sometimes in minutes.
> > 
> > 
> > This is not helpful at all, at least include a log and more information about the crash.
> 
> Nothing (apart from the version of Ryujinx) changed from the last report I did some comments up above. Same behaviour, same symptoms.

The game test I performed was done on version 1.0.0 of the game. Can you try with that version?

**Comment by voidcat0** [comment]
> 
> 
> > > > > Updated
> > > > 
> > > > 
> > > > Definitely **not** playable. Still crashes in battles up to Ryujinx 6521. Sometimes in seconds, sometimes in minutes.
> > > 
> > > 
> > > This is not helpful at all, at least include a log and more information about the crash.
> > 
> > 
> > Nothing (apart from the version of Ryujinx) changed from the last report I did some comments up above. Same behaviour, same symptoms.
> 
> The game test I performed was done on version 1.0.0 of the game. Can you try with that version?

I'll do a proper test with the latest game update version (no, I will not test old versions. while it would help gathr _some_ data, that won't be helping long term aka where the emulator should be aiming at) and latest Ryujinx version when I get the time. 

I had a crash happen on 6521, hence my comment. But Ryujinx only keeps three logs and I didn't save the file. I did look at it though and it was the array out of index error two of my earlier logs showed.

Also, please, don't simply update labels just because some time has passed. At least give an explanation as to why you deem it playable all of a sudden.

**Comment by EmulationFanatic** [comment]
> > > > > > Updated
> > > > > 
> > > > > 
> > > > > Definitely **not** playable. Still crashes in battles up to Ryujinx 6521. Sometimes in seconds, sometimes in minutes.
> > > > 
> > > > 
> > > > This is not helpful at all, at least include a log and more information about the crash.
> > > 
> > > 
> > > Nothing (apart from the version of Ryujinx) changed from the last report I did some comments up above. Same behaviour, same symptoms.
> > 
> > 
> > The game test I performed was done on version 1.0.0 of the game. Can you try with that version?
> 
> I'll do a proper test with the latest game update version (no, I will not test old versions. while it would help gather _some_ data, that won't be helping long term aka where the emulator should be aiming at) and latest Ryujinx version when I get the time.
> 
> I had a crash happen on 6521, hence my comment. But Ryujinx only keeps three logs and I didn't save the file. I did look at it though and it was the array out of index error two of my earlier logs showed.
> 
> Also, please, don't simply update labels just because some time has passed. At least give an explanation as to why you deem it playable all of a sudden.

Maybe you should give an explanation as to why you think the label was updated "just because enough time had passed". The mere suggestion of it is outrageous.

The OP was quite clearly updated at the same time the last comment "Updated" was added, with a current test reflecting the status of the game. With versions of the emulator, versions of the game, screenshots, logs.

**Comment by riperiperi** [comment]
> Maybe you should give an explanation as to why you think the label was updated "just because enough time had passed". The mere suggestion of it is outrageous.

Perhaps they didn't see that you edited in the new status to the first post, and just thought you changed the status without any explanation.

**Comment by jorgecotrinax** [comment]
My Hardware Specs :
CPU:  intel i7-8700
GPU: NVIDIA GTX 1060
RAM: 8GB
Can I Run It?

**Comment by alexwpi** [comment]
Using version 1.0.7116 the game is crashing during the dialog scene, in previous versions it was fully playable

**Comment by AliciaWhimsicott** [comment]
CPU: 7 5800X3D
GPU: Radeon RX5700
RAM: 16GB

Running on 1.1.774, the game gets past title screen and difficulty selection but always freezes within seconds of the first battle in the game, audio might persist but no it's completely locked up. Afterwards, attempting to boot the game will cause the emulator to hang (it can't seem to load all the shaders). Game version is 1.5.0, I've heard this might be a version-specific bug but haven't tried lower game versions.
