### ISSUE TITLE
SD GUNDAM G GENERATION CROSS RAYS

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2188]
#### Current on `master` : 1.0.5072

Crashes on launch.

```
Message: 'terminating with uncaught exception of type google::protobuf::FatalException: CH'

00:00:15.421 | ServiceLm Log: Guest log:
 Log level: Info
 Time: 11s
 Line: 0
 Filename: ''
 Function: ''
 Module: ''
 Thread: 'MainThread'
 ProgramName: 'gg-a_nx64_m.v100.normal'
 Message: 'ECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning):'

00:00:15.421 | ServiceLm Log: Guest log:
 Log level: Info
 Time: 11s
 Line: 0
 Filename: ''
 Function: ''
 Module: ''
 Thread: 'MainThread'
 ProgramName: 'gg-a_nx64_m.v100.normal'
 Message: ''

00:00:15.912 | HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x00519c10 __nnmusl_GetTlsValue
   sdk:0x004cbd84 Sub000000000e804d84
   sdk:0x004b1f88 Sub000000000e7eaf88
   sdk:0x004c7380 Sub000000000e800380
   sdk:0x004c9fb0 __cxa_get_exception_ptr
   sdk:0x004c9f1c Sub000000000e802f1c
   main:0x0069a35c Sub000000000869e35c
   main:0x00696ed0 Sub000000000869aed0
   main:0x004d2870 Sub00000000084d6870
   main:0x004d33b4 Sub00000000084d73b4
   main:0x004d1c20 Sub00000000084d5c20
   main:0x004d63f0 Sub00000000084da3f0
   main:0x004d6244 Sub00000000084da244
   main:0x0057bebc nnMain
   sdk:0x0029da2c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:00:15.914 | HLE.HostThread.11 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:00:15.914 | HLE.HostThread.2 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:00:15.915 | HLE.HostThread.15 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:00:15.915 | HLE.HostThread.12 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:00:15.915 | HLE.HostThread.14 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:00:15.915 | HLE.HostThread.13 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:00:15.947 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1384
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 63
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1154
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[SDGGGCR.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4995660/SDGGGCR.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by RealTabman** [comment]
The premium version of this game
**SD GUNDAM G GENERATION CROSS RAYS PREMIUM G SOUND EDITION - 010022900d3ec00** (game version 1.6.3)
shows the same behaviour as described in the first post; playable but with most map gfx missing on `master` 1.0.6872

Not sure if this game deserves it's own entry since it's essential the same as the non-premium version; it just includes all DLC (as extra downloads).

**Comment by EmulationFanatic** [comment]
@RealTabman if it is a different title ID, then it should have a separate issue. From your screenshot this indeed seems to be the case.

**Comment by EmulationFanatic** [comment]
Updated
