### ISSUE TITLE
Neverwinter Nights: Enhanced Edition

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2189]
#### Current on `master` : 1.0.5072

Crashes on launch.

```
ServiceAm SetTerminateResult: Result = 0x0001a80a (2010-0212).
00:01:23.952 | HLE.HostThread.7 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x0017ed3c Sub00000000105fed3c
   sdk:0x0017ee08 Sub00000000105fee08
   sdk:0x00097cec Sub0000000010517cec
   main:0x0002b0e8 Sub000000000802f0e8
   main:0x0003518c Sub000000000803918c
   main:0x00099a2c Sub000000000809da2c
   sdk:0x00506d20 Sub0000000010986d20
   sdk:0x00329e88 Sub00000000107a9e88
   sdk:0x0032e294 Sub00000000107ae294
   ??? Sub0000000000000000


00:01:23.954 | HLE.HostThread.2 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:23.954 | HLE.HostThread.3 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:23.954 | HLE.HostThread.5 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:23.954 | HLE.HostThread.6 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:23.983 | HLE.HostThread.7 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1384
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 63
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1154
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[NNEE.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4995728/NNEE.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by maximumxp** [comment]
Here to report the same is still happening.

**Comment by maximumxp** [comment]
The issues with the menu are fixed now on Vulkan, they look and work as intended. Sadly the game crashes after loading post-character creation.

**Comment by maximumxp** [comment]
I managed to get in game! 
![image](https://github.com/user-attachments/assets/3cbed6cb-f3be-4fa0-a602-172b11525577)

I will try a long playthrough and report if anything comes up.
Btw, it runs at an uncapped frame rate so it runs at 60fps natively, even if it didn't reach 30 on console.
