### ISSUE TITLE
SAMURAI SHODOWN

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2210]
#### Current on `master` : 1.0.5105

Game loads to title screen and then crashes after pressing A.

```
HLE.HostThread.62 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000011CFF93FD0.
00:02:53.669 | HLE.HostThread.62 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 331
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1154
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-07-31 14_36_01-Ryujinx 1 0 5105 - SAMURAI SHODOWN v1 00 (01008FC00D964000) (64-bit)](https://user-images.githubusercontent.com/62343878/89075575-bf0c3180-d33b-11ea-8ac8-b6e9663a2bd8.png)
![2020-07-31 14_36_07-Ryujinx 1 0 5105 - SAMURAI SHODOWN v1 00 (01008FC00D964000) (64-bit)](https://user-images.githubusercontent.com/62343878/89075577-bfa4c800-d33b-11ea-9e12-13c04da55921.png)
![2020-07-31 14_39_32-Ryujinx 1 0 5105 - SAMURAI SHODOWN v1 00 (01008FC00D964000) (64-bit)](https://user-images.githubusercontent.com/62343878/89075579-c03d5e80-d33b-11ea-9adc-9b63e819750f.png)
![2020-07-31 14_39_36-Ryujinx 1 0 5105 - SAMURAI SHODOWN v1 00 (01008FC00D964000) (64-bit)](https://user-images.githubusercontent.com/62343878/89075580-c03d5e80-d33b-11ea-9e1d-03848c26c6e3.png)

#### Log file :

[SS.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5008972/SS.zip)

**Comment by Cronos-0** [comment]
## SAMURAI SHODOWN

#### Game Update Version : 2.0.0

#### Current on `master` : 1.0.5292

Game version 1.0.0 and 2.0.0 now boot up and work fine.
This is the problem, the problem I am noticing right now
- The game is quite slow in story mode and versus mode here, including slow motion characters
- Some characters' textures are not rendered properly, such as gongsun li's pants and nakoruru looks like inferior rendered 3d models. And other characters
- Attack effects are sometimes entirely black (not all)
- The shadow of the character is shown as a black square for every character
- The game takes 5 - 10 minutes to load for Update 2.0.0 and all DLC before entering the game.

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-09-06 07-41-17-497](https://user-images.githubusercontent.com/35269098/92316474-e337ee00-f01e-11ea-90ff-2349b1f9e3cb.jpg)
![bandicam 2020-09-06 07-41-21-712](https://user-images.githubusercontent.com/35269098/92316475-e501b180-f01e-11ea-89a0-298df5ca47f7.jpg)
![bandicam 2020-09-06 07-41-47-368](https://user-images.githubusercontent.com/35269098/92316478-e9c66580-f01e-11ea-88ee-980bed326284.jpg)
![bandicam 2020-09-06 07-42-19-003](https://user-images.githubusercontent.com/35269098/92316480-ee8b1980-f01e-11ea-9dd7-b0c8567c1a65.jpg)
![bandicam 2020-09-06 07-42-24-855](https://user-images.githubusercontent.com/35269098/92316485-f945ae80-f01e-11ea-8877-0466892f9aa9.jpg)
![bandicam 2020-09-06 07-42-51-379](https://user-images.githubusercontent.com/35269098/92316487-fd71cc00-f01e-11ea-8ff5-2653a6749b11.jpg)
![bandicam 2020-09-06 07-43-14-211](https://user-images.githubusercontent.com/35269098/92316489-01055300-f01f-11ea-9622-a392ac3fe2ad.jpg)
![bandicam 2020-09-06 07-43-34-498](https://user-images.githubusercontent.com/35269098/92316492-082c6100-f01f-11ea-9c3d-4be7f3e526b9.jpg)
![bandicam 2020-09-06 07-43-43-158](https://user-images.githubusercontent.com/35269098/92316493-0b275180-f01f-11ea-88ab-87d73e3ade55.jpg)
![bandicam 2020-09-06 07-45-25-384](https://user-images.githubusercontent.com/35269098/92316497-167a7d00-f01f-11ea-9f3f-ce35ed431db5.jpg)
![bandicam 2020-09-06 07-45-41-475](https://user-images.githubusercontent.com/35269098/92316500-1f6b4e80-f01f-11ea-84a2-df718fcec638.jpg)
![bandicam 2020-09-06 07-45-53-316](https://user-images.githubusercontent.com/35269098/92316503-25612f80-f01f-11ea-8644-940c8bc33628.jpg)
![bandicam 2020-09-06 07-46-02-773](https://user-images.githubusercontent.com/35269098/92316506-2db96a80-f01f-11ea-966f-9b7ea5ce3c94.jpg)
![bandicam 2020-09-06 07-46-06-424](https://user-images.githubusercontent.com/35269098/92316509-327e1e80-f01f-11ea-8eda-10e62ca3dcc4.jpg)
![bandicam 2020-09-06 07-47-02-653](https://user-images.githubusercontent.com/35269098/92316512-4164d100-f01f-11ea-971b-b6d0ce759df9.jpg)
![bandicam 2020-09-06 07-47-49-449](https://user-images.githubusercontent.com/35269098/92316513-4590ee80-f01f-11ea-9c46-b8ffa73f68c8.jpg)
![bandicam 2020-09-06 07-47-19-573](https://user-images.githubusercontent.com/35269098/92316515-46c21b80-f01f-11ea-9f80-cc04f632281c.jpg)
