### ISSUE TITLE
Adventures of Bertram Fiddle EP1: A Dreadly Business

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2217]
#### Current on `master` : 1.0.5105

Loads through menus and then crashes at the end of the nvdec scene (or if you skip it) played after starting a new game.

```
HLE.HostThread.42 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000011ACF31FD0.
00:01:20.700 | ServiceAudio GetState: Stubbed. State: Playing
00:01:20.715 | ServiceAudio StopAudioRenderer: Stubbed. 
00:01:20.724 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:01:20.728 | HLE.HostThread.42 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 331
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1154
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-07-31 15_55_41-Ryujinx 1 0 5105 - Adventures of Bertram Fiddle EP1 _ A Dreadly Business v1 0 0 ](https://user-images.githubusercontent.com/62343878/89080581-7f971280-d346-11ea-9d0a-72ef6d55ade5.png)
![2020-07-31 15_55_58-Ryujinx 1 0 5105 - Adventures of Bertram Fiddle EP1 _ A Dreadly Business v1 0 0 ](https://user-images.githubusercontent.com/62343878/89080587-8160d600-d346-11ea-9a76-2c70abcacfc2.png)
![2020-07-31 15_56_12-Ryujinx 1 0 5105 - Adventures of Bertram Fiddle EP1 _ A Dreadly Business v1 0 0 ](https://user-images.githubusercontent.com/62343878/89080588-81f96c80-d346-11ea-93db-166467861862.png)

#### Log file :

[AoBFEADB.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5009194/AoBFEADB.log)

**Comment by benderscruffy** [comment]
using 1.0.7106
goes ingame now 
but the screen is black and you can hear the voices and sound fx and music

**Comment by benderscruffy** [comment]
change the status please

**Comment by EmulationFanatic** [comment]
Updated
