### ISSUE TITLE
Caretaker

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2221]
#### Current on `master` : 1.0.5105

Crashes after trying to launch for a couple of minutes.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.WriteInt64(IntPtr ptr, Int32 ofs, Int64 val)
   at System.Runtime.InteropServices.Marshal.WriteInt64(IntPtr ptr, Int64 val)
   at Ryujinx.Graphics.OpenGL.Queries.BufferedQuery.End() in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Queries\BufferedQuery.cs:line 55
   at Ryujinx.Graphics.OpenGL.Queries.CounterQueueEvent.Complete() in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Queries\CounterQueueEvent.cs:line 43
   at Ryujinx.Graphics.OpenGL.Queries.CounterQueue.QueueReport(EventHandler`1 resultHandler) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Queries\CounterQueue.cs:line 105
   at Ryujinx.Graphics.OpenGL.Queries.Counters.QueueReport(CounterType type, EventHandler`1 resultHandler) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Queries\Counters.cs:line 28
   at Ryujinx.Graphics.OpenGL.Renderer.ReportCounter(CounterType type, EventHandler`1 resultHandler) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Renderer.cs:line 96
   at Ryujinx.Graphics.Gpu.Engine.Methods.ReportCounter(GpuState state, ReportCounterType type) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodReport.cs:line 98
   at Ryujinx.Graphics.Gpu.Engine.Methods.Report(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodReport.cs:line 32
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 142
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 68
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[Caretaker.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5010317/Caretaker.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Djipi71** [comment]
Test with 6575Build : Same shader cache probem , we must delete shader cache to play again. The game now render correctly
![Sans titre-1](https://user-images.githubusercontent.com/35375131/108035598-6c743780-7037-11eb-89ae-4589507ea997.png)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
