### ISSUE TITLE
Ashen

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2230]
#### Current on `master` : 1.0.5123

Crashes while at the character creation screen.

```
ServiceLm Log: Guest log:
 Log level: Info
 Time: 308s
 Line: 117
 Filename: 'C:\Users\r.bovsunovskii\Documents\ashen\ashen_ue4\Engine\Source\Runtime\Core\Private\Switch\SwitchPlatformMisc.cpp'
 Function: 'LocalPrint'
 Module: ''
 Thread: 'GameThread'
 ProgramName: 'Ashen-Switch-Shipping'
 Message: '[2020.08.03-15.00.32:000][717]LogSwitch: Display: =======NIFM RECONNECTION STARTING UP======= 
 Waiting for Nifm to come up...'

00:05:11.623 | ServiceNifm Submit: Stubbed. 
00:05:11.623 | ServiceNifm GetRequestState: Stubbed. 
00:05:11.623 | ServiceNifm GetResult: Stubbed. 
00:05:11.624 | ServiceLm Log: Guest log:
 Log level: Info
 Time: 308s
 Line: 117
 Filename: 'C:\Users\r.bovsunovskii\Documents\ashen\ashen_ue4\Engine\Source\Runtime\Core\Private\Switch\SwitchPlatformMisc.cpp'
 Function: 'LocalPrint'
 Module: ''
 Thread: 'GameThread'
 ProgramName: 'Ashen-Switch-Shipping'
 Message: '[2020.08.03-15.00.32:000][717]LogSwitch: Display:  Nifm not available. Failed to handle network request error.'

00:05:12.042 | ServiceNv Create: Created map 82 with size 0x00400000!
00:05:12.241 | ServiceNv DecrementMapRefCount: Deleted map 70!
00:05:12.250 | ServiceNv DecrementMapRefCount: Deleted map 71!
00:05:12.287 | ServiceNv DecrementMapRefCount: Deleted map 79!
00:05:12.348 | ServiceNv Create: Created map 70 with size 0x00200000!
00:05:12.412 | ServiceNv DecrementMapRefCount: Deleted map 80!
00:05:12.538 | ServiceNv Create: Created map 71 with size 0x00400000!
00:05:12.557 | ServiceNv Create: Created map 79 with size 0x00400000!
00:05:12.574 | ServiceNv Create: Created map 80 with size 0x00400000!
00:05:12.613 | ServiceNv Create: Created map 84 with size 0x00400000!
00:05:12.681 | ServiceNv Create: Created map 85 with size 0x00400000!
00:05:12.738 | ServiceNv Create: Created map 87 with size 0x00400000!
00:05:12.799 | ServiceNv Create: Created map 88 with size 0x00400000!
00:05:12.863 | GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000B283E0000.
00:05:12.932 | GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 342
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 503
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureInfo info, TextureSearchFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 728
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 35
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 219
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 156
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 296
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 115
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 143
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 334
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-08-03 08_56_37-Ryujinx 1 0 5123 - Ashen v1 0 0 (010027B00E40E000) (64-bit)](https://user-images.githubusercontent.com/62343878/89196841-0414ab80-d568-11ea-9739-8921bf545289.png)
![2020-08-03 08_56_46-Ryujinx 1 0 5123 - Ashen v1 0 0 (010027B00E40E000) (64-bit)](https://user-images.githubusercontent.com/62343878/89196843-04ad4200-d568-11ea-82c7-386fa821c0e2.png)
![2020-08-03 08_59_26-Ryujinx 1 0 5123 - Ashen v1 0 0 (010027B00E40E000) (64-bit)](https://user-images.githubusercontent.com/62343878/89196849-070f9c00-d568-11ea-8da1-d28882be9598.png)
![2020-08-03 08_59_34-Ryujinx 1 0 5123 - Ashen v1 0 0 (010027B00E40E000) (64-bit)](https://user-images.githubusercontent.com/62343878/89196865-0b3bb980-d568-11ea-9b98-de6a8dbe46f0.png)
![2020-08-03 08_59_47-Ryujinx 1 0 5123 - Ashen v1 0 0 (010027B00E40E000) (64-bit)](https://user-images.githubusercontent.com/62343878/89196869-0d057d00-d568-11ea-8ad1-9ee576faa4b6.png)
![2020-08-03 09_00_38-Ryujinx 1 0 5123 - Ashen v1 0 0 (010027B00E40E000) (64-bit)](https://user-images.githubusercontent.com/62343878/89196876-0f67d700-d568-11ea-8c1a-56cadb3cd189.png)

#### Log file :

[Ashen.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5016748/Ashen.zip)

**Comment by benderscruffy** [comment]
using 1.0.7108
stuck on the loading screen in a loop
![ryujinx_capture_2021-11-26_17-18-17](https://user-images.githubusercontent.com/2696404/143556947-b704b76e-1534-43fe-845c-124448665c14.png)

**Comment by EmulationFanatic** [comment]
Updated
