### ISSUE TITLE
Drawngeon: Dungeons of Ink and Paper

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2250]
#### Current on `master` : 1.0.5131

Displays minor graphical corruption in menus and then crashes when attempting to progress to in-game.

```
00:03:12.048 |G| ServiceLm Log: Guest Log:
  Log level: Info
    Time: 187s
    Line: 30
    Filename: 'c:/hudson/ZeusBase/ZeusGreen/GameMaker/Runner/VC_Runner/Files/Base/Switch/ConsoleM.cpp'
    Function: 'Output'
    Module: ''
    Thread: 'MainThread'
    ProgramName: 'VCTemplate'
    Message: 'OpenGL Error Check: glFramebufferTexture2DOES: 0x0502'

00:03:12.066 |G| ServiceLm Log: Guest Log:
  Log level: Info
    Time: 187s
    Line: 30
    Filename: 'c:/hudson/ZeusBase/ZeusGreen/GameMaker/Runner/VC_Runner/Files/Base/Switch/ConsoleM.cpp'
    Function: 'Output'
    Module: ''
    Thread: 'MainThread'
    ProgramName: 'VCTemplate'
    Message: 'CreateTexture(): Ooops frame buffer Kaput(1) 0x8cd7 (36055)'

00:03:12.482 |I| HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   main:0x0006cb54 Sub0000000008070b54
   subsdk0:0x007acfc4 Sub0000000009545fc4
   subsdk0:0x007ac654 Sub0000000009545654
   subsdk0:0x007ac8e4 Sub00000000095458e4
   main:0x00081b08 Sub0000000008085b08
   main:0x00080744 Sub0000000008084744
   main:0x000b465c Sub00000000080b865c
   main:0x00108af0 Sub000000000810caf0
   main:0x000eff80 Sub00000000080f3f80
   main:0x000104e0 Sub00000000080144e0
   main:0x00012dac Sub0000000008016dac
   main:0x0001293c Sub000000000801693c
   main:0x0001b848 Sub000000000801f848
   main:0x0001b95c Sub000000000801f95c
   main:0x0007c10c Sub000000000808010c
   main:0x0007a64c Sub000000000807e64c
   main:0x000104e0 Sub00000000080144e0
   main:0x00012dac Sub0000000008016dac
   main:0x0001293c Sub000000000801693c
   main:0x0001b848 Sub000000000801f848
   main:0x0001b95c Sub000000000801f95c
   main:0x0007c10c Sub000000000808010c
   main:0x0007a64c Sub000000000807e64c
   main:0x000104e0 Sub00000000080144e0
   main:0x00012dac Sub0000000008016dac
   main:0x0001293c Sub000000000801693c
   main:0x0001b848 Sub000000000801f848
   main:0x0001b95c Sub000000000801f95c
   main:0x0007c10c Sub000000000808010c
   main:0x0007a64c Sub000000000807e64c
   main:0x0007a89c Sub000000000807e89c
   main:0x000a9f48 Sub00000000080adf48
   main:0x000ac5d8 Sub00000000080b05d8
   main:0x000011a0 nnMain
   sdk:0x0029da2c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:03:12.595 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000b1f53f0 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1109
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 134
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1149
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1340

#### Screenshots :

![2020-08-05 08_06_08-Ryujinx 1 0 5131 - Drawngeon_ Dungeons of Ink and Paper v1 0 0 (0100B7E0102E4000](https://user-images.githubusercontent.com/62343878/89422733-f2134400-d6f2-11ea-921b-ab1bc3c75547.png)
![2020-08-05 08_06_32-Ryujinx 1 0 5131 - Drawngeon_ Dungeons of Ink and Paper v1 0 0 (0100B7E0102E4000](https://user-images.githubusercontent.com/62343878/89422735-f2abda80-d6f2-11ea-9158-400287ad5bc4.png)
![2020-08-05 08_06_38-Ryujinx 1 0 5131 - Drawngeon_ Dungeons of Ink and Paper v1 0 0 (0100B7E0102E4000](https://user-images.githubusercontent.com/62343878/89422743-f4759e00-d6f2-11ea-8c57-191b2a321ea3.png)

#### Log file :

[DDoIaP.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5028919/DDoIaP.log)

**Comment by benderscruffy** [comment]
goes ingame now with graphic glitches
![drawngeon](https://user-images.githubusercontent.com/2696404/100499273-267ba600-31a3-11eb-9dfb-080fea808677.PNG)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
