### ISSUE TITLE
Baba Is You

### ISSUE THREAD

**Issue by riperiperi** [Ryujinx/Ryujinx-Games-List#227]
#### Current on `master` :

* Build Version :1.0.3602

No matter what your controller setup is, the game attempts to use the controller applet and crashes.

```
00:00:17.260 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Controller applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system) in D:\Games\RyuWork\Ryujinx\Ryujinx.HLE\HOS\Applets\AppletManager.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system) in D:\Games\RyuWork\Ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context) in D:\Games\RyuWork\Ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\SystemAppletProxy\ILibraryAppletCreator.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in D:\Games\RyuWork\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in D:\Games\RyuWork\Ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in D:\Games\RyuWork\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/648

**Comment by B3astTech** [comment]
Need's Updated

**Comment by riperiperi** [comment]
Updated for `master` @ `1.0.4135`

**Comment by EmulationFanatic** [comment]
Updated

**Comment by F1ReB4LL** [comment]
The game works very slow and generates lots of events that go into the log (about 15MBs per minute), I guess these facts are connected somehow (very similar to what happens in Breakout Recharged and Cyber Shadow).

[Ryujinx_1.1.182_2022-07-16_20-37-55.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9126293/Ryujinx_1.1.182_2022-07-16_20-37-55.log)

**Comment by riperiperi** [comment]
The controller applet is triggering constantly. Make sure that only one controller is bound. It’s been a while since I tested so maybe something went wrong.

**Comment by riperiperi** [comment]
![image](https://user-images.githubusercontent.com/6294155/179370521-12d1e384-50ce-4f3a-9f82-a7e4d5cabd60.png)
![image](https://user-images.githubusercontent.com/6294155/179370524-57a42991-1c9c-4ea8-a2f2-d9fbc05fd4fb.png)
It does seem to run fine here. For the record, I'm in docked mode, and my only controller is a Pro Controller in Player 1.

**Comment by F1ReB4LL** [comment]
Yep, turned out the slowdowns were caused by an incorrect controllers combination (Joycon Pair for P1, Joycon Right for P2, both enabled), works with a proper speed if to disable P2 and to change P1 controller to another type.
