### ISSUE TITLE
KukkoroDays

### ISSUE THREAD

**Issue by Seker-0** [Ryujinx/Ryujinx-Games-List#2276]
#### Current on `master` : 1.0.5138

The game crashes while starting the game in the title screen.

```
Process: Application, PID: 81
   sdk:0x0051da20 __nnmusl_GetTlsValue
   sdk:0x004da9dc Sub000000002d3579dc
   sdk:0x004ffd58 quick_exit
   main:0x0025839c Sub000000000825c39c
   main:0x0025d664 nnMain
   sdk:0x000a1d9c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:02:32.573 |W| HLE.HostThread.2 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:02:32.597 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1384
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 54
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1149
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Hardware Specs :

GPU : 1060
CPU : I5 8400
RAM : 16GB

#### Screenshots :

![bandicam 2020-08-07 19-21-58-469](https://user-images.githubusercontent.com/35269098/89645506-24d05e80-d8e4-11ea-9eaf-721feb318b17.jpg)
![bandicam 2020-08-07 19-22-09-363](https://user-images.githubusercontent.com/35269098/89645518-2863e580-d8e4-11ea-8f2d-40f005c875bf.jpg)
![bandicam 2020-08-07 19-16-17-396](https://user-images.githubusercontent.com/35269098/89645529-2c900300-d8e4-11ea-9308-1e95ecd22305.jpg)
![bandicam 2020-08-07 19-18-15-050](https://user-images.githubusercontent.com/35269098/89645546-36196b00-d8e4-11ea-9b04-3a62cdf1f36e.jpg)

#### Logs :

[KKRD.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5041348/KKRD.log)

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by benderscruffy** [comment]
using 1.0.7106
goes ingame now
no problems so far
![ryujinx_capture_2021-11-21_12-51-12](https://user-images.githubusercontent.com/2696404/142750077-a528228c-bee5-4b05-ada7-a711d967e689.png)
![ryujinx_capture_2021-11-21_12-51-18](https://user-images.githubusercontent.com/2696404/142750079-e94b414e-5b9e-4750-a663-910af60e03c1.png)
![ryujinx_capture_2021-11-21_12-51-24](https://user-images.githubusercontent.com/2696404/142750081-a88a24c7-775f-4c10-a585-148d7a08c72a.png)
![ryujinx_capture_2021-11-21_12-53-19](https://user-images.githubusercontent.com/2696404/142750083-97179271-1676-4494-bd3a-58cf1e0fae79.png)

**Comment by benderscruffy** [comment]
change the status please
