### ISSUE TITLE
Oddworld: Stranger's Wrath HD

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2282]
#### Current on `master` : 1.0.5142

Loads to title screen but then crashes after starting a new game.

```
HLE.HostThread.48 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x002df810 void* nn::nlibsdk::heap::TlsHeapCache::AllocFuncAlgnMode0<std::__1::integral_constant<bool, true> >(nn::nlibsdk::heap::TlsHeapCache*, unsigned long, unsigned long)
   sdk:0x002e77ac nn::mem::StandardAllocator::Allocate(unsigned long, unsigned long)
   main:0x004a3784 aligned_alloc
   main:0x00460b50 Sub0000000008464b50
   subsdk1:0x00207ccc android::NuCachedSource2::fetchInternal()
   subsdk1:0x0020771c android::NuCachedSource2::onFetch()
   subsdk1:0x00208bd8 android::AHandlerReflector<android::NuCachedSource2>::onMessageReceived(android::sp<android::AMessage> const&)
   subsdk1:0x0015837c android::ALooperRoster::deliverMessage(android::sp<android::AMessage> const&)
   subsdk1:0x001570d4 android::ALooper::loop()
   subsdk1:0x0022571c android::SfThread::_threadLoop(void*)
   sdk:0x003344b8 Sub0000000009bb14b8
   sdk:0x00338984 Sub0000000009bb5984
   ??? Sub0000000000000000


00:01:37.917 |E| HLE.HostThread.48 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x2A2B2B2B2B292949.
00:01:37.999 |E| HLE.HostThread.48 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 489
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 325
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1149
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

#### Screenshots :

![2020-08-07 09_24_16-Ryujinx 1 0 5142 - Oddworld_ Stranger's Wrath HD v1 0 0 (01002EA00ABBA000) (64-b](https://user-images.githubusercontent.com/62343878/89661916-8e268200-d890-11ea-84a7-c02434b26626.png)
![2020-08-07 09_25_04-Ryujinx 1 0 5142 - Oddworld_ Stranger's Wrath HD v1 0 0 (01002EA00ABBA000) (64-b](https://user-images.githubusercontent.com/62343878/89661950-9a124400-d890-11ea-97a2-f0ac2f818220.png)
![2020-08-07 09_25_12-Ryujinx 1 0 5142 - Oddworld_ Stranger's Wrath HD v1 0 0 (01002EA00ABBA000) (64-b](https://user-images.githubusercontent.com/62343878/89661962-9c749e00-d890-11ea-8c5d-303cdb633254.png)
![2020-08-07 09_25_22-Ryujinx 1 0 5142 - Oddworld_ Stranger's Wrath HD v1 0 0 (01002EA00ABBA000) (64-b](https://user-images.githubusercontent.com/62343878/89661993-a5fe0600-d890-11ea-85fc-5a95a65f3aea.png)

#### Log file :

[OSWHD.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5042305/OSWHD.log)

**Comment by benderscruffy** [comment]
using 1.0.7107
goes ingame now
![ryujinx_capture_2021-11-23_17-19-50](https://user-images.githubusercontent.com/2696404/142998967-69330e3a-7260-4579-a510-603f2ef275a7.png)
![ryujinx_capture_2021-11-23_17-20-08](https://user-images.githubusercontent.com/2696404/142998978-c42e7daa-ca63-429d-8bc8-2d1431b72fa0.png)
![ryujinx_capture_2021-11-23_17-21-08](https://user-images.githubusercontent.com/2696404/142998992-161e6d94-871e-41dd-acce-24b5b0988a69.png)
![ryujinx_capture_2021-11-23_17-21-32](https://user-images.githubusercontent.com/2696404/142999009-ed61c9cb-d394-462c-b436-6a87fb3a673b.png)
