### ISSUE TITLE
Ember

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2284]
#### Current on `master` : 1.0.5142

Loads with only a black screen and audio playing. Menu audio cues can be heard, and the title appears to go in-game based on the sound. Pressing buttons summons a gtk swkbd input window. At one point a gray menu bar is shown.
Crashes shortly after that.

```
HLE.HostThread.42 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   subsdk1:0x00288e20 android::OMX::emptyBuffer(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, long long)
   subsdk1:0x002c58e4 android::ACodec::BaseState::onInputBufferFilled(android::sp<android::AMessage> const&)
   subsdk1:0x002c41bc android::ACodec::BaseState::onMessageReceived(android::sp<android::AMessage> const&)
   subsdk1:0x0025ae58 android::AHierarchicalStateMachine::handleMessage(android::sp<android::AMessage> const&)
   subsdk1:0x0025cebc android::ALooperRoster::deliverMessage(android::sp<android::AMessage> const&)
   subsdk1:0x0025bc14 android::ALooper::loop()
   subsdk1:0x0032a25c android::SfThread::_threadLoop(void*)
   sdk:0x000c7058 Sub000000000badd058
   sdk:0x000cb524 Sub000000000bae1524
   ??? Sub0000000000000000


00:05:13.778 |E| HLE.HostThread.42 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x1010101010101028.
00:05:13.866 |E| HLE.HostThread.42 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 489
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 325
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
   at ARMeilleure.Instructions.NativeInterface.ReadByte(UInt64 address) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 172
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1149
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-08-07 11_44_31-Ryujinx 1 0 5142 - Ember v1 10 0 (010041A00FEC6000) (64-bit)](https://user-images.githubusercontent.com/62343878/89673400-845a4a00-d8a3-11ea-9828-da01c35d8989.png)

#### Log file :

[Ember.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5042875/Ember.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6847

**Comment by EmulationFanatic** [comment]
Updated
