### ISSUE TITLE
Fitness Boxing

### ISSUE THREAD

**Issue by Seker-0** [Ryujinx/Ryujinx-Games-List#229]
#### Current on `master` : 1.0.3624

This error occurs when pressing the L + R button to start the game.

```
00:02:43.997 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Controller applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Applets\AppletManager.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\SystemAppletProxy\ILibraryAppletCreator.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
#### Log file : 
[Ryujinx.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4144760/Ryujinx.log)

#### Screenshots : 
![bandicam 2020-02-02 23-59-25-687](https://user-images.githubusercontent.com/35269098/73611873-29f0e000-4619-11ea-8424-b4c62a9f16d7.jpg)
![bandicam 2020-02-03 00-00-40-629](https://user-images.githubusercontent.com/35269098/73611874-2eb59400-4619-11ea-9712-9a66559d1391.jpg)
![bandicam 2020-02-03 00-00-49-152](https://user-images.githubusercontent.com/35269098/73611884-442abe00-4619-11ea-87c4-197ab796b2ba.jpg)
![bandicam 2020-02-03 00-01-08-110](https://user-images.githubusercontent.com/35269098/73611886-48ef7200-4619-11ea-930e-7adacea91529.jpg)

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## Fitness Boxing

#### Current on `master` : 1.0.4573

Game loads and plays at a somewhat low FPS, and would likely be playable if motion controls were implemented.

#### Screenshots :
![2020-05-17 07_50_36-](https://user-images.githubusercontent.com/62343878/82149270-deeb8900-9813-11ea-983f-e1c4537ff088.png)
![2020-05-17 07_51_21-Ryujinx 1 0 4573 - Fitness Boxing v1 0 0 (0100E7300AAD4000) (64-bit)](https://user-images.githubusercontent.com/62343878/82149283-e14de300-9813-11ea-8c4d-cee60ea92740.png)
![2020-05-17 07_51_26-Ryujinx 1 0 4573 - Fitness Boxing v1 0 0 (0100E7300AAD4000) (64-bit)](https://user-images.githubusercontent.com/62343878/82149291-e27f1000-9813-11ea-9c65-169ff8eb287c.png)
![2020-05-17 07_51_39-Ryujinx 1 0 4573 - Fitness Boxing v1 0 0 (0100E7300AAD4000) (64-bit)](https://user-images.githubusercontent.com/62343878/82149309-e6ab2d80-9813-11ea-8a7d-586396ff87d6.png)
![2020-05-17 07_52_28-Ryujinx 1 0 4573 - Fitness Boxing v1 0 0 (0100E7300AAD4000) (64-bit)](https://user-images.githubusercontent.com/62343878/82149318-e90d8780-9813-11ea-9656-9d291eaf882a.png)
![2020-05-17 07_53_29-Ryujinx 1 0 4573 - Fitness Boxing v1 0 0 (0100E7300AAD4000) (64-bit)](https://user-images.githubusercontent.com/62343878/82149323-ead74b00-9813-11ea-8d05-17bc3c66738b.png)
![2020-05-17 07_55_31-Ryujinx 1 0 4573 - Fitness Boxing v1 0 0 (0100E7300AAD4000) (64-bit)](https://user-images.githubusercontent.com/62343878/82149334-ef036880-9813-11ea-9846-96cb5841833e.png)
![2020-05-17 07_55_33-Ryujinx 1 0 4573 - Fitness Boxing v1 0 0 (0100E7300AAD4000) (64-bit)](https://user-images.githubusercontent.com/62343878/82149348-f296ef80-9813-11ea-9b3c-122e6d2c90ef.png)


#### Log file :

[FitnessBoxing.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4640359/FitnessBoxing.zip)

**Comment by GoffyDude** [comment]
Updated
