### ISSUE TITLE
CARRION

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2297]
#### Current on `master` : 1.0.5152

Game crashes on boot
```
00:00:22.269 |I| HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   main:0x0049dbcc Sub00000000084a1bcc
   main:0x002e4fb0 Sub00000000082e8fb0
   main:0x005a5b4c Sub00000000085a9b4c
   main:0x005a6080 Sub00000000085aa080
   main:0x004c58f0 Sub00000000084c98f0
   main:0x009a9458 nnMain
   sdk:0x000a11ec nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:00:22.269 |E| HLE.HostThread.0 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:22.323 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 342
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
```

#### Log file :

[carrion.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5047764/carrion.log)

**Comment by SeraUX** [comment]
Updated
