### ISSUE TITLE
Panzer Paladin

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2303]
#### Current on `master` : 1.0.5152

Game crashes on boot with an missing service error

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IGeneralService: 5

Guest Stack Trace:
Process: Application, PID: 81
   subsdk1:0x00289ac4 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 26, 380ul> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 26, 380ul> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::BufferClientArgumentType, unsigned int)
   subsdk1:0x00287ed8 nn::sf::cmif::client::detail::CmifProxyImpl<nn::nifm::detail::IGeneralService, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::nifm::detail::IGeneralService, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_GetCurrentNetworkProfile(nn::sf::Out<nn::nifm::detail::sf::NetworkProfileData, void>)
   subsdk1:0x0028cefc nn::nifm::GetCurrentNetworkProfile(nn::nifm::NetworkProfileData*)
   subsdk1:0x0028d6b4 nn::nifm::GetCurrentProxySetting(nn::nifm::ProxySetting*)
   main:0x0332387c Sub000000000b32787c
   main:0x0331ca08 Sub000000000b320a08
   main:0x0331c128 Sub000000000b320128
   main:0x03308dcc Sub000000000b30cdcc
   main:0x03308b38 Sub000000000b30cb38
   main:0x032fbf14 Sub000000000b2fff14
   main:0x00c8d684 Sub0000000008c91684
   main:0x00c8d490 Sub0000000008c91490
   main:0x00b180c0 Sub0000000008b1c0c0
   main:0x00a18358 Sub0000000008a1c358
   main:0x00a17be8 Sub0000000008a1bbe8
   main:0x000141c0 Sub00000000080181c0
   main:0x00014290 Sub0000000008018290
   subsdk1:0x000d0108 Sub000000000f40c108
   subsdk1:0x000d48d4 Sub000000000f4108d4
   ??? Sub0000000000000000

Buffer Information:
	RecvListBuff:
	Position: 0x00000011bb103ee0 Size: 0x000000000000017c

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  05 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  E0 3E 10 BB 11 00 7C 01   ········à>·»··|·

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/643

#### Log file :

[panzer-paladin.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5048337/panzer-paladin.log)

**Comment by EmulationFanatic** [comment]
Updated
