### ISSUE TITLE
Monster Jam Steel Titans

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2326]
#### Current on `master` : 1.0.5155

Crashes in menus/loading screens.

```
GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000009D23E0000.
00:04:29.722 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 342
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 503
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureInfo info, TextureSearchFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 728
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 35
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 219
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 156
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 296
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 115
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 143
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 334
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-08-11 16_12_26-Ryujinx 1 0 5155 - Monster Jam Steel Titans v1 0 1 (010095C00F354000) (64-bit)](https://user-images.githubusercontent.com/62343878/89954238-f5746700-dbed-11ea-9b1b-ec3fcec3980e.png)
![2020-08-11 16_12_37-Ryujinx 1 0 5155 - Monster Jam Steel Titans v1 0 1 (010095C00F354000) (64-bit)](https://user-images.githubusercontent.com/62343878/89954242-f6a59400-dbed-11ea-8892-f51b4d6c438a.png)
![2020-08-11 16_13_30-Ryujinx 1 0 5155 - Monster Jam Steel Titans v1 0 1 (010095C00F354000) (64-bit)](https://user-images.githubusercontent.com/62343878/89954248-fb6a4800-dbed-11ea-89b6-37bfce057216.png)
![2020-08-11 16_13_53-Ryujinx 1 0 5155 - Monster Jam Steel Titans v1 0 1 (010095C00F354000) (64-bit)](https://user-images.githubusercontent.com/62343878/89954251-fc02de80-dbed-11ea-9d9a-e9fc46cab595.png)
![2020-08-11 16_14_53-Ryujinx 1 0 5155 - Monster Jam Steel Titans v1 0 1 (010095C00F354000) (64-bit)](https://user-images.githubusercontent.com/62343878/89954270-04f3b000-dbee-11ea-98c1-45e1da454a91.png)

#### Log file :

[MJST.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5059727/MJST.log)

**Comment by benderscruffy** [comment]
using 1.0.7104
crashes out at the same place just as the woman goes to speak in the tutorial 
but with a new error now
00:06:48.991 |E| HLE.GuestThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason)
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e)
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[Ryujinx_1.0.7104_2021-11-14_17-36-08.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7533496/Ryujinx_1.0.7104_2021-11-14_17-36-08.log)
