### ISSUE TITLE
Monster Energy Supercross - The Official Videogame 3

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2332]
#### Current on `master` : 1.0.5155

Crashes in intro splash screens.

```
GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000000F6BB0000.
00:03:29.868 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 342
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyBuffer(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyBuffer.cs:line 101
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 334
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-08-12 07_36_29-Ryujinx 1 0 5155 - Monster Energy Supercross - The Official Videogame 3 v1 0 0 (](https://user-images.githubusercontent.com/62343878/90021796-f7cad580-dc6e-11ea-9ec6-a54d2f525251.png)
![2020-08-12 07_36_39-Ryujinx 1 0 5155 - Monster Energy Supercross - The Official Videogame 3 v1 0 0 (](https://user-images.githubusercontent.com/62343878/90021807-fac5c600-dc6e-11ea-995a-3285612055c6.png)
![2020-08-12 07_36_49-Ryujinx 1 0 5155 - Monster Energy Supercross - The Official Videogame 3 v1 0 0 (](https://user-images.githubusercontent.com/62343878/90021810-fbf6f300-dc6e-11ea-8acf-02bbef666670.png)
![2020-08-12 07_38_19-Ryujinx 1 0 5155 - Monster Energy Supercross - The Official Videogame 3 v1 0 0 (](https://user-images.githubusercontent.com/62343878/90021816-fc8f8980-dc6e-11ea-9253-be94819bdaf9.png)
![2020-08-12 07_38_23-Ryujinx 1 0 5155 - Monster Energy Supercross - The Official Videogame 3 v1 0 0 (](https://user-images.githubusercontent.com/62343878/90021834-00bba700-dc6f-11ea-9387-474ccc015b32.png)

#### Log file :

[MESTOV3.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5063034/MESTOV3.log)

**Comment by EmulationFanatic** [comment]
Updated
