### ISSUE TITLE
Tangledeep

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2337]
#### Current on `master` : 1.0.5155

Game crashes during the animation before the main menu appears.

```
00:01:10.400 |E| HLE.HostThread.72 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000011D7498FD0.
00:01:10.441 |E| HLE.HostThread.72 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 331
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1149
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

#### Log file :

[tangledeep.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5063458/tangledeep.log)

**Comment by benderscruffy** [comment]
using 1.0.6229
still the same issue
