### ISSUE TITLE
Tokyo Mirage Sessions #FE Encore

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx-Games-List#234]
#### Current on `master` : 1.0.3691

*32bit is not in the latest master 1.0.3691 *

```
Last error returned.
HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000020191c (opcode 0xe6c31002) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1132
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 123
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 66
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 22
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 76
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1144
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 162
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

**Comment by AcK77** [comment]
Needs an update!

**Comment by zhoudecheng** [comment]
However, the latest version is stuck for a while after running

**Comment by Seker-0** [comment]
#### Current on `master` : 1.0.3844

- 32 bit is in the mastter now
- game freezes and crashes after starting the game
- I tried to use save but it doesn't work as well. The game crashes immediately
- I've tested older versions. It works for save

#### Log file : 
[Ryujinx_2563-03-06_18-03-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4298020/Ryujinx_2563-03-06_18-03-49.log)

#### Outstanding Issues:


#### Screenshots : 
![bandicam 2020-03-06 18-04-48-640](https://user-images.githubusercontent.com/35269098/76079104-8d827a80-5fd6-11ea-9318-9f4b02b91c1d.jpg)
![bandicam 2020-03-06 18-06-42-548](https://user-images.githubusercontent.com/35269098/76079132-9bd09680-5fd6-11ea-88af-4501c1a1bd96.jpg)
![bandicam 2020-03-06 18-08-16-208](https://user-images.githubusercontent.com/35269098/76079142-a25f0e00-5fd6-11ea-9ed0-abd263f37c16.jpg)
![bandicam 2020-03-06 18-08-30-225](https://user-images.githubusercontent.com/35269098/76079149-a559fe80-5fd6-11ea-803f-6fa8f8abf2a4.jpg)

#### Screenshots Old ver : 
![bandicam 2020-02-10 04-19-22-843](https://user-images.githubusercontent.com/35269098/76079458-4648b980-5fd7-11ea-8d98-83f552006d9c.jpg)
![bandicam 2020-02-07 04-37-45-484](https://user-images.githubusercontent.com/35269098/76079493-52cd1200-5fd7-11ea-820f-0ec546e98299.jpg)
![bandicam 2020-02-07 04-33-52-363](https://user-images.githubusercontent.com/35269098/76079547-75f7c180-5fd7-11ea-815f-374510a88808.jpg)
![bandicam 2020-02-07 03-20-20-484](https://user-images.githubusercontent.com/35269098/76079563-7ee89300-5fd7-11ea-9ddf-d7d1e90c733f.jpg)
![bandicam 2020-02-07 03-18-17-855](https://user-images.githubusercontent.com/35269098/76079600-90319f80-5fd7-11ea-81cc-283954294c60.jpg)
![bandicam 2020-02-07 03-16-13-818](https://user-images.githubusercontent.com/35269098/76079664-b5bea900-5fd7-11ea-88fd-1ba6eed9d2b9.jpg)
![bandicam 2020-02-06 13-46-51-350](https://user-images.githubusercontent.com/35269098/76079671-ba835d00-5fd7-11ea-8084-79e5e5ea6b23.jpg)

**Comment by Seker-0** [comment]
## Tokyo Mirage Sessions #FE Encore

#### Current on `master` : 1.0.4751

This game can be fully played. Previously, the game would randomly crash every time
All cutscene are black. You can skip the cutscene because nvdec is not currently in use

#### Hardware Specs :

GPU : NVIDIA GTX 1060
CPU : i5-8400
RAM : 16GB

#### Screenshots :

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Emogop** [comment]
After beating the game solely on Ryu here is what I have to say.The game is super stable, didn't crash even once. But there are a number of minor issues stiil present as of 1.1.166.
1. Some longer cutscenes and ad-lib (duo) performances tend to glitch but only when first time playing. I guess slight desynch due to shader compilation is the reason. But you can press B button to skip them.
2. https://github.com/Ryujinx/Ryujinx/issues/3261 Also the overbloom is noticible when an orb is emerging through the character's chest.
3. Some cutscenes have DoF effect and it's not working as it should, inverting the resulting image in terms of what should be focused and what should be blurred. But these cutscenes are few and the effect is not intensive.
My specs: I7 6700, GTX 1060
![Screenshot_109](https://user-images.githubusercontent.com/42875723/177738904-6bc4d567-0121-4843-b901-47c6d936b97e.png)
