### ISSUE TITLE
Monster Blast

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2340]
#### Current on `master` : 1.0.5155

game crashes on start

```
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 489
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 325
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Read[T](UInt64 gpuVa) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 58
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(IGpuAccessor gpuAccessor, Block block, UInt64 limitAddress, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 219
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(IGpuAccessor gpuAccessor, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 76
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, ShaderConfig& config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 79
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 19
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateGraphicsShader(GpuState state, TranslationFlags flags, ShaderStage stage, UInt64 gpuVa, UInt64 gpuVaA) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 373
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 143
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 960
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 120
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 67
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 59
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 334
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


```

#### Log file :

[monster-blast.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5063832/monster-blast.log)

**Comment by GamerzHell9137** [comment]
@F1ReB4LL Can you write a report about the state of the game now after the merge of the PR?

**Comment by GamerzHell9137** [comment]
### Game Name

Monster Blast

### Game Update Version

v1.0.2

### Emulator Build Version

1.1.1004

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 3600*
- ##### GPU: *NVIDIA RTX 3060 Ti*
- ##### RAM: *16GB*


### Game State

Runs and play with no issues.

### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/692e01b1-6341-4d14-b823-284bb8210c7c)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/0dac5c9b-729d-4f40-80f1-1980b95acb55)

### Log File

_No response_
