### ISSUE TITLE
Downwell

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2342]
#### Current on `master` : 1.0.5155

Game crashes on start with an missing service error.

```
00:01:03.152 |E| Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00061990 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> > >::ProcessWithOutObjects(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*)
   sdk:0x000df024 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::baas::IManagerBase, nn::sf::cmif::client::CmifDomainProxy<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::baas::IManagerForApplication>::_nn_sf_sync_EnsureIdTokenCacheAsync(nn::sf::Out<nn::sf::SharedPointer<nn::account::detail::IAsyncContext>, void>)
   sdk:0x000e9828 nn::account::EnsureNetworkServiceAccountIdTokenCacheAsync(nn::account::AsyncContext*, nn::account::UserHandle const&)
   main:0x004d41cc Sub00000000084d81cc
   main:0x0037bf0c Sub000000000837ff0c
   main:0x00144588 Sub0000000008148588
   main:0x00125a8c Sub0000000008129a8c
   main:0x00150db4 Sub0000000008154db4
   main:0x0036ead0 Sub0000000008372ad0
   main:0x0036ec7c Sub0000000008372c7c
   main:0x005131bc Sub00000000085171bc
   main:0x005133dc Sub00000000085173dc
   main:0x00556fc0 Sub000000000855afc0
   main:0x0045a994 Sub000000000845e994
   main:0x0045adc0 Sub000000000845edc0
   main:0x004c17b8 nnMain
   sdk:0x0008492c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000ac Sub00000000080000ac

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
00000010   53 46 43 49 01 00 00 00  02 00 00 00 00 00 00 00   SFCI▒▒▒▒▒▒▒▒▒▒▒▒
00000020   01 00 00 00 00 00 00 00  00 C8 41 0C 00 00 04 00   ▒▒▒▒▒▒▒▒▒EA▒▒▒▒▒

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Log file :

[downwell.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5064267/downwell.log)

**Comment by SeraUX** [comment]
Updated

**Comment by benderscruffy** [comment]
using 1.0.6229
still the same issue

**Comment by AcK77** [comment]
Needs an update

**Comment by EmulationFanatic** [comment]
Updated
