### ISSUE TITLE
Psikyo Shooting Stars Bravo

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2348]
#### Current on `master` : 1.0.5171

Game crashes with an missing service error
```
00:00:29.039 |E| Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IAccountServiceForApplication: 131

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0010ac68 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 10, 0ul> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 10, 0ul> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::BufferClientArgumentType, unsigned int)
   sdk:0x0010a920 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::IAccountServiceForApplication, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::IAccountServiceForApplication, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_ListOpenContextStoredUsers(nn::sf::OutArray<nn::account::Uid> const&)
   sdk:0x00108c20 nn::account::ListPushedOpenUsers(nn::account::Uid*, int)
   sdk:0x00108a28 nn::account::PopOpenUsers(int*, nn::account::UserHandle*, int)
   main:0x019294d8 Sub000000000992d4d8
   main:0x00156654 Sub000000000815a654
   main:0x00061c24 Sub0000000008065c24
   main:0x0098f090 Sub0000000008993090
   main:0x009f5064 Sub00000000089f9064
   main:0x009e5c78 Sub00000000089e9c78
   main:0x00eff6d0 Sub0000000008f036d0
   main:0x00effc74 Sub0000000008f03c74
   main:0x00efed68 Sub0000000008f02d68
   main:0x00bae240 Sub0000000008bb2240
   main:0x00a62188 Sub0000000008a66188
   main:0x00a621bc Sub0000000008a661bc
   main:0x00a62480 Sub0000000008a66480
   main:0x009e40fc nnMain
   sdk:0x0009857c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Buffer Information:
        RecvListBuff:
        Position: 0x000000000bf272f0 Size: 0x0000000000000080

Raw Request Data:
00000000   01 00 10 00 01 00 00 00  00 00 00 00 00 00 00 00   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
00000010   53 46 43 49 01 00 00 00  83 00 00 00 00 00 00 00   SFCI▒▒▒▒?▒▒▒▒▒▒▒
00000020   00 00 00 00 00 00 00 00  80 00 00 00 F0 72 F2 0B   ▒▒▒▒▒▒▒▒?▒▒▒dr▒▒
00000030   00 00 80 00                                        ▒▒?▒

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1267

#### Log file :

[psikyo-shooting-stars-bravo.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5069853/psikyo-shooting-stars-bravo.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
