### ISSUE TITLE
fault - milestone one

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2350]
#### Current on `master` : 1.0.5173

Game boots to the menu, but crashed when trying to go ingame
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Ryujinx.Graphics.Texture.LayoutConverter.<ConvertLinearToBlockLinear>g__Convert|5_0[[System.UInt64, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Span`1<Byte>, System.ReadOnlySpan`1<Byte>, <>c__DisplayClass5_0 ByRef, <>c__DisplayClass5_1 ByRef, <>c__DisplayClass5_2 ByRef)
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Ryujinx.Graphics.Texture.SizeInfo, System.ReadOnlySpan`1<Byte>)
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu()
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory()
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(Ryujinx.Graphics.Gpu.Image.TextureInfo, Ryujinx.Graphics.Gpu.Image.TextureSearchFlags)
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(Ryujinx.Graphics.Gpu.State.RtColorState, Int32, Int32)
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateRenderTargetState(Ryujinx.Graphics.Gpu.State.GpuState, Boolean, Int32)
   at Ryujinx.Graphics.Gpu.Engine.Methods.Clear(Ryujinx.Graphics.Gpu.State.GpuState, Int32)
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(Ryujinx.Graphics.MethodParams)
   at DynamicClass.Macro(Ryujinx.Graphics.Gpu.Engine.MME.MacroJitContext, Ryujinx.Graphics.Gpu.State.GpuState, Int32)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(Ryujinx.Graphics.MethodParams)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(System.ReadOnlySpan`1<Int32>)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
   at Ryujinx.Ui.GlRenderer.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```
#### Screenshots :

![2020-08-13 18_49_51](https://user-images.githubusercontent.com/62521228/90163516-7bcbad00-dd96-11ea-8c40-8215601fe600.png)
![2020-08-13 18_50_26](https://user-images.githubusercontent.com/62521228/90163524-7f5f3400-dd96-11ea-91c4-1164597bc04f.png)
![2020-08-13 18_51_17](https://user-images.githubusercontent.com/62521228/90163532-825a2480-dd96-11ea-9163-67146e7a9796.png)

#### Log file :

[fault-milestone-one.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5070340/fault-milestone-one.log)

**Comment by EmulationFanatic** [comment]
Updated
