### ISSUE TITLE
Arcade Archives TERRA FORCE

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2377]
#### Current on `master` : 1.0.5191

Game crashes with an missing service error after trying to go past the first menu.
```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 12

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0036976c nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 34, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<4, 33, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 12l> >, 16ul, 16ul, true>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 34, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<4, 33, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 12l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, unsigned int)
   sdk:0x0036823c Sub0000000009cf223c
   sdk:0x003671cc Sub0000000009cf11cc
   main:0x00064620 Sub0000000008068620
   main:0x00024dc8 Sub0000000008028dc8
   main:0x00029c88 Sub000000000802dc88
   main:0x00006204 Sub000000000800a204
   sdk:0x0031d3b8 Sub0000000009ca73b8
   sdk:0x00321818 Sub0000000009cab818
   ??? Sub0000000000000000

Buffer Information:
        PtrBuff:
        [0] Position: 0x00000000090ee0b0 Size: 0x0000000000000000
        SendBuff:
        Position: 0x00000011bad3fcfc Size: 0x0000000000000023 Flags: 0
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        Position: 0x00000000090ee0d8 Size: 0x0000000000000400 Flags: 0
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        ReceiveBuff:
        Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
        RecvListBuff:
        Position: 0x00000000090ee4f8 Size: 0x0000000000001000

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0C 00 00 00 00 00 00 00   SFCI············
00000010   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  00 10 00 00 F8 E4 0E 09   ············øä··
00000030   00 00 00 10                                        ····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1233

#### Screenshots :

![15-09-22_19-08-20](https://user-images.githubusercontent.com/62521228/90638755-047e9900-e22e-11ea-9a69-5b88a93b9d31.png)

#### Log file :

[aa-terra-force.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5096620/aa-terra-force.log)

**Comment by SeraUQ** [comment]
Updated
