### ISSUE TITLE
Rune Factory 4 Special

### ISSUE THREAD

**Issue by Seker-0** [Ryujinx/Ryujinx-Games-List#243]
#### Current on `master` : 1.0.3809-1.0.3810

- Need a32-vmovl-vorr In order to boot into the game and use shcache to prevent the game from crashing
- The graphics are broken and some surfaces are missing, including letters
- The game works well in the custom version
- When you click Skip quickly, it will temporarily damage the graphics and then return to normal as in the image below

#### Screenshots : latest
![bandicam 2020-03-02 00-35-10-000](https://user-images.githubusercontent.com/35269098/75663183-fd28fa80-5ca2-11ea-95dd-a14a51e3e48c.jpg)
![bandicam 2020-03-02 00-34-34-428](https://user-images.githubusercontent.com/35269098/75663199-031edb80-5ca3-11ea-9763-1db5568978be.jpg)
![bandicam 2020-03-02 00-58-16-532](https://user-images.githubusercontent.com/35269098/75663214-09ad5300-5ca3-11ea-9e75-86953277c2c1.jpg)
![bandicam 2020-03-02 01-00-39-086](https://user-images.githubusercontent.com/35269098/75663260-1a5dc900-5ca3-11ea-89eb-f37d21b947aa.jpg)
![bandicam 2020-03-02 00-35-21-084](https://user-images.githubusercontent.com/35269098/75663289-221d6d80-5ca3-11ea-91f9-9c9e4beef99c.jpg)

#### Outstanding Issues: need it not crash
- https://github.com/Ryujinx/Ryujinx/pull/960
- https://github.com/Ryujinx/Ryujinx/pull/926

## Custom a32-vmovl-vorr + shcache
![bandicam 2020-03-02 15-50-38-646](https://user-images.githubusercontent.com/35269098/75662841-5f353000-5ca2-11ea-86ea-c3bad631ab4a.jpg)
![bandicam 2020-03-02 15-54-07-224](https://user-images.githubusercontent.com/35269098/75662862-69572e80-5ca2-11ea-90c7-0a78a72cdb99.jpg)
![bandicam 2020-03-02 16-01-38-504](https://user-images.githubusercontent.com/35269098/75662871-6fe5a600-5ca2-11ea-84da-c4bb700c6f17.jpg)
![bandicam 2020-03-02 15-59-54-856](https://user-images.githubusercontent.com/35269098/75662888-77a54a80-5ca2-11ea-8b5d-dd7fe4a4cdf4.jpg)
![bandicam 2020-03-02 15-59-06-384](https://user-images.githubusercontent.com/35269098/75662916-855ad000-5ca2-11ea-844d-c819bd2f1122.jpg)
![bandicam 2020-03-02 15-56-49-364](https://user-images.githubusercontent.com/35269098/75662938-8b50b100-5ca2-11ea-89d9-64df6ffdf3f7.jpg)
![bandicam 2020-03-02 15-54-40-736](https://user-images.githubusercontent.com/35269098/75662948-90adfb80-5ca2-11ea-802a-f2e09a18bc48.jpg)

**Comment by Seker-0** [comment]
Add PR#963 fix graphics

**Comment by B3astTech** [comment]
Need's Updated and tested on Master

**Comment by Seker-0** [comment]
Update..

**Comment by GamerzHell9137** [comment]
> and use shcache to prevent the game from crashing

**Comment by Seker-0** [comment]
Update ...

**Comment by Seker-0** [comment]
Update latest version No need to use shader cache anymore.......................................

**Comment by GoffyDude** [comment]
Updated

**Comment by GamerzHell9137** [comment]
On 4709 there's minimal issues with the game, its working fine now. No crashes, you can start a new game, load it fine and all of that.
Only thing that needs fixes is the audio and another thing is that the game is running at double speed.
The game itself is running at 60 FPS on Switch but right now Ryujins is running it double speed and that's why VSync on.

**Comment by fang1121cs** [comment]
By using RTSS, the speed problem is solvable, it can limit it's max frame rate.

**Comment by GamerzHell9137** [comment]
> By using RTSS, the speed problem is solvable, it can limit it's max frame rate.

Limit to what?

**Comment by fang1121cs** [comment]
Limit to the framerate you set. For Rune Factory 4 Special, 30~FPS is suitable.

**Comment by GamerzHell9137** [comment]
> Limit to the framerate you set. For Rune Factory 4 Special, 30~FPS is suitable.

That's not the issue. The issue is that the original fps of the game is 60 FPS but it runs double speed even with Vsync on. But yes, 30 FPS slows it down but the game is not running at the right FPS.

**Comment by Tellilum** [comment]
## Rune Factory 4: Special
#### Game Update Version : 1.0.1

#### Build Version : 1.0.5221

- Without an external Frame limiter the game will run at 2x native speed
- Audio and other Graphical effects are perfect with no issues discovered
-There seems to be a xBRZ+Hybrid Upscale on 2d Assets, I don't know if this is just the way Rune Factory's engine renders or if it's a Ryujinx thing

Overall, besides the game running at 60FPS without a framelimit in place, the game runs perfectly and can be played from start to finish with no game breaking issues.

#### Hardware Specs : 

##### CPU: i5-9400
##### GPU: AMD Radeon RX570
##### RAM: 16GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx-Games-List/issues/243


#### Screenshots :

![Screenshot (74)](https://user-images.githubusercontent.com/59491721/91377149-ba2c8780-e7ec-11ea-8d09-75a10b674aa3.png)
![Screenshot (81)](https://user-images.githubusercontent.com/59491721/91377157-bef13b80-e7ec-11ea-95a5-c945aee0a168.png)
![Screenshot (82)](https://user-images.githubusercontent.com/59491721/91377164-c284c280-e7ec-11ea-91e0-603a8b2a5bdf.png)
![Screenshot (83)](https://user-images.githubusercontent.com/59491721/91377170-c57fb300-e7ec-11ea-9874-2d413eabf824.png)

#### Log file :

[Ryujinx_2020-08-26_22-32-00.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5133701/Ryujinx_2020-08-26_22-32-00.log)

**Comment by Kethus** [comment]
I found a graphical issue. For me the blade and the guard of my character's sword disappear depending on the direction he is facing. I can't show logs because the emulator freezes when I stop emulation. The sword is equipped on all screenshots.
![Ryujinx_2020-09-08_20-39-36](https://user-images.githubusercontent.com/34918632/92516411-dd5c2b80-f21d-11ea-969f-a53d193990b5.png)
![Ryujinx_2020-09-08_20-39-38](https://user-images.githubusercontent.com/34918632/92516424-e0571c00-f21d-11ea-8353-fe3c54ce6e53.png)
![Ryujinx_2020-09-08_20-39-40](https://user-images.githubusercontent.com/34918632/92516432-e2b97600-f21d-11ea-9db8-900a8cbbf8b8.png)
![Ryujinx_2020-09-08_20-39-42](https://user-images.githubusercontent.com/34918632/92516440-e5b46680-f21d-11ea-9bcd-5a64e909d00a.png)

**Comment by GamerzHell9137** [comment]
@Kethus try again with the latest master, i can see my sword 
![image](https://user-images.githubusercontent.com/2002038/92820684-847dc600-f3ca-11ea-99a1-83d1813fa864.png)

**Comment by yordanihl** [comment]
@GamerzHell9137 I still can't. The sword is visible in Tellilum's message too and that message is older than mine. Maybe because he is on Radeon and I'm on Nvidia. I saw a lot of youtube videos with my problem too. It's not just the sword, but seemingly all objects that have no thickness, like Ambrosia's wings.

**Comment by Kethus** [comment]
@GamerzHell9137 I still can't. The sword is visible in Tellilum's message too and that message is older than mine. Maybe because he is on Radeon and I'm on Nvidia. I saw a lot of youtube videos with my problem too. It's not just the sword, but seemingly all objects that have no thickness, like Ambrosia's wings.

**Comment by GamerzHell9137** [comment]
@Kethus i can't reproduce the issue either and i'm on a desktop Nvidia GPU, maybe its just mobile chipsets and its drivers or something. Update if you haven't and try docked mode instead of handheld too.

**Comment by katroxx** [comment]
Anyone here willing to play my save file? Because everytime I go face the boss called Ancient Bone the game just freeze and there's nothing I can do. I only ask to clear the Deep Water Shrine in Sharance Maze and that's it. I can't clear it because there's Ancient Bone in Deep Water Shrine and my game just completely freeze. Hope anyone here can help me with that, thanks so much 😊

**Comment by GamerzHell9137** [comment]
@katroxx send it

**Comment by katroxx** [comment]
> @katroxx send it
here you go

[Save File.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5238816/Save.File.zip)

**Comment by GamerzHell9137** [comment]
@katroxx come to discord

**Comment by katroxx** [comment]
> @katroxx come to discord
> 
> EDIT: Or not, doesn't even matter, works fine here. Killed Ancient Bone with no crash.

probably because I'm playing with my old and crappy laptop LOL

**Comment by katroxx** [comment]
> @katroxx come to discord
> 
> EDIT: Or not, doesn't even matter, works fine here. Killed Ancient Bone with no crash.

so how is it? are you done with the save file?

**Comment by Tellilum** [comment]
> @GamerzHell9137 I still can't. The sword is visible in Tellilum's message too and that message is older than mine. Maybe because he is on Radeon and I'm on Nvidia. I saw a lot of youtube videos with my problem too. It's not just the sword, but seemingly all objects that have no thickness, like Ambrosia's wings.

I looked over your log and noticed a few things:
- Your GPU is a GTX 850m
- You have alot of memory errors with the same info (might be related to your issue)
- You're not using the latest firmware (10.1.0 is the latest, you're on 9.0.1)
- The game itself is out of date

The main 3 issues would most likely be Firmware, Software Version, and the GPU. Since you're probably using a laptop with a low tier gpu it might be affecting certain models at different angles. I would try updating your firmware to 10.1.0 as opposed to your current 9.0.1 and update the game itself as well to v1.0.1

**Comment by GamerzHell9137** [comment]
> 
> 
> > @GamerzHell9137 I still can't. The sword is visible in Tellilum's message too and that message is older than mine. Maybe because he is on Radeon and I'm on Nvidia. I saw a lot of youtube videos with my problem too. It's not just the sword, but seemingly all objects that have no thickness, like Ambrosia's wings.
> 
> I looked over your log and noticed a few things:
> 
>     * Your GPU is a GTX 850m
> 
>     * You have alot of memory errors with the same info (might be related to your issue)
> 
>     * You're not using the latest firmware (10.1.0 is the latest, you're on 9.0.1)
> 
>     * The game itself is out of date
> 
> 
> The main 3 issues would most likely be Firmware, Software Version, and the GPU. Since you're probably using a laptop with a low tier gpu it might be affecting certain models at different angles. I would try updating your firmware to 10.1.0 as opposed to your current 9.0.1 and update the game itself as well to v1.0.1

I think its his GPU, i'm on 9 firmware and its fine, could be some unimplemented feature his GPU doesnt have just like some people had issues with flipped image which was got fixed. Try master and see if that changes anything.

**Comment by Kethus** [comment]
It was the game version. Thanks @Tellilum !

**Comment by ibmonkster** [comment]
Was playing great yesterday. Little faster then it's supposed to be I suppose but it was perfectly playable however today after updating to 1.0.5485 it will no longer load for me. When I try to load it, all i get is for the console which i copied below... But no longer seems playable at the moment at I can't even get to the menu :(

[Ryujinx_2020-10-03_17-16-12.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5322477/Ryujinx_2020-10-03_17-16-12.log)

**Comment by AcK77** [comment]
@ibmonkster `System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\rune factory\Rune Factory 4 Special (NSP)(US)(DLCs)(Verfied)\Rune Factory 4 Special [Another Episode Pack][010051D00E3A5001][US][v0].nsp'.`

The file didn’t exist so it’s not an emulator issue, btw, be aware of your file names, we aren’t support piracy and then don’t give support to users who follow this way.
This is issue isn’t for support too, come to our discord if you needs to! Some cleanup is necessary here.
Thanks

**Comment by Kethus** [comment]
Does the game still run at 2x native speed for everyone else? It didn't seem that fast to me, so I measured it and for me it runs at ~1.36x on Ryujinx Version 1.0.5485. I thought it could be that my laptop is weaker, but it still runs the game at 60fps.

**Comment by beavermml** [comment]
![image](https://user-images.githubusercontent.com/3795219/101279817-d97d7c80-37ff-11eb-80b3-9a8ee3e5e60d.png)

Latest update seems to break texture

**Comment by GamerzHell9137** [comment]
@beavermml latest pr is fixing the issue, soon to be merged.

**Comment by thepyroxpl** [comment]
how to fix texture have same issue as @beavermml

**Comment by thepyroxpl** [comment]
for now i downgraded my ryujinx version to 1.58 and seem to work so far

**Comment by beavermml** [comment]
any update on double the speed bug?

since i upgrade my rig.. the game running at 140fps+.. and vsync wont work since my monitor is 144hz

**Comment by EmulationFanatic** [comment]
@beavermml no proper fix yet, but setting anFPS limit on Ryujinx in the GPU driver control panel should do the trick. Try 60 FPS, if that doesn't work try 30.

**Comment by beavermml** [comment]
thank you.. i limit the FPS in Nvidia Control Panel to 60fps and it seems it did the trick

**Comment by GamerzHell9137** [comment]
A regression where the top left corner in certain maps get bugged was fixed. Atm only the double speed issue is present.

**Comment by RenBou10** [comment]
I Had an Issue.. Every I Play "Newlywed Mode".. Ryujinx Can't Load Potrait Character and Then FC..
There's Way To Fix It?

Maybe Someone Want to Try 
This is My Savedata : https://drive.google.com/file/d/1FJ6UXvns0USb8NcpNkawzPYXJ1ohpAUy/view?usp=sharing (Married Forte)

**Comment by Rei-Aldier** [comment]
need help,I had the same problem... everytime i try to play the "Newlywed Mode" in RF4 ... ryujinx fails to load the portrait and just proceeds to crash...

trying it out on clorica, and it just crashes instantly...

**Comment by GamerzHell9137** [comment]
The xBRZ+Hybrid Upscale  upgrade is normal, game plays fine on latest master. There's a graphical regression which has a PR to get fixed but other than that the game is running fine. Double speed is still prevalent without a fps limiter.

**Comment by GamerzHell9137** [comment]
### Game Name

Rune Factory 4 Special

### Game Update Version

v1.0.1

### Emulator Build Version

1.1.626

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 3600*
- ##### GPU: *NVIDIA RTX 3060 Ti*
- ##### RAM: *16GB*


### Game State

Game runs with no graphical issues. Only issue that's present is the game's animations running at double speed making the game too fast (Vsync is enabled, its an emulator bug)

### Screenshots

![image](https://user-images.githubusercontent.com/2002038/220005960-b761cc95-9188-4114-9a54-6d5c1d8f5734.png)

![image](https://user-images.githubusercontent.com/2002038/220005925-5d0fd9a5-3c77-4500-8101-99ff618c2fd7.png)

![image](https://user-images.githubusercontent.com/2002038/220005794-708af8f4-ae3d-4aa3-baa0-fe54946568a2.png)


### Log File

_No response_

**Comment by jsgATsbu** [comment]
Tried with my laptop and desktop
With different system specs, the Newlywed mode crashing issue still exists.
Try turning off portrait in game but it's still crashing.
Is there any work around?

**Comment by gdkchan** [comment]
Attach a save and instructions to reproduce the issue.

**Comment by jsgATsbu** [comment]
The reproduction step of this issue is mentioned in threads above but I will post here with my save

**Save file**
[rf4_s01.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/11279642/rf4_s01.zip)

**Reproduction Step**
![Screenshot 2023-04-20 000001](https://user-images.githubusercontent.com/35824911/233255222-2dec38e8-5e06-4f81-a679-9faeaa6d606e.jpg)
![Screenshot 2023-04-20 000059](https://user-images.githubusercontent.com/35824911/233255224-be852483-401a-4925-b7fd-b2631c3ba3c2.jpg)
![Screenshot 2023-04-20 000231](https://user-images.githubusercontent.com/35824911/233255225-a8facc90-82f9-4e8e-b75c-357227b95e6b.jpg)
![Screenshot 2023-04-20 000247](https://user-images.githubusercontent.com/35824911/233255228-57a67968-8ce1-49bb-b81c-c7211d36591a.jpg)

Just keep talking to the spouse and the game will crash.  It's random, when starting a conversation there is a 50% chance of crashing. I'm not sure which line triggers the exception.

**Error Log**
00:02:11.052 |G| HLE.OsThread.15 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 130s
    ProgramName: RF4NX
    Thread: MainThread
    Filename: D:/rf4dev/RF4NX/src/util/m2Emote.cpp
    Line: 343
    Function: InitDevice
    Message: GL_SHADING_LANGUAGE_VERSION: 4.50 NVIDIA

00:02:11.126 |E| HLE.OsThread.15 Application : Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Horizon.LogManager.Ipc.LmLogger.LogImpl(ReadOnlySpan`1 message) in D:\a\Ryujinx\Ryujinx\Ryujinx.Horizon\LogManager\Ipc\LmLogger.cs:line 77
   at Ryujinx.Horizon.LogManager.Ipc.LmLogger.Log(ServiceDispatchContext& context, HipcCommandProcessor processor, ServerMessageRuntimeMetadata runtimeMetadata, ReadOnlySpan`1 inRawData, Span`1& outHeader) in D:\a\Ryujinx\Ryujinx\Ryujinx.Horizon\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Hipc.HipcGenerator\LmLogger.g.cs:line 58
   at Ryujinx.Horizon.Sdk.Sf.Cmif.ServiceDispatchTableBase.ProcessMessageImpl(ServiceDispatchContext& context, ReadOnlySpan`1 inRawData, IReadOnlyDictionary`2 entries, String objectName) in D:\a\Ryujinx\Ryujinx\Ryujinx.Horizon\Sdk\Sf\Cmif\ServiceDispatchTableBase.cs:line 19
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerSessionManager.DispatchRequest(ServiceObjectHolder objectHolder, ServerSession session, Span`1 inMessage, Span`1 outMessage) in D:\a\Ryujinx\Ryujinx\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerSessionManager.cs:line 332
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerSessionManager.ProcessRequestImpl(ServerSession session, Span`1 inMessage, Span`1 outMessage) in D:\a\Ryujinx\Ryujinx\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerSessionManager.cs:line 206
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerManagerBase.ProcessForSession(MultiWaitHolder holder) in D:\a\Ryujinx\Ryujinx\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerManagerBase.cs:line 312
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerManagerBase.WaitAndProcessRequestsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerManagerBase.cs:line 143
   at Ryujinx.Horizon.Sdk.Sf.Hipc.ServerManagerBase.ServiceRequests() in D:\a\Ryujinx\Ryujinx\Ryujinx.Horizon\Sdk\Sf\Hipc\ServerManagerBase.cs:line 116
   at Ryujinx.Horizon.LogManager.LmIpcServer.ServiceRequests() in D:\a\Ryujinx\Ryujinx\Ryujinx.Horizon\LogManager\LmIpcServer.cs:line 35
   at Ryujinx.Horizon.LogManager.LmMain.Main(ServiceTable serviceTable) in D:\a\Ryujinx\Ryujinx\Ryujinx.Horizon\LogManager\LmMain.cs:line 13
   at Ryujinx.Horizon.ServiceEntry.Start(ISyscallApi syscallApi, IVirtualMemoryManager addressSpace, IThreadContext threadContext) in D:\a\Ryujinx\Ryujinx\Ryujinx.Horizon\ServiceEntry.cs:line 24
   at Ryujinx.HLE.HOS.Horizon.<>c__DisplayClass181_0.<StartNewServices>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Horizon.cs:line 357

**Comment by GamerzHell9137** [comment]
### Game Name

Rune Factory 4 Special

### Game Update Version

v1.0.1

### Emulator Build Version

1.1.762

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 3600*
- ##### GPU: *NVIDIA RTX 3060 Ti*
- ##### RAM: *16GB*


### Game State

Main game runs with no issues but Newlywed mode can crash while engaging with Live 2D elements added to that mode.
The Live 2D stuff can graphically break in a random fashion. There's a chance of the game to make the PC lag a lot during Live 2D portions and tank the FPS to 5-15.

### Screenshots

![image](https://user-images.githubusercontent.com/2002038/236613227-306e69ab-21e9-4d42-9eeb-69c509c21dd6.png)
![image](https://user-images.githubusercontent.com/2002038/236613436-a4f2e6f6-2c89-4ac3-a735-0f7056bc2f5b.png)


### Log File

_No response_
