### ISSUE TITLE
Mario Kart 8 Deluxe

### ISSUE THREAD

**Issue by riperiperi** [Ryujinx/Ryujinx-Games-List#244]
#### Current on `master` : 1.0.3823

All single player modes are fully playable, given some luck. Performance is good, but does not yet reach full speed on master. Graphics are generally good, but a few issues prevent it from presenting like switch.

**Gameplay issues:**
- Multiplayer mode will crash trying to use the controller applet.
- Attempting to enter online, lan or wireless play will cause either a crash or controls lock - generally by the game trying to use the error applet. With some tweaks, LAN play does work.
- Attempting to use help on the main menu will crash the game due to the browser applet.
- Attempting to use amiibo on the main menu will crash the game.
- Version 1.7.1 requires https://github.com/Ryujinx/Ryujinx/pull/964 to get ingame.

**Graphics issues:**
- Cubemaps only appear correctly on the first stage the game draws (the first run of the main menu). All future stages will only have one face of the cubemap appear correctly, with the rest appearing as black or garbage data. (ingame or any time you return to the menu)
- There is a random chance that the course-onto-actor shadows will break, and all actors will appear darker. This seems to persist through the rest of the run once it happens.
- There is a high chance that entering some courses will result in a black screen. (super bell subway, toad harbour, animal crossing, mount wario, more) If this does not happen on one of these courses the first time, then the rest of the run you will be able to play any other one of these courses with no problem.
- Part of the drift turbo sparks effect does not appear.
- Particle effects for tricks can sometimes be misaligned with the character.
- Occasionally, actors or racers can appear solid black.

**Audio issues:**
- Music streaming has periodic stuttering, and thus music tracks play back slower than they should.
- The game is incredibly loud, as all ingame sound effects play with no volume setting or 3d sound positioning/falloff.
- Looping sound effects do not loop correctly (there is a pause before their loop plays).
- Pitch shifted sound effects are not working.

#### Pull requests needed (for 1.7.1) :

https://github.com/Ryujinx/Ryujinx/pull/964

#### Screenshots :
![image](https://user-images.githubusercontent.com/6294155/75791475-86543600-5d64-11ea-9910-cf6fe8e98c30.png)

![image](https://user-images.githubusercontent.com/6294155/75791177-15148300-5d64-11ea-9fc3-245f6ed79c4e.png)

https://www.youtube.com/watch?v=UngTvxGHqrY

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/648

**Comment by riperiperi** [comment]
Updated, 1.7.1 now works on master.

**Comment by GamerzHell9137** [comment]
The Animal Crossing stage shows black screens on Summer and Winter versions of the stage.
Spring stage is playable and Fall stage shows couple of black textures on items like trees etc.

Fall Stage's black tree
![image](https://user-images.githubusercontent.com/2002038/77192678-3522a100-6add-11ea-9732-a749cc2769e7.png)

Winter/Summer stage aren't loaded at all, just UI is visible
![image](https://user-images.githubusercontent.com/2002038/77192712-479cda80-6add-11ea-917e-a52a30fca0c6.png)

To trigger specific versions of stage while choosing the stage hold one of the trigger buttons and press A to get into the race
![image](https://user-images.githubusercontent.com/2002038/77192778-6602d600-6add-11ea-8a8e-7849985a65e3.png)

**Comment by hectorprada73** [comment]
Hi, great work so far.
Is online play available, if so which "tweaks" would I need to look at?

Thanks

**Comment by riperiperi** [comment]
Retested with `master` @ `1.0.4135`:

Drift turbo and many other particle effects fixed by: https://github.com/Ryujinx/Ryujinx/pull/1082 . Some particles are still misaligned with their source. (trick particle effect)

2 player mode now softlocks rather than crashes with: https://github.com/Ryujinx/Ryujinx/pull/1003
Shows warning in console "More than one controller was requested." - right now we just return player count as 1.

**Comment by superfan31** [comment]
You mention that whenever trying to play LAN (with multiple controllers) it will cause a crash (requesting more then one controller) but with some tweaks, LAN play does work. 

Could you detail how to do this please?

**Comment by riperiperi** [comment]
One of the tweaks involves a hack right now - Mario Kart expects the BSD sockets to behave as non-blocking, but in ryujinx they default to blocking and there seems to be no signal to change that.

The other tweaks involve telling `ifnet` and `ldn` that we are connected to a local area network, which are less hacky (since the host likely is) but can cause some games to try to phone home, which isn't too great.

**Comment by Ghostotakoi** [comment]
I have been playing MK8 deluxe lately and I had encountered this graphical issues, I know they aren´t deal breakers but I just like to report them.
**Black coins and Gold**
![ScreenShot_20200513192427_compressed](https://user-images.githubusercontent.com/20958581/82008538-020f1080-963b-11ea-8c5d-46333564ea2b.jpg)
**Weird Green Outline on the characters after I finish 1 cup.**
![ScreenShot_20200513192503_compressed](https://user-images.githubusercontent.com/20958581/82008558-105d2c80-963b-11ea-8952-ee731917d44a.jpg)
![ScreenShot_20200513192600_compressed](https://user-images.githubusercontent.com/20958581/82008568-15ba7700-963b-11ea-9694-50ee3ec2ccdf.jpg)
![ScreenShot_20200513192658_compressed](https://user-images.githubusercontent.com/20958581/82008573-16eba400-963b-11ea-9d68-01f653e2a5f2.jpg)

**Comment by riperiperi** [comment]
These are all known issues with the way the game generates cubemaps, which is the first item on the list. It renders directly into a compressed, mipmapped cubemap and aggressively reuses memory during generation when blurring the faces to create each mipmap level. A similar issue is encountered when generating course shadow maps which causes characters to appear black sometimes, but not anywhere near as badly as the cubemaps.

These are all generally issues with the texture cache and view-incompatible textures.

**Comment by riperiperi** [comment]
Updated: The issue where particle affects would misalign with the player has been fixed, as of https://github.com/Ryujinx/Ryujinx/commit/56a61a57582e0fa7951bdb3d96b343ac01063e1f .

**Comment by RenanZX** [comment]
It's unplayable in multiplayer, the game freezes at character screen

**Comment by EmulationFanatic** [comment]
@RenanZX > It's unplayable in multiplayer, the game freezes at character screen

Use the P2 controller to press L+R when prompted at the title screen. Multiplayer will work then.

**Comment by RenanZX** [comment]
@EmulationFanatic > Thanks man, i didn't knew that

**Comment by DerpBlerp** [comment]
i'm getting an issue where the game just locks up while on character select in single player. if it helps i'm using a legitimate Switch Pro Controller, with it's gyro inputs being taken in through BetterJoyForCemu, over bluetooth

**Comment by taiwan-king** [comment]
1.0.6045 cant run
![1607749600167](https://user-images.githubusercontent.com/24381898/101975865-e3c5cd80-3c7a-11eb-9344-4e9ea5b181ae.jpg)

**Comment by riperiperi** [comment]
Updated. All graphical issues shown above have been fixed by the Texture Groups PR.

https://github.com/Ryujinx/Ryujinx/pull/2001

**Comment by riperiperi** [comment]
Updated again. Amiibo are now fully supported in this game.

**Comment by smiglo5** [comment]
> Started Mario Kart, seems menu layer is inverted. Log attached.
> 
> ![ryujinx_capture_2021-10-13_14-30-40](https://user-images.githubusercontent.com/13345236/137079591-288c154c-e075-4163-941c-9a23aa38041f.png)
> 
> [Ryujinx_1.0.7073_2021-10-13_14-28-42.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7335502/Ryujinx_1.0.7073_2021-10-13_14-28-42.log)

It is because new NVIDIA 496.13 drivers, rever to 472.12 or wait for a fix from devteam

**Comment by carrierfry** [comment]
@riperiperi I think the LDN status should be playable by now. If you have cached the shaders of all maps there shouldn't be any disconnects anymore (at least that worked great for me)

**Comment by Gameplayer9198** [comment]
Selecting a custom Mii (via play stats or the popup) crashes the game the next boot. (Known issue for quite some time but doesn't appear to have been posted here)
[Ryujinx_1.0.7162_2022-01-09_15-09-32.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7835836/Ryujinx_1.0.7162_2022-01-09_15-09-32.log)

**Comment by FalconNL** [comment]
Works great up until update 2.0.0 (v720896). Crashes on startup with the following error message after installing update 2.1.0 (v786432):

```
00:00:12.093 |E| HLE.GuestThread.26 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000001614ba0 (opcode 0xf3140c6e) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1105
   at Ryujinx.Cpu.Jit.JitExecutionContext.UndefinedHandler(ExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 104
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\State\ExecutionContext.cs:line 135
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 61
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
```

The crash occurs both when using OpenGL and when using Vulkan as the graphics backend.

**Comment by Executaeble** [comment]
My game crashes when i try to load cheese land or moo moo meadows all other maps work fine

**Comment by SomeoneIsWorking** [comment]
> green outline ![ScreenShot_20200513192658_compressed](https://user-images.githubusercontent.com/20958581/82008573-16eba400-963b-11ea-9d68-01f653e2a5f2.jpg)

I still get this with RX570 + Vulkan

**Comment by laernumoretz** [comment]
MK crashing when selecting gran prix still in single player or coop. All other modes work fine

#4160 above report is the exact same data in my report

**Comment by ubise** [comment]
As mentioned above, on some tracks it's like the reflection doesn't work properly. Mostly when character goes underwater it becomes normaln, but as soon the character dries out, it becomes green, or some other wierd neon color/glow.

![2023-02-06 19_50_02-Ryujinx 1 1 601 - Mario Kart 8 Deluxe v2 2 1 (0100152000022000) (32-bit)](https://user-images.githubusercontent.com/40242653/217059689-1f7e0a36-7039-4c84-9e95-1ad1edaa6b2b.png)
![2023-02-06 19_50_41-Ryujinx 1 1 601 - Mario Kart 8 Deluxe v2 2 1 (0100152000022000) (32-bit)](https://user-images.githubusercontent.com/40242653/217059692-13bc31ed-1359-4eb6-89d7-c81954688873.png)

**Comment by MetrosexualGarbodor** [comment]
Similar to Xenoblade games, Nvidia RTX 3000/4000 GPUs with drivers **newer than 522.25** running Vulkan have "puzzle pieces" in the sky. 
Left is RTX 3070 on driver version 516.94; right is RTX 4080 on driver 528.49.
![imagen](https://user-images.githubusercontent.com/79612681/219916360-a92bd55c-d584-4af0-9bea-915080bf47b4.png)

**Comment by GamerzHell9137** [comment]
> Similar to Xenoblade games, Nvidia RTX 3000/4000 GPUs with drivers **newer than 522.25** running Vulkan have "puzzle pieces" in the sky. Left is RTX 3070 on driver version 516.94; right is RTX 4080 on driver 528.49. ![imagen](https://user-images.githubusercontent.com/79612681/219916360-a92bd55c-d584-4af0-9bea-915080bf47b4.png)

RTX 3060 Ti on 528.02 on Vulkan on puzzle pieces 
![image](https://user-images.githubusercontent.com/2002038/219924580-6ebc6593-1479-4fa9-8572-1b1720ec868b.png)

Sure its newer than 522?

**Comment by MetrosexualGarbodor** [comment]
Guess it's only on RTX 4000s then

**Comment by boiitslegit** [comment]
so where do i download the game i have an irl copy

**Comment by Kiwii** [comment]
> so where do i download the disc i have an irl copy

This is not the right place to ask, but anyway: https://github.com/Ryujinx/Ryujinx/wiki/Frequently-Asked-Questions#-how-can-i-dump-games

**Comment by RDCH106** [comment]
> MK crashing when selecting gran prix still in single player or coop. All other modes work fine

Here the same issue.

Crash in gran prix selection using update 2.3.0 and a recent Ryujinx version (1.1.735 )

**Comment by riperiperi** [comment]
Make sure vsync is enabled. (green in the status bar)

**Comment by RDCH106** [comment]
> > Make sure vsync is enabled. (green in the status bar)
> 
> Thanks!!
> 
> I will try it 👍

The option was already checked.

The issue persists... The crash not always appears.

**Comment by RDCH106** [comment]
> > MK crashing when selecting gran prix still in single player or coop. All other modes work fine
> 
> Here the same issue.
> 
> Crash in gran prix selection using update 2.3.0 and a recent Ryujinx version (1.1.733 )

The problem is produced by screen frequency limitation.

I am playing with Steam Deck. The problem was that I have configured screen frequency to 40fps for the battery saving.  I have change the limitation to 60 fps and works good.

**Comment by vroom1678** [comment]
how do i download

**Comment by sn4zzzz** [comment]
how do i even download the games?

**Comment by EmaGeist** [comment]
### Bug Report

### What's the issue you encountered?
When playing Squeaky Clean Sprint, the course turns pitch black when a pink scented candle is visible, right at the start of the race. This happens again in the drain section of the course, even when the scented candle is not visible. Only the UI elements (Course layout, countdown, etc) remain visible.

### How can the issue be reproduced?
Just play the course, issue persists on Vulkan.

### Environment?
Ryujinx version: Ryujinx 1.1.996
[Ryujinx_1.1.996_2023-08-17_21-26-13.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12375048/Ryujinx_1.1.996_2023-08-17_21-26-13.log)
Game version: 2.4.0
System Specs:
OS: Win 11
CPU: AMD Ryzen 7 4800H with Radeon Graphics
GPU: AMD Radeon(TM) RX 5600M Series
RAM: 16GB
Applied Mods : No
[DxDiag.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/12375051/DxDiag.txt)

https://github.com/Ryujinx/Ryujinx-Games-List/assets/142559716/2a717454-3912-4b22-b97f-3978beb5c15b

https://github.com/Ryujinx/Ryujinx-Games-List/assets/142559716/4d39b0c0-9404-4a9c-880f-ce7f2b782460

**Comment by raoulinoz** [comment]
I can confirm the issue mentioned by @EmaGeist as well.
Still happening with version 1.1.1020 on an RX 7800XT Series.
If more information needed, let me know.

**Comment by amayra** [comment]
i don't have this problem and I'm using rx 5500xt in Linux with mesa 

this may be AMD windows driver problem or ryujinx last version because I'm using 1.1.1020

**Comment by RandomBlackGuy** [comment]
how can I download the game?

**Comment by RandomBlackGuy** [comment]
Hello, I'm new to this emulator and would like help in obtaining the games that are playable. Can I request assistance with this problem?

**Comment by QueenLinuxGlitch** [comment]
Experiencing Crash every 2nd time bug located ref. here https://github.com/Ryujinx/Ryujinx/issues/5813
[Ryujinx_1.1.1093_2023-11-25_22-38-30.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13465933/Ryujinx_1.1.1093_2023-11-25_22-38-30.log)

**Comment by paoloaveri** [comment]
**Bug Report**
What's the issue you encountered?
Experiencing a crash any time I start a race, in any mode. Crash happens during the white loading screen:
![ryujinx_capture_2024-01-10_10-34-44](https://github.com/Ryujinx/Ryujinx-Games-List/assets/47279681/c5a30f1c-4109-4dbd-96e2-28521bc74acc)

It seems to be an issue with Vulkan, see the end of the attached logs.

**Environment?**
Ryujinx version: Ryujinx 1.1.1104
[Ryujinx_1.1.1104_2024-01-10_09-37-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13885349/Ryujinx_1.1.1104_2024-01-10_09-37-49.log)
Game version: 3.0.1
System Specs:
OS: macOS 13.3.1
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU: AMD Radeon Pro 555X
RAM: 16GB
Applied Mods : No

**Comment by ahmetiverson** [comment]
plz helppp where is the link

**Comment by SuperBro64** [comment]
Can confirm the issue with Squeaky Clean Sprint as mentioned previously, where the screen goes completely black except for the UI whenever the pink candle is on screen, is still happening as of version 1.1.1114.

(Seriously... What is with this one singular candle that makes it devour the entire world except itself?)

**Comment by otonoton** [comment]
The comment at https://github.com/Ryujinx/Ryujinx-Games-List/issues/244#issuecomment-1208168774 about Sky-High Sundae still exists on current builds but is not limited to AMD, this also happens on at least M1 and M2 platforms, see video here:

https://github.com/Ryujinx/Ryujinx-Games-List/assets/62482456/f9552fae-852a-4aaa-9f60-0b4dd29d185f

**Comment by CatMow** [comment]
on my school potato, runs very well with graphics being 100% accurate. no big stutters or anything, however does lag a bit in berlin byways (drops to 45-50fps instead of 60)

**Comment by mrTerryBogard** [comment]
[Ryujinx 1.1.1291, Firmware 18.0.0]

In Mario Kart 8: Deluxe. The latest version of the game is 3.0.1. When trying to play a local game for two players, the character selection screen is terribly slow. But the emulator shows a stable 60 FPS! Is this just me or what? At the same time, for one player - no problem.

**Comment by Blergonos** [comment]
> [Ryujinx 1.1.1291, Firmware 18.0.0]
> 
> In Mario Kart 8: Deluxe. The latest version of the game is 3.0.1. When trying to play a local game for two players, the character selection screen is terribly slow. But the emulator shows a stable 60 FPS! Is this just me or what? At the same time, for one player - no problem.

I have the same issue, the only difference is that it crashes when using my Xbox Controller after pressing the menu button on my controller.

**Comment by nachowithcheesedipping** [comment]
game crashes in bankok rush while entering the first lap's water zone

**Comment by KingBrawl-R** [comment]
Any XCI download link ? I can't find any site to download it safety

**Comment by tsukii45** [comment]
> ## Mario Kart 8 Deluxe
> #### Current on `master` : 1.1.1317
> All single player modes are fully playable, graphics are close to perfect. Performance is very consistent on Zen 2 cpus.
> 
> **Gameplay issues:**
> 
> * Local Wireless play requires using the LDN build. LAN works on master. The game expects all players to run at 60fps, and disconnect/desyncs if they do not.
> * Game crashes if you select a custom mii, usually when loading the save. Select one of the default ones instead.
> 
> **Platform Specific Issues:**
> 
> * On MacOS + apple silicon, certain DLC tracks have flickering graphics in the sky, possibly also AMD+windows. Likely related to depth precision?
>   
>   * Game generally doesn't work on MacOS + intel/amd, mostly due to metal driver bugs and mvk performance overhead, though this is shared with _all_ games. On these systems, use linux/windows via bootcamp for a better experience.
> * Issue with Squeaky Clean Sprint on AMD+Windows. Needs to be investigated to see if it still happens.
> 
> #### Pull requests needed :
> (none currently)
> 
> #### Screenshots (at 2x res scale) :
> ![Base Profile Screenshot 2021 04 02 - 17 32 01 81](https://user-images.githubusercontent.com/6294155/113434783-7e3c4f00-93d9-11eb-9a66-daa29bf3a27e.png) ![Base Profile Screenshot 2021 04 02 - 17 03 59 88](https://user-images.githubusercontent.com/6294155/113435393-a2e4f680-93da-11eb-9f5e-776f29779f3e.jpg) ![Base Profile Screenshot 2021 04 02 - 17 09 41 41](https://user-images.githubusercontent.com/6294155/113435400-a4162380-93da-11eb-9e70-24ad864f4074.jpg) ![Base Profile Screenshot 2021 04 02 - 17 12 15 12](https://user-images.githubusercontent.com/6294155/113435404-a5dfe700-93da-11eb-920a-578a7ee57502.jpg) ![Base Profile Screenshot 2021 04 02 - 17 17 36 83](https://user-images.githubusercontent.com/6294155/113435405-a7111400-93da-11eb-9e45-82ea2c4622ce.jpg) ![Base Profile Screenshot 2021 04 02 - 17 18 25 36](https://user-images.githubusercontent.com/6294155/113435408-a8dad780-93da-11eb-9f65-42595be4e8e9.jpg) ![Base Profile Screenshot 2021 04 02 - 17 24 43 80](https://user-images.githubusercontent.com/6294155/113435411-aa0c0480-93da-11eb-9f77-2bd44ebb7080.jpg) ![Base Profile Screenshot 2021 04 02 - 17 28 43 27](https://user-images.githubusercontent.com/6294155/113435418-ad06f500-93da-11eb-8e00-35e05298eb47.jpg) ![Base Profile Screenshot 2021 04 02 - 16 56 40 75](https://user-images.githubusercontent.com/6294155/113435425-ae382200-93da-11eb-96a5-61d8736fde8e.jpg) ![Base Profile Screenshot 2021 04 02 - 17 01 14 90](https://user-images.githubusercontent.com/6294155/113435427-af694f00-93da-11eb-8aa8-3f3629d86e92.jpg) ![Base Profile Screenshot 2021 04 02 - 17 30 26 27](https://user-images.githubusercontent.com/6294155/113434829-90b68880-93d9-11eb-9508-81703504b995.png) ![Base Profile Screenshot 2021 04 02 - 16 53 02 09](https://user-images.githubusercontent.com/6294155/113434839-957b3c80-93d9-11eb-82a7-d95ea419f3be.png) ![Base Profile Screenshot 2021 04 02 - 17 29 28 02](https://user-images.githubusercontent.com/6294155/113434881-ab88fd00-93d9-11eb-89e4-1bedf187a590.png) ![Base Profile Screenshot 2021 04 02 - 17 02 50 22](https://user-images.githubusercontent.com/6294155/113434990-dd9a5f00-93d9-11eb-9404-28ad29d6dbdc.png) ![Base Profile Screenshot 2021 04 02 - 17 14 13 25](https://user-images.githubusercontent.com/6294155/113435073-04f12c00-93da-11eb-85aa-9fb71553e160.png)
> 
> Video (to be updated) https://www.youtube.com/watch?v=UngTvxGHqrY
> 
> #### Outstanding Issues:
> None currently.

**Comment by EchoChaos240** [comment]
i cant find the download button

**Comment by gfrhj** [comment]
Just playing on Steam Deck with all default configs except button inputs, I'm not getting the graphical bugs in Squeaky Clean Sprint. Bangkok Rush doesn't crash either. Sky High Sundae does have the graphical bugs in the sky though. I also get a stutter every time a Lightning item is used, even if it's multiple times in the same race.

**Comment by CatMow** [comment]
> game crashes in bankok rush while entering the first lap's water zone

is your error ErrorDeviceLost?

**Comment by LoganK1234567890** [comment]
[Ryujinx 1.1.1388, Firmware 17.0.0]
The latest version of the game is 3.0.3. Game crashes almost instantly. As soon as it loads enough to say "Mario kart 8 deluxe" it crashes. On mac m1 pro btw

**Comment by Grufflo** [comment]
How do you actually download the game to play on ryujinx? I have never done this before and this might be a stupid question.
