### ISSUE TITLE
Two Point Hospital

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2457]
#### Current on `master` : 1.0.5251

Crashes while loading splash screens.

```
00:04:20.138 |I| ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:04:20.664 |I| HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x001824a0 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   sdk:0x00182564 Sub000000000f83c564
   sdk:0x00182600 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   main:0x02edae24 Sub000000000aedee24
   main:0x010bf808 Sub00000000090c3808
   main:0x010bfb7c Sub00000000090c3b7c
   main:0x010c2eb0 Sub00000000090c6eb0
   main:0x010c0038 Sub00000000090c4038
   main:0x010c3048 Sub00000000090c7048
   main:0x010a0a2c Sub00000000090a4a2c
   main:0x010a8cb8 Sub00000000090accb8
   main:0x028ac8d8 Sub000000000a8b08d8
   main:0x028ab198 Sub000000000a8af198
   main:0x028ab314 Sub000000000a8af314
   main:0x006b5628 Sub00000000086b9628
   main:0x0142adb8 Sub000000000942edb8
   main:0x0142a5e4 Sub000000000942e5e4
   main:0x00a79508 Sub0000000008a7d508
   main:0x018e92ec Sub00000000098ed2ec
   main:0x020ea258 Sub000000000a0ee258
   main:0x011eeb0c Sub00000000091f2b0c
   main:0x0106a05c Sub000000000906e05c
   main:0x02eea2c4 Sub000000000aeee2c4
   main:0x02ede638 Sub000000000aee2638
   main:0x0339c044 Sub000000000b3a0044
   main:0x0339bbc4 Sub000000000b39fbc4
   main:0x03099b60 Sub000000000b09db60
   main:0x02f600c8 Sub000000000af640c8
   main:0x02f61058 Sub000000000af65058
   main:0x02f6108c Sub000000000af6508c
   main:0x02f61334 Sub000000000af65334
   main:0x02ed991c nnMain
   sdk:0x0029da2c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0
```

#### Screenshots :

![2020-08-31 07_12_21-Ryujinx 1 0 5251 - Two Point Hospital v1 0 0 (010031200E044000) (64-bit)](https://user-images.githubusercontent.com/62343878/91724060-f39d2400-eb59-11ea-871e-04707aa2f856.png)
![2020-08-31 07_13_02-Ryujinx 1 0 5251 - Two Point Hospital v1 0 0 (010031200E044000) (64-bit)](https://user-images.githubusercontent.com/62343878/91724076-fb5cc880-eb59-11ea-9ef2-c4faffc1eb75.png)

#### Log file :

[TPH.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5150440/TPH.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6847

**Comment by Mou-Ikkai** [comment]
## Two Point Hospital

#### Game Update Version : *1.0.14*

#### Current on `master` : *1.1.208*

#### Graphics Backend : *Vulkan*

The game seems to be in a bit of a better state, now going to the game's loading screen for a tutorial before crashing. This game does however seem to be potentially breaking shader cache, as it already has 4284 shaders before even reaching the gameplay (due to crashing).

```
HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3568
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 55
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
```

#### Hardware Specs : 

##### CPU: *Ryzen 9 3900X*
##### GPU: *AMD 5700XT 8GB*
##### RAM: *32GB-2667*

#### Screenshots :

![image](https://user-images.githubusercontent.com/45863583/183229675-c8f57143-bd64-43a8-a8c3-597a27ddaeac.png)
![image](https://user-images.githubusercontent.com/45863583/183229684-f0e29186-8bb1-487b-9c79-1c61ec1b0c4a.png)
![image](https://user-images.githubusercontent.com/45863583/183229690-f30e9ee2-caee-4131-8a0f-b6fe77a2ef5d.png)


#### Log file :
[Ryujinx_1.1.208_2022-08-05_22-15-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9274252/Ryujinx_1.1.208_2022-08-05_22-15-33.log)

**Comment by MetrosexualGarbodor** [comment]
Updated.

**Comment by EmulationFanatic** [comment]
Updated
