### ISSUE TITLE
OmegaLabyrinth Life

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2458]
#### Current on `master` : 1.0.5251

Crashes in splash screens.

```
HLE.HostThread.65 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000011B8750FD0.
00:00:59.079 |E| HLE.HostThread.65 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 331
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1149
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

#### Screenshots :

![2020-08-31 07_23_47-Ryujinx 1 0 5251 - OmegaLabyrinth Life v1 0 0 (01001D600E51A000) (64-bit)](https://user-images.githubusercontent.com/62343878/91724773-0bc17300-eb5b-11ea-9f7a-c086c9e7fd8f.png)
![2020-08-31 07_23_55-Ryujinx 1 0 5251 - OmegaLabyrinth Life v1 0 0 (01001D600E51A000) (64-bit)](https://user-images.githubusercontent.com/62343878/91724776-0c5a0980-eb5b-11ea-8ae6-f2aef0c6256b.png)

#### Log file :

[OLL.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5150487/OLL.log)

**Comment by EmulationFanatic** [comment]
Closing as duplicate of #1548
