### ISSUE TITLE
YGGDRA UNION We’ll Never Fight Alone

### ISSUE THREAD

**Issue by Seker-0** [Ryujinx/Ryujinx-Games-List#246]
#### Current on `master` : 1.0.3882

This game needs controller applet. to be able to play

```
00:01:34.765 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Controller applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Applets\AppletManager.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\SystemAppletProxy\ILibraryAppletCreator.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
#### Log file : 
[Ryujinx_2563-03-12_19-39-02.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4324291/Ryujinx_2563-03-12_19-39-02.log)

#### Outstanding Issues:
- https://github.com/Ryujinx/Ryujinx/issues/648

#### Screenshots : Custom Ver use controller applet
![Y1](https://user-images.githubusercontent.com/35269098/76524759-37fa1200-649d-11ea-9b9b-78ae72142b71.jpg)
![Y2](https://user-images.githubusercontent.com/35269098/76524767-3af50280-649d-11ea-826c-936bf1950844.jpg)
![Y3](https://user-images.githubusercontent.com/35269098/76524771-3d575c80-649d-11ea-84df-c703bd9163d0.jpg)

**Comment by B3astTech** [comment]
Need's Updated

**Comment by Seker-0** [comment]
Update now playable latest ver..

**Comment by B3astTech** [comment]
Updated, Thanks
