### ISSUE TITLE
Skully

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2477]
#### Current on `master` : 1.0.5266

Game loads to a title screen with corrupted graphics and an autonomously moving selector. Crashes in menus shortly after trying to start a new game.

```
GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000A64040000.
00:03:36.482 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 342
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyBuffer(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyBuffer.cs:line 109
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 334
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-09-01 12_32_33-Ryujinx 1 0 5266 - Skully v1 0 0 (0100D7B011654000) (64-bit)](https://user-images.githubusercontent.com/62343878/91892257-8cfa3200-ec4f-11ea-9b42-28d48ebe810c.png)
![2020-09-01 12_33_09-Ryujinx 1 0 5266 - Skully v1 0 0 (0100D7B011654000) (64-bit)](https://user-images.githubusercontent.com/62343878/91892263-8ec3f580-ec4f-11ea-9500-daf18517eb6e.png)

#### Log file :

[Skully.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5158180/Skully.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6911

**Comment by EmulationFanatic** [comment]
Updated
