### ISSUE TITLE
Kingdom Rush

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2479]
#### Current on `master` : 1.0.5266

Crashes on launch.

```
00:00:43.904 |I| GUI.WindowThread Hid SetupNpad: Disconnected Controller Handheld from Handheld
00:00:43.904 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld' on ''
00:00:43.930 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'npadIdType')
   at Ryujinx.HLE.HOS.Services.Hid.HidServer.HidUtils.GetIndexFromNpadIdType(NpadIdType npadIdType) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Hid\HidServer\HidUtils.cs:line 20
   at Ryujinx.HLE.HOS.Services.Hid.IHidServer.SetSupportedNpadIdType(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Hid\IHidServer.cs:line 603
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 113
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Log file :

[KR.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5158272/KR.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6807

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6851

**Comment by benderscruffy** [comment]
same status on 1.0.7112

**Comment by EmulationFanatic** [comment]
Same status (HID related crash) on 1.1.294
