### ISSUE TITLE
Cubers

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2480]
#### Current on `master` : 1.0.5266

Crashes in early nvdec splash screens.

```
Ryujinx.NvdecProcessor Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 342
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Cpu.MemoryManager.GetWritableRegion(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 236
   at Ryujinx.Graphics.Nvdec.Image.SurfaceWriter.Write(MemoryManager gmm, ISurface surface, UInt32 lumaOffset, UInt32 chromaOffset) in C:\projects\ryujinx\Ryujinx.Graphics.Nvdec\Image\SurfaceWriter.cs:line 39
   at Ryujinx.Graphics.Nvdec.H264Decoder.Decode(NvdecDevice device, ResourceManager rm, NvdecRegisters& state) in C:\projects\ryujinx\Ryujinx.Graphics.Nvdec\H264Decoder.cs:line 17
   at Ryujinx.Graphics.Nvdec.NvdecDevice.Decode(CodecId codecId) in C:\projects\ryujinx\Ryujinx.Graphics.Nvdec\NvdecDevice.cs:line 48
   at Ryujinx.Graphics.Device.DeviceState`1.Write(Int32 offset, Int32 data) in C:\projects\ryujinx\Ryujinx.Graphics.Device\DeviceState.cs:line 89
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\projects\ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Screenshots :

![2020-09-01 13_15_42-Ryujinx 1 0 5266 - Cubers v1 0 0 (010082E00F1CE000) (64-bit)](https://user-images.githubusercontent.com/62343878/91895964-58897480-ec55-11ea-9e22-3d527e60abcb.png)

#### Log file :

[Cubers.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5158334/Cubers.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6911

**Comment by EmulationFanatic** [comment]
Updated
