### ISSUE TITLE
SAMURAI SHOWDOWN NEOGEO COLLECTION

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2485]
#### Current on `master` : 1.0.5271

Crashes at title screen.

```
HLE.HostThread.34 Application : Unhandled exception caught: System.InvalidOperationException: Decoded a single empty exit block. Entry point = 0xFFE09700FFE09700.
   at ARMeilleure.Decoders.Decoder.Decode(IMemoryManager memory, UInt64 address, ExecutionMode mode, Boolean highCq, Boolean singleBlock) in C:\projects\ryujinx\ARMeilleure\Decoders\Decoder.cs:line 141
   at ARMeilleure.Translation.Translator.Translate(IMemoryManager memory, JumpTable jumpTable, UInt64 address, ExecutionMode mode, Boolean highCq) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 232
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 174
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1149
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-09-02 05_12_42-Ryujinx 1 0 5271 - SAMURAI SHODOWN NEOGEO COLLECTION v1 0 0 (0100F6800F48E000) (](https://user-images.githubusercontent.com/62343878/91974488-13a82100-ecdb-11ea-8f1c-035e16cece01.png)
![2020-09-02 05_13_02-Ryujinx 1 0 5271 - SAMURAI SHODOWN NEOGEO COLLECTION v1 0 0 (0100F6800F48E000) (](https://user-images.githubusercontent.com/62343878/91974492-1440b780-ecdb-11ea-9503-6be18d81fe58.png)

#### Log file :

[SSNC.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5161884/SSNC.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
