### ISSUE TITLE
Family Mysteries: Poisonous Promises

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2489]
#### Current on `master` : 1.0.5271

*Describe the current game state here.*

```
00:04:30.042 |I| HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: FamilyMysteries, PID: 81
   main:0x013a9840 Sub00000000093ad840
   main:0x013a9484 Sub00000000093ad484
   main:0x0136085c Sub000000000936485c
   main:0x0134f43c Sub000000000935343c
   main:0x01353b00 Sub0000000009357b00
   main:0x00b0b3c4 Sub0000000008b0f3c4
   main:0x00b0d59c Sub0000000008b1159c
   main:0x0006734c Sub000000000806b34c
   main:0x0077c490 Sub0000000008780490
   main:0x0077bb7c Sub000000000877fb7c
   main:0x007154d8 Sub00000000087194d8
   main:0x0002fc7c Sub0000000008033c7c
   main:0x000045bc Sub00000000080085bc
   main:0x000052c8 nnMain
   sdk:0x000a11ec nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:04:30.042 |E| HLE.HostThread.0 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:04:30.071 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 342
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1149
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-09-02 07_10_07-Ryujinx 1 0 5271 - Family Mysteries_ Poisonous Promises v1 0 0 (0100034012606000](https://user-images.githubusercontent.com/62343878/91987792-bb2d4f80-eceb-11ea-8ee1-1ded73cdc022.png)
![2020-09-02 07_10_40-Ryujinx 1 0 5271 - Family Mysteries_ Poisonous Promises v1 0 0 (0100034012606000](https://user-images.githubusercontent.com/62343878/91987816-c2ecf400-eceb-11ea-8c44-6570af906d84.png)
![2020-09-02 07_10_52-Ryujinx 1 0 5271 - Family Mysteries_ Poisonous Promises v1 0 0 (0100034012606000](https://user-images.githubusercontent.com/62343878/91987833-c8e2d500-eceb-11ea-9ea0-dc15c23a83a1.png)
![2020-09-02 07_12_04-Ryujinx 1 0 5271 - Family Mysteries_ Poisonous Promises v1 0 0 (0100034012606000](https://user-images.githubusercontent.com/62343878/91987904-de57ff00-eceb-11ea-886e-42f91715733e.png)

#### Log file :

[FMPP.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5162511/FMPP.zip)

**Comment by benderscruffy** [comment]
using 1.0.7108
crashes out at the same place
just with a different error now (graphics error)
00:01:46.676 |E| GPU.MainThread Application : Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearStridedToLinear(Int32 width, Int32 height, Int32 blockWidth, Int32 blockHeight, Int32 stride, Int32 bytesPerPixel, ReadOnlySpan`1 data)
   at Ryujinx.Graphics.Gpu.Engine.Dma.DmaClass.LaunchDma(Int32 argument)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(
[Ryujinx_1.0.7108_2021-11-26_20-30-25.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7608756/Ryujinx_1.0.7108_2021-11-26_20-30-25.log)
)
