### ISSUE TITLE
Layton’s Mystery Journey: Katrielle and the Millionaires’ Conspiracy

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx-Games-List#249]
**Current on `master ` : 1.0.3901**

- Some 3D graphics are rendered, most aren't
- Video files shown as black screen but playing in background

**Status** : In-game 15-60 FPS

Screenshots:
![image](https://user-images.githubusercontent.com/2002038/76872715-11f1ba80-686d-11ea-814a-1b36d48646e8.png)
![image](https://user-images.githubusercontent.com/2002038/76873232-c8559f80-686d-11ea-8e23-8ef25d25ec01.png)
![image](https://user-images.githubusercontent.com/2002038/76873827-95f87200-686e-11ea-9502-dfaf5be297ff.png)
![image](https://user-images.githubusercontent.com/2002038/76873972-c4764d00-686e-11ea-8b10-6a864a6625fe.png)
![image](https://user-images.githubusercontent.com/2002038/76874157-0f906000-686f-11ea-9b97-39410bc8fe36.png)

**Log file :**
[Ryujinx_2020-03-17_16-27-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4344345/Ryujinx_2020-03-17_16-27-49.log)

**Comment by GamerzHell9137** [comment]
4864 build update

The game's UI is breaking a lot and the game is crashing when i've tried to load my save from before
![image](https://user-images.githubusercontent.com/2002038/86961083-e7e83f00-c160-11ea-9a86-30892cf18fae.png)
Its native settings so its not Upscalling or AF settings or something like that.

![image](https://user-images.githubusercontent.com/2002038/86961134-03534a00-c161-11ea-9ee1-5d26b53d47ff.png)
Texture corruptions are random and not the same every time.
![image](https://user-images.githubusercontent.com/2002038/86961183-15cd8380-c161-11ea-9214-e75efcfe142b.png)

In game images with text load fine but with 3D models the text breaks. FPS drops to 6 FPS in game.
![image](https://user-images.githubusercontent.com/2002038/86961240-2aaa1700-c161-11ea-816d-c222b7265d56.png)

![image](https://user-images.githubusercontent.com/2002038/86961370-69d86800-c161-11ea-9582-2c256a9f7868.png)

The game crashes sometimes too, log down below.
[Ryujinx_2020-07-08_20-52-58.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4892824/Ryujinx_2020-07-08_20-52-58.log)

**Comment by GamerzHell9137** [comment]
Game crashes now after logos on 5182
[Ryujinx_2020-08-19_02-57-59.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5093482/Ryujinx_2020-08-19_02-57-59.log)

**Comment by GamerzHell9137** [comment]
Was hunting down new issues that the game started getting

Inclusion of NVDEC https://github.com/Ryujinx/Ryujinx/pull/1384 made the game not being able get past the opening video after the logos. The error that the command prompt shows is 
![image](https://user-images.githubusercontent.com/2002038/93806010-ccadab80-fc48-11ea-9fba-0fed59d33a15.png)

gdkchan says its an ffmpeg itself crashing. NVDEC build and all builds after it crash at the same place, all builds before NVDEC implementation play the sound of the video and no video and it can be skipped my pressing A after which you come to the main menu of the game.

Another thing that breaks the game is Texture Managment changes https://github.com/Ryujinx/Ryujinx/pull/1408
The logos before the intro video are broken. Bukd with Texture Managment and all after it do the same, and builds before Texture Managment shows the logos like they should be.
![image](https://user-images.githubusercontent.com/2002038/93806500-83aa2700-fc49-11ea-939e-7b6872007897.png)

**Comment by gdkchan** [comment]
I didn't say that ffmpeg was crashing. I said that that was a possibility, but I did not have enough information to confirm or deny it. Anyway the logs show that its crashing due to a invalid guest memory access on the CPU. If it's indeed caused by NVDEC, then the only thing that can be happening is that it is corrupting the memory writing the surface to memory.

**Comment by benderscruffy** [comment]
using 1.0.6213
crashes out now after you input your name
nothing in the log just in the console

**Comment by EmulationFanatic** [comment]
Working fine here

**Comment by EmulationFanatic** [comment]
Wait, spoke too soon. It crashed after a moment with this in the console.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
Fatal error.    at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at System.Threading.ThreadHelper.ThreadStart()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
```

**Comment by EmulationFanatic** [comment]
Updated

**Comment by DocMAX** [comment]
Master build - crash

**Comment by MutantAura** [comment]
Needs update :)

**Comment by GamerzHell9137** [comment]
> Needs update :)

Updated

**Comment by GamerzHell9137** [comment]
Updated!

**Comment by EmulationFanatic** [comment]
Updated
