### ISSUE TITLE
Crayon Shin-chan The Storm Called Flaming Kasukabe Runner!

### ISSUE THREAD

**Issue by Seker-0** [Ryujinx/Ryujinx-Games-List#251]
#### Current on `master` : 1.0.3920

The game will crash after selecting the language 
Can be tested in version 1.0.3910

```
00:00:17.302 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: android.gui.IGraphicBufferProducer 2
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.NvFlinger.ProcessParcelRequest(ServiceCtx context, Byte[] parcelData, Int32 code) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\NvFlinger.cs:line 88
   at Ryujinx.HLE.HOS.Services.Vi.RootService.ApplicationDisplayService.IHOSBinderDriver.TransactParcelAuto(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Vi\RootService\ApplicationDisplayService\IHOSBinderDriver.cs:line 83
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
#### Log file : 
[Ryujinx_2563-03-18_22-26-51.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4349834/Ryujinx_2563-03-18_22-26-51.log)

#### Pull requests needed PR:
- https://github.com/Ryujinx/Ryujinx/pull/981

#### Screenshots : Custom Ver use ( surface-flinger-v2 )
![CS1](https://user-images.githubusercontent.com/35269098/76978967-ee606a00-6969-11ea-8e32-2170b15952a2.jpg)
![CS2](https://user-images.githubusercontent.com/35269098/76978988-f3251e00-6969-11ea-9199-88591cbe248d.jpg)
![CS3](https://user-images.githubusercontent.com/35269098/76979005-f6200e80-6969-11ea-83ef-d1c6fc1bd3ed.jpg)

**Comment by Seker-0** [comment]
Update Playable now .. -v-
