### ISSUE TITLE
Stela

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2511]
#### Current on `master` : 1.0.5271

Crashes on launch.

```
00:02:41.117 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000009CA240A20.
00:02:41.300 |W| ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:02:41.340 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 331
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Graphics.Gpu.Memory.PhysicalMemory.Read[T](UInt64 address) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\PhysicalMemory.cs:line 57
   at Ryujinx.Graphics.Gpu.Image.TexturePool.GetDescriptor(Int32 id) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 84
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.GetTextureDescriptor(GpuState state, Int32 stageIndex, Int32 handle) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 318
   at Ryujinx.Graphics.Gpu.Image.TextureManager.GetGraphicsTextureDescriptor(GpuState state, Int32 stageIndex, Int32 handle) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 329
   at Ryujinx.Graphics.Gpu.Shader.GpuAccessor.GetTextureDescriptor(Int32 handle) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\GpuAccessor.cs:line 291
   at Ryujinx.Graphics.Gpu.Shader.GpuAccessor.QueryIsTextureRectangle(Int32 handle) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\GpuAccessor.cs:line 136
   at Ryujinx.Graphics.Shader.Translation.Lowering.RewriteTextureSample(LinkedListNode`1 node, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Lowering.cs:line 143
   at Ryujinx.Graphics.Shader.Translation.Lowering.RunPass(BasicBlock[] blocks, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Lowering.cs:line 35
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(Operation[] ops, ShaderConfig config, Int32 sizeA) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 49
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 19
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateGraphicsShader(GpuState state, TranslationFlags flags, ShaderStage stage, UInt64 gpuVa, UInt64 gpuVaA) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 373
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 149
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 960
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 120
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 67
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.MME.MacroJit.Execute(ReadOnlySpan`1 code, GpuState state, Int32 arg0) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MME\MacroJit.cs:line 37
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 334
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1282

#### Log file :

[Stela.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5175519/Stela.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
