### ISSUE TITLE
Hayfever

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2518]
#### Current on `master` : 1.0.5306

Crashes after pressing A at the title screen.

```
ServiceNv Create: Created map 20 with size 0x01000000!
00:01:29.825 |I| HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x000ce900 nn::os::AllocateMemoryPages(unsigned long, unsigned long)
   sdk:0x000b82d8 nnmem_nlib_physical_alloc
   sdk:0x000bf528 nn::nlibsdk::heap::TlsHeapCentral::AllocPhy_(void*, unsigned long)
   sdk:0x000c049c nn::nlibsdk::heap::TlsHeapCentral::SplitSpan_(nn::nlibsdk::heap::Span*, unsigned long, nn::nlibsdk::heap::Span*)
   sdk:0x000c4e50 nn::nlibsdk::heap::CentralHeap::Alloc(unsigned long, unsigned long)
   sdk:0x000c66c0 nn::mem::StandardAllocator::Allocate(unsigned long, unsigned long)
   main:0x01776a84 Sub000000000977aa84
   sdk:0x00420a60 Sub000000000caa3a60
   ??? Sub0000000000000000


00:01:29.825 |E| HLE.HostThread.0 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000000BF800021.
00:01:30.017 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 331
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 203
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1149
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-09-07 05_04_03-Ryujinx 1 0 5306 - Hayfever v1 0 0 (0100EA900FB2C000) (64-bit)](https://user-images.githubusercontent.com/62343878/92381366-f5219b80-f0c7-11ea-87c8-41130a31f396.png)
![2020-09-07 05_04_17-Ryujinx 1 0 5306 - Hayfever v1 0 0 (0100EA900FB2C000) (64-bit)](https://user-images.githubusercontent.com/62343878/92381368-f5ba3200-f0c7-11ea-862e-c29225bad06e.png)
![2020-09-07 05_04_28-Ryujinx 1 0 5306 - Hayfever v1 0 0 (0100EA900FB2C000) (64-bit)](https://user-images.githubusercontent.com/62343878/92381370-f652c880-f0c7-11ea-9e2f-6ae07e7fd37e.png)

#### Log file :

[Hayfever.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5182736/Hayfever.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by benderscruffy** [comment]
goes ingame for me no problem (but that doesn't really matter :) 
![hayfever](https://user-images.githubusercontent.com/2696404/102676888-a2817080-41da-11eb-9fed-7a9fa8cab851.PNG)

**Comment by EmulationFanatic** [comment]
It does matter, we just can't mark the game as playable if it's known to crash on NVIDIA video cards, as that is the most commonly used GPU vendor.

**Comment by benderscruffy** [comment]
i wasn't asking you to mark it as playable
this was just my findings with my graphics card

**Comment by EmulationFanatic** [comment]
Updated
