### ISSUE TITLE
Save Koch

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2519]
#### Current on `master` : 1.0.5306

Game loaded and played smoothly but with minor graphics issues and crashed a few minutes in to gameplay.

```
HLE.HostThread.124 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   main:0x013e6984 Sub00000000093ea984
   subsdk0:0x00016f4c NvMMLiteUtilDestroySurfaces
   subsdk0:0x000796ec Sub000000000b8956ec
   subsdk0:0x00017aa0 NvMMLiteBlockTryClose
   subsdk0:0x000167c0 NvMMLiteCloseBlock
   subsdk0:0x00054ae8 Sub000000000b870ae8
   subsdk0:0x0004a3ec Sub000000000b8663ec
   subsdk0:0x0001ce30 Sub000000000b838e30
   subsdk0:0x0001bf00 Sub000000000b837f00
   subsdk0:0x00026b24 Sub000000000b842b24
   sdk:0x000cfb48 Sub000000000bff8b48
   sdk:0x000d4314 Sub000000000bffd314
   ??? Sub0000000000000000


00:05:21.273 |E| HLE.HostThread.124 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000bfe1ea0 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1109
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 136
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1149
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

#### Screenshots :

![2020-09-07 05_10_32-Ryujinx 1 0 5306 - Save Koch v1 2 1 0 (0100C8300FA90000) (64-bit)](https://user-images.githubusercontent.com/62343878/92382067-3bc3c580-f0c9-11ea-9ea3-8defcb706d09.png)
![2020-09-07 05_10_47-Ryujinx 1 0 5306 - Save Koch v1 2 1 0 (0100C8300FA90000) (64-bit)](https://user-images.githubusercontent.com/62343878/92382069-3c5c5c00-f0c9-11ea-8be7-fa55613dd802.png)
![2020-09-07 05_11_14-Ryujinx 1 0 5306 - Save Koch v1 2 1 0 (0100C8300FA90000) (64-bit)](https://user-images.githubusercontent.com/62343878/92382080-41b9a680-f0c9-11ea-895a-f1ae7aa728ff.png)
![2020-09-07 05_11_31-Ryujinx 1 0 5306 - Save Koch v1 2 1 0 (0100C8300FA90000) (64-bit)](https://user-images.githubusercontent.com/62343878/92382082-43836a00-f0c9-11ea-94f3-8bdcb2441365.png)
![2020-09-07 05_11_39-Ryujinx 1 0 5306 - Save Koch v1 2 1 0 (0100C8300FA90000) (64-bit)](https://user-images.githubusercontent.com/62343878/92382099-4aaa7800-f0c9-11ea-9171-e25a1b743080.png)
![2020-09-07 05_12_32-Ryujinx 1 0 5306 - Save Koch v1 2 1 0 (0100C8300FA90000) (64-bit)](https://user-images.githubusercontent.com/62343878/92382119-5302b300-f0c9-11ea-83d4-ae2271c98b2f.png)
![2020-09-07 05_13_15-Ryujinx 1 0 5306 - Save Koch v1 2 1 0 (0100C8300FA90000) (64-bit)](https://user-images.githubusercontent.com/62343878/92382129-59912a80-f0c9-11ea-9d61-6242b3b55d9c.png)
![2020-09-07 05_14_17-Ryujinx 1 0 5306 - Save Koch v1 2 1 0 (0100C8300FA90000) (64-bit)](https://user-images.githubusercontent.com/62343878/92382160-64e45600-f0c9-11ea-8474-86676081a0d5.png)

#### Log file :

[SK.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5182801/SK.zip)

**Comment by EmulationFanatic** [comment]
Updated
