### ISSUE TITLE
Super One More Jump

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#252]
#### Current on `master` : 1.0.3913

The game is playable with slowdowns. Game between 7-33 FPS on an Intel i5-6600K/Nvidia GTX 1080. Reproducible crash if I press the X button in menus of any kind. This occurs regardless of which input mode is selected, or whether it is docked or undocked.

```
Last error returned.
00:04:41.055 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Controller applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Applets\AppletManager.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\SystemAppletProxy\ILibraryAppletCreator.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Screenshots :

![Title](https://user-images.githubusercontent.com/62343878/76976038-fe8c3100-68f8-11ea-851b-15ff1bcad44f.png)
![Menus](https://user-images.githubusercontent.com/62343878/76977516-077e0200-68fb-11ea-9fbb-852fdb1837dd.png)
![In-Game](https://user-images.githubusercontent.com/62343878/76977534-0e0c7980-68fb-11ea-949b-b51f9a43dee5.png)

#### Log file :

[SuperOneMoreJump_IgnoreMissingServicesOFF.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4349780/SuperOneMoreJump_IgnoreMissingServicesOFF.zip)

Logfile generated ending with a crash pressing the X button in Handheld mode.

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## Super One More Jump

#### Current on `master` : 1.0.4123

Game is playable though on the slow side. 
There is a control issue where menus cannot be navigated properly due to boomerang effect of the joystick or d-pad: if you press right, as soon as you let go it comes back to the place you started. Again, this happens with both the d-pad and joystick.

#### Screenshots :
![2020-04-03 07_42_11-Ryujinx 1 0 4135 _ Super One More Jump _ 0100284007D6C000](https://user-images.githubusercontent.com/62343878/78367585-8d4ab000-757f-11ea-895d-937d23deaadc.png)
![2020-04-03 07_42_16-Ryujinx 1 0 4135 _ Super One More Jump _ 0100284007D6C000](https://user-images.githubusercontent.com/62343878/78367593-8e7bdd00-757f-11ea-99b9-e71f73baf611.png)
![2020-04-03 07_43_52-Ryujinx 1 0 4135 _ Super One More Jump _ 0100284007D6C000](https://user-images.githubusercontent.com/62343878/78367596-8fad0a00-757f-11ea-9eea-099e99504838.png)

#### Log file :

[SuperOneMoreJump.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4427618/SuperOneMoreJump.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
