### ISSUE TITLE
Deep Diving Adventure

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2521]
#### Current on `master` : 1.0.5306

Game loads smoothly but crashes a few minutes in to gameplay.

```
HLE.HostThread.33 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x00054e10 Sub000000000c5d2e10
   sdk:0x00054ed8 Sub000000000c5d2ed8
   sdk:0x00054f70 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   sdk:0x000d5438 nn::os::detail::InternalConditionVariableImplByHorizon::TimedWait(nn::os::detail::InternalCriticalSection*, nn::os::detail::TimeoutHelper const&)
   sdk:0x000ca43c nn::os::TimedWaitEvent(nn::os::EventType*, nn::TimeSpan)
   main:0x01f59304 Sub0000000009f5d304
   sdk:0x000cfb48 Sub000000000c64db48
   sdk:0x000d4314 Sub000000000c652314
   ??? Sub0000000000000000


00:05:50.788 |W| HLE.HostThread.3 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.788 |W| HLE.HostThread.4 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.788 |W| HLE.HostThread.25 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.788 |W| HLE.HostThread.6 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.788 |W| HLE.HostThread.23 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.788 |W| HLE.HostThread.35 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.788 |W| HLE.HostThread.34 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.788 |W| HLE.HostThread.27 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.24 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.22 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.21 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.20 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.19 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.26 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.18 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.17 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.16 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.15 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.14 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.13 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.12 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.11 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.10 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.9 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.8 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.789 |W| HLE.HostThread.7 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:05:50.815 |E| HLE.HostThread.33 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1383
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 54
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1149
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-09-07 05_34_16-Ryujinx 1 0 5306 - Deep Diving Adventures v1 0 0 (010026800FA88000) (64-bit)](https://user-images.githubusercontent.com/62343878/92383965-8266ef00-f0cc-11ea-862d-c2624978e4e6.png)
![2020-09-07 05_34_28-Ryujinx 1 0 5306 - Deep Diving Adventures v1 0 0 (010026800FA88000) (64-bit)](https://user-images.githubusercontent.com/62343878/92383970-82ff8580-f0cc-11ea-8d53-38fbc9663557.png)
![2020-09-07 05_34_49-Ryujinx 1 0 5306 - Deep Diving Adventures v1 0 0 (010026800FA88000) (64-bit)](https://user-images.githubusercontent.com/62343878/92383972-83981c00-f0cc-11ea-8f28-7d27c535c9b4.png)
![2020-09-07 05_35_18-Ryujinx 1 0 5306 - Deep Diving Adventures v1 0 0 (010026800FA88000) (64-bit)](https://user-images.githubusercontent.com/62343878/92383989-898dfd00-f0cc-11ea-9b71-26ccfac490c0.png)
![2020-09-07 05_35_46-Ryujinx 1 0 5306 - Deep Diving Adventures v1 0 0 (010026800FA88000) (64-bit)](https://user-images.githubusercontent.com/62343878/92384029-9579bf00-f0cc-11ea-8572-074bbda0f426.png)
![2020-09-07 05_37_56-Ryujinx 1 0 5306 - Deep Diving Adventures v1 0 0 (010026800FA88000) (64-bit)](https://user-images.githubusercontent.com/62343878/92384045-9f032700-f0cc-11ea-9139-aa797826e00a.png)

#### Log file :

[DDA.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5182900/DDA.zip)

**Comment by EmulationFanatic** [comment]
Updated
