### ISSUE TITLE
Super Mario 3D All-Stars

### ISSUE THREAD

**Issue by teszNU** [Ryujinx/Ryujinx-Games-List#2529]
#### Current on `master` : Commit Id *or* Build Version : 1.0.5346

Crashed by Launched. 
note: this games is 32bit exec, and offical emulator runtime.(look like bundled n64, gamecube or wii virtual console.)

```
00:00:23.432 |W| KernelIpc CallMethod: Missing service Ryujinx.HLE.HOS.Services.Account.Acc.IAccountServiceForApplication: 131 ignored
00:00:23.524 |I| ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:00:24.527 |I| HLE.HostThread.3 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x00059084 nn::diag::detail::VAbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, std::__va_list)
   sdk:0x00059110 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, char const*, ...)
   sdk:0x00059170 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int)
   sdk:0x0011cdd0 nn::account::PopOpenUsers(int*, nn::account::UserHandle*, int)
   main:0x0048bb7c Sub000000000068fb7c
   main:0x004861dc Sub000000000068a1dc
   main:0x00676e48 Sub000000000087ae48
   main:0x00679cb0 Sub000000000087dcb0
   main:0x00459418 Sub000000000065d418
   sdk:0x000dac48 Sub000000001975bc48
   sdk:0x000de364 Sub000000001975f364
   ??? Sub0000000000000000
```

#### Log file :

[Ryujinx_2020-09-19_11-28-53.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5249051/Ryujinx_2020-09-19_11-28-53.log)

**Comment by choppymaster** [comment]
Needs update

**Comment by LBmaster001** [comment]
- Start Screen work perfectly fine. No FPS issues or crashes
- Starting Super Mario 64 -> Crash
- Starting Super Mario Sunshine -> extremly Laggy and unplayable (max 2FPS see Screenshot)
- Starting Super Mario Galaxy -> Crash

Stack Trace when starting Super Mario 64:
```
00:00:05.115 |E| HLE.OsThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletOE.ApplicationProxyService.ApplicationProxy.IApplicationFunctions: 1001

Guest Stack Trace:
Process: Service, PID: 92

Raw Request Data:
00000000   01 00 10 00 03 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  E9 03 00 00 00 00 00 00   SFCI····é·······
00000020   53 46 43 49 01 00 00 00                            SFCI····        

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Laggy Super Mario Sunshine Spash Screen (99.99% FIFO):
![grafik](https://user-images.githubusercontent.com/23264393/131211350-e65f7b2b-3011-4223-a7ab-22cf02ce26b9.png)

Stack Trace when starting Super Mario Galaxy:
```
00:00:06.674 |E| HLE.GuestThread.17 Application : Unhandled exception caught: System.NotImplementedException: Unknown MRC Opc1 0x0000000000000003 at 0x0000000000801340.
   at ARMeilleure.Instructions.InstEmit32.Mrc(ArmEmitterContext context)
   at ARMeilleure.Translation.Translator.EmitAndGetCFG(ArmEmitterContext context, Block[] blocks, Range& range, Counter`1& counter)
   at ARMeilleure.Translation.Translator.Translate(UInt64 address, ExecutionMode mode, Boolean highCq)
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode)
   at ARMeilleure.Instructions.NativeInterface.GetFunctionAddress(UInt64 address)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Ryujinx Version: 1.0.7017
OS: Windows 10 Pro 20H2 19042.1165
CPU: AMD Ryzen 9 3900x
GPU: MSI RTX 2070 Super Ventus OC Ver. 471.68

**Comment by AkihitoZero5454** [comment]
Yeah the 3 three are still not working. 64 and Galaxy are crashing when booting up and Sunshine is still very slow and hangs after the first cutscene.

**Comment by Quasardian** [comment]
Aren't these games being emulated by Nintendo?
So this is an emulation inside of an emulation?
That might be problematic to ever get running good.

**Comment by poudink** [comment]
Cases like these are actually quite common and have been succesfully emulated several times by several emulators. Ryujinx itself runs Mega Man Legacy Collection quite well, for example. There are several pull requests open that will heavily help this game once merged, as well.
https://github.com/Ryujinx/Ryujinx/pull/2458
https://github.com/Ryujinx/Ryujinx/pull/2861
https://github.com/Ryujinx/Ryujinx/pull/2954
https://github.com/Ryujinx/Ryujinx/pull/2958
https://github.com/Ryujinx/Ryujinx/pull/2959

**Comment by ethanriverpage** [comment]
Ryujinx (master build) 1.1.76 (Docked mode, 2x res)
**OS:** Windows 10 Pro 21H1 19043.928
**CPU:** Ryzen 5 3600
**GPU:** NVIDIA GeForce RTX 3070
**RAM:** 32GB DDR4-3600
NVIDIA driver version: 511.79

- Super Mario 64 crashes on boot
Stack trace:
```
00:00:04.511 |E| HLE.OsThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletOE.ApplicationProxyService.ApplicationProxy.IApplicationFunctions: 1001

Guest Stack Trace:
Process: Service, PID: 93

Raw Request Data:
00000000   01 00 10 00 03 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  E9 03 00 00 00 00 00 00   SFCI····é·······
00000020   53 46 43 49 01 00 00 00                            SFCI····        

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 156
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 214
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
```

- Super Mario Sunshine runs with no game-breaking bugs or graphical glitches, but at an unplayable framerate. Usually hovered around 15-20 FPS, seeing FIFO maxed out at 99%.
Note: pressing the suspend button (minus) during gameplay dims the screen, and there seems to be no way out of it.
![Ryujinx_ojUM7o6TBy](https://user-images.githubusercontent.com/88117372/158848874-db20eeec-cfce-4ec1-b1a5-02c357ab31ac.jpg)
![Ryujinx_3vZExrxgIG](https://user-images.githubusercontent.com/88117372/158848948-24a2c62e-1572-4d27-bd07-94d278484e84.jpg)
![Ryujinx_ic45wASo8H](https://user-images.githubusercontent.com/88117372/158848961-8ba49f75-c3db-487a-bc23-843d2fe023b8.jpg)

- Super Mario Galaxy runs with (seemingly) no game-breaking bugs or graphical glitches. Runs a steady 50-60fps.

![Ryujinx_G1aLYhqHVd](https://user-images.githubusercontent.com/88117372/158857205-fe810f8d-6dc8-43d1-bcd5-fa9412c22926.jpg)
![Ryujinx_663JVb4EKb](https://user-images.githubusercontent.com/88117372/158857230-9f3b3fd3-23ea-4d03-98e9-8811224dfa9b.jpg)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by bwyyoung** [comment]
**Ryujinx version 1.1.542
Game Update Version : 1.1.1
Backend: Vulkan
System specs - GPD Win Max 2 :**
```
Operating System: Windows 11 Enterprise 64-bit (10.0, Build 22621) (22621.ni_release.220506-1250)
Language: English (Regional Setting: English)
System Manufacturer: GPD
System Model: G1619-04
BIOS: 1.05 (type: UEFI)
Processor: AMD Ryzen 7 6800U with Radeon Graphics          (16 CPUs), ~2.7GHz
Memory: 32768MB RAM
```

![ryujinx_capture_2023-01-12_12-53-05](https://user-images.githubusercontent.com/1365439/211980461-35765a95-de43-44bc-90b7-a881901fa623.png)
![ryujinx_capture_2023-01-12_12-53-08](https://user-images.githubusercontent.com/1365439/211980480-f4bd0860-d1c6-4f6d-830c-26aae9c96cfa.png)
![ryujinx_capture_2023-01-12_12-54-08](https://user-images.githubusercontent.com/1365439/211980485-9291880e-a5a8-4ead-970b-c7e94884da06.png)

**Comment by Oliversinn** [comment]
Unplayable on M1

30-60 FPS on lunch. When selecting a game gets around 15 and then 0 FPS.

**Comment by fabiomoggi** [comment]
Also unplayable on M2. Mario 64 plays fine. Sunshine drops to 1-5 FPS right from the title screen. Galaxy closes unexpectedly after a few seconds into the introduction.

**Comment by DrWillz** [comment]
There seems to be an issue when extracting the full RomFS for this game from within Ryujinx. 
On the base cartridge version, the dump process appears to work normally, however many files are missing. The MarioSunshine directory for example is missing. 

I believe only the main program nca is being extracted on ryujinx. If you use nxdumptool you can extract the other files which are at different offsets on the cartridge. 

When an update such as version 1.1.1 is applied and the dump process is started, the emulator crashes with a hash error. A log is included below. What's weird is that the update works fine on the emulator and that the issue is only related to the dumping process.

[Ryujinx_1.1.1067_2023-10-30_23-14-37.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13210577/Ryujinx_1.1.1067_2023-10-30_23-14-37.log)

**Comment by NineKain** [comment]
Game runs at terrible framerates, ryu generated a 186mb log
[Ryujinx_1.1.1093_2023-11-26_18-22-49.log.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/13467574/Ryujinx_1.1.1093_2023-11-26_18-22-49.log.zip)

**Comment by rafaeoz** [comment]
Mac mini M1 - 8GB 

build 1.1.1192 


Mario 64 runs OK
Mario Sunshine Terrible FPS...and eventually crashes

**Comment by Ryan2603** [comment]
almost unplayable due the FIFO 100% in-game (Mario Galaxy), a web applet service keep created in millsecond.

**Comment by Emalineart** [comment]
[Ryujinx_1.1.1297_2024-05-06_19-53-59.log.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/15228699/Ryujinx_1.1.1297_2024-05-06_19-53-59.log.zip)

SM Galaxy with unplayable FPS, ranging from about 12-30
Ryujinx Version 1.1.1297
near 100% FIFO during all play except the opening cutscene

AMD Ryzen 7 1700 Eight-Core
32.0 GB Ram
Windows 10 vs 22H2
NVIDIA GeForce GTX 1080
PRIME X370-PRO Motherboard
