### ISSUE TITLE
Trine Enchanted Edition

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#253]
#### Current on `master` : 1.0.3920

- Game crashes on launch without OpenAL installed on PC. 

- With OpenAL installed, game loads but is extremely slow.

- 2-3 FPS average in-game

- Blank screen displayed during initial new game narration. Eventually graphics load properly and allow you to start the level.

- Game appears to render properly with extreme slowness.

- Button presses must be deliberate and held down for approximately half a second in order to register.

Tested on Intel I5-6600K/Nvidia GTX 1080. 

```
Last error returned.
00:00:57.299 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> SoundIOSharp.SoundIOException: incompatible device
   at SoundIOSharp.SoundIOOutStream.Open() in C:\projects\ryujinx\Ryujinx.Audio\Native\libsoundio\SoundIOOutStream.cs:line 190
   at Ryujinx.Audio.SoundIo.SoundIoAudioTrack.Open(Int32 sampleRate, Int32 channelCount, ReleaseCallback callback, SoundIOFormat format) in C:\projects\ryujinx\Ryujinx.Audio\Renderers\SoundIo\SoundIoAudioTrack.cs:line 115
   at Ryujinx.Audio.SoundIoAudioOut.OpenTrack(Int32 sampleRate, Int32 channels, ReleaseCallback callback) in C:\projects\ryujinx\Ryujinx.Audio\Renderers\SoundIo\SoundIoAudioOut.cs:line 85
   at Ryujinx.HLE.HOS.Services.Audio.IAudioOutManager.OpenAudioOutImpl(ServiceCtx context, Int64 sendPosition, Int64 sendSize, Int64 receivePosition, Int64 receiveSize) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\IAudioOutManager.cs:line 150
   at Ryujinx.HLE.HOS.Services.Audio.IAudioOutManager.OpenAudioOut(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\IAudioOutManager.cs:line 34
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
#### Screenshots :
![Title](https://user-images.githubusercontent.com/62343878/76985627-233ad580-6906-11ea-9a38-5510cabaaafb.png)
![Game_Start](https://user-images.githubusercontent.com/62343878/76985687-377ed280-6906-11ea-850a-19dfe55cfb28.png)
![In_Game](https://user-images.githubusercontent.com/62343878/76985710-3fd70d80-6906-11ea-9c41-57066cea10e3.png)

#### Log file :
Without OpenAL:
[Trine_IgnoreMissingServicesOFF.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4350124/Trine_IgnoreMissingServicesOFF.zip)

With OpenAL:
[Trine_IgnoreMissingServicesOFF_OpenAL.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4350273/Trine_IgnoreMissingServicesOFF_OpenAL.zip)

**Comment by AcK77** [comment]
The OpenAL issue isn't game specific, it's an issue between the emulator and the system you run it.
Ignore missing services isn't needed here as your logs specified it and you don't have to provide logs if there is no errors returned.
Additionnally to that, your game is slow because you use Debug log, remove them and it should be better.

**Comment by EmulationFanatic** [comment]
Updated
