### ISSUE TITLE
Dairoku: Ayakashimori

### ISSUE THREAD

**Issue by Kaizen-mini** [Ryujinx/Ryujinx-Games-List#2540]
**Game Name :** Dairoku: Ayakashimori

**Game Update Version :** 1.0.1

**Current on `master` : Commit Id *or* Build Version :** 1.0.5391

Game stuck in an infinite booting/loading loop.

**Hardware Specs :** 

CPU: i5-6600K
GPU: NVIDIA GeForce GT 730
RAM: 16GB

**Log file :**
[Ryujinx_2020-09-21_02-54-35.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5252528/Ryujinx_2020-09-21_02-54-35.log)

**Comment by AcK77** [comment]
Needs update

**Comment by Kaizen-mini** [comment]
**Game Name :** Dairoku: Ayakashimori

**Game Update Version :** 1.0.1

**Current on `master` : Commit Id *or* Build Version :** 1.0.6895

Game crashes immediately when loading.

```
00:00:12.104 |W| GUI.RenderLoop Gpu FetchParam: Macro attempted to fetch an inexistent argument.
00:00:12.133 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000004
   at Ryujinx.Cpu.MemoryManagerHostMapped.AssertValidAddressAndSize(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 121
   at Ryujinx.Cpu.MemoryManagerHostMapped.SignalMemoryTracking(UInt64 va, UInt64 size, Boolean write) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 403
   at Ryujinx.Cpu.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 277
   at Ryujinx.Graphics.Gpu.Engine.Methods.LaunchDma(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 46
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.RendererWidgetBase.Render() in C:\projects\ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 307
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Hardware Specs :** 

CPU: i5-6600K
GPU: NVIDIA GeForce GT 730
RAM: 16GB

**Log file :**
[Ryujinx_1.0.6895_2021-05-30_01-25-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6565182/Ryujinx_1.0.6895_2021-05-30_01-25-46.log)

**Comment by benderscruffy** [comment]
using 1.0.7112
goes ingame now
no problems so far
![ryujinx_capture_2021-11-30_13-05-10](https://user-images.githubusercontent.com/2696404/143989098-62759221-9df3-4368-b03f-abe76db76eac.png)
![ryujinx_capture_2021-11-30_13-05-22](https://user-images.githubusercontent.com/2696404/143989103-0cf299e6-b5bd-4ce3-9682-fd21253e420d.png)
![ryujinx_capture_2021-11-30_13-05-37](https://user-images.githubusercontent.com/2696404/143989112-f9408ec0-d218-4e00-953f-3f582558fbc9.png)
![ryujinx_capture_2021-11-30_13-05-57](https://user-images.githubusercontent.com/2696404/143989118-cea32551-3e6a-4b68-b4ca-8397c866868b.png)
![ryujinx_capture_2021-11-30_13-06-02](https://user-images.githubusercontent.com/2696404/143989136-a5ebfbfa-cb21-4ef7-92f9-a271173c32a4.png)
![ryujinx_capture_2021-11-30_13-06-07](https://user-images.githubusercontent.com/2696404/143989146-48e5dd73-9a06-401e-a8ad-59c887bf163e.png)
![ryujinx_capture_2021-11-30_13-08-25](https://user-images.githubusercontent.com/2696404/143989152-655a2b42-8ac2-4963-b63c-39d141f9321e.png)
![ryujinx_capture_2021-11-30_13-08-34](https://user-images.githubusercontent.com/2696404/143989165-26f5c13c-19fb-4085-ab04-b67218f8a0e9.png)
