### ISSUE TITLE
Minecraft

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#2551]
#### Current on `master` : 1.0.5402

Game crashes after launching due to unimplemented services.

Note: This is the Bedrock version of Minecraft, released to replace Minecraft: Nintendo Switch Edition.
```
00:00:49.657 |E| CommonServer Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Nifm.StaticService.IGeneralService: 5

Guest Stack Trace:
Process: MinecraftPE-NX, PID: 81
   sdk:0x001538b8 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)4> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 26, 380ul> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::BufferArgumentInfo<0, 26, 380ul> > >::Process(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)4> > >::ProxyBaseObject*, nn::sf::cmif::client::BufferClientArgumentType, unsigned int)
   sdk:0x00152030 nn::sf::cmif::client::detail::CmifProxyImpl<nn::nifm::detail::IGeneralService, nn::sf::cmif::client::CmifDomainProxy<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)4> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<16384ul, nn::nifm::detail::ServiceProviderClient::CreateNifmUserServiceObjectTag> >, nn::nifm::detail::IGeneralService>::_nn_sf_sync_GetCurrentNetworkProfile(nn::sf::Out<nn::nifm::detail::sf::NetworkProfileData, void>)
   sdk:0x0015648c nn::nifm::GetCurrentNetworkProfile(nn::nifm::NetworkProfileData*)
   sdk:0x00156a4c nn::nifm::GetCurrentProxySetting(nn::nifm::ProxySetting*)
   main:0x0103ca18 Sub0000000009040a18
   main:0x00f53410 Sub0000000008f57410
   main:0x00f53200 Sub0000000008f57200
   main:0x0000c724 Sub0000000008010724
   main:0x00031014 Sub0000000008035014
   main:0x000094a4 Sub000000000800d4a4
   main:0x00015ef8 Sub0000000008019ef8
   main:0x00001488 nnMain
   sdk:0x0006edfc nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000ac Sub00000000080000ac

Buffer Information:
	RecvListBuff:
	Position: 0x000000000d236460 Size: 0x000000000000017c

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 00 00 00 00  05 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00 00 00 00 00  60 64 23 0D 00 00 7C 01   ········`d#···|·

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(IpcRequest message) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 138
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\projects\ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[MinecraftBedrock.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5264931/MinecraftBedrock.log)

**Comment by KrutavShah** [comment]
With "Ignore Missing Services" enabled, the game will run and you can play, but if you try to save the game it will crash. Tested on Ryujinx 1.0.6341, Intel i5-7600k, 8GB RAM, GTX 1060.
``Missing service Ryujinx.HLE.HOS.Services.Am.AppletOE.ApplicationProxyService.ApplicationProxy.IApplicationFunctions: 25 ignored``

**Comment by Deathlife23** [comment]
Tried on v1.16.210, "Ignore Missing Services" enabled, blue screen. Running on LDN2.1 build.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Benedani** [comment]
Adding that using resolution scaling causes the graphics to disappear.
![image](https://user-images.githubusercontent.com/18270989/124349019-61d4cc00-dbed-11eb-9611-b1747e738e02.png)

**Comment by LBmaster001** [comment]
Newer Updates (1.17.10) will crash when Loading into the Game at 71% with the following crash log entry:
```
00:00:12.557 |E| HLE.OsThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Ssl.ISslService: 3

Guest Stack Trace:
Process: Service, PID: 92

Buffer Information:
	SendBuff:
	Position: 0x0000001b80000794 Size: 0x0000000000000004 Flags: 0

Raw Request Data:
00000000   01 00 10 00 01 00 00 00  00 00 00 00 C0 D1 99 15   ············ÀÑ·
00000010   53 46 43 49 01 00 00 00  03 00 00 00 00 00 00 00   SFCI············
00000020   00 00 00 00                                        ····            

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
The Base game without updates is playable, but still has some flickering of visual bugs (see Screenshot):
![grafik](https://user-images.githubusercontent.com/23264393/131213785-988cdfd1-9248-4db1-8774-c6ba4708b589.png)
Same Position as on the Screenshot above, but changed camera angle
![grafik](https://user-images.githubusercontent.com/23264393/131213805-c8e1f541-f306-46d3-b14b-075193d8b669.png)
![grafik](https://user-images.githubusercontent.com/23264393/131213893-c2f91ee8-3d46-4f2d-ace9-c67dd69a4194.png)

**Comment by lani4565** [comment]
How dowload the gme for place in ryujinx

**Comment by tdadvocate** [comment]
Game Update Version : 1.18.2 
Current on master : 1.0.7161
Confirming the same results as LBmaster001 on latest version
Hardware Specs :
CPU: Ryzen 9 3900X
GPU: NVIDIA GeForce RTX 2080 Super
RAM: 32GB

**Comment by piplup55** [comment]
since ryujinx version [**1.1.3**](https://github.com/Ryujinx/Ryujinx/issues/3236) the game has started to crash on world load and sometimes on game menu load

**Comment by Yoshimit** [comment]
Game Update Version : 1.14.60
Current on master : 1.1.196

The game just hang when open a world/save. No crash. No nothing.

Hardware Specs :
GPU: NVIDIA GeForce GTX 1070
RAM: 8GB

**Comment by EmulationFanatic** [comment]
Game is still running fine on 1.2.12.0

**Comment by MarkLanders777** [comment]
Minecraft 1.14.60 runs but freeze when you are loading the world
![FREEZE1 4](https://user-images.githubusercontent.com/82430579/195966248-08beb7a4-797c-4985-a4a0-aa84b4be3a7e.png)

Minecraft 1.0.0 in OGL has some issues
![MC1 0OGL](https://user-images.githubusercontent.com/82430579/195966274-cfb9db9b-fdd0-4b3c-9593-9b11da19d806.png)

But it works fine in Vulkan
![MC1 0VULKAN](https://user-images.githubusercontent.com/82430579/195966288-83ccadfe-dd69-446d-9070-8e50324130de.png)

Minecraft 1.16.0 stays in a loop state, it never loads the world map but it doesn't crash either, no errors on console or crashes
![mc1 1 6](https://user-images.githubusercontent.com/82430579/195966397-cac8d5d8-6110-491c-9f6d-e37e207e8217.png)

**Comment by Meistache** [comment]
Same issues reported by @MarkLanders777 on update 1.19.73, still working fine on base version using Vulkan. Game freezes when you try going back to main menu when dying (maybe just got that issue because I'm a total noob).

**Comment by Darknior** [comment]
Same issue for me, i have try many versions .... and the last one was :

- Minecraft [0100D71004694000] [v1.19.60]

And it freeze when generating the world :(
I really wish one day some one will found how to fix this problem.
For me it is the best Minecraft version ever, with the split screen to play in famille with children :)
Thanks

**Comment by Sab44** [comment]
Game Update Version : 1.2.12.0
Current on master : 1.1.1100

Can confirm game is playable at this version, split screen does also work (tested with 2 players). But: when you try to save and quit to main menu it crashes. Therefore you can't save your progress.

It's rather unfortunate that saving and quitting doesn't work, as this would be the ideal way to play split screen on PC (without a huge hassle as with Nucleus coop).

**Comment by piplup55** [comment]
LDN is broken even on hardware tested using 3 different switch's (tried with and without mitm)
according to the [lan-play doc](https://docs.google.com/spreadsheets/d/1Eg_EE0xsBytSyWr7mtvD0MGUjCjyDJBXrHJ8ra8q8-8) "Require Linked Nintendo Account and be friends on Nintendo Account"

Switch's used for testing:
- Switch v1 10.2.0 | AMS 1.6.2 | E
- Switch v2 17.0.1 | AMS 1.6.2 | E
- Switch Patched Unit 17.0.1 | OFW

**Comment by woliver99** [comment]
Can confirm that the version without any updates work but the latest version crashes on start with a `Ryujinx.Memory.InvalidMemoryRegionException`
This is with ldn disabled
[Ryujinx_1.1.1325_2024-06-02_08-47-26.log](https://github.com/user-attachments/files/15525350/Ryujinx_1.1.1325_2024-06-02_08-47-26.log)

**Comment by tmortagne** [comment]
Game Update Version : 1.20.62
Current on master : 1.1.1330

Hardware Specs :
* CPU: Intel Core i7-7500U
* GPU: NVIDIA GeForce 940MX
* RAM: 12GB

System: Windows 10 64b

Ryujinx crashes during the boot with:

```
00:00:29.814 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000001
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.SignalMemoryTracking(UInt64 va, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 393
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 285
   at Ryujinx.Graphics.Gpu.Memory.PhysicalMemory.GetSpan(UInt64 address, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\PhysicalMemory.cs:line 129
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 226
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Read[T](UInt64 va, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 98
   at Ryujinx.Graphics.Gpu.Engine.Dma.DmaClass.CopyGobBlockLinearToLinear(MemoryManager memoryManager, UInt64 srcGpuVa, UInt64 dstGpuVa, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Dma\DmaClass.cs:line 605
   at Ryujinx.Graphics.Gpu.Engine.Dma.DmaClass.DmaCopy(Int32 argument) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Dma\DmaClass.cs:line 443
   at Ryujinx.Graphics.Gpu.Engine.Dma.DmaClass.LaunchDma(Int32 argument) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Dma\DmaClass.cs:line 659
   at Ryujinx.Graphics.Device.DeviceState`1.Write(Int32 offset, Int32 data) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Device\DeviceState.cs:line 108
   at Ryujinx.Graphics.Gpu.Engine.Dma.DmaClass.Write(Int32 offset, Int32 data) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Dma\DmaClass.cs:line 129
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 242
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 229
   at Ryujinx.HLE.Switch.ProcessFrame() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Switch.cs:line 105
   at Ryujinx.Ava.AppHost.<RenderLoop>b__110_1() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 1003
   at System.Threading.Thread.StartCallback()
```

**Comment by alfonsico** [comment]
Nothing change for now
macOS 14.5 Silicon M2
Current on master: 1.1.1336
Game base: 1.2.12 playable but freeze when try to exit or die
Game base: 1.17.11 start up to create the world that never end
Game base: 1.20.xx or 1.21 crash, no load

**Comment by mitch03** [comment]
Is there a reason why it doesn't launch on Ryujinx?  (requires an account or internet, etc..)?

**Comment by ttys42** [comment]
> Is there a reason why it doesn't launch on Ryujinx? (requires an account or internet, etc..)?

The reason is called "bug"
