### ISSUE TITLE
PGA TOUR 2K21

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#2552]
#### Current on `master` : 1.0.5402

Game crashes at launch

```
00:00:43.477 |E| CommonServer Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletOE.ApplicationProxyService.ApplicationProxy.IApplicationFunctions: 141

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x000081c0 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> >, 0ul, 0ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> > >::ProcessWithOutObjects(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*)
   sdk:0x00030368 nn::sf::cmif::client::detail::CmifProxyImpl<nn::am::service::IApplicationFunctions, nn::sf::cmif::client::CmifDomainProxyKind<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::MemoryResourceAllocationPolicy, nn::am::service::IApplicationFunctions, nn::sf::cmif::client::detail::ProcessModifierImpl<nn::sf::cmif::client::DefaultProxyFilterTag> >::_nn_sf_sync_TryPopFromFriendInvitationStorageChannel(nn::sf::Out<nn::sf::SharedPointer<nn::am::service::IStorage>, void>)
   sdk:0x0019d308 nn::friends::TryPopFriendInvitationNotificationInfo(nn::account::Uid*, unsigned long*, void*, unsigned long)
   main:0x0285cdcc Sub000000000a860dcc
   main:0x008b44c4 Sub00000000088b84c4
   main:0x00166e44 Sub000000000816ae44
   main:0x035440f0 Sub000000000b5480f0
   main:0x035e29a4 Sub000000000b5e69a4
   main:0x035d07f0 Sub000000000b5d47f0
   main:0x03c7c864 Sub000000000bc80864
   main:0x037d1b44 Sub000000000b7d5b44
   main:0x03681a68 Sub000000000b685a68
   main:0x03681a9c Sub000000000b685a9c
   main:0x03681dc4 Sub000000000b685dc4
   main:0x035ce73c nnMain
   sdk:0x002a3864 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
   rtld:0x000000d4 Sub00000000080000d4

Raw Request Data:
00000000   01 00 10 00 03 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  8D 00 00 00 00 00 00 00   SFCI···········
00000020   E4 07 0C 1E 00 00 00 00  03 00 00 00 6C 01 00 00   ä···········l···

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(IpcRequest message) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 138
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\projects\ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[PGA_2K21.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5265309/PGA_2K21.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
