### ISSUE TITLE
Norn9 ~Norn + Nonette~ LOFN

### ISSUE THREAD

**Issue by Kaizen-mini** [Ryujinx/Ryujinx-Games-List#2560]
**Game Name :** Norn9 -Norn + Nonette- LOFN

**Game Update Version :** 1.0.0

**Current on `master` : Commit Id *or* Build Version :** 1.0.5418

Ryujinx crashes whenever trying to launch the game.

```
00:00:21.955 |I| NvservicesServer ServiceNv Create: Created map 121 with size 0x00080000!
00:00:22.043 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 515
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 151
   at Ryujinx.Graphics.Gpu.Engine.Methods.FinishTransfer() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 79
   at Ryujinx.Graphics.Gpu.Engine.Methods.LoadInlineData(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 66
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 111
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.MME.MacroJit.Execute(ReadOnlySpan`1 code, GpuState state, Int32 arg0) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MME\MacroJit.cs:line 37
   at Ryujinx.Graphics.Gpu.Engine.MME.Macro.Execute(ReadOnlySpan`1 code, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MME\Macro.cs:line 66
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoClass.CallMme(Int32 index, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoClass.cs:line 210
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 173
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 59
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.HLE.Switch.ProcessFrame() in C:\projects\ryujinx\Ryujinx.HLE\Switch.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 334
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Hardware Specs :** 

CPU: i5-6600K
GPU: NVIDIA GeForce GT 730
RAM: 16GB

**Log file :**
[Ryujinx_2020-09-24_22-30-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5277302/Ryujinx_2020-09-24_22-30-46.log)

**Comment by Kaizen-mini** [comment]
**Game Name :** Norn9 -Norn + Nonette- LOFN

**Game Update Version :** 1.0.0

**Current on `master` : Commit Id *or* Build Version :** 1.0.6895

Ryujinx still crashes whenever trying to launch the game.

```
00:00:11.750 |I| HLE.OsThread.10 ServiceNv Create: Created map 121 with size 0x00080000!
00:00:11.814 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000004
   at Ryujinx.Cpu.MemoryManagerHostMapped.AssertValidAddressAndSize(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 121
   at Ryujinx.Cpu.MemoryManagerHostMapped.SignalMemoryTracking(UInt64 va, UInt64 size, Boolean write) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 403
   at Ryujinx.Cpu.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 277
   at Ryujinx.Graphics.Gpu.Engine.Methods.LaunchDma(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 46
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.RendererWidgetBase.Render() in C:\projects\ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 307
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Hardware Specs :** 

CPU: i5-6600K
GPU: NVIDIA GeForce GT 730
RAM: 16GB

**Log file :**
[Ryujinx_1.0.6895_2021-05-30_02-56-17.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6565268/Ryujinx_1.0.6895_2021-05-30_02-56-17.log)

**Comment by EmulationFanatic** [comment]
Needs an update

**Comment by EmulationFanatic** [comment]
Updated
