### ISSUE TITLE
Disaster Report 4: Summer Memories

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#2561]
#### Current on `master` : 1.0.5418

Game crashes during launch.

```
00:01:50.526 |E| HLE.HostThread.21 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1331
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 54
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[DisasterReport4.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5277407/DisasterReport4.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6787

**Comment by gdkchan** [comment]
Needs an update.

**Comment by benderscruffy** [comment]
using 1.0.7101
goes ingame with glitchy graphics now
![ryujinx_capture_2021-11-09_17-11-15](https://user-images.githubusercontent.com/2696404/141070051-aecf9bca-83de-490c-91ed-9945236008f7.png)
![ryujinx_capture_2021-11-10_15-24-45](https://user-images.githubusercontent.com/2696404/141070080-32747fa0-4848-4e5b-a57a-683c1f12f74b.png)
![ryujinx_capture_2021-11-10_15-25-55](https://user-images.githubusercontent.com/2696404/141070091-66028335-b93a-4a09-9865-c3e30f29f615.png)
![ryujinx_capture_2021-11-10_15-34-04](https://user-images.githubusercontent.com/2696404/141070103-5e7b7bec-f02b-4b23-a6cf-b6abdd0e3264.png)
![ryujinx_capture_2021-11-10_15-36-37](https://user-images.githubusercontent.com/2696404/141070116-b15f017b-9a81-4b1e-979f-8f66ae734645.png)
![ryujinx_capture_2021-11-10_15-37-24](https://user-images.githubusercontent.com/2696404/141070131-1638f481-e4ae-433b-8759-5c6f2b595b28.png)

**Comment by EmulationFanatic** [comment]
Updated
