### ISSUE TITLE
Gothic Murder: Adventure That Changes Destiny

### ISSUE THREAD

**Issue by Kaizen-mini** [Ryujinx/Ryujinx-Games-List#2566]
**Game Name :** Gothic Murder: Adventure That Changes Destiny

**Game Update Version :** 1.0.0

**Current on `master` : Commit Id *or* Build Version :** 1.0.5428

Game runs fine, with occasional problems described below:

- FPS drops (sometimes near 0) whenever at loading screen

- The game would freeze and FPS completely drops to 0 from time to time (when and why it happens seems random). When that happens this is shown in the log :

```
00:08:46.368 |S| CommonServer ServiceAm LockExit: Stubbed. 
00:08:46.385 |S| CommonServer ServiceAm UnlockExit: Stubbed. 
00:08:46.385 |S| CommonServer ServiceAm LockExit: Stubbed. 
```
An empty folder named "_" is also created in the save location of the game - whereas the 0 folder is gone.

The only way is to exit the game. Trying to boot the game up right after that will lead to Ryujinx crashing with this error :

```
00:00:16.635 |W| HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:16.688 |W| HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:28.701 |S| CommonServer ServiceAcc InitializeApplicationInfo: Stubbed. {unknown: 0}
00:00:28.763 |S| CommonServer ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:28.886 |E| CommonServer Application : Unhandled exception caught: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MemoryBlock'.
   at Ryujinx.Memory.MemoryBlock.ThrowObjectDisposed() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 287
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 151
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(IpcRequest message) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 138
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\projects\ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
At this time the 0 folder is created in the game's save location (with the latest save and auto save up until before the game froze). The _ folder now seems to have the same content as the 0 folder.

![explorer_tDRlz3u5Sq](https://user-images.githubusercontent.com/71459954/94342376-e0875200-003a-11eb-80c3-b592965752ff.png)

After that, restarting Ryujinx, the game boots again normally to the title screen. However any attempt to start a new game, load from a save... will only result in the game freezing with a black screen at 0 FPS.
Close the game, delete only the _ folder and everything runs as smooth as ever (until the problem happens again...).

**Hardware Specs :** 

CPU: i5-6600K
GPU: NVIDIA GeForce GT 730
RAM: 16GB

**Screenshots :**

![Ryujinx_aWGl8OfgX9](https://user-images.githubusercontent.com/71459954/94342279-40c9c400-003a-11eb-9885-3b917d2367db.jpg)
![Ryujinx_iEzGoQ35mj](https://user-images.githubusercontent.com/71459954/94342288-52ab6700-003a-11eb-9d12-c1e3e26b58a6.png)
![Ryujinx_eZhO6H5FkX](https://user-images.githubusercontent.com/71459954/94342324-900ff480-003a-11eb-9e2d-bc151b7da0d7.png)
![Ryujinx_Gg7e4PCfkE](https://user-images.githubusercontent.com/71459954/94342315-81c1d880-003a-11eb-98d7-398dd8f90f27.png)
![Ryujinx_ftSfRKXZWe](https://user-images.githubusercontent.com/71459954/94342341-a3bb5b00-003a-11eb-8f26-a1e6d1276c81.png)
![Ryujinx_6AoU2O9Qvd](https://user-images.githubusercontent.com/71459954/94342351-b59cfe00-003a-11eb-867e-da62f28beb81.png)
![Ryujinx_6pac633jLL](https://user-images.githubusercontent.com/71459954/94342360-c2b9ed00-003a-11eb-8dab-12ffa742a25b.png)
![Ryujinx_GCUVKSTPPX](https://user-images.githubusercontent.com/71459954/94342367-c8afce00-003a-11eb-961d-f76172e8baaa.png)

**Log file :**
[GothicMLogs.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5286772/GothicMLogs.zip)

**Comment by benderscruffy** [comment]
needs updating
