### ISSUE TITLE
Grand Theft Auto 3

### ISSUE THREAD

**Issue by FranciscoCarlosJunior** [Ryujinx/Ryujinx-Games-List#2567]
Game Name: Grand Theft Auto 3

Game Update Version : 0.69

Current on `master` : Commit Id *or* Build Version : 1.0.5428

Crashes on Launch

e.g.: 00:00:01.960 |E| CommonServer Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Pm.IShellInterface: 8

Guest Stack Trace:
Process: Application, PID: 81
   rtld:0x000005f8 Sub00000000080005f8
   rtld:0x00000228 Sub0000000008000228
   rtld:0x000001c0 Sub00000000080001c0

Raw Request Data:
00000000   53 46 43 49 00 00 00 00  08 00 00 00 00 00 00 00   SFCIÂ·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·
00000010   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·Â·

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(IpcRequest message) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 86
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\projects\ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Hardware Specs : 

CPU: *Intel Core i5-6200U 2.3Ghz*
GPU: *NVIDIA Geforce GTX 920MX*
RAM: *8GB*

#### Log file :
[Ryujinx_2020-09-26_13-16-26.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5287075/Ryujinx_2020-09-26_13-16-26.log)

**Comment by tilsgee** [comment]
I can confirm: GTA 3 works.

![20230502_044058.jpg](https://user-images.githubusercontent.com/62179071/235536496-4a1ed0d7-4072-4f0f-bf05-2e88dcacc4d6.jpg)

**Comment by piplup55** [comment]
> I can confirm: GTA 3 works.
> 
> ![20230502_044058.jpg](https://user-images.githubusercontent.com/62179071/235536496-4a1ed0d7-4072-4f0f-bf05-2e88dcacc4d6.jpg)

that is not the homebrew version of gta 3, that is The Definitive Edition reports go here https://github.com/Ryujinx/Ryujinx-Games-List/issues/4154
