### ISSUE TITLE
Meiji Katsugeki Haikara Ryuuseigumi - Seibai Shimaseu, Yonaoshi Kagyou -

### ISSUE THREAD

**Issue by Kaizen-mini** [Ryujinx/Ryujinx-Games-List#2575]
**Game Name :** Meiji Katsugeki Haikara Ryuuseigumi - Seibai Shimaseu, Yonaoshi Kagyou -

**Game Update Version :** 1.0.0

**Current on `master` : Commit Id *or* Build Version :** 1.0.5459

Ryujinx crashes whenever trying to launch the game.

```
00:00:13.701 |I| HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   main:0x00000914 Sub0000000000204914
   main:0x00000490 Sub0000000000204490
   main:0x00000424 Sub0000000000204424
   main:0x000ceec8 nnMain
   sdk:0x000a9a44 nn::init::Start(unsigned int, unsigned int, void (*)(), void (*)())
   rtld:0x000000b4 Sub00000000002000b4


00:00:13.720 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000000307138 (opcode 0xe320f004) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1109
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 136
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Hardware Specs :** 

CPU: i5-6600K
GPU: NVIDIA GeForce GT 730
RAM: 16GB

**Log file :**
[Ryujinx_2020-09-30_11-58-14.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5303178/Ryujinx_2020-09-30_11-58-14.log)

**Comment by benderscruffy** [comment]
using 1.1.21
crashes out with a new error now
00:00:13.299 |E| HLE.GuestThread.14 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000000307138 (opcode 0xe320f004) is undefined!
[Ryujinx_1.1.21_2022-02-09_16-22-21.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8030894/Ryujinx_1.1.21_2022-02-09_16-22-21.log)

**Comment by EmulationFanatic** [comment]
Updated
