### ISSUE TITLE
LEGO Marvel Super Heroes 2

### ISSUE THREAD

**Issue by FranciscoCarlosJunior** [Ryujinx/Ryujinx-Games-List#2577]
Game Name: LEGO Marvel Super Heroes 2

Game Update Version : 1.0.0

Current on `master` : Commit Id *or* Build Version : 1.0.5428

Crashes on Launch

e.g.: 00:00:40.464 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 368
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 229
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 572
   at Ryujinx.Graphics.Gpu.Image.Texture.InitializeData(Boolean isView, Boolean withData) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 187
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureInfo info, TextureSearchFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 824
   at Ryujinx.Graphics.Gpu.Window.Present(Action swapBuffersCallback) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Window.cs:line 159
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 348
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Hardware Specs : 

CPU: Intel Core i5-6200U
GPU: NVIDIA Geforce 920MX
RAM: 8GB

Log file :
[Ryujinx_2020-10-01_13-22-50.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5313835/Ryujinx_2020-10-01_13-22-50.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6807

**Comment by 6Fer6** [comment]
Game Name: LEGO Marvel Super Heroes 2

Game Update Version : 1.0.6

Current on `master`: 1.0.7024

Crashes on Launch, Now With a Different Error Message
```
00:00:09.700 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0x0000000FA1A70000, size=0x0000000000870000
```

Hardware Specs :

CPU: Intel Core i5-3570S
GPU: NVIDIA Geforce 1060 3GB
RAM: 16GB

Log file : [Ryujinx_1.0.7024_2021-09-06_20-45-54.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7118058/Ryujinx_1.0.7024_2021-09-06_20-45-54.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.1.205

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Game Name: LEGO Marvel Super Heroes 2

Game Update Version : 1.0.6

Current on master : Commit Id or Build Version : 1.1.647

Crashes on Launch:

[Ryujinx_1.1.647_2023-03-02_18-09-29.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10873956/Ryujinx_1.1.647_2023-03-02_18-09-29.log)

![image](https://user-images.githubusercontent.com/88291316/222501963-7389bc01-f77e-4cd1-8293-6e95efa430e4.png)
