### ISSUE TITLE
RollerCoaster Tycoon 3: Complete Edition

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#2578]
#### Current on `master` : 1.0.5480

Game crashes on launch.

```
00:00:10.677 |E| CommonServer Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Fs.IFileSystemProxy: 205

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0007a5d8 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0>, nn::sf::cmif::detail::InRawArgumentInfo<1u, 1u, 0> >, 1u, 0u, false>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0>, nn::sf::cmif::detail::InRawArgumentInfo<1u, 1u, 0> > >::ProcessWithOutObjects(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<1u, 1u, void>, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*)
   sdk:0x00073be0 Sub00000000065cfbe0
   sdk:0x0008e6ac Sub00000000065ea6ac
   sdk:0x0008e53c Sub00000000065ea53c
   sdk:0x0008dce0 nn::fs::QueryMountRomCacheSize(unsigned int*, int)
   main:0x00aa34fc Sub0000000000ca74fc
   main:0x00aa33b0 Sub0000000000ca73b0
   main:0x00aa2450 Sub0000000000ca6450
   main:0x00a9c28c Sub0000000000ca028c
   main:0x00aa2600 Sub0000000000ca6600
   main:0x0000017c Sub000000000020417c
   rtld:0x0000075c Sub000000000020075c
   sdk:0x000a9a40 nn::init::Start(unsigned int, unsigned int, void (*)(), void (*)())
   rtld:0x000000b4 Sub00000000002000b4

Raw Request Data:
00000000   01 00 11 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  CD 00 00 00 00 00 00 00   SFCI····Í·······
00000020   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000030   00 00 00 00                                        ····            

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(IpcRequest message) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 86
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\projects\ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[RCT3-CE.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5320471/RCT3-CE.log)

**Comment by EmulationFanatic** [comment]
Thanks for the report!

**Comment by Mou-Ikkai** [comment]
Same status on 1.1.209!

**Comment by EmulationFanatic** [comment]
Updated
