### ISSUE TITLE
Steam Tactics

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2588]
#### Current on `master` : 1.0.5485

Crashes on launch in docked mode, but boots and plays properly for one level before crashing in handheld mode.

Docked mode crash:
```
GUI.WindowThread Application : Unhandled exception caught: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Ryujinx.HLE.HOS.Services.Hid.NpadDevices.UpdateSixAxis(IList`1 states) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Hid\HidDevices\NpadDevices.cs:line 340
   at Ryujinx.Ui.GlRenderer.UpdateFrame() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 549
   at Ryujinx.Ui.GlRenderer.MainLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 382
   at Ryujinx.Ui.GlRenderer.Start() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 220
   at Ryujinx.Ui.MainWindow.CreateGameWindow(Switch device) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 558
   at Ryujinx.Ui.MainWindow.<>c__DisplayClass54_0.<LoadApplication>b__1() in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 507
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Handheld mode crash:
```
CommonServer ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:05:12.228 |I| HLE.HostThread.10 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x000559c0 Sub000000000a9fe9c0
   sdk:0x00055a88 Sub000000000a9fea88
   sdk:0x00055b20 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   sdk:0x000d5f08 nn::os::detail::InternalConditionVariableImplByHorizon::Wait(nn::os::detail::InternalCriticalSection*)
   sdk:0x000cd898 nn::os::AcquireSemaphore(nn::os::SemaphoreType*)
   main:0x00f69a2c Sub0000000008f6da2c
   sdk:0x000d4ec4 Sub000000000aa7dec4
   ??? Sub0000000000000000
```

#### Screenshots :

![2020-10-03 03_47_29-Ryujinx 1 0 5485 - Steam Tactics v1 0 0 (0100AE100DAFA000) (64-bit)](https://user-images.githubusercontent.com/62343878/94988645-fbbafb80-052b-11eb-87cb-c16f0a489aff.png)
![2020-10-03 03_47_51-Ryujinx 1 0 5485 - Steam Tactics v1 0 0 (0100AE100DAFA000) (64-bit)](https://user-images.githubusercontent.com/62343878/94988648-02497300-052c-11eb-88f9-faa6b11d3e09.png)
![2020-10-03 03_47_55-Ryujinx 1 0 5485 - Steam Tactics v1 0 0 (0100AE100DAFA000) (64-bit)](https://user-images.githubusercontent.com/62343878/94988653-0d9c9e80-052c-11eb-9b03-5a683083852d.png)
![2020-10-03 03_48_05-Ryujinx 1 0 5485 - Steam Tactics v1 0 0 (0100AE100DAFA000) (64-bit)](https://user-images.githubusercontent.com/62343878/94988663-1ab98d80-052c-11eb-83b5-5a9a082c38c3.png)
![2020-10-03 03_48_41-Ryujinx 1 0 5485 - Steam Tactics v1 0 0 (0100AE100DAFA000) (64-bit)](https://user-images.githubusercontent.com/62343878/94988669-260cb900-052c-11eb-8340-7aa9332507b8.png)
![2020-10-03 03_49_22-Ryujinx 1 0 5485 - Steam Tactics v1 0 0 (0100AE100DAFA000) (64-bit)](https://user-images.githubusercontent.com/62343878/94988672-32911180-052c-11eb-8867-a93f76c582f3.png)
![2020-10-03 03_50_48-Ryujinx 1 0 5485 - Steam Tactics v1 0 0 (0100AE100DAFA000) (64-bit)](https://user-images.githubusercontent.com/62343878/94988674-3e7cd380-052c-11eb-8a53-05ecb36e8ec4.png)

#### Log file :

[ST_Docked.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5321390/ST_Docked.log)
[ST_Handheld.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5321391/ST_Handheld.log)

**Comment by EmulationFanatic** [comment]
Updated
