### ISSUE TITLE
Dei Gratia no Rashinban

### ISSUE THREAD

**Issue by Kaizen-mini** [Ryujinx/Ryujinx-Games-List#2635]
#### Current on `master` : Commit Id *or* Build Version : 1.0.5485

Ryujinx crashes whenever trying to launch the game.

```
00:00:42.103 |W| GUI.RenderLoop Gpu FetchParam: Macro attempted to fetch an inexistent argument.
00:00:42.103 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:00:42.127 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 515
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 151
   at Ryujinx.Graphics.Gpu.Engine.Methods.FinishTransfer() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 79
   at Ryujinx.Graphics.Gpu.Engine.Methods.LoadInlineData(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 66
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 111
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.MME.MacroJit.Execute(ReadOnlySpan`1 code, GpuState state, Int32 arg0) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MME\MacroJit.cs:line 37
   at Ryujinx.Graphics.Gpu.Engine.MME.Macro.Execute(ReadOnlySpan`1 code, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MME\Macro.cs:line 66
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoClass.CallMme(Int32 index, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoClass.cs:line 210
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 173
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 59
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.HLE.Switch.ProcessFrame() in C:\projects\ryujinx\Ryujinx.HLE\Switch.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 342
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs : 

CPU: i5-6600K
GPU: NVIDIA GeForce GT 730
RAM: 16GB

#### Log file :
[Ryujinx_2020-10-05_23-30-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5328738/Ryujinx_2020-10-05_23-30-44.log)

**Comment by vojo915** [comment]
**Game Version:** 1.0.0
**Current on `master` : Build Version** 1.0.6963

**Hardware Specs:**

**CPU:** Ryzen 5 3600
**GPU:** GeForce GTX 1660 Ti
**RAM:** 16GB

Playable. But the whole sound is glitch.

**Screenshots:**

![1_q99](https://user-images.githubusercontent.com/84438932/125380163-b7b72a00-e3cc-11eb-8e1c-699734594ade.jpg)

![2_q99](https://user-images.githubusercontent.com/84438932/125380175-bc7bde00-e3cc-11eb-8108-fc49baf1fe2f.jpg)

![3_q99](https://user-images.githubusercontent.com/84438932/125380184-c00f6500-e3cc-11eb-8e12-9bd1f46ab040.jpg)

![4_q99](https://user-images.githubusercontent.com/84438932/125380193-c4d41900-e3cc-11eb-8fec-64488de69489.jpg)

![5_q99](https://user-images.githubusercontent.com/84438932/125380205-c9003680-e3cc-11eb-8f25-5748296e5597.jpg)

![6_q99](https://user-images.githubusercontent.com/84438932/125380217-cd2c5400-e3cc-11eb-84d9-1c47a68c1497.jpg)

**Log file:** 
[Ryujinx_1.0.6963_010071C00CBA4000.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/6805459/Ryujinx_1.0.6963_010071C00CBA4000.zip)
