### ISSUE TITLE
nxquake2

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#2650]
#### Current on `master` : 1.0.5485

[This is a homebrew port of Quake 2.
](https://github.com/fgsfdsfgs/nxquake2/releases/tag/NXQUAKE2_020)

Game crashes at launch.
```
00:00:01.284 |E| SmServer Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: apm:p
   at Ryujinx.HLE.HOS.Services.Sm.IUserInterface.GetService(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Sm\IUserInterface.cs:line 113
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 114
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(IpcRequest message) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 86
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\projects\ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[nxquake2.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5345015/nxquake2.log)

**Comment by AcK77** [comment]
`apm:p` service was removed from HOS since firmware 7.0.1. 
Ryujinx currently follow the last firmware services so the crash occurs because the homebrew is outdated.

**Comment by benderscruffy** [comment]
same status on 1.0.7096

**Comment by LukeWarnut** [comment]
Updated.

**Comment by LukeWarnut** [comment]
Needs labels: homebrew, status-playable
