### ISSUE TITLE
Pikmin 3 Deluxe Demo

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#2656]
#### Current on `master` : 1.0.5485

Game performs relatively well. Minor graphical issues can be seen (Whistle doesn't render properly, screenshot 5). Game crashed upon opening up a Piklopedia entry

```
00:12:29.677 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 357
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 229
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![title](https://user-images.githubusercontent.com/65521430/95462117-14208100-0945-11eb-8113-9e6ca4bdce00.png)
![storyselect](https://user-images.githubusercontent.com/65521430/95462148-20a4d980-0945-11eb-8484-6283ec93e73c.png)
![storycutscene](https://user-images.githubusercontent.com/65521430/95462185-2ef2f580-0945-11eb-8a3e-5eed214aed58.png)
![onioncutscene](https://user-images.githubusercontent.com/65521430/95462223-3c0fe480-0945-11eb-9dcc-0b56f974d443.png)
![whistlebug](https://user-images.githubusercontent.com/65521430/95462262-45994c80-0945-11eb-9585-ad2f347bc22b.png)
![pad](https://user-images.githubusercontent.com/65521430/95462295-4e8a1e00-0945-11eb-9b10-c2f413fc8491.png)
![normalgameplay](https://user-images.githubusercontent.com/65521430/95462318-58138600-0945-11eb-8541-087094801817.png)

#### Log file :

[Pikmin3DeluxeDemo.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5347968/Pikmin3DeluxeDemo.log)

**Comment by LukeWarnut** [comment]
Updated
