### ISSUE TITLE
Street Power Soccer

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2691]
#### Current on `master` : 1.0.5499

Game crashes after the developer logo is over.

```
00:02:35.652 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 515
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 351
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 229
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Read[T](UInt64 gpuVa) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 58
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(IGpuAccessor gpuAccessor, Block block, UInt64 limitAddress, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 232
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(IGpuAccessor gpuAccessor, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 76
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, ShaderConfig& config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 79
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 19
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateGraphicsShader(GpuState state, TranslationFlags flags, ShaderStage stage, UInt64 gpuVa, UInt64 gpuVaA) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 373
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 149
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 985
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 122
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 149
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 41
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 342
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-10-12 14-48-02-597](https://user-images.githubusercontent.com/35269098/95719985-d8feb480-0c9a-11eb-98f8-9e78ff230005.jpg)
![bandicam 2020-10-12 14-48-08-540](https://user-images.githubusercontent.com/35269098/95719998-db610e80-0c9a-11eb-8990-34da88de8bc8.jpg)
![bandicam 2020-10-12 14-49-35-946](https://user-images.githubusercontent.com/35269098/95720006-dd2ad200-0c9a-11eb-9ece-d3e91f18ab1a.jpg)

#### Logs :

[SPS.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5363742/SPS.log)

**Comment by Cronos-0** [comment]
The game crashes again after booting to the title screen.
