### ISSUE TITLE
INMOST

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2697]
#### Current on `master` : 1.0.5517

Game loaded and was playing mostly smoothly when it suddenly crashed.

```
CommonServer Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 102
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(IpcRequest message) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 138
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\projects\ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 37
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-10-13 14_39_39-Ryujinx 1 0 5517 - INMOST v1 0 0 (0100F1401161E000) (64-bit)](https://user-images.githubusercontent.com/62343878/95914924-a8368200-0d63-11eb-863d-01f93fb37059.png)
![2020-10-13 14_40_13-Ryujinx 1 0 5517 - INMOST v1 0 0 (0100F1401161E000) (64-bit)](https://user-images.githubusercontent.com/62343878/95914940-ae2c6300-0d63-11eb-997f-1d3dbd153802.png)
![2020-10-13 14_40_58-Ryujinx 1 0 5517 - INMOST v1 0 0 (0100F1401161E000) (64-bit)](https://user-images.githubusercontent.com/62343878/95914949-b2588080-0d63-11eb-9710-59b88bff00fe.png)
![2020-10-13 14_44_31-Ryujinx 1 0 5517 - INMOST v1 0 0 (0100F1401161E000) (64-bit)](https://user-images.githubusercontent.com/62343878/95914953-b4224400-0d63-11eb-89c3-c8ea12edbc3d.png)
![2020-10-13 14_44_55-Ryujinx 1 0 5517 - INMOST v1 0 0 (0100F1401161E000) (64-bit)](https://user-images.githubusercontent.com/62343878/95914958-b6849e00-0d63-11eb-90e0-08d47ff83117.png)
![2020-10-13 14_45_35-Ryujinx 1 0 5517 - INMOST v1 0 0 (0100F1401161E000) (64-bit)](https://user-images.githubusercontent.com/62343878/95914964-b97f8e80-0d63-11eb-99df-3325583a2bca.png)
![2020-10-13 14_49_41-Ryujinx 1 0 5517 - INMOST v1 0 0 (0100F1401161E000) (64-bit)](https://user-images.githubusercontent.com/62343878/95914969-bd131580-0d63-11eb-9931-c40b41583109.png)
![2020-10-13 14_50_30-Ryujinx 1 0 5517 - INMOST v1 0 0 (0100F1401161E000) (64-bit)](https://user-images.githubusercontent.com/62343878/95914975-c00e0600-0d63-11eb-81e8-5748ddf64279.png)

#### Log file :

[INMOST.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5374027/INMOST.log)

**Comment by SeraUQ** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
