### ISSUE TITLE
FuzzBall

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2701]
#### Current on `master` : 1.0.5525

Crashes on launch.

```
HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   main:0x0185e1a4 Sub00000000098621a4
   main:0x0185e1a4 Sub00000000098621a4
   main:0x01257fdc Sub000000000925bfdc
   main:0x0125efc8 Sub0000000009262fc8
   main:0x0120f088 nnMain
   sdk:0x002a3864 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
   rtld:0x000000d4 Sub00000000080000d4


00:00:07.650 |E| HLE.HostThread.0 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000420.
00:00:07.668 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 151
   at Ryujinx.Cpu.MemoryManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 133
   at ARMeilleure.Instructions.NativeInterface.WriteVector128(UInt64 address, V128 value) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 214
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[FB.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5377912/FB.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6807
