### ISSUE TITLE
Perky Little Things

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2712]
#### Current on `master` : 1.0.5525

Game crashes on boot a few seconds after starting playing audio.

```
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 229
   at Ryujinx.Graphics.Gpu.Memory.Buffer.SynchronizeMemory(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 128
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.GetBuffer(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 818
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CommitGraphicsBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 557
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 303
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 122
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 149
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawIndexedSmall(GpuState state, Int32 argument, Boolean instanced) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 276
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawIndexedSmall(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 220
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawIndexedSmall2(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 230
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 344
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[PLT.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5381713/PLT.log)

**Comment by gdkchan** [comment]
Needs an update.

**Comment by hellomynameisnoone** [comment]
Black screen when booted, can ear music but no graphic
tested with Vulkan and OpenGL, native and 2X resolution

Ryujinx 1.1.1051

Screenshot:
![PLT](https://github.com/Ryujinx/Ryujinx-Games-List/assets/147877928/12a1e074-46bb-4d1c-9347-193cc6ebae43)

Log:


[Ryujinx_1.1.1051_2023-10-13_21-35-55.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12898220/Ryujinx_1.1.1051_2023-10-13_21-35-55.log)

**Comment by hellomynameisnoone** [comment]
game boot, sound works, get got graphic, but controls wont work

![Screenshot 2023-10-22 195243](https://github.com/Ryujinx/Ryujinx-Games-List/assets/147877928/ce30352f-5a12-43b5-b664-bba281122bc8)



Apparently what I read in forums this title (in the original Nintendo Switch) works only on handheld mode, so I switched to handheld (unchecked "Enable Docked Mode") and booted again and... still no controls

Tried to change the config input to Joycon Pair and Pro Controller and nothing

**Comment by GamerzHell9137** [comment]
> Now the game boot, sound works, and graphics, but controls wont work
> 
> ![Screenshot 2023-10-22 195243](https://user-images.githubusercontent.com/147877928/277184210-ce30352f-5a12-43b5-b664-bba281122bc8.png)
> 
> Apparently what I read in forums this title (in the original Nintendo Switch) works only on handheld mode, so I switched to handheld (unchecked "Enable Docked Mode") and booted again and... still no controls
> 
> Tried to change the config input to Joycon Pair and Pro Controller and nothing
> 
> [Ryujinx_1.1.1059_2023-10-22_20-14-21.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13064155/Ryujinx_1.1.1059_2023-10-22_20-14-21.log)

That's normal, game only works in handheld.

**Comment by Logicgatekeeper** [comment]
I tried to do in hanhheld still didn't work just black

**Comment by Logicgatekeeper** [comment]
How did you do it

**Comment by Zaloorpas** [comment]
Hi,

The game is fully playable with the last compilation.
In order to play, you must set Ryujinx as Handheld and then, set up the controller as Handheld as well.

![imagen](https://github.com/user-attachments/assets/40328049-5571-4127-b563-b07ee9f62d82)

Please, ensure that you do not have the direct access to your mouse option selected. Otherwise it will not work
![imagen](https://github.com/user-attachments/assets/d0a4cfbb-06e2-45cf-8d3b-585d65d2f7af)

As you stated before, you will play with your mouse and, eventually, you can use the controller (sticker) to move your view and the buttons to zoom in and zoom out.

Please check if this works for you to close this issue.
Best regards

**Comment by hellomynameisnoone** [comment]
It works!, you can play with mouse + controller (I use a XBOX) paning an clicking is with the mouse and zoom in and out is with the controller

I upload a test video

It should be wise, when this kind of games with "special" input or controller, notify the user how to config it or overide this configuration you mention for this specific game

Thanks!


https://github.com/user-attachments/assets/614866ce-79cd-4f8a-bdf2-94c75206f225
