### ISSUE TITLE
Liege Dragon

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2717]
#### Current on `master` : 1.0.5525

Game crashes on boot every time
```
00:00:06.541 |I| HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x0033d550 nn::os::AllocateMemoryPages(unsigned long, unsigned long)
   sdk:0x002dfde8 nnmem_nlib_physical_alloc
   sdk:0x002e7038 nn::nlibsdk::heap::TlsHeapCentral::AllocPhy_(void*, unsigned long)
   sdk:0x002e7fac nn::nlibsdk::heap::TlsHeapCentral::SplitSpan_(nn::nlibsdk::heap::Span*, unsigned long, nn::nlibsdk::heap::Span*)
   sdk:0x002ec960 nn::nlibsdk::heap::CentralHeap::Alloc(unsigned long, unsigned long)
   sdk:0x002ee1d0 nn::mem::StandardAllocator::Allocate(unsigned long, unsigned long)
   main:0x0111d11c Sub000000000912111c
   main:0x0126e5cc Sub00000000092725cc
   main:0x0111d858 Sub0000000009121858
   main:0x014ab874 Sub00000000094af874
   main:0x00e56600 Sub0000000008e5a600
   main:0x00e5c338 nnMain
   sdk:0x002a3864 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
   rtld:0x000000d4 Sub00000000080000d4


00:00:06.541 |E| HLE.HostThread.0 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000021.
00:00:06.551 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 357
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 229
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
```

#### Log file :

[liege-dragon.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5384921/liege-dragon.log)

**Comment by EmulationFanatic** [comment]
Updated
