### ISSUE TITLE
Prinny Can I Really Be the Hero

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2719]
#### Current on `master` : 1.0.5525

Crashes on launch.

```
Process: Application, PID: 81
   ??? Sub0000000000000000


00:01:19.070 |E| HLE.HostThread.3 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000000251778 (opcode 0xeef70b60) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1109
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 136
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-10-15 20-03-59-899](https://user-images.githubusercontent.com/35269098/96130767-8afbe200-0f22-11eb-800a-201ec19bfd94.jpg)
![bandicam 2020-10-15 20-04-02-097](https://user-images.githubusercontent.com/35269098/96130777-8df6d280-0f22-11eb-811c-390fe84c86a6.jpg)

#### Logs :

[PCIRBH.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5385049/PCIRBH.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6912

**Comment by EmulationFanatic** [comment]
Updated

**Comment by ShadowzI** [comment]
Game can not be saved due to use of web applet
