### ISSUE TITLE
Aokana - Four Rhythms Across the Blue

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2732]
#### Current on `master` : 1.0.5525

Game loaded and played for a few minutes and then crashed during gameplay.

```
HLE.HostThread.27 Application : Unhandled exception caught: System.InvalidOperationException: Decoded a single empty exit block. Entry point = 0x30000000000860BE.
   at ARMeilleure.Decoders.Decoder.Decode(IMemoryManager memory, UInt64 address, ExecutionMode mode, Boolean highCq, Boolean singleBlock) in C:\projects\ryujinx\ARMeilleure\Decoders\Decoder.cs:line 141
   at ARMeilleure.Translation.Translator.Translate(IMemoryManager memory, JumpTable jumpTable, UInt64 address, ExecutionMode mode, Boolean highCq) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 232
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 174
   at ARMeilleure.Instructions.NativeInterface.GetFunctionAddress(UInt64 address) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 229
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-10-15 16_20_51-Ryujinx 1 0 5525 - Aokana - Four Rhythms Across the Blue v1 0 (0100990011866000)](https://user-images.githubusercontent.com/62343878/96192271-eae29080-0f02-11eb-8746-3d7f318b658e.png)
![2020-10-15 16_21_03-Ryujinx 1 0 5525 - Aokana - Four Rhythms Across the Blue v1 0 (0100990011866000)](https://user-images.githubusercontent.com/62343878/96192272-eb7b2700-0f02-11eb-8d7b-45780165ce35.png)
![2020-10-15 16_21_22-Ryujinx 1 0 5525 - Aokana - Four Rhythms Across the Blue v1 0 (0100990011866000)](https://user-images.githubusercontent.com/62343878/96192273-ec13bd80-0f02-11eb-8a45-96ef5277a699.png)
![2020-10-15 16_21_44-Ryujinx 1 0 5525 - Aokana - Four Rhythms Across the Blue v1 0 (0100990011866000)](https://user-images.githubusercontent.com/62343878/96192283-f2099e80-0f02-11eb-9136-e4789b228528.png)
![2020-10-15 16_23_01-Ryujinx 1 0 5525 - Aokana - Four Rhythms Across the Blue v1 0 (0100990011866000)](https://user-images.githubusercontent.com/62343878/96192302-fb930680-0f02-11eb-814a-ba2166e85883.png)
![2020-10-15 16_23_18-Ryujinx 1 0 5525 - Aokana - Four Rhythms Across the Blue v1 0 (0100990011866000)](https://user-images.githubusercontent.com/62343878/96192313-0188e780-0f03-11eb-95dc-431f0beb12b9.png)
![2020-10-15 16_23_25-Ryujinx 1 0 5525 - Aokana - Four Rhythms Across the Blue v1 0 (0100990011866000)](https://user-images.githubusercontent.com/62343878/96192330-09e12280-0f03-11eb-9c54-d81128278233.png)
![2020-10-15 16_23_31-Ryujinx 1 0 5525 - Aokana - Four Rhythms Across the Blue v1 0 (0100990011866000)](https://user-images.githubusercontent.com/62343878/96192333-0a79b900-0f03-11eb-806b-152b89d4f955.png)
![2020-10-15 16_23_47-Ryujinx 1 0 5525 - Aokana - Four Rhythms Across the Blue v1 0 (0100990011866000)](https://user-images.githubusercontent.com/62343878/96192348-12d1f400-0f03-11eb-87e4-da7441225aef.png)

#### Log file :

[AFRAtB.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5388215/AFRAtB.log)

**Comment by EmulationFanatic** [comment]
Updated
