### ISSUE TITLE
MotoGP 20

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2737]
#### Current on `master` : 1.0.5525

Crashes on launch.

```
HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x000c983c nn::os::detail::VammManager::AllocateAddressRegion(unsigned long*, unsigned long)
   sdk:0x000c5d70 nn::os::AllocateAddressRegion(unsigned long*, unsigned long)
   main:0x017cd2b4 Sub00000000097d12b4
   sdk:0x00098570 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())


00:00:06.391 |E| HLE.HostThread.0 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000011C01050.
00:00:06.409 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 357
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 244
   at Ryujinx.Cpu.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 109
   at ARMeilleure.Instructions.NativeInterface.ReadUInt64(UInt64 address) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 181
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[MGP20.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5388301/MGP20.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6807

**Comment by EmulationFanatic** [comment]
Updated
