### ISSUE TITLE
Mario Kart Live: Home Circuit

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#2749]
#### Current on `master` : 1.0.5545

Crashes at launch.

```
00:00:06.735 |E| CommonServer Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Ldn.Lp2p.IServiceCreator: 0

Guest Stack Trace:
Process: Application, PID: 81
   main:0x00145ff0 Sub0000000008149ff0
   main:0x00145384 Sub0000000008149384
   main:0x00141018 Sub0000000008145018
   main:0x00fa2b30 Sub0000000008fa6b30
   sdk:0x002a3864 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
   rtld:0x000000d4 Sub00000000080000d4

Raw Request Data:
00000000   01 00 20 00 01 00 00 00  00 00 00 00 00 00 00 00   ·· ·············
00000010   53 46 43 49 01 00 00 00  00 00 00 00 00 00 00 00   SFCI············
00000020   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000030   00 00 03 00 00 24 00 00  00 A5 00 00 04 00 00 00   ·····$···¥······

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(IpcRequest message) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 86
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\projects\ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[MKLiveHC.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5395896/MKLiveHC.log)

**Comment by RagdolllFan2005** [comment]
this requires a real Mario kart home circuit toy so it will not work on emulators
