### ISSUE TITLE
TT Isle of Man 2

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2758]
#### Current on `master` : 1.0.5549

Crashes during splash screens.

```
NvservicesServer Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 10280 took more than 1000ms, resuming execution...
00:03:00.854 |E| GUI.RenderLoop Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitImageBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 307
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 147
   at Ryujinx.Graphics.Gpu.Image.TextureManager.CommitComputeBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 305
   at Ryujinx.Graphics.Gpu.Engine.Methods.Dispatch(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Compute.cs:line 147
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 351
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-10-21 05_38_32-Ryujinx 1 0 5549 - TT Isle of Man 2 v1 0 0 (010000400F582000) (64-bit)](https://user-images.githubusercontent.com/62343878/96714818-f4835280-135f-11eb-98fe-25a10b9e05cc.png)
![2020-10-21 05_38_52-Ryujinx 1 0 5549 - TT Isle of Man 2 v1 0 0 (010000400F582000) (64-bit)](https://user-images.githubusercontent.com/62343878/96714827-f64d1600-135f-11eb-87b5-7bdb3f9ec99a.png)
![2020-10-21 05_39_15-Ryujinx 1 0 5549 - TT Isle of Man 2 v1 0 0 (010000400F582000) (64-bit)](https://user-images.githubusercontent.com/62343878/96714851-fea55100-135f-11eb-962a-1f8097fda64c.png)

#### Log file :

[TTIoM2.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5415559/TTIoM2.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6913

**Comment by EmulationFanatic** [comment]
Updated
