### ISSUE TITLE
Ori and the Will of the Wisps

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2781]
#### Current on `master` : 1.0.5553

Crashes on launch with a system access violation exception that only showed in the console.

#### Log file :

[OatWotW.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5432988/OatWotW.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6807

**Comment by meisiek** [comment]
Game Update Version : 1.2.0
Current on master : 1.0.6894

Hardware Specs :
CPU: i7-8700
GPU: NVIDIA GTX 1070 Ti
RAM: 32GB

The game starts now and I played through the intro without a crash.

**Comment by ryulovesjinx** [comment]
Sadlly, game do not start at all. Not even with a lot of tries.

Ryujinx version: 1.0.6956

System Specs:
OS: Windows 10
CPU: Ryzen 5 3600
GPU: NVIDIA GTX 670
RAM: 16GB

00:00:10.896 |E| HLE.GuestThread.14 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:10.902 |E| HLE.GuestThread.14 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by d3ce1t** [comment]
Works with Ryujinx 1.0.7000. I coud start a new game :)

**Comment by zero13th** [comment]
Game Update Version : 1.2.0
Build Version : 1.0.7098
OS : Windows 10 20H2

Slow but playable 10-20 fps


Hardware Specs :
CPU : i3-6100
GPU : GT1030 - v.496.49
RAM : 32GB

Screenshot :
![11](https://user-images.githubusercontent.com/3038360/140592521-3181b16c-98b4-40ae-b5ed-aceadb8e34f6.PNG)
![12](https://user-images.githubusercontent.com/3038360/140592537-639c5398-2a5b-43c8-8cab-78f3d28e581d.PNG)
![21](https://user-images.githubusercontent.com/3038360/140592548-52d6db87-e948-48ac-a82d-528c96ffd372.PNG)
![22](https://user-images.githubusercontent.com/3038360/140592559-96ac54d2-a340-4fdf-ba58-081c7a22ecf8.PNG)

**Comment by meisiek** [comment]
The game no longer starts after Ryujinx Version 1.0.7129:
[Ryujinx_1.0.7135_2021-12-24_06-50-38.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7772862/Ryujinx_1.0.7135_2021-12-24_06-50-38.log)

**Comment by gdkchan** [comment]
That is unlike to be a regression. If you look at the previous tests, you can see that it has always crashed randomly when starting, so it probably requires a few tries to work.

**Comment by meisiek** [comment]
I know. But before this version I could start it after several tries. Now this is no longer possible or I am extremely unlucky and had 10 bad tries in a row.

**Comment by meisiek** [comment]
Quick update: I fixed the crash by purging PPTC and the shader cache. Seems something got corrupted on my PC.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by gman-villa** [comment]
anyone can share the complete shaders please?
