### ISSUE TITLE
WWE 2K Battlegrounds

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2782]
#### Current on `master` : 1.0.5553

Crashes in graphically corrupt menus.

```
GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000009EFFB0000.
00:04:08.801 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 451
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 257
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyBuffer(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyBuffer.cs:line 185
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 352
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-10-24 08_07_10-Ryujinx 1 0 5553 - WWE 2K Battlegrounds v1 0 0 1 (010081700EDF4000) (64-bit)](https://user-images.githubusercontent.com/62343878/97083872-724d9500-15d0-11eb-83a0-c0bbb25345a0.png)
![2020-10-24 08_07_25-Ryujinx 1 0 5553 - WWE 2K Battlegrounds v1 0 0 1 (010081700EDF4000) (64-bit)](https://user-images.githubusercontent.com/62343878/97083877-78dc0c80-15d0-11eb-8171-0118bdea5b20.png)
![2020-10-24 08_09_24-Ryujinx 1 0 5553 - WWE 2K Battlegrounds v1 0 0 1 (010081700EDF4000) (64-bit)](https://user-images.githubusercontent.com/62343878/97083888-80031a80-15d0-11eb-9118-83080248e1b4.png)
![2020-10-24 08_09_32-Ryujinx 1 0 5553 - WWE 2K Battlegrounds v1 0 0 1 (010081700EDF4000) (64-bit)](https://user-images.githubusercontent.com/62343878/97083892-84c7ce80-15d0-11eb-82ea-420a89c701ff.png)
![2020-10-24 08_09_40-Ryujinx 1 0 5553 - WWE 2K Battlegrounds v1 0 0 1 (010081700EDF4000) (64-bit)](https://user-images.githubusercontent.com/62343878/97083898-914c2700-15d0-11eb-8b33-d2fc4654ec05.png)
![2020-10-24 08_10_19-](https://user-images.githubusercontent.com/62343878/97083900-9610db00-15d0-11eb-89a0-92102029443a.png)

#### Log file :

[WWE2KB.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5432996/WWE2KB.log)

**Comment by taiwan-king** [comment]
1.0.6045
The arrow keys are not controlled.

**Comment by taiwan-king** [comment]
Game Update Version : 1.0.2.0
Current on master : 1.0.6604

game crash

Hardware Specs :
CPU: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
Operating System: Microsoft Windows 10.0.18363 (X64)
NVIDIA GTX 970
RAM : 16GB

Screenshots :
![1613742866314](https://user-images.githubusercontent.com/24381898/108513131-205a1900-72fd-11eb-9b7a-ec12d33764f1.jpg)

Log:
[Ryujinx_1.0.6604_2021-02-19_21-34-41.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6010406/Ryujinx_1.0.6604_2021-02-19_21-34-41.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
