### ISSUE TITLE
Paradise Killer

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2789]
#### Current on `master` : 1.0.5553

Crashes on launch.

```
GUI.RenderLoop Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.BindOrUpdateBuffers(BuffersPerStage[] bindings, Boolean bind, Boolean isStorage) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 673
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CommitGraphicsBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 636
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 302
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 121
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 149
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 41
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 352
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[PK.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5434604/PK.zip)

**Comment by watson1423** [comment]
try seting the Anisotropic filtering:manualy fixed one of my games with this problem

**Comment by EmulationFanatic** [comment]
@watson1423 AF has no bearing on this crash. Leaving it on auto is always the safest option.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
