### ISSUE TITLE
MX vs ATV All Out

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2790]
#### Current on `master` : 1.0.5553

Crashes in early splash screens.

```
GUI.RenderLoop Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.Shader.Instructions.InstEmit.Ipa(EmitterContext context) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Instructions\InstEmitMemory.cs:line 110
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, ShaderConfig& config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 175
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 19
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateComputeShader(GpuState state, UInt64 gpuVa, Int32 localSizeX, Int32 localSizeY, Int32 localSizeZ, Int32 localMemorySize, Int32 sharedMemorySize) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 315
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetComputeShader(GpuState state, UInt64 gpuVa, Int32 localSizeX, Int32 localSizeY, Int32 localSizeZ, Int32 localMemorySize, Int32 sharedMemorySize) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 74
   at Ryujinx.Graphics.Gpu.Engine.Methods.Dispatch(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Compute.cs:line 34
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 351
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-10-25 05_15_11-Ryujinx 1 0 5553 - MX vs ATV All Out v1 0 1 (0100218011E7E000) (64-bit)](https://user-images.githubusercontent.com/62343878/97105564-64a41800-1681-11eb-8801-df6c763fe650.png)
![2020-10-25 05_15_25-Ryujinx 1 0 5553 - MX vs ATV All Out v1 0 1 (0100218011E7E000) (64-bit)](https://user-images.githubusercontent.com/62343878/97105565-653cae80-1681-11eb-906b-9f16999574c3.png)

#### Log file :

[MXVSATVAO.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5434608/MXVSATVAO.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by ChassyFlaps** [comment]
Ryzen 5 2600 16gb DDR4 RTX 3060 12gb

Was able to get the game to boot twice in Vulkan with no graphical Glitches, low framerate 20 30 but choppy, Will now not boot in either open GL or Vulkan reliably past the loading screen and emulator hard crashes. Unable to provide screenshot. Console throws up a list of gpu buffer related issues
