### ISSUE TITLE
Remothered: Broken Porcelain

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2803]
#### Current on `master` : 1.0.5573

Crashes in early splash screens.

```
GUI.RenderLoop Application : Unhandled exception caught: System.ArgumentException: Invalid variable type "F64".
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.NumberFormatter.TryFormat(Int32 value, VariableType dstType, String& formatted) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\NumberFormatter.cs:line 34
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.TypeConversion.ReinterpretCast(CodeGenContext context, IAstNode node, VariableType srcType, VariableType dstType) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\TypeConversion.cs:line 18
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions.InstGen.GetExpression(CodeGenContext context, AstOperation operation) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\Instructions\InstGen.cs:line 75
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions.InstGen.GetExpression(CodeGenContext context, IAstNode node) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\Instructions\InstGen.cs:line 26
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.TypeConversion.ReinterpretCast(CodeGenContext context, IAstNode node, VariableType srcType, VariableType dstType) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\TypeConversion.cs:line 24
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.PrintBlock(CodeGenContext context, AstBlock block) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 182
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.PrintFunction(CodeGenContext context, StructuredProgramInfo info, StructuredFunction function, String funcName) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 98
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.Generate(StructuredProgramInfo info, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 17
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(FunctionCode[] functions, ShaderConfig config, Int32 sizeA) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 94
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 29
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateGraphicsShader(GpuState state, TranslationFlags flags, ShaderStage stage, UInt64 gpuVa, UInt64 gpuVaA) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 373
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 149
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 984
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 121
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 149
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 41
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 352
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-10-27 11_15_24-Ryujinx 1 0 5573 - Remothered_ Broken Porcelain v0 (0100FBD00F5F6000) (64-bit)](https://user-images.githubusercontent.com/62343878/97337464-f0ff3800-1845-11eb-9e92-a277a97fdce5.png)

#### Log file :

[RBP.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5446920/RBP.zip)

**Comment by EmulationFanatic** [comment]
Updated
