### ISSUE TITLE
Oceanhorn 2 Knights of the Lost Realm

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2807]
#### Current on `master` : 1.0.5573

Crashes on launch in menu.and graphics are broken

```
Process: OH2, PID: 81
   sdk:0x00144a04 Sub000000000dcbaa04
   sdk:0x00144b78 Sub000000000dcbab78
   main:0x006c7078 Sub00000000086cb078
   main:0x006b6e3c Sub00000000086bae3c
   main:0x00664500 Sub0000000008668500
   main:0x00627a18 Sub000000000862ba18
   main:0x00c5c01c Sub0000000008c6001c
   main:0x0000ae04 Sub000000000800ee04
   main:0x0000cc8c Sub0000000008010c8c
   sdk:0x0033e7a8 Sub000000000deb47a8
   sdk:0x00342f74 Sub000000000deb8f74
   ??? Sub0000000000000000

00:07:25.975 |E| HLE.HostThread.3 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1331
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 54
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-10-28 23-52-38-442](https://user-images.githubusercontent.com/35269098/97470692-6bc96f80-197a-11eb-80f6-7279a1738f1f.jpg)
![bandicam 2020-10-28 23-53-57-352](https://user-images.githubusercontent.com/35269098/97470710-71bf5080-197a-11eb-92d9-1e3a89597ea2.jpg)
![bandicam 2020-10-28 23-54-55-065](https://user-images.githubusercontent.com/35269098/97470720-7421aa80-197a-11eb-9f09-fd912b597acf.jpg)
![bandicam 2020-10-28 23-57-33-287](https://user-images.githubusercontent.com/35269098/97470732-771c9b00-197a-11eb-8010-8410718fd738.jpg)

#### Logs :

[O2KOTLR.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5453649/O2KOTLR.log)

**Comment by Doctorwho1909** [comment]
[Ryujinx_2020-11-19_11-53-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5567965/Ryujinx_2020-11-19_11-53-46.log)
no change as of 1.0.5763 log has been added

**Comment by crusaside** [comment]
i second this! really wanna play this. please awesome guys, do something!

**Comment by choppymaster** [comment]
? This is a compatibility list not a request centre

**Comment by EmulationFanatic** [comment]
Updated. Just for @riperiperi

**Comment by chocoblin** [comment]
> Updated. Just for @riperiperi

whoooa! gotta try this out immediately!
