### ISSUE TITLE
No More Heroes 2 Desperate Struggle

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2808]
#### Current on `master` : 1.0.5573

Crashes on launch 

```
Process: Application, PID: 81
   ??? Sub0000000000000000


00:00:20.390 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000006238b8 (opcode 0xf2460cfa) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1109
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 136
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Logs :

[NMH2DS.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5453809/NMH2DS.log)

**Comment by MarkLanders777** [comment]
![nmh2](https://user-images.githubusercontent.com/82430579/190300632-95c29124-02e7-4060-a07c-86550fa0077d.png)
![nmh22](https://user-images.githubusercontent.com/82430579/190300637-375c28fa-0053-494f-948e-cd03170d54cc.png)
![nmh23](https://user-images.githubusercontent.com/82430579/190300639-4bbcb97e-16c5-4cf8-a4e8-1dc38309d81a.png)
It works on Master now

**Comment by EmulationFanatic** [comment]
Updated. Game is now playable

**Comment by Jwayne02** [comment]
There is a crash on version 1.0.0 where the game will crash on Rank 8 after leaving the bathroom.  
[Ryujinx_1.1.362_2022-11-18_19-27-15.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10045765/Ryujinx_1.1.362_2022-11-18_19-27-15.log)
[savedata.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/10045767/savedata.zip)
