### ISSUE TITLE
No More Heroes 

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2809]
#### Current on `master` : 1.0.5573

Crashes on launch 

```
Process: Application, PID: 81


00:00:26.909 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000000717db4 (opcode 0xe6700f91) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1109
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 136
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Outstanding Issues :

https://github.com/Ryujinx/Ryujinx/issues/1602

#### Screenshots :

![bandicam 2020-10-29 00-40-41-048](https://user-images.githubusercontent.com/35269098/97475168-7f2b0980-197f-11eb-97b9-30376453055c.jpg)

#### Logs :

[NMH.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5453869/NMH.log)

**Comment by GamerzHell9137** [comment]
Missing instruction has been merged but the game has still can't go in game. Its black screen too while the audio is running in the background, the error it shows in the log is:

```00:00:03.211 |S| HLE.OsThread.15 ServiceAm InitializeApplicationCopyrightFrameBufferImpl: Stubbed. {transferMemoryAddress: 2066251776 ; transferMemorySize: 3932160 ; width: 1280 ; height: 720}
00:00:03.326 |S| HLE.OsThread.15 ServiceAm SetApplicationCopyrightImageImpl: Stubbed. {x: 256 ; y: 656 ; width: 1024 ; height: 64 ; frameBufferPos: 99857989632 ; frameBufferSize: 262144 ; windowOriginMode: 1}
00:00:03.326 |S| HLE.OsThread.15 ServiceAm SetApplicationCopyrightImage: Stubbed. {frameBufferPos: 99857989632 ; frameBufferSize: 262144 ; x: 256 ; y: 656 ; width: 1024 ; height: 64 ; windowOriginMode: 1}
00:00:03.327 |S| HLE.OsThread.15 ServiceAm SetApplicationCopyrightVisibility: Stubbed. {visible: True}
00:00:03.464 |I| HLE.GuestThread.14 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 91
   0x00000000002000a0	rtld:0x00a0	


00:00:03.466 |I| HLE.GuestThread.14 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000000000000000
	X[02]:	0x000000000000000f
	X[03]:	0x0000000000320358 (main:0x11c358)	=> 
	X[04]:	0x00000000401477d8
	X[05]:	0x0000000000000000
	X[06]:	0x000000000000000f
	X[07]:	0x00000000401477d4
	X[08]:	0x0000000000000000
	X[09]:	0x0000000000000000
	X[10]:	0x0000000000000000
	X[11]:	0x0000000032541ff8 (SP:-0x32541ff8)
	X[12]:	0x00000000003cb740
	X[13]:	0x0000000032541f50 (SP:-0x32541f50)
	X[14]:	0x00000000003203a8 (main:0x11c3a8)	=> 
	X[15]:	0x0000000000000000
	X[16]:	0x0000000000000000
	X[17]:	0x0000000000000000
	X[18]:	0x0000000000000000
	X[19]:	0x0000000000000000
	X[20]:	0x0000000000000000
	X[21]:	0x0000000000000000
	X[22]:	0x0000000000000000
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000000
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x0000000000000000
	LR:	0x0000000000000000
	SP:	0x0000000000000000
	PC:	0x0000000000000000


00:00:03.469 |E| HLE.GuestThread.14 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000003357f4 (opcode 0xe320f004) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e)
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

264 build and on a RTX 3060 Ti/Ryzen 3600

**Comment by merryhime** [comment]
^ #3694

**Comment by GamerzHell9137** [comment]
There's been an error with the things above posted, the log has been changed to the correct one.

Another thing tho about it, if the memory mode is changed to software and the PPTC deleted (the whole folder) and the game relaunched with those settings, the game wouldn't crash immediately but it would get stuck at the same place for 20 secs longer and show this in the end:

```
00:00:50.051 |E| HLE.GuestThread.15 Application : Unhandled exception caught: System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Text.StringBuilder.ExpandByABlock(Int32 )
   at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
   at System.Text.StringBuilder.Append(String value)
   at Ryujinx.HLE.HOS.Kernel.Process.HleProcessDebugger.<GetGuestStackTrace>g__AppendTrace|6_0(UInt64 address, <>c__DisplayClass6_0& ) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\HleProcessDebugger.cs:line 66
   at Ryujinx.HLE.HOS.Kernel.Process.HleProcessDebugger.GetGuestStackTrace(KThread thread) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\HleProcessDebugger.cs:line 81
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.GetGuestStackTrace() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1214
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.PrintGuestStackTrace() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1224
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.InvalidAccessHandler(UInt64 va) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1092
   at Ryujinx.Cpu.Jit.MemoryManager.Write[T](UInt64 va, T value) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\MemoryManager.cs:line 156
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 124
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
```

**Comment by GamerzHell9137** [comment]
## No More Heroes
#### Game Update Version : *v1.0.1*

#### Current on `master` : *1.1.267*

Game plays and runs perfect with no issues.
## Hardware Specs : 

OS: *Windows 10*
CPU: *Amd Ryzen 3600*
GPU: *NVIDIA RTX 3060 Ti*
RAM: *16GB*


## Screenshots : 

![image](https://user-images.githubusercontent.com/2002038/189840255-8d0c13f4-a02c-4ce8-ae94-d27fddd52213.png)
![image](https://user-images.githubusercontent.com/2002038/189840613-2aa28067-4cea-4783-b290-eb7d7856268e.png)

**Comment by MetrosexualGarbodor** [comment]
Updated, thank you 👍
