### ISSUE TITLE
Pixel Puzzle Makeout League

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2811]
#### Current on `master` : 1.0.5584

Crashes on launch 

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.TranslatedFunction.Execute(ARMeilleure.State.ExecutionContext)
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.Cpu.CpuContext.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass136_0.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-10-31 05-13-05-837](https://user-images.githubusercontent.com/35269098/97761295-ea1f4080-1b37-11eb-8198-84de31f44493.jpg)

#### Logs :

[PPML.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5467896/PPML.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6807

**Comment by EmulationFanatic** [comment]
Updated
