### ISSUE TITLE
The Language of Love

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2815]
#### Current on `master` : 1.0.5584

Crashes on launch 

```
Process: Lang Of Love, PID: 81
   sdk:0x000559c0 Sub0000000009a839c0
   sdk:0x00055a88 Sub0000000009a83a88
   sdk:0x00055b20 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   main:0x0065c0fc Sub00000000086600fc
   main:0x0065afe0 Sub000000000865efe0
   main:0x0065d8c0 Sub00000000086618c0
   sdk:0x000d06f8 Sub0000000009afe6f8
   sdk:0x000d4ec4 Sub0000000009b02ec4
   ??? Sub0000000000000000


00:00:04.664 |W| HLE.HostThread.0 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:00:04.664 |W| HLE.HostThread.2 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:00:04.686 |E| HLE.HostThread.3 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1331
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 47
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 131
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 53
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-10-31 21-48-45-046](https://user-images.githubusercontent.com/35269098/97782294-4a0ef900-1bc3-11eb-8a5c-916285dd2fd7.jpg)

#### Logs :

[TLOL.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5469270/TLOL.log)

**Comment by EmulationFanatic** [comment]
@Cronos-0 please update when you have the chance. Thanks!

**Comment by Cronos-0** [comment]
Update, now playable Ov-
