### ISSUE TITLE
Seven Knights -Time Wanderer-

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2824]
#### Current on `master` : 1.0.5611

Crashes on launch 

```
Process: Application, PID: 81
   sdk:0x00144a04 Sub0000000051747a04
   sdk:0x00144b44 Sub0000000051747b44
   sdk:0x00145a64 Sub0000000051748a64
   sdk:0x0055bbdc Sub0000000051b5ebdc
   sdk:0x0051789c Sub0000000051b1a89c
   main:0x00791f0c Sub0000000008795f0c
   main:0x007901bc Sub00000000087941bc
   main:0x008071cc Sub000000000880b1cc
   main:0x008075fc Sub000000000880b5fc
   sdk:0x004e41d0 std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*))
   main:0x0082748c Sub000000000882b48c
   main:0x00000154 Sub0000000008004154
   rtld:0x00000864 Sub0000000008000864
   sdk:0x002a3750 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
   rtld:0x000000d4 Sub00000000080000d4


00:00:11.231 |W| HLE.HostThread.2 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:00:11.753 |E| HLE.HostThread.0 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1331
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 47
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 131
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 53
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 28
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-11-06 01-12-28-913](https://user-images.githubusercontent.com/35269098/98280236-b035ba80-1fcd-11eb-8d67-92a54641c4ba.jpg)

#### Logs :

[SKTW.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5496177/SKTW.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6913

**Comment by EmulationFanatic** [comment]
Updated
