### ISSUE TITLE
Kangokuto Mary Skelter Finale

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2825]
#### Current on `master` : 1.0.5611

The game crashes after playing for a while and the sound in the video is bad, including the character's voice. When speaking, the voice will twitch from time to time. 

```
00:05:12.691 |E| HLE.HostThread.0 Application : Unhandled exception caught: System.InvalidOperationException: Decoded a single empty exit block. Entry point = 0x1868E57800000000.
   at ARMeilleure.Decoders.Decoder.Decode(IMemoryManager memory, UInt64 address, ExecutionMode mode, Boolean highCq, Boolean singleBlock) in C:\projects\ryujinx\ARMeilleure\Decoders\Decoder.cs:line 141
   at ARMeilleure.Translation.Translator.Translate(IMemoryManager memory, JumpTable jumpTable, UInt64 address, ExecutionMode mode, Boolean highCq) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 232
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 174
   at ARMeilleure.Instructions.NativeInterface.GetFunctionAddress(UInt64 address) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 229
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 122
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1150
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-11-06 01-28-20-883](https://user-images.githubusercontent.com/35269098/98282153-5be00a00-1fd0-11eb-8961-339df16ecfd1.jpg)
![bandicam 2020-11-06 01-28-42-459](https://user-images.githubusercontent.com/35269098/98282165-600c2780-1fd0-11eb-864d-d6b93643c1a1.jpg)
![bandicam 2020-11-06 01-30-37-495](https://user-images.githubusercontent.com/35269098/98282179-67333580-1fd0-11eb-8aa5-8d53e10b6249.jpg)
![bandicam 2020-11-06 01-30-43-942](https://user-images.githubusercontent.com/35269098/98282187-6a2e2600-1fd0-11eb-9c91-6cb7fa3a90d4.jpg)
![bandicam 2020-11-06 01-31-12-197](https://user-images.githubusercontent.com/35269098/98282193-6ef2da00-1fd0-11eb-920a-25d27f57bf4f.jpg)
![bandicam 2020-11-06 01-31-20-276](https://user-images.githubusercontent.com/35269098/98282204-73b78e00-1fd0-11eb-801f-086a5817d92a.jpg)
![bandicam 2020-11-06 01-31-37-607](https://user-images.githubusercontent.com/35269098/98282212-79ad6f00-1fd0-11eb-96cd-d0b04451aeff.jpg)

#### Logs :

[KMSF.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5496259/KMSF.log)

**Comment by Cronos-0** [comment]
Update now the game no longer crashes.
