### ISSUE TITLE
Jurassic World Evolution Complete Edition

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2828]
#### Current on `master` : 1.0.5636

The game crashes at the start of the first campaign, and the footage in the video jumps at intervals. But the sound plays well normally

```
00:05:22.526 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 451
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 257
   at Ryujinx.Graphics.Gpu.Memory.Buffer.<SynchronizeMemory>b__20_0(UInt64 mAddress, UInt64 mSize) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 126
   at Ryujinx.Graphics.Gpu.Memory.Buffer.SynchronizeMemory(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 137
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CreateBufferAligned(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 413
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.TranslateAndCreateBuffer(UInt64 gpuVa, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 350
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CopyBuffer(GpuVa srcVa, GpuVa dstVa, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 786
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyBuffer(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyBuffer.cs:line 138
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 352
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-11-07 22-00-01-942](https://user-images.githubusercontent.com/35269098/98444696-af279900-2145-11eb-83c0-e548fcf09a72.jpg)
![bandicam 2020-11-07 22-00-14-846](https://user-images.githubusercontent.com/35269098/98444699-b2228980-2145-11eb-8a62-518ee1ec6f4c.jpg)
![bandicam 2020-11-07 22-00-35-408](https://user-images.githubusercontent.com/35269098/98444700-b484e380-2145-11eb-9de5-270651d5d5ee.jpg)
![bandicam 2020-11-07 22-00-44-749](https://user-images.githubusercontent.com/35269098/98444703-b8b10100-2145-11eb-953b-dd45a0db2527.jpg)
![bandicam 2020-11-07 22-00-50-060](https://user-images.githubusercontent.com/35269098/98444706-bb135b00-2145-11eb-9328-f9be75a87a17.jpg)
![bandicam 2020-11-07 22-00-56-202](https://user-images.githubusercontent.com/35269098/98444707-be0e4b80-2145-11eb-84f9-f440131bd2f9.jpg)
![bandicam 2020-11-07 22-02-12-440](https://user-images.githubusercontent.com/35269098/98444709-bfd80f00-2145-11eb-8482-3b602650f782.jpg)

#### Logs :

[JWECE.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5504951/JWECE.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6895

**Comment by benderscruffy** [comment]
using 1.0.7108
still crashes out but now with a new error (missing opcode)
00:07:45.642 |E| HLE.GuestThread.14 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000971b36c (opcode 0x7e30f842) is undefined!
[Ryujinx_1.0.7108_2021-11-26_19-51-17.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7608598/Ryujinx_1.0.7108_2021-11-26_19-51-17.log)
)

**Comment by B00MST3R** [comment]
Same issue here, it crashes when loading up the first campaign, would love to have this fixed :-)

**Comment by LDj3SNuD** [comment]
Could you please update Ryujinx, retest the game and close the issue? @Cronos-0 Thanks

**Comment by LDj3SNuD** [comment]
I remember experiencing that crash myself (evidently originating from `MacroHLE.MultiDrawElementsIndirectCount`); I did not try to disable EnableMacroHLE because I could not reproduce the crash afterwards, only trying to go ingame via a campaign.
