### ISSUE TITLE
Shin Megami Tensei III NOCTURNE HD REMASTER

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2830]
#### Current on `master` : 1.0.5636

The game plays smoothly. Slightly flickering graphics Most of the games will be slow, maybe at my CPU.

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-11-07 23-07-59-380](https://user-images.githubusercontent.com/35269098/98447345-cae76b00-2156-11eb-9354-89dbfd7b9b98.jpg)
![bandicam 2020-11-07 23-08-38-756](https://user-images.githubusercontent.com/35269098/98447348-ce7af200-2156-11eb-9b9f-fb08072f7107.jpg)
![bandicam 2020-11-07 23-08-58-840](https://user-images.githubusercontent.com/35269098/98447350-cfac1f00-2156-11eb-9499-889f820a9f10.jpg)
![bandicam 2020-11-07 23-13-29-409](https://user-images.githubusercontent.com/35269098/98447352-d3d83c80-2156-11eb-9c64-371d77fc5f77.jpg)
![bandicam 2020-11-07 23-14-18-287](https://user-images.githubusercontent.com/35269098/98447353-d76bc380-2156-11eb-98da-fa6b6c4ef949.jpg)
![bandicam 2020-11-07 23-17-51-103](https://user-images.githubusercontent.com/35269098/98447356-d9ce1d80-2156-11eb-89f7-e58253b2a9e4.jpg)
![bandicam 2020-11-07 23-23-42-501](https://user-images.githubusercontent.com/35269098/98447358-dcc90e00-2156-11eb-9d2a-88de31e8f2b6.jpg)
![bandicam 2020-11-07 23-24-36-886](https://user-images.githubusercontent.com/35269098/98447361-e0f52b80-2156-11eb-941b-883527a0fcf8.jpg)
![bandicam 2020-11-07 23-28-39-268](https://user-images.githubusercontent.com/35269098/98447362-e3f01c00-2156-11eb-968d-8e8072dfdaee.jpg)
![bandicam 2020-11-07 23-37-52-164](https://user-images.githubusercontent.com/35269098/98447364-ebafc080-2156-11eb-8485-701c6fc68711.jpg)
![bandicam 2020-11-07 23-40-26-008](https://user-images.githubusercontent.com/35269098/98447366-efdbde00-2156-11eb-851b-e08524297a48.jpg)
![bandicam 2020-11-07 23-41-30-680](https://user-images.githubusercontent.com/35269098/98447367-f10d0b00-2156-11eb-896a-6acd5f0f845f.jpg)
![bandicam 2020-11-07 23-46-25-854](https://user-images.githubusercontent.com/35269098/98447369-f407fb80-2156-11eb-8624-0803a1f50674.jpg)
![bandicam 2020-11-07 23-48-06-256](https://user-images.githubusercontent.com/35269098/98447371-f8341900-2156-11eb-871e-7200b2a28748.jpg)
![bandicam 2020-11-07 23-50-24-048](https://user-images.githubusercontent.com/35269098/98447377-ff5b2700-2156-11eb-8d84-c76b92e033d6.jpg)
![bandicam 2020-11-07 23-51-03-216](https://user-images.githubusercontent.com/35269098/98447381-02561780-2157-11eb-810b-cf70af3afa9f.jpg)
![bandicam 2020-11-07 23-52-40-237](https://user-images.githubusercontent.com/35269098/98447386-097d2580-2157-11eb-80e4-9f19eb8b545a.jpg)
![bandicam 2020-11-07 23-53-47-380](https://user-images.githubusercontent.com/35269098/98447388-0bdf7f80-2157-11eb-8b7e-8b6c51a48769.jpg)
![bandicam 2020-11-07 23-58-48-198](https://user-images.githubusercontent.com/35269098/98447392-139f2400-2157-11eb-9a19-cf143bbcba5d.jpg)
![bandicam 2020-11-07 23-59-02-375](https://user-images.githubusercontent.com/35269098/98447394-17cb4180-2157-11eb-8f67-dea33a10fb71.jpg)
![bandicam 2020-11-07 23-59-08-592](https://user-images.githubusercontent.com/35269098/98447396-18fc6e80-2157-11eb-8e80-0cca93f36b1b.jpg)
![bandicam 2020-11-08 00-00-10-140](https://user-images.githubusercontent.com/35269098/98447397-1a2d9b80-2157-11eb-8c7f-a89669f2edb8.jpg)
![bandicam 2020-11-08 00-00-33-105](https://user-images.githubusercontent.com/35269098/98447399-1bf75f00-2157-11eb-8c4c-16b1f5e1738c.jpg)
![bandicam 2020-11-08 00-01-11-816](https://user-images.githubusercontent.com/35269098/98447405-2154a980-2157-11eb-9812-8a76154f4de8.jpg)
![bandicam 2020-11-08 00-02-28-725](https://user-images.githubusercontent.com/35269098/98447407-23b70380-2157-11eb-9617-d8388b0b34a4.jpg)
![bandicam 2020-11-08 00-04-02-870](https://user-images.githubusercontent.com/35269098/98447409-26195d80-2157-11eb-901f-e0958d1da032.jpg)

**Comment by cupelix1** [comment]
Game Works Great on 1.0.6096 80 FPS with VSYNC off and 30 with it on inside emulator.

**Comment by DAlphega** [comment]
![unknown](https://user-images.githubusercontent.com/109500830/179449492-a9ae392c-33dc-4f18-b912-e24dd72883b2.png)
For some reason, cant see the demon preview in The Cathedral of Shadows from Shibuya, has this happened before?

**Comment by kendofriendo** [comment]
Won't launch.

```
00:00:03.828 |E| HLE.OsThread.8 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
   at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.Tools.FsSystem.CachedStorage.ReadBlock(CacheBlock block, Int64 index)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 )
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.FsSrv.Impl.StorageInterfaceAdapter.Read(Int64 offset, OutBuffer destination, Int64 size)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\Games\RyuWork\Ryujinx\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 36
   --- End of inner exception stack trace ---
```

**Comment by EmulationFanatic** [comment]
> Won't launch.
> 
> ```
> 00:00:03.828 |E| HLE.OsThread.8 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
>    at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)
>    at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
>    at LibHac.Tools.FsSystem.CachedStorage.ReadBlock(CacheBlock block, Int64 index)
>    at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
>    at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
>    at LibHac.Tools.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.Stream.Read(Span`1 )
>    at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
>    at LibHac.FsSrv.Impl.StorageInterfaceAdapter.Read(Int64 offset, OutBuffer destination, Int64 size)
>    at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\Games\RyuWork\Ryujinx\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 36
>    --- End of inner exception stack trace ---
> ```

This is a bad dump. You will need to dump the game again.

**Comment by EmulationFanatic** [comment]
Needs update
