### ISSUE TITLE
FUSER

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2832]
#### Current on `master` : 1.0.5659

Crashes on launch 

```
00:07:24.608 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 451
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 257
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 631
   at Ryujinx.Graphics.Gpu.Image.Texture.InitializeData(Boolean isView, Boolean withData) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 217
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureInfo info, TextureSearchFlags flags, Nullable`1 sizeHint) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 826
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 35
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 285
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 243
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 304
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 123
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 149
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 41
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 352
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-11-11 16-44-08-375](https://user-images.githubusercontent.com/35269098/98864053-e1196200-249b-11eb-8b5c-c4c336c94079.jpg)
![bandicam 2020-11-11 16-43-51-404](https://user-images.githubusercontent.com/35269098/98864058-e4145280-249b-11eb-8428-0b855ba95573.jpg)
![bandicam 2020-11-11 16-44-01-687](https://user-images.githubusercontent.com/35269098/98864064-e5de1600-249b-11eb-88b1-60e344abb497.jpg)

#### Logs :

[F.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5526739/F.log)

**Comment by Mou-Ikkai** [comment]
![image](https://user-images.githubusercontent.com/45863583/125205146-d8f20c00-e24e-11eb-8811-df3a8848eee6.png)
![image](https://user-images.githubusercontent.com/45863583/125205559-da243880-e250-11eb-9631-66531408cbab.png)
Graphics are broken/audio is a bit stuttery/static, plus images/textures seem to sometimes break and become beige. But gameplay/dropping discs seems to be no problem, a minor audio static for a second, then the audio plays normally. Also, there's a pause of silence for a few seconds when loading audio. (Discovered this from cutscenes.) **_Can someone test for Nvidia GPUs?_** 
One last thing: Starting the game takes a moment! If it's on a black screen, just wait. It might take a minute, but it loads!

CPU: Ryzen 9 3900x
GPU: 5700XT
RAM: 32GB

Game Version: 1.1.0
Ryujinx Version: 1.0.6959
[FUSER.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6797413/Ryujinx_1.0.6959_2021-07-11_13-46-18.log)

**Comment by Mou-Ikkai** [comment]
![image](https://user-images.githubusercontent.com/45863583/125206674-7e5cae00-e256-11eb-8d9f-de6da315fde4.png)
Newer version, same issue of random beige textures. The disc-board (bottom of screen) also randomly flickers, or the song names will stretch far away from the disc-board. Once again: _**Can someone test for Nvidia GPUs?**_

CPU: Ryzen 9 3900x
GPU: 5700XT
RAM: 32GB

Game Version: 1.4.0
Ryujinx Version: 1.0.6959

**Comment by EmulationFanatic** [comment]
Updated
