### ISSUE TITLE
Medarot Classics Plus Kabuto Ver

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#2837]
#### Current on `master` : 1.0.5659

The game crashes after choosing to play a specific game. I tried selecting all of them, got the same error.

```
00:01:48.266 |E| AudioOutServer Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Audio.AudioOutManager.IAudioOut: 10

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x001579dc nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 0l> >, 0ul, 8ul, false>, std::__1::tuple<nn::sf::cmif::detail::OutRawArgumentInfo<8ul, 8ul, 0l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::OutRawClientArgumentType<8ul, 8ul>, unsigned int)
   sdk:0x001578d4 Sub000000000c2d78d4
   sdk:0x0015cb40 nn::audio::GetAudioOutPlayedSampleCount(nn::audio::AudioOut const*)
   main:0x0190c8d0 Sub00000000099108d0
   main:0x018aae30 Sub00000000098aee30
   main:0x018aac2c Sub00000000098aec2c
   main:0x018f76c8 Sub00000000098fb6c8
   main:0x018dff2c Sub00000000098e3f2c
   main:0x018fd520 Sub0000000009901520
   main:0x019097ec Sub000000000990d7ec
   main:0x018ad1dc Sub00000000098b11dc
   sdk:0x000d06f8 Sub000000000c2506f8
   sdk:0x000d4ec4 Sub000000000c254ec4
   ??? Sub0000000000000000

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0A 00 00 00 00 00 00 00   SFCI············
00000010   00 00 00 00 00 00 00 00  07 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(IpcRequest message) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 138
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\projects\ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()


```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-11-14 23-16-35-118](https://user-images.githubusercontent.com/35269098/99151771-f545a500-26cf-11eb-9565-2c0af7572f1e.jpg)
![bandicam 2020-11-14 23-16-45-513](https://user-images.githubusercontent.com/35269098/99151774-f8409580-26cf-11eb-8fc0-5fa38e89a617.jpg)
![bandicam 2020-11-14 23-16-58-230](https://user-images.githubusercontent.com/35269098/99151775-fa0a5900-26cf-11eb-89ad-6d0b93ef55a2.jpg)

#### Logs :

[MCPKV.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5541083/MCPKV.log)

**Comment by Cronos-0** [comment]
Update now playable

**Comment by SeraUQ** [comment]
Updated
