### ISSUE TITLE
Fantasy Tavern Sextet -Vol.1 New World Days-

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#2840]
#### Current on `master` : 1.0.5667

Goes ingame, but the game crashes soon after that and there are graphical issue, like a line at the botton of the screen with messed up textures that sometimes appears and the buttons for save/load,etc are not rendered at all or only half rendered

```
00:05:34.746 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 257
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyBuffer(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyBuffer.cs:line 91
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 352
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
#### Screenshots :

![20:25:14-11_14_20](https://user-images.githubusercontent.com/62521228/99155470-72652000-26b8-11eb-8548-067e22649be7.png)
![20:26:14-11_14_20](https://user-images.githubusercontent.com/62521228/99155471-73964d00-26b8-11eb-819f-f872ab608009.png)
![20:27:36-11_14_20](https://user-images.githubusercontent.com/62521228/99155474-77c26a80-26b8-11eb-9b9a-3fe6d96c6790.png)
![20:28:39-11_14_20](https://user-images.githubusercontent.com/62521228/99155475-785b0100-26b8-11eb-85c9-3f22cbcd1253.png)

#### Log file :

[FTSV1.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5541350/FTSV1.log)

**Comment by EmulationFanatic** [comment]
Updated
