### ISSUE TITLE
DOOM 64

### ISSUE THREAD

**Issue by Seker-0** [Ryujinx/Ryujinx-Games-List#285]
#### Current on `master` : 1.0.3936

This game needs controller applet. to be able to play

 ```
System.NotImplementedException: Controller applet is not implemented
 ```
#### Log file : 
[Ryujinx_2563-03-20_20-14-34.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4359740/Ryujinx_2563-03-20_20-14-34.log)

#### Outstanding Issues:
- https://github.com/Ryujinx/Ryujinx/issues/648

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## DOOM 64

#### Current on `master` : 1.0.4142

Hangs  on launch with the below error.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: android.gui.IGraphicBufferProducer 2
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.NvFlinger.ProcessParcelRequest(ServiceCtx context, Byte[] parcelData, Int32 code) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\NvFlinger.cs:line 88
   at Ryujinx.HLE.HOS.Services.Vi.RootService.ApplicationDisplayService.IHOSBinderDriver.TransactParcelAuto(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Vi\RootService\ApplicationDisplayService\IHOSBinderDriver.cs:line 83
```
#### Outstanding Issues : 

https://github.com/Ryujinx/Ryujinx/issues/716


#### Log file :

[DOOM64.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4431251/DOOM64.zip)

**Comment by Seker-0** [comment]
#### Pull requests needed :
- https://github.com/Ryujinx/Ryujinx/pull/981

**Comment by B3astTech** [comment]
Updated

**Comment by GoffyDude** [comment]
Needs update

**Comment by SeraUX** [comment]
## DOOM 64

#### Current on `master` : 1.0.4682

Game crashes before getting to the main menu.

```
00:04:00.349 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Error applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Applets\AppletManager.cs:line 32
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\SystemAppletProxy\ILibraryAppletCreator.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Error applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Applets\AppletManager.cs:line 32
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\SystemAppletProxy\ILibraryAppletCreator.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Log file :

[doom64.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4745401/doom64.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
