### ISSUE TITLE
Torchlight III

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2870]
#### Current on `master` : 1.0.5816

Crashes on launch.

```
GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000009C3F4E000.
00:01:21.203 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 451
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 257
   at Ryujinx.Graphics.Gpu.Memory.Buffer.<SynchronizeMemory>b__20_0(UInt64 mAddress, UInt64 mSize) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 125
   at Ryujinx.Graphics.Gpu.Memory.Buffer.SynchronizeMemory(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 137
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CreateBufferAligned(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 446
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.TranslateAndCreateBuffer(UInt64 gpuVa, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 411
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferBind(GpuState state, Int32 argument, ShaderType type) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferBind.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferBindFragment(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferBind.cs:line 54
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.HLE.Switch.ProcessFrame() in C:\projects\ryujinx\Ryujinx.HLE\Switch.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 370
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[TIII.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5602976/TIII.log)

**Comment by EmulationFanatic** [comment]
Updated
