### ISSUE TITLE
Picross S5

### ISSUE THREAD

**Issue by ekfacile** [Ryujinx/Ryujinx-Games-List#2873]
#### Current on `master` : **1.0.5828**

Playable. However, after a certain amount of time (a few minutes to 10 minutes), it crashes randomly.

```
00:03:23.226 |E| HLE.HostThread.5 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1327
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 54
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 127
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1148
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass136_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 172
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Screenshots :

![1](https://user-images.githubusercontent.com/62389564/100403213-9c97e400-30a1-11eb-8d59-02f7503df1f4.jpg)
![2](https://user-images.githubusercontent.com/62389564/100403217-a0c40180-30a1-11eb-9931-d46aec6e3a1e.jpg)
![3](https://user-images.githubusercontent.com/62389564/100403221-a3bef200-30a1-11eb-9c3c-25ae1fc25dd3.jpg)
![4](https://user-images.githubusercontent.com/62389564/100403222-a7527900-30a1-11eb-8103-1ac57e1e4a48.jpg)

#### Log file :

[Picross_S5.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5605618/Picross_S5.log)

**Comment by vojo915** [comment]
**Game Update Version :** 1.0.1  
**Current on `master` :** 1.0.6974

**CPU :** Ryzen 5 3600  
**GPU :** NVIDIA GeForce GTX 1660 Ti
**RAM :** 16GB

The probability of crashing is greatly increased.

If it is early, it will crash in about 2 minutes at the latest immediately after pressing the button on the title screen.

The same result can be obtained by enabling **Expand DRAM size to 6GB** or **Ignore Missing Services** both.

If it is **1.0.6915**, it will not crash as far as I can confirm.

**Log File :**

[Ryujinx_1.0.6974_0100AC30133EC000.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6864221/Ryujinx_1.0.6974_0100AC30133EC000.log)

**Comment by vojo915** [comment]
`Host unchecked` setting stabilizes the operation and no longer crashes.

**Comment by LukeWarnut** [comment]
## Picross S5

#### Game Update Version : 1.3.0

#### Current on `master` : 1.1.307

#### Graphics Backend : OpenGL & Vulkan

Played for around 50 minutes. The game played at full speed with no issues.

#### Hardware Specs : 

##### CPU: Intel i7-11600H
##### GPU: NVIDIA RTX 3050 Ti
##### RAM: 32GB

#### Screenshots :

![image](https://user-images.githubusercontent.com/65521430/196253099-2db6fdcc-4d89-41bc-b202-884637308112.png)
![image](https://user-images.githubusercontent.com/65521430/196253780-d074ddd9-23ea-43df-81af-6f50067d70af.png)
![image](https://user-images.githubusercontent.com/65521430/196256569-c3013fda-9971-47f8-af7e-2929219a7a79.png)![image](https://user-images.githubusercontent.com/65521430/196253419-d2646ef6-9c18-4d5c-ba15-7df8c6462dd2.png)
![image](https://user-images.githubusercontent.com/65521430/196254267-ada9f3aa-885d-43b3-ada1-c5f068e7c615.png)
![image](https://user-images.githubusercontent.com/65521430/196254716-a970dade-18c4-46e3-8403-3a518ac35f51.png)

#### Log file :

[PicrossS5.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9803561/PicrossS5.log)
[PicrossS5-Vulkan.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9803637/PicrossS5-Vulkan.log)

**Comment by MetrosexualGarbodor** [comment]
Updated, thanks!
