### ISSUE TITLE
Worm Jazz

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2874]
#### Current on `master` : 1.0.5816

Crashes a moment after pressing A at the graphically corrupt title screen.

```
GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000009F6EB0000.
00:01:37.021 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 451
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 257
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 582
   at Ryujinx.Graphics.Gpu.Image.Texture.InitializeData(Boolean isView, Boolean withData) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 217
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureInfo info, TextureSearchFlags flags, Nullable`1 sizeHint) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 831
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 35
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 285
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 242
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 304
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 123
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 149
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 41
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 370
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-11-27 06_15_03-Ryujinx 1 0 5816 - Worm Jazz v1 4 1 (01009CD012CC0000) (64-bit)](https://user-images.githubusercontent.com/62343878/100453383-0dc2a180-3078-11eb-98b0-14342e3ae44d.png)
![2020-11-27 06_15_22-Ryujinx 1 0 5816 - Worm Jazz v1 4 1 (01009CD012CC0000) (64-bit)](https://user-images.githubusercontent.com/62343878/100453385-0e5b3800-3078-11eb-9f1d-c6e6ecf4eb15.png)

#### Log file :

[WJ.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5607982/WJ.log)

**Comment by benderscruffy** [comment]
using 1.0.7098
regression
missing all graphics now
![ryujinx_capture_2021-11-06_17-29-12](https://user-images.githubusercontent.com/2696404/140604976-fd264558-101e-4d91-b837-9f55d8c45272.png)
![ryujinx_capture_2021-11-06_17-29-22](https://user-images.githubusercontent.com/2696404/140604978-2ba8a7c5-d22c-45fc-9d78-66b1640e1bdc.png)

**Comment by benderscruffy** [comment]
using 1.0.7101
goes ingame  
no problem with the controls
![ryujinx_capture_2021-11-09_16-48-58](https://user-images.githubusercontent.com/2696404/140892758-ede00a6d-f85e-45a3-94bd-0b211a092b66.png)
![ryujinx_capture_2021-11-09_16-49-08](https://user-images.githubusercontent.com/2696404/140892788-4394324d-5520-4960-9338-9f7d4fcbdb31.png)
![ryujinx_capture_2021-11-09_16-49-22](https://user-images.githubusercontent.com/2696404/140892811-5b665184-718a-4797-9228-a9b4e8e9aa85.png)
![ryujinx_capture_2021-11-09_16-49-30](https://user-images.githubusercontent.com/2696404/140892884-33ffe330-7a96-4239-bee7-4aee355006d7.png)

**Comment by benderscruffy** [comment]
can remove GPU and services and regression labels
