### ISSUE TITLE
Astebreed

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#288]
#### Current on `master` : 1.0.3937

Game crashes on launch.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'position')
   at ARMeilleure.Memory.MemoryManager.WriteBytes(Int64 position, Byte[] data) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 676
   at Ryujinx.Graphics.Gpu.Engine.Methods.FinishTransfer() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 79
   at Ryujinx.Graphics.Gpu.Engine.Methods.LoadInlineData(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 66
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 84
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, GpuState shadowState, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 511
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 185
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 103
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CachedMacro.Execute(Int32[] mme, ShadowRamControl shadowCtrl, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 73
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 236
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 212
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 158
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 329
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[Astebreed.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4361482/Astebreed.zip)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6807

**Comment by EmulationFanatic** [comment]
Updated
