### ISSUE TITLE
Doukoku Soshite... - 01007F000EB36000

### ISSUE THREAD

**Issue by ekfacile** [Ryujinx/Ryujinx-Games-List#2901]
#### Current on `master` : **1.0.5931**

Hangs forever on launch.

```
00:00:01.134 |E| Loader LoadNsos: Process initialization returned error "InvalidMemRange".
```

#### Log file :

[doukoku_soshite.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5635965/doukoku_soshite.log)

**Comment by ekfacile** [comment]
**Current on `master` : 1.0.6028** 

Boot success. However, the title movie fails to play and crashes.

```
00:01:12.124 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:01:12.143 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 535
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 gpuVa, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 94
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 18
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

![crop_1](https://user-images.githubusercontent.com/62389564/101932189-c44c8780-3c1d-11eb-9111-f799ab5be104.png)
![crop_2](https://user-images.githubusercontent.com/62389564/101932230-d6c6c100-3c1d-11eb-8fbf-192935e09706.png)
![crop_3](https://user-images.githubusercontent.com/62389564/101932250-ddedcf00-3c1d-11eb-9a50-5d0d537d68d6.png)
![crop_4](https://user-images.githubusercontent.com/62389564/101932268-e47c4680-3c1d-11eb-95ee-34ee952801f8.png)

```
[h264 @ 000001cef692f280] illegal short term buffer state ditected
```

**Log file :**

[doukoku_soshite_Ryujinx_1.0.6028.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5680548/doukoku_soshite_Ryujinx_1.0.6028.log)

**Comment by ekfacile** [comment]
**Current on `master` : 1.0.6045**

> Correct type of executable sizes ＃1802
> https://github.com/Ryujinx/Ryujinx/pull/1802

This issue has recurred.
Boot failed and hanged.

```
00:00:01.345 |E| Loader LoadNsos: Process initialization returned error "InvalidMemRange".
```

**Log file :**

[doukoku_soshite_Ryujinx_1.0.6045.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5682492/doukoku_soshite_Ryujinx_1.0.6045.log)

**Comment by ekfacile** [comment]
**Curent on `master` : 1.0.6047**

> Correct type of executable sizes # 1802
> https://github.com/Ryujinx/Ryujinx/pull/1802

Still hangs. Why?
Did someone accidentally revert before **1.0.6028**?

I used a public repository source and apply the # 1802 patch transcribe and build it (using .NET SDK 5.0.101).
\* I have little programming knowledge.

```
git clone https://github.com/Ryujinx/Ryujinx.git
patch -u -p1 -d Ryujinx < again1802.patch
dotnet build -c Release
```

As a result, we were able to reproduce the same state as when it crashed.

It is likely that Ryujinx has back before **1.0.6028**.

**Again ＃1802 patch :**

[again1802.patch.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/5683334/again1802.patch.txt)

**Comment by EmulationFanatic** [comment]
@ekfacile you are misunderstanding the way PR builds work. 1.0.6028 is not an official master build. It is 1.0.6027 with the PR added that makes this game bootable. Wait for the PR to be merged to master.

**Comment by ekfacile** [comment]
**Curent on `master` : 1.0.6052**

Same as **1.0.6028**.

**Last errors :**

```
00:01:10.052 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:01:10.066 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 535
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 gpuVa, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 94
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 18
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**h264 warnings :**

```
[h264 @ 000001b36af6d280] illegal short term buffer state ditected
00:01:09.789 |W| HLE.OsThread.10 ServiceNv Open: Cannot find file device "/dev/nvhost-prof-gpu"!
```

**Log file :**

[doukoku_soshite_Ryujinx_1.0.6052.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5686768/doukoku_soshite_Ryujinx_1.0.6052.log)

**Comment by ekfacile** [comment]
**Current on `hotfix` : 1.0.6075**

The hotfix has no effect at all. The same error will be logged.

```
00:01:05.615 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:01:05.628 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 535
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 gpuVa, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 94
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 18
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Log file :**

[doukoku_soshite_Ryujinx_1.0.6075.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5699844/doukoku_soshite_Ryujinx_1.0.6075.log)

**Comment by ekfacile** [comment]
**Current on `hotfix` : 1.0.6309**

The crash is gone with the 1.0.6309 (https://github.com/Ryujinx/Ryujinx/pull/1905) build.

However, the title movie plays only the audio and the screen remains black.

Also for the title screen, the keep black screen and only the audio is played.  
It accepts controller input, but I don't know what I'm doing because the screen is black.

I can start playing and accept controller input, but keep screen remains black and I can't play real.

```
00:04:15.721 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 63839 took more than 1000ms, resuming execution...
```

**Log file :**

[doukoku_soshite_Ryujinx_1.0.6309.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5821950/doukoku_soshite_Ryujinx_1.0.6309.zip)

**Comment by EmulationFanatic** [comment]
@ekfacile thanks for the steady updates

**Comment by ekfacile** [comment]
**Current on `hotfix` : 1.0.6332**

The crash resolved in **1.0.6309** has recurred in **1.0.6332** (https://github.com/Ryujinx/Ryujinx/pull/1905). I'm sad...

**Last error :**

```
00:01:05.617 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:01:05.629 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 292
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 545
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.WriteImpl(UInt64 va, ReadOnlySpan`1 data, WriteCallback writeCallback) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 194
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 147
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 18
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Log file :**

[doukoku_soshite_Ryujinx_1.0.6332.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5825378/doukoku_soshite_Ryujinx_1.0.6332.log)

**Comment by Kenya-Watanabe** [comment]
I cannot boot this game even now.

Current Version 1.0.6974
OS Windows 10

[Ryujinx_1.0.6974_2021-07-22_13-51-29.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6860072/Ryujinx_1.0.6974_2021-07-22_13-51-29.log)

**Comment by gdkchan** [comment]
Oh yea, I forgot that this was an issue. What you can do for now is enabling ignore missing services in the settings (system tab).

**Comment by wattunya** [comment]
@gdkchan

Thank you. I can boot this game and play it with no problem.

**Comment by GlitchingWolf297** [comment]
@gdkchan I enabled ignore missing service in the setting and when I boot the game again it crashes every single time.

**Comment by EmulationFanatic** [comment]
@GlitchingWolf297 come to Discord for support. There is no need to ping the project founder.

**Comment by EmulationFanatic** [comment]
Updated
