### ISSUE TITLE
Inertial Drift

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2904]
#### Current on `master` : 1.0.5942

Game loaded and was playing smoothly but randomly crashed during the tutorial.

```
HLE.HostThread.2 ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:03:34.907 |I| HLE.HostThread.16 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x000559c0 Sub000000000dfdb9c0
   sdk:0x00055a88 Sub000000000dfdba88
   sdk:0x00055b20 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   sdk:0x000d5f08 nn::os::detail::InternalConditionVariableImplByHorizon::Wait(nn::os::detail::InternalCriticalSection*)
   sdk:0x000cd898 nn::os::AcquireSemaphore(nn::os::SemaphoreType*)
   main:0x026b43b8 Sub000000000a6b83b8
   main:0x026b3380 Sub000000000a6b7380
   main:0x022ecefc Sub000000000a2f0efc
   sdk:0x000d06f8 Sub000000000e0566f8
   sdk:0x000d4ec4 Sub000000000e05aec4
   ??? Sub0000000000000000


00:03:34.909 |W| HLE.HostThread.12 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.14 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.17 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.18 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.36 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.20 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.42 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.21 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.22 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.41 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.25 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.40 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.26 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.39 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.27 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.37 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.28 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.35 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.29 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.34 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.30 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.33 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.32 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.31 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.24 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.23 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.19 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.15 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.13 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.43 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.44 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.45 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.46 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:34.910 |W| HLE.HostThread.47 KernelSvc PrintResult: SendSyncRequest64 returned error ThreadTerminating.
00:03:34.928 |E| HLE.HostThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 54
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 127
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.ArmProcessContext.Execute(ExecutionContext context, UInt64 codeAddress) in C:\projects\ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 21
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1162
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

#### Screenshots :

![2020-12-04 12_30_28-Ryujinx 1 0 5942 - Inertial Drift v1 0 (01002BD00F626000) (64-bit)](https://user-images.githubusercontent.com/62343878/101206887-07f72e00-362d-11eb-8f91-a540ed5548af.png)
![2020-12-04 12_30_32-Ryujinx 1 0 5942 - Inertial Drift v1 0 (01002BD00F626000) (64-bit)](https://user-images.githubusercontent.com/62343878/101206921-13e2f000-362d-11eb-8b81-b457ee4c71ff.png)
![2020-12-04 12_30_35-Ryujinx 1 0 5942 - Inertial Drift v1 0 (01002BD00F626000) (64-bit)](https://user-images.githubusercontent.com/62343878/101206969-23623900-362d-11eb-8188-58df7de14471.png)
![2020-12-04 12_31_21-Ryujinx 1 0 5942 - Inertial Drift v1 0 (01002BD00F626000) (64-bit)](https://user-images.githubusercontent.com/62343878/101206991-2bba7400-362d-11eb-84ae-a3a59f9c0402.png)
![2020-12-04 12_31_54-Ryujinx 1 0 5942 - Inertial Drift v1 0 (01002BD00F626000) (64-bit)](https://user-images.githubusercontent.com/62343878/101207179-7c31d180-362d-11eb-966d-e4bacdd6bf48.png)
![2020-12-04 12_32_26-Ryujinx 1 0 5942 - Inertial Drift v1 0 (01002BD00F626000) (64-bit)](https://user-images.githubusercontent.com/62343878/101207450-e185c280-362d-11eb-8d9f-00f41fb524eb.png)
![2020-12-04 12_32_29-Ryujinx 1 0 5942 - Inertial Drift v1 0 (01002BD00F626000) (64-bit)](https://user-images.githubusercontent.com/62343878/101207596-16921500-362e-11eb-9cf1-d16df1b54370.png)
![2020-12-04 12_32_55-Ryujinx 1 0 5942 - Inertial Drift v1 0 (01002BD00F626000) (64-bit)](https://user-images.githubusercontent.com/62343878/101207719-40e3d280-362e-11eb-9e9e-507eac6d35e5.png)

#### Log file :

[ID.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5645079/ID.log)

**Comment by EmulationFanatic** [comment]
Updated
