### ISSUE TITLE
SuperEpic: The Entertainment War

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2905]
#### Current on `master` : 1.0.5942

Crashes on launch.

```
00:00:08.208 |W| HLE.HostThread.12 KernelSvc PrintResult: MapMemory64 returned error InvalidMemState.
00:00:08.223 |I| HLE.HostThread.2 ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:00:08.434 |I| HLE.HostThread.12 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x0004f830 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   sdk:0x0004f8f4 Sub000000000ca4b8f4
   sdk:0x0004f990 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   sdk:0x000cb2bc nn::os::detail::ThreadManagerImplByHorizon::MapAliasStack(void const*, void const*, unsigned long) const
   sdk:0x000c6d14 nn::os::detail::ThreadManager::CreateAliasStackUnsafe(nn::os::ThreadType*)
   sdk:0x000c6ebc nn::os::detail::ThreadManager::CreateThread(nn::os::ThreadType*, void (*)(void*), void*, void*, unsigned long, int, int)
   sdk:0x000c4498 nn::os::CreateThread(nn::os::ThreadType*, void (*)(void*), void*, void*, unsigned long, int, int)
   main:0x01bf5e90 Sub0000000009bf9e90
   main:0x01cc8cd0 Sub0000000009ccccd0
   main:0x01ccac88 Sub0000000009ccec88
   main:0x016fdb54 Sub0000000009701b54
   main:0x016c4050 Sub00000000096c8050
   main:0x016b3248 Sub00000000096b7248
   main:0x01621210 nnMain
   sdk:0x0009857c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:00:08.435 |W| HLE.HostThread.14 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:00:08.435 |W| HLE.HostThread.13 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:00:08.435 |W| HLE.HostThread.15 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:00:08.448 |E| HLE.HostThread.12 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 54
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 127
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.ArmProcessContext.Execute(ExecutionContext context, UInt64 codeAddress) in C:\projects\ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 21
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1162
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[STEW.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5645120/STEW.log)

**Comment by EmulationFanatic** [comment]
Updated
