### ISSUE TITLE
Yomi wo Saku Hana

### ISSUE THREAD

**Issue by ekfacile** [Ryujinx/Ryujinx-Games-List#2918]
#### Current on `master` : **1.0.5954**

Playable. Some graphics are glitches.  
However, it crashes randomly on the title screen or later.

```
00:03:09.403 |E| HLE.HostThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 22
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 54
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 127
   at Ryujinx.Cpu.CpuContext.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\Ryujinx.Cpu\CpuContext.cs:line 17
   at Ryujinx.HLE.HOS.ArmProcessContext.Execute(ExecutionContext context, UInt64 codeAddress) in C:\projects\ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 21
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1162
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Screenshots :

![crop_005](https://user-images.githubusercontent.com/62389564/101236390-2e43c900-3714-11eb-816e-e7026b536c2a.png)
![crop_023](https://user-images.githubusercontent.com/62389564/101236398-3e5ba880-3714-11eb-8c3c-22ef8135536d.png)
![crop_033](https://user-images.githubusercontent.com/62389564/101236408-44ea2000-3714-11eb-8d2c-99ea1f61e023.png)
![crop_048](https://user-images.githubusercontent.com/62389564/101236412-4a476a80-3714-11eb-8d3b-3f8195f87b3d.png)
![crop_075](https://user-images.githubusercontent.com/62389564/101236417-50d5e200-3714-11eb-9d83-15b39362e0e3.png)
![crop_080](https://user-images.githubusercontent.com/62389564/101236419-56332c80-3714-11eb-9bfc-e38836c7e270.png)
![crop_083](https://user-images.githubusercontent.com/62389564/101236420-5af7e080-3714-11eb-89fc-91fd7375e080.png)

#### Log file :

[yomi_wo_saku_hana.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5646651/yomi_wo_saku_hana.log)

**Comment by Cronos-0** [comment]
Update Now it's fully playable. To make sure I tested 3 times the game didn't crash anymore

### Game Name

Yomi wo Saku Hana

### Game Update Version

1.0.0

### Emulator Build Version

1.1.650

### Graphics Backend

Vulkan

### Hardware Specs

- #### GPU: GTX 1660 SUPER 6GB
- #### CPU: INTEL I5 8400
- #### RAM: KINGSTON DDR4 16GB


### Game State

Plays smoothly

### Screenshots

![bandicam 2023-03-05 07-55-38-736](https://user-images.githubusercontent.com/35269098/222936177-60ab32f7-f3b7-4d68-a5a4-cd7ade9233de.jpg)
![bandicam 2023-03-05 07-52-11-256](https://user-images.githubusercontent.com/35269098/222936180-3b111049-8f3a-4447-8888-5a49c42a19b0.jpg)
![bandicam 2023-03-05 07-52-40-151](https://user-images.githubusercontent.com/35269098/222936183-ab3f225c-b46d-42d4-a40c-5e3c359572e9.jpg)
![bandicam 2023-03-05 07-55-06-817](https://user-images.githubusercontent.com/35269098/222936188-f2e91b22-a161-432a-8774-36f2e06e0bcf.jpg)
![bandicam 2023-03-05 07-54-40-456](https://user-images.githubusercontent.com/35269098/222936191-9fe509bc-42ce-4f11-8730-2b785bd81861.jpg)
![bandicam 2023-03-05 07-54-11-289](https://user-images.githubusercontent.com/35269098/222936192-4827de77-fc42-4fcd-8d50-27b5fdf851a2.jpg)
![bandicam 2023-03-05 07-50-14-568](https://user-images.githubusercontent.com/35269098/222936197-5cb28a5b-b835-482f-8899-85045f955088.jpg)

### Log File

_No response_
