### ISSUE TITLE
Immortals Fenyx Rising crashes at boot

### ISSUE THREAD

**Issue by Niwu34** [Ryujinx/Ryujinx-Games-List#2921]
**Immortals Fenyx Rising**

Version: 1.0.2

Current on Master : Ryujinx Version: 1.0.5995

The game simply crashes at boot

Hardware Specs : 
CPU: Ryzen 5 3600
GPU: Rx 570
RAM: 32GB

Log:
[Ryujinx_1.0.5995_2020-12-09_17-40-05.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5667759/Ryujinx_1.0.5995_2020-12-09_17-40-05.log)

**Comment by EmulationFanatic** [comment]
Please leave the formatting in next time <3

**Comment by Niwu34** [comment]
sry Goffy
:D

**Comment by EmulationFanatic** [comment]
@Niwu34 please re-test this game with "ignore missing services" DISABLED and copy/paste using the new issue template over your existing issue here.

**Comment by AcK77** [comment]
Updated

**Comment by codbugpatrol** [comment]
Same status on 1.0.7066

00:00:10.540 |E| HLE.OsThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Fs.IFileSystemProxy: 205

Guest Stack Trace:
Process: Service, PID: 92

Raw Request Data:
00000000   01 00 11 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  CD 00 00 00 00 00 00 00   SFCI····Í·······
00000020   00 00 00 00 00 00 00 00  00 00 10 00               ············    

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by sotre-develoepr** [comment]
[Ryujinx_1.0.7111_2021-11-29_22-10-37.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7619044/Ryujinx_1.0.7111_2021-11-29_22-10-37.log)

**Comment by gtmartin69** [comment]
Same error here. Any work around, maybe? Thank you all!

**Comment by michealmyerskilldesign** [comment]
> ## Immortals Fenyx Rising
> #### Version: 1.0.2
> #### Current on Master : Ryujinx Version: 1.0.6127
> The game simply crashes at boot
> 
> ```
> HLE.OsThread.5 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Fs.IFileSystemProxy: 205
> 
> Guest Stack Trace:
> Process: Service, PID: 82
> 
> Raw Request Data:
> 00000000   01 00 11 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
> 00000010   53 46 43 49 01 00 00 00  CD 00 00 00 00 00 00 00   SFCI····Í·······
> 00000020   00 00 00 00 00 00 00 00  00 00 10 00               ············
> 
>    at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 148
>    at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
>    at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
>    at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> ```
> 
> #### Hardware Specs :
> CPU: Ryzen 5 3600 GPU: Rx 570 RAM: 32GB
> 
> #### Outstanding Issues:
> [Ryujinx/Ryujinx#1794](https://github.com/Ryujinx/Ryujinx/issues/1794) [Ryujinx/Ryujinx#1596](https://github.com/Ryujinx/Ryujinx/issues/1596)
> 
> #### Log:
> [Ryujinx_1.0.5995_2020-12-09_18-10-12.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5667816/Ryujinx_1.0.5995_2020-12-09_18-10-12.log) (outdated)

Unleashing the Beast inside light the fire inside.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Niwu34** [comment]
Same as `1.1.306`` using Ryu Version  `1.1.637`
![image](https://user-images.githubusercontent.com/67392333/221231046-912bae43-88f5-4844-825d-bd20cbd13fa5.png)
