### ISSUE TITLE
ReTurn - One Way Trip

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#2954]
#### Current on `master` : 1.0.6027

Crashes on launch.

```
00:00:33.516 |I| HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x000ce900 nn::os::AllocateMemoryPages(unsigned long, unsigned long)
   sdk:0x000b82d8 nnmem_nlib_physical_alloc
   sdk:0x000bf528 nn::nlibsdk::heap::TlsHeapCentral::AllocPhy_(void*, unsigned long)
   sdk:0x000c049c nn::nlibsdk::heap::TlsHeapCentral::SplitSpan_(nn::nlibsdk::heap::Span*, unsigned long, nn::nlibsdk::heap::Span*)
   sdk:0x000c4e50 nn::nlibsdk::heap::CentralHeap::Alloc(unsigned long, unsigned long)
   sdk:0x000c66c0 nn::mem::StandardAllocator::Allocate(unsigned long, unsigned long)
   main:0x01ad7bc8 Sub0000000009adbbc8
   main:0x01ad7c68 Sub0000000009adbc68
   main:0x01ab4b70 Sub0000000009ab8b70
   main:0x01aaf544 Sub0000000009ab3544
   main:0x01abd1e8 Sub0000000009ac11e8
   main:0x01a93df4 Sub0000000009a97df4
   main:0x01a93260 Sub0000000009a97260
   main:0x01a56b38 Sub0000000009a5ab38
   main:0x01a56424 Sub0000000009a5a424
   main:0x01a54128 Sub0000000009a58128
   main:0x01a570e4 Sub0000000009a5b0e4
   main:0x015a765c Sub00000000095ab65c
   main:0x0008f984 Sub0000000008093984
   main:0x01a750ec Sub0000000009a790ec
   main:0x01a756c0 Sub0000000009a796c0
   main:0x0066f6ec Sub00000000086736ec
   main:0x016b661c Sub00000000096ba61c
   main:0x014eb7f0 Sub00000000094ef7f0
   main:0x014ea854 Sub00000000094ee854
   main:0x0008f984 Sub0000000008093984
   main:0x01a750ec Sub0000000009a790ec
   main:0x01a756c0 Sub0000000009a796c0
   main:0x01a3dad0 Sub0000000009a41ad0
   main:0x01a3e6d8 Sub0000000009a426d8
   main:0x01a3e938 Sub0000000009a42938
   main:0x01a3eda8 Sub0000000009a42da8
   main:0x0108a434 Sub000000000908e434
   main:0x00e4e314 Sub0000000008e52314
   main:0x00e4d628 Sub0000000008e51628
   main:0x00a7e980 Sub0000000008a82980
   main:0x0008f984 Sub0000000008093984
   main:0x01a750ec Sub0000000009a790ec
   main:0x01af7300 Sub0000000009afb300
   rtld:0x000000c0 Sub00000000080000c0


00:00:33.517 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000375.
00:00:33.529 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 440
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 275
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 135
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 127
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[ROWT.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5679193/ROWT.log)

**Comment by F1ReB4LL** [comment]
## ReTurn - One Way Trip

#### Game Update Version : *1.16.3*

#### Current on `master` : *1.1.243*

#### Graphics Backend : *Both Vulkan and OpenGL*

*Looks OK, haven't noticed anything unusual.*

```
Last error returned: No errors shown
```

#### Hardware Specs : 

##### CPU: *i5-11400H*
##### GPU: *NVIDIA RTX 3050*
##### RAM: *24GB*


#### Screenshots :

![ryujinx_rtn1](https://user-images.githubusercontent.com/39680140/187305784-d91f0383-1c68-4064-ae3f-a754ffdd2e63.png)
![ryujinx_rtn2](https://user-images.githubusercontent.com/39680140/187305802-f459d1fd-08e9-453b-8900-5d84b3fa7003.png)
![ryujinx_rtn3](https://user-images.githubusercontent.com/39680140/187305838-bfa8fa6c-e3a5-494a-b737-b56d58e0bb96.png)
![ryujinx_rtn4](https://user-images.githubusercontent.com/39680140/187305849-18498fee-3a85-4c96-8e1d-5dd24376eb96.png)
![ryujinx_rtn5](https://user-images.githubusercontent.com/39680140/187305863-887c5063-2734-4c7d-b865-54c0da44c880.png)
![ryujinx_rtn6](https://user-images.githubusercontent.com/39680140/187305875-16e50e92-f64b-4d05-82bd-6e3c86a0c439.png)
![ryujinx_rtn7](https://user-images.githubusercontent.com/39680140/187305887-973330cc-c7b2-4acc-9046-a2a76251eb7d.png)
![ryujinx_rtn8](https://user-images.githubusercontent.com/39680140/187305895-6e2f7103-7748-4a24-a766-4c1c49f7f99a.png)
![ryujinx_rtn9](https://user-images.githubusercontent.com/39680140/187305918-3979c463-a2f0-48d6-a84b-293a0d1e42a8.png)
![ryujinx_rtn0](https://user-images.githubusercontent.com/39680140/187305937-8d1d1f0b-47ee-494d-8d45-4ba7827909b9.png)

**Comment by EmulationFanatic** [comment]
Updated, thanks!
