### ISSUE TITLE
Kagamihara/Justice

### ISSUE THREAD

**Issue by ekfacile** [Ryujinx/Ryujinx-Games-List#3039]
#### Current on `master` : **1.0.6052**

Crash after a few tens of seconds after booting (keep black screen).

```
00:00:17.226 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:00:17.241 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 535
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 434
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 275
   at Ryujinx.Graphics.Gpu.Engine.Methods.LaunchDma(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 46
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Log file :

[kagamihara_justice_Ryujinx_1.0.6052.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5686907/kagamihara_justice_Ryujinx_1.0.6052.log)

**Comment by ekfacile** [comment]
**Current on `hotfix` : 1.0.6075**

The hotfix has no effect at all. The same error will be logged.

```
00:00:17.775 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:00:17.787 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 535
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 434
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 275
   at Ryujinx.Graphics.Gpu.Engine.Methods.LaunchDma(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 46
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Log file :**

[kagamihara_justice_Ryujinx_1.0.6075.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5699861/kagamihara_justice_Ryujinx_1.0.6075.log)

**Comment by vojo915** [comment]
**Current on `hash` :** [ee6160e](https://github.com/Ryujinx/Ryujinx/pull/2372)

**Hardware Specs :**

**CPU:** Ryzen 5 3600  
**GPU:** GeForce GTX 1660 Ti  
**RAM:** 16GB

Playable.

However, there are stutters throughout the audio.

**Screenshots :**

![1_q99](https://user-images.githubusercontent.com/84438932/122797539-892cbe80-d2fa-11eb-891a-424551b36ced.jpg)

![2_q99](https://user-images.githubusercontent.com/84438932/122797573-90ec6300-d2fa-11eb-96a6-c9e2ef74581d.jpg)

**Log file :**

[Ryujinx_1.0.0+ee6160e_0100D58012FC2000.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/6688227/Ryujinx_1.0.0%2Bee6160e_0100D58012FC2000.zip)
