### ISSUE TITLE
Atomic Heist

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3042]
#### Current on `master` : 1.0.6052

Game loaded and played smoothly before it crashed a minute or two into gameplay. OpenAL yielded minor degraded audio due to audout issues; using SoundIO worked fine.

```
HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.SignalMemoryTracking(UInt64 va, UInt64 size, Boolean write) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 627
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 135
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 127
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-12-14 04_30_57-Ryujinx 1 0 6052 - Atomic Heist v1 0 0 (01005FE00EC4E000) (64-bit)](https://user-images.githubusercontent.com/62343878/102077031-e719a000-3dc5-11eb-8326-adddf2be9f0f.png)
![2020-12-14 04_31_03-Ryujinx 1 0 6052 - Atomic Heist v1 0 0 (01005FE00EC4E000) (64-bit)](https://user-images.githubusercontent.com/62343878/102077034-e7b23680-3dc5-11eb-9fca-3c1ea3452433.png)
![2020-12-14 04_35_04-Ryujinx 1 0 6052 - Atomic Heist v1 0 0 (01005FE00EC4E000) (64-bit)](https://user-images.githubusercontent.com/62343878/102077050-ee40ae00-3dc5-11eb-9e66-8bdc546abe16.png)
![2020-12-14 04_35_13-Ryujinx 1 0 6052 - Atomic Heist v1 0 0 (01005FE00EC4E000) (64-bit)](https://user-images.githubusercontent.com/62343878/102077055-eed94480-3dc5-11eb-9125-7a211e01a9ae.png)

#### Log file :

[AH.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5688509/AH.log)

**Comment by EmulationFanatic** [comment]
Updated
