### ISSUE TITLE
Arrest of a stone Buddha

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3053]
#### Current on `master` : 1.0.6052

Crashes on launch with a memory access violation console-only error.

#### Log file :

[AoasB.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5688984/AoasB.log)

**Comment by benderscruffy** [comment]
using 1.1.21
still the same problem

**Comment by benderscruffy** [comment]
using 1.1.341
still the same problem

**Comment by EmulationFanatic** [comment]
Same status on 1.1.444, though the error is logged now:

```
HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   0x0000000008014a84	main:0x10a84	
   0x00000000080172ec	main:0x132ec	
   0x0000000008016e78	main:0x12e78	
   0x000000000801ff88	main:0x1bf88	
   0x000000000802009c	main:0x1c09c	
   0x000000000808415c	main:0x8015c	
   0x0000000008084d2c	main:0x80d2c	
   0x00000000080865cc	main:0x825cc	
   0x00000000080b0150	main:0xac150	
   0x00000000080b058c	main:0xac58c	
   0x0000000008004e88	main:0x0e88	
   0x0000000008005474	main:0x1474	nnMain:0x0104
   0x000000000aeeed9c	sdk:0xa1d9c	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)()):0x004c
   0x00000000080000c0	rtld:0x00c0	


00:00:10.730 |I| HLE.GuestThread.15 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x000000100fab6050
	X[01]:	0x0000000000000002
	X[02]:	0x00000010c52cfa00
	X[03]:	0x0000000000000003
	X[04]:	0x00000010c09abf58
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000003
	X[09]:	0x0000000008004000 (main:0x0000)	=> 
	X[10]:	0x0000000000b0c920
	X[11]:	0x0000000000001885
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000000
	X[14]:	0x0000000000000002
	X[15]:	0x000000100ca0a32c
	X[16]:	0x000000000af5f1a0 (sdk:0x1121a0)	=> nn::account::CloseUser(nn::account::UserHandle const&)
	X[17]:	0x0000000008b10920
	X[18]:	0x000000118c303450 (SP:-0xffffffffffffffa0)
	X[19]:	0x000000118c303500 (SP:-0x0050)
	X[20]:	0x0000000000000000
	X[21]:	0x0000000000000000
	X[22]:	0x0000000000000001
	X[23]:	0x0000000000000c58
	X[24]:	0x0000000008b25000
	X[25]:	0x0000000008b25000
	X[26]:	0x000000100fab6c98
	X[27]:	0x000000100f910bd0
	X[28]:	0x0000000008b23d58
	FP:	0x000000118c3034f0 (SP:-0x0040)
	LR:	0x0000000008077730 (main:0x73730)	=> 
	SP:	0x000000118c3034b0 (SP)
	PC:	0x000000000af5f1a0 (sdk:0x1121a0)	=> nn::account::CloseUser(nn::account::UserHandle const&)


00:00:10.730 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:10.767 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 271
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 130
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
```
