### ISSUE TITLE
Midnight Evil

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3054]
#### Current on `master` : 1.0.6052

Crashes on launch.

```
HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x00180244 nn::diag::detail::InvokeAbortObserver(nn::diag::AbortInfo const&)
   sdk:0x0017f09c nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   main:0x00ce3eb8 malloc
   main:0x00cd0250 Sub0000000008cd4250
   main:0x00cd02f8 Sub0000000008cd42f8
   main:0x00cb6504 Sub0000000008cba504
   main:0x00ca944c Sub0000000008cad44c
   main:0x00cb65c8 Sub0000000008cba5c8
   main:0x00c90ae8 Sub0000000008c94ae8
   main:0x00c8ff78 Sub0000000008c93f78
   main:0x00c55e70 Sub0000000008c59e70
   main:0x00c55764 Sub0000000008c59764
   main:0x00c53638 Sub0000000008c57638
   main:0x00c56404 Sub0000000008c5a404
   main:0x00abd050 Sub0000000008ac1050
   main:0x00420dfc Sub0000000008424dfc
   main:0x0040b7dc Sub000000000840f7dc
   main:0x0040b344 Sub000000000840f344
   main:0x003fc3c4 Sub00000000084003c4
   main:0x00145cfc Sub0000000008149cfc
   main:0x0004e2c4 Sub00000000080522c4
   main:0x00c7163c Sub0000000008c7563c
   main:0x00cf50a4 Sub0000000008cf90a4
   main:0x00ced114 Sub0000000008cf1114
   main:0x011aab20 Sub00000000091aeb20
   main:0x011aafc0 Sub00000000091aefc0
   main:0x011aa9b8 Sub00000000091ae9b8
   main:0x0116d9d8 Sub00000000091719d8
   main:0x0116d868 Sub0000000009171868
   main:0x00d55070 Sub0000000008d59070
   main:0x00d54a40 Sub0000000008d58a40
   main:0x00d54cd8 Sub0000000008d58cd8
   main:0x00d543d4 Sub0000000008d583d4
   main:0x00d55774 Sub0000000008d59774
   main:0x00d55c58 Sub0000000008d59c58
   main:0x00d4e218 Sub0000000008d52218
   main:0x00d69e7c Sub0000000008d6de7c
   main:0x00ce4694 nnMain
   sdk:0x0029670c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:00:17.897 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000008ce7da4 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1086
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 58
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 127
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1340

#### Log file :

[ME.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5689273/ME.log)

**Comment by EmulationFanatic** [comment]
Updated
