### ISSUE TITLE
Shady Part of Me

### ISSUE THREAD

**Issue by SeraUQ** [Ryujinx/Ryujinx-Games-List#3058]
#### Current on `master` : 1.0.6052

Game boots but crashes on the loading screen before going ingame.

```
00:01:50.892 |E| GUI.RenderLoop Application : Unhandled exception caught: System.ArgumentException: Invalid reinterpret cast from "F32" to "Bool".
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.TypeConversion.ReinterpretCast(String expr, IAstNode node, VariableType srcType, VariableType dstType) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\TypeConversion.cs:line 72
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.TypeConversion.ReinterpretCast(CodeGenContext context, IAstNode node, VariableType srcType, VariableType dstType) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\TypeConversion.cs:line 20
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions.InstGen.GetExpression(CodeGenContext context, AstOperation operation) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\Instructions\InstGen.cs:line 96
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.<>c__DisplayClass4_0.<PrintBlock>b__0(Object sender, BlockVisitationEventArgs e) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 126
   at Ryujinx.Graphics.Shader.StructuredIr.AstBlockVisitor.Visit()+MoveNext() in C:\projects\ryujinx\Ryujinx.Graphics.Shader\StructuredIr\AstBlockVisitor.cs:line 43
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.PrintBlock(CodeGenContext context, AstBlock block) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 160
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.PrintFunction(CodeGenContext context, StructuredProgramInfo info, StructuredFunction function, String funcName) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 74
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.Generate(StructuredProgramInfo info, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 17
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(FunctionCode[] functions, ShaderConfig config, ShaderProgramInfo& shaderProgramInfo, Int32 sizeA) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 106
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateShader(TranslatorContext translatorContext) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 762
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetComputeShader(GpuState state, UInt64 gpuVa, Int32 localSizeX, Int32 localSizeY, Int32 localSizeZ, Int32 localMemorySize, Int32 sharedMemorySize) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 391
   at Ryujinx.Graphics.Gpu.Engine.Methods.Dispatch(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Compute.cs:line 31
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 111
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![15:43:39-12_14_20](https://user-images.githubusercontent.com/62521228/102095636-0a733800-3e24-11eb-83bd-42c14e31a46a.png)

#### Log file :
[SPoM.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5689483/SPoM.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
