### ISSUE TITLE
Aery - Broken Memories

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3068]
#### Current on `master` : 1.0.6052

Crashes on launch.

```
HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x000cf4b0 nn::os::AllocateMemoryPages(unsigned long, unsigned long)
   sdk:0x000b8e88 nnmem_nlib_physical_alloc
   sdk:0x000c00d8 nn::nlibsdk::heap::TlsHeapCentral::AllocPhy_(void*, unsigned long)
   sdk:0x000c104c nn::nlibsdk::heap::TlsHeapCentral::SplitSpan_(nn::nlibsdk::heap::Span*, unsigned long, nn::nlibsdk::heap::Span*)
   sdk:0x000c5a00 nn::nlibsdk::heap::CentralHeap::Alloc(unsigned long, unsigned long)
   sdk:0x000c7270 nn::mem::StandardAllocator::Allocate(unsigned long, unsigned long)
   main:0x0101dacc Sub0000000009021acc
   main:0x0116d4fc Sub00000000091714fc
   main:0x0101e208 Sub0000000009022208
   main:0x013a9974 Sub00000000093ad974
   main:0x00d58ee0 Sub0000000008d5cee0
   main:0x00d5ec28 nnMain
   sdk:0x000a1d9c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:00:05.269 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000044.
00:00:05.281 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 440
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 275
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 135
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 127
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[ABM.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5691474/ABM.log)

**Comment by EmulationFanatic** [comment]
Updated
