### ISSUE TITLE
Desire remaster ver.

### ISSUE THREAD

**Issue by ekfacile** [Ryujinx/Ryujinx-Games-List#3077]
#### Current on `master` : **1.0.6069**

Boot success. However, the title movie fails to play and crashes.  
Same case as #2901.

```
00:01:13.926 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:01:13.938 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 535
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 gpuVa, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 94
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 18
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Screenshots :

![crop_1](https://user-images.githubusercontent.com/62389564/102212813-21e01d00-3f19-11eb-869d-94659b345a36.png)
![crop_2](https://user-images.githubusercontent.com/62389564/102212832-299fc180-3f19-11eb-8210-bc90b25a098b.png)
![crop_3](https://user-images.githubusercontent.com/62389564/102212891-3fad8200-3f19-11eb-9030-8ec7b24082f4.png)
![crop_4](https://user-images.githubusercontent.com/62389564/102212908-476d2680-3f19-11eb-9b21-ea61d5b1e8af.png)

#### Log file :

[desire_remaster_ver_Ryujinx_1.0.6069.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5695674/desire_remaster_ver_Ryujinx_1.0.6069.log)

**Comment by saldabain** [comment]
Can you try this on my hotfix build?

**Comment by ekfacile** [comment]
**Current on `hotfix` : 1.0.6075**

The hotfix has no effect at all. The same error will be logged.

```
00:01:06.779 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:01:06.790 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 535
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 gpuVa, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 94
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 18
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Log file :**

[desire_remaster_ver_Ryujinx_1.0.6075.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5699825/desire_remaster_ver_Ryujinx_1.0.6075.log)

**Comment by ekfacile** [comment]
**Current on `hotfix` 1.0.6309** and **1.0.6332** (https://github.com/Ryujinx/Ryujinx/pull/1905)

### in case 1.0.6309

The crash is resolved. It also accepts controller input.  
However, the screen is black and I can't actually play it.

Same case as #2901.

**Log file :**

[desire_remaster_ver_Ryujinx_1.0.6309.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5825447/desire_remaster_ver_Ryujinx_1.0.6309.zip)

### in case 1.0.6332

The crash resolved in **1.0.6309** has recurred in **1.0.6332**.

Same case as #2901.

**Last error :**

```
00:01:06.395 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:01:06.413 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 292
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 545
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.WriteImpl(UInt64 va, ReadOnlySpan`1 data, WriteCallback writeCallback) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 194
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 147
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 18
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Log file :**

[desire_remaster_ver_Ryujinx_1.0.6332.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5825448/desire_remaster_ver_Ryujinx_1.0.6332.log)
