### ISSUE TITLE
Alluris

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3078]
#### Current on `master` : 1.0.6069

Crashes on launch.

```
GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000009C1981000.
00:00:52.075 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 451
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 275
   at Ryujinx.Graphics.Gpu.Memory.Buffer.RegionModified(UInt64 mAddress, UInt64 mSize) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 146
   at Ryujinx.Memory.Tracking.MultiRegionHandle.QueryModified(UInt64 address, UInt64 size, Action`2 modifiedAction, Int32 sequenceNumber) in C:\projects\ryujinx\Ryujinx.Memory\Tracking\MultiRegionHandle.cs:line 111
   at Ryujinx.Graphics.Gpu.Memory.Buffer.SynchronizeMemory(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 112
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CreateBufferAligned(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 472
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.TranslateAndCreateBuffer(UInt64 gpuVa, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 409
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferBind(GpuState state, Int32 argument, ShaderType type) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferBind.cs:line 65
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[Alluris.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5696246/Alluris.log)

**Comment by perblac** [comment]
No more dark colors.

Ryujinx 1.1.973

![1](https://github.com/Ryujinx/Ryujinx-Games-List/assets/1044604/69b18c92-5beb-48fa-ad28-d76c2ccb3ac3)

![2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/1044604/02b11013-d620-4f54-9aa5-eac73108ca58)

![3](https://github.com/Ryujinx/Ryujinx-Games-List/assets/1044604/899be054-3689-4c23-bffd-a9391cc8aca7)

![4](https://github.com/Ryujinx/Ryujinx-Games-List/assets/1044604/3360fabb-2094-4542-bcb1-dee680699492)
0)
![5](https://github.com/Ryujinx/Ryujinx-Games-List/assets/1044604/1655a0d9-54b5-4331-898b-90d79c263d30)

![6](https://github.com/Ryujinx/Ryujinx-Games-List/assets/1044604/255cc463-6a7b-41f5-a25c-3cc7a3cc3771)
