### ISSUE TITLE
Among Us

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#3111]
#### Current on `master` : 1.0.6082

The game crashes while trying to start the game. This game is online only, can't be played alone, hope idn1 / 2 can play (just hope).

```
00:03:14.963 |E| HLE.OsThread.5 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Pctl.ParentalControlServiceFactory.IParentalControlService: 1017

Guest Stack Trace:
Process: Service, PID: 82

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  F9 03 00 00 00 00 00 00   SFCI····ù·······
00000020   00 00 00 00 00 00 00 00                            ········        

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 148
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2020-12-16 09-03-58-279](https://user-images.githubusercontent.com/35269098/102296012-14f61480-3f7f-11eb-848a-e2115a58a282.jpg)
![bandicam 2020-12-16 09-04-13-323](https://user-images.githubusercontent.com/35269098/102296027-1cb5b900-3f7f-11eb-99a7-dd4632b7b250.jpg)
![bandicam 2020-12-16 09-04-18-562](https://user-images.githubusercontent.com/35269098/102296035-1fb0a980-3f7f-11eb-94c2-7cf9529e8314.jpg)
![bandicam 2020-12-16 09-04-21-363](https://user-images.githubusercontent.com/35269098/102296038-217a6d00-3f7f-11eb-8337-f790ca822985.jpg)
![bandicam 2020-12-16 09-04-25-930](https://user-images.githubusercontent.com/35269098/102296042-23443080-3f7f-11eb-9df9-fba7983579cb.jpg)
![bandicam 2020-12-16 09-04-41-405](https://user-images.githubusercontent.com/35269098/102296048-250df400-3f7f-11eb-9347-375e7f9e0f41.jpg)

#### Logs :

[Ryujinx_1.0.6082_2020-12-16_09-01-06.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5699860/Ryujinx_1.0.6082_2020-12-16_09-01-06.log)

**Comment by GamerzHell9137** [comment]
Touch emulation in Docked mode is wrong (probably because the resolution goes from 720p Handheld to 1080p Docked) https://streamable.com/wf6t0f

**Comment by GamerzHell9137** [comment]
Ryujinx.HLE.HOS.Services.Pctl.ParentalControlServiceFactory.IParentalControlService: 1017 only triggers when you try Online mode.

For Local Wireless and FreePlay its asking for 
00:02:35.306 |E| HLE.OsThread.6 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient: 31

**Comment by Cronos-0** [comment]
@GamerzHell9137 I have updated the post. Thanks for the additional report. Ov-

**Comment by enalibdac** [comment]
Hi, i have been downloaded emulator to play among us in my pc, but now I'need the ROM of among us nintendo switch and I'cant find

**Comment by enalibdac** [comment]
the game not opens, my so is windows 8.1, i have a portatile toshiba satellite

**Comment by SwigS-27** [comment]
Testing with LDN1:
Local multiplayer screen does open:
![image](https://user-images.githubusercontent.com/30056568/102427562-811d5a80-4009-11eb-8234-589cc44fc138.png)
But crashes when attempting to create a local lobby.
![image](https://user-images.githubusercontent.com/30056568/102427757-e3765b00-4009-11eb-9b40-13ef647169ef.png)

```00:00:30.159 |I| ServiceLdn : LDN TCP client connected a new session with Id 63e9af68-8713-474e-bc53-415f94e15d32
00:00:30.725 |S| ServiceAm LockExit: Stubbed. 
00:00:30.767 |S| ServiceAm UnlockExit: Stubbed. 
00:00:47.467 |S| ServiceAm LockExit: Stubbed. 
00:00:47.489 |S| ServiceAm UnlockExit: Stubbed. 
00:00:47.629 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Services.Ldn.UserServiceCreator.RyuLdn.RyuLdnProtocol.Encode[T](PacketId type, T packet, Byte[] data) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx.HLE\HOS\Services\Ldn\UserServiceCreator\RyuLdn\RyuLdnProtocol.cs:line 327
   at Ryujinx.HLE.HOS.Services.Ldn.UserServiceCreator.RyuLdn.MasterServerClient.CreateNetwork(CreateAccessPointRequest request, Byte[] advertiseData) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx.HLE\HOS\Services\Ldn\UserServiceCreator\RyuLdn\MasterServerClient.cs:line 384
   at Ryujinx.HLE.HOS.Services.Ldn.UserServiceCreator.AccessPoint.CreateNetwork(SecurityConfig securityConfig, UserConfig userConfig, NetworkConfig networkConfig) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx.HLE\HOS\Services\Ldn\UserServiceCreator\AccessPoint.cs:line 81
   at Ryujinx.HLE.HOS.Services.Ldn.UserServiceCreator.IUserLocalCommunicationService.CreateNetworkImpl(ServiceCtx context, Boolean isPrivate) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx.HLE\HOS\Services\Ldn\UserServiceCreator\IUserLocalCommunicationService.cs:line 498
   at Ryujinx.HLE.HOS.Services.Ldn.UserServiceCreator.IUserLocalCommunicationService.CreateNetwork(ServiceCtx context) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx.HLE\HOS\Services\Ldn\UserServiceCreator\IUserLocalCommunicationService.cs:line 446
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 177
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by jpblood3** [comment]
Are there any plans to make a fix for the local multiplayer in this game?

**Comment by roobscoob** [comment]
Ditto. Need an emu for my use case.

**Comment by roobscoob** [comment]
It would honestly be much more preferable if it let you go to Online mode. Even if you can't connect to Officials you can use a Custom server like NodePolus to connect

**Comment by jpblood3** [comment]
> It would honestly be much more preferable if it let you go to Online mode. Even if you can't connect to Officials you can use a Custom server like NodePolus to connect

Well online doesn't work in emulators because of legal issues but you can do "local wireless" as they call it, where you use their servers to play from anywhere. I also need an emulator because I'm trying to access an older version of the game

**Comment by GamerzHell9137** [comment]
Same issues as reported are plaguing the game so nothing to update about the state here
