### ISSUE TITLE
AO Tennis 2

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3118]
#### Current on `master` : 1.0.6086

Crashes after selecting language.

```
HLE.OsThread.5 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.HorizonResultException: ResultFsAesXtsFileHeaderInvalidKeysInRenameFile (2002-4747): Could not decrypt AES-XTS keys
   at LibHac.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.FsSystem.AesXtsFileSystem.ReadXtsHeader(String filePath, String keyPath)
   at LibHac.FsSystem.AesXtsFileSystem.RenameDirectoryImpl(String srcDir, String dstDir, Boolean doRollback)
   at LibHac.FsSystem.AesXtsFileSystem.DoRenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.Fs.Fsa.IFileSystem.RenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.FsSystem.SubdirectoryFileSystem.DoRenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.Fs.Fsa.IFileSystem.RenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.<DoCommit>g__RenameSynchronizingDir|45_2()
   at LibHac.FsSystem.Utility.RetryFinitelyForTargetLocked(Func`1 function)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.DoCommit()
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IFileSystem.Commit(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IFileSystem.cs:line 150
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 114
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-12-16 09_35_32-Ryujinx 1 0 6086 - AO Tennis 2 v1 0 0 (010047000E9AA000) (64-bit)](https://user-images.githubusercontent.com/62343878/102377682-2ee52680-3f82-11eb-9c22-898e49ad5dcb.png)

#### Log file :

[AOT2.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5704072/AOT2.log)

**Comment by EmulationFanatic** [comment]
Updated
