### ISSUE TITLE
Ashphalt 9 Legends

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3127]
#### Current on `master` : 1.0.6086

Crashes on launch.

```
HLE.OsThread.6 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Memory.AddressSpaceManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Memory\AddressSpaceManager.cs:line 167
   at Ryujinx.Memory.AddressSpaceManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Memory\AddressSpaceManager.cs:line 126
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient.WriteSockAddr(ServiceCtx context, Int64 bufferPosition, IPEndPoint endPoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Sockets\Bsd\IClient.cs:line 215
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient.Accept(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Sockets\Bsd\IClient.cs:line 676
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 114
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[AL9.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5704622/AL9.log)

**Comment by sauradipdebnath** [comment]
Implement online services

**Comment by RagdolllFan2005** [comment]
Its Already On Windows For Free

**Comment by EmulationFanatic** [comment]
Updated
