### ISSUE TITLE
BaconMan

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3140]
#### Current on `master` : 1.0.6096

On 1st try game booted for a brief second and audio could be heard playing before crashing.
On 2nd try game booted to title screen and proceeded past for a moment before crashing.

```
GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000A61860000.
00:02:32.732 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 461
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 285
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 557
   at Ryujinx.Graphics.Gpu.Image.Texture.InitializeData(Boolean isView, Boolean withData) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 198
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureInfo info, TextureSearchFlags flags, Nullable`1 sizeHint) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 852
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 62
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 285
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 242
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 304
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 123
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 71
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 40
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 403
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-12-16 14_45_41-Ryujinx 1 0 6096 - BaconMan v1 0 0 (0100EAF00E32E000) (64-bit)](https://user-images.githubusercontent.com/62343878/102410403-bdbb6880-3fad-11eb-9637-685640c25aea.png)
![2020-12-16 14_46_15-Ryujinx 1 0 6096 - BaconMan v1 0 0 (0100EAF00E32E000) (64-bit)](https://user-images.githubusercontent.com/62343878/102410407-beec9580-3fad-11eb-9533-e58febe812c0.png)

#### Log file :

[BM.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5705657/BM.log)

**Comment by benderscruffy** [comment]
using 1.0.7106
goes ingame now
has graphic glitches 
![ryujinx_capture_2021-11-20_10-29-41](https://user-images.githubusercontent.com/2696404/142711570-cd790505-b1a7-44ea-a343-6ae1f1b68d5d.png)
![ryujinx_capture_2021-11-20_10-30-09](https://user-images.githubusercontent.com/2696404/142711572-23e25378-4d07-4bb0-84b5-dd85746ea5e2.png)
![ryujinx_capture_2021-11-20_10-30-25](https://user-images.githubusercontent.com/2696404/142711575-af8f1cd6-11ee-4205-b3e2-f1ce5b585e41.png)
![ryujinx_capture_2021-11-20_10-30-43](https://user-images.githubusercontent.com/2696404/142711577-8de2539e-2ee0-43ff-ab02-cc83b58afd3f.png)
![ryujinx_capture_2021-11-20_10-30-54](https://user-images.githubusercontent.com/2696404/142711579-1aff7252-f803-431a-a39a-e0fcb735ca68.png)
![ryujinx_capture_2021-11-20_10-31-24](https://user-images.githubusercontent.com/2696404/142711583-da88eb20-f67e-43b2-9cdd-4118ca1c2553.png)
![ryujinx_capture_2021-11-20_10-31-40](https://user-images.githubusercontent.com/2696404/142711587-a250dfc9-7bd9-4954-8107-3451684faf82.png)
![ryujinx_capture_2021-11-20_10-31-49](https://user-images.githubusercontent.com/2696404/142711590-66337d6c-47bc-40f4-a1e6-79f8081aff3d.png)
![ryujinx_capture_2021-11-20_10-31-55](https://user-images.githubusercontent.com/2696404/142711599-be54ca9d-b2f4-4385-b239-6b5485dbc377.png)
