### ISSUE TITLE
Baron: Fur Is Gonna Fly

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3149]
#### Current on `master` : 1.0.6119

Crashes while displaying a corrupt early splash screen.

```
GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:01:41.415 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 545
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 444
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 285
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Read[T](UInt64 gpuVa) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 55
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(IGpuAccessor gpuAccessor, Block block, UInt64 limitAddress, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 255
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(IGpuAccessor gpuAccessor, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 87
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, TranslationCounts counts, ShaderConfig& config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 140
   at Ryujinx.Graphics.Shader.Translation.Translator.CreateContext(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, TranslationCounts counts) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 34
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 444
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 989
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 123
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 71
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 40
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 403
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-12-17 04_46_31-Ryujinx 1 0 6119 - Baron_ Fur Is Gonna Fly v1 0 0 (010039C0106C6000) (64-bit)](https://user-images.githubusercontent.com/62343878/102484084-f3e6ff80-4022-11eb-9a07-65f9bc25306d.png)

#### Log file :

[BFIGF.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5709112/BFIGF.zip)

**Comment by benderscruffy** [comment]
using 1.0.7176
goes ingame now
with messed up graphics
![ryujinx_capture_2022-01-19_16-51-57](https://user-images.githubusercontent.com/2696404/150104052-4d34a91a-6b51-4684-8cea-b6ea28af594c.png)
![ryujinx_capture_2022-01-19_16-52-08](https://user-images.githubusercontent.com/2696404/150104078-20fda7b9-9723-4bf5-b89f-164f02970f31.png)
![ryujinx_capture_2022-01-19_16-52-18](https://user-images.githubusercontent.com/2696404/150104108-2f09ee7b-226c-4ebf-82cd-9f68f1464b5f.png)
![ryujinx_capture_2022-01-19_16-52-21](https://user-images.githubusercontent.com/2696404/150104138-a702ca25-40f1-40d0-8fef-c0a42bfc6bb5.png)
![ryujinx_capture_2022-01-19_16-52-25](https://user-images.githubusercontent.com/2696404/150104155-ef5e9d0e-0097-4ca0-9a43-b98387065250.png)
![ryujinx_capture_2022-01-19_16-52-30](https://user-images.githubusercontent.com/2696404/150104198-dddb0d4e-7f38-44d6-8b64-fea6606c2fbd.png)
![ryujinx_capture_2022-01-19_16-52-38](https://user-images.githubusercontent.com/2696404/150104394-b0c58f14-a770-4917-a26d-fed3259467ed.png)
![ryujinx_capture_2022-01-19_16-52-58](https://user-images.githubusercontent.com/2696404/150104439-39a395f4-78d1-4b97-bf68-70802e5c0af9.png)

**Comment by benderscruffy** [comment]
please update
