### ISSUE TITLE
Re:Turn - One Way Trip

### ISSUE THREAD

**Issue by SeraUQ** [Ryujinx/Ryujinx-Games-List#3158]
#### Current on `master` : 1.0.6119

Game crashes on boot
```
00:00:59.169 |I| HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x000ce900 nn::os::AllocateMemoryPages(unsigned long, unsigned long)
   sdk:0x000b82d8 nnmem_nlib_physical_alloc
   sdk:0x000bf528 nn::nlibsdk::heap::TlsHeapCentral::AllocPhy_(void*, unsigned long)
   sdk:0x000c049c nn::nlibsdk::heap::TlsHeapCentral::SplitSpan_(nn::nlibsdk::heap::Span*, unsigned long, nn::nlibsdk::heap::Span*)
   sdk:0x000c4e50 nn::nlibsdk::heap::CentralHeap::Alloc(unsigned long, unsigned long)
   sdk:0x000c66c0 nn::mem::StandardAllocator::Allocate(unsigned long, unsigned long)
   main:0x01ad7bc8 Sub0000000009adbbc8
   main:0x01ad7c68 Sub0000000009adbc68
   main:0x01aae974 Sub0000000009ab2974
   main:0x01abd1c8 Sub0000000009ac11c8
   main:0x01a93df4 Sub0000000009a97df4
   main:0x01a93260 Sub0000000009a97260
   main:0x01a56b38 Sub0000000009a5ab38
   main:0x01a56424 Sub0000000009a5a424
   main:0x01a54128 Sub0000000009a58128
   main:0x01a570e4 Sub0000000009a5b0e4
   main:0x015a765c Sub00000000095ab65c
   main:0x0008f984 Sub0000000008093984
   main:0x01a750ec Sub0000000009a790ec
   main:0x01a756c0 Sub0000000009a796c0
   main:0x0066f6ec Sub00000000086736ec
   main:0x016b661c Sub00000000096ba61c
   main:0x014eb7f0 Sub00000000094ef7f0
   main:0x014ea854 Sub00000000094ee854
   main:0x0008f984 Sub0000000008093984
   main:0x01a750ec Sub0000000009a790ec
   main:0x01a756c0 Sub0000000009a796c0
   main:0x01a3dad0 Sub0000000009a41ad0
   main:0x01a3e6d8 Sub0000000009a426d8
   main:0x01a3e938 Sub0000000009a42938
   main:0x01a3eda8 Sub0000000009a42da8
   main:0x0108a434 Sub000000000908e434
   main:0x00e4e314 Sub0000000008e52314
   main:0x00e4d628 Sub0000000008e51628
   main:0x00a7e980 Sub0000000008a82980
   main:0x0008f984 Sub0000000008093984
   main:0x01a750ec Sub0000000009a790ec
   main:0x01af7300 Sub0000000009afb300
   rtld:0x000000c0 Sub00000000080000c0

00:00:59.169 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000375.
00:00:59.180 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 450
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 285
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 145
```

#### Log file :

[RTOWT.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5709308/RTOWT.log)

**Comment by SeraUQ** [comment]
closed as a duplicate of #2954
