### ISSUE TITLE
Edna & Harvey: Harvey's New Eyes

### ISSUE THREAD

**Issue by SeraUQ** [Ryujinx/Ryujinx-Games-List#3186]
#### Current on `master` : 1.0.6119

Game crashes with an missing opcode
```
Process: Vis1, PID: 92
   main:0x0060ed78 Sub0000000008612d78
   main:0x0060e878 ff_h264_execute_decode_slices
   main:0x005fb614 Sub00000000085ff614
   main:0x005fce74 Sub0000000008600e74
   main:0x005a4efc avcodec_decode_video2
   main:0x006e1e94 Sub00000000086e5e94
   main:0x006e1234 avformat_find_stream_info
   main:0x0025a940 Sub000000000825e940
   main:0x007a768c SDL_RunThread
   main:0x0081481c Sub000000000881881c
   subsdk0:0x005196d0 Sub000000000bbfe6d0
   subsdk0:0x003344b8 Sub000000000ba194b8
   subsdk0:0x00338984 Sub000000000ba1d984
   ??? Sub0000000000000000


00:01:24.442 |I| HLE.OsThread.10 ServiceNv Create: Created map 186 with size 0x00003000!
00:01:24.449 |E| HLE.GuestThread.36 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000085fcd48 (opcode 0xf8a16801) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1086
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 58
```

#### Log file :

[EaHHNE.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5711141/EaHHNE.log)

**Comment by EmulationFanatic** [comment]
Updated
