### ISSUE TITLE
Death Coming

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#3199]
#### Current on `master` : 1.0.6127

Game crashes at launch.

```
00:00:30.799 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 545
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 444
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 285
   at Ryujinx.Graphics.Gpu.Engine.Methods.LaunchDma(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Inline2Memory.cs:line 46
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 403
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[DeathComing.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5714076/DeathComing.log)

**Comment by benderscruffy** [comment]
using 1.1.17
goes ingame now
![ryujinx_capture_2022-02-06_15-38-33](https://user-images.githubusercontent.com/2696404/152671890-026d3436-148f-4be4-b895-2232099e2889.png)
![ryujinx_capture_2022-02-06_15-38-35](https://user-images.githubusercontent.com/2696404/152671891-331c176e-6173-4b3e-b706-ff2158c0545b.png)
![ryujinx_capture_2022-02-06_15-38-39](https://user-images.githubusercontent.com/2696404/152671893-5ac23467-7725-48f4-9fc6-abd4d8935125.png)
![ryujinx_capture_2022-02-06_15-38-48](https://user-images.githubusercontent.com/2696404/152671894-1231b068-e465-4299-88a5-fcec30fcfbef.png)
![ryujinx_capture_2022-02-06_15-38-56](https://user-images.githubusercontent.com/2696404/152671895-c603e886-1f55-475d-89bb-42dff2e52d27.png)
![ryujinx_capture_2022-02-06_15-39-06](https://user-images.githubusercontent.com/2696404/152671896-30c53153-d3e4-47af-ba30-5642678081e0.png)
![ryujinx_capture_2022-02-06_15-39-08](https://user-images.githubusercontent.com/2696404/152671897-15ce070c-a174-4304-8502-ddc9acdcc005.png)
![ryujinx_capture_2022-02-06_15-39-27](https://user-images.githubusercontent.com/2696404/152671900-2c7cc0e3-5113-4b33-819d-971afd18ca85.png)
![ryujinx_capture_2022-02-06_15-39-34](https://user-images.githubusercontent.com/2696404/152671901-5189e806-4c29-4f88-ac83-eb4c98bd6a4c.png)
![ryujinx_capture_2022-02-06_15-39-36](https://user-images.githubusercontent.com/2696404/152671902-0d221ab9-8d08-4a35-8907-e5608d78d888.png)
![ryujinx_capture_2022-02-06_15-40-07](https://user-images.githubusercontent.com/2696404/152671903-9b4d34ed-5319-49a2-8e6e-aa68c811dd1e.png)
![ryujinx_capture_2022-02-06_15-40-23](https://user-images.githubusercontent.com/2696404/152671904-d98e0424-4140-4671-bd4b-2e0eaf4b20b6.png)
![ryujinx_capture_2022-02-06_15-40-37](https://user-images.githubusercontent.com/2696404/152671905-ecc67ee3-ee91-4a3e-99ac-7c173bdfdd6d.png)
![ryujinx_capture_2022-02-06_15-41-04](https://user-images.githubusercontent.com/2696404/152671907-df87acc3-289b-4a22-ad74-9a64ca69a097.png)
![ryujinx_capture_2022-02-06_15-41-49](https://user-images.githubusercontent.com/2696404/152671908-3ac397d8-a2df-4270-891d-11e1eefa97f6.png)
![ryujinx_capture_2022-02-06_15-41-53](https://user-images.githubusercontent.com/2696404/152671909-c75959c7-258b-4be3-842a-5b8bd7c9cafd.png)
![ryujinx_capture_2022-02-06_15-42-04](https://user-images.githubusercontent.com/2696404/152671910-5b8b2392-c979-4761-ba5f-07d1b0aa5f0f.png)
