### ISSUE TITLE
Gensou Rougoku no Kaleidscope

### ISSUE THREAD

**Issue by ekfacile** [Ryujinx/Ryujinx-Games-List#3202]
#### Current on `master` : **1.0.6127**

Boot success. However, it crashes when the game settings are changed and confirmed.  
If not, it crashes immediately after the opening movie finishes playing.  
The content of the error is the same.

Other issue, the screen flickers for a while immediately after the screen transition.

```
00:02:40.771 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000000C18C0000.
00:02:40.784 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 461
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 285
   at Ryujinx.Graphics.Gpu.Memory.Buffer.RegionModified(UInt64 mAddress, UInt64 mSize) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 146
   at Ryujinx.Memory.Tracking.MultiRegionHandle.QueryModified(UInt64 address, UInt64 size, Action`2 modifiedAction, Int32 sequenceNumber) in C:\projects\ryujinx\Ryujinx.Memory\Tracking\MultiRegionHandle.cs:line 111
   at Ryujinx.Graphics.Gpu.Memory.Buffer.SynchronizeMemory(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 112
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CreateBufferAligned(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 472
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.TranslateAndCreateBuffer(UInt64 gpuVa, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 409
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferBind(GpuState state, Int32 argument, ShaderType type) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferBind.cs:line 65
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 403
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Screenshots :

![1](https://user-images.githubusercontent.com/62389564/102680758-93acb500-41fe-11eb-96ba-0ecd1e74a3cc.png)
![2](https://user-images.githubusercontent.com/62389564/102680762-a3c49480-41fe-11eb-922d-d1b25b303802.png)

#### Log file :

[Gensou_Rougoku_no_Kaleidscope_Ryujinx_1.0.6127.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5718904/Gensou_Rougoku_no_Kaleidscope_Ryujinx_1.0.6127.zip)

**Comment by benderscruffy** [comment]
using 1.0.7107
goes ingame now
![ryujinx_capture_2021-11-24_16-41-48](https://user-images.githubusercontent.com/2696404/143203866-74a4fd34-3356-40ca-a708-1cec41f63365.png)
![ryujinx_capture_2021-11-24_16-41-14](https://user-images.githubusercontent.com/2696404/143203910-43107206-f2d8-4365-9129-47e09002ac5e.png)
![ryujinx_capture_2021-11-24_16-40-59](https://user-images.githubusercontent.com/2696404/143203933-d00300b2-3ea3-41ff-855f-3c310df93128.png)
![ryujinx_capture_2021-11-24_16-40-49](https://user-images.githubusercontent.com/2696404/143203964-5137f660-73b5-49b8-a1a7-a6f16331fbf1.png)
![ryujinx_capture_2021-11-24_16-39-57](https://user-images.githubusercontent.com/2696404/143204010-036b2427-19bc-497e-9d7e-9e3dbea08d12.png)
![ryujinx_capture_2021-11-24_16-39-47](https://user-images.githubusercontent.com/2696404/143204028-4746835c-60a1-4b44-8f31-df3aa158b967.png)
![ryujinx_capture_2021-11-24_16-34-13](https://user-images.githubusercontent.com/2696404/143204057-e3b49a54-320b-45cb-be0e-f02f6124f0fb.png)
