### ISSUE TITLE
Witch Spring 3 Re:Fine -The Story of the Marionette Witch Eirudy-

### ISSUE THREAD

**Issue by ekfacile** [Ryujinx/Ryujinx-Games-List#3203]
#### Current on `master` : **1.0.6127**

Sometimes FPS drops, but playable. However, it crashes randomly during play.

```
00:06:39.809 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 37
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 139
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Screenshots :

![0](https://user-images.githubusercontent.com/62389564/102718220-63623500-432a-11eb-82d6-d14c043dcbfe.png)
![1](https://user-images.githubusercontent.com/62389564/102718226-69f0ac80-432a-11eb-93ce-1d232a285424.png)
![2](https://user-images.githubusercontent.com/62389564/102718230-6eb56080-432a-11eb-888b-c28d51e1a364.png)
![3](https://user-images.githubusercontent.com/62389564/102718234-7543d800-432a-11eb-94cb-61a912fd8683.png)
![4](https://user-images.githubusercontent.com/62389564/102718245-7ffe6d00-432a-11eb-9ad2-0963d466e677.png)
![5](https://user-images.githubusercontent.com/62389564/102718248-87257b00-432a-11eb-91fc-efd8666fd2ed.png)
![6](https://user-images.githubusercontent.com/62389564/102718258-91e01000-432a-11eb-9bf6-9049080fb67d.png)
![7](https://user-images.githubusercontent.com/62389564/102718274-986e8780-432a-11eb-933c-8291d2ca7759.png)
![8](https://user-images.githubusercontent.com/62389564/102718278-9e646880-432a-11eb-91be-2282c51514ee.png)
![9](https://user-images.githubusercontent.com/62389564/102718280-a3291c80-432a-11eb-96fd-fa2e73b6c335.png)

#### Log file :

[witch_spring_3_Ryujinx_1.0.6127.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5721163/witch_spring_3_Ryujinx_1.0.6127.zip)

**Comment by JellyEastlao** [comment]
Omg thank you, i’m was waiting for this, i’m hype now, thank you!!!

**Comment by vojo915** [comment]
**Game Update Version:** 1.1

**Current on `Master`:** 1.0.6982

**CPU:** Ryzen 5 3600  
**GPU:** NVIDIA GeForce GTX 1660 Ti  
**RAM:** 16GB  

There is no problem in operation except that the FPS sometimes drops. It doesn't crash and is very stable.

![0](https://user-images.githubusercontent.com/84438932/128631076-fe32ecaa-f19c-41d1-9b2f-ee7b7e51c6ca.jpg)

**Log file:** [Ryujinx_1.0.6982_0100454012E32000.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6950650/Ryujinx_1.0.6982_0100454012E32000.log)
