### ISSUE TITLE
Nekopara Vol.4

### ISSUE THREAD

**Issue by ekfacile** [Ryujinx/Ryujinx-Games-List#3211]
#### Current on `master` : **1.0.6127**

The boot is not stable and may crash.  
Even if the boot succeeds, it will definitely crash when you try to save it (the save itself is done normally).

There is no problem with the behavior itself while playing.

**Last errors:**

- Case 1: Unstable boot

```
00:00:02.629 |E| GUI.RenderLoop Application : Unhandled exception caught: OpenTK.Graphics.GraphicsContextException: Failed to make context 65537 current. Error: 170
   at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window)
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 374
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

- Case 2: Normal boot

```
00:01:45.975 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 545
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 gpuVa, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 94
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 18
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 403
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Screenshots :

![crop_1](https://user-images.githubusercontent.com/62389564/102990885-7f98e880-455b-11eb-864e-862f4be1c867.png)
![crop_2](https://user-images.githubusercontent.com/62389564/102990902-87588d00-455b-11eb-9144-cae545d99795.png)
![crop_3](https://user-images.githubusercontent.com/62389564/102990911-8de70480-455b-11eb-9cda-c9746bb696dc.png)
![crop_4](https://user-images.githubusercontent.com/62389564/102990922-94757c00-455b-11eb-8735-664044ccfd36.png)
![crop_7](https://user-images.githubusercontent.com/62389564/102990929-9a6b5d00-455b-11eb-9c13-bd0fb168ec0b.png)
![crop_8](https://user-images.githubusercontent.com/62389564/102990953-a1926b00-455b-11eb-8e0a-e10e43a12e92.png)
![crop_9](https://user-images.githubusercontent.com/62389564/102990974-a8b97900-455b-11eb-8039-e40e2e633147.png)

#### Log file :

[nekopara_vol.4_Ryujinx_1.0.6127.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5734810/nekopara_vol.4_Ryujinx_1.0.6127.zip)

**Comment by ekfacile** [comment]
**Current on `hotfix` : 1.0.6309** and **1.0.6332** (https://github.com/Ryujinx/Ryujinx/pull/1905)

### in case 1.0.6309 

The crash on save has been improved, but the image is corrupted.  
After that, the screen goes black and I can't really play it (Can play it by rebooting).

![crop_0_q99](https://user-images.githubusercontent.com/62389564/104828694-7f1c1500-58af-11eb-910a-5c528c7cc889.jpg)

Apart from this, as a **new bug**, some images sometimes do not rendering.

**Normal image**

![crop_1_q99](https://user-images.githubusercontent.com/62389564/104828751-edf96e00-58af-11eb-92e7-2906979ba291.jpg)

**Illigal image**

![crop_2_q99](https://user-images.githubusercontent.com/62389564/104828753-f5b91280-58af-11eb-97a7-89f125d4870a.jpg)

**Log file :**

[nekopara_vol_4_Ryujinx_1.0.6309.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5825404/nekopara_vol_4_Ryujinx_1.0.6309.log)

### in case 1.0.6332

The crash resolved in **1.0.6309** has recurred in **1.0.6332**.

Instead, the new bug in **1.0.6309** does not occur.

**Last error :**

```
00:00:52.830 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:00:52.844 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 292
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 545
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.WriteImpl(UInt64 va, ReadOnlySpan`1 data, WriteCallback writeCallback) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 194
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 147
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 18
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Log file :**

[nekopara_vol_4_Ryujinx_1.0.6332.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5825408/nekopara_vol_4_Ryujinx_1.0.6332.log)
