### ISSUE TITLE
Cannot enter input config dialog

### ISSUE THREAD

**Issue by IlyaPlatonov** [Ryujinx/Ryujinx-Games-List#3231]
#### Current on `master` : Build Version : *1.0.6213 mac*

*Cannot start any game yet*

There is impossible to enter input configuration dialog.

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :

Here is the log:
00:00:00.090 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6213
00:00:00.097 |N| Application PrintSystemInfo: Operating System: Darwin 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64 (X64)
00:00:00.097 |N| Application PrintSystemInfo: CPU: Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
00:00:00.098 |N| Application PrintSystemInfo: Total RAM: 16384 MB
00:00:00.102 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:27.514 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> GLib.GException: Unrecognized image file format
   at Gdk.PixbufLoader.Write(Byte[] buf, UInt64 count)
   at Gdk.PixbufLoader.LoadFromStream(Stream input)
   at Gdk.PixbufLoader.InitFromAssemblyResource(Assembly assembly, String resource)
   at Gdk.Pixbuf..ctor(Assembly assembly, String resource, Int32 width, Int32 height)
   at Ryujinx.Ui.ControllerWindow.SetControllerSpecificFields() in C:\projects\ryujinx\Ryujinx\Ui\ControllerWindow.cs:line 255
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
00:00:27.527 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> GLib.GException: Unrecognized image file format
   at Gdk.PixbufLoader.Write(Byte[] buf, UInt64 count)
   at Gdk.PixbufLoader.LoadFromStream(Stream input)
   at Gdk.PixbufLoader.InitFromAssemblyResource(Assembly assembly, String resource)
   at Gdk.Pixbuf..ctor(Assembly assembly, String resource, Int32 width, Int32 height)
   at Ryujinx.Ui.ControllerWindow.SetControllerSpecificFields() in C:\projects\ryujinx\Ryujinx\Ui\ControllerWindow.cs:line 255
   at Ryujinx.Ui.ControllerWindow.InputDevice_Changed(Object sender, EventArgs args) in C:\projects\ryujinx\Ryujinx\Ui\ControllerWindow.cs:line 681
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
00:00:27.531 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> GLib.GException: Unrecognized image file format
   at Gdk.PixbufLoader.Write(Byte[] buf, UInt64 count)
   at Gdk.PixbufLoader.LoadFromStream(Stream input)
   at Gdk.PixbufLoader.InitFromAssemblyResource(Assembly assembly, String resource)
   at Gdk.Pixbuf..ctor(Assembly assembly, String resource, Int32 width, Int32 height)
   at Ryujinx.Ui.ControllerWindow.SetControllerSpecificFields() in C:\projects\ryujinx\Ryujinx\Ui\ControllerWindow.cs:line 255
   at Ryujinx.Ui.ControllerWindow.InputDevice_Changed(Object sender, EventArgs args) in C:\projects\ryujinx\Ryujinx\Ui\ControllerWindow.cs:line 681
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
00:00:27.544 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> GLib.GException: Unrecognized image file format
   at Gdk.PixbufLoader.Write(Byte[] buf, UInt64 count)
   at Gdk.PixbufLoader.LoadFromStream(Stream input)
   at Gdk.PixbufLoader.InitFromAssemblyResource(Assembly assembly, String resource)
   at Gdk.Pixbuf..ctor(Assembly assembly, String resource, Int32 width, Int32 height)
   at Ryujinx.Ui.ControllerWindow.SetControllerSpecificFields() in C:\projects\ryujinx\Ryujinx\Ui\ControllerWindow.cs:line 255
   at Ryujinx.Ui.ControllerWindow.SetCurrentValues() in C:\projects\ryujinx\Ryujinx\Ui\ControllerWindow.cs:line 219
   at Ryujinx.Ui.ControllerWindow..ctor(Builder builder, PlayerIndex controllerId, VirtualFileSystem virtualFileSystem) in C:\projects\ryujinx\Ryujinx\Ui\ControllerWindow.cs:line 161
   at Ryujinx.Ui.SettingsWindow.ConfigureController_Pressed(Object sender, EventArgs args, PlayerIndex playerIndex) in C:\projects\ryujinx\Ryujinx\Ui\SettingsWindow.cs:line 557
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

*(Optional section, remove it if unneeded)*

**Comment by EmulationFanatic** [comment]
This is a game compatibility database.
The mac client is essentially broken currently due to Apple deprecating OpenGL. Your best bet is to use boot camp to dual boot with Windows and use Ryujinx there.
