### ISSUE TITLE
Monster Sanctuary

### ISSUE THREAD

**Issue by Niwu34** [Ryujinx/Ryujinx-Games-List#3237]
## Monster Sanctuary

####1.0.1

#### Current on `master` : 1.0.6235

*The Game goes ingame with a decent framerate - It crashes randomly with the following error message*

```
00:02:55.918 |E| HLE.GuestThread.20 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 37
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 139
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![Cover](https://user-images.githubusercontent.com/67392333/103660610-17400300-4f6e-11eb-987f-e4c62613f414.PNG)
![Intro](https://user-images.githubusercontent.com/67392333/103660626-1a3af380-4f6e-11eb-8f9e-aa8430d8353d.PNG)
![Choos familiar](https://user-images.githubusercontent.com/67392333/103660631-1d35e400-4f6e-11eb-9517-7a53d42447d2.PNG)

#### Log file :

[Ryujinx_1.0.6235_2021-01-05_15-01-59.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5770850/Ryujinx_1.0.6235_2021-01-05_15-01-59.log)

**Comment by Krusher97** [comment]
## Monster Sanctuary

#### Game Update Version : 1.0.2

#### Current on `master` : 1.0.6818

*Playable. Finished the game with no crashes,freezes or noticeable graphical glitches. Runs at 60FPS but performance worsens progressively with each monster encounter, dropping to as low as 15FPS after an hour or two of playtime. This performance drop persists until the game is stopped as not even quitting to the main menu fixes it.*


#### Hardware Specs : 

##### CPU: *i5-6500*
##### GPU: *NVIDIA GTX 1050Ti*
##### RAM: *8GB*

#### Screenshots :

![Ryujinx_2021-04-04_10-06-04](https://user-images.githubusercontent.com/25664221/113499148-56f89580-9531-11eb-969c-13a71fac772a.png)
![Ryujinx_2021-04-04_10-06-26](https://user-images.githubusercontent.com/25664221/113499151-5e1fa380-9531-11eb-8f0c-de475cc02ce9.png)
![Ryujinx_2021-04-04_10-04-14](https://user-images.githubusercontent.com/25664221/113499150-5a8c1c80-9531-11eb-92bc-1fb339c4ddfd.png)


#### Log file :

[Ryujinx_1.0.6818_2021-04-04_10-05-09.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6254005/Ryujinx_1.0.6818_2021-04-04_10-05-09.log)
