### ISSUE TITLE
Problem Starting Animal Crossing New Horizons

### ISSUE THREAD

**Issue by PizzaLover175** [Ryujinx/Ryujinx-Games-List#3238]
Animal Crossing New Horizons

So i have a problem launching the game. I have the prod.keys and the title.keys and the firmware installed.
When i want to start the game it just crash.

The Log says:

00:00:00.041 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6245
00:00:01.399 |N| Application PrintSystemInfo: Operating System: Microsoft Windows 6.1.7601 Service Pack 1 (X64)
00:00:01.399 |N| Application PrintSystemInfo: CPU: AMD Athlon(tm) II X2 250 Processor
00:00:01.400 |N| Application PrintSystemInfo: Total RAM: 8191 MB
00:00:01.405 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.776 |I| Hid Configure: Configured Controller JoyconPair to Player1
00:00:00.906 |N| Application LoadApplication: Using Firmware Version: 9.2.0
00:00:00.907 |I| Application LoadApplication: Loading as XCI.
00:00:01.107 |I| ModLoader QueryContentsDir: Searching mods for Title 01006F8002326000
00:00:01.136 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.335 |I| Loader LoadExeFs: Loading rtld...
00:00:01.375 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:01.376 |I| Loader LoadExeFs: Loading main...
00:00:03.960 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\Project\Park\App\Rom\NX64\Product\code\Park.nss
    SDK Libraries: SDK MW+OmronSoftware+iWnn-1_9_0
                   SDK MW+Nintendo+NintendoSDK_libcurl-9_3_1-Release
                   SDK MW+Nintendo+NintendoSDK_libz-9_3_1-Release
                   SDK MW+Nintendo+NEX-4_6_3-
                   SDK MW+Nintendo+PiaClone-5_24_0
                   SDK MW+Nintendo+PiaCommon-5_24_0
                   SDK MW+Nintendo+Pia-5_24_0
                   SDK MW+Nintendo+PiaLan-5_24_0
                   SDK MW+Nintendo+PiaLocal-5_24_0
                   SDK MW+Nintendo+PiaSession-5_24_0
                   SDK MW+Nintendo+PiaTransport-5_24_0
                   SDK MW+Nintendo+PiaNex-5_24_0-forNEX-4_6_3
                   SDK MW+Nintendo+NEX_MM-4_6_3
                   SDK MW+Nintendo+NintendoWare_Vfx2-9_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-9_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-9_3_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d-9_3_1-Release
                   SDK MW+Nintendo+NintendoWare_Atk-9_3_1-Release
                   SDK MW+Nintendo+NEX_CO-4_6_3
                   SDK MW+Microsoft+Havok_Cloth-2019_1
                   SDK MW+Microsoft+Havok_Animation-2019_1
00:00:03.960 |I| Loader LoadExeFs: Loading subsdk0...
00:00:04.382 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-9_3_1-Release
00:00:04.383 |I| Loader LoadExeFs: Loading sdk...
00:00:05.569 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 9.3.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-9_3_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-9_3_1-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-9_3_1-Release
00:00:05.685 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:05.726 |I| Ptc Load: Loaded Profiling Info (size: 28607 bytes, profiled functions: 10044).
00:00:06.081 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:06.094 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:06.154 |I| Loader LoadNsos: Loading image 2 at 0x000000000babb000...
00:00:06.163 |I| Loader LoadNsos: Loading image 3 at 0x000000000c1c8000...
00:00:06.198 |I| Loader LoadNca: Application Loaded: Animal Crossing: New Horizons v1.0.0 [01006f8002326000] [64-bit]
00:00:07.246 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:07.281 |N| GUI.RenderLoop Gpu PrintGpuInformation: ATI Technologies Inc. Radeon RX 570 Series (4.5.13497 Compatibility Profile Context 23.20.768.12)
00:00:07.466 |I| Ptc TranslationLogger: 0 of 10044 functions translated
00:00:08.408 |E| Application : Unhandled exception caught: System.ArgumentException: Failed to encode constant 0x3B5B0000.
   at ARMeilleure.CodeGen.X86.Assembler.WriteInstruction(Operand dest, Operand source, OperandType type, X86Instruction inst) in C:\projects\ryujinx\ARMeilleure\CodeGen\X86\Assembler.cs:line 986
   at ARMeilleure.CodeGen.X86.CodeGenerator.GenerateStore(CodeGenContext context, Operand address, Operand value) in C:\projects\ryujinx\ARMeilleure\CodeGen\X86\CodeGenerator.cs:line 1588
   at ARMeilleure.CodeGen.X86.CodeGenerator.GenerateOperation(CodeGenContext context, Operation operation) in C:\projects\ryujinx\ARMeilleure\CodeGen\X86\CodeGenerator.cs:line 502
   at ARMeilleure.CodeGen.X86.CodeGenerator.Generate(CompilerContext cctx, PtcInfo ptcInfo) in C:\projects\ryujinx\ARMeilleure\CodeGen\X86\CodeGenerator.cs:line 169
   at ARMeilleure.Translation.Compiler.Compile(ControlFlowGraph cfg, OperandType[] argTypes, OperandType retType, CompilerOptions options, PtcInfo ptcInfo) in C:\projects\ryujinx\ARMeilleure\Translation\Compiler.cs:line 58
   at ARMeilleure.Translation.Translator.Translate(IMemoryManager memory, JumpTable jumpTable, UInt64 address, ExecutionMode mode, Boolean highCq) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 248
   at ARMeilleure.Translation.PTC.Ptc.<>c__DisplayClass71_0.<MakeAndSaveTranslations>g__TranslateFuncs|0() in C:\projects\ryujinx\ARMeilleure\Translation\PTC\Ptc.cs:line 675
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   
   
Please help me :(

**Comment by EmulationFanatic** [comment]
This is a game compatibility database, and there is already an entry for this game. However, in looking at your log,  your PC simply does not meet the minimum requirements for the emulator.

**Comment by PizzaLover175** [comment]
> This is a game compatibility database, and there is already an entry for this game. However, in looking at your log, your PC simply does not meet the minimum requirements for the emulator.

Oh okay :/ thank you
