### ISSUE TITLE
Monster Hunter Rise Demo

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3239]
#### Current on `master` : 1.0.6235

Crashes on launch. With ignore missing services enabled, game gets through graphically corrupt menus but crashes before being able to go in-game.

```
HLE.OsThread.5 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor: 60

Guest Stack Trace:
Process: Service, PID: 82

Raw Request Data:
00000000   01 00 10 00 0B 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  3C 00 00 00 00 00 00 00   SFCI····<·······
00000020   01 00 00 00 00 00 00 00                            ········        

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 148
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1875

#### Log file :

[MHRD.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5785221/MHRD.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Harvey-365** [comment]
(Ryujinx:11932): Gdk-WARNING **: 16:47:20.427: gdkwindow-win32.c:527: DwmEnableBlurBehindWindow (0000000000100350) failed: 80263001

**Comment by Harvey-365** [comment]
keep getting this error on AMD build during the main menu loading

**Comment by MisterPrintf** [comment]
It may be worth noting that the missing service can most likely just be stubbed or immediately returned true, as with Ignore Missing Services enabled the game will get all the way into quest.

**Comment by mrbitr0t** [comment]
![image](https://user-images.githubusercontent.com/76608630/104141524-34535680-53f2-11eb-9eae-fcb976b4e293.png)

AMD rx580 with r5 3600, now boots into ToS without ignore services, Still crashes the driver when it reaches the part where the music starts playing, this should be the same issue as Harvey, Does not reach quest selection.

**Comment by Sergal3** [comment]
![image](https://user-images.githubusercontent.com/77264003/104153929-a2008200-53f4-11eb-808a-8805ee4e01eb.png)
objects in the game are not loaded. Ryzen 5 2600, GTX 1660S, 16GB RAM.

**Comment by MisterPrintf** [comment]
> objects in the game are not loaded. Ryzen 5 2600, GTX 1660S, 16GB RAM.

One of the devs (Peri) is working on implementing SSBO, which fixes the missing textures. Make no mistake, the objects are indeed loaded.
Once that's in place in the Master branch things should work as planned.
Earlier when self-compiling the shadows had some major problems, but MHVuze submitted another PR (which is now in Master) that fixes this.

**Comment by Caian** [comment]
Testing GDKChan PR https://github.com/Ryujinx/Ryujinx/pull/1926 merged on the latest master yields good results: 

![OOOoooo](https://user-images.githubusercontent.com/2220062/104933208-65e69780-5987-11eb-81ef-ecc6df28640f.PNG)

But the game still crushes the FIFO.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by jochuan** [comment]
Game still crashes the driver when it reaches the main menu on build 1.0.6455. The same issue with DwmEnableBlurBehindWindow mentioned above.

**Comment by EratoTiaTuatha** [comment]
Running mostly stable, no crashes, but FPS around 15-20 most of the time, with regular slowdowns into single digits. 
Rig is i7 4790, GTX 1080, 16GB RAM, other titles run smoothly at a stable 30.

**Comment by MisterPrintf** [comment]
Runs well at an almost locked 30FPS, with occasional slowdowns when PPTC functions are added, as is to be expected.
Rig is 10600K (OCd to 5.1Ghz), 16gb 3200Mhz RAM (OCd to 3400), RTX 2060.

**Comment by jdau0096** [comment]
From potato PC side, can run really well in menu but a slow load entering the map, with the highest 28 FPS in the menu and 9-10 FPS average ingame. Rig is i5-8300H (3.7ghz), 8gb 2666Mhz RAM, GTX 1050 Ti.

**Comment by EmulationFanatic** [comment]
Updated
