### ISSUE TITLE
Scott Pilgrim vs The World: The Game

### ISSUE THREAD

**Issue by Niwu34** [Ryujinx/Ryujinx-Games-List#3245]
## Scott Pilgrim vs The World:
[Ryujinx_1.0.6324_2021-01-15_19-10-05.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5822309/Ryujinx_1.0.6324_2021-01-15_19-10-05.log)
 The Game

#### Current on `master` : *1.0.6324*

The game doesn't go ingame which is caused by an unimplemented service. 

```
Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 13

Guest Stack Trace:
Process: Service, PID: 82

Buffer Information:
	PtrBuff:
	[0] Position: 0x0000000000000000 Size: 0x0000000000000000
	SendBuff:
	Position: 0x00000020c0000660 Size: 0x0000000000000010 Flags: 0
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
	ReceiveBuff:
	Position: 0x0000001e800004f0 Size: 0x0000000000000167 Flags: 0
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0D 00 00 00 00 00 00 00   SFCI············
00000010   00 00 00 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00   ················
00000030   00 00 00 00                                        ····            

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 148
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1819

**Comment by Itamai** [comment]
Still not playable.
if you ignore the unimplemented service you get an invalid access handler exception but i dont know if this is related to the missing service issue
```
00:00:27.289 |I| HLE.GuestThread.17 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   main:0x00d22958 Sub0000000008d26958
   main:0x00db21a4 Sub0000000008db61a4
   main:0x00db20f4 Sub0000000008db60f4
   main:0x00eb8580 Sub0000000008ebc580
   sdk:0x003460a4 Sub000000000b5b50a4
   ??? Sub0000000000000000


00:00:27.289 |E| HLE.GuestThread.17 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000010.
00:00:27.315 |E| HLE.GuestThread.17 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 468
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 292
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 150
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 141
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Niwu34** [comment]
The Game still crashes at Boot due the Missing Service not being implemented:
https://github.com/Ryujinx/Ryujinx/issues/1819

```
00:00:09.031 |E| HLE.OsThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 13

Guest Stack Trace:
Process: Service, PID: 93

Buffer Information:
	PtrBuff:
	[0] Position: 0x0000000000000000 Size: 0x0000000000000000
	SendBuff:
	Position: 0x00000020c0000660 Size: 0x0000000000000010 Flags: 0
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
	ReceiveBuff:
	Position: 0x0000001e800004f0 Size: 0x0000000000000167 Flags: 0
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0D 00 00 00 00 00 00 00   SFCI············
00000010   00 00 00 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00   ················
00000030   00 00 00 00                                        ····            

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 156
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 212
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1038
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

**Comment by benderscruffy** [comment]
same status on 1.1.17

**Comment by SwigS-27** [comment]
Scott Pilgrim now boots with Ignore Missing Services as of around build 1.1.26
Seems to be playable.

![image](https://user-images.githubusercontent.com/30056568/153732942-500f04b8-a613-4539-b8ce-7b0f768726ea.png)
![image](https://user-images.githubusercontent.com/30056568/153732956-affd7734-ef70-48a8-af4f-7d4a5c411edc.png)
[Ryujinx_1.1.26_2022-02-13_00-11-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8054740/Ryujinx_1.1.26_2022-02-13_00-11-28.log)

**Comment by Vivimagic** [comment]
I am getting crashes even with "Ignore Missing Services" turn on in the settings.

00:00:00.097 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.101 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.101 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.102 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.103 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.103 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.104 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x13D7
00:00:00.104 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.105 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.105 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.107 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.114 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.114 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.114 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.114 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.114 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.115 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.115 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.115 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.115 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.115 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.116 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.116 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.116 |I| Configuration LogValueChange: IgnoreMissingServices set to: True
00:00:00.116 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.120 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.673
00:00:00.124 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.124 |N| Application Print: CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz ; 8 logical
00:00:00.125 |N| Application Print: RAM: Total 65496 MiB ; Available 59773 MiB
00:00:00.128 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.128 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.075 |I| Gpu : Backend Threading (Auto): True
00:00:00.360 |N| Application LoadApplication: Using Firmware Version: 15.0.1
00:00:00.361 |I| Application LoadApplication: Loading as NSP.
00:00:00.389 |I| ModLoader QueryContentsDir: Searching mods for Title 0100394011C30000
00:00:00.390 |I| ModLoader QueryContentsDir: Searching mods for Title 0100394011C30000
00:00:00.394 |I| Loader LoadExeFs: Loading rtld...
00:00:00.404 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.404 |I| Loader LoadExeFs: Loading main...
00:00:00.702 |I| Loader PrintRoSectionInfo: main:
    Module: E:\ES\Scott\git\Build\NX64\Release\Scott\Scott.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libcurl-10_6_0-Release
00:00:00.702 |I| Loader LoadExeFs: Loading subsdk0...
00:00:00.808 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: glslc
00:00:00.808 |I| Loader LoadExeFs: Loading sdk...
00:00:00.948 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 10.6.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-10_6_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-10_6_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-10_6_0-Release
00:00:01.178 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.191 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.193 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:01.214 |I| Loader LoadNsos: Loading image 2 at 0x000000000a963000...
00:00:01.218 |I| Loader LoadNsos: Loading image 3 at 0x000000000b26c000...
00:00:01.231 |I| ModLoader LoadCheats: Build ids found for title 0100394011C30000:
    C1ED34FD7D1962277A4555D9EC7146571218ED5D000000000000000000000000
    064F1988133C54DB3B757810E5B11A4048E209FF000000000000000000000000
    B7B77217CBF6B12D160220BBB766F8CC1405AC4D000000000000000000000000
    BBC88B74CD99A89DDA01EE7BE469161200BCC28B000000000000000000000000
00:00:01.234 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.241 |I| Loader LoadNca: Application Loaded: Scott Pilgrim vs The World: The Game v1.0.0 [0100394011c30000] [64-bit]
00:00:01.256 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.275 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:01.576 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 980M (Vulkan v1.3.236, Driver v531.29.0.0)
00:00:01.587 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:01.595 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:02.236 |S| HLE.OsThread.20 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.364 |S| HLE.OsThread.20 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:02.369 |S| HLE.OsThread.20 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.373 |S| HLE.OsThread.20 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.436 |S| HLE.OsThread.20 ServicePctl Initialize: Stubbed. 
00:00:06.933 |S| HLE.OsThread.20 ServiceAm SetOperationModeChangedNotification: Stubbed. {operationModeChangedNotification: True}
00:00:06.934 |S| HLE.OsThread.20 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:06.935 |S| HLE.OsThread.20 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: True ; unknownFlag2: True ; unknownFlag3: False}
00:00:06.935 |S| HLE.OsThread.20 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:06.964 |W| HLE.GuestThread.19 KernelSvc : MapSharedMemory() = InvalidMemoryRegion
00:00:06.978 |S| HLE.OsThread.5 ServiceBsd RegisterClient: Stubbed. 
00:00:06.980 |S| HLE.OsThread.5 ServiceBsd StartMonitoring: Stubbed. {unknown0: 0}
00:00:07.027 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:07.031 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV8
00:00:07.055 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:07.055 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:07.100 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:07.109 |S| HLE.OsThread.20 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72120541376610304}
00:00:07.126 |S| HLE.OsThread.20 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:07.175 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:07.248 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:07.251 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 96 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight}
00:00:07.258 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 9 Players: Handheld,Player1,Player2,Player3,Player4,Player5,Player6,Player7,Player8
00:00:07.302 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:07.324 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:07.366 |I| HLE.OsThread.20 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:07.368 |I| HLE.OsThread.20 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:07.493 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:07.555 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.559 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:07.559 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.561 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:07.561 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.562 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:07.562 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:07.689 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:07.691 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:07.692 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:07.693 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:07.697 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:07.698 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:07.701 |S| HLE.OsThread.10 ServiceNv SetTimeslice: Stubbed. 
00:00:07.710 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:07.960 |S| HLE.OsThread.9 ServiceHid StartSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 131075}
00:00:08.012 |W| HLE.OsThread.20 KernelIpc CallHipcMethod: Missing service Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 13 ignored
00:00:09.503 |S| HLE.OsThread.20 ServiceNifm CreateRequest: Stubbed. {version: 2}
00:00:09.507 |S| HLE.OsThread.20 ServiceNifm Cancel: Stubbed. 
00:00:09.509 |S| HLE.OsThread.20 ServiceNifm Submit: Stubbed. 
00:00:09.509 |S| HLE.OsThread.20 ServiceNifm GetRequestState: Stubbed. 
00:00:09.510 |S| HLE.OsThread.20 ServiceNifm GetResult: Stubbed. 
00:00:09.511 |S| HLE.OsThread.20 ServiceNifm Cancel: Stubbed. 
00:00:09.681 |S| HLE.OsThread.20 ServiceNifm Submit: Stubbed. 
00:00:09.684 |S| HLE.OsThread.20 ServiceNifm GetRequestState: Stubbed. 
00:00:09.689 |S| HLE.OsThread.20 ServiceNifm GetResult: Stubbed. 
00:00:09.692 |S| HLE.OsThread.20 ServiceSsl SetInterfaceVersion: Stubbed. {interfaceVersion: 3}
00:00:10.027 |I| HLE.OsThread.20 ServiceNifm GetCurrentIpAddress: Console's local IP is "192.168.1.190".
00:00:10.092 |S| HLE.OsThread.20 ServiceNifm Submit: Stubbed. 
00:00:10.093 |S| HLE.OsThread.20 ServiceNifm GetRequestState: Stubbed. 
00:00:10.093 |S| HLE.OsThread.20 ServiceNifm GetResult: Stubbed. 
00:00:10.558 |I| HLE.OsThread.20 ServiceNifm GetCurrentIpAddress: Console's local IP is "192.168.1.190".
00:00:11.293 |I| HLE.OsThread.20 ServiceNifm GetCurrentIpConfigInfo: Console's local IP is "192.168.1.190".
00:00:11.330 |I| HLE.OsThread.20 ServiceNifm GetCurrentIpConfigInfo: Console's local IP is "192.168.1.190".
00:00:11.387 |I| HLE.OsThread.20 ServiceNifm GetCurrentIpAddress: Console's local IP is "192.168.1.190".
00:00:14.203 |I| HLE.GuestThread.22 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 96
   0x0000000008d25418	main:0xd21418	
   0x0000000008db4c64	main:0xdb0c64	
   0x0000000008db4bb4	main:0xdb0bb4	
   0x0000000008ebb040	main:0xeb7040	
   0x000000000b5b20a4	sdk:0x3460a4	
   0x0000000000000000


00:00:14.209 |I| HLE.GuestThread.22 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000001016a9f980
	X[01]:	0x000000120a653d10 (SP:-0x4000)
	X[02]:	0x000000120a653d10 (SP:-0x4000)
	X[03]:	0x000000120a651d10 (SP:-0x2000)
	X[04]:	0x0000000000002000
	X[05]:	0x0000000000000800
	X[06]:	0x0000000000000001
	X[07]:	0x0000000000000001
	X[08]:	0x0000000008d2c340 (main:0xd28340)	=> 
	X[09]:	0x000000120a657d70 (SP:-0x8060)
	X[10]:	0x0000000000000800
	X[11]:	0x0000000000001000
	X[12]:	0x000000120a65bdc0 (SP:-0xc0b0)
	X[13]:	0x000000120a651d10 (SP:-0x2000)
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000000
	X[16]:	0x0000000000000000
	X[17]:	0x000000000b5b3740 (sdk:0x347740)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Leave()
	X[18]:	0x0000000000000000
	X[19]:	0x0000001016a9f980
	X[20]:	0x0000000000000800
	X[21]:	0x000000120a657dc0 (SP:-0x80b0)
	X[22]:	0x000000120a657d70 (SP:-0x8060)
	X[23]:	0x000000120a64fd10 (SP)
	X[24]:	0x0000000000002000
	X[25]:	0x0000001016a9f960
	X[26]:	0x0000001016607000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x000000120a653d60 (SP:-0x4050)
	LR:	0x0000000008d2bd98 (main:0xd27d98)	=> 
	SP:	0x000000120a64fd10 (SP)
	PC:	0x0000000008d2c340 (main:0xd28340)	=> 


00:00:14.209 |E| HLE.GuestThread.22 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:14.269 |E| HLE.GuestThread.22 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 277
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270

**Comment by mdsmendes94** [comment]
I am experiencing the same as  @Vivimagic, Ryujinx 1.1.699, getting crashes even with "Ignore Missing services" turned on

**Comment by Niwu34** [comment]
The game crashes with ignore missing services at boot the first time.
It boots fine on the second try.
Seems to be related to the pptc (crashed again once when I delted my pptc)

**Comment by joe564338** [comment]
I found the fix for people who are still crashing as i was even with ignore missing services checked. Make a mii with the mii applet. Solved the problem for me. Also update ryujinx to latest could of also been latest update

**Comment by joshfarmpig** [comment]
I did all of the things and it is still crashing similarly to the previous one

**Comment by cddude** [comment]
Same status on 1.1.1345

[Ryujinx_1.1.1345_2024-07-12_04-06-29.log](https://github.com/user-attachments/files/16190706/Ryujinx_1.1.1345_2024-07-12_04-06-29.log)
