### ISSUE TITLE
Fantasy Tavern Sextet -Vol.2 Adventurer's Days-

### ISSUE THREAD

**Issue by ekfacile** [Ryujinx/Ryujinx-Games-List#3246]
#### Current on `master` : **1.0.6327**

Playable.

However, FPS is unstable (8 - 50).  
Video and audio stutters occur at regular intervals.  
The game may stop working for a few seconds.

And when I try to call the "backlog screen" or "save screen" or "load screen" it crashes.

```
00:02:49.685 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 292
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 267
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyBuffer(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyBuffer.cs:line 109
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Screenshots :

![crop_1_q99](https://user-images.githubusercontent.com/62389564/104852856-82abac80-5940-11eb-8c5c-0f2399cd992e.jpg)
![crop_2_q99](https://user-images.githubusercontent.com/62389564/104852859-8808f700-5940-11eb-9f28-b8b60799f93e.jpg)
![crop_3_q99](https://user-images.githubusercontent.com/62389564/104852861-8c351480-5940-11eb-9da1-9c1f3a697959.jpg)
![crop_4_q99](https://user-images.githubusercontent.com/62389564/104852864-91925f00-5940-11eb-86aa-fb1d17f4de88.jpg)
![crop_5_q99](https://user-images.githubusercontent.com/62389564/104852875-96efa980-5940-11eb-954d-85fa0e100bac.jpg)

#### Log file :

[fantasy_tavern_sextet_vol_2_Ryujinx_1.0.6327.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5826614/fantasy_tavern_sextet_vol_2_Ryujinx_1.0.6327.log)

**Comment by benderscruffy** [comment]
can the title be changed to 
Fantasy Tavern Sextet -Vol.2 Adventurer's Days - 01005c10136ca000
doesn't crash at backlog or save and load screen anymore
on problem is when you save the picture in the save box is messed up
other than that no problems so far
![ryujinx_capture_2021-11-06_10-55-05](https://user-images.githubusercontent.com/2696404/140595680-710009cd-fc62-452b-a5a5-120e5c7c29e4.png)
