### ISSUE TITLE
Body of Evidence - 0100721013510000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3252]
#### Current on `master` : 1.0.6373

Crashes shortly after pressing A for New Game at the title screen.

```
GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x2370EF000..0x23714F000 is not fully mapped.
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 325
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 732
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(CopyTexture copyTexture, FormatInfo formatInfo, Boolean preferScaling, Nullable`1 sizeHint) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 506
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyTexture(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyTexture.cs:line 105
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2021-01-20 16_59_58-Ryujinx 1 0 6373 - Body of Evidence v1 0 0 (0100721013510000) (64-bit)](https://user-images.githubusercontent.com/62343878/105256257-a4748180-5b42-11eb-9c7c-5bbd57f201eb.png)
![2021-01-20 17_01_04-Ryujinx 1 0 6373 - Body of Evidence v1 0 0 (0100721013510000) (64-bit)](https://user-images.githubusercontent.com/62343878/105256265-a8080880-5b42-11eb-9202-9b5237599853.png)

#### Log file :

[BoE.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5845985/BoE.log)

**Comment by EmulationFanatic** [comment]
Updated
