### ISSUE TITLE
FUZE Player - 010055801134E000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3258]
#### Current on `master` : 1.0.6373

Crashes on launch.

```
00:00:11.049 |S| HLE.OsThread.5 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72151602570780672}
00:00:11.086 |S| HLE.OsThread.5 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:11.657 |I| HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   main:0x00159510 Sub000000000815d510


00:00:11.657 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x000000000000007A.
00:00:11.674 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 292
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 450
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 285
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 145
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 139
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[FP.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5850519/FP.log)

**Comment by EmulationFanatic** [comment]
Updated
