### ISSUE TITLE
Tennis World Tour 2 - 0100950012F66000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3269]
#### Current on `master` : 1.0.6407

Crashes in early splash screens.

```
HLE.OsThread.5 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.HorizonResultException: ResultFsAesXtsFileHeaderInvalidKeysInRenameFile (2002-4747): Could not decrypt AES-XTS keys
   at LibHac.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.FsSystem.AesXtsFileSystem.ReadXtsHeader(String filePath, String keyPath)
   at LibHac.FsSystem.AesXtsFileSystem.RenameDirectoryImpl(String srcDir, String dstDir, Boolean doRollback)
   at LibHac.FsSystem.AesXtsFileSystem.DoRenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.Fs.Fsa.IFileSystem.RenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.FsSystem.SubdirectoryFileSystem.DoRenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.Fs.Fsa.IFileSystem.RenameDirectory(U8Span oldPath, U8Span newPath)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.<DoCommit>g__RenameSynchronizingDir|45_2()
   at LibHac.FsSystem.Utility.RetryFinitelyForTargetLocked(Func`1 function)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.DoCommit()
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IFileSystem.Commit(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IFileSystem.cs:line 150
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 114
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1947

#### Screenshots :

![2020-11-26 03_31_43-Ryujinx 1 0 5816 - Tennis World Tour 2 v1 0 0 (01002AF011D14000) (64-bit)](https://user-images.githubusercontent.com/62343878/105762528-c0e13700-5f11-11eb-83c1-832351d59b04.png)
![2020-11-26 03_32_18-Ryujinx 1 0 5816 - Tennis World Tour 2 v1 0 0 (01002AF011D14000) (64-bit)](https://user-images.githubusercontent.com/62343878/105762532-c2126400-5f11-11eb-8611-f8575b893260.png)
![2021-01-25 13_30_38-Ryujinx 1 0 6407 - Tennis World Tour 2 v1 0 0 (0100950012F66000) (64-bit)](https://user-images.githubusercontent.com/62343878/105762533-c2126400-5f11-11eb-935a-bd4f0d6a5909.png)
![2021-01-25 13_31_17-Ryujinx 1 0 6407 - Tennis World Tour 2 v1 0 0 (0100950012F66000) (64-bit)](https://user-images.githubusercontent.com/62343878/105762534-c2aafa80-5f11-11eb-9b3b-f92d531dae5b.png)

#### Log file :

[TWT2.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5869510/TWT2.log)

**Comment by benderscruffy** [comment]
using 1.4
goes  in game now
only problem is the players have black spots on them
![ryujinx_capture_2022-01-23_11-18-06](https://user-images.githubusercontent.com/2696404/150663559-21195630-2e90-4f52-8854-fe6b2fec4e90.png)
![ryujinx_capture_2022-01-23_11-18-47](https://user-images.githubusercontent.com/2696404/150663562-2383e7bd-a4bf-43f9-85a2-02f14e7a680a.png)
![ryujinx_capture_2022-01-23_11-19-11](https://user-images.githubusercontent.com/2696404/150663565-6c80398c-e5b0-47a2-9c57-565ccb91cb9f.png)
![ryujinx_capture_2022-01-23_11-19-17](https://user-images.githubusercontent.com/2696404/150663569-2108f6ff-0042-4ab9-9e2e-360085fc925f.png)
![ryujinx_capture_2022-01-23_11-21-59](https://user-images.githubusercontent.com/2696404/150663573-e6d73fce-946e-4275-9684-0c78a8634853.png)
![ryujinx_capture_2022-01-23_11-22-10](https://user-images.githubusercontent.com/2696404/150663575-d046376f-867f-4ab7-afa1-b84a230df503.png)
![ryujinx_capture_2022-01-23_11-22-53](https://user-images.githubusercontent.com/2696404/150663576-2f821c57-5b45-4f1a-af68-404c5223a63d.png)
![ryujinx_capture_2022-01-23_11-23-04](https://user-images.githubusercontent.com/2696404/150663577-5ee07b78-8f88-4f15-bd5d-f3a4fcf09c76.png)
![ryujinx_capture_2022-01-23_11-23-23](https://user-images.githubusercontent.com/2696404/150663579-a2cf0e87-2745-4945-a897-054a0106b726.png)
![ryujinx_capture_2022-01-23_11-23-27](https://user-images.githubusercontent.com/2696404/150663580-500d406f-a8c8-442f-a902-a21f6d6daeb3.png)
![ryujinx_capture_2022-01-23_11-23-30](https://user-images.githubusercontent.com/2696404/150663583-416dba9a-d65d-4485-8256-fe31126fc4b5.png)

**Comment by benderscruffy** [comment]
please update

**Comment by EmulationFanatic** [comment]
Updated
