### ISSUE TITLE
Shadow Gangs - 0100BE501382A000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3270]
#### Current on `master` : 1.0.6407

Crashes on launch.

```
SurfaceFlinger.Composer Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.SurfaceFlinger.Compose() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\SurfaceFlinger.cs:line 266
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.SurfaceFlinger.HandleComposition() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\SurfaceFlinger.cs:line 227
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[SG.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5869520/SG.log)

**Comment by AcK77** [comment]
Needs an update

**Comment by EmulationFanatic** [comment]
Updated

**Comment by benderscruffy** [comment]
using 1.1.17
goes ingame now
![ryujinx_capture_2022-02-06_15-30-36](https://user-images.githubusercontent.com/2696404/152671601-a5f81963-a71d-47cd-90e5-e4cd6379b8d0.png)
![ryujinx_capture_2022-02-06_15-30-50](https://user-images.githubusercontent.com/2696404/152671603-c1daef8d-98ae-46b7-912a-3e9916750261.png)
![ryujinx_capture_2022-02-06_15-30-53](https://user-images.githubusercontent.com/2696404/152671604-eaf27de5-3a5f-439d-8795-96e89f2b67e5.png)
![ryujinx_capture_2022-02-06_15-31-05](https://user-images.githubusercontent.com/2696404/152671606-c8ffe67d-f6da-4e81-9153-59490e824b02.png)
![ryujinx_capture_2022-02-06_15-31-18](https://user-images.githubusercontent.com/2696404/152671612-ad8e1c23-d005-4767-ae58-6f0908f14cec.png)
![ryujinx_capture_2022-02-06_15-32-04](https://user-images.githubusercontent.com/2696404/152671615-7864f04c-17d7-4cbb-b6b5-26fe7d26c14c.png)

**Comment by F1ReB4LL** [comment]
## Game Name

#### Game Update Version : *1.0.0*

#### Current on `master` : Build Version : *1.1.166*

*The game is super-unstable. Sometimes, it doesn't show anything at all and crashes right after loading (haven't kept the log, sorry). Sometimes, it runs, but flickers heavily and crashes when the game starts (first log). Sometimes, it runs without flickering, but still crashes when the game starts. Sometimes, it crashes after the very first logo (second log).*

```
Last error returned.
case 1: Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
case 2: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000a0e85c0 (opcode 0xe7ffdefe) is undefined!
```

#### Hardware Specs : 

##### CPU: *i5-11400H*
##### GPU: *NVIDIA RTX 3050*
##### RAM: *24GB*

#### Log file :

[Ryujinx_1.1.166_2022-07-08_01-49-25.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9067794/Ryujinx_1.1.166_2022-07-08_01-49-25.log)
[Ryujinx_1.1.166_2022-07-08_01-51-02.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9067796/Ryujinx_1.1.166_2022-07-08_01-51-02.log)

**Comment by F1ReB4LL** [comment]
Can you change its status? Or is it only me and works fine for others?

**Comment by F1ReB4LL** [comment]
1.1.201 with Vulkan - same story (with a little bit different crash lines).

Case 1:
>Unhandled exception. Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000a0e85c0 (opcode 0xe7ffdefe) is undefined!                                                                                                             
at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1105                                                
at Ryujinx.Cpu.Jit.JitExecutionContext.UndefinedHandler(ExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 104                                                                     
at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\State\ExecutionContext.cs:line 135                                                                                                      at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 61                                                                                             at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168                                                                                              
at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32                                                                                                        
at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40                                                                                          
at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265                                                                                                                     at System.Threading.Thread.StartCallback()

Case 2:
>Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.                  
at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 252                                                        
at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168                                                                                              
at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32                                                                                                        
at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40                                                                                          
at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265                                                                                                                     at System.Threading.Thread.StartCallback()

**Comment by F1ReB4LL** [comment]
https://github.com/Ryujinx/Ryujinx/issues/1340

**Comment by F1ReB4LL** [comment]
I would also add a "regression" tag, since it really works in the 1.1.17 build, but not in the current versions.

**Comment by F1ReB4LL** [comment]
Unexpected, but this one seems to be also affected by the https://github.com/Ryujinx/Ryujinx/pull/3302
Works properly in 1.1.106, but has started to either flicker or crash on the first logo when not flickering in 1.1.107

[Ryujinx_1.1.107_2022-08-30_05-04-08.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9448986/Ryujinx_1.1.107_2022-08-30_05-04-08.log)

**Comment by EmulationFanatic** [comment]
As of 1.1.320, game version 1.0.0 boots and goes in-game, but the latest version (1.0.3) crashes in early splashes.

**Comment by F1ReB4LL** [comment]
> As of 1.1.320, game version 1.0.0 boots and goes in-game, but the latest version (1.0.3) crashes in early splashes.

Nope, flickers like crazy and crashes for me like before (and now it is always flickering, sometimes it wasn't in earlier versions). See the attached video.

[bandicam 2022-10-21 02-21-27-321.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/9834530/bandicam.2022-10-21.02-21-27-321.zip)
[Ryujinx_1.1.320_2022-10-21_02-21-00.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9834531/Ryujinx_1.1.320_2022-10-21_02-21-00.log)

**Comment by EmulationFanatic** [comment]
You can say "nope" all you want, here is version 1.0.0 in-game on 1.1.320. It's not very stable, but "goes in-game" is still an accurate status.
![2022-10-20 17_56_48-Ryujinx 1 1 320 - Shadow Gangs v1 0 0 (0100BE501382A000) (64-bit)](https://user-images.githubusercontent.com/62343878/197080901-a5300006-4813-4a08-b3f9-6fa1ff8db7bd.png)

It's possible some differences in the respective NVIDIA drivers are the reason we're seeing different behaviors.
The flickering is random, as are the missing graphics at the title screen. Sometimes it happens, sometimes it doesn't. The game isn't marked playable, in any case.

**Comment by F1ReB4LL** [comment]
1.1.970 - Same behavior (flickering + crashes prior to ingame), but the error text differs:
```
GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x00000000003C0000
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 137
   at Ryujinx.Graphics.Gpu.Image.Texture.FlushTextureDataToGuest(Boolean tracked, ITexture texture) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 1021
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.<>c__DisplayClass50_0.<FlushModified>b__0(Int32 baseHandle, Int32 regionCount, Boolean split) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 535
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.FlushModified(Texture texture, Boolean tracked)
   at Ryujinx.Graphics.Gpu.Image.AutoDeleteCache.RemoveLeastUsedTexture() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\AutoDeleteCache.cs:line 130
   at Ryujinx.Graphics.Gpu.Engine.Twod.TwodClass.PixelsFromMemorySrcY0Int(Int32 argument) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Twod\TwodClass.cs:line 231
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 206
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__79_0() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 450
   at System.Threading.Thread.StartCallback()
```
[Ryujinx_1.1.970_2023-07-31_02-13-54.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/12210336/Ryujinx_1.1.970_2023-07-31_02-13-54.zip)

**Comment by F1ReB4LL** [comment]
Finally fixed in 1.1.1288 by https://github.com/Ryujinx/Ryujinx/pull/6687 (the version on the screenshots below is 1.0.3)

![ryujinx_sga1](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/c0e1e678-3e16-40e5-9e82-ad8d0ec823d2)
![ryujinx_sga2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/f3ed4a25-bf2a-4c89-9632-13429c61dd95)
![ryujinx_sga3](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/ff919e47-cc48-4a1b-8541-d02484a2d428)
![ryujinx_sga4](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/e055612d-c7c6-414e-8ec0-ba63a5152395)
![ryujinx_sga5](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/dc11aee3-e1b2-43e3-82dd-b8be61204033)
![ryujinx_sga6](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/e7d31d99-1f37-483f-a9fb-d6c37ec29cd1)
![ryujinx_sga7](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/78b223e5-23a0-4897-8ec6-6ec70629f120)
