### ISSUE TITLE
Construction Simulator 3 - Console Edition - 0100A5600FAC0000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3272]
#### Current on `master` : 1.0.6407

Crashes in early splash screens.

```
Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 10

Guest Stack Trace:
Process: Service, PID: 82

Buffer Information:
	PtrBuff:
	[0] Position: 0x0000006556c00000 Size: 0x0000000000000017
	[1] Position: 0x0000000000000000 Size: 0x0000000000000000
	SendBuff:
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
	ReceiveBuff:
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
	RecvListBuff:
	Position: 0x0000006556c00000 Size: 0x0000000000000200

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0A 00 00 00 00 00 00 00   SFCI············
00000010   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  00 02 00 00               ············    

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 148
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/642

#### Screenshots :

![2021-01-25 13_47_17-Ryujinx 1 0 6407 - Construction Simulator 3 - Console Edition v1 1 2 (0100A5600F](https://user-images.githubusercontent.com/62343878/105764328-0868c280-5f14-11eb-8670-36faec573415.png)

#### Log file :

[CS3CE.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5869571/CS3CE.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Sherm1984** [comment]
Game totally fine up to this point, then the ground flickers and you get photos below. Same result Vulkan and opengl. included vulkan and opengl logs

![2023-02-06 (1)](https://user-images.githubusercontent.com/39433024/216935376-cae7828c-d90e-4146-908c-ed039cd0f6f3.png)
[Ryujinx_1.1.601_2023-02-06_09-20-10.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10661601/Ryujinx_1.1.601_2023-02-06_09-20-10.log)
[Ryujinx_1.1.601_2023-02-06_09-23-41.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10661602/Ryujinx_1.1.601_2023-02-06_09-23-41.log)

![2023-02-06 (2)](https://user-images.githubusercontent.com/39433024/216935379-07d042ae-7afc-489d-9d78-691bb4f751ae.png)
![2023-02-06](https://user-images.githubusercontent.com/39433024/216935381-16b4ceab-2bd4-4296-a410-50c2ed2e2055.png)
