### ISSUE TITLE
The Last Campfire - 0100449011506000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3286]
#### Current on `master` : 1.0.6455

Crashes a minute in to a new game.

```
HLE.GuestThread.18 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x000559c0 Sub000000000da2a9c0
   sdk:0x00055a88 Sub000000000da2aa88
   sdk:0x00055b20 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   sdk:0x000d5f08 nn::os::detail::InternalConditionVariableImplByHorizon::Wait(nn::os::detail::InternalCriticalSection*)
   sdk:0x000cd898 nn::os::AcquireSemaphore(nn::os::SemaphoreType*)
   main:0x02740f00 Sub000000000a744f00
   sdk:0x000d4ec4 Sub000000000daa9ec4
   ??? Sub0000000000000000


00:03:26.027 |W| HLE.GuestThread.19 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.40 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.43 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.17 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.22 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.50 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.38 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.52 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.44 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.42 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.37 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.36 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.35 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.34 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.33 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.32 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.31 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.30 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.29 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.28 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.27 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.26 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.25 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.24 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.23 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.21 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.20 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.16 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:03:26.027 |W| HLE.GuestThread.39 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:03:26.055 |E| HLE.GuestThread.18 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 37
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 139
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2021-01-31 04_25_57-Ryujinx 1 0 6455 - The Last Campfire v1 0 0 (0100449011506000) (64-bit)](https://user-images.githubusercontent.com/62343878/106382517-57cc4a00-637d-11eb-9d0e-d5bacd4752cc.png)
![2021-01-31 04_26_42-Ryujinx 1 0 6455 - The Last Campfire v1 0 0 (0100449011506000) (64-bit)](https://user-images.githubusercontent.com/62343878/106382518-58fd7700-637d-11eb-9097-5851bc267ee9.png)
![2021-01-31 04_31_31-Ryujinx 1 0 6455 - The Last Campfire v1 0 0 (0100449011506000) (64-bit)](https://user-images.githubusercontent.com/62343878/106382521-5ac73a80-637d-11eb-8b99-e328420f4f68.png)

#### Log file :

[TLC.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5899601/TLC.log)

**Comment by F1ReB4LL** [comment]
Same issue on 1.1.200, but the error lines have changed, so, attaching the current log. Also the game is playable, you can run the game again after the crash and continue to play.

[Ryujinx_1.1.200_2022-08-01_05-18-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9237822/Ryujinx_1.1.200_2022-08-01_05-18-28.log)

**Comment by EmulationFanatic** [comment]
Updated
