### ISSUE TITLE
Spinny's journey - 01001E40136FE000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3287]
#### Current on `master` : 1.0.6455

Controller input doesn't seem to work in Docked mode (thoguh using a keyboard for input will get around this). Handheld mode works fine for all input.
Otherwise played smoothly until it crashed a couple of minutes in to gameplay.

```
00:02:17.106 |I| HLE.GuestThread.19 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x00144a04 Sub000000000b62da04
   sdk:0x00144b78 Sub000000000b62db78
   sdk:0x00343fb8 nn::os::detail::InternalConditionVariableImplByHorizon::Wait(nn::os::detail::InternalCriticalSection*)
   sdk:0x0033b918 nn::os::AcquireSemaphore(nn::os::SemaphoreType*)
   main:0x008f8e98 Sub00000000088fce98
   main:0x008f7e5c Sub00000000088fbe5c
   main:0x005303fc Sub00000000085343fc
   sdk:0x0033e7a8 Sub000000000b8277a8
   sdk:0x00342f74 Sub000000000b82bf74
   ??? Sub0000000000000000

00:02:17.107 |W| HLE.GuestThread.17 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.107 |W| HLE.GuestThread.39 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.107 |W| HLE.GuestThread.20 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.107 |W| HLE.GuestThread.44 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.107 |W| HLE.GuestThread.21 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.107 |W| HLE.GuestThread.41 KernelSvc PrintResult: SendSyncRequest64 returned error ThreadTerminating.
00:02:17.107 |W| HLE.GuestThread.22 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.40 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.23 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.38 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.24 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.37 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.36 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.25 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.35 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.26 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.34 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.27 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.33 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.28 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.32 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.29 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.31 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.30 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.18 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.42 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.16 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:02:17.108 |W| HLE.GuestThread.46 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.148 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 37
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 139
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2021-01-31 04_34_42-Ryujinx 1 0 6455 - Spinny's journey v1 0 1 (01001E40136FE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106382693-8696f000-637e-11eb-9a1e-df96b59151aa.png)
![2021-01-31 04_35_09-Ryujinx 1 0 6455 - Spinny's journey v1 0 1 (01001E40136FE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106382694-872f8680-637e-11eb-93c4-416e7a7fb078.png)
![2021-01-31 04_36_17-Ryujinx 1 0 6455 - Spinny's journey v1 0 1 (01001E40136FE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106382699-8eef2b00-637e-11eb-8f4c-5b83cac5dd60.png)
![2021-01-31 04_38_56-Ryujinx 1 0 6455 - Spinny's journey v1 0 1 (01001E40136FE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106382701-94e50c00-637e-11eb-962b-87c9a3870cfa.png)
![2021-01-31 04_39_09-Ryujinx 1 0 6455 - Spinny's journey v1 0 1 (01001E40136FE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106382710-a0383780-637e-11eb-8a6e-8a30bf7ad3dd.png)
![2021-01-31 04_39_26-Ryujinx 1 0 6455 - Spinny's journey v1 0 1 (01001E40136FE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106382717-aaf2cc80-637e-11eb-991a-f4b93a36fac8.png)
![2021-01-31 04_39_34-Ryujinx 1 0 6455 - Spinny's journey v1 0 1 (01001E40136FE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106382727-b6de8e80-637e-11eb-8fd1-fe26a515e007.png)
![2021-01-31 04_39_46-Ryujinx 1 0 6455 - Spinny's journey v1 0 1 (01001E40136FE000) (64-bit)](https://user-images.githubusercontent.com/62343878/106382735-be059c80-637e-11eb-886d-786796db5557.png)

#### Log file :

[Sj.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5899626/Sj.zip)

**Comment by benderscruffy** [comment]
using 1.0.7112
controller input works in Docked mode now
played game for a while and didn't crash out
