### ISSUE TITLE
Bus Driver Simulator - 010030D012FF6000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3301]
#### Current on `master` : 1.0.6455

Loaded and played through the tutorial without issues, but crashed when trying to load a career.

```
00:09:48.708 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x275EAF000..0x275F0F000 is not fully mapped.
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 325
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 746
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(CopyTexture copyTexture, FormatInfo formatInfo, Boolean preferScaling, Nullable`1 sizeHint) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 506
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyTexture(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyTexture.cs:line 105
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2021-01-31 07_07_37-Ryujinx 1 0 6455 - Bus Driver Simulator v1 0 0 (010030D012FF6000) (64-bit)](https://user-images.githubusercontent.com/62343878/106386894-66722b80-6394-11eb-8096-329b609f109e.png)
![2021-01-31 07_07_52-Ryujinx 1 0 6455 - Bus Driver Simulator v1 0 0 (010030D012FF6000) (64-bit)](https://user-images.githubusercontent.com/62343878/106386895-670ac200-6394-11eb-9387-53cc3ca60e49.png)
![2021-01-31 07_09_28-Ryujinx 1 0 6455 - Bus Driver Simulator v1 0 0 (010030D012FF6000) (64-bit)](https://user-images.githubusercontent.com/62343878/106386901-6d993980-6394-11eb-831c-861536e2efb6.png)
![2021-01-31 07_10_00-Ryujinx 1 0 6455 - Bus Driver Simulator v1 0 0 (010030D012FF6000) (64-bit)](https://user-images.githubusercontent.com/62343878/106386906-7558de00-6394-11eb-8b8a-6b0fecb3d6ae.png)
![2021-01-31 07_12_33-Ryujinx 1 0 6455 - Bus Driver Simulator v1 0 0 (010030D012FF6000) (64-bit)](https://user-images.githubusercontent.com/62343878/106386914-7db11900-6394-11eb-95d9-043e77efdbb1.png)
![2021-01-31 07_14_06-Ryujinx 1 0 6455 - Bus Driver Simulator v1 0 0 (010030D012FF6000) (64-bit)](https://user-images.githubusercontent.com/62343878/106386920-873a8100-6394-11eb-992a-c0a2f68207c5.png)

#### Log file :

[BDS.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5899895/BDS.log)

**Comment by EmulationFanatic** [comment]
Updated
