### ISSUE TITLE
Blade II The Return of Evil - 01009cc00e224000

### ISSUE THREAD

**Issue by sreport** [Ryujinx/Ryujinx-Games-List#3302]
## Game Name
**Blade II The Return of Evil**
#### Current on `master` : *1.0.6473*
Game loads fine, plays "ok" with little hiccups here and there, you can play for some minutes, then it crashes with an Audio error.
Resolution scaler seems not to be working correctly.

```
Last error returned.
00:05:34.442 |E| HLE.OsThread.7 AudioRenderer Update: Unmap of memory pool (address: 0x1050340000, size 0x729000) failed!
00:07:52.166 |E| AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.DataSourceHelper.ProcessWaveBuffers(IVirtualMemoryManager memoryManager, Span`1 outputBuffer, WaveBufferInformation info, UInt32 targetSampleRate, Int32 sampleCount) in C:\projects\ryujinx\Ryujinx.Audio.Renderer\Dsp\DataSourceHelper.cs:line 70
   at Ryujinx.Audio.Renderer.Dsp.Command.AdpcmDataSourceCommandVersion1.Process(CommandList context) in C:\projects\ryujinx\Ryujinx.Audio.Renderer\Dsp\Command\AdpcmDataSourceCommandVersion1.cs:line 76
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(HardwareDevice outputDevice) in C:\projects\ryujinx\Ryujinx.Audio.Renderer\Dsp\Command\CommandList.cs:line 98
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in C:\projects\ryujinx\Ryujinx.Audio.Renderer\Dsp\AudioProcessor.cs:line 191
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![BD1](https://user-images.githubusercontent.com/78411102/106578938-b45a7100-6505-11eb-93c7-d81e72edcc24.jpg)
![BD2](https://user-images.githubusercontent.com/78411102/106578972-bfad9c80-6505-11eb-9819-e2c5b562b464.jpg)
![BD3](https://user-images.githubusercontent.com/78411102/106578981-c20ff680-6505-11eb-9ef2-9c04f2ba4c7f.jpg)

#### Log file :
[Ryujinx_1.0.6473_2021-02-02_02-43-47.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5909953/Ryujinx_1.0.6473_2021-02-02_02-43-47.log)

**Comment by EmulationFanatic** [comment]
Thanks for the report!

**Comment by sreport** [comment]
yw, also might want to add UE4 label too, since game is on that engine.

**Comment by EmulationFanatic** [comment]
> yw, also might want to add UE4 label too, since game is on that engine.

Done

**Comment by benderscruffy** [comment]
using 1.0.7104
doesn't crash out now with audio error
