### ISSUE TITLE
Re:ZERO -Starting Life in Another World- The Prophecy of the Throne

### ISSUE THREAD

**Issue by Niwu34** [Ryujinx/Ryujinx-Games-List#3308]
#### Current on `master` :  *1.0.6471*

*The game does boot for me: The update is needed! (Crashes otherwise)
The issue is that it is not rendering anything - The screen stays black.
You can hear the sound of the game and interact with it *

```
Last error returned.
No Error as i closed the game myself!
```

#### Screenshots :
https://user-images.githubusercontent.com/67392333/107130428-ad4cad80-68cd-11eb-99f2-a3c76854c911.mp4

#### Log file :
[Ryujinx_1.0.6471_2021-02-06_22-30-42.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5937741/Ryujinx_1.0.6471_2021-02-06_22-30-42.log)

**Comment by jayzakk** [comment]
Experiencing a full crash with 1.0.6551:

```
00:00:57.413 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4912B (sRGB: False).
00:00:57.490 |E| GUI.RenderLoop Gpu GetInfo: Invalid texture format 0x4912B (sRGB: False).
...
00:01:09.166 |E| GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:01:09.180 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 292
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 545
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 444
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 285
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 103
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 56
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(IGpuAccessor gpuAccessor, Block block, UInt64 limitAddress, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 255
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(IGpuAccessor gpuAccessor, UInt64 startAddress) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 87
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, TranslationCounts counts, ShaderConfig& config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 118
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetComputeShader(GpuState state, UInt64 gpuVa, Int32 localSizeX, Int32 localSizeY, Int32 localSizeZ, Int32 localMemorySize, Int32 sharedMemorySize) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 359
   at Ryujinx.Graphics.Gpu.Engine.Methods.Dispatch(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Compute.cs:line 31
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 404
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

Full log: [Ryujinx_1.0.6551_2021-02-13_02-58-14.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5974965/Ryujinx_1.0.6551_2021-02-13_02-58-14.log)

**Comment by Niwu34** [comment]
Same status as before (I also checked it with the lastets update Game Version whichis 1.0.2)

**Comment by F1ReB4LL** [comment]
1.1.272 - Black screen + sounds with OpenGL (like before), instant crash with Vulkan:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.             
at Silk.NET.Vulkan.Vk.CreateComputePipelines(Silk.NET.Vulkan.Device, Silk.NET.Vulkan.PipelineCache, UInt32, Silk.NET.Vulkan.ComputePipelineCreateInfo*, Silk.NET.Vulkan.AllocationCallbacks*, Silk.NET.Vulkan.Pipeline*)                                                                                                    
at Ryujinx.Graphics.Vulkan.PipelineState.CreateComputePipeline(Ryujinx.Graphics.Vulkan.VulkanRenderer, Silk.NET.Vulkan.Device, Ryujinx.Graphics.Vulkan.ShaderCollection, Silk.NET.Vulkan.PipelineCache)                                                                                                                     
at Ryujinx.Graphics.Vulkan.ShaderCollection.CreateBackgroundComputePipeline()                                                                                 
at Ryujinx.Graphics.Vulkan.ShaderCollection+<BackgroundCompilation>d__35.MoveNext()                                                                           
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Ryujinx.Graphics.Vulkan.ShaderCollection+<BackgroundCompilation>d__35, Ryujinx.Graphics.Vulkan, Version=1.1.272.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)                                                                  
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)                          
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Ryujinx.Graphics.Vulkan.ShaderCollection+<BackgroundCompilation>d__35, Ryujinx.Graphics.Vulkan, Version=1.1.272.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)                                                                        
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Ryujinx.Graphics.Vulkan.ShaderCollection+<BackgroundCompilation>d__35, Ryujinx.Graphics.Vulkan, Version=1.1.272.0, Culture=neutral, PublicKeyToken=null]].MoveNext()                                                                                               
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)                           
at System.Threading.Tasks.Task.RunContinuations(System.Object)                                                                                                
at System.Threading.Tasks.Task.TrySetResult()                                                                                                                 
at System.Threading.Tasks.Task+WhenAllPromise.Invoke(System.Threading.Tasks.Task)                                                                             
at System.Threading.Tasks.Task.RunOrQueueCompletionAction(System.Threading.Tasks.ITaskCompletionAction, Boolean)                                              
at System.Threading.Tasks.Task.RunContinuations(System.Object)                                                                                                
at System.Threading.Tasks.Task.FinishStageThree()                                                                                                             
at System.Threading.Tasks.Task.FinishStageTwo()                                                                                                               
at System.Threading.Tasks.Task.Finish(Boolean)                                                                                                                
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)                                             
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)                                                                                    
at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)                                                                                 
at System.Threading.ThreadPoolWorkQueue.Dispatch()                                                                                                            
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()                                                                                       
at System.Threading.Thread+StartHelper.RunWorker()                                                                                                            
at System.Threading.Thread+StartHelper.Run()                                                                                                                  
at System.Threading.Thread.StartCallback()                                  
```

**Comment by EmulationFanatic** [comment]
Same status on 1.1.326

**Comment by Cronos-0** [comment]
ot much has changed in the latest version. The game still doesn't render in Opengl (only hears audio), is interactive, and the game doesn't crash. For Vulkan, the game crashes immediately after booting with an error not showing up in the logs (see image below) // Build 1.1.650 // Update 1.0.2

OpenGl

![bandicam 2023-03-07 08-39-29-949](https://user-images.githubusercontent.com/35269098/223299074-92fcb18e-96ce-4c98-a11c-b35a580745bb.jpg)

VulKan

![bandicam 2023-03-07 08-40-54-169](https://user-images.githubusercontent.com/35269098/223299145-12bd91cb-bbf5-4283-a5be-1c85be6be693.jpg)

**Comment by amayra** [comment]
can you post log file please

**Comment by Cronos-0** [comment]
@amayra The error is not shown in the logs and is the same problem tested as others. it may not be necessary
