### ISSUE TITLE
Disjunction - 01000B70122A2000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3323]
#### Current on `master` : 1.0.6521

Game loads and plays at a high FPS.

#### Screenshots :

![2021-02-08 13_18_56-Ryujinx 1 0 6521 - Disjunction v1 0 0 (01000B70122A2000) (64-bit)](https://user-images.githubusercontent.com/62343878/107277180-4c2df280-6a11-11eb-9f57-6f61488cdbe6.png)
![2021-02-08 13_19_20-Ryujinx 1 0 6521 - Disjunction v1 0 0 (01000B70122A2000) (64-bit)](https://user-images.githubusercontent.com/62343878/107277182-4cc68900-6a11-11eb-9f6f-ee4677be89af.png)
![2021-02-08 13_20_15-Ryujinx 1 0 6521 - Disjunction v1 0 0 (01000B70122A2000) (64-bit)](https://user-images.githubusercontent.com/62343878/107277185-4d5f1f80-6a11-11eb-9491-7754568f4c10.png)
![2021-02-08 13_21_06-Ryujinx 1 0 6521 - Disjunction v1 0 0 (01000B70122A2000) (64-bit)](https://user-images.githubusercontent.com/62343878/107277187-4df7b600-6a11-11eb-94a4-ede5f9d79902.png)
![2021-02-08 13_21_27-Ryujinx 1 0 6521 - Disjunction v1 0 0 (01000B70122A2000) (64-bit)](https://user-images.githubusercontent.com/62343878/107277189-4f28e300-6a11-11eb-901f-16b958772d3c.png)
![2021-02-08 13_22_11-Ryujinx 1 0 6521 - Disjunction v1 0 0 (01000B70122A2000) (64-bit)](https://user-images.githubusercontent.com/62343878/107277196-50f2a680-6a11-11eb-8e3d-10743d109501.png)
![2021-02-08 13_23_31-Ryujinx 1 0 6521 - Disjunction v1 0 0 (01000B70122A2000) (64-bit)](https://user-images.githubusercontent.com/62343878/107277200-518b3d00-6a11-11eb-84b3-73100f5b522d.png)
![2021-02-08 13_24_20-Ryujinx 1 0 6521 - Disjunction v1 0 0 (01000B70122A2000) (64-bit)](https://user-images.githubusercontent.com/62343878/107277204-52bc6a00-6a11-11eb-8242-b5721deda08a.png)

#### Log file :

[Disjunction.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/5946642/Disjunction.zip)

**Comment by F1ReB4LL** [comment]
## Disjunction

#### Game Update Version : *1.0.1*

#### Current on `master` : *1.1.213*

#### Graphics Backend : *Both Vulkan and OpenGL*

*Serious video issues. OpenGL: Many sprites are covered with cyan rectangles. Vulkan: no cyan rectangles, but some sprites are cut the same way as if they were covered (look at the bodies on the screenshots). Regression?*

```
Last error returned: No errors shown
```

#### Hardware Specs : 

##### CPU: *i5-11400H*
##### GPU: *NVIDIA RTX 3050*
##### RAM: *24GB*

#### Screenshots :

OpenGL:
![ryujinx_disj1](https://user-images.githubusercontent.com/39680140/184465910-9c54466e-7cec-441b-b002-6a324ad3bc5b.png)
![ryujinx_disj2](https://user-images.githubusercontent.com/39680140/184465912-ba18da62-0596-4572-8b86-e2f101378240.png)

Vulkan:
![ryujinx_disj3](https://user-images.githubusercontent.com/39680140/184465914-d05804d6-d1c1-4bf1-bed3-a430366a2fb4.png)
![ryujinx_disj4](https://user-images.githubusercontent.com/39680140/184465915-ab0e5bec-03f9-4bd6-8b7b-4405d4974684.png)

**Comment by F1ReB4LL** [comment]
Should I maybe create new reports for regression cases? It seems the comments for the "status-playable" games are mostly ignored (This one, Everspace, Katana Zero, maybe more, don't remember already).

**Comment by EmulationFanatic** [comment]
> Should I maybe create new reports for regression cases? It seems the comments for the "status-playable" games are mostly ignored (This one, Everspace, Katana Zero, maybe more, don't remember already).

That isn't necessary. However, what you're suggesting is that we are selectively letting games with regressions remain in a favorable state for presumably dishonest purposes. The simple fact is that we can't always keep up with user submitted reports. 
If you know of any other games that have regressed (aside from the ones you listed above), feel free to reach out to a staff member.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by F1ReB4LL** [comment]
Broken in 1.1.107 by https://github.com/Ryujinx/Ryujinx/pull/3302

![ryujinx_disj11106](https://user-images.githubusercontent.com/39680140/185744249-db2b28bf-deac-49f8-9372-0ba2bc167505.png)
![ryujinx_disj11107](https://user-images.githubusercontent.com/39680140/185744254-6d82d792-0b85-44dc-b132-49688c440812.png)

**Comment by F1ReB4LL** [comment]
Fixed in 1.1.1288 by https://github.com/Ryujinx/Ryujinx/pull/6687

![ryujinx_disj11287](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/c67d6f52-c744-4f04-8e0c-76830fb4ac5a)
![ryujinx_disj11288](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/691123f2-f69c-4662-bd3b-17d8e1c83d9e)

**Comment by F1ReB4LL** [comment]
While running the game using the OpenGL rendering, closing the emulator triggers some error (doesn't happen with Vulkan renderer):

![crash](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/8fd5b644-4459-4908-bb62-e6f765810a2e)

```
GUI.WindowThread UI MakeCurrent: Failed to bind OpenGL context: SPB.Graphics.Exceptions.ContextException: MakeCurrent() failed with error 0xaa
   at SPB.Platform.WGL.WGLOpenGLContext.MakeCurrent(NativeWindowBase window)
   at Ryujinx.Ava.UI.Renderer.EmbeddedWindowOpenGL.MakeCurrent(Boolean unbind, Boolean shouldThrow) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\UI\Renderer\EmbeddedWindowOpenGL.cs:line 69
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at OpenTK.Graphics.OpenGL.GL.DeleteFramebuffer(Int32)
   at Ryujinx.Graphics.OpenGL.Image.TextureCopy.Dispose()
   at Ryujinx.Graphics.OpenGL.OpenGLRenderer.Dispose()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.Dispose()
   at Ryujinx.Graphics.Gpu.GpuContext.Dispose()
   at Ryujinx.HLE.Switch.DisposeGpu()
   at Ryujinx.Ava.AppHost.DisposeGpu()
   at Ryujinx.Ava.AppHost.DisposeContext()
   at Ryujinx.Ava.UI.ViewModels.MainWindowViewModel.InitializeGame()
   at System.Threading.Thread+StartHelper.RunWorker()
   at System.Threading.Thread+StartHelper.Run()
   at System.Threading.Thread.StartCallback()
```
[Ryujinx_1.1.1294_2024-04-29_02-34-01.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/15144245/Ryujinx_1.1.1294_2024-04-29_02-34-01.log)
