### ISSUE TITLE
Super Mario 3D World™ + Fury World

### ISSUE THREAD

**Issue by teszNU** [Ryujinx/Ryujinx-Games-List#3349]
#### Current on `master` : Commit Id *or* Build Version : 1.0.6540

runtime only fine inside main title screen, sm3dw title screen to select player, try play games with stuck and crash. graphics very slow.

```
00:02:01.463 |I| HLE.OsThread.5 ServicePrepo ProcessReport: 
PlayReport log:
 Room: erepo_region
 Report: {
    "Region": 0,
    "Language": 0,
    "StandardTimeName": "UTC",
    "UtcOffsetSeconds": 0,
    "system_report_tag": 2759414308
}

00:02:01.559 |E| HLE.OsThread.5 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Prepo.IPrepoService: 10400

Guest Stack Trace:
Process: Service, PID: 82

Raw Request Data:
00000000   01 00 10 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  A0 28 00 00 00 00 00 00   SFCI···· (······
00000020   05 00 01 00 00 00 00 00                            ········        

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 148
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :
![STD1](https://user-images.githubusercontent.com/61547678/107534943-4562d380-6bfb-11eb-9ffb-d755f1ceb1dc.png)
![STD2](https://user-images.githubusercontent.com/61547678/107534340-c53c6e00-6bfa-11eb-8118-9b2803fee5a2.png)
![STD3](https://user-images.githubusercontent.com/61547678/107534371-cbcae580-6bfa-11eb-9c19-ae71ca6bdd19.png)

#### Log file :
[Ryujinx_1.0.6540_2021-02-10_23-28-38.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5959447/Ryujinx_1.0.6540_2021-02-10_23-28-38.log)
[Ryujinx_1.0.6540_2021-02-10_23-44-55.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5959450/Ryujinx_1.0.6540_2021-02-10_23-44-55.log)

**Comment by EmulationFanatic** [comment]
This game has not been released yet and as such is an indicator of participation in piracy.
