### ISSUE TITLE
Scribblenauts Mega Pack

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#336]
#### Current on `master` : 1.0.3975

Game crashes as it is loading title screen.

```
HLE.HostThread.10 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000080ca4a0 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1132
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 127
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 70
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 96
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1144
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 162
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-03-24 07_44_48-Ryujinx 1 0 3975 _ Scribblenauts Mega Pack _ 0100E7100B198000](https://user-images.githubusercontent.com/62343878/77432272-751aaa00-6da3-11ea-8e47-e0addf19457c.png)
![2020-03-24 07_44_51-Ryujinx 1 0 3975 _ Scribblenauts Mega Pack _ 0100E7100B198000](https://user-images.githubusercontent.com/62343878/77432279-78ae3100-6da3-11ea-9ef3-a9d8986a6a3d.png)
![2020-03-24 07_44_55-](https://user-images.githubusercontent.com/62343878/77432285-7a77f480-6da3-11ea-9f02-fa2731a3b047.png)

#### Log file :

[ScribblenautsMegaPack.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4375575/ScribblenautsMegaPack.zip)

**Comment by EmulationFanatic** [comment]
Updated
