### ISSUE TITLE
Scribblenauts Showdown

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#337]
#### Current on `master` : 1.0.3975

Game crashes as it is loading title screen. The first time, the console displayed a memory access violation that did not show up in the log. The second time, it showed the error below in the log.

```
Unhandled exception. Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000084309b8 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1132
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 127
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 70
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 96
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1144
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 162
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-03-24 07_47_56-Ryujinx 1 0 3975 _ Scribblenauts Showdown _ 01001E40041BE000](https://user-images.githubusercontent.com/62343878/77432583-e2c6d600-6da3-11ea-954a-67a219c96344.png)
![2020-03-24 07_48_04-Ryujinx 1 0 3975 _ Scribblenauts Showdown _ 01001E40041BE000](https://user-images.githubusercontent.com/62343878/77432591-e5c1c680-6da3-11ea-8954-43a1c4e1f93d.png)
![2020-03-24 07_48_06-Ryujinx 1 0 3975 _ Scribblenauts Showdown _ 01001E40041BE000](https://user-images.githubusercontent.com/62343878/77432593-e65a5d00-6da3-11ea-9532-024d631e8390.png)

#### Log file :
[ScribblenautsShowdown.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4375618/ScribblenautsShowdown.zip)

**Comment by EmulationFanatic** [comment]
Updated
