### ISSUE TITLE
Get Over Here

### ISSUE THREAD

**Issue by jayzakk** [Ryujinx/Ryujinx-Games-List#3370]
#### Current on `master` : Build Version : *1.0.6551*

Starts up, no glitches, playable. But at some random point (in menu, in game, ...) crashes.

```
00:03:53.827 |I| HLE.GuestThread.19 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x00054e10 Sub000000000c402e10
   sdk:0x00054ed8 Sub000000000c402ed8
   sdk:0x00054f70 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   sdk:0x000d5358 nn::os::detail::InternalConditionVariableImplByHorizon::Wait(nn::os::detail::InternalCriticalSection*)
   sdk:0x000ccce8 nn::os::AcquireSemaphore(nn::os::SemaphoreType*)
   main:0x01ab792c Sub0000000009abb92c
...
00:03:53.845 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 37
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 139
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :

Logfile (large...): https://shuuichi.jav.net/getoverhere-full.log.gz
And stripped down: [getoverhere-stripped.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5974938/getoverhere-stripped.log)

*(Optional section, remove it if unneeded)*

**Comment by EmulationFanatic** [comment]
Thanks for the test!

**Comment by EmulationFanatic** [comment]
Updated
