### ISSUE TITLE
Unspottable

### ISSUE THREAD

**Issue by jayzakk** [Ryujinx/Ryujinx-Games-List#3371]
#### Current on `master` : Build Version : *1.0.6551*

Playable without glitches, until it crashes (randomly).

```
00:08:52.164 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 26!
00:08:56.874 |I| HLE.OsThread.5 ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:08:57.230 |I| HLE.OsThread.10 ServiceNv Create: Created map 26 with size 0x01000000!
00:08:57.273 |I| HLE.GuestThread.19 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   sdk:0x00144a04 Sub000000000c9d4a04
   sdk:0x00144b78 Sub000000000c9d4b78
   sdk:0x00343fb8 nn::os::detail::InternalConditionVariableImplByHorizon::Wait(nn::os::detail::InternalCriticalSection*)
   sdk:0x0033b918 nn::os::AcquireSemaphore(nn::os::SemaphoreType*)
   main:0x009cdec8 Sub00000000089d1ec8
   main:0x009cce8c Sub00000000089d0e8c
   main:0x00603f1c Sub0000000008607f1c
   sdk:0x0033e7a8 Sub000000000cbce7a8
   sdk:0x00342f74 Sub000000000cbd2f74
   ??? Sub0000000000000000
...
00:08:57.302 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 37
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 139
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Screenshots :
![grafik](https://user-images.githubusercontent.com/4440984/107839268-fc518180-6daa-11eb-881c-b314a09bd78d.png)
![grafik](https://user-images.githubusercontent.com/4440984/107839292-260aa880-6dab-11eb-9194-d72adb42206a.png)
![grafik](https://user-images.githubusercontent.com/4440984/107839307-3e7ac300-6dab-11eb-8269-e7e0d3678d02.png)

#### Log file :
[Ryujinx_1.0.6551_2021-02-13_03-06-39.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5975024/Ryujinx_1.0.6551_2021-02-13_03-06-39.log)

**Comment by EmulationFanatic** [comment]
Updated
