### ISSUE TITLE
STORY OF SEASONS Pioneers of Olive [ 牧場物語 オリーブタウンと希望の大地 ] - 010017301007E000

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#3416]
#### Current on `master` : 1.0.6714

Load and play at full speed.

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2021-02-25 23-54-29-438](https://user-images.githubusercontent.com/35269098/109191459-c78cf380-77c8-11eb-990d-77d40715a48c.jpg)
![bandicam 2021-02-25 23-55-01-170](https://user-images.githubusercontent.com/35269098/109191469-c9ef4d80-77c8-11eb-80a3-a370e9d06dd0.jpg)
![bandicam 2021-02-25 23-56-48-624](https://user-images.githubusercontent.com/35269098/109191485-cd82d480-77c8-11eb-9a8b-549fb8879b5a.jpg)
![bandicam 2021-02-25 23-59-53-092](https://user-images.githubusercontent.com/35269098/109191501-d2e01f00-77c8-11eb-8840-2e513ccecf2f.jpg)
![bandicam 2021-02-26 00-00-23-665](https://user-images.githubusercontent.com/35269098/109191512-d5db0f80-77c8-11eb-8c2e-6b2091b729bb.jpg)
![bandicam 2021-02-26 00-01-18-132](https://user-images.githubusercontent.com/35269098/109191532-db385a00-77c8-11eb-9992-533cebc15c00.jpg)
![bandicam 2021-02-26 00-01-59-982](https://user-images.githubusercontent.com/35269098/109191550-decbe100-77c8-11eb-9a51-78f9c6f3334d.jpg)
![bandicam 2021-02-26 00-07-42-079](https://user-images.githubusercontent.com/35269098/109191581-e4c1c200-77c8-11eb-8c39-b462b2d43933.jpg)
![bandicam 2021-02-26 00-10-23-197](https://user-images.githubusercontent.com/35269098/109191612-eab7a300-77c8-11eb-9ecd-b63cdc39f471.jpg)
![bandicam 2021-02-26 00-10-55-430](https://user-images.githubusercontent.com/35269098/109191625-ee4b2a00-77c8-11eb-9599-c867cab11067.jpg)
![bandicam 2021-02-26 00-11-58-624](https://user-images.githubusercontent.com/35269098/109191634-f0ad8400-77c8-11eb-8ac9-219bd294a1e6.jpg)
![bandicam 2021-02-26 00-12-42-751](https://user-images.githubusercontent.com/35269098/109191658-f5723800-77c8-11eb-9b73-b6266348c67a.jpg)
![bandicam 2021-02-26 00-14-18-089](https://user-images.githubusercontent.com/35269098/109191670-f86d2880-77c8-11eb-950d-9d091c0a3902.jpg)
![bandicam 2021-02-26 00-17-31-747](https://user-images.githubusercontent.com/35269098/109191715-028f2700-77c9-11eb-8c04-b8763e4fa08a.jpg)
![bandicam 2021-02-26 00-17-00-536](https://user-images.githubusercontent.com/35269098/109191727-0458ea80-77c9-11eb-8102-3f78fae47806.jpg)
![bandicam 2021-02-26 00-18-29-715](https://user-images.githubusercontent.com/35269098/109191741-0753db00-77c9-11eb-8784-a3849addb6f5.jpg)
![bandicam 2021-02-26 00-19-30-075](https://user-images.githubusercontent.com/35269098/109191814-1aff4180-77c9-11eb-807c-b30905e6cc4e.jpg)

**Comment by Dastano** [comment]
Mine just Crash, sadly.

`   main:0x025103b4 Sub000000000a5143b4
   main:0x023c8518 Sub000000000a3cc518
   main:0x000a9b64 Sub00000000080adb64
   main:0x00221a50 Sub0000000008225a50
   main:0x00285004 Sub0000000008289004
   main:0x00272de0 Sub0000000008276de0
   main:0x0090ad84 Sub000000000890ed84
   main:0x00472144 Sub0000000008476144
   main:0x003243e8 Sub00000000083283e8
   main:0x0032441c Sub000000000832841c
   main:0x00324744 Sub0000000008328744
   main:0x00270bbc nnMain
   sdk:0x002a3864 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
   rtld:0x000000d4 Sub00000000080000d4


00:00:39.711 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000028.
00:00:39.893 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 452
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 287
   at Ryujinx.Cpu.MemoryManager.ReadTracked[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 147
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 141
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

**Comment by pineappleEA** [comment]
It seems to work on the latest master
![image](https://user-images.githubusercontent.com/67879877/111620640-a891e800-87ef-11eb-86e1-2531e1e5bf8d.png)
Could you provide the full log?
