### ISSUE TITLE
Plants vs. Zombies: Battle for Neighborville Complete Edition - 0100C56010FD8000

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#3437]
#### Current on `master` : 1.0.6794

Game crashes at startup.

```
00:01:50.992 |E| HLE.GuestThread.35 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 174
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 141
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[PvZBfN.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6174194/PvZBfN.log)

**Comment by LukeWarnut** [comment]
Updated with tests of version 1.0.0.

**Comment by EmulationFanatic** [comment]
Basically the same status on 1.1.326. Slight differences are version 1.0.3 of the game boots to the title screen on OpenGL and then crashes. On Vulkan, the game crashes in splash screens before the title screen.

**Comment by Cronos-0** [comment]
Update to the latest version The game doesn't display properly. At least in the latest version, in the game menu page, you can see a little graphical rendering and the bottom text that it spam all the time. / Update 1.0.3 / Build 1.1.650

```
00:01:22.754 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Pixld is not implemented.
```

![bandicam 2023-03-05 07-58-08-006](https://user-images.githubusercontent.com/35269098/222936085-8afc61b9-361e-4fda-9d50-fe752ce7fba3.jpg)
![bandicam 2023-03-05 07-58-23-113](https://user-images.githubusercontent.com/35269098/222936087-55dd69f9-db45-49e2-815a-ecc151715997.jpg)
![bandicam 2023-03-05 07-58-32-224](https://user-images.githubusercontent.com/35269098/222936088-f15a85a9-b399-400f-8310-c6a0af415506.jpg)

Logs 

[Ryujinx_1.1.650_2023-03-05_07-56-03.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10890518/Ryujinx_1.1.650_2023-03-05_07-56-03.log)

**Comment by Ari-Memer** [comment]
Tested bfn on m1 macbook air and same results, just at 10 fps

**Comment by Lancelotking0** [comment]
Its possible to reach gameplay sections of the game now and I could control my character for a few seconds before the crash.Graphical rendering seems to have improved a bit, but its still impossible to tell what's going on in the game,the ui elements seem unaffected by these issues however, the game sometimes crashes at loading screens , or much further into initial gameplay section, also the right half of the screen has missing textures in comparison to the left. Version1.0.3. Build 1.1.1202
there seems to be an audio issue and (atleast)another issue causing crashes it seems 
![Screenshot (9)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/160503973/354642d1-30d6-422b-97da-63823cb84bc5)
![Screenshot (11)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/160503973/9953cff6-e592-40b7-88f5-49d5efe7adaa)
![Screenshot (12)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/160503973/83fbf7b1-81c2-4986-b02a-7cb914f6d1c9)
Logs:-
[Ryujinx_1.1.1202_2024-02-19_19-42-08.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14332431/Ryujinx_1.1.1202_2024-02-19_19-42-08.log)
[Ryujinx_1.1.1202_2024-02-19_19-52-09.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14332433/Ryujinx_1.1.1202_2024-02-19_19-52-09.log)
[Ryujinx_1.1.1202_2024-02-19_19-53-27.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14332434/Ryujinx_1.1.1202_2024-02-19_19-53-27.log)

**Comment by lostromb** [comment]
Might as well track boot issues under https://github.com/Ryujinx/Ryujinx/issues/7193

**Comment by Wokwokwok3000** [comment]
Is it still working on ? If it's not please make it happen 
Appreciate the work

**Comment by Wokwokwok3000** [comment]
PLEEEAAAASE MAKE IT PLAYABLE








appreciate the work btw

**Comment by chocoboxx** [comment]
Can someone fix the Plants vs Zombies game please?
<img width="960" alt="Sin título" src="https://github.com/user-attachments/assets/152ea818-2be7-4836-a914-95828a0d2278">

**Comment by lostromb** [comment]
> Can someone fix the Plants vs Zombies game please?

This game clearly needs a lot of work done for it to render anything properly and run without crashing. It likely will not be playable for a while. Please stop spamming the issue tracker unless you have something to contribute.

**Comment by Wokwokwok3000** [comment]
> > Can someone fix the Plants vs Zombies game please?
> 
> This game clearly needs a lot of work done for it to render anything properly and run without crashing. It likely will not be playable for a while. Please stop spamming the issue tracker unless you have something to contribute.

Srry
