### ISSUE TITLE
Wondershot

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#345]
#### Current on `master` : 1.0.3975

Crashes while loading the tutorial.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32 width, Int32 height, Int32 depth, Int32 levels, Int32 layers, Int32 blockWidth, Int32 blockHeight, Int32 bytesPerPixel, Int32 gobBlocksInY, Int32 gobBlocksInZ, Int32 gobBlocksInTileX, SizeInfo sizeInfo, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.Texture\LayoutConverter.cs:line 215
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 473
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 324
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(RtColorState colorState, Int32 samplesInX, Int32 samplesInY) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 387
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateRenderTargetState(GpuState state, Boolean useControl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 276
   at Ryujinx.Graphics.Gpu.Engine.Methods.Clear(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodClear.cs:line 60
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 74
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, GpuState shadowState, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 497
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 131
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 98
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 154
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 212
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 187
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 329
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-03-24 11_00_14-Ryujinx 1 0 3975 _ WonderShot _ 0100F5D00C812000](https://user-images.githubusercontent.com/62343878/77454933-d603ab80-6dbe-11ea-9c39-9c54eb396b32.png)
![2020-03-24 11_00_16-Ryujinx 1 0 3975 _ WonderShot _ 0100F5D00C812000](https://user-images.githubusercontent.com/62343878/77454937-d69c4200-6dbe-11ea-8bc1-d4de5bdec311.png)
![2020-03-24 11_00_31-Ryujinx 1 0 3975 _ WonderShot _ 0100F5D00C812000](https://user-images.githubusercontent.com/62343878/77454941-d734d880-6dbe-11ea-9db4-6231e6d05b37.png)
![2020-03-24 11_00_36-Ryujinx 1 0 3975 _ WonderShot _ 0100F5D00C812000](https://user-images.githubusercontent.com/62343878/77454961-de5be680-6dbe-11ea-946a-331c3056bb1c.png)

#### Log file :

[Wondershot.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4376649/Wondershot.zip)

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
