### ISSUE TITLE
Soccer Club Life: Playing Manager - 010017B012AFC000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3450]
#### Current on `master` : 1.0.6797

Crashed after trying to load for 10 minutes.

```
00:10:07.537 |I| HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: NewStarManager, PID: 92
   sdk:0x004f6258 __nnmusl_GetTlsValue
   sdk:0x004a8294 Sub000000000ae8c294
   subsdk0:0x0096183c Sub0000000009d0683c
   subsdk0:0x00a5711c Sub0000000009dfc11c
   subsdk0:0x00a56bfc Sub0000000009dfbbfc
   subsdk0:0x00a4c784 Sub0000000009df1784
   subsdk0:0x00a4ca44 Sub0000000009df1a44
   subsdk0:0x00a142ac Sub0000000009db92ac
   subsdk0:0x00a13cec Sub0000000009db8cec
   subsdk0:0x00a147d8 Sub0000000009db97d8
   subsdk0:0x009cd310 Sub0000000009d72310
   subsdk0:0x00a152a4 Sub0000000009dba2a4
   subsdk0:0x00a16bd8 Sub0000000009dbbbd8
   subsdk0:0x00a1673c Sub0000000009dbb73c
   subsdk0:0x00a1e24c Sub0000000009dc324c
   subsdk0:0x0074d9d0 Sub0000000009af29d0
   subsdk0:0x0074d6bc Sub0000000009af26bc
   main:0x0011b57c gxtkSurface::Bind()
   main:0x0011b82c gxtkSurface::BindDirect(int)
   main:0x0011bbf8 gxtkGraphics::LoadSurface(String, bool, int, gxtkSurface*)
   main:0x00172c18 c_Image::p_LoadSurface(String, bool, int)
   main:0x0015f51c c_AtlasManager::m_LoadRequiredAtlases()
   main:0x0015d90c c_GameEngine::p_OnRender_Early()
   main:0x00114218 BBGame::RenderGame_Early()
   main:0x00115c28 BBGlfwGame::Run()
   main:0x001163dc BBMonkeyGame::Main()
   main:0x00ae297c nnMain
   sdk:0x00289ddc nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:10:07.556 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1422
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 37
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 141
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[SCLPM.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6196648/SCLPM.log)

**Comment by EmulationFanatic** [comment]
Updated
