### ISSUE TITLE
Blizzard Arcade Collection - 0100743013D56000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3457]
#### Current on `master` : 1.0.6797

Took a long time to boot but, once in, the embedded games played normally at a high FPS.

#### Screenshots :

![2021-03-24 06_46_47-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314811-14040b80-8c6f-11eb-965d-32eb9db8a3c0.png)
![2021-03-24 06_47_30-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314827-19615600-8c6f-11eb-9d86-4073a8f54fda.png)
![2021-03-24 06_47_50-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314850-1f573700-8c6f-11eb-9da2-098f87e73232.png)
![2021-03-24 06_48_21-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314867-24b48180-8c6f-11eb-8cc3-f2e0e707271a.png)
![2021-03-24 06_48_50-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314893-2a11cc00-8c6f-11eb-8a2d-64a940b5f63b.png)
![2021-03-24 06_49_27-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314895-2b42f900-8c6f-11eb-8a6c-8688ce1300c8.png)
![2021-03-24 06_51_20-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314909-2ed68000-8c6f-11eb-9ce1-16c63cdbd838.png)
![2021-03-24 06_52_09-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314940-372ebb00-8c6f-11eb-864b-b52fbbdf7238.png)
![2021-03-24 07_00_28-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314950-3b5ad880-8c6f-11eb-8c30-49dfed9100f5.png)
![2021-03-24 07_01_10-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314979-40b82300-8c6f-11eb-92c5-189a2cff333b.png)
![2021-03-24 07_01_16-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314984-41e95000-8c6f-11eb-8615-e3664f0fcbe6.png)
![2021-03-24 07_03_09-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314987-41e95000-8c6f-11eb-9565-e0615aa4ec8c.png)
![2021-03-24 07_03_21-Ryujinx 1 0 6797 - BLIZZARD ARCADE COLLECTION v1 0 0 (0100743013D56000) (64-bit)](https://user-images.githubusercontent.com/62343878/112314996-444baa00-8c6f-11eb-86ee-11507cd8c686.png)

#### Log file :

[BAC.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6197428/BAC.log)

**Comment by LukeWarnut** [comment]
## Blizzard Arcade Collection

#### Game Update Version : 1.0.0

#### Current on `master` : 1.1.205

#### Graphics Backend : Vulkan and OpenGL

The game now crashes on startup. (Regression)
```
00:00:07.927 |E| HLE.GuestThread.15 Application : Unhandled exception caught: System.OverflowException: Arithmetic operation resulted in an overflow.
   at ARMeilleure.IntermediateRepresentation.Operand.AddAssignment(Operation operation) in D:\a\Ryujinx\Ryujinx\ARMeilleure\IntermediateRepresentation\Operand.cs:line 185
   at ARMeilleure.Translation.RegisterToLocal.Rename(ControlFlowGraph cfg) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\RegisterToLocal.cs:line 12
   at ARMeilleure.Translation.Compiler.Compile(ControlFlowGraph cfg, OperandType[] argTypes, OperandType retType, CompilerOptions options) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Compiler.cs:line 52
   at ARMeilleure.Translation.Translator.Translate(UInt64 address, ExecutionMode mode, Boolean highCq, Boolean singleStep) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 258
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 245
   at ARMeilleure.Instructions.NativeInterface.GetFunctionAddress(UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 240
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
```

#### Hardware Specs : 

##### CPU: AMD Ryzen 5 2600
##### GPU: NVIDIA GTX 1660 SUPER
##### RAM: 16GB

#### Log file :

[BAC.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9254472/BAC.log)
