### ISSUE TITLE
Storm in a Teacup - 0100B2300B932000

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#3461]
#### Current on `master` : 1.0.6797

Game crashes after initial splashes. Rendered video is inverted.

```
00:00:53.737 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x10954F000..0x1095D2040 is not fully mapped.
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 325
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 762
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(CopyTexture copyTexture, FormatInfo formatInfo, Boolean preferScaling, Nullable`1 sizeHint) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 520
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyTexture(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyTexture.cs:line 105
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 449
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![image](https://user-images.githubusercontent.com/65521430/112353344-07e57180-8ca2-11eb-995e-6edf83204861.png)

#### Log file :

[StormTeacup.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6199211/StormTeacup.log)

**Comment by benderscruffy** [comment]
using 1.0.7096
goes ingame now
![ryujinx_capture_2021-11-03_17-11-39](https://user-images.githubusercontent.com/2696404/140034347-5413b706-eaa7-47a5-bbc1-00af2e326e21.png)
![ryujinx_capture_2021-11-03_17-11-42](https://user-images.githubusercontent.com/2696404/140034360-3677187a-6fb1-4746-994a-377e8b0c068a.png)
![ryujinx_capture_2021-11-03_17-11-57](https://user-images.githubusercontent.com/2696404/140034378-e9f1dfba-ddf8-428d-ad35-8ca4eaeebe91.png)
![ryujinx_capture_2021-11-03_17-12-00](https://user-images.githubusercontent.com/2696404/140034388-72e84df9-c364-4293-87b7-0f0192991cb8.png)
![ryujinx_capture_2021-11-03_17-12-02](https://user-images.githubusercontent.com/2696404/140034399-a99ef50a-ac9f-4bfe-b9a0-545574e8f398.png)
![ryujinx_capture_2021-11-03_17-12-10](https://user-images.githubusercontent.com/2696404/140034410-41cbd993-bf5c-4bcb-97cc-0d309d2a56d2.png)
![ryujinx_capture_2021-11-03_17-12-17](https://user-images.githubusercontent.com/2696404/140034424-94f3527a-900d-48a7-a7af-a077d92ef0a9.png)
![ryujinx_capture_2021-11-03_17-12-31](https://user-images.githubusercontent.com/2696404/140034446-a20749a6-34f5-47c5-aa47-17fb0489d82c.png)

**Comment by benderscruffy** [comment]
can get rid of the gpu label
