### ISSUE TITLE
Monster hunter rise crashing when loading/creating saves

### ISSUE THREAD

**Issue by koedrly** [Ryujinx/Ryujinx-Games-List#3468]
#### Current on `LDN2` : LDN2
*The game will load and get to the menu's but once you try to name a character it crashes. It also crashes why trying to load a saved game past that( I downloaded someone elses save in an attempt to bypass the naming character screen.)

```
Last error returned.

```at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

#### Hardware Specs : 

##### CPU: I7 9750H
##### GPU: RTX 2070 max q
##### RAM: 16 gb
[Ryujinx_1.0.0-ldn2.1_2021-04-01_00-40-07.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6241097/Ryujinx_1.0.0-ldn2.1_2021-04-01_00-40-07.log)


#### Pull requests needed :



#### Outstanding Issues:



#### Screenshots :



#### Log file :

https://drive.google.com/file/d/1sUeehy0drizzNVSCCJ1dhpSrAueB_fYX/view?usp=sharing

**Comment by SeraUQ** [comment]
this is not a place for support
come to our [discord](https://discord.gg/ryujinx) for that
