### ISSUE TITLE
Tales from the Borderlands - 0100F0C011A68000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3504]
#### Current on `master` : 1.0.6819

Crashes shortly after pressing A at the title screen.

```
GUI.RenderLoop Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.Shader.Translation.Rewriter.InsertSnormNormalization(LinkedListNode`1 node, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Rewriter.cs:line 481
   at Ryujinx.Graphics.Shader.Translation.Rewriter.RunPass(BasicBlock[] blocks, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Rewriter.cs:line 40
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(FunctionCode[] functions, ShaderConfig config, ShaderProgramInfo& shaderProgramInfo) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 75
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateShader(TranslatorContext translatorContext, TranslatorContext translatorContext2) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 825
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetComputeShader(GpuState state, UInt64 gpuVa, Int32 localSizeX, Int32 localSizeY, Int32 localSizeZ, Int32 localMemorySize, Int32 sharedMemorySize) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 455
   at Ryujinx.Graphics.Gpu.Engine.Methods.Dispatch(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Compute.cs:line 31
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 449
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2021-04-07 10_15_22-Ryujinx 1 0 6819 - Tales from the Borderlands v1 0 0 (0100F0C011A68000) (64-bit)](https://user-images.githubusercontent.com/62343878/113899873-79d1b680-978a-11eb-9edb-d99bff9041d3.png)
![2021-04-07 10_15_43-Ryujinx 1 0 6819 - Tales from the Borderlands v1 0 0 (0100F0C011A68000) (64-bit)](https://user-images.githubusercontent.com/62343878/113899906-80f8c480-978a-11eb-9a00-de621dce9b9d.png)
![2021-04-07 10_15_58-Ryujinx 1 0 6819 - Tales from the Borderlands v1 0 0 (0100F0C011A68000) (64-bit)](https://user-images.githubusercontent.com/62343878/113899936-881fd280-978a-11eb-9845-6589a7a7f6e6.png)

#### Log file :

[TftB.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6273069/TftB.log)

**Comment by benderscruffy** [comment]
using 1.0.7106
goes ingame now
only problem is all the characters are invisible
![ryujinx_capture_2021-11-21_12-13-35](https://user-images.githubusercontent.com/2696404/142749444-97d7a7ad-5256-46ee-a1f7-6cbf91104a0f.png)
![ryujinx_capture_2021-11-21_12-13-43](https://user-images.githubusercontent.com/2696404/142749451-51982f83-2b35-432f-9f87-8a41c15eb9eb.png)
![ryujinx_capture_2021-11-21_12-14-17](https://user-images.githubusercontent.com/2696404/142749452-1afcfe8d-b8ad-4d2c-9489-f4fb9f979a6b.png)
![ryujinx_capture_2021-11-21_12-15-56](https://user-images.githubusercontent.com/2696404/142749454-81117728-21de-4446-81f4-2289a496d957.png)
![ryujinx_capture_2021-11-21_12-18-04](https://user-images.githubusercontent.com/2696404/142749456-8367e678-583a-4e65-a1ad-9bec882b40ae.png)
![ryujinx_capture_2021-11-21_12-18-11](https://user-images.githubusercontent.com/2696404/142749460-4abd8683-e44c-4115-a493-5e20a3d72d2d.png)

**Comment by benderscruffy** [comment]
change the status please

**Comment by EmulationFanatic** [comment]
Updated
