### ISSUE TITLE
Star Wars: Republic Commando - 0100FA10115F8000

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#3506]
#### Current on `master` : 1.0.6823

Game crashes at lauch. Both versions 1.0.0 and 1.0.1 were tested.

```
00:00:15.932 |E| SurfaceFlinger.Composer Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.SurfaceFlinger.Compose() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\SurfaceFlinger.cs:line 266
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.SurfaceFlinger.HandleComposition() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\SurfaceFlinger.cs:line 227
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[StarWarsRC.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6275227/StarWarsRC.log)

**Comment by AcK77** [comment]
Needs an update

**Comment by ffsPLASMA** [comment]
It now shows the games boot screen but crashes afterwards.

Ryujinx Version: 1.0.6829

`00:01:14.128 |E| HLE.GuestThread.21 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000000758d50 (opcode 0xf3f222e2) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1086
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 142
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

Log file: 
[Ryujinx_1.0.6829_2021-04-13_11-09-07.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6302566/Ryujinx_1.0.6829_2021-04-13_11-09-07.log)

**Comment by LukeWarnut** [comment]
Updated

**Comment by ffsPLASMA** [comment]
Still crashing at same position.

Version: 1.0.6840


00:00:25.295 |E| HLE.GuestThread.21 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000000758d50 (opcode 0xf3f222e2) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1086
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 142
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


Log:
[Ryujinx_1.0.6840_2021-04-18_10-55-13.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6330808/Ryujinx_1.0.6840_2021-04-18_10-55-13.log)

**Comment by MetrosexualGarbodor** [comment]
Needs an update.

**Comment by viksmir** [comment]
Version: 1.0.4

Graphical artifact in the Lucasarts intro video, otherwise very much playable.


![ryujinx_capture_2022-10-24_23-53-58](https://user-images.githubusercontent.com/48307254/197678586-45e9b4a2-71a8-436a-9a2c-1977eab76cd5.png)
![ryujinx_capture_2022-10-24_23-50-49](https://user-images.githubusercontent.com/48307254/197678605-f37ca00b-a6a3-4363-9da5-3531b79deca3.png)
![ryujinx_capture_2022-10-24_23-44-13](https://user-images.githubusercontent.com/48307254/197678608-121f6369-1f34-40c4-883f-4601ec1770f6.png)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by LeaveNhA** [comment]
The glitch you reported in the entry screen is in the game and appearing a lot. How can I provide some debug information?
