### ISSUE TITLE
MAGLAM LORD - 0100c2c0125fc000

### ISSUE THREAD

**Issue by tazevam** [Ryujinx/Ryujinx-Games-List#3511]
#### Current on `master` : 1.0.6823

The game seems to be able to run and save/load normally, but when the game enters the 3d battle scene, it will crash. Check the log and find that it has similar problem as dq11s. 

#### Outstanding Issues:

The game seems to be able to run and save/load normally, but when the game enters the 3d battle scene, it will crash. Check the log and find that it has similar problem as dq11s. 

Example: https://github.com/Ryujinx/Ryujinx/issues/1976

#### Screenshots :

![1](https://user-images.githubusercontent.com/73407337/114091901-d7314900-98eb-11eb-92ee-417bc63ee7bd.PNG)
![2](https://user-images.githubusercontent.com/73407337/114091916-dbf5fd00-98eb-11eb-9149-9024cf79a76a.PNG)
![3](https://user-images.githubusercontent.com/73407337/114091929-df898400-98eb-11eb-83b1-d3983a90d358.PNG)

#### Log file :
[Ryujinx_1.0.6823_2021-04-09_04-03-26.log](https://github.com/Ryujinx/Ryujinx/files/6281253/Ryujinx_1.0.6823_2021-04-09_04-03-26.log)

**Comment by Itamai** [comment]
Can confirm this issue as well :)
```
GUI.RenderLoop Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000009E7CA0000.
00:09:05.842 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 479
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 292
   at Ryujinx.Graphics.Gpu.Memory.PhysicalMemory.GetSpan(MultiRange range, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\PhysicalMemory.cs:line 53
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeFull() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 641
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.EvaluateRelevantHandles(Texture texture, HandlesCallbackDelegate callback) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 320
   at Ryujinx.Graphics.Gpu.Image.AutoDeleteCache.Add(Texture texture) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\AutoDeleteCache.cs:line 44
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 1004
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(CopyTexture copyTexture, FormatInfo formatInfo, Boolean preferScaling, Nullable`1 sizeHint) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 520
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyTexture(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyTexture.cs:line 46
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 449
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   ```
