### ISSUE TITLE
FEZ - 01008D900B984000

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#3526]
#### Current on `master` : 1.0.6836

Game crashes at launch.

```
00:00:04.850 |E| AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.Command.DelayCommand.ProcessDelayMono(Span`1 outputBuffer, ReadOnlySpan`1 inputBuffer, UInt32 sampleCount) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\DelayCommand.cs:line 69
   at Ryujinx.Audio.Renderer.Dsp.Command.DelayCommand.ProcessDelay(CommandList context) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\DelayCommand.cs:line 212
   at Ryujinx.Audio.Renderer.Dsp.Command.DelayCommand.Process(CommandList context) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\DelayCommand.cs:line 269
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\CommandList.cs:line 98
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 220
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[FEZ.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6328536/FEZ.log)

**Comment by AcK77** [comment]
Needs update

**Comment by LukeWarnut** [comment]
Updated.

**Comment by AcK77** [comment]
Needs an update

**Comment by LukeWarnut** [comment]
Updated.

**Comment by riperiperi** [comment]
> Player sprite renders incorrectly for a few frames when exiting/entering doors before acquiring the FEZ

This appears to happen on the switch:

https://youtu.be/Mvk2lG-wF5o?t=50
