### ISSUE TITLE
SaGa Frontier Remastered - 0100A51013530000

### ISSUE THREAD

**Issue by ponchojohn1234** [Ryujinx/Ryujinx-Games-List#3550]
#### Current on `master` : 1.0.6844

Emulator crashes

```
00:00:09.714 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000420.
00:00:09.775 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 174
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 160
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[Ryujinx_1.0.6844_2021-04-20_11-06-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6345011/Ryujinx_1.0.6844_2021-04-20_11-06-33.log)

**Comment by EmulationFanatic** [comment]
Updated
