### ISSUE TITLE
Shantae - 0100430013120000

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#3555]
#### Current on `master` : 1.0.6846

Game crashes after the WayForward logo.

```
00:01:09.812 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x1068BF000..0x106940F00 is not fully mapped.
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 325
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 762
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(CopyTexture copyTexture, FormatInfo formatInfo, Boolean preferScaling, Nullable`1 sizeHint) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 520
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyTexture(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyTexture.cs:line 105
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 450
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![image](https://user-images.githubusercontent.com/65521430/115811178-3cda0680-a3bd-11eb-8e31-8dc93109c9a3.png)

#### Log file :

[ShantaeGBC.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6362396/ShantaeGBC.log)

**Comment by mjd180** [comment]
After 3rd/4th boot attempt, able to get just after this to 'Limited Run' logo.

**Comment by LukeWarnut** [comment]
I'm getting a slight variation of the same error on the latest master build. Any ideas on the cause? It seems to work for everyone else.
```
00:01:10.015 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x1064BF000..0x106540F00 is not fully mapped.
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 325
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 762
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(CopyTexture copyTexture, FormatInfo formatInfo, Boolean preferScaling, Nullable`1 sizeHint) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 520
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyTexture(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyTexture.cs:line 105
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 450
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()\
```
[ShantaeLWCrash.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6408525/ShantaeLWCrash.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by BigheadSMZ** [comment]
Figured I'd leave a bit more feedback, not sure if it will be any use but here it is. I've tested this game on four different PCs now, and it crashes on all of them every single time. I have yet to see this game successfully load in Ryujinx. All PCs using Windows 10, some pro, some home, some v1909, some v20h2. Fresh Ryujinx install on each, no copy and pasting for the sake of accidentally copying the error. Tried multiple settings, multiple firmware revisions, result is always the same.

Ryzen 3700x, 16GB RAM, GTX 1060, 512GB M.2 SSD
Intel 9700k, 32GB RAM, RTX 2070, 1TB M.2 SSD
Intel 2700k, 16GB RAM, GTX 970, 320GB SSD
Intel 4790k, 20GB RAM, GTX 970, 2TB HDD

The crash always seems to happen after creating "map 44" or "map 50", with the same exact error message as in LukeWarnut's post. I'm in no rush to play it here as I have this game on GBC, switch, other emulators, etc. I just kinda fell into a trap trying it out, seeing it listed as "playable", but for the life of me can't get it to play.

**Comment by gdkchan** [comment]
The random crash after the WayForward logo should be fixed by https://github.com/Ryujinx/Ryujinx/pull/2302

**Comment by LukeWarnut** [comment]
> The random crash after the WayForward logo should be fixed by [Ryujinx/Ryujinx#2302](https://github.com/Ryujinx/Ryujinx/pull/2302)

Awesome. This fixes it for me.

**Comment by BigheadSMZ** [comment]
Fixed it for me too! Tested on at least 2 of the systems mentioned.
