### ISSUE TITLE
Nintendo Labo Toy-Con 03: Vehicle Kit - 01001E9003502000

### ISSUE THREAD

**Issue by LukeWarnut** [Ryujinx/Ryujinx-Games-List#3564]
#### Current on `master` : 1.0.6860

Crashes after initial HD Rumble splash screen.

```
00:00:29.916 |E| HLE.OsThread.5 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Hid.Irs.IIrSensorServer: 314

Guest Stack Trace:
Process: Service, PID: 82

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  3A 01 00 00 00 00 00 00   SFCI····:·······
00000010   00 00 00 00 05 00 18 00  01 00 00 00 00 00 00 00   ················
00000020   53 46 43 49                                        SFCI            

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 156
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Outstanding Issues:

Ryujinx/Ryujinx#2268

#### Screenshots :

![image](https://user-images.githubusercontent.com/65521430/117159664-77b14680-ad8e-11eb-897c-f9824cfa30ce.png)

#### Log file :

[ToyCon3.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6427935/ToyCon3.log)

**Comment by LukeWarnut** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
