### ISSUE TITLE
Taiko no Tatsujin - Drum 'n' Fun! (Europe).xci  

### ISSUE THREAD

**Issue by dsfdsdsgfdgfd** [Ryujinx/Ryujinx-Games-List#3565]
00:00:00.017 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.018 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.019 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.020 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.024 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.039 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.039 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.039 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.039 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.039 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.041 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.041 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.041 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.045 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6864
00:00:00.051 |N| Application Print: Operating System: Microsoft Windows 10.0.19041 (X64)
00:00:00.051 |N| Application Print: CPU: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz ; 4 logical
00:00:00.051 |N| Application Print: RAM: Total 16271 MB ; Available 10843 MB
00:00:00.055 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.055 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.445 |I| Hid Configure: Configured Controller JoyconPair to Player1
00:00:00.580 |N| Application LoadApplication: Using Firmware Version: 12.0.1
00:00:00.580 |I| Application LoadApplication: Loading as XCI.
00:00:00.720 |I| ModLoader QueryContentsDir: Searching mods for Title 01002C000B552000
00:00:00.735 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.101 |I| Loader LoadExeFs: Loading rtld...
00:00:01.130 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:01.130 |I| Loader LoadExeFs: Loading main...
00:00:01.307 |I| Loader PrintRoSectionInfo: main:
    Module: E:\Jenkins\workspace\TaikoSwitchMasterW\Program\Taylor\Bin\NX64_v140\AbRelease\Taylor.nss
00:00:01.307 |I| Loader LoadExeFs: Loading sdk...
00:00:01.465 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 4.5.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-4_5_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-4_5_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-4_5_0-Release
00:00:01.549 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.738 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.743 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:01.772 |I| Loader LoadNsos: Loading image 2 at 0x000000000ad75000...
00:00:01.782 |I| ModLoader LoadCheats: Build ids found for title 01002C000B552000:
    6EFA2FDA5159C68960EC029B86AEC44B292262D5000000000000000000000000
    5458BDFE72EAD13348D2008E282DFF8100000000000000000000000000000000
    E01AD5381C948C4EC3B0BB210B08D5C8D72D7782000000000000000000000000
00:00:01.782 |I| Loader LoadNca: Application Loaded: Taiko no Tatsujin: Drum ‘n’ Fun! v1.0.0 [01002c000b552000] [64-bit]
00:00:01.908 |E| Application : Unhandled exception caught: SPB.Platform.Exceptions.PlatformException: Missing needed WGL extension: "WGL_ARB_create_context_profile"
   at SPB.Platform.WGL.WGLHelper.EnsureExtensionPresence(String extensionName)
   at SPB.Platform.WGL.WGLHelper.EnsureInit()
   at SPB.Platform.WGL.WGLHelper.CreateContext(IntPtr& windowHandle, FramebufferFormat framebufferFormat, Int32 major, Int32 minor, OpenGLContextFlags flags, Boolean directRendering, IntPtr shareContext)
   at SPB.Platform.WGL.WGLOpenGLContext.Initialize(NativeWindowBase window)
   at Ryujinx.Ui.GlRenderer.IntializeOpenGL() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 63
   at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr) in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 50
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)

**Comment by dsfdsdsgfdgfd** [comment]
it will not work
