### ISSUE TITLE
Lost Words: Beyond the Page - 0100018013124000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3569]
#### Current on `master` : 1.0.6864

Crashes almost instantly after launch.

```
HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   main:0x0091c7e4 Sub00000000089207e4
   main:0x0091c7e4 Sub00000000089207e4
   main:0x0091c7e4 Sub00000000089207e4
   main:0x0091c7e4 Sub00000000089207e4
   main:0x0091c7e4 Sub00000000089207e4
   main:0x00315afc Sub0000000008319afc
   main:0x0031cae8 Sub0000000008320ae8
   main:0x002ccba8 nnMain
   sdk:0x002a3864 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)())
   rtld:0x000000d4 Sub00000000080000d4


00:00:04.672 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000420.
00:00:04.684 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.Write[T](UInt64 va, T value) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 174
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 160
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[LWBtP.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6435516/LWBtP.log)

**Comment by EmulationFanatic** [comment]
Updated
