### ISSUE TITLE
Rune Factory 5

### ISSUE THREAD

**Issue by JXXKER** [Ryujinx/Ryujinx-Games-List#3597]
Game Name : Rune Factory 5

Game Update Version : 1.01.1

Current on `master` : 1.0.6887

Crashes after sword & lock-on tutorial

```
Last error returned.

00:06:21.795 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x223EAF000..0x223ECF000 is not fully mapped.
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 325
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 764
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(CopyTexture copyTexture, FormatInfo formatInfo, Boolean preferScaling, Nullable`1 sizeHint) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 522
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyTexture(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyTexture.cs:line 105
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.RendererWidgetBase.Render() in C:\projects\ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 307
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

Hardware Specs : 

CPU: Intel i5 9400F
GPU: GTX 1650 Super
RAM: 8GB

**Comment by GamerzHell9137** [comment]
## Rune Factory 5 (ルーンファクトリー5) JPN Version

#### Game Update Version : *v1.01.1*

#### Current on `master` : *1.0.6887*

1. Crashes at the fighting tutorial scene in **Docked** mode

```
Last error returned.
e.g.: Unhandled Exception: System.NotImplementedException: /dev/nvhost-nvdec 40044801
```

2. With included PR the game might crash later
```
Fatal error. Internal CLR error. (0x80131506)
```

#### Hardware Specs : 

**CPU: *Amd Ryzen 3600*
GPU: *NVIDIA GTX 960 2GB*
RAM: *16GB***

#### Pull requests needed :

**PR 2302 for fixing the tutorial crash** -- https://github.com/Ryujinx/Ryujinx/pull/2302

#### Outstanding Issues:

1. The graphics lightning might bug when leaving interiors. Randomly fixes itself by reentering.

![Ryujinx Nvidia Profile Screenshot 2021 05 20 - 10 22 15 99](https://user-images.githubusercontent.com/2002038/119184858-39967100-ba76-11eb-874f-3cc2b0f2f908.png)
![Ryujinx Nvidia Profile Screenshot 2021 05 20 - 10 20 22 73](https://user-images.githubusercontent.com/2002038/119184887-3e5b2500-ba76-11eb-9885-967b5a2ac93b.png)

2. Skirts of characters are lifted up and clipping
![image](https://user-images.githubusercontent.com/2002038/119184778-1c61a280-ba76-11eb-82f1-1bf62c5df5f9.png)

https://user-images.githubusercontent.com/2002038/119185121-ab6eba80-ba76-11eb-99f8-a9e6a4a6f25a.mp4

**Comment by GamerzHell9137** [comment]
## Rune Factory 5 (ルーンファクトリー5) JPN Version

#### Game Update Version : *v1.01.1*

#### Current on `master` : *1.0.6895*

## Fixed bugs:
With https://github.com/Ryujinx/Ryujinx/pull/2306 was fixed
```
1. Fatal error. Internal CLR error. (0x80131506)
2. Random corruption of lighting in game
```
With https://github.com/Ryujinx/Ryujinx/pull/2305 was fixed
```
1. Skirts being lifted up and being clipped
```

With https://github.com/Ryujinx/Ryujinx/pull/2302 was fixed
```
1. Crashes at the fighting tutorial scene in **Docked** mode caused by invalid memory regions being accessed
```
## Hardware Specs : 

**CPU: *Amd Ryzen 3600*
GPU: *NVIDIA GTX 960 2GB*
RAM: *16GB***

## Outstanding Issues:

1. While executing a combo attack with a friendly unit, the transparent ripple effect is actually a static background image(?) copied over it
![image](https://user-images.githubusercontent.com/2002038/120075081-2b60da00-c0a0-11eb-947f-da3a36613086.png)
![image](https://user-images.githubusercontent.com/2002038/120075100-416e9a80-c0a0-11eb-82d7-f4cd6b05e7b0.png)
![image](https://user-images.githubusercontent.com/2002038/120075119-4fbcb680-c0a0-11eb-8455-9be7dad4ce4a.png)
![image](https://user-images.githubusercontent.com/2002038/120075131-5cd9a580-c0a0-11eb-9885-72860d6cfc98.png)

## On real hardware the combo attack looks like:
![image](https://user-images.githubusercontent.com/2002038/120075074-200dae80-c0a0-11eb-94f6-a46b91082091.png)

Video examples of the issue:

https://user-images.githubusercontent.com/2002038/120075541-00778580-c0a2-11eb-9aab-a5c7418a1e29.mp4

https://user-images.githubusercontent.com/2002038/120075556-14bb8280-c0a2-11eb-9b5d-776da2a037a1.mp4

**Comment by vojo915** [comment]
**Game Update Version :** **v1.0.2** (Note: Newer than v1.01.1)
**Current on `master` :** **1.0.6896**

Hardware Specs :

**CPU:** AMD Ryzen 5 3600
**GPU:** NVIDIA GeForce GTX 1660 Ti 6GB
**RAM:** 16GB

I can reach the title screen, but it will crash randomly after that (during loading after the title screen or during the in-game opening).

**Log File:** [Ryujinx_1.0.6896_2021-05-30_15-14-46_Rune Factory 5_v1.0.2_010014D01216E000.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/6565826/Ryujinx_1.0.6896_2021-05-30_15-14-46_Rune.Factory.5_v1.0.2_010014D01216E000.zip)

**Comment by vojo915** [comment]
**Game Update Version : v1.0.2** (Note: Newer than v1.01.1)
**Current on `master` : 1.0.6900**

Hardware Specs :

**CPU:** AMD Ryzen 5 3600
**GPU:** NVIDIA GeForce GTX 1660 Ti 6GB
**RAM:** 16GB

It always crashes in this scene right after the start of play.

**Screen shot:**

![s001](https://user-images.githubusercontent.com/84438932/120319437-fb256f80-c31b-11eb-9166-e16696dca74e.jpg)

**Log file:** [Ryujinx_1.0.6900_2021-06-01_20-42-48_Rune_Factory_5_v1.0.2.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/6576021/Ryujinx_1.0.6900_2021-06-01_20-42-48_Rune_Factory_5_v1.0.2.zip)
