### ISSUE TITLE
ryujinx 1.0.6890

### ISSUE THREAD

**Issue by fang1121cs** [Ryujinx/Ryujinx-Games-List#3598]
#### Outstanding Issues:
It can't run any games on windows10 ltsc(1809) ,and work properly on windows 10 pro

log:
00:00:00.002 |I| Configuration LogValueChange: EnableFileLog set to: False
00:00:00.004 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.005 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.005 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.006 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.009 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.104 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.105 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.105 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.105 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.105 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.106 |I| Configuration LogValueChange: AudioBackend set to: OpenAl
00:00:00.106 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.106 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.108 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.6890
00:00:00.113 |N| Application Print: Operating System: Microsoft Windows 10.0.17763 (X64)
00:00:00.113 |N| Application Print: CPU: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz ; 6 logical
00:00:00.113 |N| Application Print: RAM: Total 8043 MB ; Available 5252 MB
00:00:00.116 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.116 |N| Application PrintSystemInfo: Launch Mode: UserProfile
Marshaling row-activated signal
00:00:00.802 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at Ryujinx.Memory.MemoryManagementWindows.AllocateInternal(IntPtr size, AllocationType flags) in C:\projects\ryujinx\Ryujinx.Memory\MemoryManagementWindows.cs:line 71
   at Ryujinx.Memory.MemoryManagement.Allocate(UInt64 size) in C:\projects\ryujinx\Ryujinx.Memory\MemoryManagement.cs:line 10
   at Ryujinx.Memory.MemoryBlock..ctor(UInt64 size, MemoryAllocationFlags flags) in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 31
   at Ryujinx.HLE.Switch..ctor(HLEConfiguration configuration) in C:\projects\ryujinx\Ryujinx.HLE\Switch.cs:line 70
   at Ryujinx.Ui.MainWindow.InitializeSwitchInstance() in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 436
   at Ryujinx.Ui.MainWindow.LoadApplication(String path) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 554
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 1012
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by choppymaster** [comment]
Hello @fang1121cs, this is the database of games tested in ryujinx. You can ask in our [discord server](https://discord.gg/ryujinx) for support.
