### ISSUE TITLE
MotoGP 21 - 01000F5013820000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3611]
#### Current on `master` : 1.0.6895

Crashes in menus while trying to load into a race.

```
GUI.RenderLoop Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Graphics.Shader.Translation.Rewriter.InsertSnormNormalization(LinkedListNode`1 node, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Rewriter.cs:line 490
   at Ryujinx.Graphics.Shader.Translation.Rewriter.RunPass(BasicBlock[] blocks, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Rewriter.cs:line 40
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(FunctionCode[] functions, ShaderConfig config, ShaderProgramInfo& shaderProgramInfo) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 75
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateShader(TranslatorContext translatorContext, TranslatorContext translatorContext2) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 921
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetComputeShader(GpuState state, UInt64 gpuVa, Int32 localSizeX, Int32 localSizeY, Int32 localSizeZ, Int32 localMemorySize, Int32 sharedMemorySize) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 545
   at Ryujinx.Graphics.Gpu.Engine.Methods.Dispatch(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Compute.cs:line 33
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.RendererWidgetBase.Render() in C:\projects\ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 307
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2021-05-26 06_57_37-Ryujinx 1 0 6895 - MotoGP™21 v1 0 0 (01000F5013820000) (64-bit)](https://user-images.githubusercontent.com/62343878/119664494-9edcc000-bdf0-11eb-8674-48d47cd72a8a.png)
![2021-05-26 06_58_24-Ryujinx 1 0 6895 - MotoGP™21 v1 0 0 (01000F5013820000) (64-bit)](https://user-images.githubusercontent.com/62343878/119664502-a0a68380-bdf0-11eb-86db-bf0b33bb4d99.png)
![2021-05-26 06_59_06-Ryujinx 1 0 6895 - MotoGP™21 v1 0 0 (01000F5013820000) (64-bit)](https://user-images.githubusercontent.com/62343878/119664510-a3a17400-bdf0-11eb-8a4e-fdbbe9abbe72.png)
![2021-05-26 07_03_13-Ryujinx 1 0 6895 - MotoGP™21 v1 0 0 (01000F5013820000) (64-bit)](https://user-images.githubusercontent.com/62343878/119664526-a69c6480-bdf0-11eb-9fab-07c2a7aad790.png)

#### Log file :

[MGP21.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6546862/MGP21.log)

**Comment by EmulationFanatic** [comment]
Updated
