### ISSUE TITLE
Himehibi 1 gakki - Princess Days - 0100F8D0129F4000

### ISSUE THREAD

**Issue by Kaizen-mini** [Ryujinx/Ryujinx-Games-List#3615]
#### Current on `master` : Commit Id *or* Build Version : *1.0.6895*

Ryujinx crashes when loading the game.

```
00:00:26.987 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000008
   at Ryujinx.Cpu.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 134
   at Ryujinx.Cpu.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManagerHostMapped.cs:line 281
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 103
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Read[T](UInt64 va) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 56
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(IGpuAccessor gpuAccessor, Block block, UInt64 limitAddress, UInt64 startAddress, Boolean& hasBindless) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 260
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(IGpuAccessor gpuAccessor, UInt64 startAddress, Boolean& hasBindless) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 89
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, TranslationCounts counts, ShaderConfig& config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 125
   at Ryujinx.Graphics.Shader.Translation.Translator.CreateContext(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, TranslationCounts counts) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 34
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 627
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 985
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 138
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 71
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 40
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 154
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 101
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.RendererWidgetBase.Render() in C:\projects\ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 307
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :
[Ryujinx_1.0.6895_2021-05-30_03-25-20.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6565288/Ryujinx_1.0.6895_2021-05-30_03-25-20.log)

**Comment by EmulationFanatic** [comment]
Can you update your gpu drivers and try again? They are years out of date.

**Comment by Kaizen-mini** [comment]
Sorry, those drivers are the latest version my GPU can handle. I know getting a new one can be dirt cheap to some people, I'm just not in a suitable situation for that right now.
Maybe someone else who has the game can test it. Sorry for the incomplete test.

**Comment by RealTabman** [comment]
I tried it with my semi-recent nvidia driver and also got the same crash.
##### CPU:  AMD Ryzen 5 2600
##### GPU:  Nvidia GTX 1660
##### RAM: 16GB
[Ryujinx_1.0.6896_2021-05-30_20-09-02.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6566685/Ryujinx_1.0.6896_2021-05-30_20-09-02.log)

**Comment by gdkchan** [comment]
> 
> 
> Sorry, those drivers are the latest version my GPU can handle. I know getting a new one can be dirt cheap to some people, I'm just not in a suitable situation for that right now.
> Maybe someone else who has the game can test it. Sorry for the incomplete test.

I think this is fine if thats the latest driver version you have available for your GPU. Those exceptions can't be caused by broken drivers anyway.

**Comment by benderscruffy** [comment]
using 1..7096
goes ingame now
![ryujinx_capture_2021-11-03_16-29-12](https://user-images.githubusercontent.com/2696404/140029305-8ad75dc4-2ac6-4ecf-933f-b2f7760b8ef7.png)
![ryujinx_capture_2021-11-03_16-29-18](https://user-images.githubusercontent.com/2696404/140029336-e9bb4b05-429d-43a6-8855-448dd6770c20.png)
![ryujinx_capture_2021-11-03_16-29-54](https://user-images.githubusercontent.com/2696404/140029341-9d5c169f-059e-442d-82d3-5cdc4aa84d53.png)
![ryujinx_capture_2021-11-03_16-30-02](https://user-images.githubusercontent.com/2696404/140029364-d91f4521-c396-4b87-b1a2-806743e38bd4.png)
![ryujinx_capture_2021-11-03_16-30-09](https://user-images.githubusercontent.com/2696404/140029373-6c826159-651f-4019-90f2-38774464b425.png)
![ryujinx_capture_2021-11-03_16-30-13](https://user-images.githubusercontent.com/2696404/140029389-d49b33e6-0fd0-4dc2-a4f1-96481a41c6bc.png)
![ryujinx_capture_2021-11-03_16-30-16](https://user-images.githubusercontent.com/2696404/140029412-da2ee2c1-1925-44cd-8b73-331d1f924585.png)
![ryujinx_capture_2021-11-03_16-30-47](https://user-images.githubusercontent.com/2696404/140029462-bec80986-7b19-48a0-ae8f-3ee308109ec5.png)
![ryujinx_capture_2021-11-03_16-30-53](https://user-images.githubusercontent.com/2696404/140029524-9ec76ca2-6c5b-4165-95fe-72de968237bf.png)
![ryujinx_capture_2021-11-03_16-30-57](https://user-images.githubusercontent.com/2696404/140029567-8d87e252-5c53-4361-9a93-96d1154fe7fb.png)
![ryujinx_capture_2021-11-03_16-31-07](https://user-images.githubusercontent.com/2696404/140029599-c4751e2a-624d-40eb-bdc1-259b8e683b19.png)
