### ISSUE TITLE
Red screen on Dragon Ball FightersZ

### ISSUE THREAD

**Issue by ryulovesjinx** [Ryujinx/Ryujinx-Games-List#3621]
#### Current on `master` : 1.0.6900

The game works really well, great FPS but on the characters selection screen and the pre-load battle screen, the screen is flickering between correct state and a red screen, most of the time is red screen.

```
Last error returned.
00:04:49.987 |E| GUI.RenderLoop Gpu GLERROR: DebugSeverityHigh: GL_INVALID_VALUE error generated. <offset> is negative or <size> is less than or equal to zero or <offset> is not an integer multiple of TEXTURE_BUFFER_OFFSET_ALIGNMENT.
CallStack=   at System.Environment.get_StackTrace()
   at Ryujinx.Graphics.OpenGL.Debugger.GLDebugHandler(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Debugger.cs:line 66
   at Ryujinx.Graphics.OpenGL.Image.TextureBuffer.SetStorage(BufferRange buffer) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Image\TextureBuffer.cs:line 76
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CommitBufferTextureBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 668
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CommitGraphicsBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 807
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 125
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 71
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 40
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 111
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 176
   at Ryujinx.Ui.RendererWidgetBase.Render() in C:\projects\ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 307
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :
![Screenshot from 2021-06-01 17-18-59](https://user-images.githubusercontent.com/85196112/120386055-87c13500-c2fe-11eb-9724-1d6e7728a0e4.png)
![Screenshot from 2021-06-01 17-19-03](https://user-images.githubusercontent.com/85196112/120386058-88f26200-c2fe-11eb-8813-cf764f65d1b4.png)
![Screenshot from 2021-06-01 17-19-57](https://user-images.githubusercontent.com/85196112/120386062-8a238f00-c2fe-11eb-994b-63b818930a92.png)

**Comment by ryulovesjinx** [comment]
Problem occurs on both Windows and Linux, MAC not tested.

**Comment by EmulationFanatic** [comment]
Hi @ryulovesjinx thanks for the info! There is already an entry for this game so this test will be closed. Can you re-test the game with opengl logging OFF and submit it as a reply on the original issue.
