### ISSUE TITLE
Lonely Mountains Downhill - 0100A0C00E0DE000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3626]
#### Current on `master` : 1.0.6906

Game took about 5 minutes to boot after pressing "Play Offline" the first time (roughly half that in subsequent boots), but played at a high FPS after that.

#### Screenshots :

![2021-06-07 08_06_22-Ryujinx 1 0 6906 - Lonely Mountains_ Downhill v1 0 5 (0100A0C00E0DE000) (64-bit)](https://user-images.githubusercontent.com/62343878/121032330-6a5df200-c768-11eb-8e61-29a8bd0fc3ec.png)
![2021-06-07 08_09_38-Ryujinx 1 0 6906 - Lonely Mountains_ Downhill v1 0 5 (0100A0C00E0DE000) (64-bit)](https://user-images.githubusercontent.com/62343878/121032335-6b8f1f00-c768-11eb-9369-dca421b03941.png)
![2021-06-07 08_10_08-Ryujinx 1 0 6906 - Lonely Mountains_ Downhill v1 0 5 (0100A0C00E0DE000) (64-bit)](https://user-images.githubusercontent.com/62343878/121032338-6b8f1f00-c768-11eb-80df-8ad5b0be5ceb.png)
![2021-06-07 08_10_57-Ryujinx 1 0 6906 - Lonely Mountains_ Downhill v1 0 5 (0100A0C00E0DE000) (64-bit)](https://user-images.githubusercontent.com/62343878/121032342-6c27b580-c768-11eb-9930-583e4f73f39d.png)
![2021-06-07 08_11_51-Ryujinx 1 0 6906 - Lonely Mountains_ Downhill v1 0 5 (0100A0C00E0DE000) (64-bit)](https://user-images.githubusercontent.com/62343878/121032345-6cc04c00-c768-11eb-9f30-7ae11af23e05.png)
![2021-06-07 08_12_42-Ryujinx 1 0 6906 - Lonely Mountains_ Downhill v1 0 5 (0100A0C00E0DE000) (64-bit)](https://user-images.githubusercontent.com/62343878/121032351-6d58e280-c768-11eb-9214-a46060d5c359.png)
![2021-06-07 08_14_27-Ryujinx 1 0 6906 - Lonely Mountains_ Downhill v1 0 5 (0100A0C00E0DE000) (64-bit)](https://user-images.githubusercontent.com/62343878/121032356-6e8a0f80-c768-11eb-9a6d-87eda8c53c8b.png)

#### Log file :

[LMD.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6609711/LMD.log)

**Comment by F1ReB4LL** [comment]
## Lonely Mountains Downhill

#### Game Update Version : *1.5.0*

#### Current on `master` :  *1.1.582*

*Crashes after the "Loading" screen.*

```
Last error returned: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1873
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3383
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270
   at System.Threading.Thread.StartCallback()
```

#### Hardware Specs : 

##### CPU: *i5-11400H*
##### GPU: *NVIDIA RTX 3050*
##### RAM: *24GB*



#### Log file :
[Ryujinx_1.1.582_2023-01-21_14-54-57.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10472166/Ryujinx_1.1.582_2023-01-21_14-54-57.log)
[Ryujinx_1.1.582_2023-01-21_15-11-07.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10472167/Ryujinx_1.1.582_2023-01-21_15-11-07.log)

**Comment by F1ReB4LL** [comment]
Also, v1.0.5 works correctly as described in the first post (and it seems it doesn't have that delay anymore, boots instantly), the one that crashes is v1.5.0 (so it is probably not a regression).

**Comment by cddude** [comment]
Won't load past Megagon industries screen.  Frames completely drop to 0.

Game version 1.6.0
Ryujinx 1.1.1340
