### ISSUE TITLE
TONY HAWK'S™ PRO SKATER™ 1 + 2 - 0100CC00102B4000

### ISSUE THREAD

**Issue by Kryptuq** [Ryujinx/Ryujinx-Games-List#3632]
#### Current on `master` : *1.0.6937*

*Crashes at Launch*

```
00:00:06.731 |E| HLE.OsThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Ns.IAddOnContentManager: 10

Guest Stack Trace:
Process: Service, PID: 93

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0A 00 00 00 00 00 00 00   SFCI············
00000010   00 00 00 00 00 00 00 00  00 00 00 00               ············    

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[Ryujinx_1.0.6937_2021-06-25_02-25-18.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6712810/Ryujinx_1.0.6937_2021-06-25_02-25-18.log)

**Comment by Kryptuq** [comment]
Starting when Ignore Missing Services is ticked: 
![image](https://user-images.githubusercontent.com/68452851/123353209-4c163580-d561-11eb-9c33-c243b1ea254a.png)

**Comment by Kryptuq** [comment]
updated

**Comment by sxwebster** [comment]
i5-4590 16gb GTX 1060 3gb, barely achieving 1fps from load. AA changed from auto to 2x, all sound options tried. Unchecked bump DRAM to 6gb. 

Several recurring errors including the following samples:
00:09:31.206 |E| HLE.OsThread.6 AudioRenderer Update: Unmap of memory pool (address: 0x1f170f1000, size 0xa000) failed!
00:13:46.323 |E| Ryujinx.NvdecProcessor FFmpeg Log: [h264 @ 000002687ae3ea40] illegal short term buffer state detected
00:17:36.434 |E| HLE.OsThread.9 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 162582 took more than 1000ms, resuming execution...
00:18:46.652 |E| HLE.OsThread.9 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 172033 took more than 1000ms, resuming execution...

**Comment by Eli0t77** [comment]
Ignore missing services must be ticked or it will crash.
Works well in game (30 FPS) after doing this and caching some shaders.
The intro video is very slow

Ryujinx version 1.1.15

**Comment by Mateus109** [comment]
Was working perfectly on macOS, but a recent update to Ryujinx is now causing some texture flickering. Game otherwise runs great (60fps patch at x2 scaling on M1 Max)
![Tony Hawks Pro Skater](https://github.com/Ryujinx/Ryujinx-Games-List/assets/11629946/d318bd3c-a770-47db-aa7e-0fb147d21045)

**Comment by 0ffse7** [comment]
Game freezes every time I play. Tested with DLCs turned on and off and Ignore Missing Services on and off. Happens either way.

Game version: 1.0.3

Ryujinx version: 1.1.1217

System: Apple M2 Pro (MacOS Sonoma 14.3.1)

Error:
|W| HLE.GuestThread.71 KernelSvc : UnmapPhysicalMemory() = InvalidCurrentMemory

Log:
[Ryujinx_1.1.1217_2024-03-07_10-59-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14522567/Ryujinx_1.1.1217_2024-03-07_10-59-44.log)

**Comment by MisterPingouin** [comment]
MacBook Pro M2
Ruining v 1.1.1290

Works fine some tiny freeze and some glitch on video explaining the tricks otherwise it run well at 60fps.
Same problem on the flickering caracter as mentioned before on the menu.

**Comment by 0ffse7** [comment]
I got rid of the crashes by disabling "Use hypervisor". I also have "Ignore missing services" enabled as suggested above. Been playing for hours without crashes.

Light flickering in menus and on some levels is still present. Same goes for stuttering video in the tutorial and movies.

I can't get split screen multiplayer to work. I need to press A with the second controller, but it doesn't register. Other games work fine with multiplayer, so my controller settings should be fine.
