### ISSUE TITLE
Game Builder Garage [Status: In-game]

### ISSUE THREAD

**Issue by BearGamesStudio** [Ryujinx/Ryujinx-Games-List#3641]
#### Current on `master` : 1.0.6939

Game loads into first tutorial as intended, the apple never spawns, preventing you from continuing to tutorial

```
Last error returned.
None.
```

#### Screenshots :

![Screenshot 2021-07-03 173609](https://user-images.githubusercontent.com/73830999/124361104-438ac280-dc25-11eb-9e63-ab9aca42e400.png)
![Screenshot 2021-07-03 173615](https://user-images.githubusercontent.com/73830999/124361105-45ed1c80-dc25-11eb-9654-ee093696a75a.png)

**Comment by user670** [comment]
Not only does the apple not spawn, but also
- in touch control mode (which can be set in in-game settings), dragging mouse on the emulated screen doesn't allow you to connect nodons (despite other touch functions work, like advancing dialog and navigating menus). Nodons can still be connected by using controller.
- emulator crashed on me. I'll try a few times to see if it's consistent in the future, but I don't feel like trying now.

Windows 10 x64, Intel CPU, NVIDIA GPU, emulator version 1.1.119.

**Comment by LukeWarnut** [comment]
## Game Builder Garage

#### Game Update Version : 1.0.0

#### Current on `master` : 1.1.199

Game loads with multiple issues.

Issues:
- Shadows are much darker than they should be.
- Touch screen does not work in the editor, but does in menus.
- I experienced a deadlock while exiting the texture nodon's settings.
- Ryujinx crashed after idling in a game.
- Ryujinx crashed with a missing service error when going into the settings of the IR sensor nodon.
- Using the scroll wheel with direct mouse access on renders the editor unusable
- Ryujinx crashes when attempting to share or recieve a game online or locally.

```
00:08:52.423 |E| HLE.OsThread.6 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey , TValue , InsertionBehavior )
   at Ryujinx.HLE.HOS.Services.IpcService.MakeObject(ServiceCtx context, IpcService obj) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 219
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManagerServer.GetAudioDeviceServiceWithRevisionInfo(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManagerServer.cs:line 103
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 219
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 138
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 86
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261
   at System.Threading.Thread.StartCallback()
```
```
00:06:14.575 |E| HLE.OsThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Hid.Irs.IIrSensorServer: 318

Guest Stack Trace:
Process: Service, PID: 93

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  3E 01 00 00 00 00 00 00   SFCI····>·······
00000010   00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00   ················
00000020   40 0D 03 00                                        @···            

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 156
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 219
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 138
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 86
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261
```
```
00:00:50.976 |E| HLE.OsThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Pctl.ParentalControlServiceFactory.IParentalControlService: 1017

Guest Stack Trace:
Process: Service, PID: 93

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  F9 03 00 00 00 00 00 00   SFCI····ù·······
00000020   00 00 00 00 00 01 00 00                            ········        

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 156
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 219
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 138
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 86
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261
```

#### Hardware Specs : 

##### CPU: AMD Ryzen 5 2600
##### GPU: NVIDIA GTX 1660 SUPER
##### RAM: 16GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/2420
https://github.com/Ryujinx/Ryujinx/issues/3108

#### Screenshots :

![image](https://user-images.githubusercontent.com/65521430/181936446-954002c8-27dd-4309-abe2-c600ce73324a.png)
![image](https://user-images.githubusercontent.com/65521430/181936559-68ab9b5c-bbe6-4d8f-9fd2-8dd50311891b.png)
![image](https://user-images.githubusercontent.com/65521430/181936581-98e23b34-efce-45b8-85c0-4861c1b8d549.png)
![image](https://user-images.githubusercontent.com/65521430/181936589-2284cccb-d06e-47c3-83df-6e9aca8e6ea9.png)
![image](https://user-images.githubusercontent.com/65521430/181936607-cc56aedb-dcda-441d-a124-14c47f477468.png)

#### Log file :

[GBG-IdleCrash.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9227089/GBG-IdleCrash.log)
[GBG-IRCrash.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9227111/GBG-IRCrash.log)
[GBG-OnlineCrash.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9227124/GBG-OnlineCrash.log)
[GBG-TextureDeadlock.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9227090/GBG-TextureDeadlock.log)

**Comment by matthew-211** [comment]
#### Emulator Build Version: 1.1.1287
#### Game Update Version: 1.0.2
LDN works when sharing to Ryujinx, but any attempt to share from Ryujinx brings up error 2110-0631 on guest Switch consoles.
![2024042015342400-1AB131B6E6571375B79964211BB3F5AE](https://github.com/Ryujinx/Ryujinx-Games-List/assets/155031549/e6780c3b-0352-4c90-85a9-1f5789ae0e50)
