### ISSUE TITLE
Miitopia - 01003DA010E8A000

### ISSUE THREAD

**Issue by Arekkusuda** [Ryujinx/Ryujinx-Games-List#3644]
#### Current on `master` : 1.0.6956

The game has a lot of stutters and even some freezes while generating shader cache. After that, the game seems able to run pretty well (30fps most of the time). Its possible to use the makeup and wig options ingame, but trying to make a Mii ingame will crash the emulator

```
00:08:19.274 |E| HLE.OsThread.15 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: MiiEdit applet is not implemented.
```

#### Screenshots :
![2021-07-08_14-55](https://user-images.githubusercontent.com/83657761/124991729-4576cc00-dfff-11eb-8c5e-c7843e11afe8.png)

![2021-07-08_15-00](https://user-images.githubusercontent.com/83657761/124991768-5293bb00-dfff-11eb-9d86-6a99d33327e7.png)

![2021-07-08_15-02](https://user-images.githubusercontent.com/83657761/124991946-8ec71b80-dfff-11eb-8ed6-0b06768a4c87.png)

**Comment by Pf-16** [comment]
Hello, I'd like to add that when trying to get through a specific part of a game you will end up with crash showing an error looking like this and you cannot have any workaround in-game to get past it.

Game Update Version : 1.0.3
Ryujinx version: 1.0.6957 (master)

Hardware specs:

CPU: i5-10600KF
RAM: 16GB
GPU: NVIDIA RTX 3060Ti

This is the error I get

```
00:04:51.341 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x3390F8000..0x33914DE00 is not fully mapped.
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size)
   at Ryujinx.Graphics.Gpu.Image.TextureCache.FindOrCreateTexture(MemoryManager memoryManager, TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range)
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings()
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings(GpuState state)
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount)
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount)
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument)
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
   at Ryujinx.Ui.RendererWidgetBase.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```
![image](https://user-images.githubusercontent.com/46072423/125040274-bcf83a00-e097-11eb-84d0-8703b758e872.png)

(after going through this point and sleeping at the inn will make the game crash making it impossible to proceed)

**Comment by donaldnemesis** [comment]
Ryujinx crashes when I attempt to choose the Cleric or Mage role before first fight

Game Update Version : 1.0.3
Ryujinx version: 1.0.6961

Hardware spec:
AMD Ryzen 7 4800H
NVIDIA GTX 1650 ti
16gb ram

The error log while I attempt to use Cleric:
[Ryujinx_1.0.6961_2021-07-11_18-12-19.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6797769/Ryujinx_1.0.6961_2021-07-11_18-12-19.log)

The error log while I attempt to use Mage:
[Ryujinx_1.0.6961_2021-07-11_18-32-40.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6797772/Ryujinx_1.0.6961_2021-07-11_18-32-40.log)

**Comment by donaldnemesis** [comment]
> Ryujinx crashes when I attempt to choose the Cleric or Mage role before first fight
> 
> Game Update Version : 1.0.3
> Ryujinx version: 1.0.6961
> 
> Hardware spec:
> AMD Ryzen 7 4800H
> NVIDIA GTX 1650 ti
> 16gb ram
> 
> The error log while I attempt to use Cleric:
> [Ryujinx_1.0.6961_2021-07-11_18-12-19.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6797769/Ryujinx_1.0.6961_2021-07-11_18-12-19.log)
> 
> The error log while I attempt to use Mage:
> [Ryujinx_1.0.6961_2021-07-11_18-32-40.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6797772/Ryujinx_1.0.6961_2021-07-11_18-32-40.log)

Oops I forget to post screenshot
![bandicam 2021-07-11 18-06-11-080](https://user-images.githubusercontent.com/87284218/125212008-6eee5c80-e278-11eb-9b3a-e65c24c50a5e.jpg)

![bandicam_2021-07-10_12-25-40-181](https://user-images.githubusercontent.com/87284218/125212019-7ada1e80-e278-11eb-9dd3-a88ad51558f6.jpg)

**Comment by Mr-Foxtrot** [comment]
I too am having the same fatal crash, but it turns out you don't even have to have the Mage/Cleric in your party. They can be at an inn and the game will still continue to crash at specific points.

Important bit of the log is pasted below. Here is also a link to the full log.
[Ryujinx_1.0.6976_2021-07-29_05-14-29.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6899487/Ryujinx_1.0.6976_2021-07-29_05-14-29.log)

```
00:04:13.797 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x33A257000..0x33A282400 is not fully mapped.
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size)
   at Ryujinx.Graphics.Gpu.Image.TextureCache.FindOrCreateTexture(MemoryManager memoryManager, TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range)
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings()
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.CommitBindings()
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount)
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
   at Ryujinx.Ui.RendererWidgetBase.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
If I attempt to follow this path, and take either fork of the road: reaching an inn will cause the emulator to freeze and close.
![image](https://user-images.githubusercontent.com/45246118/127467642-8b8d9993-11dd-4296-b974-f11c466dc227.png)

A video, showing I don't even have my mage/cleric in the party (at an Inn) and when exactly the crash happens.
https://user-images.githubusercontent.com/45246118/127468057-c9c3d936-0d2d-4769-b72e-8b5ff612e327.mp4

**Comment by Amiiban** [comment]
I get a crash whenever I recieve the letter from the worried mother (Ignore the google translate mod I know that is not causing the crash because i removed the file and it still happened.)
![Ryujinx 1 0 6956 - Miitopia v1 0 3 (01003DA010E8A000) (64-bit) 08_07_2021 10_57_05](https://user-images.githubusercontent.com/88581946/128598649-1ceed01a-ee25-4551-8e9f-138304e2d65e.png)

**Comment by gh34777** [comment]
## Miitopia

#### Game Update Version : 1.0.3

#### Current on `master`  Build Version : *(1.0.6982)*
#### Hardware Specs : 

##### CPU: Intel Core i7-6820HQ
##### GPU: NVIDIA Quadro M1000M
##### RAM: 16GB

#### Hi, I'd like to report that when entering this specific section, where a cut scene played, the game will crash. This is the error I got, and the full log

Full log
[Ryujinx_1.0.6982_2021-08-11_18-35-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6968143/Ryujinx_1.0.6982_2021-08-11_18-35-49.log)

Actual error
[actual error.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/6968168/actual.error.txt)

#### Screenshot of the location of where I got the error

![ryujinx_capture_2021-08-11_18-37-05_LI](https://user-images.githubusercontent.com/88777521/129025087-34feacce-db71-4625-b81e-860b61c2e8ab.jpg)

**Comment by Olgie** [comment]
Hello, I'd like to add that when trying to get through a specific part of a game you will end up with a crash showing an error looking like this and you cannot have any workaround in-game to get past it.

Game Update Version : 1.0.0
Ryujinx version: 1.0.7000 

Hardware specs:

CPU: i7-5500U
RAM: 16274 MB
GPU: NVIDIA Corporation

This is the error I get when rescued princess face cutscene shows up and then it ends and crashes
![welpunplayable](https://user-images.githubusercontent.com/34794689/130234598-ca68a16a-e03f-48c4-b342-abc70f68d6e6.PNG)

And Full Logs
[Ryujinx_1.0.7000_2021-08-20_15-35-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7021486/Ryujinx_1.0.7000_2021-08-20_15-35-28.log)

**Comment by GtRblx** [comment]
So for anybody that cant progress the game due to a crash at one point in the game I know how to avoid it but its bad news for your storage and that is just switch to another emulator such as Yuzu just need to put your save data into Yuzu and you can continue the game and if your going to create a mii then switch over to ryujinx and create your mii

**Comment by Olgie** [comment]
> So for anybody that cant progress the game due to a crash at one point in the game I know how to avoid it but its bad news for your storage and that is just switch to another emulator such as Yuzu just need to put your save data into Yuzu and you can continue the game and if your going to create a mii then switch over to ryujinx and create your mii

So now what
I grabbed user save data  From Ryujinx and send it to yuzu
well the problem is that when I launched I got into the menu screen, mii characters part works fine and so menu, but I meant that when I enter into Start screen, it gets a black screen, my fps drops to 0 and it freezing my computer and crashes it
And it sometimes it freezes doesn't load the menu either
is it really a problem that goes to my GPU driver or its the game's problem?
![image](https://user-images.githubusercontent.com/34794689/130348818-16fde039-56b8-4307-83af-3a9f625ed34f.png)

**Comment by GtRblx** [comment]
> > So for anybody that cant progress the game due to a crash at one point in the game I know how to avoid it but its bad news for your storage and that is just switch to another emulator such as Yuzu just need to put your save data into Yuzu and you can continue the game and if your going to create a mii then switch over to ryujinx and create your mii
> 
> So now what
> I grabbed user save data From Ryujinx and send it to yuzu
> well the problem is that when I launched I got into the menu screen, mii characters part works fine and so menu, but I meant that when I enter into Start screen, it gets a black screen, my fps drops to 0 and it freezing my computer and crashes it
> And it sometimes it freezes doesn't load the menu either
> is it really a problem that goes to my GPU driver or its the game's problem?
> **(UPDATE: Nevermind, It turns out I dont have to insert "replay" or "acHistory" folders into user data)**
> ![image](https://user-images.githubusercontent.com/34794689/130348818-16fde039-56b8-4307-83af-3a9f625ed34f.png)

I don't really know its probably your GPU driver because the game works fine when am switching save files to Ryujinx or Yuzu I have encountered crashes such as the princess face being returned I switched over to Yuzu and it works fine

**Comment by Mr-Foxtrot** [comment]
Miitopia
Game Update Version : 1.0.3
Ryujinx version: 1.0.6976

Hardware:
CPU: Intel Core i7-9700K
GPU: NVIDIA RTX 2070 SUPER
RAM: 16 GB

Despite testing with a few of the newer updates, the game still crashes at the same specific points.
No hacks or enhancements were enabled for this log, and during testing the game still would crash with hacks/enhancements.

Important bit of the log is pasted below. Here is also a link to the full log.
[Ryujinx_1.0.7023_2021-08-31_02-26-26.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7081716/Ryujinx_1.0.7023_2021-08-31_02-26-26.log)

`00:00:26.440 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x317478000..0x3174A3400 is not fully mapped.
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size)
   at Ryujinx.Graphics.Gpu.Image.TextureCache.FindOrCreateTexture(MemoryManager memoryManager, TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range)
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings()
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.CommitBindings()
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount)
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.MME.Macro.Execute(ReadOnlySpan`1 code, IDeviceState state)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`

Screenshot of the location of where I got the error
![image](https://user-images.githubusercontent.com/45246118/131453667-81b0109e-9235-4397-810f-c1027b3315f9.png)

It is the same location as @gh34777 , so there is some consistency here with the crash locations.

**Comment by awoomyn** [comment]
Miitopia
Game Update Version : 1.0.3

Hardware:
CPU: Intel Core i5-10400
GPU: Intel UHD Graphics 630
RAM: 12 GB

After reaching the postgame, Switching from Vampire back to Mage seems to crash my game every time I try it.

[Ryujinx_1.0.7024_2021-09-03_14-49-14.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7108003/Ryujinx_1.0.7024_2021-09-03_14-49-14.log)

**Comment by gdkchan** [comment]
Can someone attach a save near the location that causes, the crash along with steps to reproduce?

**Comment by gh34777** [comment]
> ## Miitopia
> #### Game Update Version : 1.0.3
> #### Current on `master` Build Version : _(1.0.6982)_
> #### Hardware Specs :
> ##### CPU: Intel Core i7-6820HQ
> ##### GPU: NVIDIA Quadro M1000M
> ##### RAM: 16GB
> #### Hi, I'd like to report that when entering this specific section, where a cut scene played, the game will crash. This is the error I got, and the full log
> Full log
> [Ryujinx_1.0.6982_2021-08-11_18-35-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6968143/Ryujinx_1.0.6982_2021-08-11_18-35-49.log)
> 
> Actual error
> [actual error.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/6968168/actual.error.txt)
> 
> #### Screenshot of the location of where I got the error
> ![ryujinx_capture_2021-08-11_18-37-05_LI](https://user-images.githubusercontent.com/88777521/129025087-34feacce-db71-4625-b81e-860b61c2e8ab.jpg)



> Miitopia
> Game Update Version : 1.0.3
> Ryujinx version: 1.0.7023
> 
> Hardware:
> CPU: Intel Core i7-9700K
> GPU: NVIDIA RTX 2070 SUPER
> RAM: 16 GB
> 
> Despite testing with a few of the newer updates, the game still crashes at the same specific points.
> No hacks or enhancements were enabled for this log, and during testing the game still would crash with hacks/enhancements.
> 
> Important bit of the log is pasted below. Here is also a link to the full log.
> [Ryujinx_1.0.7023_2021-08-31_02-26-26.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7081716/Ryujinx_1.0.7023_2021-08-31_02-26-26.log)
> 
> ```
> 00:00:26.440 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x317478000..0x3174A3400 is not fully mapped.
>    at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size)
>    at Ryujinx.Graphics.Gpu.Image.TextureCache.FindOrCreateTexture(MemoryManager memoryManager, TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range)
>    at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id)
>    at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex)
>    at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings()
>    at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.CommitBindings()
>    at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount)
>    at Macro(MacroJitContext , IDeviceState , Int32 )
>    at Ryujinx.Graphics.Gpu.Engine.MME.Macro.Execute(ReadOnlySpan`1 code, IDeviceState state)
>    at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall)
>    at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer)
>    at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
>    at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0()
>    at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> ```
> 
> Screenshot of the location of where I got the error
> ![image](https://user-images.githubusercontent.com/45246118/131453667-81b0109e-9235-4397-810f-c1027b3315f9.png)
> 
> It is the same location as @gh34777 , so there is some consistency here with the crash locations.

This issue still occurs in Ryujinx 1.0.7024, but now I'll attach my save folder and how to recreate the crash

_Go to the Underground Maze, enter the locked door in front of the Genie. Normally a cutscene would play, but at this point the game will crash, with or without hacks/enhancements. Leaving the settings by default will also crash the game at this point._

Since @Mr-Foxtrot has the same issue, I assume that posting the save file would matter a lot since we don't share the same hardware specs, so here it is, along with the logs
[Ryujinx_1.0.7024_2021-09-07_12-11-56.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7119210/Ryujinx_1.0.7024_2021-09-07_12-11-56.log)
[error log.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/7119231/error.log.txt)
[save_backup.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/7119218/save_backup.zip)

**Comment by Amiiban** [comment]
Well all of these crashes involve the Wizard or a cleric so it must be something to do with them.

**Comment by Toppii** [comment]
Miitopia
Game Update Version : 1.0.3
Ryujinx version: 1.0.7024

Hardware:
CPU: Intel Core i5-9600K
GPU: NVIDIA GeForce GTX 1060 6GB
RAM: 32 GB

Game crashes  after Citrus Cave first dot cutscene

[Ryujinx_1.0.7024_2564-09-09_17-04-53.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7135664/Ryujinx_1.0.7024_2564-09-09_17-04-53.log)

**Comment by Mr-Foxtrot** [comment]
> This issue still occurs in Ryujinx 1.0.7024, but now I'll attach my save folder and how to recreate the crash
> 
> _Go to the Underground Maze, enter the locked door in front of the Genie. Normally a cutscene would play, but at this point the game will crash, with or without hacks/enhancements. Leaving the settings by default will also crash the game at this point._
> 
> Since @Mr-Foxtrot has the same issue, I assume that posting the save file would matter a lot since we don't share the same hardware specs, so here it is, along with the logs
> [Ryujinx_1.0.7024_2021-09-07_12-11-56.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7119210/Ryujinx_1.0.7024_2021-09-07_12-11-56.log)
> [error log.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/7119231/error.log.txt)
> [save_backup.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/7119218/save_backup.zip)

Here is my save data as well, hopefully this can be fixed as I basically cannot progress past the crash.
[0000000000000002.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/7184163/0000000000000002.zip)

**Comment by Wiese2007** [comment]
> 
> 
> Well all of these crashes involve the Wizard or a cleric so it must be something to do with them.

i have the same issue and my team has an scientist, an thief, an chef and an imp.

**Comment by TonkyTc** [comment]
> > Well all of these crashes involve the Wizard or a cleric so it must be something to do with them.
> 
> i have the same issue and my actual team has an scientist, an thief, an chef and an imp.
> 
> edit: have found a way -> copied the save to yuzu just for the cutscene xD

Hi, could you tell me how to copy the save datas, please?

**Comment by Wiese2007** [comment]
> its easy just rightclick on the game in ryujinx and in yuzu and there are options to open the savefolder. Then just copy from ryujinx to yuzu. after the cutscene you can sent it back. at the end i needed todo this for 4 cutscences.

**Comment by josedanielsteller** [comment]
## Miitopia

#### Game Update Version : *1.0.3*

#### Current on `master` : Emulator Build Version : *1.1.329*

#### Graphics Backend : *OpenGL*

For some reason, the Squire Sword has a shader issue--if it appears, its shiny gray shader is also applied to the armor.
[Recently restarted my save file, so I don't know if the same happens with other armors.]

#### Hardware Specs : 

##### CPU: *Intel Core i5-10400F*
##### GPU: *AMD Radeon RX 560 Series*
##### RAM: *16GB*

#### Screenshots :

This is what it should look like [the issue doesn't happen with weapons other than the Squire Sword]:
![ryujinx_capture_2022-10-27_18-28-00](https://user-images.githubusercontent.com/69710618/198422144-663a7514-91e9-4685-a906-6b64b99d67e2.png)

This is what it looks like instead:
![ryujinx_capture_2022-10-27_18-27-39](https://user-images.githubusercontent.com/69710618/198422186-c4a813fb-381f-497b-bed7-085b78c45ca6.png)

**Comment by walletje** [comment]
### Miitopia

**Game Update Version** : _1.0.3_

**Emulator Build Version** : _1.1.0-macos1_

**Graphics Backend** : _Vulkan_

**Hardware Specs** :

CPU: _3,2 GHz 6-Core Intel Core i7_

GPU: _AMD Radeon RX 580 8GB_

RAM: _16GB_

I have been able to make Mii's and adding one to the game. But I can't get past the first town. Whenever I touch one of the standard Mii's or touch the scenery Ryujinx will crash. I've tried walking past everything yet there still seems to be some invisible thing that triggers that same reaction.

**Log File** : 
[Ryujinx_ 1.1.0-macos1_2023-03-30_13-53-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11111246/Ryujinx_.1.1.0-macos1_2023-03-30_13-53-46.log)

**Comment by isxtsoulz** [comment]
how do i download miitopia for it

**Comment by Youzbusrat** [comment]
how to install it pls

**Comment by noselaigu** [comment]
where can i install the rom?
