### ISSUE TITLE
Sky: Children of the Light - 0100c52011460000

### ISSUE THREAD

**Issue by EliEron** [Ryujinx/Ryujinx-Games-List#3647]
#### Current on `master` : 1.0.6959

Game boots, but produces no graphics. Sound plays but stops after a couple of seconds. After running for a little while the game prints a stack trace, and then Ryuginx itself crashes with an undefined instruction exception:

```
00:01:04.885 |E| HLE.GuestThread.20 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000008a4969c (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e)
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :
[SCOTL.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6796123/SCOTL.log)

**Comment by benderscruffy** [comment]
using 1.1.26
still the same status

**Comment by MetrosexualGarbodor** [comment]
This game requires an online connection to work on Switch, so it's likely not going to run on Ryujinx for a long time, if ever.

Video recorded by MutantAura: 

https://user-images.githubusercontent.com/79612681/163651647-8ad1aaf8-b99d-4aa5-8a20-e81882782c41.mp4
![unknown](https://user-images.githubusercontent.com/79612681/163651713-eda0524c-f92a-4f4c-8b06-0d0f560b2a88.png)

**Comment by sauradipdebnath** [comment]
Why is it hard to implement online on ryujinx

**Comment by MutantAura** [comment]
> Why is it hard to implement online on ryujinx

Connection to nintendo servers are explicitly blocked on purpose by the emulator. Connecting to a paid service via an emulator is not a clever idea.

**Comment by Shadowgeist12** [comment]
> Connection to nintendo servers are explicitly blocked on purpose by the emulator. Connecting to a paid service via an emulator is not a clever idea.

What if there was a way to connect to servers on other platforms? There's still Apple, Android, and even PlayStation to go off of, if any of those can be utilized. Last I checked, PS4 can be emulated on a Switch, so that _can_ be used to bypass the Nintendo server issue.

**Comment by EliEron** [comment]
> > Connection to nintendo servers are explicitly blocked on purpose by the emulator. Connecting to a paid service via an emulator is not a clever idea.
> 
> What if there was a way to connect to servers on other platforms? There's still Apple, Android, and even PlayStation to go off of, if any of those can be utilized. Last I checked, PS4 -- another system that can load Sky -- can be emulated on a Switch, so that _can_ be used to bypass the Nintendo server issue.

You must be misremembering something. There are no PS4 emulators for the Switch, and likely never will be given that the PS4 is quite a bit more powerful than the Switch itself. Not that there currently exist any mature PS4 emulators to begin with, as even PC based ones are in their infancy right now.

As for using the network of a different platform for the Switch game, this is not possible without significant reverse engineering and patching of the game, which is unlikely to occur. Especially since it would be a nightmare to maintain.
