### ISSUE TITLE
The Legend of Zelda:: Breath of the Wild Demo

### ISSUE THREAD

**Issue by Luminoso-256** [Ryujinx/Ryujinx-Games-List#3652]
#### Current on `master` : 1.0.6966

*Describe the current game state here.*

Game is decently playable - performance improves *significantly* on menus when Vsync is disabled. (with Vsync the game seems to be artificially capped at 20 FPS for whatever reason).

Main problem lies in the "Thanks for Playing!"  screen, wherein after the screen displays, the game blacks out, and FPS/FIFO both drop to 0.

a common exception throughout gameplay is:
```
00:02:39.274 |E| GUI.RenderLoop Gpu GLERROR: DebugSeverityHigh: GL_INVALID_OPERATION error generated. The source and destination internal formats are not compatible.
CallStack=   at System.Environment.get_StackTrace()
   at Ryujinx.Graphics.OpenGL.Debugger.GLDebugHandler(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam)
   at OpenTK.Graphics.OpenGL.GL.CopyImageSubData(Int32 srcName, ImageTarget srcTarget, Int32 srcLevel, Int32 srcX, Int32 srcY, Int32 srcZ, Int32 dstName, ImageTarget dstTarget, Int32 dstLevel, Int32 dstX, Int32 dstY, Int32 dstZ, Int32 srcWidth, Int32 srcHeight, Int32 srcDepth)
   at Ryujinx.Graphics.OpenGL.Image.TextureCopy.CopyUnscaled(ITextureInfo src, ITextureInfo dst, Int32 srcLayer, Int32 dstLayer, Int32 srcLevel, Int32 dstLevel, Int32 depth, Int32 levels)
   at Ryujinx.Graphics.OpenGL.Image.TextureView.CopyTo(ITexture destination, Int32 srcLayer, Int32 dstLayer, Int32 srcLevel, Int32 dstLevel)
   at Ryujinx.Graphics.Gpu.Image.TextureGroupHandle.Copy(TextureGroupHandle fromHandle)
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.CreateCopyDependency(Texture other, Int32 firstLayer, Int32 firstLevel, Boolean copyTo)
   at Ryujinx.Graphics.Gpu.Image.TextureCache.FindOrCreateTexture(MemoryManager memoryManager, TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range)
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings()
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.CommitBindings()
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount)
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
   at Ryujinx.Ui.RendererWidgetBase.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
00:02:39.274 |E| GUI.RenderLoop Gpu GLERROR: DebugSeverityHigh: GL_INVALID_OPERATION error generated. The source and destination internal formats are not compatible.
CallStack=   at System.Environment.get_StackTrace()
   at Ryujinx.Graphics.OpenGL.Debugger.GLDebugHandler(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam)
   at OpenTK.Graphics.OpenGL.GL.CopyImageSubData(Int32 srcName, ImageTarget srcTarget, Int32 srcLevel, Int32 srcX, Int32 srcY, Int32 srcZ, Int32 dstName, ImageTarget dstTarget, Int32 dstLevel, Int32 dstX, Int32 dstY, Int32 dstZ, Int32 srcWidth, Int32 srcHeight, Int32 srcDepth)
   at Ryujinx.Graphics.OpenGL.Image.TextureCopy.CopyUnscaled(ITextureInfo src, ITextureInfo dst, Int32 srcLayer, Int32 dstLayer, Int32 srcLevel, Int32 dstLevel, Int32 depth, Int32 levels)
   at Ryujinx.Graphics.OpenGL.Image.TextureView.CopyTo(ITexture destination, Int32 srcLayer, Int32 dstLayer, Int32 srcLevel, Int32 dstLevel)
   at Ryujinx.Graphics.Gpu.Image.TextureGroupHandle.Copy(TextureGroupHandle fromHandle)
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.CreateCopyDependency(Texture other, Int32 firstLayer, Int32 firstLevel, Boolean copyTo)
   at Ryujinx.Graphics.Gpu.Image.TextureCache.FindOrCreateTexture(MemoryManager memoryManager, TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range)
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex)
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings()
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.CommitBindings()
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount)
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
   at Ryujinx.Ui.RendererWidgetBase.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

After the game triggers it's "thank you for playing" screen and blacks out, the following warnings are returned in the log:
```
00:20:37.123 |W| HLE.GuestThread.22 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.123 |W| HLE.GuestThread.16 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.123 |W| HLE.GuestThread.18 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.123 |W| HLE.GuestThread.24 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.123 |W| HLE.GuestThread.25 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.21 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.26 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.27 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.28 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.36 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.38 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.42 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.29 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.45 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.49 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.30 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.51 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.31 KernelSvc PrintResult: SendSyncRequest64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.62 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.32 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.124 |W| HLE.GuestThread.33 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.125 |W| HLE.GuestThread.35 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.125 |W| HLE.GuestThread.37 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.125 |W| HLE.GuestThread.39 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.125 |W| HLE.GuestThread.41 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.125 |W| HLE.GuestThread.43 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.129 |W| HLE.GuestThread.44 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.130 |W| HLE.GuestThread.48 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.130 |W| HLE.GuestThread.54 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:20:37.130 |W| HLE.GuestThread.61 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
```

#### Screenshots :
![unknown](https://user-images.githubusercontent.com/63971285/125636516-0024f8fd-2209-425f-86c3-e83dbb4bead6.png)
![Screenshot 2021-07-14 090724](https://user-images.githubusercontent.com/63971285/125636186-bb22f8e8-a648-4006-9960-05f9b66d7809.png)
![Screenshot 2021-07-14 090611](https://user-images.githubusercontent.com/63971285/125636191-5917ffb8-e091-4945-b081-ba66ab34f789.png)

**Comment by AcK77** [comment]
> After the game triggers it's "thank you for playing" screen and blacks out, the following warnings are returned in the log

That seems to be an expected behavior since it since it’s a demo, the game just exit by itself.

**Comment by Luminoso-256** [comment]
True - could explain that pretty easily. Out of curiosity, if the game exits, why doesn't Ryujinx go back to the game selection screen and close emulation?

**Comment by tonylua** [comment]
![image](https://user-images.githubusercontent.com/7982504/209422240-125ad58c-5cc2-4931-93bd-4553d3bc3d19.png)
stay here
1.1.0 for macos
