### ISSUE TITLE
Monster wo taoshite tsuyoi ken ya yoroi wo te ni shinasai. Shinde mo akiramezu ni tsuyoku nari nasai. Yuushatai ga maoh wo taosu sono hi wo shinzite imasu. - モンスターを倒して強い剣や鎧を手にしなさい。死んでも諦めずに強くなりなさい。勇者隊が魔王を倒すその日を信じています。 - 01004E10142FE000

### ISSUE THREAD

**Issue by vojo915** [Ryujinx/Ryujinx-Games-List#3659]
## モンスターを倒して強い剣や鎧を手にしなさい。死んでも諦めずに強くなりなさい。勇者隊が魔王を倒すその日を信じています。

\* Abbreviation: モン勇 (Mon‐yuu)

#### Current on `master` : Commit Id *or* Build Version : 1.0.6974

Unstable. It is virtually impossible to play.

1. Basically, it crashes over time. It will crash over time even if no control is taken.
2. Regardless of 1, it can also crash before the title screen is displayed.

```
00:06:14.585 |E| HLE.GuestThread.20 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason)
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e)
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Screenshots :

![1_q99](https://user-images.githubusercontent.com/84438932/126284994-3d4ebfcd-99ab-41d8-8ce3-66e1612593d6.jpg)

![2_q99](https://user-images.githubusercontent.com/84438932/126285028-ea1d79b4-abfd-403e-a5cf-b93990c3ed9d.jpg)

![3_q99](https://user-images.githubusercontent.com/84438932/126285049-a74286d1-1c7d-417f-8218-b05bfe5ce9b7.jpg)

![4_q99](https://user-images.githubusercontent.com/84438932/126285065-ecd99bfc-728e-44a5-9df6-bc44690093e2.jpg)

![5_q99](https://user-images.githubusercontent.com/84438932/126285088-3e728783-2cb2-4c2c-826f-3b2360a96f56.jpg)

![6_q99](https://user-images.githubusercontent.com/84438932/126285228-376418cf-a462-4413-9f59-ad6a79510dfc.jpg)

![7_q99](https://user-images.githubusercontent.com/84438932/126285258-e607932b-8cb5-4ae8-95ab-af109b1fc21e.jpg)

#### Log file :

[Ryujinx_1.0.6974_01004E10142FE000_take_1+2+3.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/6846559/Ryujinx_1.0.6974_01004E10142FE000_take_1%2B2%2B3.zip)

**Comment by AcK77** [comment]
What about using `Host unchecked` instead of `Software` as memory management mode?

**Comment by vojo915** [comment]
> What about using `Host unchecked` instead of `Software` as memory management mode?

With that setting, the operation was stable and it never crashed. It's very stable.
