### ISSUE TITLE
Suguru Nature - 0100BF9012AC6000

### ISSUE THREAD

**Issue by vojo915** [Ryujinx/Ryujinx-Games-List#3660]
#### Current on `master` : 1.0.6974

Random crash. It is unpredictable when the crash will occur.

```
00:05:34.969 |E| HLE.GuestThread.18 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason)
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e)
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Screenshots :

![1_q99](https://user-images.githubusercontent.com/84438932/126314075-d62e3eb8-7c4e-4862-acf2-ad5829fd6bf8.jpg)

![2_q99](https://user-images.githubusercontent.com/84438932/126314102-bbd0af2f-730a-475f-8d66-8a0392671bbe.jpg)

![3_q99](https://user-images.githubusercontent.com/84438932/126314121-f5687982-9845-4957-9902-d59fe620b906.jpg)

#### Log file :

[Ryujinx_1.0.6974_0100BF9012AC6000.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6847745/Ryujinx_1.0.6974_0100BF9012AC6000.log)

**Comment by AcK77** [comment]
What about using `Host unchecked` instead of `Software` as memory management mode?

**Comment by vojo915** [comment]
> What about using `Host unchecked` instead of `Software` as memory management mode?

That setting no longer causes a crash. It's very stable. Sorry for the late report.
