### ISSUE TITLE
Cris Tales - 0100B0400EBC4000

### ISSUE THREAD

**Issue by vojo915** [Ryujinx/Ryujinx-Games-List#3662]
#### Current on `master` : 1.0.6974

- Crash with high probability in scenes that the player cannot operate, such as movie scenes (can be avoided by skipping for the time being).
- It also crashes over time. It is difficult to continue playing.
- FPS often drops to less than 10 at screen transitions. In normal times, 40-60 FPS.

```
00:08:46.247 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason)
   at Break64(Syscall64 , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(Object sender, InstExceptionEventArgs e)
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

#### Screenshots :

![1_q99](https://user-images.githubusercontent.com/84438932/126528616-3932c016-6441-4982-b853-0d1477cc9171.jpg)

![2_q99](https://user-images.githubusercontent.com/84438932/126528660-8015466e-1e83-4c8a-9c9a-3284bf99657b.jpg)

![3_q99](https://user-images.githubusercontent.com/84438932/126528683-0fd30403-4603-45cc-b2cd-d9ee7a5021e8.jpg)

![4_q99](https://user-images.githubusercontent.com/84438932/126528696-f646820d-3368-45dc-9662-38097304ec51.jpg)

![5_q99](https://user-images.githubusercontent.com/84438932/126528704-57a4683e-f05b-4529-83c4-baf652068119.jpg)

![6_q99](https://user-images.githubusercontent.com/84438932/126528728-1a6fc525-22b0-4c9e-a072-7de335073fa1.jpg)

![7_q99](https://user-images.githubusercontent.com/84438932/126528736-9f63afa9-c82c-4f1a-8f40-4885ab81b6a5.jpg)

![8_q99](https://user-images.githubusercontent.com/84438932/126528750-6fa0b543-f8e4-44c6-9f8d-744938cafd9b.jpg)

![9_q99](https://user-images.githubusercontent.com/84438932/126528762-fb6d49d7-70d2-43ce-9e04-e91160b00cf6.jpg)

#### Log file :

[Ryujinx_1.0.6974_0100B0400EBC4000_take_1+2.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/6857564/Ryujinx_1.0.6974_0100B0400EBC4000_take_1%2B2.zip)

**Comment by AcK77** [comment]
What about using `Host unchecked` instead of `Software` as memory management mode?

**Comment by vojo915** [comment]
> What about using `Host unchecked` instead of `Software` as memory management mode?

This setting stopped the crash from happening. It's very stable. Sorry for the delay in reporting.
