### ISSUE TITLE
MHR Choose character crash

### ISSUE THREAD

**Issue by jarvis1801** [Ryujinx/Ryujinx-Games-List#3673]
#### Current on `master` : LDN 2.3

Choose character crash

```
Last error returned.
00:05:24.935 |E| HLE.GuestThread.75 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:05:24.956 |E| HLE.GuestThread.75 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in C:\project\ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 214
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\project\ryujinx\ARMeilleure\Translation\Translator.cs:line 167
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\project\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1038
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

#### Hardware Specs : 

##### CPU: R5-3600X
##### GPU: 1660S
##### RAM: 32GB

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :

*Add screenshots here if the game rendering something.*

*(Optional section, remove it if unneeded)*

#### Log file :

*Add a link to the log file here.*

*(Optional section, remove it if unneeded)*

**Comment by gdkchan** [comment]
Post on the existing entry for this game #3465.
