### ISSUE TITLE
Spy Alarm - 01000E6015350000

### ISSUE THREAD

**Issue by edisionnano** [Ryujinx/Ryujinx-Games-List#3695]
#### Current on `master` : 1.0.7024

Crashes due to a missing services, works if missing services are ignored.

`
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Hid.Irs.IIrSensorServer: 308

Guest Stack Trace:
Process: Service, PID: 92

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  34 01 00 00 00 00 00 00   SFCI····4·······
00000010   00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00   ················
00000020   E0 93 04 00 00 00 00 00  00 08 00 00 00 00 00 00   à··············
00000030   08 00 1B 00 04 00 00 00  00 10 00 00 00 00 00 00   ················
00000040   00 00 00 00 00 00 00 00                            ········

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`

#### Outstanding Issues :

Ryujinx/Ryujinx#2126

#### Screenshots :
![image](https://user-images.githubusercontent.com/26039434/132099169-a3c98cc3-56c0-42c5-af08-d207f445f4da.png)
![image](https://user-images.githubusercontent.com/26039434/132099172-a33f5e1f-d6f3-47b9-88e8-84d383b42926.png)

**Comment by EmulationFanatic** [comment]
Updated
