### ISSUE TITLE
Sonic Colors Ultimate [010040E0116B8000]

### ISSUE THREAD

**Issue by szentigrad3** [Ryujinx/Ryujinx-Games-List#3712]
#### Current on `master` : 1.0.7024

*Crashed when pressed the start game*

```
Last error returned.
00:01:52.918 |I| HLE.GuestThread.69 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 91
   0x00000000096f7fdc	main:0x16f3fdc	
   0x00000000097c22e8	main:0x17be2e8	
   0x000000000e551508	subsdk2:0x344508	
   0x000000000e555cd4	subsdk2:0x348cd4	
   0x0000000000000000


00:01:52.925 |I| HLE.GuestThread.69 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0xebbca1a96e65db5e
	X[01]:	0x000000105a71d3a0
	X[02]:	0x0000000000000018
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x35c6d83b34394eae
	X[09]:	0x185313755837e423
	X[10]:	0x9ddfea08eb382d69
	X[11]:	0xbfd942bf67545b4e
	X[12]:	0x4f08560df6186ce3
	X[13]:	0xc949d7c7509e6557
	X[14]:	0xc3a5c85c97cb3127
	X[15]:	0xbe41013c00000000
	X[16]:	0x000000000ee8dff8
	X[17]:	0x000000000e557370 (subsdk2:0x34a370)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Leave()
	X[18]:	0x0000000000000000
	X[19]:	0x000000101cb551d8
	X[20]:	0x000000105a71cd50
	X[21]:	0x000000100fe509e8
	X[22]:	0x00000011d7afceb9 (SP:-0x00d9)
	X[23]:	0x000000105a71cd40
	X[24]:	0x000000105a71d3a0
	X[25]:	0x000000105a71cd50
	X[26]:	0x000000101157a020
	X[27]:	0x000000101cb551a0
	X[28]:	0x000000000ace6ac8
	FP:	0x00000011d7afce20 (SP:-0x0040)
	LR:	0x00000000097023f0 (main:0x16fe3f0)	=> 
	SP:	0x00000011d7afcde0 (SP)
	PC:	0x0000000000000000


00:01:52.925 |E| HLE.GuestThread.69 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFE8AC37CF000.
00:01:52.927 |I| HLE.OsThread.9 ServiceNv Create: Created map 455 with size 0x00004000!
00:01:52.928 |S| HLE.OsThread.8 ServiceHid SetSupportedNpadStyleSet: Stubbed. {appletResourceUserId: 4294967296 ; type: ProController, Handheld, JoyconPair}
00:01:52.935 |S| HLE.OsThread.8 ServiceHid SetSupportedNpadStyleSet: Stubbed. {appletResourceUserId: 4294967296 ; type: ProController, Handheld, JoyconPair}
00:01:52.981 |E| HLE.GuestThread.69 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

##### RAM: 32GB

[Ryujinx_1.0.7024_2021-09-08_20-25-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7128154/Ryujinx_1.0.7024_2021-09-08_20-25-49.log)

**Comment by INFINITY99K** [comment]
https://www.youtube.com/watch?v=GZffKowmRQM ,What about this?

**Comment by othmanead** [comment]
Sonic Colors Ultimate
#### Game Update Version : 1.0.9

#### Current on `master` : 1.1.341

#### Graphics Backend : Vulkan

*Describe the current game state here.*

Game plays with no issues

#### Hardware Specs : 

##### CPU: I5-10300H
##### GPU: NVIDI
##### RAM: *(e.g. 16GB)*

#### Pull requests needed :

*Add needed PR links here.*

*(Optional section, remove it if unneeded)*

#### Outstanding Issues:

*Add issue links here.*

*Example: https://github.com/Ryujinx/Ryujinx/issues/xxx (xxx = number issue)*

*(Optional section, remove it if unneeded)*

#### Screenshots :
![image](https://user-images.githubusercontent.com/106798110/201484055-2cb8843c-0005-4e2d-be8a-44ef996bb23d.png)
![image](https://user-images.githubusercontent.com/106798110/201484100-4b3a6be8-e639-4da2-a659-ca2afcd3d49a.png)
![image](https://user-images.githubusercontent.com/106798110/201484204-940cafda-75fe-458d-ba42-e8fb420460eb.png)
![image](https://user-images.githubusercontent.com/106798110/201484236-6586774c-8501-4762-b7d6-44800718b10f.png)

**Comment by EmulationFanatic** [comment]
Updated
