### ISSUE TITLE
Lost in Random - 01005FE01291A000

### ISSUE THREAD

**Issue by Djipi71** [Ryujinx/Ryujinx-Games-List#3724]
Lost in Random

Game Update Version : 1.0.1

Current Build use : 1.0.7047

Problem: The game don't start at all.

Last error returned: 

Marshaling row-activated signal
00:00:00.308 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.InvalidDataException: Section offset (0x1c000) and length (0x10a42c000) fall outside the total NCA length (0x97d30000).
   at LibHac.FsSystem.NcaUtils.Nca.OpenSectionStorage(Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorage(Int32 index, Boolean openEncrypted)
   at LibHac.FsSystem.NcaUtils.Nca.OpenRawStorageWithPatch(Nca patchNca, Int32 index)
   at LibHac.FsSystem.NcaUtils.Nca.OpenStorageWithPatch(Nca patchNca, Int32 index, IntegrityCheckLevel integrityCheckLevel)
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNca(Nca mainNca, Nca patchNca, Nca controlNca)
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNsp(String nspFile)
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen)
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

 Log file :

The log file is empty...i don't know why.

**Comment by Djipi71** [comment]
Build 7140 : Now game go in game, totally playable.

But there is a scaling problem , if we use upscale , many graphicals are red.

**Comment by MutantAura** [comment]
I've updated the listing but if you could edit you comment with any screenshots in-game that would be really helpful :)

**Comment by twain28** [comment]
> Build 7140 : Now game go in game, totally playable.
> 
> But there is a scaling problem , if we use upscale , many graphicals are red.

Actually...I got the same error of the initial bugtrack, and I can't seem to be able to run the game with either build 7140 nor the newest one...maybe it is just me?

![Ryufail](https://user-images.githubusercontent.com/8655008/147815530-c84fd456-952a-4d17-a85e-05ef5ee724ae.png)

**Comment by Djipi71** [comment]
here's the problem : 

Native:
![ryujinx_capture_2021-12-31_10-57-03](https://user-images.githubusercontent.com/35375131/147816807-1fe76c01-7510-4f69-8dbd-ce8294a5f791.png)

2X:
![ryujinx_capture_2021-12-31_10-56-51](https://user-images.githubusercontent.com/35375131/147816812-352bd396-ad01-45a6-93ec-02e604f3ec1a.png)

**Comment by wattunya** [comment]
Same error and Same error message happen for me.

**Comment by Niwu34** [comment]
## Lost in Random

#### Game Update Version : 1.ß.1

#### Current on `master` : 1.0.7170

Lost in Random boots and the performance is good most of the time. There are `dream areas` in which the Fps can drop to around 20fps.
The Fps is dynamic: Uncapping the guest vsync makes it possible to play with higher frames per second than 30 (60-80fps: depends on the area [using my hardware])
The Game does not work properly with the resolution scaler yet as it adds a red silhouette to the image.

#### Hardware Specs : 

##### CPU: *Ryzen 5 5600X @4,7 Ghz*
##### GPU: *Nvidia RTX 2080 Ti*
##### RAM: *32Gb @ 3200 Mhz*

*Add issue links here.*
https://github.com/Ryujinx/Ryujinx/issues/1488

#### Screenshots :
![1](https://user-images.githubusercontent.com/67392333/149202749-af1758af-a950-4c70-be06-6d1ea7b633aa.png)
![2](https://user-images.githubusercontent.com/67392333/149202767-094aff20-6921-4220-b389-9ac82d57f8af.png)
![6](https://user-images.githubusercontent.com/67392333/149203284-ff1ee002-e055-4936-9dce-577a50a7be4c.png)

Native:
![3](https://user-images.githubusercontent.com/67392333/149203078-28d6c7e6-abfd-465d-aa75-f0f1e8bdc0be.png)

4x Res
![4](https://user-images.githubusercontent.com/67392333/149203177-648b3de3-51d0-460e-9df8-c06bf339e4ca.png)

`Dream Area` which in which Ryujinx struggles to hit the intended 30fps
![5](https://user-images.githubusercontent.com/67392333/149203251-deaf3e38-51a1-4d36-aded-c5e7843fd641.png)

**Comment by MetrosexualGarbodor** [comment]
Updated with Niwu's comment.

**Comment by Gitphex** [comment]
The game doesn't even boot for me, i have the latest keys and firmware, should i use a special PR or something?

Thanks in advance. Greetings.
