### ISSUE TITLE
Metroid Dread - works like a charm - 'status-playable'

### ISSUE THREAD

**Issue by VegaBiggs** [Ryujinx/Ryujinx-Games-List#3730]
#### Current on `master` : 1.0.7066

Absolutely no issues at all to report ! (about halfway to the game it seems)

```
Last error returned.
none
```

#### Screenshots :
![image](https://user-images.githubusercontent.com/79387037/136636363-36959c98-a08f-4469-bd83-3dcc93b4b3d3.png)
![image](https://user-images.githubusercontent.com/79387037/136636450-347fd854-d0c9-4a9a-bd11-77f774419d6b.png)

**Comment by VegaBiggs** [comment]
Solid 60 fps (59.XX - 60.XX with v-sync) but I do have to cut off my downloads for some reason. Since the last patch
I have seen a weird lighting glitch inside elevators, that's it (I'll try to take a picture of it). Loadings are a bit hiccy maybe.

**Comment by KawaiiDinosaur** [comment]
Game is playable with solid performance. But I get some visual artifacts. Using an AMD card with latest drivers installed.

![ryujinx_capture_2021-10-10_02-46-46](https://user-images.githubusercontent.com/36821201/136686058-f448aed8-1042-48ef-84b2-ad9fd1725d48.png)
![ryujinx_capture_2021-10-10_03-22-46](https://user-images.githubusercontent.com/36821201/136686060-b98fd7a9-ed5a-40d1-9773-7e73e2fa4a01.png)

**Comment by dabbott12** [comment]
No issues yet. Only an hour in the game or so.
Game looks/feels amazing compared to native switch, which I've tried as well.

4k, 120hz CX
rtx 3080 ti
11700k
32gb ram
ssd
win 10

**Comment by KayloBlaze** [comment]
I'm getting severe FPS drops from 60 to 10-20 FPS but only in the elevator and teleporter loading screens. The rest of the game runs a smooth 60 FPS.

Hardware Specs

CPU: I7-8770k 
GPU: GTX1070ti-8GB
RAM: 16gb DDR4
Monitor 4k 144hz Freesync

**Comment by uofirob** [comment]
Ryujinx version: 1.0.7097 I've been having freezing issues in the zone with the x parasite.  1st it was at the Chozo Soldier boss battle.  I just got to phase 3 (the quicktime section) and the game just froze.  Next time I beat that, but on trying to hit the save point at the start of the zone, I started the save sequence and it froze.  here is the log: 
00:13:33.789 |I| Ptc Save: Saved Profiling Info (size: 209075 bytes, profiled functions: 62123).
00:14:33.786 |I| Ptc Save: Saved Profiling Info (size: 209075 bytes, profiled functions: 62123).
00:14:40.690 |S| HLE.OsThread.15 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 1}
00:15:03.787 |I| Ptc Save: Saved Profiling Info (size: 209114 bytes, profiled functions: 62135).
00:15:08.013 |S| HLE.OsThread.15 ServiceAm SetIdleTimeDetectionExtension: Stubbed. {idleTimeDetectionExtension: 0}
00:15:38.873 |W| HLE.GuestThread.14 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:15:38.874 |W| HLE.OsThread.9 ServiceNv Close: Closing channel
00:15:38.874 |W| HLE.OsThread.9 ServiceNv Close: Closing channel
00:15:38.874 |S| HLE.OsThread.15 ServiceAm UnlockExit: Stubbed. 
00:15:38.879 |I| HLE.OsThread.15 ServiceAm SetTerminateResult: Result = 0x00326e02 (ResultFsFileNotClosed (2002-6455)).
00:15:39.063 |I| HLE.GuestThread.14 Cpu PrintGuestStackTrace: Guest stack trace:
Process: GameApp, PID: 91
   0x000000007b1ac038	sdk:0x145038	
   0x000000007b1ac0f8	sdk:0x1450f8	
   0x000000007b21f6c0	sdk:0x1b86c0	nn::fs::detail::FileSystemAccessor::DumpUnclosedAccessorList(int, int)
   0x000000007b21f88c	sdk:0x1b888c	nn::fs::detail::FileSystemAccessor::~FileSystemAccessor():0x0014
   0x000000007b2209fc	sdk:0x1b99fc	nn::fs::detail::MountTable::Unmount(char const*):0x00cc
   0x000000007b2211e0	sdk:0x1ba1e0	nn::fs::Unmount(char const*):0x00a0
   0x0000000008136c8c	main:0x132c8c	
   0x000000007b3174c4	sdk:0x2b04c4	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000080000d4	rtld:0x00d4	


00:15:39.065 |I| HLE.GuestThread.14 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000004a5e308ec8 (SP:-0x01b8)
	X[02]:	0x0000000000000004
	X[03]:	0x000000000000000c
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000100000000
	X[09]:	0x000000007b067000 (sdk:0x0000)	=> 
	X[10]:	0x0000000000c696c8
	X[11]:	0x0000000000800000
	X[12]:	0x0000000000000000
	X[13]:	0x000000000000000e
	X[14]:	0x0000000000000002
	X[15]:	0x0000000000000000
	X[16]:	0x000000007b1ad870 (sdk:0x146870)	=> nn::diag::detail::Abort(nn::Result const*)
	X[17]:	0x000000007bcd06c8
	X[18]:	0x0000000000000000
	X[19]:	0x0000004a5e308ec8 (SP:-0x01b8)
	X[20]:	0x0000000000000000
	X[21]:	0x000000007ba85d5c
	X[22]:	0x000000007ba85d5c
	X[23]:	0x0000000000000000
	X[24]:	0x000000007ba85d5c
	X[25]:	0x0000004a5e308e90 (SP:-0x0180)
	X[26]:	0x000000007ba85d5c
	X[27]:	0x000000007b1ac0f8 (sdk:0x1450f8)	=> 
	X[28]:	0x0000000000000000
	FP:	0x0000004a5e308d10 (SP)
	LR:	0x000000007b1ad888 (sdk:0x146888)	=> nn::diag::detail::Abort(nn::Result const*):0x0018
	SP:	0x0000004a5e308d10 (SP)
	PC:	0x0000000000000000


00:15:39.066 |W| HLE.GuestThread.16 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.

**Comment by uofirob** [comment]
I just did the same sequence again (forgot about getting the powerbomb in the area) and yup, it does the same thing.  I think I'm done for tonight, but I'll try to go to a different save point to see if that helps anything

**Comment by uofirob** [comment]
I was able to get passed the crash by saving in a different zone.

**Comment by iinkshade** [comment]
I just updated to the most recent version of Ryujinx 1.0.7106 and the emulator has crashed multiple times since updating, game ran perfectly before with no issues other than the animation on the loading screens between zones looking choppy.  Crashes happen upon entering a new room.  I take a couple steps and then the crash happens.  Seems to happen randomly
[Ryujinx_1.0.7106_2021-11-16_17-56-32.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7551194/Ryujinx_1.0.7106_2021-11-16_17-56-32.log)
[Ryujinx_1.0.7106_2021-11-16_18-50-35.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7551196/Ryujinx_1.0.7106_2021-11-16_18-50-35.log)
.

**Comment by deposted** [comment]
CPU: Ryzen 3700x
GPU: 2070 Super
RAM: 32 GB

Game pretty much ran smoothly with 2x (1440p/2160p) resolution scale enabled. My only issue was that the game would eventually have audio desyncing issues for longer playthroughs. This would occur after 1-2 hours of playtime. 

Restarting the game seems to fix the audio desyncing. Delay would vary around 1-2 seconds.

**Comment by PostAngular** [comment]
CPU: AMD Ryzen 7 4800H
GPU: NVIDIA GeForce RTX 2060
RAM: 16 GB

   Application crashes during some cutscenes with closeups inside Samus's visor, I'll see if I can replicate it to get the log.
Also there are some problems with audio desync if the output is changed that are fixed by restarting Ryujinx and minor graphical glitches in elevators after updating from 1.0.7107 to 1.0.7108. 

Other than those issues the game runs smoothly at around 60 fps playing at native resolution with vsync on.

**Comment by CoonWorks** [comment]
Sometimes getting some FPS drops when it comes to transition cutscenes and artifacts, but most probably because of low-ish PC specs. Other than that, it runs on a smooth 30-60 FPS range during normal play with no other noteworthy issues.

CPU: Celeron G3900
RAM: 8 GB
GPU: Radeon R9 280x

**Comment by goptorry** [comment]
Solid 4K 60FPS Performance

Intel i7 9700K
nVidia GTX 1080
16GB DDR4
512GB nVMe 

![Metroid Dread](https://user-images.githubusercontent.com/96797158/147607178-ffcdc315-7e86-496c-bc9a-ad4aa4914bf1.jpg)

**Comment by d3ce1t** [comment]
After finishing the game and see credits it gets stuck in this screen

![image](https://user-images.githubusercontent.com/3706385/147826416-a7111580-758d-4928-9243-c2cfba0bd7b2.png)

**Comment by OmegaAtrocity** [comment]
Version: 2.1.0
Ryzen 7 3700x
GeForce 3080
16GB 3600 RAM


Played through entire game several times at 2x resolution and completed boss rush several times as well. Game works pretty much flawlessly, some loading screens have visual errors but that's all I could possibly report. Game stuttered a touch on the initial playthrough during intensive shader compilation.

**Comment by ScorelessPine** [comment]
Game version: 2.0.0
Emulator version: 1.1.111
Ryzen 2600x
RTX 2060
16GB RAM

The game often runs into crashing issues upon moving through Dairon, in particular, the lower right door after collecting Bombs and leaving via the bomb launcher. I suppose you could say this may not be entirely accurate to the base game report, due to the fact that I am reporting this after experiencing this many times in Randomizer. The attached log uses a Debug Logger mod for Dread, and is running a randomizer, hence the LUA:RANDO function calls, however the function call leading to the crash is vanilla. Below is the relevant exception from the log, and attached is the full log:
`00:05:27.738 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000007b365550 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1097
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
`
[Ryujinx_1.1.111_2022-05-03_06-05-24.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8610627/Ryujinx_1.1.111_2022-05-03_06-05-24.log)
Relevant issue from Ryujinx/Ryujinx repo: Ryujinx/Ryujinx#1340

**Comment by H-A-M-G-E-R** [comment]
[https://tenor.com/view/catsup-ketchup-mustard-cheeseburger-pickles-gif-14970294](url)

**Comment by H-A-M-G-E-R** [comment]
![catsup-ketchup](https://user-images.githubusercontent.com/98665992/174692973-e18e960d-09b6-4543-92a6-b9d03746e5dd.gif)

**Comment by Shock9616** [comment]
Game version 1.0.0
Emulator version: 1.1.0-macos1
Apple M1 Pro (8 core cpu, 14 core gpu)
16GB RAM

The game runs fantastically! It hits a solid 60fps throughout gameplay

**Comment by shingoxray** [comment]
> Game version 1.0.0 Emulator version: 1.1.0-macos1 Apple M1 Pro (8 core cpu, 14 core gpu) 16GB RAM
> 
> The game runs fantastically! It hits a solid 60fps throughout gameplay

Have you finished the game yet? I get crash when transfering to Burenia.

Game version: 2.1.0
Emulator version: Ryujinx-1.1.0-macos1-macos_universal and test-ava-ryujinx-1.1.800-macos_universal
Apple M1 Pro

**Comment by Shock9616** [comment]
Yes I've beaten it many times. Some vanilla playthroughs some with mods/randomizers, I've never had any issues with crashes

**Comment by shingoxray** [comment]
> Yes I've beaten it many times. Some vanilla playthroughs some with mods/randomizers, I've never had any issues with crashes

Thanks your replay. I found the problem. I used a bad XCI file.

**Comment by BloxBuiler301** [comment]
Where can you safely download the Metroid Dread game file

**Comment by BloxBuiler301** [comment]
> From your homebrewed Nintendo Switch. Anywhere else is piracy and can't be shared or linked to here

cool!

**Comment by gamobigz3** [comment]
As of Ryujinx Version 1.1.1065, This game is absolutely beatable and playable with 97% working speed.

Now there are some cutscenes where it lags a bit but it's not a big deal and sometimes my ryujinx crashes when near the gravity suit area.

![snip time 1](https://github.com/Ryujinx/Ryujinx-Games-List/assets/137640106/d55def27-038f-4de7-a417-df15e8a13486)


My Hardware specs
Rujinx Version: 1.1.1065
Game version: 2.1
Firmware/System Version: 16.0.3
CPU : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz ; 8 logical
GPU : NVIDIA GeForce GTX 1060
RAM : Total 16340 MiB ; Available 12731 MiB
