### ISSUE TITLE
Wheel of Fortune 010033600ADE6000

### ISSUE THREAD

**Issue by Azzhoe** [Ryujinx/Ryujinx-Games-List#3756]
#### Current on `master` : Commit Id *or* Build Version : 1.0.0+7887fc7

Game boots up fine, but when it gets to the Intro screen and asks to press a button to start it'll immediately crash.

```
Last error returned.
00:00:31.107 |E| HLE.GuestThread.14 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000009515658 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e)
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

##### RAM: 64GB

**Comment by Azzhoe** [comment]
Game is fully working now!

**Comment by EmulationFanatic** [comment]
Updated and marked as Needs More Attention

**Comment by dux6262** [comment]
Hi I am having this same problem. Is there any update?

**Comment by TCAtrevor** [comment]
Game worked fine for me. Did one quick round with no issue other than stutters.

**Comment by Maick90** [comment]
I'm having the same issue. Ryujinx version 1.11079. Game version 1.0.3. 
[Ryujinx_1.1.1079_2023-11-12_22-26-45.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13329076/Ryujinx_1.1.1079_2023-11-12_22-26-45.log)
