### ISSUE TITLE
Just Dance 2022 - 0100EA6014BB8000

### ISSUE THREAD

**Issue by miyukikame** [Ryujinx/Ryujinx-Games-List#3763]
#### Current on `master` : Commit Id *or* Build Version : 1.0.7098

*Crashes on boot with ServiceNotImplemented exception.*

```
00:00:05.274 |E| HLE.OsThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Pctl.ParentalControlServiceFactory.IParentalControlService: 1017

Guest Stack Trace:
Process: Service, PID: 92

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  F9 03 00 00 00 00 00 00   SFCI····ù·······
00000020   00 00 00 00 00 00 00 00                            ········        

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by LukeWarnut** [comment]
Corresponding issue:
https://github.com/Ryujinx/Ryujinx/issues/2420

**Comment by GTAWWEKID** [comment]
Use "Ignore Missing Services" hack to boot. Game is playable.
Settings>System>Hacks

**Comment by thomeval** [comment]
Like previous Just Dance games, this one suffers from mildly garbled video playback as well.
See: https://github.com/Ryujinx/Ryujinx/issues/2104

![image](https://user-images.githubusercontent.com/11618454/141157580-eaad8e69-4783-4a71-9c5b-1b6df9eaf223.png)

**Comment by thomeval** [comment]
As of version 1.1.330, the above issue is still present.

Hardware Specs:
CPU: Ryzen 5 5600x
GPU:  AMD Radeon RX 6700 XT
RAM: 16GB
