### ISSUE TITLE
DoDonPachi Resurrection - 怒首領蜂大復活 - 01005A001489A000

### ISSUE THREAD

**Issue by vojo915** [Ryujinx/Ryujinx-Games-List#3805]
#### Current on `master` : 1.0.7172

All game modes are freeze.

It freezes when loading after selecting the game mode.

There is no difference in symptoms depending on the memory emulation settings. Can reach the legal screen very rarely, but it still freezes.

**Unable to quit Ryujinx from normal method. Can quit from the console window only.**

#### Screenshots :

![1_q99](https://user-images.githubusercontent.com/84438932/149617171-4f6a9369-8597-4427-b723-ebe70e106f0d.jpg)
![2_q99](https://user-images.githubusercontent.com/84438932/149617174-a56f3856-39f1-47f8-a155-e4b81e985ecc.jpg)
![3_q99](https://user-images.githubusercontent.com/84438932/149617177-f5923c53-5a92-42f0-a5b6-d8ef15347a1b.jpg)
![4_q99](https://user-images.githubusercontent.com/84438932/149617183-40f47ecd-64be-43be-8a0e-f0eb7d073a44.jpg)

#### Log file :

No errors.

[Ryujinx_1.0.7172_01005A001489A000.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7874676/Ryujinx_1.0.7172_01005A001489A000.log)

**Comment by gdkchan** [comment]
Can you try the updated version of the game instead of the base version? I think they "fixed" the controller applet issue with the update, but I'm not sure.

**Comment by gdkchan** [comment]
Needs an update.

**Comment by vojo915** [comment]
**Current on `master` : 1.0.7174**

Can play in all modes.

However, it crashes after defeating the stage 3 boss.

**Last error:**

```
00:31:03.835 |E| HLE.GuestThread.22 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000098E79000.
00:31:03.918 |E| HLE.GuestThread.22 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in C:\projects\ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 220
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1182
```

**Screenshots:**

![100_q99](https://user-images.githubusercontent.com/84438932/149663569-8fc9ecf4-d9bd-4c2d-9ba7-ad35cc929501.jpg)
![101_q99](https://user-images.githubusercontent.com/84438932/149663575-0f577db3-f305-4fad-a4ea-5cf65f308571.jpg)
![102_q99](https://user-images.githubusercontent.com/84438932/149663582-c4b52807-aca2-4108-aef0-505d82c01236.jpg)

It crashed after stage 3 score result.

![103_q99](https://user-images.githubusercontent.com/84438932/149663600-0dd6ac97-9eba-452a-80d6-2cacbacbbe29.jpg)
![200_q99](https://user-images.githubusercontent.com/84438932/149663643-1de451f3-6134-401a-82ec-c80f12e85c94.jpg)
![201_q99](https://user-images.githubusercontent.com/84438932/149663651-ec03e650-f444-48bf-a4a6-e1a07aa55ef1.jpg)
![202_q99](https://user-images.githubusercontent.com/84438932/149663659-30591344-0c76-453d-83c9-bd81ae2a3e72.jpg)

**Log file:**

[Ryujinx_1.0.7174_01005A001489A000.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7877105/Ryujinx_1.0.7174_01005A001489A000.log)

**Comment by Eli0t77** [comment]
was able to complete the game (with continues) with no crashes

ryujinx 1.1.1110
game version 1.0.4
- ##### CPU: *i7-13700KF*
- ##### GPU: *NVIDIA RTX 4070 Ti*
- ##### GPU Driver version: *545.84*
- ##### RAM: *32GB*
