### ISSUE TITLE
Pokemon Legends: Arceus - 01001F5010DFA000

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx-Games-List#3817]
#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*

Game runs and plays without issues. Minor graphical issues on Vulkan and OpenGL on both AMD and Nvidia vendors.

#### Outstanding Issues:

-Protagonist changes sizes when doing animations (standing still, cutscenes when talking etc)

https://user-images.githubusercontent.com/2002038/151573350-be0c0201-c51f-4621-a004-177f0582d803.mp4

-Twitchy animations on characters

https://user-images.githubusercontent.com/2002038/151573383-b943accf-d313-40cc-b8b2-c0181f3c291c.mp4

-Tranparent dithering effect not present under trees and when pokemons break out of pokeball

-Oreburrow Tunnel has broken textures (OpenGL)
![Oreburrow Tunnel](https://user-images.githubusercontent.com/2002038/151573505-fe5300f9-5e6a-4087-a901-27fc79511b6e.PNG)

-Using styles shows broken textures (Vulkan)
![Styles](https://user-images.githubusercontent.com/2002038/151573534-94ec54c4-bed7-4b53-863e-240514b3e7bc.PNG)

-Vertex explosions (Vulkan)
![image](https://user-images.githubusercontent.com/2002038/151573689-e617de8e-d8f2-4d02-a928-65a2941d9c75.png)

-Vulcano fog in the distance at the beach looks buged sometimes (Vulkan)
![Fog](https://user-images.githubusercontent.com/2002038/151573743-ec740d96-e5f7-407d-81d8-1aeaf6ca9e6a.png)

-Random flickering graphics (Vulkan)

https://user-images.githubusercontent.com/2002038/151573783-37bae95c-98ca-47e8-bdab-06a10184978f.mp4

-Skybox texture(?) gets copied on water (OpenGl) (Random?)

https://user-images.githubusercontent.com/2002038/151573811-34647627-a852-4b04-aac7-aec0ba46a0d4.mp4

All things above and tested on real hardware and it doesn't reproduce the same effects.

#### Screenshots :
![Circle](https://user-images.githubusercontent.com/2002038/151574117-df6d3806-a800-48d9-92dc-7abb839d8957.PNG)
![Vulcano](https://user-images.githubusercontent.com/2002038/151574212-c247c8d7-f25c-4ac2-beb4-41b34372dfa1.PNG)
![Screen](https://user-images.githubusercontent.com/2002038/151574280-cf0ebb95-6733-424a-9aa8-35c3d5cc387b.jpg)

**Comment by Kakarot1397** [comment]
is local trade working?

**Comment by Kakarot1397** [comment]
i tried but error message keeps popping out

**Comment by MutantAura** [comment]
Discord reports say that if you reach the trade area on the LDN build (still buggy and not recommended for play) then trading does work p2p.

**Comment by Kakarot1397** [comment]
> is local trade working? i tried but an error msg is popping out



> Discord reports say that if you reach the trade area on the LDN build (still buggy and not recommended for play) then trading does work p2p.

but i am using only the latest build not LDN built:(

**Comment by genderist** [comment]
I've been trying to run this rom on the latest version, but the game keeps crashing after character selection, just before the title screen. Anyone else facing the same issues?

**Comment by GamerzHell9137** [comment]
> I've been trying to run this rom on the latest version, but the game keeps crashing after character selection, just before the title screen. Anyone else facing the same issues?

Join discord for support, this is just for reporting issues.

**Comment by KouutZ** [comment]
a

**Comment by tatuobai** [comment]
where to download

**Comment by Aedan1122** [comment]
how to download on pc?

**Comment by jperd21** [comment]
I've not been able to get this game to load. It either crashes completely, or freezes during the first cutscene. What information would be helpful in solving this? I am using AMD, and it fails using default settings and the Vulkan method

**Comment by MetrosexualGarbodor** [comment]
Search for your GPU drivers here https://www.amd.com/en/support and download the optional 22.1.2 drivers.

> I've not been able to get this game to load. It either crashes completely, or freezes during the first cutscene. What information would be helpful in solving this? I am using AMD, and it fails using default settings and the Vulkan method

**Comment by jperd21** [comment]
> Search for your GPU drivers here https://www.amd.com/en/support and download the optional 22.1.2 drivers.
> 
> > I've not been able to get this game to load. It either crashes completely, or freezes during the first cutscene. What information would be helpful in solving this? I am using AMD, and it fails using default settings and the Vulkan method

Thank you trying it now

**Comment by ISSHIGEN** [comment]
MetrosexualGarbodor told me to report here my issue.
It's happenned in the village, I was running, the FPS was at 30 and I saw it decreased a bit (around 20), It freezed for some seconds  and Ryujinx directly crashed (closed if you prefer). I'm playing with sky_moon_improvement Mod since some hours and LoD_wip_v2.2 Mod since 1 hour, this LOD mod is only an update of an existing one I used 1 day ago.
Note that I purged shader cache around 9 hours ago.

[Ryujinx_1.1.11_2022-01-29_21-35-00.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7964789/Ryujinx_1.1.11_2022-01-29_21-35-00.log)

**Comment by jperd21** [comment]
> Search for your GPU drivers here https://www.amd.com/en/support and download the optional 22.1.2 drivers.
> 
> > I've not been able to get this game to load. It either crashes completely, or freezes during the first cutscene. What information would be helpful in solving this? I am using AMD, and it fails using default settings and the Vulkan method

You're the best! It works great now!! Thank you so much!

**Comment by GamerzHell9137** [comment]
> MetrosexualGarbodor told me to report here my issue. It's happenned in the village, I was running, the FPS was at 30 and I saw it decreased a bit (around 20), It freezed for some seconds and Ryujinx directly crashed (closed if you prefer). I'm playing with sky_moon_improvement Mod since some hours and LoD_wip_v2.2 Mod since 1 hour, this LOD mod is only an update of an existing one I used 1 day ago. Note that I purged shader cache around 9 hours ago.
> 
> [Ryujinx_1.1.11_2022-01-29_21-35-00.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7964789/Ryujinx_1.1.11_2022-01-29_21-35-00.log)

iirc that happens rarely and random its a bug that happens on Sword and Shield too.

**Comment by Pluvialis98** [comment]
The starting city has a lot of graphical glitches where textures are all over, many characters are bliking in two different colours, some building are missing textures and are straight up invisible. Inside the building where we pick our starter the texture glitches covered the entire screen and I couldn't saw anything. Is there any way to fix these stuff yet or we can only wait?

**Comment by MetrosexualGarbodor** [comment]
@Pluvialis98 please come to Discord for support, this sounds like it can be solved

**Comment by PostAngular** [comment]
CPU: AMD Ryzen 7 4800H
GPU: NVIDIA GeForce RTX 2060
RAM: 16 GB

Game runs around 20 to 30fps pretty consistently but when an attack with a lot of particle effects loads in for the first time there's a lot of slowdown. After the first time the attack is used it runs at full speed though, so it could just be an issue of Ryujinx having to find where the effect is stored in the nsp file? I also experienced the broken textures in Oreburrow Tunnel that GamerzHell9137 reported.

May be irrelevant now but on 1.1.12 I experienced a creepypasta like bug with the player character's eye color:

https://user-images.githubusercontent.com/90218238/151681858-eab3128c-52ae-4034-9a8e-6790e0d57fe5.mp4

**Comment by Pluvialis98** [comment]
Another problem, the game freezes when I load my save, and doesn't fixes no matter how long I wait. The console shows this

![Screenshot_115](https://user-images.githubusercontent.com/89564966/151681883-f6bebb5e-a45d-4094-871d-7a7516f252e3.png)
![Screenshot_116](https://user-images.githubusercontent.com/89564966/151681889-ff72ba14-b62f-4c75-b051-35442d9f45bd.png)

**Comment by MutantAura** [comment]
> Another problem, the game freezes when I load my save, and doesn't fixes no matter how long I wait. The console shows this
> 
> ![Screenshot_115](https://user-images.githubusercontent.com/89564966/151681883-f6bebb5e-a45d-4094-871d-7a7516f252e3.png) ![Screenshot_116](https://user-images.githubusercontent.com/89564966/151681889-ff72ba14-b62f-4c75-b051-35442d9f45bd.png)

You are on an outdated version. Please manually update, we had to change our release provider so autoupdate no longer works.

**Comment by Pluvialis98** [comment]
> > Another problem, the game freezes when I load my save, and doesn't fixes no matter how long I wait. The console shows this
> > ![Screenshot_115](https://user-images.githubusercontent.com/89564966/151681883-f6bebb5e-a45d-4094-871d-7a7516f252e3.png) ![Screenshot_116](https://user-images.githubusercontent.com/89564966/151681889-ff72ba14-b62f-4c75-b051-35442d9f45bd.png)
> 
> You are on an outdated version. Please manually update, we had to change our release provider so autoupdate no longer works on builds before the changeover.

The 1.1.13? I already downloaded it

Or the game? Where do I download it? A friend passed me a link to the current one

**Comment by MutantAura** [comment]
Well the issues your describing have all had targeted patches. I'm really unsure why they're presenting themselves if you're on the latest version. As metro said you'd be better of joining the discord for support.

**Comment by Kakarot1397** [comment]
i tried local trading in ldn and in normal version(updated) its not working.
If u guys are abke to do please let me know here

**Comment by LavenderAndChamomile** [comment]
My game freezes when the lights turn into a ball and it bounces. I have fiddled around a bit and it still freezes.

**Comment by KawaiiDinosaur** [comment]
Windows 11 21H2
CPU: Ryzen 7 3700X
GPU: Radeon RX 5700 XT
Drivers: Adrenalin 22.1.2

Good performance but character models don't load.

![ryujinx_capture_2022-01-30_14-33-15](https://user-images.githubusercontent.com/36821201/151710717-1c1f9153-9d35-48de-a706-e2261943799f.png)

**Comment by s3327445** [comment]
test

**Comment by harris861009** [comment]
https://www.youtube.com/watch?v=b5F4pqiWa6c

does anyone know how  to fix this problem?><

**Comment by dennistsc** [comment]
> Windows 11 21H2 CPU: Ryzen 7 3700X GPU: Radeon RX 5700 XT Drivers: Adrenalin 22.1.2
> 
> Good performance but character models don't load.
> 
> ![ryujinx_capture_2022-01-30_14-33-15](https://user-images.githubusercontent.com/36821201/151710717-1c1f9153-9d35-48de-a706-e2261943799f.png)

i have the same problem the character is not showing. AMD GPU radeon 5000 ser
do you solve the problem?

**Comment by MetrosexualGarbodor** [comment]
Download the Vulkan build from the bottom link in this comment @dennistsc @KawaiiDinosaur  https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890255424

And please come to discord for help next time.

**Comment by dennistsc** [comment]
> discord

could you send me the discord link thanks you

**Comment by LavenderAndChamomile** [comment]
> > discord
> 
> could you send me the discord link thanks you

Me too, please?

**Comment by MetrosexualGarbodor** [comment]
https://discord.gg/ryujinx @LavenderAndChamomile @dennistsc

**Comment by LavenderAndChamomile** [comment]
> https://discord.gg/ryujinx @LavenderAndChamomile @dennistsc

Thanks you!

**Comment by IgiariValkyr** [comment]
I can confirm that the slowdown actually gets _worse_ in the village as the game progresses, with more NPCs showing up.

**Comment by LavenderAndChamomile** [comment]
> I can confirm that the slowdown actually gets _worse_ in the village as the game progresses, with more NPCs showing up.

I've tweaked the emulator's settings as best I could and I still get slowdown at times then massive speedups. Kinda funny when I goes from being stoned mode, to speed mode xD.

**Comment by guihg00d** [comment]
**Pokemon Legends Arceus crashes when loading game**

00:10:20.776 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorUnknown".
   at Ryujinx.Graphics.Vulkan.PipelineState.CreateGraphicsPipeline(VulkanGraphicsDevice gd, Device device, ShaderCollection program, PipelineCache cache, RenderPass renderPass) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineState.cs:line 338
   at Ryujinx.Graphics.Vulkan.PipelineBase.CreatePipeline(PipelineBindPoint pbp) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1103
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(PipelineBindPoint pbp) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1057
   at Ryujinx.Graphics.Vulkan.PipelineBase.Draw(Int32 vertexCount, Int32 instanceCount, Int32 firstVertex, Int32 firstInstance) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 234
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_41(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 145
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131

**Comment by DjanngooL** [comment]
como baixar o jogo ?

**Comment by tatudeterno** [comment]
where???!!!

**Comment by thiago0412** [comment]
como descargo el juego?

**Comment by MrRay0708** [comment]
Hi, Im having some issues trying to complete a specific mission. Everytime I try to deliver it, my game crashes and the console reports that:
![imagem_2022-02-05_181826](https://user-images.githubusercontent.com/98743274/152659365-3c7bb40b-2aa5-43ed-b374-ca2d076ccdab.png)

**Comment by FreeQ13131** [comment]
how to downoald?

**Comment by KawaiiDinosaur** [comment]
> how to downoald?

Stop asking this here.

**Comment by judge2020** [comment]
~2 second freeze and crash during Kleavor post-successful-fight cutscene. RTX 3080 Ti, AMD 3600x, Ryujinx 1.1.19
```
00:40:40.922 |E| GPU.MainThread Application : Unhandled exception caught: System.ArgumentException: Invalid floating point type "0".
   at Ryujinx.Graphics.Shader.Instructions.InstEmit.UnpackImm(EmitterContext context, DstFmt floatType, Boolean h, Int32 imm) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Instructions\InstEmitConversion.cs:line 396
   at Ryujinx.Graphics.Shader.Instructions.InstEmit.F2iI(EmitterContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Instructions\InstEmitConversion.cs:line 52
   at Ryujinx.Graphics.Shader.Translation.Translator.EmitOps(EmitterContext context, Block block) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 340
   at Ryujinx.Graphics.Shader.Translation.Translator.EmitShader(DecodedProgram program, ShaderConfig config, Boolean initializeOutputs, Int32& initializationOperations) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 193
   at Ryujinx.Graphics.Shader.Translation.TranslatorContext.Translate(ShaderProgramInfo& shaderProgramInfo, TranslatorContext nextStage, TranslatorContext other) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Translation\TranslatorContext.cs:line 142
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateShader(ShaderDumper dumper, MemoryManager memoryManager, TranslatorContext currentStage, TranslatorContext nextStage, TranslatorContext vertexA) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 1046
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(ThreedClassState& state, GpuChannel channel, GpuAccessorState gas, ShaderAddresses addresses)
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 1050
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 129
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 264
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 389
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 100
```

**Comment by SandySpuds** [comment]
My game wont load any characters or pokemon??

**Comment by Greezleee** [comment]
![image](https://user-images.githubusercontent.com/99158761/152722665-1e930a66-c5d2-45eb-8a69-076ee31e88bf.png)

Hi anyone, can help me solve this problem? because after this log shows error log, the game crashes and closes the app

**Comment by Satantoo** [comment]
Clouds in Alabaster Icelands are green when they should be white. 
I have installed and am running on the PR which fixes the gray caves, so this seems to be a different issue

![image](https://user-images.githubusercontent.com/58292533/152780469-80d900ae-6a16-447f-a7da-ba66d21f3a78.png)

**Comment by ISSHIGEN** [comment]
> Clouds in Alabaster Icelands are green when they should be white. I have installed and am running on the PR which fixes the gray caves, so this seems to be a different issue
> 
> ![image](https://user-images.githubusercontent.com/58292533/152780469-80d900ae-6a16-447f-a7da-ba66d21f3a78.png)

It's not a bug dude, it's due to the moment you are in the story. The color of the sky changed, so the color of the clouds change also. When you will have finish the story, it will come back normally. Think more next time before posting -_-

**Comment by Satantoo** [comment]
No, I won't since it was doing this even before. Thanks though for the insight

**Comment by LORYT699** [comment]
Game continue crash loading uxie's cave

**Comment by LORYT699** [comment]
can you pass me the .nsp cause I think mine is broken

**Comment by fhuga** [comment]
CPU: Ryzen 5 3600
GPU: RX 580 8GB
RAM: 16 Gb
Game freezes at this point audio continue

https://user-images.githubusercontent.com/99697742/153969638-950d8235-9959-4d97-98c3-df19d285c558.mp4

s

**Comment by MetrosexualGarbodor** [comment]
@fhuga please follow the [patreon guide](https://www.patreon.com/posts/pokemon-legends-61739749), you need the Vulkan build and the latest optional AMD drivers 
And next time ask for support on [discord](https://discord.gg/ryujinx), not on github

**Comment by LORYT699** [comment]
@MetrosexualGarbodor any suggestion for me?Could help changing game? I mean take another file of the same game anywhere?

**Comment by dariobduarte** [comment]
I have the RX 6800 XT video card and Ryujinx runs very poorly on my PC. When I play on Yuzu I play perfect without any problem and even if I put all the texture mods the game is still light and uses little GPU at 4k. But on Ryujinx It crashes, it doesn't accept resolution higher than the default which is 720p (horrible) Anyway. There is some incompatibility of my GPU with this emulator. Even using the vulkan version it runs very poorly. My processor is a new generation i7 and I have 16GB of Ram. Could anyone help?

**Comment by MetrosexualGarbodor** [comment]
> please follow the [patreon guide](https://www.patreon.com/posts/pokemon-legends-61739749), you need the Vulkan build and the latest optional AMD drivers And next time ask for support on [discord](https://discord.gg/ryujinx), not on github

@Duartangel

**Comment by Duartangel** [comment]
> > please follow the [patreon guide](https://www.patreon.com/posts/pokemon-legends-61739749), you need the Vulkan build and the latest optional AMD drivers And next time ask for support on [discord](https://discord.gg/ryujinx), not on github
> 
> @Duartangel

Thanks for help.

**Comment by saran001** [comment]
> I've not been able to get this game to load. It either crashes completely, or freezes during the first cutscene. What information would be helpful in solving this? I am using AMD, and it fails using default settings and the Vulkan method

Hi,
Facing similar issue.....Have latest AMD Radon (22.2.3) installed Ryzen 5700, 16 GB RAM.....Game goes till first cutscene and freezes after that. I'm using latest Ryujinx Vulkan Windows Release.

Logs :
[Ryujinx_logs.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/8192516/Ryujinx_logs.txt)

Image:
<img width="960" alt="Issue_Ryujinx" src="https://user-images.githubusercontent.com/19660860/156922566-e78929eb-d516-4822-b8a6-4dfb237d6024.png">

Stuck in this issue for a long time....Kindly help....

**Comment by MutantAura** [comment]
> Hi, Facing similar issue.....Have latest AMD Radon (22.2.3) installed Ryzen 5700, 16 GB RAM.....Game goes till first cutscene and freezes after that. I'm using latest Ryujinx Vulkan Windows Release.
> 
> Logs : [Ryujinx_logs.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/8192516/Ryujinx_logs.txt)
> 
> Image: <img alt="Issue_Ryujinx" width="960" src="https://user-images.githubusercontent.com/19660860/156922566-e78929eb-d516-4822-b8a6-4dfb237d6024.png">
> 
> Stuck in this issue for a long time....Kindly help....

As your image shows you're still using OpenGL. Head to settings -> graphics and switch the backend to vulkan.

**Comment by Blargle** [comment]
There is a weird outline bug where it is oddly shaped and seems to take on the colour of the water that is beyond it between the character and the outline when in verity cavern.
Video below was taken on 1.1.106 but it also apparently happens on vulkan.
https://user-images.githubusercontent.com/4081536/164344262-e4aab958-46f7-4775-9b8e-30edbaaf20ba.mp4
This is not my save but one from who reported the issue on discord.
[main.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/8526204/main.zip)

**Comment by GamerzHell9137** [comment]
> There is a weird outline bug where it is oddly shaped and seems to take on the colour of the water that is beyond it between the character and the outline when in verity cavern. Video below was taken on 1.1.106 but it also apparently happens on vulkan.
> 2022-04-21.01-06-47.mp4
> 
> This is not my save but one from who reported the issue on discord. [main.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/8526204/main.zip)

You could check on real hardware how it looks because that's exactly how it looks on real hardware.

**Comment by Blargle** [comment]
> > There is a weird outline bug where it is oddly shaped and seems to take on the colour of the water that is beyond it between the character and the outline when in verity cavern. Video below was taken on 1.1.106 but it also apparently happens on vulkan.
> > 2022-04-21.01-06-47.mp4
> > This is not my save but one from who reported the issue on discord. [main.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/8526204/main.zip)
> 
> You could check on real hardware how it looks because that's exactly how it looks on real hardware.

Yea I just had a look and seems that is how it is so it is accurate though more pronounced on ryujinx since the resolution is higher so you see the outline clearer. I was just reporting it from what someone said on discord since metro suggested making a comment on it after someone reported it and I just so happend to have time to quickly open it with their save and check.

**Comment by Kidakakash** [comment]
Hello, since the update of ryujinx in 1.1.107, I have light flashes on npcs or on pokemon. The ground sometimes disappears too. Am I the only one having this?

**Comment by r4ck3r** [comment]
Hi! Would alo like to report that between 1.1.107 and 1.1.110 I also have flashes and lines going out from npcs, pokemon and buildings, usually after some minutes playing. From 1.1.111 to 1.1.115 the game won't start at all (not even the initial screen). I had to downgrade to 1.1.106 to keep playing.

**Comment by MetrosexualGarbodor** [comment]
@r4ck3r the flashes were fixed on 1.1.109.[ After 1.1.110, you can't run this game if you have enabled "expand DRAM size to 6GB"](https://github.com/Ryujinx/Ryujinx/issues/3314). Disable it until it's fixed.

**Comment by NobodyCares6969** [comment]
Hey guys/Gals i'm tryna figure out how to work ryujinx i've been able to load and start the game the background loads and (ALMOST) everything works except the fact that I can't see any characters Npcs or my own character (Heres a Pic of what im seeing)
![Screenshot (2)](https://user-images.githubusercontent.com/106133699/169947364-6a317dd1-b7bb-4a1c-8bfb-0d5e9a82a25d.png)

**Comment by piplup55** [comment]
> Hey guys/Gals i'm tryna figure out how to work ryujinx i've been able to load and start the game the background loads and (ALMOST) everything works except the fact that I can't see any characters Npcs or my own character (Heres a Pic of what im seeing) Am I doing anything wrong???? ![Screenshot (2)](https://user-images.githubusercontent.com/106133699/169947364-6a317dd1-b7bb-4a1c-8bfb-0d5e9a82a25d.png)

this is not the place to ask for support, please join the discord https://discord.gg/ryujinx and ask there

**Comment by bzrajo** [comment]
@@@@@@@@@@@@@@@@@@@@@@@

**Comment by Salver98361** [comment]
lol how do i use it

**Comment by zwz5203311** [comment]
0123456474

**Comment by fpolg** [comment]
Hi,
I'm trying to play from a laptop with this requirements
Processor	Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, 2112 Mhz
RAM : 64GB
Graph: RTX3070 on an external dock (EGPU)

I have 1.1.0 Pokemon Arceus and the 60FPS for 1.1.0, but I think I've never managed more than 25 FPS (and for a few secs), normally 5-9 FPS


Is this CPU limitation or something else? I've activated/deactivated VSYNC, and other options as per several tutorials I've seen, but nothing happens  (actually only works on 50FPS when I'm in the room :)  )

thanks !!

**Comment by GamerzHell9137** [comment]
> Hi, I'm trying to play from a laptop with this requirements Processor Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz, 2112 Mhz RAM : 64GB Graph: RTX3070 on an external dock (EGPU)
> 
> I have 1.1.0 Pokemon Arceus and the 60FPS for 1.1.0, but I think I've never managed more than 25 FPS (and for a few secs), normally 5-9 FPS (not playing 4k, but lowst res)
> 
> Is this CPU limitation or something else? I've activated/deactivated VSYNC, and other options as per several tutorials I've seen, but nothing happens (actually only works on 50FPS when I'm in the room :) )
> 
> thanks !!

Github is not used for support. Join the discord and in the support channel drop the log and the problem you have.

Discord group : https://discord.gg/VkQYXAZ

**Comment by sawnfrost** [comment]
En la aplicacion RYUSAK no me aparece ningun MOD de pokemon arceus y me gustaria usarlos para ir 60 fps

**Comment by StrixKruiboh** [comment]
On AMD Adrenalin 23.2.2 drivers. Player model is now invisible.  
![unknown_2023 03 07-11 03](https://user-images.githubusercontent.com/114706645/223478415-cb3cdf3b-5317-4c87-9ca3-9f0ea0ac52eb.png)

**Comment by NitroTears** [comment]
Just had a play around figured I'd add to this, some sweet AMD testing for ya.
Ryujinx 1.1.731 with Vulkan
CPU: AMD Ryzen 7 5700X
GPU: AMD Radeon RX 6700 XT - Driver Version: 23.2.2
RAM: 32 GB

Game runs at a solid 30 with no drops at all (though I've only reaslly tested the starting area).

![ryujinx_capture_2023-04-25_08-55-43](https://user-images.githubusercontent.com/73270647/234135896-a967aece-7f0f-4e9c-9911-dd1f450749a2.png)
![ryujinx_capture_2023-04-25_09-13-39](https://user-images.githubusercontent.com/73270647/234135909-592effd2-ecb6-437d-84ce-6b385956d5e2.png)

There isn't any visual glitches or issues I could see. Like some others mentioned note that when your character is over the water, there is an outline rendering issue? (As seen in first screenshot above). This actually happens on real switch hardware, so it technically doesn't count an issue. I do not have the intro crashs mentioned above on Vulkan, or on OpenGL.

**Comment by kayl098** [comment]
in the newest ryujinx versions the shading/lighting of the game has been broken for a while for me
my system specs are:
GPU: Intel Iris Xe (integrated)
CPU: Intel Core i5-1135G7
RAM: 8 GB
i'm running the game on vulkan with the newest 1.1.763 build of the emulator
i can't test opengl bcuz well... everything is broken and it can crash my gpu
![20230506124957_1](https://user-images.githubusercontent.com/132771385/236634985-b397f1b2-97bd-4afd-b536-a38c73ab7a87.jpg)
![20230506124933_1](https://user-images.githubusercontent.com/132771385/236634994-4d4d8cf6-85cf-4940-bf4c-8642c5f1a267.jpg)
![20230506124926_1](https://user-images.githubusercontent.com/132771385/236634998-f552166a-4f27-48e9-b464-8a8da36178b0.jpg)
![20230506124912_1](https://user-images.githubusercontent.com/132771385/236635002-363d63b8-8ca0-471c-842f-a2cda1ab10cc.jpg)
![20230506125022_1](https://user-images.githubusercontent.com/132771385/236635004-4d75bf00-cdca-40d0-b61e-7f2fbb56be2f.jpg)

**Comment by AlexTu2** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/assets/6798052/a524f3a2-df82-466e-968e-995cbb95c478

About 20 Mins into the game, first major graphical bug spotted. (At my home there was flickering too but not as intensive)

Ryujinx LDN 3.13 with Vulkan

OS Name Microsoft Windows 10 Education	
Version 10.0.19045 Build 19045	
Processor AMD Ryzen 9 5900X 12-Core Processor, 4276 Mhz, 12 Core(s), 24 Logical Processor(s)	
BaseBoard Product	MAG X570S TOMAHAWK MAX WIFI (MS-7D54)	
Installed Physical Memory (RAM)	32.0 GB	
NVIDIA GeForce RTX 3070 Ti	
Driver Version	31.0.15.3179

**Comment by GamerzHell9137** [comment]
> 

Probably because of the Nvidia driver change that happened. LDN 4 is gonna be fine i guess.

**Comment by AlexTu2** [comment]
> > 
> 
> Probably because of the Nvidia driver change that happened. LDN 4 is gonna be fine i guess.

Is there a planned release date?

**Comment by Arczii77** [comment]
> ## Pokémon Legends: Arceus
> #### Game Update Version : 1.0.0
> #### Current on `master` : 1.1.11
> Game runs and plays without issues. Minor graphical issues on Vulkan and OpenGL on both AMD and Nvidia vendors.
> 
> #### Hardware Specs :
> ##### CPU: Ryzen 3600
> ##### GPU: NVIDIA GTX 960 2 GB
> ##### RAM: 16 GB
> #### Outstanding Issues:
> -Randomly on rare occasions textures bug out
> 
> ![jpeg](https://user-images.githubusercontent.com/2002038/152039637-65942bf4-1107-43a0-b67a-aebae48d2237.jpg)
> 
> -If Handheld controller is enabled the game controls will go amok
> 
>  Ryujinx.Nvidia.Profile.2022.02.01.-.20.53.17.01.mp4 
> -Or rare occasions game can crash/freeze
> 
> [Crashing during loading](https://github.com/Ryujinx/Ryujinx-Games-List/files/7981506/log1.txt) [Freeze while walking around (Moonview Arena)](https://github.com/Ryujinx/Ryujinx-Games-List/files/7987427/log2.txt)
> 
> #### Screenshots :
> ![Circle](https://user-images.githubusercontent.com/2002038/151574117-df6d3806-a800-48d9-92dc-7abb839d8957.PNG) ![Vulcano](https://user-images.githubusercontent.com/2002038/151574212-c247c8d7-f25c-4ac2-beb4-41b34372dfa1.PNG) ![Screen](https://user-images.githubusercontent.com/2002038/151574280-cf0ebb95-6733-424a-9aa8-35c3d5cc387b.jpg)

**Comment by Stormymods** [comment]
were tf is download link???

**Comment by BoD767** [comment]
Hi trying to run pokemon legends arceus version 1.1.1 but it crashes on launch

**Comment by Brambleclaw190** [comment]
![Screenshot](https://github.com/user-attachments/assets/7ab95cde-26c2-4906-be55-b35cce5063a6)
This randomly happened while I was playing

**Comment by Kelberus** [comment]
I have finished set up base game and file update without problems. However, after game launch and go into language selection, I cannot select anything apart from exit the game. I have already config the controller, and it seems not the controller issue. Mousepad also working just fine, but nothing happened after clicks.

**Comment by gius-n** [comment]
The game (update 1.1.1) runs almost flawless (very few visual glitches from time to time, but they're pretty rare) at around 30fps, but it often happens that it freezes at casual time: sometimes after 10 mins, sometimes after 30, 40 or even more. It happens when a pokemon uses an attach, when i summon a pokemon or even if I talk to someone or just walk around.

This hasn't changed amongst different Ryujinx versions. How could I fix, or at least limitate, it?

Thanks
