### ISSUE TITLE
Monster Hunter Generations Ultimate Crash - 0100c3800049c000

### ISSUE THREAD

**Issue by INIRU** [Ryujinx/Ryujinx-Games-List#3841]
#### Current on `master` : Ryujinx 1.1.46

*Ryujinx ends while playing the game. (Translator)*

```
---> System.Exception: None of these fonts were found in the system: 맑은 고딕, Liberation Sans, FreeSans, DejaVu Sans!
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRendererBase.CreateFonts(String uiThemeFontFamily) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardRendererBase.cs:line 137
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRendererBase..ctor(IHostUiTheme uiTheme) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardRendererBase.cs:line 107
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboard.SoftwareKeyboardRenderer..ctor(IHostUiTheme uiTheme) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardRenderer.cs:line 26
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboardApplet.Start(AppletSession normalSession, AppletSession interactiveSession) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardApplet.cs:line 105
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 214
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1266
```

#### Log file :
[Ryujinx_1.1.46_2022-02-20_23-00-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8104144/Ryujinx_1.1.46_2022-02-20_23-00-49.log)
[Ryujinx_1.1.46_2022-02-20_23-03-22.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8104145/Ryujinx_1.1.46_2022-02-20_23-03-22.log)
[Ryujinx_1.1.46_2022-02-20_23-05-11.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8104146/Ryujinx_1.1.46_2022-02-20_23-05-11.log)

**Comment by davidlai1983** [comment]
hi
