### ISSUE TITLE
Mononoke Slashdown - 0100F3A00FB78000

### ISSUE THREAD

**Issue by lurkingaround** [Ryujinx/Ryujinx-Games-List#3844]
#### Current on `master` : Commit Id *or* Build Version : 1.1.53

Game boots, can make a new save file but crashes when selecting a mission to start playing.
```
00:00:30.353 |E| HLE.OsThread.6 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Audio.Renderer.Server.Performance.PerformanceManagerGeneric`3.CopyHistories(Span`1 performanceOutput) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Server\Performance\PerformanceManagerGeneric.cs:line 208
   at Ryujinx.Audio.Renderer.Server.StateUpdater.UpdatePerformanceBuffer(PerformanceManager manager, Span`1 performanceOutput) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Server\StateUpdater.cs:line 588
   at Ryujinx.Audio.Renderer.Server.AudioRenderSystem.Update(Memory`1 output, Memory`1 performanceOutput, ReadOnlyMemory`1 input) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Server\AudioRenderSystem.cs:line 480
   at Ryujinx.HLE.HOS.Services.Audio.AudioRenderer.AudioRendererServer.RequestUpdate(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRenderer\AudioRendererServer.cs:line 77
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 214
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1266

```

#### Log file :

[Ryujinx_1.1.53_2022-02-24_22-39-18.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8132192/Ryujinx_1.1.53_2022-02-24_22-39-18.log)

**Comment by MetrosexualGarbodor** [comment]
Needs an update.

**Comment by Cronos-0** [comment]
๊UPDATE......

## Mononoke Slashdown

#### Game Update Version : 1.0.0 / US 

#### Current on `master` : 1.1.63

The game still crashes when starting the first mission. 

```
00:00:55.530 |E| HLE.OsThread.6 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Outstanding Issues :



#### Screenshots :

![bandicam 2022-03-10 11-10-08-293](https://user-images.githubusercontent.com/35269098/157589042-883e33ca-571c-4934-8e85-19f8a047d337.jpg)
![bandicam 2022-03-10 11-10-35-684](https://user-images.githubusercontent.com/35269098/157589055-23c8481a-5f5c-4889-bdaf-48fdc5fe5018.jpg)
![bandicam 2022-03-10 11-10-39-134](https://user-images.githubusercontent.com/35269098/157589069-8ebe5f60-ee66-45d8-bc32-cd53f2ac14ce.jpg)
![bandicam 2022-03-10 11-15-45-753](https://user-images.githubusercontent.com/35269098/157589096-062ca6e8-cac8-4e7e-918b-aa22a3db6dd3.jpg)
![bandicam 2022-03-10 11-16-12-005](https://user-images.githubusercontent.com/35269098/157589102-7a1bc4f0-2558-4b27-8870-ca1542b8538c.jpg)

#### Logs :

[Ryujinx_1.1.63_2022-03-10_11-15-03.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8220310/Ryujinx_1.1.63_2022-03-10_11-15-03.log)

**Comment by Cronos-0** [comment]
๊UPDATE......

## Mononoke Slashdown

#### Game Update Version : 1.0.0 / US 

#### Current on `master` : 1.1.115

playable now,no more crashes

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2022-05-05 03-50-16-728](https://user-images.githubusercontent.com/35269098/166824220-f55b0b8d-5186-4c25-8380-518071dffdda.jpg)
![bandicam 2022-05-05 03-50-07-191](https://user-images.githubusercontent.com/35269098/166824254-1fb5b6bb-c2e4-4984-9786-38cee73c6136.jpg)
![bandicam 2022-05-05 03-49-02-386](https://user-images.githubusercontent.com/35269098/166824343-314b5656-fd4d-4728-ae2e-ade81e901247.jpg)
![bandicam 2022-05-05 03-48-33-539](https://user-images.githubusercontent.com/35269098/166824424-3a45e518-f017-4548-bf92-e1584f641712.jpg)
