### ISSUE TITLE
Atelier Sophie 2: The Alchemist of the Mysterious Dream - 010082A01538E000

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx-Games-List#3851]
#### Current on `master` : 1.1.60

Game runs fine until you get to Near Forest area where it crashes. The GPU driver crashes and the error that's pops out is
```
00:07:49.861 |E| GUI.RenderLoop Gpu : GL Sync Object 56236 failed to signal within 1000ms. Continuing...
```
There's a chance of the driver not crashing but the same error message is shown on the console. The way the game acts is just being dimmed like the game is loading assets in the background, it is "playable" which means you can move and hear stuff that's happening, open menus etc. but since the screen is stuck at the dimmed loading screen nothing can be done.

Dimmed frozen screen:

![image](https://user-images.githubusercontent.com/2002038/156917244-092c651f-5503-4087-8bf5-781fe1be3243.png)

![image](https://user-images.githubusercontent.com/2002038/156917255-4fb7e8ff-807e-47f3-8cf4-839808376c49.png)

Sometimes the game crashes on the main menu too and while loading a save

```
00:00:49.605 |I| HLE.GuestThread.44 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   0x00000000082839c8    main:0x27f9c8    
   0x0000000008264214    main:0x260214    
   0x0000000008264248    main:0x260248    
   0x0000000008264248    main:0x260248    
   0x0000000008264248    main:0x260248    
   0x000000000826d2b0    main:0x2692b0    
   0x000000000890a660    main:0x906660    
   0x000000000890bc60    main:0x907c60    
   0x000000000863dcf4    main:0x639cf4    
   0x000000000a2ddee8    sdk:0x341ee8    
   0x000000000a2e4474    sdk:0x348474    
   0x0000000000000000

00:00:49.613 |I| HLE.GuestThread.44 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
    X[00]:    0x0000000000000000
    X[01]:    0x00000065f854a680
    X[02]:    0x00000000082839d4 (main:0x27f9d4)    => 
    X[03]:    0x0000000000000000
    X[04]:    0x000000000a41f370 (sdk:0x483370)    => 
    X[05]:    0x0000000000000000
    X[06]:    0x0000000000000400
    X[07]:    0x00000049efad5a30 (SP:-0xfffffffffffffd70)
    X[08]:    0x00000000098ffce8
    X[09]:    0x00000000098ffce8
    X[10]:    0x0000000000000001
    X[11]:    0x0000000000000000
    X[12]:    0x0000000000000000
    X[13]:    0x0000000000000001
    X[14]:    0x0000000000000000
    X[15]:    0x00000000387fffff
    X[16]:    0x000000000982e4c0
    X[17]:    0x000000000a4d8350 (sdk:0x53c350)    => memcpy
    X[18]:    0x000000000aa6e716
    X[19]:    0x00000049efad5e18 (SP:-0x0158)
    X[20]:    0x0000000000000000
    X[21]:    0x0000000000000000
    X[22]:    0x0000000001312d00
    X[23]:    0x0000000038047110
    X[24]:    0x00000000098fb138
    X[25]:    0x0000000000000001
    X[26]:    0x00000000098f9da8
    X[27]:    0x0000000009841120
    X[28]:    0x0000000000000000
    FP:    0x00000049efad5d00 (SP:-0x0040)
    LR:    0x000000000827c168 (main:0x278168)    => 
    SP:    0x00000049efad5cc0 (SP)
    PC:    0x0000000000000000

0:00:49.613 |E| HLE.GuestThread.44 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:49.726 |E| HLE.GuestThread.44 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 220
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1266
```

#### Outstanding Issues:

No graphical issues noticed.

#### Screenshots :

![image](https://user-images.githubusercontent.com/2002038/156917371-e0dbfda9-0dfb-42e7-befa-4a0ff79683cb.png)

![image](https://user-images.githubusercontent.com/2002038/156917380-a1bf31e1-077d-4562-8647-63cd5a3ed57e.png)

![image](https://user-images.githubusercontent.com/2002038/156917401-cc0b9d94-84a7-487a-b124-daee82530ac5.png)

![image](https://user-images.githubusercontent.com/2002038/156917408-e159c682-68fc-4a28-a854-8fbca247ded5.png)

**Comment by MetrosexualGarbodor** [comment]
Needs an update as the crash is supposed to be fixed.

**Comment by GamerzHell9137** [comment]
Updated

**Comment by nivodeus** [comment]
Sadly having the same exact issue here despite updating. Other games still run fine.

**Comment by zackdx** [comment]
I have a glitch with text in box inside the game, menu, text, map
Any fix ? ? 

version ryuninx 1.1.272

**Comment by AntiGrieferGames** [comment]
That game stills crashing while on starting


[Ryujinx_1.1.323_2022-10-22_23-28-24.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9845286/Ryujinx_1.1.323_2022-10-22_23-28-24.log)

**Comment by EmulationFanatic** [comment]
> That game stills crashing while on starting
> 
> [Ryujinx_1.1.323_2022-10-22_23-28-24.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9845286/Ryujinx_1.1.323_2022-10-22_23-28-24.log)

It's able to go in-game here...I didn't test for long but it didn't crash on boot on Vulkan.
![image](https://user-images.githubusercontent.com/62343878/197363402-0abfff9d-c9e3-4217-8e84-7cce01ec5065.png)

**Comment by AntiGrieferGames** [comment]
i use a amd rx 480 gpu, you using a nvidia gpu, thats why

**Comment by EmulationFanatic** [comment]
> i use a amd rx 480 gpu, you using a nvidia gpu, thats why

Yes it seems so.

**Comment by Fince10086** [comment]
random stuck or crash on macbook pro (m1 pro) that can't continue playing
