### ISSUE TITLE
Chocobo GP - 01006A30124CA000

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#3855]
#### Current on `master` : 1.1.64

Game crashes while the game background video preview starts.  

```
00:01:17.547 |I| HLE.GuestThread.53 Cpu PrintGuestStackTrace: Guest stack trace:
Process: ChickenRace, PID: 92
   0x000000001158193c	sdk:0x40193c	NvDdkVicConfigure:0x005c
   0x0000000011578344	sdk:0x3f8344	
   0x0000000011575e10	sdk:0x3f5e10	
   0x00000000115759d4	sdk:0x3f59d4	NvBlit:0x00b4
   0x0000000010de0a54	subsdk0:0x311a54	android::SfNvnUtil::Blit(native_handle const*, int, native_handle const*):0x01e4
   0x0000000010bf9ea8	subsdk0:0x12aea8	movie::NnCodecConsumer::acquireBuffer(unsigned long*, movie::Buffer*):0x0218
   0x0000000010bf2e48	subsdk0:0x123e48	movie::DecoderImpl::CopyOutputBufferToClientTextureAndRelease(int, movie::Buffer*):0x0078
   0x0000000010bf30d0	subsdk0:0x1240d0	movie::DecoderImpl::GetOutputBuffer(int, movie::Buffer*):0x0220
   0x000000000aef5098	main:0x2ef1098	
   0x00000000081e0d70	main:0x1dcd70	
   0x00000000081e80b0	main:0x1e40b0	
   0x00000000081e8330	main:0x1e4330	
   0x000000000892caf8	main:0x928af8	
   0x000000000892c65c	main:0x92865c	
   0x00000000090f5068	main:0x10f1068	
   0x000000000891ceb0	main:0x918eb0	
   0x00000000114be698	sdk:0x33e698	
   0x00000000114c2e64	sdk:0x342e64	
   0x0000000000000000


00:01:17.554 |I| HLE.GuestThread.53 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x00000003c057c000
	X[02]:	0x0000000000000610
	X[03]:	0x00000003c057c000
	X[04]:	0x0000000000000610
	X[05]:	0x0000000000000610
	X[06]:	0x0000000000000001
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000610
	X[09]:	0x0000000000000610
	X[10]:	0x0000000000000001
	X[11]:	0x0000000000000001
	X[12]:	0x0000000000000610
	X[13]:	0x0000000000000001
	X[14]:	0x0000000000000610
	X[15]:	0x0000000000000000
	X[16]:	0x0000000011ddc0e0
	X[17]:	0x00000000116b0b70 (sdk:0x530b70)	=> __memcpy_device
	X[18]:	0x0000000000000024
	X[19]:	0x00000003c057c000
	X[20]:	0x0000000000000c20
	X[21]:	0x0000000000000000
	X[22]:	0x0000000000000610
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000079
	X[25]:	0x0000000000001000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000610
	X[28]:	0x0000000000000000
	FP:	0x00000011e5afb4c0 (SP:-0x0060)
	LR:	0x0000000011561208 (sdk:0x3e1208)	=> NvRmMemWriteStrided:0x0138
	SP:	0x00000011e5afb460 (SP)
	PC:	0x0000000000000000


00:01:17.554 |E| HLE.GuestThread.53 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:01:17.647 |E| HLE.GuestThread.53 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2022-03-11 09-08-59-345](https://user-images.githubusercontent.com/35269098/157789123-31bbf1dd-c592-4e23-9ea2-9b69646dd505.jpg)
![bandicam 2022-03-11 09-09-02-616](https://user-images.githubusercontent.com/35269098/157789138-624f6e81-22ec-4a81-b1f9-ed951054b4e7.jpg)
![bandicam 2022-03-11 09-09-20-602](https://user-images.githubusercontent.com/35269098/157789155-6b99c4fe-a1bb-4153-a404-813ce7215cb2.jpg)
![bandicam 2022-03-11 09-09-28-808](https://user-images.githubusercontent.com/35269098/157789171-9effa2d9-fb73-4ac2-952e-80b0021a3d31.jpg)

#### Logs :

[Ryujinx_1.1.64_2022-03-11_09-06-29.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8228448/Ryujinx_1.1.64_2022-03-11_09-06-29.log)

**Comment by MetrosexualGarbodor** [comment]
Your Memory Manager Mode is set to host mapped. Does it crash on host unchecked as well?

**Comment by Cronos-0** [comment]
@MetrosexualGarbodor No it doesn't crash on host unchecked i have updated again thanks for reminding me

**Comment by EliEron** [comment]
> Sounds in the game seem to be broken all the time, both OpenAL/SoundIO.

Did you try with SDL2? I've not had any audio issues with the game using that backend.

**Comment by LukeWarnut** [comment]
Chocobo GP is an online-only mode btw. That's why it didn't work.

**Comment by Gigadragon78** [comment]
> Chocobo GP is an online-only mode btw. That's why it didn't work.

Nope,Chocobo GP is Online and Offline. You can still play the story mode without a conection but you will not get all the contents.
By the way,the game crashes randomly after chapter 4,tested with Yuzu EA 2538.

**Comment by MetrosexualGarbodor** [comment]
> tested with Yuzu EA 2538.

You are on Ryujinx GitHub.

**Comment by LukeWarnut** [comment]
> Nope,Chocobo GP is Online and Offline. You can still play the story mode without a conection but you will not get all the contents. By the way,the game crashes randomly after chapter 4,tested with Yuzu EA 2538.

Re-read what I said. I was referring to the mode, not the game. This is Ryujinx btw, not yuzu.

**Comment by Gigadragon78** [comment]
> You are on Ryujinx GitHub.
Excuse me,first time here.

**Comment by GamerzHell9137** [comment]
## Chocobo GP

Game Update Version : v1.0.3

Current on master : 1.1.137

Game runs and plays fine. There's some graphical issues like characters being invisible after the race ends at the results screen, in story mode(character seen sliding into the screen from the side but after a little bit of their body is shown they disappear) and in the character menu screen. Upscaling to x2 makes one of the loading screen that happens at boot turn grey instead of staying pitch black. Rare chance of the opening video crashing the emulator.

Aforementioned issues are not happening on the Vulkan backend (only the grey loading screen at boot when upscaled), only OpenGL.

Video crash log:
```
00:01:22.066 |I| HLE.GuestThread.53 Cpu PrintGuestStackTrace: Guest stack trace:
Process: ChickenRace, PID: 92
   0x000000001158193c   sdk:0x40193c    NvDdkVicConfigure:0x005c
   0x0000000011578344   sdk:0x3f8344
   0x0000000011575e10   sdk:0x3f5e10
   0x00000000115759d4   sdk:0x3f59d4    NvBlit:0x00b4
   0x0000000010de0a54   subsdk0:0x311a54        android::SfNvnUtil::Blit(native_handle const*, int, native_handle const*):0x01e4
   0x0000000010bf9ea8   subsdk0:0x12aea8        movie::NnCodecConsumer::acquireBuffer(unsigned long*, movie::Buffer*):0x0218
   0x0000000010bf2e48   subsdk0:0x123e48        movie::DecoderImpl::CopyOutputBufferToClientTextureAndRelease(int, movie::Buffer*):0x0078
   0x0000000010bf30d0   subsdk0:0x1240d0        movie::DecoderImpl::GetOutputBuffer(int, movie::Buffer*):0x0220
   0x000000000aef5098   main:0x2ef1098
   0x00000000081e0d70   main:0x1dcd70
   0x00000000081e80b0   main:0x1e40b0
   0x00000000081e8330   main:0x1e4330
   0x000000000892caf8   main:0x928af8
   0x000000000892c65c   main:0x92865c
   0x00000000090f5068   main:0x10f1068
   0x000000000891ceb0   main:0x918eb0
   0x00000000114be698   sdk:0x33e698
   0x00000000114c2e64   sdk:0x342e64
   0x0000000000000000


00:01:22.070 |I| HLE.GuestThread.53 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
        X[00]:  0x0000000000000000
        X[01]:  0x00000003c060acc0
        X[02]:  0x0000000000000610
        X[03]:  0x00000003c060acc0
        X[04]:  0x0000000000000610
        X[05]:  0x0000000000000610
        X[06]:  0x0000000000000001
        X[07]:  0x0000000000000000
        X[08]:  0x0000000000000610
        X[09]:  0x0000000000000610
        X[10]:  0x0000000000000001
        X[11]:  0x0000000000000001
        X[12]:  0x0000000000000610
        X[13]:  0x0000000000000001
        X[14]:  0x0000000000000610
        X[15]:  0x0000000000000000
        X[16]:  0x0000000011ddc0e0
        X[17]:  0x00000000116b0b70 (sdk:0x530b70)       => __memcpy_device
        X[18]:  0x0000000000000024
        X[19]:  0x00000003c060acc0
        X[20]:  0x0000000000000c20
        X[21]:  0x0000000000000000
        X[22]:  0x0000000000000610
        X[23]:  0x0000000000000000
        X[24]:  0x00000000000000d4
        X[25]:  0x0000000000001000
        X[26]:  0x0000000000000000
        X[27]:  0x0000000000000610
        X[28]:  0x0000000000000000
        FP:     0x00000011e5afb4c0 (SP:-0x0060)
        LR:     0x0000000011561208 (sdk:0x3e1208)       => NvRmMemWriteStrided:0x0138
        SP:     0x00000011e5afb460 (SP)
        PC:     0x0000000000000000


00:01:22.070 |E| HLE.GuestThread.53 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:01:22.278 |E| HLE.GuestThread.53 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in C:\Users\Gamestation\Desktop\Vulkkan\ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 244
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\Users\Gamestation\Desktop\Vulkkan\ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\Users\Gamestation\Desktop\Vulkkan\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
   at System.Threading.Thread.StartCallback()
Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in C:\Users\Gamestation\Desktop\Vulkkan\ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 244
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\Users\Gamestation\Desktop\Vulkkan\ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\Users\Gamestation\Desktop\Vulkkan\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
   at System.Threading.Thread.StartCallback()
```

### Hardware Specs :

CPU: Amd Ryzen 3600
GPU: NVIDIA GTX 960 2GB
RAM: 16GB

### OpenGL screenshots:


![image](https://user-images.githubusercontent.com/2002038/172006011-3607b2d9-5095-4825-9984-9bea1d76e845.png)
![image](https://user-images.githubusercontent.com/2002038/172006243-a26072af-341b-4008-a171-fd3b6ea1eb8e.png)
![image](https://user-images.githubusercontent.com/2002038/172006346-cf59e1b2-1de1-4430-8b8c-149681c0dd5d.png)
![image](https://user-images.githubusercontent.com/2002038/172006969-b0bf8664-0dae-4675-b011-e3c1b6f00cff.png)

### Vulkan screenshots:

![image](https://user-images.githubusercontent.com/2002038/172007789-403335cd-7f3d-4a97-8f27-c6f9444cdccd.png)
![image](https://user-images.githubusercontent.com/2002038/172007795-dde1d2cd-de34-4339-a2dc-127bed3521f4.png)
![image](https://user-images.githubusercontent.com/2002038/172007908-6b3a8f20-f3a4-4e8e-87ef-85c2f728a11c.png)

**Comment by MetrosexualGarbodor** [comment]
Updated.
