### ISSUE TITLE
MLB® The Show™ 22 - 0100876015D74000

### ISSUE THREAD

**Issue by CrusadingNinja** [Ryujinx/Ryujinx-Games-List#3875]
#### Current on master : 1.1.101

Crashes on boot.  

Last error returned:
```

`00:00:06.188 |E| HLE.OsThread.8 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Fs.IFileSystemProxy: 205

Guest Stack Trace:
Process: Service, PID: 85

Raw Request Data:
00000000   01 00 11 00 01 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  CD 00 00 00 00 00 00 00   SFCI····Í·······
00000020   00 00 00 00 00 00 00 00  00 00 00 00               ············    

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 156
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 214
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263`

```
With missing services enabled it gets past the above service but proceeds to crash as follows:
```
00:00:06.265 |I| HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   0x000000000c9df508	sdk:0x217508	
   0x000000000c9de8ac	sdk:0x2168ac	nn::fs::QueryMountRomCacheSize(unsigned long*, int):0x00cc
   0x00000000086761f0	main:0x6721f0	
   0x000000000860a6b0	main:0x6066b0	
   0x00000000086074dc	main:0x6034dc	
   0x00000000081041e4	main:0x1001e4	
   0x00000000080fdbbc	main:0xf9bbc	nnMain:0x011c
   0x000000000caa3c14	sdk:0x2dbc14	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000080000d4	rtld:0x00d4	


00:00:06.273 |I| HLE.GuestThread.15 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x00000065b9700000
	X[01]:	0x0000000000000000
	X[02]:	0x00000049efb088e0 (SP)
	X[03]:	0x0000000000000050
	X[04]:	0x00000049efb08840 (SP:-0xffffffffffffff60)
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000010
	X[07]:	0x0000000000000000
	X[08]:	0x000000000c9b9920 (sdk:0x1f1920)	=> nn::fs::detail::StorageServiceObjectAdapter<nn::fssrv::sf::IStorage>::Read(long, void*, unsigned long)
	X[09]:	0x000000000c7c8000 (sdk:0x0000)	=> 
	X[10]:	0x0000000000cda430
	X[11]:	0x0000000000000080
	X[12]:	0x0000000000000000
	X[13]:	0xec8aeb400163e275
	X[14]:	0x8000000000000000
	X[15]:	0x0000000000000000
	X[16]:	0x000000000c99f998 (sdk:0x1d7998)	=> nn::fs::RomFsFileSystem::GetRequiredWorkingMemorySize(unsigned long*, nn::fs::IStorage*)
	X[17]:	0x000000000d4a2430
	X[18]:	0x0000000000000000
	X[19]:	0x00000049efb08958 (SP:-0x0078)
	X[20]:	0x00000049efb089a8 (SP:-0x00c8)
	X[21]:	0x0000000000000000
	X[22]:	0x00000065d368b848
	X[23]:	0x00000065d3684c68
	X[24]:	0x00000065d3687798
	X[25]:	0x00000065d3686208
	X[26]:	0x00000065d3684818
	X[27]:	0x000000000ba57000
	X[28]:	0x000000000ae045f0
	FP:	0x00000049efb08930 (SP:-0x0050)
	LR:	0x000000000c99f9dc (sdk:0x1d79dc)	=> nn::fs::RomFsFileSystem::GetRequiredWorkingMemorySize(unsigned long*, nn::fs::IStorage*):0x0044
	SP:	0x00000049efb088e0 (SP)
	PC:	0x0000000000000000


00:00:06.273 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:06.347 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 220
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1263
```

#### Outstanding Issues:
https://github.com/Ryujinx/Ryujinx/issues/1596

#### Log file : [Ryujinx_1.1.101_2022-04-10_09-32-10.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8459228/Ryujinx_1.1.101_2022-04-10_09-32-10.log)

With Ignore Missing Services enabled: [Ryujinx_1.1.101_2022-04-10_09-32-41.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8459231/Ryujinx_1.1.101_2022-04-10_09-32-41.log)

**Comment by EmulationFanatic** [comment]
Updated. Thanks!

**Comment by Alexisyeahh** [comment]
Game Version 1.0.18
Emulator Version 1.1.343
Graphic Backend :OpenGL

![Screenshot 2022-11-15 230134](https://user-images.githubusercontent.com/73174992/202025353-12c912ff-00c0-44d8-aa7f-0ffefe52e5bb.png)




Hardware:
GPU:GTX 1660 SUPER
CPU:I7 10700F
RAM:16GB

**Comment by freewifiman** [comment]
Game Version 1.0.17
Emulator Version 1.1.351
Graphic Backend :Vulkan
The game boot normally but crush at loading When using Vulkan graphic backend .

`00:01:39.248 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 248
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 213
   at Ryujinx.Graphics.GAL.Multithreading.Commands.SetRenderTargetsCommand.Run(SetRenderTargetsCommand& command, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\Commands\SetRenderTargetsCommand.cs:line 21
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_74(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 209
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 107
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 401
   at System.Threading.Thread.StartCallback()`

Harware:
CPU:i7-9750H
GPU:RTX2060
RAM:32GB

**Comment by freewifiman** [comment]
Game Version 1.0.17
Emulator Version 1.1.351
Graphic Backend :Vulkan
The game boot normally but crush at loading When using Vulkan graphic backend .

![err](https://user-images.githubusercontent.com/118337630/202332277-a29325c6-0f8d-44c5-bf83-2d4102f47d8b.png)


Harware:
CPU:i7-9750H
GPU:RTX2060
RAM:32GB

**Comment by CrusadingNinja** [comment]
> Game Version 1.0.18 Emulator Version 1.1.343 Graphic Backend :OpenGL
> 
> ![Screenshot 2022-11-15 230134](https://user-images.githubusercontent.com/73174992/202025353-12c912ff-00c0-44d8-aa7f-0ffefe52e5bb.png)
> 
> Graphic Backend :Vulkan
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/73174992/202136847-9e350833-6728-4154-abb3-92d733928008.png)
> 
> Hardware: GPU:GTX 1660 SUPER CPU:I7 10700F RAM:16GB

These errors have nothing to do with the actual game. It appears Ryujinx is unable to access certain files due to insufficient file system permissions or possibly anti virus interference.

**Comment by Alexisyeahh** [comment]
Using the Vulkan backend menus work fine but whenever I try to play a game it's crashing in the loading screen

**Comment by dari1991** [comment]
I am presenting the following problem I have a Ryzen 3 3200G 16GB RAM and my graphics card is the Nvidea GTX 760 here I show you in the following image the problem
![image](https://user-images.githubusercontent.com/96393214/234192101-d9ca3962-f36d-46c4-9fa9-5aa66e371899.png)
