### ISSUE TITLE
LOOPERS - 010062A0178A8000

### ISSUE THREAD

**Issue by EliEron** [Ryujinx/Ryujinx-Games-List#3904]
#### Current on `master` : Commit Id *or* Build Version : 1.1.137

Most of the game runs well but during sections where it displays "noise" on the screen (Which I'm fairly certain is actually a video overlaying the screen) the game slows down quite a bit. Also when a movie or the aforementioned effects are played there is a random chance Ryujinx will crash with a System Access Violation Exception.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Ryujinx.Graphics.Vic.Blender.BlendOneSse41(Ryujinx.Graphics.Vic.Image.Surface, Ryujinx.Graphics.Vic.Image.Surface, Ryujinx.Graphics.Vic.Types.SlotStruct ByRef)
   at Ryujinx.Graphics.Vic.Blender.BlendOne(Ryujinx.Graphics.Vic.Image.Surface, Ryujinx.Graphics.Vic.Image.Surface, Ryujinx.Graphics.Vic.Types.SlotStruct ByRef)
   at Ryujinx.Graphics.Vic.VicDevice.Execute(Int32)
   at Ryujinx.Common.AsyncWorkQueue`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].DoWork()
   at System.Threading.Thread.StartCallback()
```

Since this is a memory error it's worth noting that it can occur on all of the memory backends, though it seems to trigger more rarely on the software backend. 

Here is a save right before a section that seems to crash Ryujinx quite frequently [Loopers.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/8833106/Loopers.zip), just load the last save and advance the text once. If Ryujinx does not crash then restart Ryujinx and try again. Simply reloading the save does not work to reproduce the glitch in my experience.

Since the error occurs within a SSE 4.1 optimized method I decided to see what would happen if I edited Ryujinx to not use the SSE 4.1 version. Doing so still results in a crash but a different kind:

```
00:00:20.973 |E| Ryujinx.VicProcessor Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.Vic.Blender.BlendOne(Surface dst, Surface src, SlotStruct& slot) in C:\Users\EliEron\RiderProjects\Ryujinx\Ryujinx.Graphics.Vic\Blender.cs:line 25
   at Ryujinx.Graphics.Vic.VicDevice.Execute(Int32 data) in C:\Users\EliEron\RiderProjects\Ryujinx\Ryujinx.Graphics.Vic\VicDevice.cs:line 50
   at Ryujinx.Graphics.Device.DeviceState`1.Write(Int32 offset, Int32 data) in C:\Users\EliEron\RiderProjects\Ryujinx\Ryujinx.Graphics.Device\DeviceState.cs:line 105
   at Ryujinx.Graphics.Vic.VicDevice.Write(Int32 offset, Int32 data) in C:\Users\EliEron\RiderProjects\Ryujinx\Ryujinx.Graphics.Vic\VicDevice.cs:line 26
   at Ryujinx.Graphics.Host1x.ThiDevice.Process(CommandAction cmdAction) in C:\Users\EliEron\RiderProjects\Ryujinx\Ryujinx.Graphics.Host1x\ThiDevice.cs:line 131
   at Ryujinx.Common.AsyncWorkQueue`1.DoWork() in C:\Users\EliEron\RiderProjects\Ryujinx\Ryujinx.Common\AsyncWorkQueue.cs:line 37
   at System.Threading.Thread.StartCallback()
```

There are also cases where an effect will not crash Ryujinx but it will also not play correctly, it will simply be frozen on the first frame and remain completely static.

I can provide further debugging information if needed.

#### Screenshots :
![Ryujinx_YnnHAAyStr](https://user-images.githubusercontent.com/22575945/171881608-badd98e7-ecc1-432d-a570-299c2ed45f8d.png)
![Ryujinx_vG6UQYV0Ep](https://user-images.githubusercontent.com/22575945/171898452-6e3ed9fe-1790-406e-bac6-7c9eb64df724.png)
![Ryujinx_liMvY9bh2E](https://user-images.githubusercontent.com/22575945/171898541-6a279033-391a-4e24-809e-4ee9fb3c0cc0.png)

#### Log file :

[Ryujinx_1.1.137_2022-06-03_16-27-43.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8833139/Ryujinx_1.1.137_2022-06-03_16-27-43.log)

Since Ryujinx itself crashes the last error message does not actually appear in the log.

**Comment by MetrosexualGarbodor** [comment]
Needs an update.

**Comment by EliEron** [comment]
Updated, while the crashing is gone the game is not perfect. The noise effect causes slowdowns (likely due to being a VP9 video file) and does sometimes does not loop properly.
