### ISSUE TITLE
Mario Strikers Battle League Football First Kick [01008A30182F2000]

### ISSUE THREAD

**Issue by daegura9308** [Ryujinx/Ryujinx-Games-List#3908]
#### Current on `master` : Ruyjinx  1.1.142*

*The game crash after start, only show the loading screen and the he crash and the emulator closes*

```
Last error returned.
nException: The instruction at 0x000000000861233c (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1102
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261
Unhandled exception. Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000861233c (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1102
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261
```

**Comment by piplup55** [comment]
since the "demo/playtest" needs internet you can't play it, 
anyway the crash is due to the intro video and can be workaround with a mod
[video](https://www.youtube.com/watch?v=NECsNWPEjiU) - github didn't like the video so i had to upload it to youtube
https://github.com/Ryujinx/Ryujinx/issues/3367
