### ISSUE TITLE
Mario Strikers: Battle League Football - 010019401051C000

### ISSUE THREAD

**Issue by Dejizoku** [Ryujinx/Ryujinx-Games-List#3910]
#### Current on `master` : 1.1.142

Game crashes on the intro sequence.
Can be Bypassed with this mod:
[Intro Bypass.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/8877643/Intro.Bypass.zip)

**Other than that the game is actually working quite good.**

```
00:00:21.974 |E| HLE.GuestThread.41 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000861c85c (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1102
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261
```

#### Screenshots :
![2022-06-10 11_34_42-Ryujinx 1 1 142 - Mario Strikers_ Battle League Football v1 0 0 (010019401051C00](https://user-images.githubusercontent.com/53313552/173039673-02deee8b-1782-4a31-9d98-ada6a4d94646.png)
![2022-06-10 11_36_49-Ryujinx 1 1 142 - Mario Strikers_ Battle League Football v1 0 0 (010019401051C00](https://user-images.githubusercontent.com/53313552/173039707-dc634116-d53d-4c08-99a8-666bf4f51cdb.png)
![2022-06-10 11_38_40-Ryujinx 1 1 142 - Mario Strikers_ Battle League Football v1 0 0 (010019401051C00](https://user-images.githubusercontent.com/53313552/173039784-42af7683-0593-4077-9d5b-315f2d46ed9d.png)
![2022-06-10 11_39_00-Ryujinx 1 1 142 - Mario Strikers_ Battle League Football v1 0 0 (010019401051C00](https://user-images.githubusercontent.com/53313552/173039938-2b45f95a-35ea-4d53-bd9c-0408b3109601.png)
![2022-06-10 11_42_57-Ryujinx 1 1 142 - Mario Strikers_ Battle League Football v1 0 0 (010019401051C00](https://user-images.githubusercontent.com/53313552/173039997-bc58dea5-f50f-4f07-a05c-e275c3660346.png)

**Comment by GamerzHell9137** [comment]
The 3D crowd is not rendered on OpenGL. Vulkan partially shows it.

**Comment by AlvaroGlezG** [comment]
Where do you paste the bypass?? I paste it on AppData\Roaming\Ryujinx\sdcard\atmosphere\contents and still crashing

**Comment by epl609** [comment]
Ryzen 5 5600, GeForce 1080 8GB. Windows 10.i

The game reaches Menu to press a, pressing a leads to a white flash, then back to the main menu. I have attempted to reconfigure my controller and just try the mouse and keyboard. No luck. I also attempted the Vulkan build as well.

**Comment by gdkchan** [comment]
> Ryzen 5 5600, GeForce 1080 8GB. Windows 10.i
> 
> The game reaches Menu to press a, pressing a leads to a white flash, then back to the main menu. I have attempted to reconfigure my controller and just try the mouse and keyboard. No luck. I also attempted the Vulkan build as well.

You're probably running the demo, not the full game then.

**Comment by epl609** [comment]
> > Ryzen 5 5600, GeForce 1080 8GB. Windows 10.i
> > The game reaches Menu to press a, pressing a leads to a white flash, then back to the main menu. I have attempted to reconfigure my controller and just try the mouse and keyboard. No luck. I also attempted the Vulkan build as well.
> 
> You're probably running the demo, not the full game then.

Mario Strikers Battle League Football First Kick [01008A30182F2000][v0](Nsw2uxyz).nsp - 955,229 KB.

**Comment by GamerzHell9137** [comment]
Seems like the crowd issue is another issue like the Kirby one.
On the 3000 series and the 700 series of Nvidia cards the crowd is properly shown while 900 series and 10 series isn't, on OpenGL, On Vulkan the crowd is emulated correctly on all cards.

**Comment by dizzydragon9** [comment]
how do u actually download the game tho

**Comment by GamerzHell9137** [comment]
The issue related to the crowd not rendering correctly has been fixed by a not so recent change. The same trap issue related to the opening video is still present tho.

Tested on 1.1.272

![image](https://user-images.githubusercontent.com/2002038/190892654-0b08c782-f0b4-4e52-8b30-dbb445b1373e.png)

**Comment by GamerzHell9137** [comment]
Also there still might be issues on the 900 series and 10 series cards because them acted strange while on all other cards it was broken on vulkan until the change was merged to master.

**Comment by Tschensche** [comment]
After the recent update from 1.1.230 to Ryujinx 1.1.280, the game crashes when loading any match or training session. The game runs fine in the menu, everythin is accessible, but no football match or training can be started.

**Comment by lilxluuc** [comment]
i tried playing with a friend. it worked at first until the match started, then we got a message "the match was terminated". that happened in our both attempts. does anybody know what's the issue?

**Comment by SosaXIII** [comment]
I tested multiplayer matches on the Ryujinx main build (v1.1.1297) with Mario Strikers on 7 PCs.

PCs 1-5 (Intel CPU/Nvidia GPU): worked flawless. Could play several matches without match being terminated.
PC 6 (AMD CPU/Nvidia GPU): made the whole lobby disconnect like 1 second into the game with message "match was terminated"
PC 7 (AMD CPU/Nvidia GPU): could not join lobbies and got a Ryujinx message like "could not connect to other consoles" (translated from german). If that pc created a lobby, nobody was able to join and the same message appeared.

I don't know if that's coincidence, but from my testing it looks like an AMD CPU problem. Sadly i dont have more AMD PCs to test it. Maybe someone else can prove that right or wrong.

Also: PC 6 caused Mario Tennis Aces matches to disconnect randomly throughout the match. Could not finish a single match with this pc involved. Without that pc i was able to finish more than 15 matches back to back without a single disconnect.
