### ISSUE TITLE
Teenage Mutant Ninja Turtles: Shredder's Revenge [0100FE701475A000]

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx-Games-List#3912]
#### Current on `master` : 1.1.147

The Game freezes on a white screen after trying to load a movie file or crashes with a error

```
Last error returned.
00:00:38.664 |E| HLE.GuestThread.38 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:38.731 |E| HLE.GuestThread.38 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Memory/MemoryBlock.cs:line 462
   at Ryujinx.Cpu.Jit.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Cpu/Jit/MemoryManager.cs:line 425
   at Ryujinx.Cpu.Jit.MemoryManager.Read[T](UInt64 va) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Cpu/Jit/MemoryManager.cs:line 124
   at Ryujinx.Cpu.Jit.MemoryManager.ReadTracked[T](UInt64 va) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Cpu/Jit/MemoryManager.cs:line 132
```

#### Screenshots :

![image](https://user-images.githubusercontent.com/100526773/174160454-330d1319-72d2-4430-9a7a-a5c3b04a1cc6.png)

#### Log file :

No Crash: [Ryujinx_1.1.147_2022-06-16_21-43-11.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8922358/Ryujinx_1.1.147_2022-06-16_21-43-11.log)

Crash: [Ryujinx_1.1.147_2022-06-16_21-57-35.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8922359/Ryujinx_1.1.147_2022-06-16_21-57-35.log)

**Comment by mmarino4** [comment]
I get the same but if I turn off V-sync and multithreading, it works.  I also let the logos play until the opening video starts.

**Comment by CarolSum** [comment]
> I get the same but if I turn off V-sync and multithreading, it works. I also let the logos play until the opening video starts.

I have tried this way and it WORKS! thanks.

**Comment by taiwan-king** [comment]
Game Update Version : 1.1.0
Current on master : 1.1.159

Starting the game will be randomly dead lock.
Once the start is successful, you can play game to the end.

Hardware Specs :
CPU: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
GPU:NVIDIA GeForce GTX 970
Operating System: Microsoft Windows 10.0.18363 (X64)
RAM : 16GB

**Comment by CarolSum** [comment]
您好，邮件已收到。

**Comment by Daniman666** [comment]
i have this and emu lock 
00:00:01.245 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: An item with the same key has already been added. Key: 357EFC198E728CB5
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey , TValue , InsertionBehavior )
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 , Func`2 , Func`2 , IEqualityComparer`1 )
   at Ryujinx.HLE.HOS.ModLoader.LoadCheats(UInt64 titleId, ProcessTamperInfo tamperInfo, TamperMachine tamperMachine) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ModLoader.cs:line 653
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadExeFs(IFileSystem codeFs, MetaLoader metaData, Boolean isHomebrew) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 663
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNca(Nca mainNca, Nca patchNca, Nca controlNca) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 520
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNsp(String nspFile) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 288
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 815
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1174
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by jjaaxx44** [comment]
> I get the same but if I turn off V-sync and multithreading, it works. I also let the logos play until the opening video starts.

+1 though I have not played much yet.
1.0.3 M1 pro base model

**Comment by chmiiller** [comment]
M1 Pro here and actually just turning off VSync is enough. Thanks for that @mmarino4 ! It also fixed Klonoa for me

**Comment by mrTerryBogard** [comment]
Status: Playble.

Bug: The sound is strange in the intro. Unlike the TMNT collection, tui sound is not cured by changing Vulkan to OpenGL.

**Comment by ballo** [comment]
M2 Max: does not execute past initial game load screen and publisher splash. Disabling vsync did not help.

**Comment by lazywhite** [comment]
> I get the same but if I turn off V-sync and multithreading, it works. I also let the logos play until the opening video starts.

M2 pro: crash
ryujinx: 1.1.1357

**Comment by thecodechef** [comment]
> Instant Crash as soon i tell it to run i have the 1.0.9 update as well as all the DLC and i have tried having both off and still crashes
M1: crash
ryujinx: 1.1.1400

**Comment by lazywhite** [comment]
> I get the same but if I turn off V-sync and multithreading, it works. I also let the logos play until the opening video starts.

this works

**Comment by antoniodesousa** [comment]
> I get the same but if I turn off V-sync and multithreading, it works. I also let the logos play until the opening video starts.
I can confirm this works for me as well. It's just too bad Ryujinx doesn't support per-game settings 😞
