### ISSUE TITLE
nx-hbmenu - 0000000000000000

### ISSUE THREAD

**Issue by MutantAura** [Ryujinx/Ryujinx-Games-List#3925]
#### Current on `master` : 1.1.159

Boots to show an error text and then crashes due to missing service implementations.

```
00:00:05.565 |E| HLE.OsThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Ptm.Ts.IMeasurementServer: 1

Guest Stack Trace:
Process: Service, PID: 93

Raw Request Data:
00000000   53 46 43 49 00 00 00 00  01 00 00 00 00 00 00 00   SFCI············
00000010   00 46 43 4F 00 00 00 00  00 00 00 00               ·FCO········    

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 156
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 219
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 138
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261
```

#### Screenshots :

![image](https://user-images.githubusercontent.com/44103205/175834828-aed4ec29-cd13-4f13-9ca0-030dd81dee5d.png)

#### Log file :

[Ryujinx_1.1.159_2022-06-26_22-39-24.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8987564/Ryujinx_1.1.159_2022-06-26_22-39-24.log)

**Comment by parkerlreed** [comment]
Trying to run this myself. What is nx-hblauncher? I can't find anything by that name.

**Comment by DraconicNEO** [comment]
> Trying to run this myself. What is nx-hblauncher? I can't find anything by that name.

This is [nx-hblauncher](https://github.com/switchbrew/nx-hbmenu/releases) also sometimes referred to as hbmenu.

**Comment by TSRBerry** [comment]
nx-hbmenu and nx-hbloader (or hbl) are different projects:
- [nx-hbmenu](https://github.com/switchbrew/nx-hbmenu)
- [nx-hbloader](https://github.com/switchbrew/nx-hbloader)

**Comment by 995qa** [comment]
Just tested on 1.1.1262, still has the launchInit() Failed error.
![nx-hbmenu_2024-04-06_13-26-24](https://github.com/Ryujinx/Ryujinx-Games-List/assets/67975160/8aed1f9b-a2c6-4924-a2a9-cddaccf184b2)
error.

[Log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14894598/Ryujinx_1.1.1262_2024-04-06_13-26-02.log)

**Comment by gdkchan** [comment]
You are not supposed to launch it directly, you need to launch it from hblauncher. To launch it directly we would have  to emulate hblauncher behaviour.

**Comment by 995qa** [comment]
Where can i download hblauncher?

**Comment by gdkchan** [comment]
> Where can i download hblauncher?

https://github.com/switchbrew/nx-hbloader/releases
(It it actually called hbloader, not hblauncher, I made a mistake).
Place `hbmenu.nro` in the Ryujinx `sdcard` folder. (File > Open Ryujinx Directory, then open the `sdcard` folder).

**Comment by 995qa** [comment]
Ok, I will test soon

**Comment by 995qa** [comment]
It launches! It loads homebdew perfectly too
Cant test controller input because i dont have my controller rn, but the touch works!
![_2024-04-06_15-47-10](https://github.com/Ryujinx/Ryujinx-Games-List/assets/67975160/5db1e31e-2c3d-4be9-8a75-3acf3ccbec3d)

**Comment by 995qa** [comment]
could we change the tags?

**Comment by 995qa** [comment]
Controller works, same as loading any homebrew (that is supported by ryujinx)
