### ISSUE TITLE
Xenoblade Definitive Edition Crashing - Build Version Ryujinx_1.1.0+080a263

### ISSUE THREAD

**Issue by Nobodygr** [Ryujinx/Ryujinx-Games-List#3937]
#### Current on `master` : Commit Id *or* Build Version : Ryujinx_1.1.0+080a263

Game crashes. Im not 100% sure but I think all the times I crashed I was in a menu in the game, maybe a shop menu or a save menu or a skills menu or something similar. Screen freezes then game and console shut down completely.

```
Last error returned.
01:22:55.828 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorUnknown".
   at Ryujinx.Graphics.Vulkan.DescriptorSetManager.DescriptorPoolHolder..ctor(Vk api, Device device) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\DescriptorSetManager.cs:line 22
   at Ryujinx.Graphics.Vulkan.DescriptorSetManager.GetPool(Vk api, Int32 requiredCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\DescriptorSetManager.cs:line 182
   at Ryujinx.Graphics.Vulkan.DescriptorSetManager.AllocateDescriptorSets(Vk api, ReadOnlySpan`1 layouts) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\DescriptorSetManager.cs:line 172
   at Ryujinx.Graphics.Vulkan.DescriptorSetManager.AllocateDescriptorSet(Vk api, DescriptorSetLayout layout) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\DescriptorSetManager.cs:line 161
   at Ryujinx.Graphics.Vulkan.PipelineLayoutCacheEntry.GetNewDescriptorSetCollection(VulkanRenderer gd, Int32 commandBufferIndex, Int32 setIndex, Boolean& isNew) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineLayoutCacheEntry.cs:line 68
   at Ryujinx.Graphics.Vulkan.DescriptorSetUpdater.UpdateAndBindDescriptorSets(CommandBufferScoped cbs, PipelineBindPoint pbp) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\DescriptorSetUpdater.cs:line 281
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(PipelineBindPoint pbp) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1144
   at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32 indexCount, Int32 instanceCount, Int32 firstIndex, Int32 firstVertex, Int32 firstInstance) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 279
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_40(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 141
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 108
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 397
   at System.Threading.Thread.StartCallback()
```

#### Log file :

[Ryujinx_1.1.0+080a263_2022-07-13_23-24-46.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9109054/Ryujinx_1.1.0%2B080a263_2022-07-13_23-24-46.log)

**Comment by MetrosexualGarbodor** [comment]
Please don't open issues for already existing games, and please don't report Vulkan issues outside of the Vulkan PR.
