### ISSUE TITLE
Wunderling - 01001C400482C000

### ISSUE THREAD

**Issue by F1ReB4LL** [Ryujinx/Ryujinx-Games-List#3938]
#### Current on `master` : *1.1.181*

*Works the very first time you start it. After closing the emulator, on further tries, it shows the first logo, then crashes (unless you delete all the PPTC cache files, then it works again). Crash text doesn't go into the log for some reason (all the logging options are checked, though).*

```
Last error returned:

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at Ryujinx.Audio.Renderer.Server.MemoryPool.PoolMapper.ClearUsageState(System.Memory`1<Ryujinx.Audio.Renderer.Server.MemoryPool.MemoryPoolState>)
at Ryujinx.Audio.Renderer.Server.AudioRenderSystem.Dispose(Boolean)
at Ryujinx.Audio.Renderer.Server.AudioRenderSystem.Dispose()
at Ryujinx.HLE.HOS.Services.Audio.AudioRenderer.AudioRenderer.Dispose(Boolean)
at Ryujinx.HLE.HOS.Services.Audio.AudioRenderer.AudioRenderer.Dispose()
at Ryujinx.HLE.HOS.Services.Audio.AudioRenderer.AudioRendererServer.Dispose(Boolean)
at Ryujinx.HLE.HOS.Services.DisposableIpcService.Dispose()
at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32, UInt64)
at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
at Ryujinx.HLE.HOS.Services.ServerBase.Main()
at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
at System.Threading.Thread+StartHelper.RunWorker()
at System.Threading.Thread+StartHelper.Run()
at System.Threading.Thread.StartCallback()
```

#### Screenshots :

![ryujinx_wund1](https://user-images.githubusercontent.com/39680140/179122691-71ee96a2-b5e4-4e05-81f8-21320c533b2e.png)
![ryujinx_wund2](https://user-images.githubusercontent.com/39680140/179124498-3f9d15e1-3139-466b-902d-4b68b8e52571.png)
![ryujinx_wund3](https://user-images.githubusercontent.com/39680140/179124509-7e45db85-bbc4-44a6-bb42-2848ecd0a9f0.png)
![ryujinx_wund4](https://user-images.githubusercontent.com/39680140/179124520-9ac928e2-77f2-4528-9df9-6315babb3ca4.png)

#### Log file :

[Ryujinx_1.1.181_2022-07-15_03-17-50.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9116727/Ryujinx_1.1.181_2022-07-15_03-17-50.log)

**Comment by F1ReB4LL** [comment]
Was working after cleaning the cache/crasing with non-clean cache on 1.1.254 yesterday with the same message as before.

It seems the audio buffer-related changes in in 1.1.257 have changed something, now it always crashes on boot, but with a different message:

```00:00:30.706 |E| HLE.GuestThread.17 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3568
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 53
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 124
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
```

[Ryujinx_1.1.258_2022-09-10_16-14-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9540423/Ryujinx_1.1.258_2022-09-10_16-14-44.log)
