### ISSUE TITLE
SYNTHETIK: Ultimate - 01009BF00E7D2000

### ISSUE THREAD

**Issue by F1ReB4LL** [Ryujinx/Ryujinx-Games-List#3939]
#### Current on `master` : *1.1.182*

*Works with minor graphical glitches - some text and HUD elements on almost every screen (both menus and ingame) are solid black. I've added 2 Yuzu screenshots for comparison (no graphic bugs there).
Sometimes crashes after choosing the language on the very first screen (and the crash text goes to the console, not into the logs)*

```
Last error returned:

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
at Ryujinx.Cpu.Jit.JitCpuContext.Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
at Ryujinx.HLE.HOS.ArmProcessContext`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
at System.Threading.Thread+StartHelper.RunWorker()
at System.Threading.Thread+StartHelper.Run()
at System.Threading.Thread.StartCallback()
```

#### Screenshots :

![ryujinx_sult1](https://user-images.githubusercontent.com/39680140/179359249-8cee8e0c-5a64-44e9-813a-67055e40da27.png)
![ryujinx_sult2](https://user-images.githubusercontent.com/39680140/179359253-aedeb855-dee5-4741-9005-8b27113defcd.png)
![ryujinx_sult3](https://user-images.githubusercontent.com/39680140/179359257-30c4a8c8-c12b-4351-bc01-1bd0bb4ead4f.png)

---
![ryujinx_yuzu1](https://user-images.githubusercontent.com/39680140/179360012-c974ba4e-d546-406b-854f-39ce4a238b8a.png)
![ryujinx_yuzu](https://user-images.githubusercontent.com/39680140/179360014-3c6c5965-e7c8-46f0-b9c2-b057b7bc2a35.png)

#### Log file :

No crash:
[Ryujinx_1.1.182_2022-07-16_07-49-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9126015/Ryujinx_1.1.182_2022-07-16_07-49-33.log)

Crash:
[Ryujinx_1.1.182_2022-07-16_17-24-17.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9126017/Ryujinx_1.1.182_2022-07-16_17-24-17.log)

**Comment by F1ReB4LL** [comment]
The game looks fine now, no "black HUD elements" blending/transparency issues (was most likely fixed by https://github.com/Ryujinx/Ryujinx/pull/3610, since the problem was still there a few versions earlier). Haven't faced any crashes this time, but can't claim they are 100% gone.

![ryujinx_sult8](https://user-images.githubusercontent.com/39680140/187341099-d2cb0639-7b15-4596-a6b9-4bee064497aa.png)
![ryujinx_sult4](https://user-images.githubusercontent.com/39680140/187341115-403cc338-04b0-4d2f-a9e3-19fcd89c227f.png)
![ryujinx_sult5](https://user-images.githubusercontent.com/39680140/187341126-0caecbd9-feb8-482b-86e5-c6d35823d5a1.png)
![ryujinx_sult6](https://user-images.githubusercontent.com/39680140/187341134-3a51ff65-2251-41a7-9296-ecd1faacac02.png)
![ryujinx_sult7](https://user-images.githubusercontent.com/39680140/187341145-a9fd39e8-ccc3-43b0-affb-e87cd1cf6421.png)
