### ISSUE TITLE
Nintendo Labo Toy-Con 04: VR Kit - 0100165003504000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#3976]
#### Graphics Backend : Vulkan

Crashes in early splash screens with a missing service error.

```
Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ISelfController: 67

Guest Stack Trace:
Process: Service, PID: 93

Raw Request Data:
00000000   01 00 10 00 06 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  43 00 00 00 00 00 00 00   SFCI····C·······
00000020   00 00 00 00 00 00 00 00                            ········        

   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 156
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 219
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 138
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 86
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261
```

#### Outstanding Issues : 

https://github.com/Ryujinx/Ryujinx/issues/2264

#### Screenshots :

![2022-08-07 07_09_53-](https://user-images.githubusercontent.com/62343878/183292235-2ba2ee5a-b32e-4da3-8ed5-52d90f25483f.png)

#### Log file :
[Ryujinx_1.1.208_2022-08-07_07-06-31.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9276842/Ryujinx_1.1.208_2022-08-07_07-06-31.log)

**Comment by Luminoso-256** [comment]
With the merge of https://github.com/Ryujinx/Ryujinx/pull/4007, the game now fully boots (though, one might still find it a bit challenging to play, heh.)

![image](https://user-images.githubusercontent.com/63971285/209973953-c82573d6-1f30-4297-bade-a568d6fa367b.png)

**Comment by oscie57** [comment]
I have noticed many graphical glitches when playing this.

Lighting is very off, making things brighter and darker in some things.

---

![image](https://user-images.githubusercontent.com/66192059/213025697-1dcc1e5b-a457-4cb7-a0d5-99982b468943.png)

---

1. Random boxes appear when turning the camera around.
2. Joy-con seems to be missing textures, and, extremely metal-looking.
3. The area around is usually a solid colour on console, but here it varies.
4. Random parts of cardboard are shiny, and super bright.

![image](https://user-images.githubusercontent.com/66192059/213025873-23488433-27c6-4f4c-a16f-6b444c3126c6.png)

**Comment by Luminoso-256** [comment]
I encountered that while I was doing testing... If I remember correctly it might be a Vulkan-only bug? Not sure. Either way, graphics is _far_ outside of my skillset, so no idea how I'd go about solving that.
