### ISSUE TITLE
Kirby’s Dream Buffet - 0100A8E016236000

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#3999]
#### Current on `master` : 1.1.219

The game played well the first time. After enabling pptc or shader cache while playing it spam this message all the time `Invalid texture format 0x7FFFF (sRGB: False).` After 2-3 restarts using Opengl / Vulkan it seems to crash immediately. After skipping the video preview or waiting for the end to reach the game menu, I tried clearing the cache and trying again. It doesn't seem to crash, the solution is simple, just don't have to enable Shader cache or pptc and play.

As for battle/online/local mode, when pressing play it doesn't seem to have any errors other than the local mode it shows a pop-up (maybe playing with LDN)

![bandicam 2022-08-17 07-32-17-335](https://user-images.githubusercontent.com/35269098/185015490-97578651-773f-4b57-83b3-76b6464de4f9.jpg)

This is a message that is spammed all the time during play

![bandicam 2022-08-17 07-33-33-503](https://user-images.githubusercontent.com/35269098/185014269-c028da81-3255-467e-bb54-1f114d579f56.jpg)

I'm not sure if this is a graphics issue or not. When two characters are stacked on top of each other, a small square will be visible.

![bandicam 2022-08-17 07-37-07-016](https://user-images.githubusercontent.com/35269098/185014810-36e87933-5c41-4343-a5dc-a45dfdc79b50.jpg)
![bandicam 2022-08-17 07-37-06-610](https://user-images.githubusercontent.com/35269098/185014947-e1ff3282-0e0b-4dd2-b645-bf941d8709a9.jpg)

```
00:01:20.888 |I| HLE.GuestThread.27 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   0x00000000087c21a8	main:0x7be1a8	
   0x00000000087f54c4	main:0x7f14c4	
   0x00000000088ae590	main:0x8aa590	
   0x00000000088ae318	main:0x8aa318	
   0x00000000088ae974	main:0x8aa974	
   0x0000000008917520	main:0x913520	
   0x00000000096039b8	sdk:0x3779b8	
   0x0000000009609fd4	sdk:0x37dfd4	
   0x0000000000000000


00:01:20.890 |I| HLE.GuestThread.27 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000004a09032b08 (SP:-0xffffffffffffffb8)
	X[01]:	0x0000000000020313
	X[02]:	0x000000000014ffb9
	X[03]:	0x0000000000000001
	X[04]:	0x0000000000000073
	X[05]:	0x00000000085c4098 (main:0x5c0098)	=> 
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x000000656165fc7c
	X[09]:	0x0000000000000092
	X[10]:	0x00000000087f63c0 (main:0x7f23c0)	=> 
	X[11]:	0x00000000000005aa
	X[12]:	0xffffff0000000000
	X[13]:	0x00000065b8c2aa78
	X[14]:	0x0000004a090325f8 (SP:-0xfffffffffffffaa8)
	X[15]:	0x0000000000000000
	X[16]:	0x0000000008bc1370
	X[17]:	0x0000000009839380 (sdk:0x5ad380)	=> 
	X[18]:	0x0000000043564c46
	X[19]:	0x00000065ab4518f0
	X[20]:	0x00000065a6f363e0
	X[21]:	0x0000000000000000
	X[22]:	0x0000000000000006
	X[23]:	0x0000000000000000
	X[24]:	0x000000000000000e
	X[25]:	0x00000065ab451940
	X[26]:	0x00000065ab451970
	X[27]:	0x0014ffb9ff030492
	X[28]:	0x0000000008a25a72
	FP:	0x0000004a09032b70 (SP:-0x0020)
	LR:	0x00000000087f54d8 (main:0x7f14d8)	=> 
	SP:	0x0000004a09032b50 (SP)
	PC:	0x00000000087f63c0 (main:0x7f23c0)	=> 


00:01:20.890 |E| HLE.GuestThread.27 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:01:20.947 |E| HLE.GuestThread.27 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 252
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
  
```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2022-08-17 07-27-59-281](https://user-images.githubusercontent.com/35269098/185010756-97e374b9-60d3-4a85-9491-77c2e6581198.jpg)
![bandicam 2022-08-17 07-28-09-822](https://user-images.githubusercontent.com/35269098/185010769-393cffcb-3a51-4d76-9402-831b29f1b027.jpg)
![bandicam 2022-08-17 07-28-21-099](https://user-images.githubusercontent.com/35269098/185010776-fa396142-6c20-4c83-9e06-2fd3df0fa3c2.jpg)
![bandicam 2022-08-17 07-30-41-226](https://user-images.githubusercontent.com/35269098/185010811-5462b6b8-e198-400a-b0d6-76263f876c00.jpg)
![bandicam 2022-08-17 07-31-05-272](https://user-images.githubusercontent.com/35269098/185010836-dfd250a1-c2a3-4ab8-95c4-92cbe8bd855c.jpg)
![bandicam 2022-08-17 07-31-32-534](https://user-images.githubusercontent.com/35269098/185010844-425f8d8a-45dc-4ae1-9455-55d22cc64e0b.jpg)
![bandicam 2022-08-17 07-31-46-559](https://user-images.githubusercontent.com/35269098/185010852-a0528758-5069-4e2d-a3cb-c95b58e28b83.jpg)
![bandicam 2022-08-17 07-32-06-426](https://user-images.githubusercontent.com/35269098/185010876-1e07a775-bf30-406a-9f3a-e57393aa9c3c.jpg)
![bandicam 2022-08-17 07-33-18-549](https://user-images.githubusercontent.com/35269098/185010922-0e5f0ebc-a7fb-4410-9b13-2852c5fdf163.jpg)
![bandicam 2022-08-17 07-34-00-581](https://user-images.githubusercontent.com/35269098/185010968-88c04ed0-ad52-47ce-8dd5-85f72cd07f6d.jpg)
![bandicam 2022-08-17 07-34-50-466](https://user-images.githubusercontent.com/35269098/185011124-c7074415-dbd5-4f53-aa3d-b78cf61bf314.jpg)
![bandicam 2022-08-17 07-35-22-080](https://user-images.githubusercontent.com/35269098/185011181-00822e37-5163-4b4d-b5ce-e4fe608240d1.jpg)
![bandicam 2022-08-17 07-35-51-177](https://user-images.githubusercontent.com/35269098/185011328-e8f7c06f-a0a5-471e-a1a5-1943ed69d98d.jpg)
![bandicam 2022-08-17 07-35-32-313](https://user-images.githubusercontent.com/35269098/185011385-374cb0ee-3eb4-437b-94b2-2288f43d202e.jpg)
![bandicam 2022-08-17 07-36-35-106](https://user-images.githubusercontent.com/35269098/185011479-94877305-cb83-4796-9bca-634b2758f611.jpg)
![bandicam 2022-08-17 07-37-07-376](https://user-images.githubusercontent.com/35269098/185011798-23cdbf81-a6e0-4f4c-b1a3-ca7dacb9bb16.jpg)
![bandicam 2022-08-17 07-37-31-714](https://user-images.githubusercontent.com/35269098/185011848-13f13eed-d819-49f3-a9c5-63bef6feb23b.jpg)
![bandicam 2022-08-17 07-38-07-332](https://user-images.githubusercontent.com/35269098/185011909-f7d30554-af83-4309-b7c7-235f436ed60c.jpg)
![bandicam 2022-08-17 07-38-27-483](https://user-images.githubusercontent.com/35269098/185012058-e6a7d334-fa5c-4178-9ff8-45ca242d78c3.jpg)
![bandicam 2022-08-17 07-39-17-458](https://user-images.githubusercontent.com/35269098/185012152-06433cc4-636e-40e4-91c3-74bfc5081a15.jpg)
![bandicam 2022-08-17 07-40-16-241](https://user-images.githubusercontent.com/35269098/185012183-07bcc41e-9dcf-44bd-aac2-785221d54b5e.jpg)

#### Logs : Crashes after 2nd replay using previously created cache.

[Ryujinx_1.1.219_2022-08-17_07-42-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9355546/Ryujinx_1.1.219_2022-08-17_07-42-23.log)

#### Logs : First played by spam Invalid texture format 0x7FFFF (sRGB: False) all the time.

[Ryujinx_1.1.219_2022-08-17_07-27-13.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9355569/Ryujinx_1.1.219_2022-08-17_07-27-13.log)

**Comment by EmulationFanatic** [comment]
LDN is working in this game 
![image](https://user-images.githubusercontent.com/62343878/185138831-ec028233-de01-4a35-9ea0-3a53df773896.png)

**Comment by LillyLaFrog** [comment]
I couldn't get the LDN build to launch the game

**Comment by LillyLaFrog** [comment]
that fixed it! thank you! :D

**Comment by GamerzHell9137** [comment]
### Game Name

Kirby's Dream Buffet

### Game Update Version

v1.0.0

### Emulator Build Version

1.1.1217

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 3600*
- ##### GPU: *NVIDIA RTX 3060 TI*
- ##### GPU Driver version: *546.33*
- ##### RAM: *16GB*

### Game State

Game runs fine with no graphical issues.


### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/1d17d3ee-a046-4b94-958d-81ca24526bdc)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/4ad7a0c7-a1a3-407a-946f-03864dbe9fd2)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/7e5bc83e-d01c-4dd6-8a90-aa064f3cebf4)


### Log File

_No response_
