### ISSUE TITLE
Temtem - 0100C8B012DEA000

### ISSUE THREAD

**Issue by yuwenhua653** [Ryujinx/Ryujinx-Games-List#4026]
#### Graphics Backend : *OpenGL*

*When the game starts to the first page, it shows loading and then the emulator crashes, which may be because of the need to connect to the Internet*

```
00:01:42.637 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:01:42.713 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
```

#### Screenshots :
![ryujinx_capture_2022-09-10_08-47-54](https://user-images.githubusercontent.com/30205483/189462146-1ed12eff-7354-4118-b8a6-dcf4d9cac6ad.png)
![ryujinx_capture_2022-09-10_08-47-59](https://user-images.githubusercontent.com/30205483/189462153-04b6d639-fc3b-4fd3-8b79-ded5715a8725.png)

#### Log file :
[Ryujinx_1.1.254_2022-09-10_08-36-51.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9539313/Ryujinx_1.1.254_2022-09-10_08-36-51.log)

**Comment by atuljha12** [comment]
same happen on 1.1.279 with firmware 14+

**Comment by nathangi1990** [comment]
[Ryujinx_1.1.299_2022-10-10_13-26-45.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9745902/Ryujinx_1.1.299_2022-10-10_13-26-45.log)


![image](https://user-images.githubusercontent.com/82410682/194864794-741a7c01-5eb4-499f-805c-966c4f264d40.png)


00:00:00.117 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.299
00:00:00.124 |N| Application Print: Operating System: Microsoft Windows 10.0.19044 (X64)
00:00:00.124 |N| Application Print: CPU: Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz ; 4 logical
00:00:00.126 |N| Application Print: RAM: Total 8084 MB ; Available 3837 MB
00:00:00.490 |N| Application LoadApplication: Using Firmware Version: 14.1.2
00:00:03.749 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 760 (Vulkan v1.2.175, Driver v472.12.0.0)


Process Dump: https://citrix.sharefile.com/d-sdf9e55fb5e864752a981b51fdf7598e0

Process: Application, PID: 92
00:01:26.375 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:01:26.453 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 251
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 124
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()

**Comment by TSRBerry** [comment]
I went through the process of getting a log file for the same crash from someone on Discord, so I'll add it here too.
This crash was produced on 1.1.476 and also contains a guest stack trace: [Ryujinx_redirection_-12-2022_18-24.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10252282/Ryujinx_redirection_-12-2022_18-24.log)
