### ISSUE TITLE
Life is Strange Remastered - 0100DC301186A000

### ISSUE THREAD

**Issue by Djipi71** [Ryujinx/Ryujinx-Games-List#4049]
Tested Version of the game : 1.0.1

Build : 1.1.280

Tested with both Vulkan and OpenGL

The game crash

Hardware Specs : 

CPU: i9-9900K
GPU: NVIDIA RTX 3080
RAM: 32GB

Log file :
[Ryujinx_1.1.280_2022-09-28_21-56-00.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9668568/Ryujinx_1.1.280_2022-09-28_21-56-00.log)

**Comment by gdkchan** [comment]
Please test with resolution scale set to native.

**Comment by IgelRM** [comment]
Confirming, crashes during black screen loading: (same as Ryujinx/Ryujinx/issues/3550)

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.ArmProcessContext`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
```
Log file: [Ryujinx_1.1.280_2022-09-28_22-49-01.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9668851/Ryujinx_1.1.280_2022-09-28_22-49-01.log)

**Comment by EmulationFanatic** [comment]
> Confirming, crashes during black screen loading: (same as [Ryujinx/Ryujinx/issues/3550](https://github.com/Ryujinx/Ryujinx/issues/3550))
> 
> ```
> Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
>    at Ryujinx.Cpu.Jit.JitCpuContext.Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
>    at Ryujinx.HLE.HOS.ArmProcessContext`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute(Ryujinx.Cpu.IExecutionContext, UInt64)
>    at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
> ```
> 
> Log file: [Ryujinx_1.1.280_2022-09-28_22-49-01.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9668851/Ryujinx_1.1.280_2022-09-28_22-49-01.log)

Any reason why you aren't using Vulkan? It should be a better experiencing on AMD GPUs.

**Comment by IgelRM** [comment]
> Any reason why you aren't using Vulkan? It should be a better experiencing on AMD GPUs.

Had tested Vulkan as well, same crash. It's still considered bleeding edge in some ways, so I still try OpenGL.

**Comment by MetrosexualGarbodor** [comment]
Needs an update.

**Comment by EmulationFanatic** [comment]
Updated

**Comment by MarkLanders777** [comment]
It crashes after a while playing in Vulkan with out of device memory error.  

NVIDIA RTX 2060 with 6GB VRAM

**Comment by MetrosexualGarbodor** [comment]
@MarkLanders777 please post a log file when reporting crashes.

**Comment by MarkLanders777** [comment]
the log says the same (it takes all the vram and crashes), I will post the save file to reproduce the error instead. Just play the game in the episode 2 and continue, play the scene and reverse time a few times
[Save Slot 0.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/9691413/Save.Slot.0.zip)

**Comment by IgelRM** [comment]
Confirming, crashes sometimes during quick rewinding.

Log: [Ryujinx_1.1.287_2022-10-02_19-37-26.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/9693133/Ryujinx_1.1.287_2022-10-02_19-37-26.zip)

"
00:11:59.949 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 180
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 49
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, PhysicalDevice physicalDevice, Device device, TextureCreateInfo info, Single scaleFactor, Auto`1 foreignAllocation) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 56
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.CreateTextureView(TextureCreateInfo info, Single scale) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 315
   at Ryujinx.Graphics.Vulkan.VulkanRenderer.CreateTexture(TextureCreateInfo info, Single scale) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanRenderer.cs:line 302
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_5(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 64
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 130
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 107
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 401
   at System.Threading.Thread.StartCallback()
"

---
 Btw: the game flickers a lot on AMD, suppose it doesn't on Nvidia by @EmulationFanatic report.
 
![image](https://user-images.githubusercontent.com/8018939/193468835-fbbc6bc2-c906-4dc9-a237-ab7ea6343549.png)

**Comment by MarkLanders777** [comment]
It's playable from start to finish but the video memory leak is there, you can play for like 30 minutes, but after that the game will eat all your vram (the rewinding thing and resolution x2 can trigger the problem faster)
