### ISSUE TITLE
NieR:Automata The End of YoRHa Edition - 0100B8E016F76000

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx-Games-List#4067]
#### Graphics Backend : Vulkan and OpenGL

First time boot crashed but after that the game runs fine, Runs better on Vulkan than OpenGL. Both run slow because FIFO gets to 100%, the FPS drops under 30. Some minor graphical issue have been seen in the intro sequence.

First boot crash error
```
00:00:14.130 |I| HLE.GuestThread.33 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   0x000000000b3ce360	sdk:0x147360	nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...):0x0120
   0x0000000008a6ada0	main:0xa66da0	
   0x0000000008a654f0	main:0xa614f0	
   0x0000000008a5eecc	main:0xa5aecc	
   0x0000000008a58a58	main:0xa54a58	
   0x0000000008a52550	main:0xa4e550	
   0x0000000008a55a10	main:0xa51a10	
   0x000000000b5c9188	sdk:0x342188	
   0x000000000b5cf714	sdk:0x348714	
   0x0000000000000000


00:00:14.131 |I| HLE.GuestThread.33 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000000000000000
	X[02]:	0x0000000000000004
	X[03]:	0x0000000008fd6e00
	X[04]:	0x0000000000000000
	X[05]:	0x000000000bcb7e79
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000100000000
	X[09]:	0x000000000b287000 (sdk:0x0000)	=> 
	X[10]:	0x0000000000c7ef40
	X[11]:	0x0000000000000080
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000001
	X[14]:	0x0000000000000001
	X[15]:	0x0000000000000000
	X[16]:	0x000000000b3cf900 (sdk:0x148900)	=> nn::diag::detail::Abort(nn::Result const*)
	X[17]:	0x000000000bf05f40
	X[18]:	0x0000000000000001
	X[19]:	0x0000000000000000
	X[20]:	0x0000000008fd6e00
	X[21]:	0x0000000008fd6e00
	X[22]:	0x0000000008fd6e00
	X[23]:	0x000000000bcb7e79
	X[24]:	0x0000000000000002
	X[25]:	0x000000000a189000
	X[26]:	0x000000000a189000
	X[27]:	0x000000000a189ce0
	X[28]:	0x00000015dbdc1110
	FP:	0x00000049bde86c40 (SP)
	LR:	0x000000000b3cf918 (sdk:0x148918)	=> nn::diag::detail::Abort(nn::Result const*):0x0018
	SP:	0x00000049bde86c40 (SP)
	PC:	0x000000000b61e640 (sdk:0x397640)	=> 


00:00:14.133 |W| HLE.GuestThread.17 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = ThreadTerminating
00:00:14.133 |W| HLE.GuestThread.25 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.133 |W| HLE.GuestThread.15 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.133 |W| HLE.GuestThread.34 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.133 |W| HLE.GuestThread.19 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.133 |W| HLE.GuestThread.18 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.133 |W| HLE.GuestThread.24 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.133 |W| HLE.GuestThread.50 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.133 |W| HLE.GuestThread.26 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.133 |W| HLE.GuestThread.51 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.133 |W| HLE.GuestThread.20 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.21 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.54 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.56 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.31 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.23 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.27 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.28 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.52 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.53 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.59 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.30 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.58 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.36 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.57 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.134 |W| HLE.GuestThread.37 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:14.203 |E| HLE.GuestThread.33 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3568
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 53
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 124
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265

```

## OpenGL
![image](https://user-images.githubusercontent.com/2002038/194543356-e1ed9c9e-3e75-43da-ba63-9e8703be3e9c.png)

![image](https://user-images.githubusercontent.com/2002038/194543398-6be003df-268e-4ec7-aba5-6e7ec5b70a9b.png)

## Vulkan

![image](https://user-images.githubusercontent.com/2002038/194544502-70141e1e-bf05-4646-ac55-9d3ed744b282.png)

**Comment by EmulationFanatic** [comment]
Leaving the gpu label off for now since the graphical issues are unconfirmed or possibly occurred only at x2 resolution scaling.

**Comment by yuwenhua653** [comment]
Game has a lot of graphics bugs in AMD gpu
![20221008083113](https://user-images.githubusercontent.com/30205483/194678531-45c13cc2-803c-4d03-a756-920d159c1878.jpg)

**Comment by taiwan-king** [comment]
Game Update Version : 1.0.2
Current on master : 1.1.338

crash in game.

Hardware Specs :
CPU: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
GPU:NVIDIA GeForce GTX 970
Operating System: Microsoft Windows 10.0.18363 (X64)
RAM : 16GB

log:
[Ryujinx_1.1.338_2022-11-05_20-24-51.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9943906/Ryujinx_1.1.338_2022-11-05_20-24-51.log)

**Comment by MetrosexualGarbodor** [comment]
Can you please explain when, where and how you got this crash? And please test with default settings. PPTC and Vsync should not be disabled. @taiwan-king

**Comment by taiwan-king** [comment]
> 
PPTC and Vsync enable.
There is no crash so far.
FPS drops under 30.
Will continue testing, thank you.

**Comment by taiwan-king** [comment]
Game Update Version : 1.0.2
Current on master : 1.1.343

The game can play at the end, and occasionally a random crash appears.

Hardware Specs :
CPU: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
GPU:NVIDIA GeForce GTX 970
Operating System: Microsoft Windows 10.0.18363 (X64)
RAM : 16GB

**Comment by SUNG-JUN-HONG** [comment]
Game Update Version : 1.0.2
Current on master : 1.1.451

![image](https://user-images.githubusercontent.com/47591360/206623234-d47bdbd7-8472-451f-b3e3-d29758c5f9ed.png)
<img width="768" alt="image" src="https://user-images.githubusercontent.com/47591360/206623352-f91f51f7-00a2-4fe8-82f9-3ebb71699e6e.png">

The game crashes after pressing the "Start Game". 


Hardware Specs :

![image](https://user-images.githubusercontent.com/47591360/206623017-005d12d5-65d2-4922-b96a-61969eeecda6.png)
CPU: Intel Core i7 12700H


![image](https://user-images.githubusercontent.com/47591360/206623076-b16c08bd-1a7b-4d52-923e-a813df22dbb5.png)
GPU:NVIDIA GeForce RTX 3070Ti Laptop
Operating System: Microsoft Windows 11 (X64)
RAM : 16GB

The log file is attached below: 

[Ryujinx_1.1.451_2022-12-08_20-16-36.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10191755/Ryujinx_1.1.451_2022-12-08_20-16-36.log)

Thank you for looking into this report.

**Comment by MetrosexualGarbodor** [comment]
@SUNG-JUN-HONG Your comment has been removed for containing piracy websites in the log file.

**Comment by lmewmewl** [comment]
M1 pro, crash after first loading screen

**Comment by Omegaxis** [comment]
Graphics bugs in AMD gpus are still there even on my steam deck

**Comment by jojodunet** [comment]
> Graphics bugs in AMD gpus are still there even on my steam deck

Could you please share a pic ?

**Comment by jojodunet** [comment]
> Graphics bugs in AMD gpus are still there even on my steam deck

@Omegaxis 
Could you please share a pic?

**Comment by jojodunet** [comment]
> Graphics bugs in AMD gpus are still there even on my steam deck

Could you please share a pic?
@Omegaxis

**Comment by levitabris** [comment]
> M1 pro, crash after first loading screen

basic M1, same problem here.

**Comment by DarkTein** [comment]
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/6154129/4f91f936-cde8-45ac-9c97-4c494b55564b)

RX 580  23.4.3 driver

@jojodunet

**Comment by iewnfod** [comment]
Seems like graphic error: Most objects are rendered in black... Only some backgrounds like sky and special effects for fighting and shooting can be rendered properly. 

Game Update Version: 1.0.2
Current on Master: 1.1.1000

Graphic API: Vulkan (I cannot choose OpenGL...)
All settings are the default one. 

Hardware:
CPU & GPU: Apple M1
System: MacOS 13.5

<img width="1627" alt="截屏2023-08-25 22 52 17" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/108739262/2905e621-77c8-4baf-9023-77f16ba4862a">

It is similar but worse than a previous test: [issuecomment-1272178118](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4067#issuecomment-1272178118)

**Comment by unknowgamers** [comment]
> Seems like graphic error: Most objects are rendered in black... Only some backgrounds like sky and special effects for fighting and shooting can be rendered properly.
> 
> Game Update Version: 1.0.2 Current on Master: 1.1.1000 Firware Version: 14.1.2
> 
> Graphic API: Vulkan (I cannot choose OpenGL...) All settings are the default one.
> 
> Hardware: CPU & GPU: Apple M1 System: MacOS 13.5
> 
> <img alt="截屏2023-08-25 22 52 17" width="1627" src="https://user-images.githubusercontent.com/108739262/263303829-2905e621-77c8-4baf-9023-77f16ba4862a.png">
> It is similar but worse than a previous test: [issuecomment-1272178118](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4067#issuecomment-1272178118)

same issue, 
m1 16gb, its work so smooth, the fps always 40-60 but the rendered object (player,NPC,building) just black
its seems like underworld zelda totk before news version come, after update ryujinx that issue already fix
hope this one got same solution

**Comment by deanawge** [comment]
> > Seems like graphic error: Most objects are rendered in black... Only some backgrounds like sky and special effects for fighting and shooting can be rendered properly.
> > Game Update Version: 1.0.2 Current on Master: 1.1.1000 Firware Version: 14.1.2
> > Graphic API: Vulkan (I cannot choose OpenGL...) All settings are the default one.
> > Hardware: CPU & GPU: Apple M1 System: MacOS 13.5
> > <img alt="截屏2023-08-25 22 52 17" width="1627" src="https://user-images.githubusercontent.com/108739262/263303829-2905e621-77c8-4baf-9023-77f16ba4862a.png">
> > It is similar but worse than a previous test: [issuecomment-1272178118](https://github.com/[/issues/4067](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4067)#issuecomment-1272178118)
> 
> same issue, m1 16gb, its work so smooth, the fps always 40-60 but the rendered object (player,NPC,building) just black its seems like underworld zelda totk before news version come, after update ryujinx that issue already fix hope this one got same solution

any update?

**Comment by iewnfod** [comment]
> > > Seems like graphic error: Most objects are rendered in black... Only some backgrounds like sky and special effects for fighting and shooting can be rendered properly.
> > > Game Update Version: 1.0.2 Current on Master: 1.1.1000 Firware Version: 14.1.2
> > > Graphic API: Vulkan (I cannot choose OpenGL...) All settings are the default one.
> > > Hardware: CPU & GPU: Apple M1 System: MacOS 13.5
> > > <img alt="截屏2023-08-25 22 52 17" width="1627" src="https://user-images.githubusercontent.com/108739262/263303829-2905e621-77c8-4baf-9023-77f16ba4862a.png">
> > > It is similar but worse than a previous test: [issuecomment-1272178118](https://github.com/%5B/issues/4067%5D(https://github.com/Ryujinx/Ryujinx-Games-List/issues/4067)#issuecomment-1272178118)
> > 
> > 
> > same issue, m1 16gb, its work so smooth, the fps always 40-60 but the rendered object (player,NPC,building) just black its seems like underworld zelda totk before news version come, after update ryujinx that issue already fix hope this one got same solution
> 
> any update?

Device: M1 Macbook Pro 8GB RAM
System: MacOS
MacOS: 14.0.0
Ryujinx Version: 1.1.1053

The scene can be rendered properly for sometimes now and my computer can only get a nearly 10 fps when fighting (with a 60-70˚C CPU and full fans). Also, Ryujinx might crash when playing. 

Here is some images for the current situation: 
<img width="1551" alt="截屏2023-10-19 17 02 49" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/108739262/fc703fc8-988c-4679-95ad-94ac850832d8">
<img width="1627" alt="截屏2023-10-19 17 05 47" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/108739262/2a218946-43e3-4c96-b3e4-cf7eeaeb5186">

**Comment by Spazzymiku** [comment]
every time i press new game the game restart to the press any button screen those someone have an answer?

**Comment by AcK77** [comment]
Reported in : https://github.com/Ryujinx/Ryujinx/issues/6140

> NieR:Automata The End of YoRHa Edition faces visual flashes in the beginning mission.
> The game runs smoothly(30 fps) till that point at least.

### OS
MacOS 14.2

### Ryujinx version
1.1.1111

### Game version
1.0.2

### CPU
M1 Max

### GPU
M1 Max 32 core

### RAM
32

**Comment by yogithesymbian** [comment]
any updates ? apple m1 ?
