### ISSUE TITLE
NINJA GAIDEN 3: Razor's Edge - 01002AF014F4C000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#4141]
#### Graphics Backend : Vulkan

Went in-game briefly at a low FPS and then crashes (reproducibly after pressing X when prompted) with an audio related error:

```
AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.DataSourceHelper.ProcessWaveBuffers(IVirtualMemoryManager memoryManager, Span`1 outputBuffer, WaveBufferInformation& info, Span`1 wavebuffers, VoiceUpdateState& voiceState, UInt32 targetSampleRate, Int32 sampleCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\DataSourceHelper.cs:line 49
   at Ryujinx.Audio.Renderer.Dsp.Command.DataSourceVersion2Command.Process(CommandList context) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\DataSourceVersion2Command.cs:line 90
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\CommandList.cs:line 124
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 208
```

#### Screenshots :

![2022-10-28 17_58_41-Ryujinx 1 1 330 - NINJA GAIDEN 3_ Razor's Edge v1 0 1 (01002AF014F4C000) (64-bit](https://user-images.githubusercontent.com/62343878/198752243-1efc2b2d-877d-4720-84aa-5caa675499ea.png)
![2022-10-28 17_59_17-Ryujinx 1 1 330 - NINJA GAIDEN 3_ Razor's Edge v1 0 1 (01002AF014F4C000) (64-bit](https://user-images.githubusercontent.com/62343878/198752248-a7369a45-1eb3-4b30-a58b-0a64a659ee4e.png)
![2022-10-28 18_01_25-Ryujinx 1 1 330 - NINJA GAIDEN 3_ Razor's Edge v1 0 1 (01002AF014F4C000) (64-bit](https://user-images.githubusercontent.com/62343878/198752258-52582403-6afe-4214-89d1-673b867b50ab.png)
![2022-10-28 18_02_16-Ryujinx 1 1 330 - NINJA GAIDEN 3_ Razor's Edge v1 0 1 (01002AF014F4C000) (64-bit](https://user-images.githubusercontent.com/62343878/198752272-9d44591d-a335-4f75-a39e-84b9164c75d3.png)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by cesarNeZe** [comment]
i have tested this game on Mac pro M1 
the game crashes on the first jump 

Please fix
