### ISSUE TITLE
Zengeon - 0100057011E50000

### ISSUE THREAD

**Issue by F1ReB4LL** [Ryujinx/Ryujinx-Games-List#4158]
#### Graphics Backend : *Both Vulkan and OpenGL*

*Plays an NVDEC intro (with "mosaics" on some frames, not sure if emulation-related), then crashes (with a network-related error, it seems).*

```
Last error returned: Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.BsdSockAddr.FromIPEndPoint(IPEndPoint endpoint) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Sockets\Bsd\Types\BsdSockAddr.cs:line 27
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient.WriteSockAddr(ServiceCtx context, UInt64 bufferPosition, ISocket socket, Boolean isRemote) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Sockets\Bsd\IClient.cs:line 125
   at Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient.GetSockName(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Sockets\Bsd\IClient.cs:line 608
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 218
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 137
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261
   at System.Threading.Thread.StartCallback()
```

#### Screenshots :

![ryujinx_zgn1](https://user-images.githubusercontent.com/39680140/199363295-a32d432c-3e49-49f4-bd86-7f6b0aca5e1e.png)
![ryujinx_zgn3](https://user-images.githubusercontent.com/39680140/199363303-bfbdd973-25f3-460e-8645-f7e10292cdd9.png)
![ryujinx_zgn2](https://user-images.githubusercontent.com/39680140/199363308-ed016b25-cf16-4833-8df7-80786594d5ba.png)

#### Log file :

[Ryujinx_1.1.335_2022-11-02_02-35-59.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9914707/Ryujinx_1.1.335_2022-11-02_02-35-59.log)

**Comment by F1ReB4LL** [comment]
Was fixed in 1.1.1143 by https://github.com/Ryujinx/Ryujinx/pull/6206

![ryujinx_zgn4](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/08446d35-c8ee-4ffc-a42b-84878bf59cf5)
![ryujinx_zgn5](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/9c29bf27-4404-4533-924b-916e8bacd041)
![ryujinx_zgn6](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/52877d99-b60d-4d97-bb8a-f4f7ea040909)
![ryujinx_zgn7](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/53501b0f-b156-4cea-90a2-e5d5c5afeeba)
![ryujinx_zgn8](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/4ba7feff-5145-4877-a0dc-ced515f0b208)
