### ISSUE TITLE
Ninja Gaiden Sigma 2 - 0100696014FA000

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx-Games-List#4200]
#### Graphics Backend : Vulkan

Loads past the title screen but crashed with an audio related error during a new game intro video.

```
AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.DataSourceHelper.ProcessWaveBuffers(IVirtualMemoryManager memoryManager, Span`1 outputBuffer, WaveBufferInformation& info, Span`1 wavebuffers, VoiceUpdateState& voiceState, UInt32 targetSampleRate, Int32 sampleCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\DataSourceHelper.cs:line 49
   at Ryujinx.Audio.Renderer.Dsp.Command.DataSourceVersion2Command.Process(CommandList context) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\DataSourceVersion2Command.cs:line 90
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\CommandList.cs:line 116
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 179
```

#### Screenshots :
![2022-11-13 09_29_47-Ryujinx 1 1 343 - NINJA GAIDEN Σ2 v1 0 2 (0100696014F4A000) (64-bit)](https://user-images.githubusercontent.com/62343878/201532914-2289ab2d-88c0-4fac-a99e-f75651cbdf77.png)

**Comment by DragonSlayer220** [comment]
I play on mac but ryujinx suddenly crash when I get to a certain point of the story, over and over.

**Comment by Veltiel** [comment]
> I play on mac but ryujinx suddenly crash when I get to a certain point of the story, over and over.

I got the same issue on Windows 10. It's on the second chapter, right? When you finish off the enemy ninjas right at the temple entrance, I got a repeatable crash. On Yuzu this doesn't happen. Will the OPs update this thread?

**Comment by gdkchan** [comment]
Attach log and save near the point where it crashes, along with instructions of how to reproduce it, otherwise the instruction is unlikely to be looked at.

**Comment by pancakefactor1** [comment]
> > I play on mac but ryujinx suddenly crash when I get to a certain point of the story, over and over.
> 
> I got the same issue on Windows 10. It's on the second chapter, right? When you finish off the enemy ninjas right at the temple entrance, I got a repeatable crash. On Yuzu this doesn't happen. Will the OPs update this thread?

Getting the exact same crash on M1 Macbook Air 2020. If anyone could explain how to attach a log before the crash I would be willing to do it.

**Comment by Veltiel** [comment]
[Ryujinx_1.1.819_2023-05-23_23-07-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14455106/Ryujinx_1.1.819_2023-05-23_23-07-44.log)

Here is my crashlog from last year. As stated above, Ninja Gaiden 2 Sigma crashes right before entering the temple, while fighting the black spider ninjas. I don't know if this has been fixed. This crash occurs only on RyujinX. Yuzu is fine, and the game is fully playable there.

**Comment by gdkchan** [comment]
Please attach a save near the place where the game crashes, otherwise it will be hard for someone else to reproduce this issue. Also include instructions of how to get it to crash.

**Comment by GamerzHell9137** [comment]
> [Ryujinx_1.1.819_2023-05-23_23-07-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14455106/Ryujinx_1.1.819_2023-05-23_23-07-44.log)
> 
> Here is my crashlog from last year. As stated above, Ninja Gaiden 2 Sigma crashes right before entering the temple, while fighting the black spider ninjas. I don't know if this has been fixed. This crash occurs only on RyujinX. Yuzu is fine, and the game is fully playable there.

You got the wrong log, there's nothing in it. Go trough the same place and make the emulator crash, after that send the log.

**Comment by dirtybytes** [comment]
The game also crashes for me occasionally (both in the first and second chapters), here's two logs and the last save files. The last crash happened a couple seconds after I picked up talons.
[Ryujinx_1.1.1214_2024-03-01_22-08-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14467418/Ryujinx_1.1.1214_2024-03-01_22-08-28.log)
[Ryujinx_1.1.1214_2024-03-02_04-02-21.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14467419/Ryujinx_1.1.1214_2024-03-02_04-02-21.log)
[ninjagaidensigma2saves.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/14467421/ninjagaidensigma2saves.zip)

**Comment by Veltiel** [comment]
Ok, now you have the right log from another user. I hope you can look into this. I'll make RyujinX crash later, :P

**Comment by GamerzHell9137** [comment]
The game crashes because of audio related issues

```00:03:17.265 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 25
00:03:17.514 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 24
00:03:17.514 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 25
00:03:27.100 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 24
00:03:27.100 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 25
00:03:28.899 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 24
00:03:28.899 |E| AudioProcessor.Worker AudioRenderer GetCoefficientAtIndex: Out of bound read for coefficient at index 25
00:03:41.125 |E| AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.DataSourceHelper.ProcessWaveBuffers(IVirtualMemoryManager memoryManager, Span`1 outputBuffer, WaveBufferInformation& info, Span`1 wavebuffers, VoiceUpdateState& voiceState, UInt32 targetSampleRate, Int32 sampleCount) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Audio\Renderer\Dsp\DataSourceHelper.cs:line 49
   at Ryujinx.Audio.Renderer.Dsp.Command.DataSourceVersion2Command.Process(CommandList context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Audio\Renderer\Dsp\Command\DataSourceVersion2Command.cs:line 88
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Audio\Renderer\Dsp\Command\CommandList.cs:line 116
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 207
   at System.Threading.Thread.StartCallback()```

**Comment by GamerzHell9137** [comment]
### Game Name

Ninja Gaiden Sigma 2

### Game Update Version

v1.0.0

### Emulator Build Version

1.1.1363

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 7800X3D*
- ##### GPU: *NVIDIA RTX 3060 TI*
- ##### GPU Driver version: *555.99*
- ##### RAM: *32GB*

### Game State

Game runs with no graphical issues but crashes during gameplay.

> [!NOTE]  
> The issue stems from a audio crash during gameplay which occurs when fighting with enemies.

### Screenshots

![image](https://github.com/user-attachments/assets/c8c295ac-c927-4ebd-8a52-a1f8895546da)
![image](https://github.com/user-attachments/assets/4dcda756-7876-46fa-9752-ecdf54725753)


### Log File

[Ryujinx_1.1.0+26dc8fb_2024-07-31_23-38-34.log](https://github.com/user-attachments/files/16447498/Ryujinx_1.1.0%2B26dc8fb_2024-07-31_23-38-34.log)
