### ISSUE TITLE
ODDWORLD SOULSTORM - 0100D210177C6000

### ISSUE THREAD

**Issue by sovcali** [Ryujinx/Ryujinx-Games-List#4222]
ODDWORLD SOULSTORM - 0100D210177C6000

 Game Update Version : 1.0.0

Current on `master` : 1.1.361

Graphics Backend : `Vulkan`

Game starts and shows loading screen then crashes, tried on Yuzu and works fine.

`00:00:25.349 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3439
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 130
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
`

Hardware Specs : 

CPU: i7-11800H
GPU: NVIDIA RTX 3060
RAM: 16GB

Screenshots :

![image](https://user-images.githubusercontent.com/95439008/202764801-0b78681e-5151-47e8-b155-8ec44cf5b1a0.png)

Log file :

[https://drive.google.com/file/d/19zRSw2FlFWZBcNuOtd4hv952AVqVjw8d/view?usp=sharing](LOG)

**Comment by MetrosexualGarbodor** [comment]
Please upload the log onto the post instead of using Google Drive.

**Comment by sovcali** [comment]
> Please upload the log onto the post instead of using Google Drive.

UPDATED

**Comment by 0megaron** [comment]
still the same error in version 1.1.362

**Comment by cddude** [comment]
Same issue persists

Game version 1.1.3
Ryujinx version 1.1.1344
Mac mini M2 Pro 16 GB RAM

[Ryujinx_1.1.1344_2024-07-10_01-19-05.log](https://github.com/user-attachments/files/16155573/Ryujinx_1.1.1344_2024-07-10_01-19-05.log)

**Comment by gh0sti** [comment]
so looks like still a known issue glad I am not the only one.
