### ISSUE TITLE
The Oregon Trail - 0100B080184BC000

### ISSUE THREAD

**Issue by Rolbag** [Ryujinx/Ryujinx-Games-List#4229]
#### Graphics Backend : *Vulkan*

*After the first text (see screenshot), Ryujinx crashes*

```
Log says:
00:01:27.153 |E| HLE.OsThread.16 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
```

#### Screenshot: 

![Screenshot_3](https://user-images.githubusercontent.com/118939844/203660115-0b64f77d-5be5-4ac5-904b-311452db3662.png)

#### Log file :

*[Ryujinx_1.1.373_2022-11-23_22-38-55.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10079603/Ryujinx_1.1.373_2022-11-23_22-38-55.log)*

**Comment by MetrosexualGarbodor** [comment]
Please edit the post and drag and drop the log file into it. Also add a screenshot if the game renders anything.

**Comment by Rolbag** [comment]
> Please edit the post and drag and drop the log file into it. Also add a screenshot if the game renders anything.

Done. :)

**Comment by Rolbag** [comment]
I updated to 1.1.376 and could start the tutorial until everyone was healt and repaired the horse-drawn carriage, then it crashes again completly
[Ryujinx_1.1.376_2022-11-24_07-23-17.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10081419/Ryujinx_1.1.376_2022-11-24_07-23-17.log)

**Comment by gdkchan** [comment]
Does it not work with guest internet access disabled in the settings?

**Comment by Rolbag** [comment]
> 

I disabled it and could complete the tutorial without any hickups. Just some flickering. :)

**Comment by EmulationFanatic** [comment]
We leave the issues open for compatibility catalogging.

**Comment by Rolbag** [comment]
The screen flickering I meantion before. Was in the complete game.

https://user-images.githubusercontent.com/118939844/203780228-1a8eb2d9-741d-495c-9938-830b5a34b44f.mp4

No more issues found.

**Comment by GD825** [comment]
i do get random crashes in the game as well.. like i can play for quite a bit, then   ryu just crashes itself out.. sometimes it happens right away.. maybe  it has something to do with the fact that the game is looking for a network connection for some reason? (If you try  to play this game on a network banned switch, you cant even get into the game itself as it just spams the switch is banned message over and over).. so maybe this could be related to ryu's issues with the game?

---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean, Byte[], CancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String, X509CertificateCollection , SslProtocols, Boolean)
   at Ryujinx.HLE.HOS.Services.Ssl.SslService.SslManagedSocketConnection.Handshake(String hostName) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Ssl\SslService\SslManagedSocketConnection.cs:line 97
   at Ryujinx.HLE.HOS.Services.Ssl.SslService.ISslConnection.DoHandshakeGetServerCert(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\Ssl\SslService\ISslConnection.cs:line 203
   at InvokeStub_ISslConnection.DoHandshakeGetServerCert(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\IpcService.cs:line 66
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 320
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 90
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 85
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1261

**Comment by gdkchan** [comment]
Those crashes are caused by the game trying to connect to GameLoft servers. You can just disable guest internet access on the settings to stop it from doing that.
