### ISSUE TITLE
Super Mario Odyssey - 0100000000010000

### ISSUE THREAD

**Issue by MerBudd** [Ryujinx/Ryujinx-Games-List#4248]
##### RAM: *(8GB)*

The game runs good most of the time, but there are a few issues:
1st - The game assets flicker sometimes and there's also some tearing both with and without VSync enabled.
2nd - In Ruined Kingdom, the game keeps crashing, possibly because of a missing MoltenVK API call. I didn't find the issue to happen on other kingdoms. I attached my save file below.
<img width="372" alt="Crash Error Screen" src="https://user-images.githubusercontent.com/82082386/204881443-139d9188-21be-4a02-a36f-4f61fd16d3dc.png">
[File1.bin.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/10126280/File1.bin.zip)

```
Last error returned:

HLE.GuestThread.16 Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.PersistentFlushBuffer.GetTextureData(CommandBufferPool cbp, TextureView view, Int32 size, Int32 layer, Int32 level) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Vulkan/PersistentFlushBuffer.cs:line 81
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.FlushTextureDataSliceToGuest(Boolean tracked, Int32 sliceIndex, ITexture texture) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs:line 420
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.<>c__DisplayClass66_0.<FlushAction>b__0() in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs:line 1434
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.FlushAction(TextureGroupHandle handle, UInt64 address, UInt64 size) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.Gpu/Image/TextureGroup.cs:line 1416
   at Ryujinx.Memory.Tracking.RegionHandle.Signal(UInt64 address, UInt64 size, Boolean write, IList`1& handleIterable) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Memory/Tracking/RegionHandle.cs:line 259
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 273
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.DataAbort(MemoryTracking tracking, UInt64 vcpu, UInt32 esr) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 227
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.SynchronousException(HvMemoryManager memoryManager, HvVcpu& vcpu) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 169
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.Execute(HvMemoryManager memoryManager, UInt64 address) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 160
   at Ryujinx.Cpu.AppleHv.HvCpuContext.Execute(IExecutionContext context, UInt64 address) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvCpuContext.cs:line 30
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/HOS/ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
```

#### Screenshots:
![SMO](https://user-images.githubusercontent.com/82082386/204885600-b751f9ae-6ba9-4c8b-a45d-7eafcd4a8dc8.png)

#### Log file:
[Ryujinx_ 1.1.0-macos1_2022-11-30_21-18-17.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10126295/Ryujinx_.1.1.0-macos1_2022-11-30_21-18-17.log)

**Comment by MetrosexualGarbodor** [comment]
Please post this on #93. Closing as duplicate.

**Comment by mrTerryBogard** [comment]
All the videos run as if there is not enough memory. The sound is just terrible. However, there are no problems in the game.
