### ISSUE TITLE
Ace Angler: Fishing Spirits - 01007C50132C8000

### ISSUE THREAD

**Issue by justwannafish** [Ryujinx/Ryujinx-Games-List#4251]
##### RAM: 16GB

When starting up the game, it asks for the system to be in handheld mode, one player, JoyConPair. Playing in docked mode also causes Ryujinx to continuously prompt for said setting change.
The game seems to run very well, at least throughout the intro. However, after finishing character creation, the game tries to load into the hub area for the first time and crashes at the loading screen. No other issues seem present up until then.

```
00:02:20.273 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3424
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 130
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
```

#### Screenshots:
![ryujinx_capture_2022-12-01_14-46-03](https://user-images.githubusercontent.com/119627377/205156345-c22fcab4-c442-4ab3-97b8-c9c4785f300e.png)
![ryujinx_capture_2022-12-01_14-46-39](https://user-images.githubusercontent.com/119627377/205156351-fef93fb5-efa3-4a9b-9f98-69b461e9326b.png)
![ryujinx_capture_2022-12-01_14-47-08](https://user-images.githubusercontent.com/119627377/205156361-d0a393a8-d7da-43dc-8e76-4007e8cccf3a.png)

#### Log file:
[Ryujinx_1.1.407_2022-12-01_13-40-58.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10136033/Ryujinx_1.1.407_2022-12-01_13-40-58.log)

**Comment by Cronos-0** [comment]
Updated in the latest version. The game still crashes as before. But can be played after loading to the hub area. And start fishing for the first time, the game will crash immediately on the loading page

### Game Name

Ace Angler: Fishing Spirits

### Game Update Version

1.0.0

### Emulator Build Version

1.1.647

### Graphics Backend

Vulkan

### Hardware Specs

- #### GPU: GTX 1660 SUPER 6GB
- #### CPU: INTEL I5 8400
- #### RAM: KINGSTON DDR4 16GB


### Game State

Updated in the latest version. The game still crashes as before. But can be played after loading to the hub area. And start fishing for the first time, the game will crash immediately on the loading page

- This is a message that is spammed all the time
```
00:02:18.220 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Votevtg is not implemented.
```
```
00:06:09.984 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
```

### Screenshots

![bandicam 2023-03-03 09-37-25-302](https://user-images.githubusercontent.com/35269098/222622506-7982febe-1190-4cf6-a576-4556ce546a99.jpg)
![bandicam 2023-03-03 09-37-10-141](https://user-images.githubusercontent.com/35269098/222622521-1a628a28-54d1-42da-b317-d0a9867c2b37.jpg)
![bandicam 2023-03-03 09-39-06-686](https://user-images.githubusercontent.com/35269098/222622537-fa801d19-e025-4c0b-a3ab-4a33b96ca60c.jpg)
![bandicam 2023-03-03 09-40-46-168](https://user-images.githubusercontent.com/35269098/222622550-c2b3eac6-a4e5-48c0-a4e1-5cf3c87f7321.jpg)
![bandicam 2023-03-03 09-41-15-080](https://user-images.githubusercontent.com/35269098/222622571-32be87f8-db16-46fd-bdee-e9f89a2711b8.jpg)
![bandicam 2023-03-03 09-41-21-174](https://user-images.githubusercontent.com/35269098/222622579-c3a0eefc-92e4-4367-8629-03814d1293f1.jpg)
![bandicam 2023-03-03 09-41-37-965](https://user-images.githubusercontent.com/35269098/222622586-287ecdb7-db69-4b7d-bae5-8fb4bd90189f.jpg)
![bandicam 2023-03-03 09-41-52-569](https://user-images.githubusercontent.com/35269098/222622591-5ade3e92-0d77-4fda-8f9b-55a5f57fa2fe.jpg)
![bandicam 2023-03-03 09-42-04-184](https://user-images.githubusercontent.com/35269098/222622597-4b840dcf-0b70-44b9-851d-0ed4e4d57831.jpg)

### Log File

[Ryujinx_1.1.647_2023-03-03_09-28-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10877874/Ryujinx_1.1.647_2023-03-03_09-28-44.log)
