### ISSUE TITLE
Sword of the Necromancer - 0100E4701355C000

### ISSUE THREAD

**Issue by F1ReB4LL** [Ryujinx/Ryujinx-Games-List#4279]
##### RAM: *24GB*

*Works mostly fine, but sometimes crashes when leaving the lobby (where your girlfriend is "sleeping"), not yet sure how to exactly trigger the crash.*

```
Last error returned: Application : Unhandled exception caught: System.InvalidOperationException: Decoded a single empty exit block. Entry point = 0xC600000042000000.
   at ARMeilleure.Decoders.Decoder.Decode(IMemoryManager memory, UInt64 address, ExecutionMode mode, Boolean highCq, DecoderMode dMode)
   at ARMeilleure.Translation.Translator.GetOrTranslate(UInt64 address, ExecutionMode mode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 180
   at ARMeilleure.Instructions.NativeInterface.GetFunctionAddress(UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 194
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 130
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
```

#### Screenshots:

![ryujinx_sotn1](https://user-images.githubusercontent.com/39680140/206821592-9307e486-d619-4e7e-a3d4-bcaa8cec1933.png)
![ryujinx_sotn2](https://user-images.githubusercontent.com/39680140/206821598-5ccb05e8-8e33-417f-a3c3-51fed8ff4ff2.png)
![ryujinx_sotn3](https://user-images.githubusercontent.com/39680140/206821599-c7a0cdb9-0863-4db6-91cf-0572784133ca.png)
![ryujinx_sotn4](https://user-images.githubusercontent.com/39680140/206821604-f72b0001-0b33-410f-989d-47edb22d6467.png)
![ryujinx_sotn5](https://user-images.githubusercontent.com/39680140/206821698-94b537b6-df65-4f72-ba41-eef97d37f3e2.png)
![ryujinx_sotn6](https://user-images.githubusercontent.com/39680140/206821608-84a049bd-5a1b-44e3-995e-6bbf9b7889e7.png)
![ryujinx_sotn7](https://user-images.githubusercontent.com/39680140/206821613-f9afaf7e-847b-4019-b930-5bc480e82e14.png)
![ryujinx_sotn8](https://user-images.githubusercontent.com/39680140/206821617-656a75fb-cfb2-4da0-a156-22392586403c.png)
![ryujinx_sotn9](https://user-images.githubusercontent.com/39680140/206821621-33f0bde3-1c37-4713-8891-0b28bc678b33.png)

#### Log file:

[Ryujinx_1.1.450_2022-12-08_13-20-23.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10198958/Ryujinx_1.1.450_2022-12-08_13-20-23.log)

**Comment by F1ReB4LL** [comment]
The intro is NVDEC, I guess (lots of ServiceNv and ServiceMm calls when playing).
