### ISSUE TITLE
Yu-Gi-Oh! Rush Duel: Dawn of the Battle Royale!! Let's Go! Go Rush!! - 01002D60188DE000

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#4311]
#### Graphics Backend: Vulkan

This game can be played But random errors occur. Of course it can continue to play even if the error is displayed in the console. It's really weird. Normally it crashes immediately. But this time it still play. I tried with ava it won't boot or in console it doesn't show any error. It just freezes and nothing happens, which is weird

```
00:00:02.706 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> DiscordRPC.Exceptions.StringOutOfRangeException: Length of string is out of range. Expected a value with a maximum length of 128

00:11:30.072 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.FormatException: The string 'Never' was not recognized as a valid DateTime. There is an unknown word starting at index '0'.
   at System.DateTimeParse.Parse(ReadOnlySpan`1, DateTimeFormatInfo, DateTimeStyles)
   at System.DateTime.Parse(String s)
   at Ryujinx.Ui.MainWindow.<>c.<UpdateGameMetadata>b__97_0(ApplicationMetadata appMetadata) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1019
   at Ryujinx.Ui.App.Common.ApplicationLibrary.LoadAndSaveMetaData(String titleId, Action`1 modifyFunction) in D:\a\Ryujinx\Ryujinx\Ryujinx.Ui.Common\App\ApplicationLibrary.cs:line 518
   at Ryujinx.Ui.MainWindow.UpdateGameMetadata(String titleId) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1017
   at Ryujinx.Ui.MainWindow.StopEmulation_Pressed(Object sender, EventArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1329
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Screenshots :

![bandicam 2022-12-30 11-44-05-396](https://user-images.githubusercontent.com/35269098/210036699-c7a92ed1-a7c8-463e-8067-418ef81047fc.jpg)
![bandicam 2022-12-30 11-44-18-682](https://user-images.githubusercontent.com/35269098/210036704-0e5a7519-ab59-4412-a4cc-8afa84dc263f.jpg)
![bandicam 2022-12-30 11-44-33-582](https://user-images.githubusercontent.com/35269098/210036709-e5edf8c9-81f7-431a-b236-1e73b03906d2.jpg)
![bandicam 2022-12-30 11-45-18-761](https://user-images.githubusercontent.com/35269098/210036715-ec37e1f1-ad91-45c2-a2fe-67e505354e6d.jpg)
![bandicam 2022-12-30 11-46-12-253](https://user-images.githubusercontent.com/35269098/210036724-8e0ef06b-9352-456e-a2ae-4b7fa3411a84.jpg)
![bandicam 2022-12-30 11-47-49-072](https://user-images.githubusercontent.com/35269098/210036733-212835e3-2f71-4dd7-8d32-38f49e248274.jpg)
![bandicam 2022-12-30 11-48-17-069](https://user-images.githubusercontent.com/35269098/210036737-6e64e338-eaab-4102-b337-3936c4cfa45c.jpg)
![bandicam 2022-12-30 11-50-22-103](https://user-images.githubusercontent.com/35269098/210036747-c18ccde8-2ca3-4585-bc94-3d1435819488.jpg)
![bandicam 2022-12-30 11-51-06-481](https://user-images.githubusercontent.com/35269098/210036757-4c9858c5-c5ca-4930-94e9-8cea26e613e1.jpg)
![bandicam 2022-12-30 11-52-01-115](https://user-images.githubusercontent.com/35269098/210036762-012727fd-b034-490c-8ba2-45ea334feafe.jpg)
![bandicam 2022-12-30 11-52-21-201](https://user-images.githubusercontent.com/35269098/210036770-a180a307-da2d-45b4-9f6f-a218f124ab21.jpg)
![bandicam 2022-12-30 11-53-20-576](https://user-images.githubusercontent.com/35269098/210036779-97698bd9-ac61-4bbb-befd-4ad5d076493b.jpg)
![bandicam 2022-12-30 11-54-06-066](https://user-images.githubusercontent.com/35269098/210036791-b0b3029e-bba8-4435-81b9-53e2d21d2bd8.jpg)
![bandicam 2022-12-30 11-54-27-788](https://user-images.githubusercontent.com/35269098/210036799-c9449bf0-b6ad-4545-8544-c392585975c9.jpg)

#### Logs :

[Ryujinx_1.1.500_2022-12-30_11-42-26.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10323175/Ryujinx_1.1.500_2022-12-30_11-42-26.log)

**Comment by Cronos-0** [comment]
Update now playable I have tested it 3 times to make sure it won't crash again. More in online mode does not seem to work. I tried with the LDN build but nothing happened.
