### ISSUE TITLE
Ryujinx Crashes Upon ACNH Launch

### ISSUE THREAD

**Issue by RyujinxFTW** [Ryujinx/Ryujinx-Games-List#433]
#### V1.1.0

The game doesn’t even start before it crashes other than show a black screen and approximately 59FPS.

Here is the log file:

00:00:02.601 | Application LoadApplication: Loading as XCI.

00:00:08.857 | GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: OpenTK.Graphics.GraphicsContextException: Failed to make context 65537 current. Error: 170

at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window)

at OpenTK.Graphics.GraphicsContext.MakeCurrent(IWindowInfo window)

at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 309

at System.Threading.ThreadHelper.ThreadStart_Context(Object state)

at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location where exception was thrown ---

at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

at System.Threading.ThreadHelper.ThreadStart()

**Comment by AcK77** [comment]
Closed because of #250
