### ISSUE TITLE
Neon White

### ISSUE THREAD

**Issue by Cowman5** [Ryujinx/Ryujinx-Games-List#4347]
##### RAM: 16GB

The game has run flawlessly at 60 fps for maybe the first half of the game. The only issue is that there is now a new level that can not open without crashing ryujinx.

[Neon White save.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/10370162/Neon.White.save.zip)

```

Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs:line 99
   at System.Threading.Thread.StartCallback()

```

#### Screenshots:

*Add screenshots here (preferably on windowed mode) if the game is rendering.*

#### Log file:
[Ryujinx_ 1.1.0-macos1_2023-01-08_13-08-32.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10370173/Ryujinx_.1.1.0-macos1_2023-01-08_13-08-32.log)

**Comment by Cowman5** [comment]
> Please add some screenshots.

Of the game while it's working? There are no graphical issues I could screenshot before it crashes

**Comment by AutumnWolfMike** [comment]
For me the game works but I keep running into this error, it usually happens when I reload a stage

Specs: 16GB RAM, RTX 3050, Ryzen 5500

```
00:36:36.546 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 180
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 57
   at Ryujinx.Graphics.Vulkan.TextureStorage..ctor(VulkanRenderer gd, PhysicalDevice physicalDevice, Device device, TextureCreateInfo info, Single scaleFactor, Auto`1 foreignAllocation) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\TextureStorage.cs:line 162
   at Ryujinx.Graphics.Gpu.Image.Texture.InitializeData(Boolean isView, Boolean withData) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 258
   at Ryujinx.Graphics.Gpu.Image.TextureCache.FindOrCreateTexture(MemoryManager memoryManager, TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureCache.cs:line 856
   at Ryujinx.Graphics.Gpu.Image.TextureCache.FindOrCreateTexture(MemoryManager memoryManager, RtColorState colorState, Boolean layered, Int32 samplesInX, Int32 samplesInY, Size sizeHint) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureCache.cs:line 349
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateRenderTargetState(Boolean useControl, Boolean layered, Int32 singleUse) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 410
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount, Int32 drawFirstVertex, Int32 drawVertexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 120
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 argument) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 107
   at Macro(MacroJitContext, IDeviceState, Int32)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoClass.CallMme(Int32 index, IDeviceState state) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoClass.cs:line 245
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 207
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__75_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 403
   at Ryujinx.Graphics.GAL.IRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\IRenderer.cs:line 49
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 401
   at System.Threading.Thread.StartCallback()

```

**Comment by Jgreene2023** [comment]
Was this issue resolved? If so how can I fix it? I am running into the same issue on a 2020 m1 MacBook Pro

**Comment by Cowman5** [comment]
> Was this issue resolved? If so how can I fix it? I am running into the same issue on a 2020 m1 MacBook Pro

No it has not been resolved as far as I can tell. Is your game crashing on the same level as mine?

**Comment by Jgreene2023** [comment]
Yeah, same level.

**Comment by ADAMSSSSSSSSSSSSSSS** [comment]
Found a workaround - 

open your savedata.dat in TextEdit
scroll down a little bit and locate this:

"_missionInProgress": true,
"_farthestLevel": 7,
"_archiveUnlocked": false

Change the "_farthestLevel": **7** to an "_farthestLevel": **8** and save. You'll skip the level that causes the crash.

Note - my savedata.dat was in two folders and I needed to replace both of them to make it work, I haven't played much more but the rest of the game seems to be working fine.

**Comment by ADAMSSSSSSSSSSSSSSS** [comment]
If you don't know how to go to your game saves -

Open Ryujinx
File - Open Ryujinx Folder
Open "bis"
Open "user"
Open "save"

You'll see folders labeled 0000000000000001, 0000000000000002, etc...
Find the one with a bunch of files that start with "Ghosts"
Find your savedata.dat. Copy and paste is on your desktop so you can restore it in the event you mess it up
Edit the file as described above in TextEdit
Make sure the edited savedata.dat file is in both 0 and 1 of the 000000000000000(Number) folder

**Comment by Cowman5** [comment]
> Found a workaround -
> 
> open your savedata.dat in TextEdit scroll down a little bit and locate this:
> 
> "_missionInProgress": true, "_farthestLevel": 7, "_archiveUnlocked": false
> 
> Change the "_farthestLevel": **7** to "_farthestLevel": **8** and save. You'll skip the level that causes the crash.
> 
> Note - my savedata.dat was in two folders and I needed to replace both of them to make it work. I haven't played much more but the rest of the game seems to be working fine.

Worked for me! Thanks so much.
