### ISSUE TITLE
Lone Ruin - 0100B6D016EE6000

### ISSUE THREAD

**Issue by F1ReB4LL** [Ryujinx/Ryujinx-Games-List#4360]
### Is there an existing issue for the game?

- [X] I have searched the existing game issues

### Game Name

Lone Ruin

### Game Update Version

1.0

### Emulator Build Version

1.1.559

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: *i5-11400H*
- ##### GPU: *NVIDIA RTX 3050*
- ##### RAM: *24GB*

### Game State

Mostly works. Sometimes crashes when you're killed and trying to return to main menu from the "you died" screen with the following error:
```
Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 275
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270
   at System.Threading.Thread.StartCallback()
```

If you're trying to access leaderboards with a guest internet access enabled, always crashes with another error:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at Ryujinx.Memory.AddressSpaceManager.Write(UInt64, System.ReadOnlySpan`1<Byte>)
   at Ryujinx.HLE.HOS.Services.Sockets.Nsd.IManager.ResolveEx(Ryujinx.HLE.HOS.ServiceCtx)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(Ryujinx.HLE.HOS.ServiceCtx)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32, UInt64)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Services.ServerBase.Main()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
```

Also reports about an unimplemented shader (https://github.com/Ryujinx/Ryujinx/issues/2794):
```
Shader translator: Shader instruction Votevtg is not implemented.
```

### Screenshots

![ryujinx_lrn0](https://user-images.githubusercontent.com/39680140/212621544-7b7f9d4f-617f-4056-b922-90ef95a4b397.png)
![ryujinx_lrn1](https://user-images.githubusercontent.com/39680140/212621629-e1e5549c-4217-4bd7-8007-1d1253a8f836.png)
![ryujinx_lrn2](https://user-images.githubusercontent.com/39680140/212621667-40bb310b-4cbd-499c-b900-a91e4c4d6518.png)
![ryujinx_lrn3](https://user-images.githubusercontent.com/39680140/212621696-f8e154ef-55b0-4398-87a8-531492169e87.png)
![ryujinx_lrn4](https://user-images.githubusercontent.com/39680140/212621721-ddea4d04-f937-42d3-9222-edfd4a1c2b5e.png)
![ryujinx_lrn5](https://user-images.githubusercontent.com/39680140/212621749-a594c0d2-0ff4-4bea-8c78-a8ef7ba2e041.png)
![ryujinx_lrn6](https://user-images.githubusercontent.com/39680140/212621768-ff0285ce-3a0c-42dc-b8b5-ba7d1f91f9bc.png)

Says "Error Submitting" when trying to "submit score" to leaderboards (w/guest access enabled):
![ryujinx_lrn7](https://user-images.githubusercontent.com/39680140/212621789-8d033e40-a246-482e-8393-6a2f5ab44e03.png)

Crashes when trying to access leaderboards (w/guest access enabled):
![ryujinx_lrn8](https://user-images.githubusercontent.com/39680140/212621951-6b24bbbb-2bed-4e7e-b242-cc527d73a298.png)

### Log File

Random crash after being killed and trying to return to main menu:
[Ryujinx_1.1.559_2023-01-15_14-40-18.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10423430/Ryujinx_1.1.559_2023-01-15_14-40-18.log)

Crash after trying to access leaderboards (the crash text itself isn't in the log):
[Ryujinx_1.1.559_2023-01-15_15-15-47.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10423435/Ryujinx_1.1.559_2023-01-15_15-15-47.log)

**Comment by F1ReB4LL** [comment]
Intro videos are NVDEC ones.

**Comment by F1ReB4LL** [comment]
Probably also needs an "online broken" flag (leaderboards issues)?
