### ISSUE TITLE
my pokemon violet started crashing when i try to start the game after i updated to 1.1.0

### ISSUE THREAD

**Issue by Semeviumentiu** [Ryujinx/Ryujinx-Games-List#4368]
### Game Name

Pokemon Violet

### Game Update Version

1.1.0

### Emulator Build Version

1.1.0-Idn3.0.1

### Graphics Backend

Vulkan

### Hardware Specs

- AMD Ryzen 5 2600 Six-Core Processor
- NVIDIA GeForce GTX 1070 Ti
- 8.00 GB RAM

### Game State

it's just crashes when i click to play

### Log File

00:00:00.048 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.054 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.054 |I| Configuration LogValueChange: MaxAnisotropy set to: 2
00:00:00.055 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.056 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.057 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.058 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1B82
00:00:00.067 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.0-ldn3.0.1
00:00:00.073 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.073 |N| Application Print: CPU: AMD Ryzen 5 2600 Six-Core Processor ; 12 logical
00:00:00.074 |N| Application Print: RAM: Total 8126 MiB ; Available 1407 MiB
00:00:00.075 |N| Application PrintSystemInfo: Logs Enabled: <None>
00:00:00.075 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.374 |N| Application LoadApplication: Using Firmware Version: 15.0.0
00:00:18.830 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce GTX 1070 Ti (Vulkan v1.3.224, Driver v528.2.0.0)
00:00:32.508 |N| HLE.GuestThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3460
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 38
   at Ryujinx.Cpu.Jit.JitExecutionContext.SupervisorCallHandler(ExecutionContext context, UInt64 address, Int32 imm) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 99
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx_staging\Ryujinx_staging\ARMeilleure\State\ExecutionContext.cs:line 145
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx_staging\Ryujinx_staging\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx_staging\Ryujinx_staging\ARMeilleure\Translation\Translator.cs:line 130
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx_staging\Ryujinx_staging\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()

**Comment by MutantAura** [comment]
Please join out Discord for support queries: https://discord.gg/ryujinx
