### ISSUE TITLE
Fire Emblem: Engage - 0100A6301214E000

### ISSUE THREAD

**Issue by Bjorn29512** [Ryujinx/Ryujinx-Games-List#4370]
### Game Name

Fire Emblem: Engage

### Game Update Version

1.0.0

### Emulator Build Version

1.1.574

### Graphics Backend

Vulkan

### Hardware Specs

- CPU: i5-12400f

- GPU: NVIDIA GTX 1660 Super

- RAM: 32GB

### Game State

- Works as intended on Vulkan and no discernible issues so far.
- Resolution scaler seems to be working inconsistently for some where only certain elements of the game will scale or not at all.

### Screenshots

![image](https://user-images.githubusercontent.com/110204265/213569094-5c5382f1-83ce-4449-9307-584aa9d2af8f.png)
![image](https://user-images.githubusercontent.com/110204265/213569213-9b0245a4-e0ab-4f9e-906a-12cb261fbd14.png)
![image](https://user-images.githubusercontent.com/110204265/213569527-8b52ff75-fb7d-44b6-8f56-0b1aa136cbdd.png)
![image](https://user-images.githubusercontent.com/110204265/213569768-50fea330-6e83-47b1-8487-4db068600ebe.png)
![image](https://user-images.githubusercontent.com/110204265/213570155-ae836ae2-d3f3-4261-8db4-93e7d6d5f4b8.png)
![image](https://user-images.githubusercontent.com/110204265/213570752-fd9ef588-3800-4e34-bf1d-b922738c3285.png)

**Comment by Foul-Tarnished** [comment]
The game is awfully aliased, even with resolution scaler
(It even looks more aliased at 3x or 4x than at 2x, weirdly. At least on my 1080p monitor)

I guess fixing this would need a game mod.
Post Processing PR doesn't really help here, at least not significantly, and does add some blurriness even with SMAA Ultra

**Comment by Bjorn29512** [comment]
i am on a 1080p monitor as well but dont share this issue, are you playing in windowed mode with scaling ?

**Comment by Bjorn29512** [comment]
> The game is awfully aliased, even with resolution scaler (It even looks more aliased at 3x or 4x than at 2x, weirdly. At least on my 1080p monitor)
> 
> I guess fixing this would need a game mod. Post Processing PR doesn't really help here, at least not significantly, and does add some blurriness even with SMAA Ultra
i am on a 1080p monitor as well but dont share this issue, are you playing in windowed mode with scaling ?

**Comment by Foul-Tarnished** [comment]
Fullscreen

x2
![image](https://user-images.githubusercontent.com/107711110/213592211-24ac0daf-2dd4-4ff2-9260-0914e3cb01ad.png)

or x3
![image](https://user-images.githubusercontent.com/107711110/213592248-154da5ec-db95-445e-9c77-01fc0a78de4e.png)

it looks pretty awful, but I guess it's just more visible than at real hw resolution

**Comment by Foul-Tarnished** [comment]
Fullscreen

x2
![image](https://user-images.githubusercontent.com/107711110/213592499-43c57987-eed9-40fa-a104-aaaa6a07eba3.png)

x3
![image](https://user-images.githubusercontent.com/107711110/213592529-748faccc-d4f0-4279-8dc3-09e6361caf9c.png)

it looks awful, but I guess it's just the game

**Comment by Bjorn29512** [comment]
For me the image is much cleaner and sharper when using scaling and it seems to be working as intended, it does seem like maybe the game uses its own AA which doesn't scale well or perhaps some elements on characters aren't being properly scaled but idk.

Native : 

![Ryujinx Nvidia Profile Screenshot 2023 01 20 - 06 08 03 86](https://user-images.githubusercontent.com/110204265/213594218-e0e156a8-e675-497f-a28f-b593642bbb85.png)
![Ryujinx Nvidia Profile Screenshot 2023 01 20 - 06 11 12 83](https://user-images.githubusercontent.com/110204265/213594236-bd9b2f40-ded9-4b5f-be1b-ab4af5a8b20a.png)

2x : 
![Ryujinx Nvidia Profile Screenshot 2023 01 20 - 06 08 16 95](https://user-images.githubusercontent.com/110204265/213594292-72624bc3-e400-4520-8fbd-e165b9261e13.png)
![Ryujinx Nvidia Profile Screenshot 2023 01 20 - 06 11 24 30](https://user-images.githubusercontent.com/110204265/213594300-b3abe8e7-e3df-4e5f-8a20-a11c40daac32.png)

**Comment by GamerzHell9137** [comment]
> For me the image is much cleaner and sharper when using scaling and it seems to be working as intended, it does seem like maybe the game uses its own AA which doesn't scale well or perhaps some elements on characters aren't being properly scaled but idk.
> 
> Native :
> 
> ![Ryujinx Nvidia Profile Screenshot 2023 01 20 - 06 08 03 86](https://user-images.githubusercontent.com/110204265/213594218-e0e156a8-e675-497f-a28f-b593642bbb85.png) ![Ryujinx Nvidia Profile Screenshot 2023 01 20 - 06 11 12 83](https://user-images.githubusercontent.com/110204265/213594236-bd9b2f40-ded9-4b5f-be1b-ab4af5a8b20a.png)
> 
> 2x : ![Ryujinx Nvidia Profile Screenshot 2023 01 20 - 06 08 16 95](https://user-images.githubusercontent.com/110204265/213594292-72624bc3-e400-4520-8fbd-e165b9261e13.png) ![Ryujinx Nvidia Profile Screenshot 2023 01 20 - 06 11 24 30](https://user-images.githubusercontent.com/110204265/213594300-b3abe8e7-e3df-4e5f-8a20-a11c40daac32.png)

Still looks aliased.

**Comment by PekaPete** [comment]
I tested this briefly on my Mac and it seems to work pretty well. A few things I did notice:
1. Some split second flickering/ rendering issue was seen. But it was so brief that I could not capture an image of it.
2. The upscaling seems to not work during closeups of characters talking. Could not tell a difference between 1X, 2X, 3X at all. During battle it feels like it works but not really? Marginal difference between 1X and 2X.
3. The upscaling seems to only clearly work during the free roaming section.

**Comment by yuwenhua653** [comment]
When using OpenGL in Mesa, there will be a texture error, and the character will randomly appear black head or body

**Comment by Sha-tan** [comment]
It crashes when walking around Soranel (the floating island). Is it just me or does it happen to you too?

**Comment by Bjorn29512** [comment]
updated

**Comment by Digitaln3ko** [comment]
Here is a cool thing, when using scaling, if you just loaded into the game, and into an exploring section, where you can walk around and talk top npc's etc, it'll be at the scaling resolution you set and look really nice, however, if you then go to the save menu and back out, the fxaa and dynamic scaler seem to kick back in into overdrive and completely ruin the image again, like it's no longer running at whatever you set it at.

**Comment by ChristopherCalderon** [comment]
> It crashes when walking around Soranel (the floating island). Is it just me or does it happen to you too?

Same here, so far I got 3 random crashes, 2 walking around and one at the start of a battle in chapter 2

**Comment by Bjorn29512** [comment]
> > It crashes when walking around Soranel (the floating island). Is it just me or does it happen to you too?
> 
> Same here, so far I got 3 random crashes, 2 walking around and one at the start of a battle in chapter 2

do you guys have AMD gpu a few ppl on discord reported crashes with amd gpu, i would recommend joining the discord and posting logs in support, if so i will make an update in the report for AMD

**Comment by ChristopherCalderon** [comment]
> > > It crashes when walking around Soranel (the floating island). Is it just me or does it happen to you too?
> > 
> > 
> > Same here, so far I got 3 random crashes, 2 walking around and one at the start of a battle in chapter 2
> 
> do you guys have AMD gpu a few ppl on discord reported crashes with amd gpu, i would recommend joining the discord and posting logs in support, if so i will make an update in the report for AMD

Im on nvidia gpu

**Comment by Bjorn29512** [comment]
> > > > It crashes when walking around Soranel (the floating island). Is it just me or does it happen to you too?
> > > 
> > > 
> > > Same here, so far I got 3 random crashes, 2 walking around and one at the start of a battle in chapter 2
> > 
> > 
> > do you guys have AMD gpu a few ppl on discord reported crashes with amd gpu, i would recommend joining the discord and posting logs in support, if so i will make an update in the report for AMD
> 
> Im on nvidia gpu

then post a log here or the discord when you crash.

**Comment by ChristopherCalderon** [comment]
> 
> then post a log here or the discord when you crash.

Sorry for taking a while, now that I was looking for a crash it didnt crash lol
But I got one again, walking around the somniel, I was able to play just fine the chapter before it crashed tho, so probly the problem is in the somniel 
[Ryujinx_1.1.578_2023-01-20_22-51-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10471539/Ryujinx_1.1.578_2023-01-20_22-51-49.log)

**Comment by Bjorn29512** [comment]
> > then post a log here or the discord when you crash.
> 
> Sorry for taking a while, now that I was looking for a crash it didnt crash lol But I got one again, walking around the somniel, I was able to play just fine the chapter before it crashed tho, so probly the problem is in the somniel [Ryujinx_1.1.578_2023-01-20_22-51-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10471539/Ryujinx_1.1.578_2023-01-20_22-51-49.log)

Need texture recompression enabled on GPU with less than 6GB vram to avoid crash there and love of hod update your drivers

**Comment by Bjorn29512** [comment]
Updated

**Comment by andyblarblar** [comment]
> > > It crashes when walking around Soranel (the floating island). Is it just me or does it happen to you too?
> > 
> > 
> > Same here, so far I got 3 random crashes, 2 walking around and one at the start of a battle in chapter 2
> 
> do you guys have AMD gpu a few ppl on discord reported crashes with amd gpu, i would recommend joining the discord and posting logs in support, if so i will make an update in the report for AMD

Looking at the discord it seems that the AMD crashes occur when entering and leaving loading areas and cutscenes with resolution scaled above native. I can conferm this is very consistent for me.

All the logs end with a pattern of :
```
00:01:12.791 |S| HLE.OsThread.20 ServicePctl IsFreeCommunicationAvailable: Stubbed. 
00:01:21.162 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:22.162 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 5326 took more than 1000ms, resuming execution...
00:01:33.881 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 230447 bytes, profiled functions: 66456).
00:01:41.560 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:42.561 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 7587 took more than 1000ms, resuming execution... 
```
Before ending, if this means anything to anyone.

**Comment by Bjorn29512** [comment]
Updated again with AMD bug

**Comment by andyblarblar** [comment]
> Updated again with AMD bug

Tested the AMD issue on linux with mesa and the game runs fine (outside of the normal AA issues), so it does seem like the windows drivers are the cause of the crashes (suprise there).

**Comment by massiveinvisible** [comment]
Issue running on Steam Deck with latest Ryujinx version in Vulkan. When running around the open areas, objects seem to pop in and out, even relatively close ones. This doesn't happen with OpenGL. Can’t replicate this on Windows.

**Comment by andyblarblar** [comment]
> Issue running on Steam Deck with latest Ryujinx version in Vulkan. When running around the open areas, objects seem to pop in and out, even relatively close ones. This doesn't happen with OpenGL. Can’t replicate this on Windows.

I can replicate this issue with an AMD GPU on desktop ubuntu as well.

**Comment by Bjorn29512** [comment]
Updated (Issue Fixed)

**Comment by michael-stubbs** [comment]
Screen tearing present during motion. Running Vulcan with VSync on. Usually just on the top quarter of the screen, nothing unplayable.  i9/3090TI

**Comment by Zheyres** [comment]
I have a lot of crashes with Vulkan on Ryujinx 1.1.595. I switched to OpenGL and now it's not crashing but I have a little more stuttering + the cutscenes freeze (only video audio is fine). I got some serious visual bugs on Vulkan like when you have old drivers (magenta textures, artifacting) but not on OpenGL mode. 
My Specs:
 Operating System: Windows 10 Pro 64-bit (10.0, Build 19044)
Processor: Intel(R) Pentium(R) CPU G4560 @ 3.50GHz (4 CPUs), ~3.5GHz
Available OS Memory: 8142MB RAM
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 950
Display Memory: 6078 MB
    Dedicated Memory: 2007 MB
       Shared Memory: 4070 MB
Current Mode: 1152 x 864 (32 bit) (75Hz)

**Comment by Bjorn29512** [comment]
> 

switch back to vulkan and enable texture re compression to avoid crashes, its likely crashing cause you run out of memory as the game needs 6gb + vram since the game uses ASTC

**Comment by ayurai** [comment]
Just some vertex explosions.
https://user-images.githubusercontent.com/20160968/216585295-41a34367-d73e-4395-823b-87dc690a1e7a.mp4

**Comment by kuroganashi** [comment]
> > 
> 
> switch back to vulkan and enable texture re compression to avoid crashes, its likely crashing cause you run out of memory as the game needs 6gb + vram since the game uses ASTC

still crashes here and there :(

Windows 10 Home 64-bit (10.0 Build 19045.2486)
AMD Ryzen 5 3600 6-Core Processor                 3.95 GHz
AMD RX 550/50 4000 VRAM,
Direct X 12
16GB RAM

![image](https://user-images.githubusercontent.com/4380256/216627200-9e33d367-a728-4773-87cc-4c5ef0bae25d.png)

![image](https://user-images.githubusercontent.com/4380256/216627334-b1ca8117-ed2e-4c49-8f74-ca6c0a647128.png)

**Comment by Bjorn29512** [comment]
> > > 
> > 
> > 
> > switch back to vulkan and enable texture re compression to avoid crashes, its likely crashing cause you run out of memory as the game needs 6gb + vram since the game uses ASTC
> 
> still crashes here and there :(
> 
> Windows 10 Home 64-bit (10.0 Build 19045.2486) AMD Ryzen 5 3600 6-Core Processor 3.95 GHz AMD RX 550/50 4000 VRAM, Direct X 12 16GB RAM
> 
> ![image](https://user-images.githubusercontent.com/4380256/216627200-9e33d367-a728-4773-87cc-4c5ef0bae25d.png)
> 
> ![image](https://user-images.githubusercontent.com/4380256/216627334-b1ca8117-ed2e-4c49-8f74-ca6c0a647128.png)

hmm it shouldn't if you have texture re compression and not using scaling for amd, might wanna post a log for this one either here or the discord server.

**Comment by pinguallyj** [comment]
The game crashes on MacOS, M2, Vulcan when you disable V-Sync. Works fine with V-Sync. Tried switching different options, but it didn't work. Ryujinx 1.1.0

**Comment by ayurai** [comment]
[Ryujinx_1.1.616_2023-02-11_02-00-50.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10712727/Ryujinx_1.1.616_2023-02-11_02-00-50.log)
ErrorDeviceLost /\ Dont think anyone has reported that.

**Comment by Bjorn29512** [comment]
> [Ryujinx_1.1.616_2023-02-11_02-00-50.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10712727/Ryujinx_1.1.616_2023-02-11_02-00-50.log) ErrorDeviceLost /\ Dont think anyone has reported that.

How to reproduce ?

**Comment by Radinax** [comment]
> 03:27:02.460 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 315
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 202
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\Window.cs:line 269
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 115
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 400

I just got this error.

The first one I got three days ago was the VRAM out of memory stuff but it fixed with Texture Recompression, but now I got this one in one crash, will report back to see if it happens again.

It happened when I tried entering a battle on the first map when you get Timerra.

**Comment by Bjorn29512** [comment]
> > 03:27:02.460 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
> > at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 315    at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 202    at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\Window.cs:line 269    at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
> > at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
> > at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 115
> > at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 400
> 
> I just got this error.
> 
> The first one I got three days ago was the VRAM out of memory stuff but it fixed with Texture Recompression, but now I got this one in one crash, will report back to see if it happens again.
> 
> It happened when I tried entering a battle on the first map when you get Timerra.

Is that dlc content?

**Comment by Shiea** [comment]
I had that same thing happen, was indeed during the new dlc quest, froze then crashed during the first second of a battle, about five mins into the new dlc.

```
00:26:27.978 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 315
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 202
   at Ryujinx.Graphics.GAL.Multithreading.Commands.SetRenderTargetsCommand.Run(SetRenderTargetsCommand& command, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\Commands\SetRenderTargetsCommand.cs:line 21
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 115
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 400
```

**Comment by Bjorn29512** [comment]
Updated, AMD issue fixed and new device lost error introduced with dlc and update.

**Comment by BilmondNight** [comment]
[Ryujinx_1.1.650_2023-03-08_14-39-50.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10917650/Ryujinx_1.1.650_2023-03-08_14-39-50.log)

I also have the random crash issue. I uploaded the most recent crash log as above.
Windows 11
Intel i9-12900H 2.9GHz
16GB RAM
Nvidia GTX 3060
Ryujinx Ver. 1.1.650

**Comment by nightulp** [comment]
Game run well with wierd random crash. When in battle it rarely happen to crash but when in Somniel it happen many time when idle or goes around for long time.
all version of Ryujinx always has this issue to me
Windows 11  
Ryzen 5 3600
16GB ram
Nvidia GT1030

**Comment by Bjorn29512** [comment]
> Game run well with wierd random crash. When in battle it rarely happen to crash but when in Somniel it happen many time when idle or goes around for long time. all version of Ryujinx always has this issue to me Windows 11 Ryzen 5 3600 16GB ram Nvidia GT1030

This sound very much like an out of memory crash, try enabling texture recompression in settings

**Comment by nightulp** [comment]
> > Game run well with wierd random crash. When in battle it rarely happen to crash but when in Somniel it happen many time when idle or goes around for long time. all version of Ryujinx always has this issue to me Windows 11 Ryzen 5 3600 16GB ram Nvidia GT1030
> 
> This sound very much like an out of memory crash, try enabling texture recompression in settings

I enabled it. Yes, this does improve from disabled, but it does not solve. 
Oh and another weird thing is it only happen when I first open Ryujinx will always crash like this but if I reopen it again it rarely or not crashes. This happens everyday repeat.

**Comment by Bjorn29512** [comment]
> > > Game run well with wierd random crash. When in battle it rarely happen to crash but when in Somniel it happen many time when idle or goes around for long time. all version of Ryujinx always has this issue to me Windows 11 Ryzen 5 3600 16GB ram Nvidia GT1030
> > 
> > 
> > This sound very much like an out of memory crash, try enabling texture recompression in settings
> 
> I enabled it. Yes, this does improve from disabled, but it does not solve. Oh and another weird thing is it only happen when I first open Ryujinx will always crash like this but if I reopen it again it rarely or not crashes. This happens everyday repeat.

GT 1030 has pathetic amount of vram even with texture re-compression it wont be able to reduce vram usage enough for that gpu so you will still get crash, what you can do instead is enable texture re-compression and switch to opengl, as far as the other launch crash is concerned you should post a log for that in ryujinx discord support channel.

**Comment by yutijang** [comment]
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/5685320/7a3e9d3a-ee7b-4889-87e6-8fdcc0bbace4)

I had got this dialog then crash and exit Ryujinx
Video backend: Vulkan
FEE version: 2.0.0

**Comment by DiamondBr3aker** [comment]
The game runs fine, however cutscenes stutter with V-Sync on and character dialogue boxes slowly render with V-Sync off.
Windows 11 Pro
Intel i5-13400F
16GB RAM
Nvidia GTX 3060
Ryujinx Ver. 1.1.1217

**Comment by neverused776** [comment]
There is a possible Intel GPU bug. The game crashes almost every time a 3D portrait is rendered next to the dialogue box. When this happens the entire emulator crashes and my screen goes dark for about 10 seconds. I could not find any settings that fixed this. As is, the game is **unplayable**, and will crash in the first map at the first dialogue box. I attached my save file, ignore the real saves they are from my Switch, take the autosave and it crashes almost immediately for me.
Windows 11
Intel Core Ultra 7
16GB RAM
Intel Arc
Ryujinx version 1.1.1384
[Engage Save.zip](https://github.com/user-attachments/files/16830824/Engage.Save.zip)
