### ISSUE TITLE
Metroid Prime Remastered - 010012101468C000

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx-Games-List#4411]
### Game Name

Metroid Prime Remastered

### Game Update Version

v1.0.0

### Emulator Build Version

1.1.609

### Graphics Backend

Vulkan

### Hardware Specs

- #### CPU: *Ryzen 3600*
- #### GPU: *NVIDIA RTX 3060 Ti*
- #### RAM: *16GB*

### Game State

The character, enemies and some environments have wrong lighting.
Game crashes down the line with the error:

```
00:15:16.784 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Pixld is not implemented.
00:15:16.834 |E| GPU.MainThread Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Spv.Generator.Instruction.Write(BinaryWriter writer) in D:\a\Ryujinx\Ryujinx\Spv.Generator\Instruction.cs:line 114
   at Spv.Generator.Module.Generate() in D:\a\Ryujinx\Ryujinx\Spv.Generator\Module.cs:line 363
   at Ryujinx.Graphics.Shader.CodeGen.Spirv.SpirvGenerator.Generate(StructuredProgramInfo info, ShaderConfig config) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\CodeGen\Spirv\SpirvGenerator.cs:line 137
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(FunctionCode[] functions, ShaderConfig config) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 34
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateShader(ShaderDumper dumper, GpuChannel channel, TranslatorContext context, Byte[] code) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 648
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 1276
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount, Int32 drawFirstVertex, Int32 drawVertexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 120
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 argument) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 107
   at Macro(MacroJitContext, IDeviceState, Int32)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 207
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__75_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 402
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass51_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 107
   at System.Threading.Thread.StartCallback()
```

### Screenshots

![image](https://user-images.githubusercontent.com/2002038/217689120-3e856f1b-4d06-403f-bb09-1ebc24b6c4b6.png)

![image](https://user-images.githubusercontent.com/2002038/217688503-19aac531-2a2b-4fff-9d4c-5877c8b8d425.png)

![image](https://user-images.githubusercontent.com/2002038/217690295-4879fe81-4123-4c37-b4be-c7449b2198b0.png)

**Comment by AbbieDoobie** [comment]
OpenGL seems to fix the crashing issues. Lighting issues occur on both backends.

**Comment by Superbroom** [comment]
I am seeing the same issues with this. OpenGL fixes the crashing, but I only have "lighting" issues on OpenGL. With Vulkan I am able to see shields, scan icons, etc.

**Comment by Sev73n** [comment]
same issus

**Comment by Bjorn29512** [comment]
> OpenGL seems to fix the crashing issues. Lighting issues occur on both backends.
outdated, latest ryu fixes crashes on vulkan.

**Comment by lbdevprv** [comment]
Broken on m1 Macbook air 128gb 8gb (my school laptop) crashes soon after shooting for the first time.

**Comment by NineKain** [comment]
Same issue here, Vulkan

**Comment by tracygoo** [comment]
when this issue will be fixed on MAC?

**Comment by GamerzHell9137** [comment]
> when this issue will be fixed on MAC?

Someday

**Comment by cazlin** [comment]
I have the same lighting issues  as well on both back ends. 
5800X 
RTX 3080 (driver v528.24)
build v1.1.614-win_x64

**Comment by LexBoosT** [comment]
Solution here, test with this PR
https://github.com/Ryujinx/Ryujinx/pull/4394

**Comment by MetrosexualGarbodor** [comment]
Needs an update. Lighting and Vulkan crashes are fixed, but there are reports of other smaller issues:
- Samus doesn't have a shadow on Vulkan. Has a shadow on OpenGL, but the ground texture is rendered wrongly.
![image](https://user-images.githubusercontent.com/79612681/218139719-b4220a05-40ab-4b37-8821-a7e52790e26f.png)
- There's some stuttering when going through doors and on the intro. The cause for this is known and will be looked into.

**Comment by GamerzHell9137** [comment]
Updated

**Comment by xxe1** [comment]
keeps crashing for me when loading a new room. emu just closes itself.

**Comment by Grammernatzi** [comment]
Specific pieces of ice flickering in Phendrana Drifts Depths. Minor issue, but figured it's worth pointing out.

https://cdn.discordapp.com/attachments/811402989046333440/1073849099654275142/Ryujinx_Nvidia_Profile_2023.02.10_-_22.12.16.01.mp4

Running on an RTX 2060 Mobile, default graphics settings (at 2x docked), Ryujinx 1.1.616

**Comment by zamxavib** [comment]
Is anybody else having framerate drops in some rooms at Magmoor Caverns? Specially while shooting, and shooting lava makes it even worse apparently

**Comment by WildChild-SomethingWild** [comment]
See screenshots below.

The macOS arm port having black textures and abnormal textures seen in different area, Samus suit is always entirely black.
On shooting, the game crash the Ryujinx app.
![SCR-20230212-k97](https://user-images.githubusercontent.com/83997024/218333073-aea4a13a-f71b-46e8-9ab1-60f5b44c9f06.jpeg)
![SCR-20230212-k9c](https://user-images.githubusercontent.com/83997024/218333079-89e245bc-55c8-4b10-9077-8f138a5495f3.jpeg)
![SCR-20230212-jv3](https://user-images.githubusercontent.com/83997024/218333094-cf854748-775b-4bf7-afc4-5de5a82a305d.jpeg)
![SCR-20230212-jvq](https://user-images.githubusercontent.com/83997024/218333100-47179cee-27e1-4f9d-b7d5-2297802c712c.jpeg)

**Comment by LegendarySavageGamer** [comment]
i have a i9 10900k 10th Gen , Nvidia GeForce 1660 Super OC 
![Desktop Screenshot 2023 02 15 - 10 25 29 98](https://user-images.githubusercontent.com/125479883/219072874-cca406f4-d9f4-4cfd-9c57-2ad08228cd2b.png)
The only issues I'm noticing that I'm having is my Frame Drop's a lot when i shoot the doors to load in next room and it stutters some enemies cause it to stutter also but what i notice alot is from when i load my save when the save room loads in Samus an Scans her my FPS goes from 60FPS - 1FPS..

**Comment by njmdietrich** [comment]
I am on an RX 7900 XT. The game crashes on those exploding enemies on the ceiling in the room that you reach from your ship in Tallon Overworld by going up behind the waterfall. The last log message is about shader instruction Pixld not being implemented.

**Comment by thejokoono** [comment]
1.1.625 - MacOS with M1 Pro: 

With and w/o Hypervisor: Crashes immediately after intro sequence.

<img width="1191" alt="Bildschirm­foto 2023-02-19 um 16 42 05" src="https://user-images.githubusercontent.com/90209865/219958581-7808218b-7ece-462a-b1b2-9d5789be5ab4.png">

**Comment by knives-repo** [comment]
> See screenshots below.
> 
> The macOS arm port having black textures and abnormal textures seen in different area, Samus suit is always entirely black. On shooting, the game crash the Ryujinx app. ![SCR-20230212-k97](https://user-images.githubusercontent.com/83997024/218333073-aea4a13a-f71b-46e8-9ab1-60f5b44c9f06.jpeg) ![SCR-20230212-k9c](https://user-images.githubusercontent.com/83997024/218333079-89e245bc-55c8-4b10-9077-8f138a5495f3.jpeg) ![SCR-20230212-jv3](https://user-images.githubusercontent.com/83997024/218333094-cf854748-775b-4bf7-afc4-5de5a82a305d.jpeg) ![SCR-20230212-jvq](https://user-images.githubusercontent.com/83997024/218333100-47179cee-27e1-4f9d-b7d5-2297802c712c.jpeg)

I'm having this exact same issue on Mac Monterey 12.6.3

**Comment by LandonGorton** [comment]
https://user-images.githubusercontent.com/123523356/220413949-3af774b2-639a-4b67-966c-80e16ac39dd9.mp4

Build: ryujinx-1.1.630-win_x64
Backend: Vulkan
CPU: i5 13600k
GPU: Nvidia 3060

Persistent crash going into this room in Magmoor Caverns. Have tried entering the room from Monitor Station as well as the Tallon Overworld West Transport room, both yield crashes.

Log File: 
[Ryujinx_1.1.630_2023-02-21_11-11-51.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10795966/Ryujinx_1.1.630_2023-02-21_11-11-51.log)

**Comment by MetrosexualGarbodor** [comment]
@LandonGorton your game file is corrupt, dump it again

**Comment by LandonGorton** [comment]
> @LandonGorton your game file is corrupt, dump it again

just took a look at the log after posting and saw the hash error. doh.

**Comment by Sommerwiesel** [comment]
Build: ryujinx-1.1.644-flatpak on manjaro-linux
Backend: Vulkan (2x Scaling)
CPU: AMD Ryzen 7 5800X
GPU: AMD Radeon RX 6700 XT
Firmware: 15.0.1

Game is on PCIE 4.0 NVME SSD

The beam switch animation is glitched.
The rest of the game (except for missing shadows) works great.

I cannot upload a photo to github due to some bug in githubs javascript so I'll just post a link to the screenshot here:

[![Screenshot-20230227-172537.png](https://i.postimg.cc/DwQXYTfP/Screenshot-20230227-172537.png)](https://postimg.cc/LJX5nG1J)

**Comment by nsklaus** [comment]
small tip for mac users out there who are desperate to play metroid prime remaster such as myself.
the original macos1 build from november crashes so often with this game, that it is not usable. as far as i can tell from the logs, it's an array out of bounds error. but all is not lost .. recent builds of ryujinx can play this title just fine if you modify 1 line, to disable TransformFeedback. then metroid prime runs, admitedly with minor glitches here and there..

edit `Ryujinx/Ryujinx.Graphics.Vulkan/PipelineBase.cs:177` change the `true` to `false` like so: 
```
        public void BeginTransformFeedback(GAL.PrimitiveTopology topology)
        {
            _tfEnabled = false;
        }
```

original macos1 build from november had transformfeedback support/workaround but game wasn't playable because of the crash mentionned above. and current source tree hasn't brought in the transformfeedback support from macos1 build yet. but with that small change, you can enjoy testing metroid prime a bit further than with macos1 build.

**Comment by WildChild-SomethingWild** [comment]
> small tip for mac users out there who are desperate to play metroid prime remaster such as myself. the original macos1 build from november crashes so often with this game, that it is not usable. as far as i can tell from the logs, it's an array out of bounds error. but all is not lost .. recent builds of ryujinx can play this title just fine if you modify 1 line, to disable TransformFeedback. then metroid prime runs, admitedly with minor graphical glitches here and there..
> 
> edit `Ryujinx/Ryujinx.Graphics.Vulkan/PipelineBase.cs:177` change the `true` to `false` like so:
> 
> ```
>         public void BeginTransformFeedback(GAL.PrimitiveTopology topology)
>         {
>             _tfEnabled = false;
>         }
> ```
> 
> original macos1 build from november had transformfeedback support/workaround but game wasn't playable because of the crash mentionned above. and current source tree hasn't brought in the transformfeedback support from macos1 build yet. but with that small change, you can enjoy testing metroid prime a bit further than with macos1 build.

Where do we need to go to be able to add the change ?
Thanks

**Comment by nsklaus** [comment]
you clone the ryujinx repo, 
then in the source file here: ` Ryujinx/Ryujinx.Graphics.Vulkan/PipelineBase.cs:177 `  you change the true to false, save file,
then you recompile using: 
```
./distribution/macos/create_macos_release.sh . ../temp/ ../output/ distribution/macos/entitlements.xml 1.1.1 1.5
```

then play :)

**Comment by WildChild-SomethingWild** [comment]
> you clone the ryujinx repo, then in the source file here: `Ryujinx/Ryujinx.Graphics.Vulkan/PipelineBase.cs:177` you change the true to false, save file, then you recompile using: (you need to have installed the [dotnet sdk](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) )
> 
> ```
> ./distribution/macos/create_macos_release.sh . ../temp/ ../output/ distribution/macos/entitlements.xml 1.1.1 1.5
> ```
> 
> the newly created app bundle will be located in `output` directory, next to where you cloned the repo. then play :) works for me, but i have to mention i have also imported a few PR too (some have been commited since then, and some have not yet)
> 
> ```
> klaus@NsMac Ryujinx % git branch
> * master
>   pr4368
>   pr4404
>   pr4406
>   pr4408
>   pr4471
> klaus@NsMac Ryujinx %
> ```

I have made the changes to the line 177 and installed dotnet SDK, now how do I compile for macOS ? 😅

**Comment by nsklaus** [comment]
i gave you the entire line to use to be able to compile it

**Comment by WildChild-SomethingWild** [comment]
> i gave you the entire line to use to be able to compile it

That's what I got when doing so: 
<img width="807" alt="Capture d’écran, le 2023-03-05 à 14 56 30" src="https://user-images.githubusercontent.com/83997024/222982737-c67d1693-c59e-4ef3-b929-f931d8f888c3.png">

**Comment by nsklaus** [comment]
type `pwd` then paste the output here,
i'll help you, then when we will have finished, we'll remove a few of our posts to avoid spamming here ok ?

**Comment by WildChild-SomethingWild** [comment]
The output is: /Users/Dan

**Comment by nsklaus** [comment]
then type: `cd <input the path where you cloned the ryujinx repo, without those greater/smaller than symbols>`

**Comment by WildChild-SomethingWild** [comment]
> then type: `cd <input the path where you cloned the ryujinx repo, without those greater/smaller than symbols>`

It's compiling, now I'm seeing a folder called ''output'' creating himself in the desired location

**Comment by nsklaus** [comment]
yes, wait for compile to properly finish and you should have your newly made ryujinx app bundle

**Comment by nsklaus** [comment]
also note that the ryujinx config directory has changed since "macos1" build from novemeber, it is no longer `~/.config/ryujinx/`  now it's `~/Library/Application\ Support/Ryujinx`  (the ~  means `/Users/Dan/`   your "home" dir)

**Comment by nsklaus** [comment]
all done ? we remove all our posts now ok ? 
we should have used discord instead, let's delete all the posts, and if you still have issues, you can see me on the discord, i'll help if i can.

**Comment by WildChild-SomethingWild** [comment]
> 

Everything i s done and compiled, I then copy the new Ryujinx app into my apps folder. The game launch fine and seems to work but right after the opening message ''talon orbit something'' (before the opening cinematic) the newly created app crashes..

**Comment by illadelph1** [comment]
@nsklaus how would i go about editing this code?

**Comment by sykoe** [comment]
Got several of these errors when loading the game (shaders) 

```
00:01:05.834 |W| GPU.AsyncTranslationThread.2 Gpu Log: Shader translator: Shader instruction Pixld is not implemented.
00:01:05.835 |W| GUI.RenderLoop Gpu CheckProgramLink: Shader linking failed:
Vertex info
-----------
0(646) : error C1021: operands to ">>" must be integral
0(659) : error C1021: operands to ">>" must be integral
0(688) : error C1021: operands to ">>" must be integral
0(699) : error C1021: operands to ">>" must be integral

```

**Comment by MetrosexualGarbodor** [comment]
Needs an update, stuttering when going through doors should be fixed.

**Comment by Bjorn29512** [comment]
> Needs an update, stuttering when going through doors should be fixed.

Not entirely no, there will still be astc decoding related stutter but the amt has been significantly reduced on initial load now

**Comment by TathagataDM** [comment]
There also seems to be an audio delay that increases in size the longer you play, perhaps it's due to the small delay when opening doors. It's most noticeable with any sound effect, as there's a second or two delay with about an hour of playtime.

**Comment by Galandil74** [comment]
> I am on an RX 7900 XT. The game crashes on those exploding enemies on the ceiling in the room that you reach from your ship in Tallon Overworld by going up behind the waterfall. The last log message is about shader instruction Pixld not being implemented.
> 
> EDIT: It appears the crash only occurs if you attempt to scan the enemies, otherwise it is fine.
> 
> EDIT2: Shooting them also triggers the crash.

I confirm this same exact bug. After a couple of tests, I noticed that the CTD happens only when the enemies fire and the exploding effect starts, it's not related to scanning them or shooting them, they have to open fire.

My rig:
CPU AMD 5600X
GPU AMD 7900XTX
32GB RAM
Adrenalin drivers v23.4.1

The bug happens on:
RyuJinx version 1.1.700 & 1.1.708
Firmware version 15.0.1 & 16.0.0

**Comment by njmdietrich** [comment]
@Galandil74 Well done for your thorough debugging. I'm guessing it must be an issue with RDNA3 cards. Interestingly, yuzu had the same crash at one point, but it is working there on the most recent version.

**Comment by Galandil74** [comment]
> @Galandil74 Well done for your thorough debugging. I'm guessing it must be an issue with RDNA3 cards. Interestingly, yuzu had the same crash at one point, but it is working there on the most recent version.

No problem at all.

Also, I forgot to add that, as you noticed in the log, this happens with the Vulkan API.
With the OpenGL API, it doesn't happen, but with OpenGL there're a lot of constant flickering textures basically everywhere.

**Comment by NitroTears** [comment]
On Ryujinx 1.1.763, Firmware 16.0.2, No Upscale/Mods/Cheats
GPU: Radeon RX 6700 XT (23.4.2) - CPU: Ryzen 7 5700X

This is a bit of a long one.

### Both Vulkan/OpenGL
- I found that the suttering issue when going through doors still does occur. 
- There is a near constant spam of `IsSixAxisSensorAtRest` stubs going off at all times. (even when not using motion control options in game)

![Screenshot 2023-05-07 084205](https://user-images.githubusercontent.com/73270647/236649244-692885a9-14ca-4504-ba26-25bcc6cae1d3.png)

- I can't pin down the exact reason but as you keep on playing the game you will occasionally get the following warning. You can trigger a few of these in a row by viewing models in the character gallery.
`|W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Pixld is not implemented.`
- When in main menu / gallery, the menu transitions occasionally trigger this error, though nothing appears to happen in game
`|E| Ryujinx.NvdecProcessor FFmpeg Log: [h264 @ 0000037dd32f2b80] co located POCs unavailable`

- I could not replicate any issue regarding the exploding seedling enemies, scanning, letting them attack/explode ect. Here is a snippet of me interacting with them.

https://user-images.githubusercontent.com/73270647/236648900-d5c8d004-d464-4c32-8566-20e1e2123724.mp4

### OpenGL Specific
There are very large amounts of buggy textures / texture flickering in various areas in the game, here are some examples:
![ryujinx_capture_2023-05-07_08-17-25](https://user-images.githubusercontent.com/73270647/236649508-582e5eef-87fc-4922-938c-19ce687fc884.png)
![ryujinx_capture_2023-05-07_08-16-56](https://user-images.githubusercontent.com/73270647/236649523-5c612102-3e56-459c-9ca0-20bbe340fe3b.png)

https://user-images.githubusercontent.com/73270647/236649480-68b95fa8-4615-44ef-b59f-f83f214030f2.mp4

If there is anything else specific you want tested with AMD stuff, let me know

**Comment by pp6taez74** [comment]
Experiencing a few issues on macOS:

Ryujinx 1.1.942, Firmware 16.0.3, No Upscale/Mods/Cheats
GPU & CPU: Apple M2 Pro

1. Intermittent "black textures" on Samus as described above, along with white/multicoloured textures on other stuff and  flickering multicoloured lights

https://github.com/Ryujinx/Ryujinx-Games-List/assets/138143820/1c74a152-3073-4729-9466-12b66becfa1a

2. Fps drops dramatically (from 60fps to 10-15fps) when opening and closing the map 


https://github.com/Ryujinx/Ryujinx-Games-List/assets/138143820/e8fbe8b7-69c6-4d24-8e25-b687d796057c

**Comment by jeanravin** [comment]
Ryujinx 1.1.1090 - firmware 17.0.0 - macOS 14.1.1 - M1 max (mac studio 22)

In Phazon mines the new pirates (the ones that have your technology) have no textures (black). Also Samu's weapon have no light inside.

![ryujinx_capture_2023-11-19_13-53-16](https://github.com/Ryujinx/Ryujinx-Games-List/assets/1174299/10530d4a-c9d9-4a97-a955-4ee858fffb4f)

**Comment by drpeppercherry** [comment]
> Ryujinx 1.1.1090 - firmware 17.0.0 - macOS 14.1.1 - M1 max (mac studio 22)
> 
> In Phazon mines the new pirates (the ones that have your technology) have no textures (black). Also Samu's weapon have no light inside (in all the game).
> 
> ![ryujinx_capture_2023-11-19_13-53-16](https://user-images.githubusercontent.com/1174299/284058764-10530d4a-c9d9-4a97-a955-4ee858fffb4f.png)
> 
> When loading the game the weapon light shows, though. But not when going 1st person.
> 
> ![ryujinx_capture_2023-11-19_13-49-38](https://user-images.githubusercontent.com/1174299/284059733-eb17c49e-2b7f-4c0b-affa-fec4b642bb17.png)

Same. Ryujinx 1.1092, Firmware 17.0.0, M2 Macbook Air 15 inch, MacOS Sonoma 14.1.1

I don't even get the textures on the arm cannon in cutscenes. Charging animations will show, but not the pulsing light inside. Coloured space pirates just show as black, and Chozo ghosts in X-ray vision mode do not show at all. Metroid Prime boss also does not show any colours, so literally can't beat it.

**Comment by JouBqa** [comment]
So does this game work?

**Comment by cannondale0815** [comment]
> i haven't tested using vulkan renderer yet.

Only works using OpenGL for me
