### ISSUE TITLE
DragonBlaze for Nintendo Switch

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#442]
#### Current on `master` : 1.0.4047

Crashes on launch with the below error.
NOTE: This error does not show up in the logfile; it only shows up in the console. I copied the console output to the attached log.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(System.Object, ARMeilleure.State.InstUndefinedEventArgs)
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64, Int32)
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64, Int32)
   at ARMeilleure.Translation.TranslatedFunction.Execute(ARMeilleure.State.ExecutionContext)
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass129_0.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[DragonBlaze.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4394344/DragonBlaze.zip)

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by EmulationFanatic** [comment]
Updated
