### ISSUE TITLE
Octopath Traveller II - 0100A3501946E000

### ISSUE THREAD

**Issue by taufik-ridwan** [Ryujinx/Ryujinx-Games-List#4465]
### Game Name

Octopath Traveller II

### Game Update Version

1.0.2

### Emulator Build Version

1.1.637

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *AMD Ryzen 5-5600G*
- ##### GPU: *AMD Radeon RX 6600, using RADV on mesa 22.3.6*
- ##### RAM: *2x8GB*
- ##### OS: *Linux 6.1.12-zen1-1-zen*

### Game State

Game is playable at full speed without any game-breaking issues at the moment.  

### Screenshots

Screenshots:
![octopops1](https://user-images.githubusercontent.com/75967358/221203874-bfe0c2a5-8522-4c1b-963e-e9eaab6dfd02.png)
![octopops2](https://user-images.githubusercontent.com/75967358/221203931-6276f55d-5f51-4588-bd08-68a4fc27f328.png)

Exploring:

https://user-images.githubusercontent.com/75967358/221206969-80792a7f-6da8-4f1c-8b5a-ee5fb697598b.mp4

Combat:

https://user-images.githubusercontent.com/75967358/221207615-96a4d0e7-1bb1-4d22-91f0-03757f6ebbfb.mp4

**Comment by dmjohn0x** [comment]
Not working for me. Vulkan result in the game crashing on boot, OpenGL loads fine uptil you start a new game, then looks like absolute nonsense. Im also on the latest update (1.1.637). PC is Ryzen 2600X w AMD 5700XT GPU and 32gb DDR4-3200. On Windows 11, if that matters.

![image](https://user-images.githubusercontent.com/15333851/221281027-1ff6b4dc-b702-48fe-a38f-610109ce5a10.png)


![image](https://user-images.githubusercontent.com/15333851/221279747-634459b3-8d22-41cc-bb06-a4ce397e9674.png)

**Comment by dmjohn0x** [comment]
Wanted to update. But wanted to play a bit to make sure there was no more crashing... 
I was able to play clear through the first chapter of Throne' with only a few hitches for cache'ing. Game seems playable so far.

I got Vulkan to run the game fine using the following settings:
![image](https://user-images.githubusercontent.com/15333851/221313329-8d966d0b-61b0-431b-864b-4c5b1529f3d0.png)
![image](https://user-images.githubusercontent.com/15333851/221313441-47fa3955-c926-44b0-b681-da6cec81fe8b.png)
![image](https://user-images.githubusercontent.com/15333851/221313062-28b71e6c-6168-4894-a504-db70a6668360.png)

**Comment by GamerzHell9137** [comment]
> Wanted to update. But wanted to play a bit to make sure there was no more crashing... I was able to play clear through the first chapter of Throne' with only a few hitches for cache'ing. Game seems playable so far.
> 
> I got Vulkan to run the game fine using the following settings: ![image](https://user-images.githubusercontent.com/15333851/221313329-8d966d0b-61b0-431b-864b-4c5b1529f3d0.png) ![image](https://user-images.githubusercontent.com/15333851/221313441-47fa3955-c926-44b0-b681-da6cec81fe8b.png) ![image](https://user-images.githubusercontent.com/15333851/221313062-28b71e6c-6168-4894-a504-db70a6668360.png)

Why are you using alternative memory layout? If anything that should never be enabled. Also if there's no need for ignoring services then disable that one too. And only use texture recompression is necessary, that is if you don't have enough VRAM. If you're GPU is 8 GB then there's no need for it.

**Comment by Vinicius881** [comment]
Hey bro, only crash here

**Comment by vesper8** [comment]
Playing on Mac, using both the stable release as well as the latest build. Works great for the most part but getting a lot of random crashes. Here's a log of the latest crash.

```

00:36:24.193 |I| HLE.GuestThread.21 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Majesty, PID: 93
   0x0000000008be691c	main:0xbe291c	
   0x0000000011b76ee8	sdk:0x341ee8	
   0x0000000011b7d474	sdk:0x348474	
   0x0000000000000000


00:36:24.195 |I| HLE.GuestThread.21 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000001800aa4900
	X[01]:	0x00000000fffffffe
	X[02]:	0x0000000000000000
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000003
	X[09]:	0x00000000e0000002
	X[10]:	0x0000000000000000
	X[11]:	0x8000000000000000
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000000
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000000
	X[16]:	0x00000000124bb158
	X[17]:	0x0000000011b7ec44 (sdk:0x349c44)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Leave()
	X[18]:	0x0000000000000001
	X[19]:	0x0000001800aa4900
	X[20]:	0x000000000ef03d38
	X[21]:	0x0000000000000000
	X[22]:	0x0000001800aa4910
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000000
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x0000004a21394f40 (SP:-0x0010)
	LR:	0x0000000008c4d3e4 (main:0xc493e4)	=> 
	SP:	0x0000004a21394f30 (SP)
	PC:	0x0000000092000046


00:36:24.195 |E| HLE.GuestThread.21 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000003.
00:36:24.221 |E| HLE.GuestThread.21 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 273
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.DataAbort(MemoryTracking tracking, UInt64 vcpu, UInt32 esr) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 227
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.SynchronousException(HvMemoryManager memoryManager, HvVcpu& vcpu) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 169
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.Execute(HvMemoryManager memoryManager, UInt64 address) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 155
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1269
   at System.Threading.Thread.StartCallback()
```

**Comment by vesper8** [comment]
Tried changing the CPU's memory manager mode to Host instead of Host Unchecked but that isn't preventing the errors unfortunately. Stuck on Throne's chapter 1 since I can't even get to the first save before it crashes

```

00:11:19.614 |E| HLE.GuestThread.24 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000003.
00:11:19.639 |E| HLE.GuestThread.24 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in /Volumes/Memories/Photos/2012/PictureBright/DEV/_EMU/2023/Ryujinx/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 281
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.DataAbort(MemoryTracking tracking, UInt64 vcpu, UInt32 esr) in /Volumes/Memories/Photos/2012/PictureBright/DEV/_EMU/2023/Ryujinx/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 227
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.SynchronousException(HvMemoryManager memoryManager, HvVcpu& vcpu) in /Volumes/Memories/Photos/2012/PictureBright/DEV/_EMU/2023/Ryujinx/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 169
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.Execute(HvMemoryManager memoryManager, UInt64 address) in /Volumes/Memories/Photos/2012/PictureBright/DEV/_EMU/2023/Ryujinx/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 160
   at Ryujinx.Cpu.AppleHv.HvCpuContext.Execute(IExecutionContext context, UInt64 address) in /Volumes/Memories/Photos/2012/PictureBright/DEV/_EMU/2023/Ryujinx/Ryujinx.Cpu/AppleHv/HvCpuContext.cs:line 30
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in /Volumes/Memories/Photos/2012/PictureBright/DEV/_EMU/2023/Ryujinx/Ryujinx.HLE/HOS/ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /Volumes/Memories/Photos/2012/PictureBright/DEV/_EMU/2023/Ryujinx/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1270
   at System.Threading.Thread.StartCallback()
```

**Comment by vesper8** [comment]
Unsure if related but after reading other issues involving `InvalidAccessHandler`, I queued the PPTC to be rebuilt, and purged the shader cache, and then I was able to get past the point where it was crashing. Pretty sure random crashes will continue to occur but so far so good.

**Comment by Winter-Stormer** [comment]
### Objects/characters flickering in cutscenes when using Vulkan backend

This flickering occurs in the great majority of cutscenes, and more frequently the more objects are on screen.
If you watch the same cutscene multiple times, a different set of objects/characters seems to flicker each time.
The problem does not seem to occur when using the OpenGL backend; if it does, it's much, much rarer.

**Specs**
*Game Update Version:* 1.0.2
*Emulator Build Version:* 1.1.644
*Graphics Backend:* Vulkan
*Hardware*:
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 3080 (driver version: 516.94)
- RAM: 32 GB
- OS: Windows 10 Pro (Version 21H2, build 19044.2604)

Steps to reproduce:
- Put attached save files in your save directory
- Launch game with Vulkan backend
- Continue at main menu
- Once game has loaded, press X to get into the game menu
- Select "Journal"
- Select "Ochette"
- Select "8. Cohazeh's Request"
- Watch the cutscene and notice occasional flickering

[Ryujinx_1.1.644_2023-02-26_22-44-47.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10836297/Ryujinx_1.1.644_2023-02-26_22-44-47.log)
[octopath-traveller-bug-save.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/10836298/octopath-traveller-bug-save.zip)

https://user-images.githubusercontent.com/3084312/221482626-aef9e496-9c5d-4a21-b1a2-66491d7dfb4b.mp4

https://user-images.githubusercontent.com/3084312/221482870-0074c672-54a0-4698-901c-1d2a2781a538.mp4

**Comment by fzpefe** [comment]
> ### Objects/characters flickering in cutscenes when using Vulkan backend
> 
> This flickering occurs in the great majority of cutscenes, and more frequently the more objects are on screen. If you watch the same cutscene multiple times, a different set of objects/characters seems to flicker each time. The problem does not seem to occur when using the OpenGL backend; if it does, it's much, much rarer.

Happens a lot for me on OpenGL even outside of cutscenes 
https://streamable.com/x3f8p3

**Comment by gr3ger** [comment]
I'm just here to confirm that the "Invalid memory access at virtual address" error happens quite frequently on my setup as well. But putting Memory Manager Mode to "Software" seems to solve the issue until a proper fix has been found. Before that audio started stuttering in increasing intervals in loading screens and then just crash the emulator.

AMD Ryzen 7 3700X
32gb ram
Nvidia RTX 2070

**Comment by vesper8** [comment]
Does anyone know how to address the super dark interiors? Whenever I enter a house, the brightness is way down. I think this is an issue with games that use the Unreal Engine.. I remember reading about it but now I can't find a fix for this. I'm seeing this on Mac.. not sure if it also affects Windows users.

**Comment by Alllusive** [comment]
> I'm just here to confirm that the "Invalid memory access at virtual address" error happens quite frequently on my setup as well. But putting **Memory Manager Mode** to **"Software"** seems to solve the issue until a proper fix has been found. Before that audio started stuttering in increasing intervals in loading screens and then just crash the emulator.
> 
> Windows 11 Ryujinx 1.1.646 AMD Ryzen 7 3700X 32gb ram Nvidia RTX 2070
> 
> ```
> 00:01:23.319 |E| HLE.GuestThread.24 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
> 00:01:24.061 |E| HLE.GuestThread.24 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
>    at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
>    at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
>    at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
>    at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
>    at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
>    at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270
> ```

I am having the exact same issue but when i try to boot the game.
I switched to Memory Management to Software but it didn't fix it for me.

Windows 11
Ryujinx 1.1.650
Intel 12600
32GB Ram
Nvidia RTX 3060

**Comment by gr3ger** [comment]
> I am having the exact same issue but when i try to boot the game.

That is strange, here are my settings if you want to try and replicate. I've been playing for around 20 hours now with no issues except some frame drops.

[System](https://imgur.com/etIXMQm)
[Graphics](https://imgur.com/EoXXvKd)

**Comment by Alllusive** [comment]
> > I am having the exact same issue but when i try to boot the game.
> 
> That is strange, here are my settings if you want to try and replicate. I've been playing for around 20 hours now with no issues except some frame drops. Do try and purge shader cache + queue PPTC rebuild by right clicking the game before booting as well.
> 
> [System](https://imgur.com/etIXMQm) [Graphics](https://imgur.com/EoXXvKd)

I switched out my settings for yours. And it just works now. No idea how exactly.
Our settings were almost the exact same.
Anyway thank you very much.

**Comment by gr3ger** [comment]
### Description of the issue

Characters, lighting, objects flicker in and out of existence seemingly.
It does seem to be related to the memory manager, since it's stable on "Software", faster but some times flickering on "Host", and fails to boot on "Host Unchecked". I also can't seem to be able to reproduce the error after a restart of Ryujinx and quickly getting to the same spot again, which makes me think it might be related to the memory manager and not anything regarding the rendering itself.

[I did however grab two RenderDoc frames and a save file that I have attached in case it helps.](https://drive.google.com/file/d/1-JP4kIkEOfovX8kReIp19tfyny58fAQC/view)


Nothing in the logs seem to be sticking out at me, and I'm not entirely sure how the memory managers works so maybe these kinds of issues are known when running on stuff other than "Software".

### Reproduction steps

Load save file
Enter the building
Progress the cutscene for a bit until you see the lady, the child, and all the other children in the audience watching (the renderdoc location is where the child says "I'll do whatever you ask, Mother.").
Characters will be flickering in/out now and again.

### Log file

[Ryujinx_1.1.662_2023-03-14_09-41-47.log](https://github.com/Ryujinx/Ryujinx/files/10968234/Ryujinx_1.1.662_2023-03-14_09-41-47.log)


### OS

Windows 11 (10.0.22621 Build 22621)

### Ryujinx version

1.1.662

### Game version

1.0.2

### CPU

AMD Ryzen 7 3700X

### GPU

NVIDIA RTX 2070

### RAM

32gb

### List of applied mods

_No response_

### Additional context?

_No response_

**Comment by RobbidyRob94** [comment]
> ![image](https://user-images.githubusercontent.com/128827296/227566790-d4869d4d-6b92-4406-a8ef-762c3346f665.png)

Emulator can't launch the game, giving the same error every time and then crashing. Tried changing the **Memory Manager Mode** to **Software** as someone else suggested, didn't help. Game is literally un-startable.

PC Specs:
Ryzen 5 2700x
Nvidia GTX 1060 6GB
16GB Ram
Windows 10

**Comment by Alllusive** [comment]
> [System](https://imgur.com/etIXMQm) [Graphics](https://imgur.com/EoXXvKd)

Use these settings exactly. worked for me.

**Comment by soulnekoes** [comment]
> //Edit: **_Setting an exception for the Ryujinx.exe in Windows Defender solved it. Don't ask me why, it's stupid and shouldn't be an issue._**
> 
> > > ![image](https://user-images.githubusercontent.com/128827296/227566790-d4869d4d-6b92-4406-a8ef-762c3346f665.png)
> > 
> > 
> > Emulator can't launch the game, giving the same error every time and then crashing. Tried changing the **Memory Manager Mode** to **Software** as someone else suggested, didn't help. Game is literally un-startable.
> > PC Specs:
> > Ryzen 5 2600x
> > Nvidia GTX 1060 6GB
> > 16GB Ram
> > Windows 10

which setting do you apply in win defender??

i have the same problem, it crashing ryujinx when opening the game.

**Comment by RobbidyRob94** [comment]
> which setting do you apply in win defender??
> 
> i have the same problem, it crashing ryujinx when opening the game.

In Windows Defender you can set up an exception, there you can choose which type of exception you want (File, Folder, File-Type or Process) in which case you choose process and put "ryujinx.exe" in there.

![windef1](https://user-images.githubusercontent.com/128827296/229331305-087818e2-ae6b-4add-b7aa-81204f8e5af0.png)

![windef2](https://user-images.githubusercontent.com/128827296/229331306-e2b5ee21-d2c5-4d2a-8d54-3e37cf0dbb24.png)

**Comment by dmfreck** [comment]
Crashes before loading game on 1.1.881 even if I add it to the Windows Defender exception list

**Comment by LUKMER** [comment]
<img width="1271" alt="Captura de pantalla 2023-07-04 a las 7 58 43" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/93650882/10943b25-8437-4eb9-947a-a0360d9afa52">
Room in dark in mac version 
M2 Ultra
In PC work fine
![WhatsApp Image 2023-07-04 at 9 33 54 AM (1)](https://github.com/Ryujinx/Ryujinx-Games-List/assets/93650882/db748fa5-15ac-4222-be1b-feb250bb5bd7)

**Comment by tvoracek** [comment]
> 

This indeed works. But...why? OT2 worked fine before without this exception. Doesn't make much sense tbh.

**Comment by tvoracek** [comment]
> > which setting do you apply in win defender??
> > i have the same problem, it crashing ryujinx when opening the game.
> 
> In Windows Defender you can set up an exception, there you can choose which type of exception you want (File, Folder, File-Type or Process) in which case you choose process and put "ryujinx.exe" in there.
> 
> ![windef1](https://user-images.githubusercontent.com/128827296/229331305-087818e2-ae6b-4add-b7aa-81204f8e5af0.png)
> 
> ![windef2](https://user-images.githubusercontent.com/128827296/229331306-e2b5ee21-d2c5-4d2a-8d54-3e37cf0dbb24.png)

This indeed works. But...why? OT2 worked fine before without this exception. Doesn't make much sense tbh.

**Comment by kokolamintun** [comment]
Same issue, room or interior is dark in mac version, still not fixed yet.

**Comment by laminsk** [comment]
have same issue, all dark when entering the room (only on mac). please help fix. Thanks

**Comment by whirlwind747** [comment]
upgrading from base version 1.0.2 to 1.1.1 update would crash upon starting.

works fine if I revert back to 1.0.2

**Comment by antoniodesousa** [comment]
I just tested it and it works fine for me on version 1.1.1.
Ryujinx_1.1.1336

**Comment by amwinagil** [comment]
UP UP, room or interior is dark in mba M1 version, Ryujinx 1.1.1397. please fix it. thank you
