### ISSUE TITLE
Bravely Default II Demo

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx-Games-List#448]
#### Current on `master` : 1.0.4047

*Crashes on startup*

```
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```
#### Log file :

[Ryujinx_2020-03-27_17-38-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4394835/Ryujinx_2020-03-27_17-38-28.log)

**Comment by EmulationFanatic** [comment]
Needs update

**Comment by SeraUX** [comment]
## Bravely Default II Demo

#### Game Update Version : 1.0.0

#### Current on `master` : 1.0.4740

Game crashes while booting.

```
00:03:25.757 | GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentException: Invalid variable type "F64".
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.NumberFormatter.TryFormat(Int32 value, VariableType dstType, String& formatted) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\NumberFormatter.cs:line 34
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.TypeConversion.ReinterpretCast(CodeGenContext context, IAstNode node, VariableType srcType, VariableType dstType) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\TypeConversion.cs:line 18
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions.InstGen.GetExpression(CodeGenContext context, AstOperation operation) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\Instructions\InstGen.cs:line 30
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions.InstGen.GetExpression(CodeGenContext context, IAstNode node) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\Instructions\InstGen.cs:line 25
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.TypeConversion.ReinterpretCast(CodeGenContext context, IAstNode node, VariableType srcType, VariableType dstType) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\TypeConversion.cs:line 24
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.PrintBlock(CodeGenContext context, AstBlock block) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 130
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.PrintMainBlock(CodeGenContext context, StructuredProgramInfo info) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 65
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.Generate(StructuredProgramInfo info, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 21
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(Operation[] ops, ShaderConfig config, Int32 size, Int32 sizeA) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 51
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 19
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateGraphicsShader(GpuState state, ShaderStage stage, UInt64 gpuVa, UInt64 gpuVaA) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 333
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 140
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 867
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 129
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 59
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 105
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 497
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 217
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 102
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CachedMacro.Execute(Int32[] mme, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 73
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 218
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 327
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs :

##### CPU: i3 7300
##### GPU: NVIDIA Corporation GeForce GTX 1050 Ti
##### RAM: 8GB

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/1255

#### Screenshots :



#### Log file :

[bd2-demo.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4809668/bd2-demo.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Cronos-0** [comment]
## Bravely Default II Demo

#### Game Update Version : 1.0.0 / USA

#### Current on `master` : 1.0.5636

Now it boots to the menu page. Still crashes after pressing start game

```
00:06:03.888 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 451
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 257
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 623
   at Ryujinx.Graphics.Gpu.Image.Texture.InitializeData(Boolean isView, Boolean withData) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 211
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(TextureInfo info, TextureSearchFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 832
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 35
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 306
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 243
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 302
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 121
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 149
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 41
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 82
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 67
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 352
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Outstanding Issues :



#### Screenshots :

![bandicam 2020-11-08 02-24-09-451](https://user-images.githubusercontent.com/35269098/98449878-46064c80-216a-11eb-8ee9-09b9e1f698c6.jpg)
![bandicam 2020-11-08 02-24-25-433](https://user-images.githubusercontent.com/35269098/98449880-49013d00-216a-11eb-9576-436ebebc0a77.jpg)
![bandicam 2020-11-08 02-25-11-139](https://user-images.githubusercontent.com/35269098/98449883-4acb0080-216a-11eb-9a68-5d2dd5f54e7b.jpg)
![bandicam 2020-11-08 02-17-52-235](https://user-images.githubusercontent.com/35269098/98449886-4c94c400-216a-11eb-8cea-3b0c506aebbb.jpg)
![bandicam 2020-11-08 02-17-58-996](https://user-images.githubusercontent.com/35269098/98449887-4e5e8780-216a-11eb-83c6-f86afd56538e.jpg)
![bandicam 2020-11-08 02-18-00-974](https://user-images.githubusercontent.com/35269098/98449889-4f8fb480-216a-11eb-8928-4ffcedaee572.jpg)


#### Logs :

[BD2D.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5505334/BD2D.log)

**Comment by SeraUX** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
