### ISSUE TITLE
SD Shin Kamen Rider Ranbu [ SD シン・仮面ライダー 乱舞 ] - 0100CD40192AC000

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#4525]
### Game Name

SD Shin Kamen Rider Ranbu [ SD シン・仮面ライダー 乱舞 ]

### Game Update Version

1.0.0

### Emulator Build Version

1.1.677

### Graphics Backend

Vulkan

### Hardware Specs

- #### GPU: GTX 1660 SUPER 6GB
- #### CPU: INTEL I5 8400
- #### RAM: KINGSTON DDR4 16GB

### Game State

The game crashes after the developer logo ends

```
00:00:49.093 |W| HLE.GuestThread.19 KernelSvc : CreateTransferMemory(handle: 0x00000000) = InvalidCurrentMemory
00:00:49.102 |I| HLE.OsThread.20 ServiceAm SetTerminateResult: Result = 0x0000d401 (ResultSvcInvalidCurrentMemory (2001-0106)).
00:00:49.602 |I| HLE.GuestThread.19 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 96
   0x000000000f9388b8	sdk:0x8d8b8	
   0x000000000f93897c	sdk:0x8d97c	
   0x000000000f9da390	sdk:0x12f390	nn::os::detail::TransferMemoryImplByHorizon::Create(unsigned int*, void*, unsigned long, nn::os::MemoryPermission):0x00d0
   0x000000000f9d6b40	sdk:0x12bb40	nn::os::CreateTransferMemory(nn::os::TransferMemoryType*, void*, unsigned long, nn::os::MemoryPermission):0x0020
   0x000000000fba1770	sdk:0x2f6770	nn::ec::detail::ShopServiceAccessServer::Proxy::Initialize(nn::ec::detail::ShopServiceAccessServer::IProxyObjectMemoryProvider*, void*, unsigned long):0x01c8
   0x000000000fb9eac0	sdk:0x2f3ac0	
   0x000000000fb9ea5c	sdk:0x2f3a5c	nn::ec::InitializeForShopServiceAccessors(void*, unsigned long):0x000c
   0x00000000097fe1e4	main:0x17fa1e4	
   0x000000000b965978	main:0x3961978	
   0x0000000008114704	main:0x110704	
   0x00000000083e3a38	main:0x3dfa38	
   0x0000000008545110	main:0x541110	
   0x0000000008543d48	main:0x53fd48	
   0x0000000008529cd4	main:0x525cd4	
   0x0000000008529df0	main:0x525df0	
   0x000000000852aa04	main:0x526a04	
   0x000000000888398c	main:0x87f98c	
   0x00000000086da934	main:0x6d6934	
   0x00000000086da984	main:0x6d6984	
   0x00000000086dacbc	main:0x6d6cbc	
   0x0000000008452a50	main:0x44ea50	nnMain:0x06f0
   0x000000000f9a5414	sdk:0xfa414	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000080000d4	rtld:0x00d4	


00:00:49.603 |I| HLE.GuestThread.19 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x00000049f2d08090 (SP:-0x01b0)
	X[02]:	0x0000000000000004
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000100000000
	X[09]:	0x000000000f8ab000 (sdk:0x0000)	=> 
	X[10]:	0x0000000000cea088
	X[11]:	0x0080000000000000
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000002
	X[14]:	0x0000000000000002
	X[15]:	0x0000000000000000
	X[16]:	0x000000000f93a0f0 (sdk:0x8f0f0)	=> nn::diag::detail::Abort(nn::Result const*)
	X[17]:	0x0000000010595088
	X[18]:	0x0000000000000000
	X[19]:	0x00000049f2d08090 (SP:-0x01b0)
	X[20]:	0x0000000000000000
	X[21]:	0x000000001033d30a
	X[22]:	0x000000001033d30a
	X[23]:	0x0000000000000000
	X[24]:	0x000000001033d30a
	X[25]:	0x00000049f2d08060 (SP:-0x0180)
	X[26]:	0x000000000f93897c (sdk:0x8d97c)	=> 
	X[27]:	0x000000001033d30a
	X[28]:	0x000000000852a9cc (main:0x5269cc)	=> 
	FP:	0x00000049f2d07ee0 (SP)
	LR:	0x000000000f93a108 (sdk:0x8f108)	=> nn::diag::detail::Abort(nn::Result const*):0x0018
	SP:	0x00000049f2d07ee0 (SP)
	PC:	0x000000000fa03b40 (sdk:0x158b40)	=> 

00:00:49.664 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1873
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1807
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3383
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 50
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270
   at System.Threading.Thread.StartCallback()



```

### Screenshots

![bandicam 2023-03-24 08-56-53-171](https://user-images.githubusercontent.com/35269098/227406744-18afe9b0-b5a1-4fa3-926c-a865efa316d9.jpg)
![bandicam 2023-03-24 08-57-04-875](https://user-images.githubusercontent.com/35269098/227406753-e9607ea6-19ba-4aeb-800d-1c5fb6d5bbd6.jpg)
![bandicam 2023-03-24 08-57-08-722](https://user-images.githubusercontent.com/35269098/227406762-aae51e65-bfea-4c06-a109-23bd3d550932.jpg)
![bandicam 2023-03-24 08-57-11-024](https://user-images.githubusercontent.com/35269098/227406766-0e2c3365-b6f6-4182-b729-baf6bfb45bc0.jpg)
![bandicam 2023-03-24 08-57-21-405](https://user-images.githubusercontent.com/35269098/227406813-13c81ed4-34fa-4716-b6dd-2b7fb4f47b70.jpg)

### Log File

[Ryujinx_1.1.677_2023-03-24_08-55-01.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11057865/Ryujinx_1.1.677_2023-03-24_08-55-01.log)

**Comment by MetrosexualGarbodor** [comment]
Hasn't even been tagged and already needs an update.

**Comment by Cronos-0** [comment]
Update now playable
