### ISSUE TITLE
Blade Assault - 0100EA1018A2E000

### ISSUE THREAD

**Issue by F1ReB4LL** [Ryujinx/Ryujinx-Games-List#4535]
### Game Name

Blade Assault

### Game Update Version

1.0.0

### Emulator Build Version

1.1.692

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: *i5-11400H*
- ##### GPU: *NVIDIA RTX 3050*
- ##### RAM: *24GB*

### Game State

Crashes right after loading, shows nothing.

`AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Audio.Renderer.Dsp.Command.DeviceSinkCommand.Process(CommandList context) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\DeviceSinkCommand.cs:line 61
   at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\Command\CommandList.cs:line 124
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in D:\a\Ryujinx\Ryujinx\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 213`

### Log File

[Ryujinx_1.1.692_2023-04-02_02-57-51.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11130902/Ryujinx_1.1.692_2023-04-02_02-57-51.log)

**Comment by F1ReB4LL** [comment]
Ryujinx 1.1.1294 - same crash:

```
AudioProcessor.Worker Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.     
at Ryujinx.Audio.Renderer.Dsp.Command.DeviceSinkCommand.Process(CommandList context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Audio\Renderer\Dsp\Command\DeviceSinkCommand.cs:line 61                                                                                                                                            
at Ryujinx.Audio.Renderer.Dsp.Command.CommandList.Process(IHardwareDevice outputDevice) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Audio\Renderer\Dsp\Command\CommandList.cs:line 124                                                                                                                                              
at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Work() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 209
```

But I've tested a bit and noticed that it only happens with the 1.0.0 game build and only with the SDL2 and SoundIO audio outputs. OpenAL and Dummy work fine (no crash, game works, with sound in OpenAL mode).

Versions 1.0.1 and above work fine with all 4 possible audio outputs.

![ryujinx_bldaslt1](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/0da54ae7-108d-4279-b034-da5e123bd153)
![ryujinx_bldaslt2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/ff3deff1-5f8f-4d7a-a8e1-8df8e947bed8)
![ryujinx_bldaslt3](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/13954384-0b96-4b4f-aa1a-f8ef565818a3)
![ryujinx_bldaslt4](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/71e43aa4-5078-42fe-9b84-9c146114e2cf)
![ryujinx_bldaslt5](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/e226e5f4-a705-4424-ae69-9dee5c3a0460)
![ryujinx_bldaslt6](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/fe9a1f33-85da-4414-bfbf-24178fdb6b6f)
![ryujinx_bldaslt7](https://github.com/Ryujinx/Ryujinx-Games-List/assets/39680140/e062f7ad-8768-4434-ae04-c0000eb60c4d)
