### ISSUE TITLE
Heaven Dust

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#457]
#### Current on `master` : 1.0.4047

Crashes on boot

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: android.gui.IGraphicBufferProducer 2
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.NvFlinger.ProcessParcelRequest(ServiceCtx context, Byte[] parcelData, Int32 code) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\NvFlinger.cs:line 88
   at Ryujinx.HLE.HOS.Services.Vi.RootService.ApplicationDisplayService.IHOSBinderDriver.TransactParcelAuto(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Vi\RootService\ApplicationDisplayService\IHOSBinderDriver.cs:line 83
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

#### Pull requests needed :
Needs pr #981 to work

#### Log file :
[heaven-dust.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4396367/heaven-dust.log)

**Comment by GoffyDude** [comment]
Needs update

**Comment by SeraUX** [comment]
## Heaven Dust

#### Current on `master` : 1.0.4573
Game boots and plays well, no problems found.

#### Screenshots :

![2020-05-17-152353_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82148421-5fca7500-9854-11ea-9b1a-7edcf0e4f1b5.png)
![2020-05-17-153348_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82148425-62c56580-9854-11ea-972a-009eaf1c4fc8.png)
![2020-05-17-153415_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82148430-68bb4680-9854-11ea-9497-fb9492bdbefd.png)
![2020-05-17-153410_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82148433-6c4ecd80-9854-11ea-8d69-54c34aa2d358.png)
![2020-05-17-153540_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82148606-06af1100-9855-11ea-9f18-7254aa8cd3fb.png)



#### Log file :
[heaven-dust.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4640334/heaven-dust.log)

**Comment by GoffyDude** [comment]
Updated
