### ISSUE TITLE
BraveDungeon - The Meaning of Justice - 010068A00DAFC000

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#4574]
### Game Name

BraveDungeon - The Meaning of Justice

### Game Update Version

1.0.0

### Emulator Build Version

1.1.726

### Graphics Backend

Vulkan

### Hardware Specs

- #### GPU: GTX 1660 SUPER 6GB
- #### CPU: INTEL I5 8400
- #### RAM: KINGSTON DDR4 16GB

### Game State

The game plays smoothly. but when pressing stop emu The game crashes immediately (seems like it's random), normally I tested 3 times, it crashes 1 time

```
00:05:32.948 |E| HLE.OsThread.4 Application : Unhandled exception caught: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at Microsoft.IO.RecyclableMemoryStreamManager.ReturnBlocks(List`1 blocks, Guid id, String tag) in /_/src/RecyclableMemoryStreamManager.cs:line 570
   at Microsoft.IO.RecyclableMemoryStream.Dispose(Boolean disposing) in /_/src/RecyclableMemoryStream.cs:line 301
   at System.IO.BinaryWriter.Dispose(Boolean)
   at System.IO.BinaryWriter.Dispose()
   at Ryujinx.HLE.HOS.Services.ServerBase.Dispose(Boolean disposing) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 409
   at Ryujinx.HLE.HOS.Services.ServerBase.Dispose() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 418
   at Ryujinx.HLE.HOS.Services.Sm.IUserInterface.DestroyAtExit() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\Sm\IUserInterface.cs:line 256
   at Ryujinx.HLE.HOS.Services.ServerBase.Dispose(Boolean disposing) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 395
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 196
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 109
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1262
   at System.Threading.Thread.StartCallback()

```

### Screenshots

![bandicam 2023-04-23 07-34-19-173](https://user-images.githubusercontent.com/35269098/233813639-cf8d9010-a7e7-48a3-8cc0-a509aa80e61f.jpg)
![bandicam 2023-04-23 07-34-37-601](https://user-images.githubusercontent.com/35269098/233813641-8990594d-59b1-46f4-bd1e-960bd441cd24.jpg)
![bandicam 2023-04-23 07-34-57-677](https://user-images.githubusercontent.com/35269098/233813642-47a23aef-42de-42a3-b7bc-d65d34188a32.jpg)
![bandicam 2023-04-23 07-35-18-239](https://user-images.githubusercontent.com/35269098/233813644-069eb046-e84b-49d9-901f-d8d6dde1575f.jpg)
![bandicam 2023-04-23 07-35-45-522](https://user-images.githubusercontent.com/35269098/233813647-2d872e52-4178-402b-864f-98cbc9d643ea.jpg)
![bandicam 2023-04-23 07-36-20-657](https://user-images.githubusercontent.com/35269098/233813648-6fa7c2d3-10ed-454e-86de-d530bc3dc8e2.jpg)
![bandicam 2023-04-23 07-37-12-987](https://user-images.githubusercontent.com/35269098/233813649-b9f76a2b-d8c5-4a26-949a-421b998af599.jpg)
![bandicam 2023-04-23 07-37-35-631](https://user-images.githubusercontent.com/35269098/233813650-3fd87edd-b4cc-4e69-8a72-b8faa48ae850.jpg)
![bandicam 2023-04-23 07-37-56-828](https://user-images.githubusercontent.com/35269098/233813652-9e0e3d13-91f7-45e3-bffd-d232d040c598.jpg)
![bandicam 2023-04-23 07-38-40-421](https://user-images.githubusercontent.com/35269098/233813655-c7161cf8-e44b-4281-9481-a02afcd60f24.jpg)
![bandicam 2023-04-23 07-38-53-900](https://user-images.githubusercontent.com/35269098/233813656-3812eb18-6b2a-4d63-a7f0-7a1744c8c4d3.jpg)

### Log File

[Ryujinx_1.1.726_2023-04-23_07-31-35.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11302602/Ryujinx_1.1.726_2023-04-23_07-31-35.log)

**Comment by MetrosexualGarbodor** [comment]
According to reports, the error described here is fixed in https://github.com/Ryujinx/Ryujinx/pull/4577
