### ISSUE TITLE
Disney SpeedStorm - 0100F0401435E000

### ISSUE THREAD

**Issue by Cronos-0** [Ryujinx/Ryujinx-Games-List#4583]
### Game Name

Disney SpeedStorm

### Game Update Version

1.0.0f_2

### Emulator Build Version

1.1.739

### Graphics Backend

Vulkan

### Hardware Specs

- #### GPU: GTX 1660 SUPER 6GB
- #### CPU: INTEL I5 8400
- #### RAM: KINGSTON DDR4 16GB

### Game State

I tested it 2 times. The first time I ran the game without using saves. The game crashes on the title page ( a symptom that occurs before the game crashes. In the preview video, it lags intermittently. which sometimes freezes ) The 2nd time I used to save the game crashed immediately as well. Because the game requires additional services. Made me have to enable the option `Ignore Missing Services` Yes, the game still crashes

- additionally this game usually requires an internet connection to play. But you can skip it by using a save ( must finish tutorial first )

```
00:02:04.852 |E| HLE.OsThread.20 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.AccountService.IManagerForApplication: 150

Guest Stack Trace:
Process: Service, PID: 97

Buffer Information:
	PtrBuff:
	[0] Position: 0x0000006556c00000 Size: 0x0000000000000200

Raw Request Data:
00000000   01 00 14 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  96 00 00 00 00 00 00 00   SFCI···········
00000020   00 10 00 00 00 00 00 00  00 80 06 00               ···········    

   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 66
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 346
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 196
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 109
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1258

```

```
00:00:30.962 |W| HLE.OsThread.20 KernelIpc CallCmifMethod: Missing service Ryujinx.HLE.HOS.Services.Account.Acc.AccountService.IManagerForApplication: 150 ignored
00:00:31.550 |I| HLE.GuestThread.22 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Disney Speedstorm, PID: 96
   0x00000000085e1cb0	main:0x5ddcb0	
   0x00000000085e1444	main:0x5dd444	
   0x00000000080e1fcc	main:0xddfcc	
   0x00000000080e8550	main:0xe4550	
   0x000000000816c500	main:0x168500	
   0x000000000ce5da70	main:0x4e59a70	
   0x000000000ce580dc	main:0x4e540dc	
   0x000000000ce57ec8	main:0x4e53ec8	
   0x0000000008d80544	main:0xd7c544	
   0x0000000008d806a4	main:0xd7c6a4	
   0x0000000008d7fa18	main:0xd7ba18	
   0x0000000008d7edec	main:0xd7adec	
   0x0000000008d544e0	main:0xd504e0	
   0x0000000008d65ea4	main:0xd61ea4	
   0x0000000008d65614	main:0xd61614	
   0x000000000ce5739c	main:0x4e5339c	
   0x000000000ce59b0c	main:0x4e55b0c	
   0x000000000ce59464	main:0x4e55464	
   0x000000000819758c	main:0x19358c	
   0x000000000818ae00	main:0x186e00	
   0x00000000080f5140	main:0xf1140	
   0x00000000080f48d4	main:0xf08d4	
   0x0000000008d96f1c	main:0xd92f1c	
   0x0000000008d9acb0	main:0xd96cb0	
   0x0000000008d80544	main:0xd7c544	
   0x0000000008d82d88	main:0xd7ed88	
   0x0000000008d83a3c	main:0xd7fa3c	
   0x0000000008d7fa18	main:0xd7ba18	
   0x0000000008d7f4b4	main:0xd7b4b4	
   0x00000000083ade50	main:0x3a9e50	
   0x00000000159eb674	sdk:0x132674	
   0x00000000159e2578	sdk:0x129578	
   0x00000000159e8b54	sdk:0x12fb54	
   0x0000000000000000


00:00:31.561 |I| HLE.GuestThread.22 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000004a13c73758 (SP:-0x0008)
	X[01]:	0x0000000000000000
	X[02]:	0x0000004a13c737a0 (SP:-0x0050)
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000016563448
	X[09]:	0x00000000158b9000 (sdk:0x0000)	=> 
	X[10]:	0x0000000000cee110
	X[11]:	0x0080000000000000
	X[12]:	0x0000000000000000
	X[13]:	0x00000000165cabc0
	X[14]:	0x0000000000000010
	X[15]:	0x0000000000000000
	X[16]:	0x0000000015a52c70 (sdk:0x199c70)	=> nn::account::NintendoAccountAuthorizationRequestContext::Invoke()
	X[17]:	0x00000000165a7110
	X[18]:	0x0000000000000000
	X[19]:	0x0000004a13c739a8 (SP:-0x0258)
	X[20]:	0x0000000000000000
	X[21]:	0x0000000000000000
	X[22]:	0x0000004a13c739e0 (SP:-0x0290)
	X[23]:	0x000000656590c3a8
	X[24]:	0x0000000013ce0000
	X[25]:	0x0000004a13c742c0 (SP:-0x0b70)
	X[26]:	0x00000065659b7738
	X[27]:	0x0000000000000249
	X[28]:	0x00000065659b7690
	FP:	0x0000004a13c737f0 (SP:-0x00a0)
	LR:	0x0000000015a50934 (sdk:0x197934)	=> nn::account::CreateNintendoAccountAuthorizationRequest(nn::account::NintendoAccountAuthorizationRequestContext*, nn::account::UserHandle const&, nn::account::NintendoAccountAuthorizationRequestParameters const&, void*, unsigned long):0x00e4
	SP:	0x0000004a13c73750 (SP)
	PC:	0x0000000015a52c70 (sdk:0x199c70)	=> nn::account::NintendoAccountAuthorizationRequestContext::Invoke()


00:00:31.561 |E| HLE.GuestThread.22 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:00:31.614 |E| HLE.GuestThread.22 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1266


```

### Screenshots

![bandicam 2023-05-01 06-24-46-227](https://user-images.githubusercontent.com/35269098/235381428-5373d79c-8002-415f-9c77-fcb786b1ad02.jpg)
![bandicam 2023-05-01 06-25-34-531](https://user-images.githubusercontent.com/35269098/235381434-1a0ae1c3-7289-4519-9d33-a6ea45adb2cf.jpg)
![bandicam 2023-05-01 06-25-40-385](https://user-images.githubusercontent.com/35269098/235381442-0c43bf8a-c0a0-4993-93b0-53d1ae1fa1dc.jpg)
![bandicam 2023-05-01 06-25-43-621](https://user-images.githubusercontent.com/35269098/235381447-8073854a-3b27-4d42-ace5-0edaabc86dbe.jpg)
![bandicam 2023-05-01 06-29-42-437](https://user-images.githubusercontent.com/35269098/235381453-41438a61-a1ea-4fb1-91cc-6312ed2327fc.jpg)

### Log File

T1 : [Ryujinx_1.1.739_2023-05-01_06-23-39.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11362686/Ryujinx_1.1.739_2023-05-01_06-23-39.log)
T2 : [Ryujinx_1.1.739_2023-05-01_06-26-59.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11362687/Ryujinx_1.1.739_2023-05-01_06-26-59.log)

**Comment by aandrioni** [comment]
`But` you can skip it by using a save ( must finish tutorial first )" `

Could you share this save, please?

**Comment by Cronos-0** [comment]
@aandrioni I think it's useless for now. I will share when it update more services. But now it's useless for Emu

**Comment by Cronos-0** [comment]
The game is currently unplayable, a missing service is required, and the error below occurs with the latest update (v1.3.1a) not much different from the error above

```
00:00:51.456 |E| HLE.OsThread.43 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.AccountService.IManagerForApplication: 150

Guest Stack Trace:
Process: Service, PID: 120

Buffer Information:
	PtrBuff:
	[0] Position: 0x0000006556c00000 Size: 0x0000000000000200

Raw Request Data:
00000000   01 00 14 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  96 00 00 00 00 00 00 00   SFCI···········
00000020   00 10 00 00 06 41 28 C0  00 80 05 00               ·····A(À···    

   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 159
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 358
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1256
   at System.Threading.Thread.StartCallback()

```

![bandicam 2023-11-27 09-05-41-356](https://github.com/Ryujinx/Ryujinx-Games-List/assets/35269098/36b00296-8e91-441b-9c22-7c6f5f6792fb)
