### ISSUE TITLE
Mercenaries Wings The False Phoenix

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#459]
#### Current on `master` : 1.0.4047

Crashes on Launch. Needs the controller applet

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Controller applet is not implemented.
   at Ryujinx.HLE.HOS.Applets.AppletManager.Create(AppletId applet, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Applets\AppletManager.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor..ctor(AppletId appletId, Horizon system) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 27
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ILibraryAppletCreator.CreateLibraryApplet(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\SystemAppletProxy\ILibraryAppletCreator.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

#### Pull requests needed :
Needs pr [#1003](https://github.com/Ryujinx/Ryujinx/pull/1003)

#### Log file :
[mercenaries-wings-the-false-phoenix.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4396441/mercenaries-wings-the-false-phoenix.log)

**Comment by HorrorTroll** [comment]
Need updated

**Comment by SeraUX** [comment]
#### Update on `master` : 1.0.4142
Game is playable. Didn't find any problems in my testing

#### Screenshots :
![2020-04-05-162155_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/78501222-1833d200-775b-11ea-9a3a-76f421643e8e.png)
![2020-04-05-162254_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/78501230-1bc75900-775b-11ea-8cf6-eb816d4066d1.png)
![2020-04-05-162422_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/78501243-21bd3a00-775b-11ea-9315-e483a7a401c2.png)

![2020-04-05-162441_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/78501245-2550c100-775b-11ea-9edb-7eba14da5f2a.png)
![2020-04-05-162944_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/78501262-37326400-775b-11ea-968a-58a5ef0a30da.png)
![2020-04-05-163027_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/78501246-284bb180-775b-11ea-83e3-c0501bffefc3.png)

#### Log file :

**Comment by GoffyDude** [comment]
Updated
