### ISSUE TITLE
Bayonetta 2

### ISSUE THREAD

**Issue by AcK77** [Ryujinx/Ryujinx-Games-List#46]
Current State on `master`: 

```
System.NotImplementedException : 'R8G8B8A8'
```

Maybe due to https://github.com/Ryujinx/Ryujinx/pull/402 ?

Before this PR merged you got:

```
System.NotImplementedException : 'Texture resizing is not supported'
```

If you skip the exception, you can go to the boot and menu screen:

![unknown 2](https://user-images.githubusercontent.com/4905390/45397944-83cac180-b642-11e8-9906-d8eafc401e60.png)
![unknown 3](https://user-images.githubusercontent.com/4905390/45397945-84635800-b642-11e8-9bba-cc14ea9d4489.png)

But when you start a new game, the game deadlock.

**Comment by jduncanator** [comment]
Bayonetta 2 now crashes with:

```
Unhandled Exception: System.NotImplementedException: Per component types are not implemented!
   at Ryujinx.Graphics.Texture.ImageUtils.ConvertTexture(GalTextureFormat Format, GalTextureType RType, GalTextureType GType, GalTextureType BType, GalTextureType AType, Boolean ConvSrgb) in Ryujinx.Graphics\Texture\ImageUtils.cs:line 154
   at Ryujinx.Graphics.Texture.TextureFactory.GetImageFormat(Int32[] Tic) in Ryujinx.Graphics\Texture\TextureFactory.cs:line 98
   at Ryujinx.Graphics.Texture.TextureFactory.MakeTexture(NvGpuVmm Vmm, Int64 TicPosition) in Ryujinx.Graphics\Texture\TextureFactory.cs:line 15
   at Ryujinx.Graphics.NvGpuEngine3d.UploadTexture(NvGpuVmm Vmm, Int32 TexIndex, Int32 TextureHandle) in Ryujinx.Graphics\NvGpuEngine3d.cs:line 533
   at Ryujinx.Graphics.NvGpuEngine3d.UploadTextures(NvGpuVmm Vmm, GalPipelineState State, Int64[] Keys) in Ryujinx.Graphics\NvGpuEngine3d.cs:line 506
   at Ryujinx.Graphics.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in Ryujinx.Graphics\NvGpuEngine3d.cs:line 118
   at Ryujinx.Graphics.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in Ryujinx.Graphics\NvGpuEngine3d.cs:line 79
   at Ryujinx.Graphics.MacroInterpreter.Send(NvGpuVmm Vmm, Int32 Value) in Ryujinx.Graphics\MacroInterpreter.cs:line 415
   at Ryujinx.Graphics.MacroInterpreter.Step(NvGpuVmm Vmm, Int32[] Mme) in Ryujinx.Graphics\MacroInterpreter.cs:line 192
   at Ryujinx.Graphics.MacroInterpreter.Execute(NvGpuVmm Vmm, Int32[] Mme, Int32 Position, Int32 Param) in Ryujinx.Graphics\MacroInterpreter.cs:line 87
   at Ryujinx.Graphics.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in Ryujinx.Graphics\NvGpuFifo.cs:line 188
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in Ryujinx.Graphics\NvGpuFifo.cs:line 120
   at Ryujinx.Graphics.NvGpuFifo.Step() in Ryujinx.Graphics\NvGpuFifo.cs:line 104
```

**Comment by AcK77** [comment]
Need an update.

**Comment by jduncanator** [comment]
Updated.

**Comment by Seker-0** [comment]
#### Current on `master` : 1.0.3609

Can be used to save or play normally, can also be played..
Not updated since 2018 lol

#### Status : Playable 

#### Screenshots :
![bandicam 2020-02-02 04-35-16-543](https://user-images.githubusercontent.com/35269098/73599634-1e011180-4578-11ea-9c74-6b78d94455cd.jpg)
![bandicam 2020-02-02 04-37-31-810](https://user-images.githubusercontent.com/35269098/73599639-2b1e0080-4578-11ea-9306-a8318e705b7d.jpg)
![bandicam 2020-02-02 04-38-19-529](https://user-images.githubusercontent.com/35269098/73599643-37a25900-4578-11ea-993e-e58d1e44e43a.jpg)
![bandicam 2020-02-02 04-38-50-509](https://user-images.githubusercontent.com/35269098/73599646-40932a80-4578-11ea-98fb-d6f176911b8f.jpg)

**Comment by EmulationFanatic** [comment]
## Bayonetta 2

#### Current on `master` : 1.0.4683

Game now loads and plays at a high FPS, after significant initial shader stutter.

#### Screenshots :

![2020-06-08 12_03_04-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065284-62b31400-a981-11ea-8dd9-7096467b819d.png)
![2020-06-08 12_03_09-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065292-66469b00-a981-11ea-8ce1-00a259fc4b1d.png)
![2020-06-08 12_03_15-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065299-69418b80-a981-11ea-9dbb-7f0ba3568aaf.png)
![2020-06-08 12_04_15-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065312-6cd51280-a981-11ea-86dc-48c7ac67431e.png)
![2020-06-08 12_04_33-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065336-752d4d80-a981-11ea-8335-63ecb58944f2.png)
![2020-06-08 12_06_22-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065364-7f4f4c00-a981-11ea-9579-d907840be5e0.png)
![2020-06-08 12_07_09-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065393-8c6c3b00-a981-11ea-8b4e-3930be825e89.png)
![2020-06-08 12_07_13-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065418-9726d000-a981-11ea-89a8-4b3b1e4755cb.png)
![2020-06-08 12_07_53-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065444-a148ce80-a981-11ea-81d0-9539715c2d9c.png)
![2020-06-08 12_08_48-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065472-a9a10980-a981-11ea-90dd-43ad9aa3bfdb.png)
![2020-06-08 12_09_00-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065483-ae65bd80-a981-11ea-81b5-051311dbeb51.png)
![2020-06-08 12_09_26-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065510-b9b8e900-a981-11ea-9597-5d7539553ac4.png)
![2020-06-08 12_09_31-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065512-ba517f80-a981-11ea-80a6-32c0a5882561.png)
![2020-06-08 12_10_05-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065540-c5a4ab00-a981-11ea-98ad-cdd837404b9d.png)
![2020-06-08 12_10_33-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065579-d0f7d680-a981-11ea-96be-fe36368a015b.png)
![2020-06-08 12_10_39-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065585-d523f400-a981-11ea-8f2f-d401416ab2fe.png)
![2020-06-08 12_11_17-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065589-d7864e00-a981-11ea-94f4-7d1de1b9e3d9.png)
![2020-06-08 12_12_00-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065593-da813e80-a981-11ea-9ff7-2634a9fe4cb9.png)
![2020-06-08 12_12_10-Ryujinx 1 0 4683 - Bayonetta 2 v1 0 (01007960049A0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84065619-e4a33d00-a981-11ea-83d3-a0933e36d097.png)

#### Log file :

[B2.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4747792/B2.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Kryptuq** [comment]
in order to make LDN work both need to go Tag Climax and Local Play.

One Player need to start a Session "With CPU". If the Screen shows "Select a Verse Card." the other player needs to do "Find Player" and u can request to join his room :)

**Comment by Pixxel123** [comment]
On current `master` 1.0.6997, I've observed an issue that seems to happen with the animations when Bayonetta is firing her weapon in the air. On original hardware, she falls and skips with each shot, her body staying upright:

https://user-images.githubusercontent.com/36304206/129735162-2a6704ca-912f-44d8-89a7-bdb18fd4be1a.mp4

Normal shot, just holding Y while falling.


When the player holds the lock on button (ZR) and Y while falling in the air, the character animation changes, she seems to be stuck in a looping "fetal position" instead of remaining upright.

https://user-images.githubusercontent.com/36304206/129735406-824c54e2-9a5d-40e9-93dc-35c15a253e66.mp4

Bad animation example 1

https://user-images.githubusercontent.com/36304206/129735581-ad5dba2d-ac87-4e5e-a3ff-8a67ba088d2f.mp4

Bad animation example 2

I have not been able to reproduce this at all on original hardware.

**Comment by LukeWarnut** [comment]
New update (1.2) leaves a mess in the log when calling UpdateUserPresence,
![image](https://user-images.githubusercontent.com/65521430/204071213-92050f60-5571-492b-bfae-39d87abfc22d.png)

[Ryujinx_1.1.389_2022-11-25_20-25-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10095625/Ryujinx_1.1.389_2022-11-25_20-25-28.log)
