### ISSUE TITLE
Dexteritrip

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#462]
#### Current on `master` : 1.0.4047

Crashes while exiting the first screen after starting a game.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32 width, Int32 height, Int32 depth, Int32 levels, Int32 layers, Int32 blockWidth, Int32 blockHeight, Int32 bytesPerPixel, Int32 gobBlocksInY, Int32 gobBlocksInZ, Int32 gobBlocksInTileX, SizeInfo sizeInfo, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.Texture\LayoutConverter.cs:line 215
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 473
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 324
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(RtColorState colorState, Int32 samplesInX, Int32 samplesInY) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 387
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateRenderTargetState(GpuState state, Boolean useControl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 276
   at Ryujinx.Graphics.Gpu.Engine.Methods.Clear(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodClear.cs:line 60
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 74
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, GpuState shadowState, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 497
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 131
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 98
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 154
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 212
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 187
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 329
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :
![2020-03-28 02_26_44-Ryujinx 1 0 4047 _ Dexteritrip _ 010044000CBCA000](https://user-images.githubusercontent.com/62343878/77818970-d2ad4000-709c-11ea-90a6-5971003357ac.png)
![2020-03-28 02_33_28-Ryujinx 1 0 4047 _ Dexteritrip _ 010044000CBCA000](https://user-images.githubusercontent.com/62343878/77818972-d4770380-709c-11ea-855e-af69a19688fa.png)
![2020-03-28 02_33_37-Ryujinx 1 0 4047 _ Dexteritrip _ 010044000CBCA000](https://user-images.githubusercontent.com/62343878/77818973-d50f9a00-709c-11ea-9c25-2a5b50d8049c.png)

#### Log file :

[Dexteritrip.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4396836/Dexteritrip.zip)

**Comment by EmulationFanatic** [comment]
Updated
