### ISSUE TITLE
Pikmin 4 - 0100B7C00933A000

### ISSUE THREAD

**Issue by Jomanakk** [Ryujinx/Ryujinx-Games-List#4693]
### Game Name

Pikmin 4

### Game Update Version

1.0.1

### Emulator Build Version

1.1.966

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Intel I5 12400F*
- ##### GPU: *Nvidia GTX 1650 4gb*
- ##### RAM: *16gb*

### Game State

The game runs fine, for the most part, No Audio issues or Graphical problems during normal gameplay.

The only issue is the Menu flickering to black like the demo. However, when you save and exit to the title screen, the issue is gone.

Upscaling to 2x is fine.

### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/107001229/4c9aecdc-95a5-4f58-b43e-9d9fd6787b66)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/107001229/0da6e0f7-2fac-4cc5-9aff-e888c79600c1)

### Log File

[Ryujinx_1.1.966_2023-07-21_01-24-40.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12114761/Ryujinx_1.1.966_2023-07-21_01-24-40.log)

**Comment by Ritaku02** [comment]
The game seems to hang on me at random. So far, it's managed to get past the hang, but every time I worry it's going to crash. Also, one time, most objects on-screen suddenly went very bright, including my character. It hasn't happened again, and I wish I got a screenshot of it when it did. When it happened, I was wandering around the starting area.

Hardware Specs
Ryzen 7 5800X3D
32GB DDR4-3200
RTX 2070 8GB

Ryujinx Build 1.1.968

**Comment by mrtnptrs** [comment]
> The game seems to hang on me at random. So far, it's managed to get past the hang, but every time I worry it's going to crash. Also, one time, most objects on-screen suddenly went very bright, including my character. It hasn't happened again, and I wish I got a screenshot of it when it did. When it happened, I was wandering around the starting area.
> 
> Hardware Specs Ryzen 7 5800X3D 32GB DDR4-3200 RTX 2070 8GB
> 
> Ryujinx Build 1.1.968

A log file would be handy here :)

**Comment by Ritaku02** [comment]
Here ya go, plus pics of the bloom getting extra bright. Sorry it took a bit, was trying to reproduce the hang because previous log files were lost.
https://www.dropbox.com/s/qdqhjyfu5igov0z/Ryujinx.Ava%202023-07-22%2012-24-12.png?dl=0
https://www.dropbox.com/s/5udhi7540c5dxw0/Ryujinx.Ava%202023-07-22%2012-24-19.png?dl=0
https://www.dropbox.com/s/taokkye3jncaxk5/Ryujinx.Ava%202023-07-22%2012-24-30.png?dl=0
https://www.dropbox.com/s/n5p864qrhixtsr9/Ryujinx.Ava%202023-07-22%2012-24-38.png?dl=0
https://www.dropbox.com/s/5m5y9di8jwtga73/Ryujinx.Ava%202023-07-22%2012-26-36.png?dl=0
[Ryujinx_1.1.968_2023-07-22_11-27-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12137140/Ryujinx_1.1.968_2023-07-22_11-27-49.log)

**Comment by ThatGuyUSA** [comment]
Hi! It seems to run quite well however it does pause briefly every so often during game play like stated earlier by Ritaku02. I have another issue though, when on the surface various elements all flash in unison as seen [here](https://youtu.be/4AHvnskmtu8) (rapid flashing warning). I don't have video of this part but the flashing seem to happen more often the longer I played. Near the end of the session all of the effected scenery would non-stop flash between various colors rapidly.

In the caves the flashing seems to not be present, but the pausing does still happen occasionally.

My specs:
CPU -  AMD Ryzen 5 3600X 3.8 GHz 6-Core Processor
Memory - Corsair Vengeance LPX 16 GB (2x8) DDR4-3200 CL16
GPU - NVIDIA RTX 3070TI Founders Edition (8GB)

[Ryujinx_1.1.968_2023-07-23_02-14-19.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12138492/Ryujinx_1.1.968_2023-07-23_02-14-19.log) Log of the short session shown in the video

**Comment by Jomanakk** [comment]
> Here ya go, plus pics of the bloom getting extra bright. Sorry it took a bit, was trying to reproduce the hang because previous log files were lost. https://www.dropbox.com/s/qdqhjyfu5igov0z/Ryujinx.Ava%202023-07-22%2012-24-12.png?dl=0 https://www.dropbox.com/s/5udhi7540c5dxw0/Ryujinx.Ava%202023-07-22%2012-24-19.png?dl=0 https://www.dropbox.com/s/taokkye3jncaxk5/Ryujinx.Ava%202023-07-22%2012-24-30.png?dl=0 https://www.dropbox.com/s/n5p864qrhixtsr9/Ryujinx.Ava%202023-07-22%2012-24-38.png?dl=0 https://www.dropbox.com/s/5m5y9di8jwtga73/Ryujinx.Ava%202023-07-22%2012-26-36.png?dl=0 [Ryujinx_1.1.968_2023-07-22_11-27-49.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12137140/Ryujinx_1.1.968_2023-07-22_11-27-49.log)

Ok, this one is actually new to me, another one of the bugs I've never noticed, can you tell me your GPU/CPU?

**Comment by Ritaku02** [comment]
I listed them in my post before that, but here; 

Ryzen 7 5800X3D
RTX 2080 8GB on latest driver

**Comment by Jomanakk** [comment]
> I listed them in my post before that, but here;
> 
> Ryzen 7 5800X3D RTX 2070 8GB with driver 536.40

Then it might be an AMD issue.

**Comment by Ritaku02** [comment]
Don't see how, my video card is an Nvidia card. An AMD issue would imply an AMD GPU, not CPU.

**Comment by oroussel** [comment]
Hello,
At least for the weird "extra-colorful bloom" effect, this is not an AMD-only issue:

CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
GPU: NVIDIA GeForce GTX 1070 with Max-Q Design (Vulkan v1.3.236, Driver v531.79.0.0)

See eg. the two (partial) screenshots, and the full log.

![Capture](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2471984/3439c1a3-5d81-4807-b414-a82f3414f83f)
![Capture2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2471984/afe8a9e8-b55e-4616-824f-6a4c4bdaf7fb)
[Ryujinx_1.1.968_2023-07-24_13-50-17.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/12145818/Ryujinx_1.1.968_2023-07-24_13-50-17.log)

This effect appears randomly, albeit rarely. Only happened thrice in about ~10h of game.
Effect impact most (but not all!) meshes in the scene. See eg. in the screenshots, the green leafs or yellow dandelion are unaffected, but the random junk & twig on the ground is.
No specific action of event seems to trigger it, at first view. It can happen just while exploring the world, not doing any action. It happened also on several maps, and several times of day.
The "intensity" of the bloom is not always constant: sometimes it's very light, sometimes so strong the whole screen becomes almost all white.

Going to the menu does not fix the issue, but going to a cave, or ending the day seems to fix the issue.

**Comment by Jkosio23** [comment]
The flashing colors is not random! It's tied to the 'time of day' shader from what i've noticed! going away during the middle of the day but being prominent at the start and end

**Comment by GamerzHell9137** [comment]
### Game Name

Pikmin 4

### Game Update Version

1.0.1

### Emulator Build Version

1.1.969

### Graphics Backend

Vulkan and OpenGL

### Hardware Specs

- ##### CPU: *Ryzen 3600*
- ##### GPU: *NVIDIA RTX 3060 TI*
- ##### RAM: *16GB*

### Game State

A full playtrough is possible to be done but with some emulation bugs:

1. The video on main menu is skipping frames and going black (Issue not present in OpenGL)

https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/67dece36-256f-4ca4-94c5-63062a932d61

3. In game tutorial videos have a rainbow line underneath them

https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/d0a47145-4c5d-445d-9342-c5328d5a84cb


4. While videos are playing there's a chance that the game freezes for couple of seconds (the FPS goes to 0) (Sometimes freezes happen during gameplay too but extremely rare)

5. Areas that are not visited in the hub have weird block artifacts

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/9714fc1c-3d00-49cc-abe9-03189b430223)

6. Rarely game crashes during loading/saving

```
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Ryujinx.Graphics.Vulkan.PersistentFlushBuffer.GetTextureData(Ryujinx.Graphics.Vulkan.CommandBufferPool, Ryujinx.Graphics.Vulkan.TextureView, Int32)
   at Ryujinx.Graphics.Vulkan.TextureView.GetData()
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper+<>c.<InitLookup>b__5_1[[Ryujinx.Graphics.GAL.Multithreading.Commands.Texture.TextureGetDataCommand, Ryujinx.Graphics.GAL, Version=1.1.969.0, Culture=neutral, PublicKeyToken=null]](System.Span`1<Byte>, Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer, Ryujinx.Graphics.GAL.IRenderer)
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(System.Threading.ThreadStart)
   at Ryujinx.Ui.RendererWidgetBase.Render()
```

7.  Cubemaps can break during gameplay, can be easily triggered with upscaling on and in the 3rd stage of the game. Game is played on native resolution without mods so its not an only upscaling issue.

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/b694f31f-7613-4466-9478-2ce831f4b503)

8. 3D objects are flashing in and out of existence when looked at a certain angle with the camera (Issue not present in OpenGL)

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/667ca59c-dd70-48db-9789-f939e94b39bc)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/9c98aa0f-45e6-4b70-8b77-dc88e4459e78)

https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/334aec06-a2e1-44e8-8521-d40c90d530d9

9. Game FPS goes to 0 and hangs for a while when accessing Olimar's Shipwreck Tale

https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/239f0778-3169-42c1-9fcf-833f4bdc8a01

10. [OpenGL only issue] Enviorment is flashing in different colors

https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/b5493706-c603-4e85-b472-da4c22bb6859


### Screenshots
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/04d67274-6d73-418d-8739-cd221a000986)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/0af35ea9-228b-4d1b-a89f-5f6917923d6f)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/169d460c-1cea-4bf5-8826-104ef52eea27)

### Log File

N/A

**Comment by jcm93** [comment]
Hi, in reference to this issue from upthread:

https://private-user-images.githubusercontent.com/2002038/256787287-67dece36-256f-4ca4-94c5-63062a932d61.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTI0NzAsIm5iZiI6MTcwNTcxMjE3MCwicGF0aCI6Ii8yMDAyMDM4LzI1Njc4NzI4Ny02N2RlY2UzNi0yNTZmLTRjYTQtOTRjNS02MzA2MmE5MzJkNjEubXA0P1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMDA1NjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzVjM2NkNjI0NmY3MGUyNjUzOTc5OWYwMTU3NTk5Mzg1OWFhMmUxYzhlYWE0YjQ3NzZlOWQxZGUzN2Q1OGNkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EjYd2Dfu_BdRQ2VsulP3AXtKZaVUtua8Lj3GObD9rIM

I've discovered that, at least on macOS arm64, this issue seems to have been caused by https://github.com/Ryujinx/Ryujinx/commit/dcf10561b996cdba111c5a3c3fe128781ab44021 and is not present in prior builds.

**Comment by Prophet32899** [comment]
This happens rarely, the first time it happened is when Oatchi jumped ontop of a flarlic randomly, then the second time this happened is when I entered sublevel 2 of Drafty Galley. 
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/159637587/71e7136b-1693-478c-89e1-74b4a62eaa99)

**Comment by Prophet32899** [comment]
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/159637587/d86fea11-14ed-4998-9587-b6a43299919f)
The version is the latest update, 1.0.2. this is the first time this happened to me but whenever I look behind a wall that has a startle spore plant behind it, this happens. It flashes, and Its pretty seizure-inducing. Please, fix this.

**Comment by WhiteDust87** [comment]
Does anyone have the link or file to download the Pikmin 4 for Ryujinx??

**Comment by JuanTheGamer8033** [comment]
I don’t know what is causing this, but everything got white and black, and super bright too. Can anyone please help me, or Atleast find a solution?
![IMG_6745](https://github.com/Ryujinx/Ryujinx-Games-List/assets/135474928/887026b3-ee3b-4515-934c-29555569f79c)

**Comment by MultiKoopa** [comment]
There's also the problem with the map getting corrupted (like the map screen); parts of the map you've cleared will suddenly be re-covered randomly with a bunch of Cross/Plus shaped things; this wouldn't matter much, except it completely destroys the "Go Here" functionality because you can't select anything on the map to go to if it's covered by the random crosses.

Don't have a screenshot because I'm not using Ryujinx for this game anymore after that map glitch
