### ISSUE TITLE
Hogwarts Legacy 0100F7E00C70E000

### ISSUE THREAD

**Issue by Defaalt** [Ryujinx/Ryujinx-Games-List#4809]
### Game Name

Hogwarts Legacy

### Game Update Version

v65536 - 1.01

### Emulator Build Version

Latest build 1.1.1080

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *8-core*
- ##### GPU: *Apple M1*
- ##### RAM: *8GB*

### Game State

Light flickering and textures applied weirdly. 

### Screenshots

https://github.com/Ryujinx/Ryujinx-Games-List/assets/91022358/1633f090-567b-4418-a4a8-708b250db6cc

**Comment by Defaalt** [comment]
Note : The 1.1.1065 build fixes some of the textures and color grading but the light flickering is still persistent. 
Not recommended for people with epilepsy

**Comment by GamerzHell9137** [comment]
> Note : The 1.1.1065 build fixes some of the textures and color grading but the light flickering is still persistent. Not recommended for people with epilepsy

1.1.1065 literally does nothing about the textures in game.

**Comment by Defaalt** [comment]
It's a consistent 30fps even for my config. The game runs fine but the textures/colorgrading and the flickering is annoying and I cannot go any further in the game with it.

**Comment by appvitor** [comment]
[Ryujinx_1.1.1080_2023-11-13_23-08-48.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13355189/Ryujinx_1.1.1080_2023-11-13_23-08-48.log)
[Ryujinx_1.1.1080_2023-11-14_00-00-10.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13355190/Ryujinx_1.1.1080_2023-11-14_00-00-10.log)
[Ryujinx_1.1.1080_2023-11-14_16-28-36.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13355191/Ryujinx_1.1.1080_2023-11-14_16-28-36.log)

Using the Lumos charm allows you to go further into the game. It is very weird, clear spaces are dark and this metallic effect is present on everything. Natural light becomes complete white in inner spaces. 
Revelio makes the light glitch activate and persistently flashes, going back to the main menu is the only way to make it stop.

**Comment by Niwu34** [comment]
### Game Name
 
Hogwarts Legacy
### Game Update Version
 
v65536 - 1.01
### Emulator Build Version
 
Latest build 1.1.1080
### Graphics Backend
 
Vulkan
### Hardware Specs
 
    * ##### CPU: _I5 13600K_
 
    * ##### GPU: _Nvidia 3090_
 
    * ##### RAM: _32GB_
 
 
### Game State
 
Performance is great: the game runs at 30 fps & uses dynamic framerate

Visually there are some glitches:
Hogwarts Legacy makes use of bindless textures which causes a lot of missing textures on the latest master build (See Screenshots)
Using the following PR: https://github.com/Ryujinx/Ryujinx/pull/3001 this issue mainly gets eliminated.
There are still has some lighting issues which can be reproduced by using the `Lumos Spell` a few times in a row. (shown in video).

The Log indicated that the `Ram` & `Sam` shader instructions are notimplemented yet:
`00:00:37.179 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Sam is not implemented.`
`00:00:37.179 |W| GPU.MainThread Gpu Log: Shader translator: Shader instruction Ram is not implemented.`

The following crash occured to me while testing so far:
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/67392333/8a01750a-b31f-42f4-842b-453a68b4c8c1)

The game will also crash when Guest Internet Access is enabled before it can get to the menu:

````00:00:26.552 |E| HLE.OsThread.43 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.AccountService.IManagerForApplication: 150

Guest Stack Trace:
Process: Service, PID: 120

Buffer Information:
        PtrBuff:
        [0] Position: 0x0000006556c00000 Size: 0x0000000000000200

Raw Request Data:
00000000   01 00 14 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  96 00 00 00 00 00 00 00   SFCI····?·······
00000020   00 10 00 00 00 00 00 00  00 00 00 00               ············

   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()
   at Ryujinx.HLE.HOS.Services.ServerBase.Main()
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.AccountService.IManagerForApplication: 150

Guest Stack Trace:
Process: Service, PID: 120

Buffer Information:
        PtrBuff:
        [0] Position: 0x0000006556c00000 Size: 0x0000000000000200

Raw Request Data:
00000000   01 00 14 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  96 00 00 00 00 00 00 00   SFCI····?·······
00000020   00 10 00 00 00 00 00 00  00 00 00 00               ············

   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context)
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr)
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop()```

```00:00:17.031 |I| HLE.OsThread.43 ServiceNifm GetCurrentNetworkProfile: Console's local IP is "192.168.178.108".
00:00:17.041 |I| HLE.OsThread.43 ServiceNifm GetCurrentNetworkProfile: Console's local IP is "192.168.178.108".
00:00:17.043 |I| HLE.OsThread.43 ServiceSfdnsres GetHostByNameRequestImpl: Trying to resolve: phoenix-api.wbagora.com
00:00:17.070 |I| HLE.OsThread.43 ServiceSfdnsres GetHostByNameRequestImpl: Trying to resolve: phoenix-api.wbagora.com
00:00:17.079 |W| HLE.OsThread.5 ServiceBsd SetSocketOption: Unsupported SetSockOpt Option: SoNoSigpipe Level: Socket````

https://github.com/Ryujinx/Ryujinx/issues/2997

### Screenshots
![0 5](https://github.com/Ryujinx/Ryujinx-Games-List/assets/67392333/6bd875dd-d5de-4a87-9b7f-757d2289f326)
Master:
![1](https://github.com/Ryujinx/Ryujinx-Games-List/assets/67392333/d413f4b2-f6ba-4e7d-b13d-39bfabd331a6)
PR 3001:
![2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/67392333/2b02e84a-4761-43b1-8d76-287b4e9604c2)
Lumos:
https://streamable.com/vbrf0y
https://streamable.com/olyb9u

### Log File
 
_No response_

**Comment by appvitor** [comment]
With 1.1.1083 the glitch caused by Revelio is almost fixed, but the lighting flashes still continues to happen.

[Ryujinx_1.1.1081_2023-11-14_17-52-42.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13361178/Ryujinx_1.1.1081_2023-11-14_17-52-42.log)
[Ryujinx_1.1.1081_2023-11-15_02-56-43.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13361179/Ryujinx_1.1.1081_2023-11-15_02-56-43.log)
[Ryujinx_1.1.1083_2023-11-15_02-56-58.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13361180/Ryujinx_1.1.1083_2023-11-15_02-56-58.log)

**Comment by appvitor** [comment]
Version 1.1.1087 hasn't showed a lot of differences, but try to avoid casting Revelio while using Lumos. Sometimes for no reasons the light flashes start by just crossing windows with the camera in movement.

[Ryujinx_1.1.1087_2023-11-15_23-14-08.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13371944/Ryujinx_1.1.1087_2023-11-15_23-14-08.log)
[Ryujinx_1.1.1087_2023-11-15_23-22-14.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13371945/Ryujinx_1.1.1087_2023-11-15_23-22-14.log)
[Ryujinx_1.1.1087_2023-11-16_00-38-29.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13371946/Ryujinx_1.1.1087_2023-11-16_00-38-29.log)

**Comment by yogithesymbian** [comment]
in world maps sometimes freeze sometimes smooth 30 fps in another area i got 40 fps with disable vsync .
> after 10 or 30 second freeze at moment, then smooth again . 

  **Macbook pro m1 ( 8GB ) ( Apple m1 base )** 
`RyujinX V1.1.1093`

**Comment by bprn** [comment]
Me too. I use Ryujinx with version build 1.1.1094 , the game has the problem with lighting so I should use Lumos every time to explore the Hogwarts. Some texture also missing and it only show black glitch. I got 30fps but the game is not playable without use Lumos spell.

**Comment by SashaBaych** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/assets/112338108/a7d3fbff-c8e3-4154-a00b-ab159baea7e9

Significant flickering  and wrong texture application. 
Playable, but not really enjoyable. 

M1 Pro Max, 64 GB, Sonoma 14.1.2

RyujinX V1.1.1098
System version 17.0.0
Default settings. Tried tinkering a lot with graphics settings and v-sync, but nothing helped.

**Comment by ParanoidHitman** [comment]
Hogwarts legacy black textures seem fixed, but lighting crashs sometimes, even playing.
Something about the layers and textures failure, seems playable, but has lots of freezes and eats lots of ram since new AVA, incomparison with GTK.

**Comment by bprn** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/assets/47177201/1e944a74-c8b6-4ec1-bf92-f6a6a2495def

Hogwart legacy Black texture issue seems has been fixed and running well / playable in my PC without crash. All texture in game is now visible without appearance of black texture. But it looks like that in some scene where player in dark background or when use lumos, there is still has issue where the game screen flickering. This flickering is very annoying if you use/spell  lumos.

RyujinX v.1.1.1292 System version 17.0.0
Windows 11 (v10.0.22631) Intel i7, 32GB, NVidia GTX 1650

**Comment by ParanoidHitman** [comment]
Still has problems with lighting, specially with lumos and some spells it just drops crazy frames when casting spells.. still when turning camera fast, has some lines texture failure. I’m with firmware 18.0.0, tried 17.0.0 same issues on nvidia GTX 1660 TI

**Comment by GamerzHell9137** [comment]
### Game Name

Hogwarts Legacy

### Game Update Version

v1.0.2

### Emulator Build Version

1.1.1297

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 3600*
- ##### GPU: *NVIDIA RTX 3060 TI*
- ##### GPU Driver version: *551.76*
- ##### RAM: *16GB*

### Game State

Game runs with couple of graphical issues.

> [!NOTE]  
> The Lumos spell whenever its used flashbangs the screen . Another issue is the fog effect on dust is flickering and not rendering properly.

Lumos and dust bug:

https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/b93f9f03-41fc-40e7-a463-638751ebde0a

### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/9e98a2f5-cb2a-4327-b6de-f161d5d630aa)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/01da1f12-d414-4c56-abde-2e41f3d61905)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/ef9092d4-be76-4293-a524-e23ba06a07a3)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/6097e52b-0975-4853-8ab6-11811c225ae3)


### Log File

_No response_

**Comment by bprn** [comment]
GPU.MainThread Gpu GetInfo: Invalid texture format 0x25A5A (sRGB: True).

I Use Ryujinx 1.1.1298 on my Windows 11 PC with Intel i7.
Black texture issue has been solved and didnt appeared.  But if we use spell Revelio or Lumos, it can cause screen flickering and there is a glitch on current main character wand, like a distorted lamp. If we check Ryujinx logs then it will show error with message : **" GPU.MainThread Gpu GetInfo: Invalid texture format 0x25A5A (sRGB: True)."**
Check this recorded video:

https://github.com/Ryujinx/Ryujinx-Games-List/assets/47177201/1959cc2f-65e1-48ed-a752-75579dd22928

and here is my ryujinx logs file with error message **" Invalid texture format 0x25A5A (sRGB: True)"**

[Ryujinx_1.1.1298_2024-05-09_13-15-00.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/15258513/Ryujinx_1.1.1298_2024-05-09_13-15-00.log)

**Comment by Kupo91** [comment]
I updated from v1.0.1 to v1.0.3. While v1.0.1 is loading with no problems, v1.0.3 is crashing after compiling shaders.
[Ryujinx_1.1.1336_2024-06-22_16-31-56.log](https://github.com/user-attachments/files/15937110/Ryujinx_1.1.1336_2024-06-22_16-31-56.log)

**Comment by bprn** [comment]
> I updated from v1.0.1 to v1.0.3. While v1.0.1 is loading with no problems, v1.0.3 is crashing after compiling shaders. [Ryujinx_1.1.1336_2024-06-22_16-31-56.log](https://github.com/user-attachments/files/15937110/Ryujinx_1.1.1336_2024-06-22_16-31-56.log)

me too. v1.0.3 is depend on switch firmware at least 18.0.1 , so you should upgrade your switch firmware. and the second, it is caused by shop access service which is not implemented or missing in ryujinx. 
I have tried ignore missing service configuration but the game still error. There is a bug need consent in ryujinx development about this shop service not implemented.
But for current condition, we should play v1.0.2 which is still supported or downgraded from v1.0.3 to v1.0.2.

**Comment by Kupo91** [comment]
> > I updated from v1.0.1 to v1.0.3. While v1.0.1 is loading with no problems, v1.0.3 is crashing after compiling shaders. [Ryujinx_1.1.1336_2024-06-22_16-31-56.log](https://github.com/user-attachments/files/15937110/Ryujinx_1.1.1336_2024-06-22_16-31-56.log)
> 
> me too. v1.0.3 is depend on switch firmware at least 18.0.1 , so you should upgrade your switch firmware. and the second, it is caused by shop access service which is not implemented or missing in ryujinx. I have tried ignore missing service configuration but the game still error. There is a bug need consent in ryujinx development about this shop service not implemented. But for current condition, we should play v1.0.2 which is still supported or downgraded from v1.0.3 to v1.0.2.

Thank you for clarifying this. I downgraded to v1.0.2 and now I'm able to successfully load the game again.
Hopefully this shop service will be fixed in the future.
Kind regards

**Comment by matiashuarta** [comment]
CPU: i7 14700
RAM: 32GB
GPU: RTX 4060 Ti

In current version 1.1.1370 I get these texture errors, along with 1FPS "cutscenes" prior to have control of the character:

![1](https://github.com/user-attachments/assets/8f5bbea3-d0f8-4e9d-bc60-a655007a492f)

Any advise for this?

**Comment by tomxhachijuroku** [comment]
**Game Name**
Hogwarts Legacy

**Game Update Version**
v1.0.4

**Emulator Build Version**
1.1.1372

**Graphics Backend**
Vulkan

Hardware Specs

- CPU: i7-11800H @ 2.30GHz
- GPU: NVIDIA GeForce RTX 3060 Laptop GPU
- GPU Driver version: 560.81
- RAM: 16GB

**Game State**
The game crashes on loading with the latest update v1.0.4, works fine with older updates.

**Screenshot**
![game crash](https://github.com/user-attachments/assets/47bdb64f-e1cb-485a-be8b-ccf344bd3785)

**Log File**
[Ryujinx_1.1.1372_2024-08-06_18-30-46.log](https://github.com/user-attachments/files/16513205/Ryujinx_1.1.1372_2024-08-06_18-30-46.log)

**Comment by RobertCat** [comment]
> CPU: i7 14700 RAM: 32GB GPU: RTX 4060 Ti Game Version: 1.0.2
> 
> In current version 1.1.1370 I get these texture errors, along with 1FPS "cutscenes" prior to have control of the character:
> 
> ![1](https://private-user-images.githubusercontent.com/107086769/354959526-8f5bbea3-d0f8-4e9d-bc60-a655007a492f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjY5MDYsIm5iZiI6MTcyNDkyNjYwNiwicGF0aCI6Ii8xMDcwODY3NjkvMzU0OTU5NTI2LThmNWJiZWEzLWQwZjgtNGU5ZC1iYzYwLWE2NTUwMDdhNDkyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxMDE2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTIxOTJkY2Q4MjgwOGNlOGU2ZjIwNjE5MzNjZWYxOTg1ZDhjMTZiMTRmYmMzNDE1OWQzMzVlNDFiZWFiNDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L0BHi4gSSA8DHnroXqsq_-J3pkd9oCHTIzuPzdZIBF4)
> 
> Any advise for this?

I have the same isue with Ryzen 5 3600 +16G + radeon 5600xt 6G (last gpu driver)
I played a lot in settings but with no luck.

**Comment by bprn** [comment]
The game is too slow to be played on Ryujinx for Update 1.0.4 . When playing the game , the performance become too slow. 
I think latest Ryujinx version is not optimized yet for update 1.0.4. 
Also latest version of Ryujinx 1.1.1382 has performance issue if I played with old version of hogwart legacy, some place in game become not playable.

**Comment by viksmir** [comment]
A regression appears to have been introduced into the code in the past 2 weeks. In-building environments are now not renderred and the buffers appear to be not clearing between draw calls. This results in nothing but bright light accumulating in the frame buffer, eventually blinding you completely.

CPU: Ryzen 5800X3D
GPU: RTX 3090 24GB
Game Version: 1.0.2
Ryujinx version: 1.1.1385

![bug](https://github.com/user-attachments/assets/28e645d3-fed9-4b81-8478-31e758584c3f)
