### ISSUE TITLE
Princess Peach: Showtime! - 01007A3009184000

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx-Games-List#4907]
### Game Name

Princess Peach: Showtime!

### Game Update Version

1.0.0

### Emulator Build Version

1.1.1240

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: AMD Ryzen 9 7900X3D
- ##### GPU: AMD RX 6600 XT
- ##### GPU Driver version: Mesa 24.0.3
- ##### RAM: 64GB

### Game State

Game is playable, from discord reports there seems to be some resolution scaling issue in docked mode it doesn't seem to scale in docked mode at all, i didn't see it at all

### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/100526773/328a3274-2476-4fa9-86ae-967a001a4a2d)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/100526773/4491183a-a672-4dad-bccf-4f49297c7013)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/100526773/2138220d-7130-44c6-a7d7-81b735d5f069)

**Comment by CapitaineNemo13** [comment]
W11
CPU: i5-13600KF
GPU: RTX 4070 
Ram: 64 go 

game completed 100%
Runs perfectly at 60 fps by disabling Vsync and blocking the max framerate at 60 in the Nvidia settings
Just at the “Detective 2” level you have to reactivate Vsync/30fps at the start because a character gets stuck at 60 fps as if facing an invisible wall

**Comment by CyanRyan** [comment]
Emulator Build Version: 1.1.1244
Game Version: 1.0.0
CPU: R5 5600X
GPU: RTX 3060 Ti
RAM: 32 gb

Consistently crashes on launch when other games don't. Gives error:

<code>00:00:57.346 |E| HLE.GuestThread.53 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000003.
00:00:57.381 |E| HLE.GuestThread.53 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\MemoryBlock.cs:line 440
   at Ryujinx.Cpu.Jit.MemoryManager.WriteGuest[T](UInt64 va, T value) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManager.cs:line 219
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
   at System.Threading.Thread.StartCallback()</code>

**Comment by kipusoep** [comment]
So do you guys have any clue about why I can't get passed the loading screen (stage with the closed curtains)?

**Comment by wushatn33n** [comment]
Emulator Build Version: 1.1.1244
Game Version: 1.0.0
CPU: R5 5600
GPU: RX 580
RAM: 32 GB
Windows 10

Vulkan: Stable 60 fps with VSync off/mod with major graphical artifacts in the form of constantly flashing textures.
OpenGL fixes most of artifacts but severely degrades performance(10-15 in action scenes).

**Comment by piplup55** [comment]
Game fails to boot with the sdl2 backend on some cpu's, switching to OpenAL seems to fix this

**Comment by jimmyshiau** [comment]
* Stuck here, any idea?
![碧姬公主 表演時刻！_2024-03-31_07-37-01](https://github.com/Ryujinx/Ryujinx-Games-List/assets/1056469/36e55e81-0c41-42e4-b891-6b4abfaddd3a)

**Comment by gbqgbq** [comment]
Please also switch to 30 FPS to play normally

**Comment by jimmyshiau** [comment]
> Please also switch to 30 FPS to play normally

It works, thanks!!

**Comment by jaimerave** [comment]
Emulator Build Version: 1.1.1249
Game Version: 1.0.0
CPU: i5 8500
GPU: RX 6500 XT
RAM: 16 GB
Windows 11

The game is crashing for me with the following backtrace:

```
00:00:44.464 |I| HLE.GuestThread.53 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Princess Peach: Showtime!, PID: 125
   0x000000000abcb884	main:0x26c7884	
   0x0000000014497518	sdk:0x12a518	
   0x000000001449d2f4	sdk:0x1302f4	
   0x0000000000000000


00:00:44.468 |I| HLE.GuestThread.53 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000001800aac480
	X[01]:	0x00000000fffffffe
	X[02]:	0x0000000000000000
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000001
	X[09]:	0x0000000000000000
	X[10]:	0x0000000000000000
	X[11]:	0x0000001800aac4c8
	X[12]:	0x0000000000000000
	X[13]:	0x000000000000001e
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000000
	X[16]:	0x0000000015075318
	X[17]:	0x000000001449e804 (sdk:0x131804)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Leave()
	X[18]:	0x0000000000000001
	X[19]:	0x0000001800aac480
	X[20]:	0x0000000012be9a38
	X[21]:	0x0000000000000000
	X[22]:	0x0000001800aac490
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000000
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x0000004a20e40f40 (SP:-0x0010)
	LR:	0x000000000ac2c804 (main:0x2728804)	=> 
	SP:	0x0000004a20e40f30 (SP)
	PC:	0x000000000ac2c708 (main:0x2728708)	=> 


00:00:44.468 |E| HLE.GuestThread.53 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
```

**Comment by ZielonoBluzy** [comment]
where can i  download this?

**Comment by taylor85345** [comment]
Getting a consistent crash on Steam Deck during the transformation cutscene of patisserie-1, just as the screen goes white:

```
00:09:54.904 |E| HLE.OsThread.2 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.     ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!                                                                             at LibHac.Common.ThrowHelper.ThrowResult(Result result, String message)                   at LibHac.Tools.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)                                           at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)                         at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)             at LibHac.Tools.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count)     at System.IO.Stream.Read(Span`1)                                                          at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)             at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IStorage.cs:line 35                                                                                     at InvokeStub_IStorage.Read(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)                                                                        --- End of inner exception stack trace ---                                                at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)                                                                        at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Services/IpcService.cs:line 126                  at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 372                                                                                       at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 254                                        at Ryujinx.HLE.HOS.Services.ServerBase.Main() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Services/ServerBase.cs:line 172                                              at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1255                            at System.Threading.Thread.StartCallback()
```

**Comment by RupeeClock** [comment]
> Getting a consistent crash on Steam Deck during the transformation cutscene of patisserie-1, just as the screen goes white:
> ```
> 00:09:54.904 |E| HLE.OsThread.2 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> LibHac.Common.HorizonResultException: ResultFsNonRealDataVerificationFailed (2002-4604): Hash error!
> ```

Your game file is corrupted, you'll need to re-dump.

https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-crashing-after-booting-a-game-or-crashing-after-applying-an-update-with-e-hleosthread8-application--unhandled-exception-caught-systemreflectiontargetinvocationexception-exception-has-been-thrown-by-the-target-of-an-invocation-----libhaccommonhorizonresultexception-resultfsnonrealdataverificationfailed-2002-4604-hash-error

**Comment by datvm** [comment]
Everytime a level loads or when I exit the level (when the stage curtain is supposed to open), it's a 50/50 chance that it crashes. Luckily the game is saved. It's just a bit annoying I have to restart the app almost every level. Sometimes it happens right at the first level load, sometimes it crashes on the 2nd level I select.

**Comment by BParks21** [comment]
@RinMaru The frame pacing at 30fps in this game is downright broken on Nvidia as well. Has to run at 60 or higher to look decent.

**Comment by UwU990099** [comment]
Any idea why is it crashing at loading screen on my potato PC?

i5 4460
RAM 8GB
GTX 1050 2GB


Log (just before the crash)
00:01:56.669 |S| HLE.OsThread.47 ServiceAm SetScreenShotPermission: Stubbed. {screenShotPermission: True}
00:02:12.018 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:02:12.142 |S| HLE.OsThread.47 ServiceAm SetScreenShotPermission: Stubbed. {screenShotPermission: True}
00:02:13.018 |E| HLE.OsThread.4 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 5978 took more than 1000ms, resuming execution...
00:02:13.832 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:02:14.832 |E| HLE.OsThread.4 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 5981 took more than 1000ms, resuming execution...
00:02:15.117 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 517098 bytes, profiled functions: 193759).
00:02:15.391 |W| HLE.OsThread.4 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:02:17.328 |I| HLE.GuestThread.51 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Princess Peach: Showtime!, PID: 127
   0x000000000abcb884	main:0x26c7884	
   0x0000000014497518	sdk:0x12a518	
   0x000000001449d2f4	sdk:0x1302f4	
   0x0000000000000000


00:02:17.348 |I| HLE.GuestThread.51 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000001800aac480
	X[01]:	0x00000000fffffffe
	X[02]:	0x0000000000000000
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000000001
	X[09]:	0x0000000000000000
	X[10]:	0x0000000000000000
	X[11]:	0x0000001800aac5e0
	X[12]:	0x000000000000001e
	X[13]:	0x000000000000001e
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000000
	X[16]:	0x0000000015075318
	X[17]:	0x000000001449e804 (sdk:0x131804)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Leave()
	X[18]:	0x0000000000000001
	X[19]:	0x0000001800aac480
	X[20]:	0x0000000012be9a38
	X[21]:	0x0000000000000000
	X[22]:	0x0000001800aac490
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000000
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x0000004a20e40f40 (SP:-0x0010)
	LR:	0x000000000ac2c804 (main:0x2728804)	=> 
	SP:	0x0000004a20e40f30 (SP)
	PC:	0x000000000ac2c708 (main:0x2728708)	=> 


00:02:17.348 |E| HLE.GuestThread.51 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
