### ISSUE TITLE
New Super Lucky's Tale

### ISSUE THREAD

**Issue by r3ntonboy** [Ryujinx/Ryujinx-Games-List#493]
**New Super Lucky's Tale**

**Current on master :** 1.0.4093

Runs really slow. It has Vertex explosions.

**Screenshots :**
![1](https://user-images.githubusercontent.com/35672114/77860714-fa102400-71e6-11ea-8e96-02cb650e62ee.jpg)
![2](https://user-images.githubusercontent.com/35672114/77860721-0300f580-71e7-11ea-9939-02d082585e52.jpg)
![3](https://user-images.githubusercontent.com/35672114/77860726-085e4000-71e7-11ea-9649-776cd3e3b8e9.jpg)
![4](https://user-images.githubusercontent.com/35672114/77860731-0eecb780-71e7-11ea-9c03-273bed80d510.jpg)

**Log file :**

[New Super Luckys Tale.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4399772/New.Super.Luckys.Tale.zip)

**Comment by r3ntonboy** [comment]
**Current on master:** 1.0.4921

Crash after main menue

**Log file:**
[New Super Luckys Tale.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4913651/New.Super.Luckys.Tale.zip)

**Comment by r3ntonboy** [comment]
Current on master : 1.0.6896

The game now crash after "playful studios" logo.

Log file:
[Ryujinx_1.0.6896_2021-05-29_20-08-29.log.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/6565438/Ryujinx_1.0.6896_2021-05-29_20-08-29.log.zip)

**Comment by r3ntonboy** [comment]
Boxes are not being rendered. Yuzu for reference.
![Captura de pantalla 2021-10-09 212201](https://user-images.githubusercontent.com/35672114/136677145-bb1fc922-ec0f-45a8-8540-f0c9aad1aafe.jpg)
![Captura de pantalla 2021-10-09 212440](https://user-images.githubusercontent.com/35672114/136677146-83fd17f3-28f1-422d-9591-f9e24e3d82d7.jpg)

**Comment by RupeeClock** [comment]
Boxes identified as not rendering in Ryujinx v1.0.7066 appear to render correctly in Ryujinx v1.1.1102
![Ryujinx 1 1 1102 - New Super Lucky's Tale v1 4 2](https://github.com/Ryujinx/Ryujinx-Games-List/assets/24753760/678b04b3-6df9-45c5-9c9e-37b3c4c9e9f6)

However, the game is highly prone to crashing within a few seconds or few minutes of gameplay, producing logs to this effect:
```
00:06:17.948 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 281
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\Window.cs:line 443
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 449
   at System.Threading.Thread.StartCallback()
```

```
00:00:48.700 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 281
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 272
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 291
   at Ryujinx.Graphics.Vulkan.Window.Present(ITexture texture, ImageCrop crop, Action swapBuffersCallback) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\Window.cs:line 325
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 41
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Ui\RendererWidgetBase.cs:line 449
   at System.Threading.Thread.StartCallback()
```

**CPU**: 12th Gen Intel(R) Core(TM) i7-12700K 3.60 GHz
**GPU**: NVIDIA RTX 3070
**GPU Driver version**: 546.17 / 546.3.3
**RAM**: 32GB DDR5 (2x16gb)

Crashes occurred on game update versions v1.4.2 and v1.6.5.
See attached log files.
[Ryujinx_1.1.1102_2024-01-02_02-08-18.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13806701/Ryujinx_1.1.1102_2024-01-02_02-08-18.log)
[Ryujinx_1.1.1102_2024-01-02_02-00-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13806703/Ryujinx_1.1.1102_2024-01-02_02-00-44.log)
[Ryujinx_1.1.1102_2024-01-02_01-46-12.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/13806702/Ryujinx_1.1.1102_2024-01-02_01-46-12.log)

**Comment by HomeStarRunnerTron** [comment]
> However, the game is highly prone to crashing within a few seconds or few minutes of gameplay, producing logs to this effect:

Thank you SO much for these logs! It helped me figure out how to solve the crashing, at least for myself. All I had to do was turn off Graphics Backend Multithreading, Apply, then Restart the program. (I'm an M1 macOS running Monterey 12.5). Haven't experienced a crash since. (Also, to anyone who's playing this game, I highly suggest the [60fps patch](https://www.gamebrew.org/wiki/New_Super_Luckys_Tale_60_FPS_Mod_Switch)-- runs supe-y smooth.)

**Comment by RupeeClock** [comment]
Disabling Graphics Backend Multithreading on Ryujinx Version 1.1.1223 did seem to help alleviate the issue, but it did still ultimately crash after a few minutes of play.
Purging the shader caches generated from when it was enabled seemed to be necessary as well.

Logging showed large numbers of these warnings which I think coincide with loading screens between areas.
```00:07:56.687 |W| GUI.RenderThread Gpu Log: Shader translator: Failed to find storage buffer for global memory operation "Store".```

Here's the log file for the session I just tried, with the crash at the end:
[Ryujinx_1.1.1223_2024-03-11_13-53-22.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14559857/Ryujinx_1.1.1223_2024-03-11_13-53-22.log)

```00:09:22.844 |W| HLE.OsThread.8 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:09:23.845 |E| HLE.OsThread.8 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 182450 took more than 1000ms, resuming execution...
00:09:29.022 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 281
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 268
   at Ryujinx.Graphics.Gpu.Image.TextureManager.UpdateRenderTargets() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 431
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.Draw(ThreedClass engine, PrimitiveTopology topology, Int32 count, Int32 instanceCount, Int32 firstIndex, Int32 firstVertex, Int32 firstInstance, Boolean indexed) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 550
   at Ryujinx.Graphics.Gpu.Engine.MME.MacroHLE.DrawElements(IDeviceState state, Int32 arg0) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\MME\MacroHLE.cs:line 316
   at Ryujinx.Graphics.Gpu.Engine.MME.MacroHLE.Execute(ReadOnlySpan`1 code, IDeviceState state, Int32 arg0) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\MME\MacroHLE.cs:line 78
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoClass.CallMme(Int32 index, IDeviceState state) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoClass.cs:line 245
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 264
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 95
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 229
   at Ryujinx.Ava.AppHost.<RenderLoop>b__103_1() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 934
   at Ryujinx.Graphics.GAL.IRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\IRenderer.cs:line 54
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 918
   at System.Threading.Thread.StartCallback()```

During my play session, I tinkered with graphical settings (native or 2x resolution, toggling Vsync) to get a measure of performance, and noticed a fair bit of stutter whether it was capped at 30 FPS or 60 FPS. This might be attributed to exiting out of fullscreen a few times, as I've noticed pausing emulation briefly after doing any changes usually helps with this.
This was without the 60 FPS patch, as it wasn't compatible with my installation.
You can however simply disabling Switch VSync to uncap the framerate, and then use GPU control panel settings or RTSS to cap to your desired framerate.
