### ISSUE TITLE
ANIMAL WELL - 010020D01AD24000

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx-Games-List#4958]
### Game Name

ANIMAL WELL

### Game Update Version

1.0.2

### Emulator Build Version

1.1.1298

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: AMD Ryzen 9 7900X3D
- ##### GPU: RX 6600 XT
- ##### GPU Driver version: Mesa 24.0.6
- ##### RAM: 64gb

### Game State

game crashes before booting
```00:00:00.978 |W| Loader Load: No RomFS found in NCA```

nxdumptool can't see the romfs either
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/100526773/e72090c7-013f-4a99-a6ea-506682ca70cd)

### Log File

[Ryujinx_1.1.1298_2024-05-09_19-48-09.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/15266520/Ryujinx_1.1.1298_2024-05-09_19-48-09.log)

**Comment by F1ReB4LL** [comment]
Also version 1.0.2 is detected not as an update to version 1.0.0, but as a standalone title, not sure if it is correct or not.

**Comment by pwnedbygary** [comment]
Can confirm this with my Ryujinx install, running latest version. CTD every launch. I was able to get the updated version to show up as a single title by merging XCI + NSPs using SAK however.
![image_2024-05-10_132000814](https://github.com/Ryujinx/Ryujinx-Games-List/assets/488786/ebce1971-324a-4fdf-94b6-022a8af7c0dd)

**Comment by adr1um** [comment]
Yeah same issue here

**Comment by buggii** [comment]
The game seems to be just 1 executable file so probably the update contains the "full" updated game itself.

**Comment by plexecutor** [comment]
> The game seems to be just 1 executable file so probably the update contains the "full" updated game itself.

The update and the game itself are basically the same size as well which would corroborate this being the case.

**Comment by remutro** [comment]
1.0.3 version is out, still doesn't work with this version either. Just crashes Ryujinx when attempting to start the game.

**Comment by figgefigge** [comment]
Can confirm for 1.0.0, 1.0.2 and 1.0.3 on Linux. 
[Ryujinx_1.1.1298+a23d8cb92f3f1bb8dc144f4d9fb3fddee749feae_2024-05-13_23-49-05.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/15300342/Ryujinx_1.1.1298%2Ba23d8cb92f3f1bb8dc144f4d9fb3fddee749feae_2024-05-13_23-49-05.log)

**Comment by harrismcc** [comment]
Just to add here, having the same issues. Here are the application/crash logs:

```
00:00:00.048 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.055 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.055 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.056 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.057 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.058 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.058 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x731F
00:00:00.059 |I| Configuration LogValueChange: AntiAliasing set to: SmaaUltra
00:00:00.060 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.060 |I| Configuration LogValueChange: ScalingFilterLevel set to: 60
00:00:00.061 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.066 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.066 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.066 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.066 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.066 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.067 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.067 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.067 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.067 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.067 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.067 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.069 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.069 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.069 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.069 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.071 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.074 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1310
00:00:00.078 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.078 |N| Application Print: CPU: AMD Ryzen 7 3800X 8-Core Processor ; 16 logical
00:00:00.080 |N| Application Print: RAM: Total 31.9 GiB ; Available 26.5 GiB
00:00:00.082 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.082 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.121 |I| Gpu : Backend Threading (Auto): True
00:00:00.366 |N| Application LoadGuestApplication: Using Firmware Version: 17.0.0
00:00:00.366 |I| Application LoadGuestApplication: Loading as NSP.
00:00:00.382 |I| ModLoader QueryContentsDir: Searching mods for Application 010020D01AD24000 in "C:\Users[redacted]\AppData\Roaming\Ryujinx\mods\contents"
00:00:00.383 |I| ModLoader QueryContentsDir: Searching mods for Application 010020D01AD24000 in "C:\Users[redacted]\AppData\Roaming\Ryujinx\sdcard\atmosphere\contents"
00:00:00.385 |I| Loader Load: Loading rtld...
00:00:00.390 |I| Loader PrintRoSectionInfo: rtld:
Module: nnrtld
00:00:00.390 |I| Loader Load: Loading main...
00:00:00.749 |I| Loader PrintRoSectionInfo: main:
Module: C:\Users\bigdo\source\repos\BeanTech\NX64\Release\Animal Well.nss
SDK Libraries: SDK MW+Nintendo+NintendoSDK_gfx-17_5_3-Release
00:00:00.749 |I| Loader Load: Loading sdk...
00:00:00.797 |I| Loader PrintRoSectionInfo: sdk:
Module: nnSdk
FS SDK Version: 17.5.3
SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-17_5_3-Release
SDK MW+Nintendo+NintendoSdk_nnSdk-17_5_3-Release
SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
SDK MW+Nintendo+NintendoSDK_NVN-17_5_3-Release
00:00:00.888 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:00.912 |I| Loader LoadNsos: Loading image 0 at 0x0000000008500000...
00:00:00.913 |I| Loader LoadNsos: Loading image 1 at 0x0000000008505000...
00:00:01.066 |I| Loader LoadNsos: Loading image 2 at 0x000000002be9f000...
00:00:01.070 |I| ModLoader LoadCheats: Build ids found for application 010020D01AD24000:
CCD8D2E002A068EA0A32370756F3675E5D8363D5000000000000000000000000
2E7796A893CB510DF31E9957DAC554CEEFB65A04000000000000000000000000
311DEAB1F062B504F3D646A49DDCD4E86757F97B000000000000000000000000
00:00:01.072 |W| Loader Load: No RomFS found in NCA
00:00:01.072 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.117 |I| Loader Start: Application Loaded: ANIMAL WELL v1.0.0 [010020d01ad24000] [64-bit]
00:00:01.145 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:01.362 |N| GUI.RenderThread Gpu PrintGpuInformation: AMD AMD Radeon RX 5700 XT (Vulkan v1.3.270, Driver v2.0.294)
00:00:01.369 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:01.375 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:02.012 |S| HLE.OsThread.51 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:02.107 |S| HLE.OsThread.51 ServiceAm AcquireForegroundRights: Stubbed.
00:00:02.111 |S| HLE.OsThread.51 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:02.114 |S| HLE.OsThread.51 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:02.189 |S| HLE.OsThread.51 ServicePctl Initialize: Stubbed.
00:00:03.146 |W| GUI.WindowThread Hid Remap: No matching controllers found. Application requests 'ProController, Handheld, JoyconPair, JoyconLeft, JoyconRight' on 'Player1, Player2, Player3, Player4, Player5, Player6, Player7, Player8, Handheld'
00:00:04.322 |I| HLE.OsThread.51 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:04.324 |I| HLE.OsThread.51 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:04.387 |S| HLE.OsThread.7 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:04.389 |S| HLE.OsThread.7 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:04.390 |S| HLE.OsThread.7 ServiceHid SetTouchScreenResolution: Stubbed. {width: 1280 ; height: 720 ; appletResourceUserId: 1}
00:00:04.391 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:04.397 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:04.401 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 127 ; appletResourceUserId: 1 ; type: ProController, Handheld}
00:00:04.401 |S| HLE.OsThread.7 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:04.419 |W| HLE.OsThread.15 ServiceAudio GetWorkBufferSize: Library Revision REV12 is not supported!
00:00:04.445 |I| HLE.OsThread.51 ServiceAm SetTerminateResult: Result = 0x00000499 (2153-0002).
00:00:04.517 |I| HLE.GuestThread.50 Cpu PrintGuestStackTrace: Guest stack trace:
Process: ANIMAL WELL, PID: 127
0x000000002bf36e94 sdk:0x97e94
0x000000002bf36f48 sdk:0x97f48
0x000000002bf37028 sdk:0x98028
0x000000002c0834cc sdk:0x1e44cc
0x00000000085127fc main:0xd7fc
0x0000000008505e68 main:0x0e68
0x0000000008513a6c main:0xea6c nnMain:0x005c
0x000000002bfa41e4 sdk:0x1051e4 nn::init::Start(unsigned long, unsigned long, void ()(), void ()(), void (*)()):0x0054
0x00000000085000d8 rtld:0x00d8

00:00:04.518 |I| HLE.GuestThread.50 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
X[00]: 0x0000000000000000
X[01]: 0x0000004a10008510 (SP:-0x0200)
X[02]: 0x0000000000000004
X[03]: 0x0000000000000000
X[04]: 0x0000000000000000
X[05]: 0x0000000000000000
X[06]: 0x0000000000000000
X[07]: 0x0000000000000000
X[08]: 0x0000000100000000
X[09]: 0x000000002c9c3100
X[10]: 0x0000000100000000
X[11]: 0x0000000000000001
X[12]: 0x0000000000000000
X[13]: 0x0000000000000000
X[14]: 0x0000000000000000
X[15]: 0x000000000000000e
X[16]: 0x000000002c996c20
X[17]: 0x000000002bf387b0 (sdk:0x997b0) => nn::diag::detail::Abort(nn::Result const)
X[18]: 0x0000000000000000
X[19]: 0x0000004a10008510 (SP:-0x0200)
X[20]: 0x0000000000000000
X[21]: 0x000000002c742f50
X[22]: 0x000000002c742f50
X[23]: 0x0000000000000000
X[24]: 0x000000002c742f50
X[25]: 0x0000004a10008490 (SP:-0x0180)
X[26]: 0x000000002c742f50
X[27]: 0x000000002bf36f48 (sdk:0x97f48) =>
X[28]: 0x0000000000000000
FP: 0x0000004a10008310 (SP)
LR: 0x000000002bf387c8 (sdk:0x997c8) => nn::diag::detail::Abort(nn::Result const):0x0018
SP: 0x0000004a10008310 (SP)
PC: 0x000000002c001868 (sdk:0x162868) =>

00:00:04.527 |W| HLE.GuestThread.52 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:00:04.567 |E| HLE.GuestThread.50 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1933
at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 1807
at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\Ryujinx.Horizon.Kernel.Generators\Ryujinx.Horizon.Kernel.Generators.SyscallGenerator\SyscallDispatch.g.cs:line 3461
at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 38
at Ryujinx.Cpu.Jit.JitExecutionContext.SupervisorCallHandler(ExecutionContext context, UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 99
at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\State\ExecutionContext.cs:line 156
at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Instructions\NativeInterface.cs:line 50
at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 145
at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 40
at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 62
at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
at System.Threading.Thread.StartCallback()
```

**Comment by piplup55** [comment]
Locking until a developer takes a look at this game, since we already have more than comments saying the game doesn't work

**Comment by GamerzHell9137** [comment]
### Game Name

ANIMAL WELL

### Game Update Version

v1.0.2

### Emulator Build Version

1.1.1315

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 3600*
- ##### GPU: *NVIDIA RTX 3060 TI*
- ##### GPU Driver version: *551.76*
- ##### RAM: *16GB*

### Game State

Game working as intended

### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/fed5396c-f31e-4674-9639-0d867146e9e9)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/cf314ffc-3375-4739-b0d3-c4cc5e15187e)

### Log File
[Ryujinx_1.1.1315_2024-05-17_23-01-02.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/15358486/Ryujinx_1.1.1315_2024-05-17_23-01-02.log)

**Comment by buggii** [comment]
I can confirm that with v1.1.1316 the game works; version 1.0.3 stand alone file works too without the v0 version.

**Comment by muermo** [comment]
In Ryujinx v.1.1.1318 the game works. Standalone file version 1.0.4, without base game.
[Ryujinx_1.1.1318_2024-05-22_19-57-35.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/15407048/Ryujinx_1.1.1318_2024-05-22_19-57-35.log)
