### ISSUE TITLE
DOOM

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#499]
#### Current on `master` : 1.0.4093

Choppy audio during intro splash screen animation and the title screen. While at title screen, emulation crashes.

```
ServiceLm Log: Guest log:
 Log level: Info
 Line: 0
 Filename: ''
 Function: ''
 Module: ''
 Thread: 'Renderer'
 Message: 'RestartRenderThread called and renderer is not synced'

00:03:38.149 | HLE.HostThread.26 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at ARMeilleure.Memory.MemoryManager.WriteUInt32(Int64 position, UInt32 value) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 649
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 96
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1142
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 162
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-03-30 05_54_31-Ryujinx 1 0 4093 _ DOOM _ 0100416004C00000](https://user-images.githubusercontent.com/62343878/77909870-51e07680-724b-11ea-9a05-94530572f35d.png)
![2020-03-30 05_54_37-Ryujinx 1 0 4093 _ DOOM _ 0100416004C00000](https://user-images.githubusercontent.com/62343878/77909874-53aa3a00-724b-11ea-86d3-5924b67602e1.png)
![2020-03-30 05_54_53-Ryujinx 1 0 4093 _ DOOM _ 0100416004C00000](https://user-images.githubusercontent.com/62343878/77909876-53aa3a00-724b-11ea-8913-a7cb2d2edb66.png)
![2020-03-30 05_54_58-Ryujinx 1 0 4093 _ DOOM _ 0100416004C00000](https://user-images.githubusercontent.com/62343878/77909878-54db6700-724b-11ea-9085-b68385d461f5.png)
![2020-03-30 05_55_27-Ryujinx 1 0 4093 _ DOOM _ 0100416004C00000](https://user-images.githubusercontent.com/62343878/77909881-5573fd80-724b-11ea-8070-7e23a2aec34a.png)

#### Log file :

[DOOM.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4402495/DOOM.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Doctorwho1909** [comment]
in game things have changed the textures are now correct not sure which PR did it

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6846

**Comment by Djipi71** [comment]
Test on RyujiNX build 1.1.15

Version of the game : 1.0

Now go ingame , no graphical issues but it's extremely slow ....But after waiting some time without movement , go fullspeed. but if we move , slowdown to 4 fps again...

BUT there is two error code at the beginning of the game : Error 2002-6400 but not crashing the game start.

LOG:
[Ryujinx_1.1.15_2022-02-02_08-32-43.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7984455/Ryujinx_1.1.15_2022-02-02_08-32-43.log)

Screenshot:
![ryujinx_capture_2022-02-01_23-59-05](https://user-images.githubusercontent.com/35375131/152112194-80ffac52-c2fd-474c-887d-a2e35ed2b970.png)
![ryujinx_capture_2022-02-02_08-38-13](https://user-images.githubusercontent.com/35375131/152112759-88aa29cd-9605-48cf-b581-5a2b393600aa.png)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by C4N1SMAJ0R** [comment]
EmulationFanatic#
How do you pass the "accept terms" screen?
The controls here doesn't work.

**Comment by PrisedRabbit** [comment]
> EmulationFanatic# How do you pass the "accept terms" screen? The controls here doesn't work.

Any luck?

**Comment by x4080** [comment]
@C4N1SMAJ0R I got ps4 and still cannot click anything 😄

**Comment by DamnageMusic** [comment]
> > > EmulationFanatic# How do you pass the "accept terms" screen? The controls here doesn't work.
> > 
> > 
> > Any luck?
> 
> Nope... A guy on youtube say if u use a ps4 controller, for some reason you can accept the terms and pass for a new game. But, I only have a xbox one controller, so I can't confirm this... Anyway, I will still walting for a fix.

It's been a year now, has anyone figured this out yet?

**Comment by C4N1SMAJ0R** [comment]
> > > > EmulationFanatic# How do you pass the "accept terms" screen? The controls here doesn't work.
> > > 
> > > 
> > > Any luck?
> > 
> > 
> > Nope... A guy on youtube say if u use a ps4 controller, for some reason you can accept the terms and pass for a new game. But, I only have a xbox one controller, so I can't confirm this... Anyway, I will still walting for a fix.
> 
> It's been a year now, has anyone figured this out yet?

Nope
still not working...
