### ISSUE TITLE
Shin Megami Tensei V: Vengeance - 010069C01AB82000

### ISSUE THREAD

**Issue by time-axis** [Ryujinx/Ryujinx-Games-List#4991]
### Game Name

Shin Megami Tensei V

### Game Update Version

1.0.2

### Emulator Build Version

1.1.1332

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: i7 8700
- ##### GPU: NVIDIA GTX 1070
- ##### GPU Driver version: 32.0.15.5599
- ##### RAM: 16GB

### Game State

Appears playable but with flickering objects throughout. Played through the intro sequence up to when you first make it to the netherworld. The map screen flickers sometimes, and the main character flickers. This only happens with Vulcan, not OpenGL, although OpenGL is much slower.

### Screenshots

![SHIN MEGAMI TENSEI V_ Vengeance_2024-06-16_14-35-38](https://github.com/Ryujinx/Ryujinx-Games-List/assets/16064381/e12d59bc-944d-400e-abd3-2aa4d75d0b07)
![smtvflicker](https://github.com/Ryujinx/Ryujinx-Games-List/assets/16064381/b8204f41-221e-4731-aa39-58e85a6f4062)

### Log File

[Ryujinx_1.1.1333_2024-06-16_14-34-31.log](https://github.com/user-attachments/files/15859489/Ryujinx_1.1.1333_2024-06-16_14-34-31.log)

**Comment by Icarus170303** [comment]
Game Version: 1.0.1
Emulator Version: 1.1.1334
Backend: Vulcan

Specs:
CPU: Intel i5-9300H
Ram: 16 GB
GPU: Nvidia GTX 1660Ti

The game boots up, however upon selecting New Game option on the main menu, the game gets frozen on the following screen and then the emulator crashes. 
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/40916331/aaf69eea-883b-4061-8b9b-b68759991529)

Log: 
[Ryujinx_1.1.1334_2024-06-19_01-12-25.log](https://github.com/user-attachments/files/15891886/Ryujinx_1.1.1334_2024-06-19_01-12-25.log)

**Comment by katsuragiayato** [comment]
Game Name
Shin Megami Tensei V: Vengeance

Game  Version
1.0.0

Emulator Build Version
1.1.683

OS
Windows 10 Home 22H2

Graphics Backend
Vulkan

Hardware Specs
CPU:  i5-10400
GPU: AMD RX 6400
GPU Driver version: 23.2.2(Windows store version 31.0.14033.1012)
RAM: 16GB

Game State

Runs without any issues at 30fps native resolution, didn't spotted any graphical or sound glitches either. Developers team thank you very very much.

**Comment by Ghaleon7771** [comment]
Game Name
Shin Megami Tensei V: Vengeance

Game Version
1.0.1

Emulator Build Version
1.1.1336

OS
Windows 10 Home 22H2

Graphics Backend
Vulkan

Hardware Specs
CPU: i3-10100F
GPU: AMD RX 6500 XT Pulse
GPU Driver version: 24.5.1
RAM: 16GB

Game State

Runs without any problems except a lot of stuttering when loading shaders. The problem i am facing its that after closing the game, and booting it up again, it starts compiling shaders again but without "too" much stuttering. 
30FPS stable anyway, tried the 60FPS patch and it gets up to 55 FPS on average going down to 40 in some more populated areas, the "other" emu doesnt have this issue but it has got a lot of graphical glitches so i prefer Ryujinx anyway.

**Comment by JoriaanNL** [comment]
Game Name
Shin Megami Tensei V: Vengeance

Game Version
1.0.1

Emulator Build Version
1.1.1337

OS
Windows 11 Home (10.0) 64-bit (build 22631)

Graphics Backend
Vulkan

Hardware Specs
CPU: AMD Ryzen 7 7840HS
GPU: Nvidia GeForce RTX 4070 Laptop
GPU Driver version: 24.5.1
RAM: 16GB

Game State
Updating emulator build to 1.1.1337 completely eliminated the heavy stuttering and long loading times on first boot, that would usually smooth out after first encountering them with only occasional bouts of stuttering afterwards and a crash here and there when quickly switching between in-game and sub-menus (e.g. via leyline font). Still managed to play the game until halfway into the second Netherworld area, but it wasn't always pleasant. 

Post-update performance is so smooth that it almost seems like black magic. Using graphic upgrade mods to test this new level of performance (increased LOD, etc.) gives a very playable FPS across the board without bouts of stuttering.

Already reported visual bugs, like some characters occasionally flashing during cutscenes or some surfaces flickering in the World of Shadows, are still there, but do not detract from gameplay in the slightest.

**Comment by GamerzHell9137** [comment]
> Game Name Shin Megami Tensei V: Vengeance
> 
> Game Version 1.0.1
> 
> Emulator Build Version 1.1.1337
> 
> OS Windows 11 Home (10.0) 64-bit (build 22631)
> 
> Graphics Backend Vulkan
> 
> Hardware Specs CPU: AMD Ryzen 7 7840HS GPU: Nvidia GeForce RTX 4070 Laptop GPU Driver version: 555.99 RAM: 16GB
> 
> Game State Updating emulator build to 1.1.1337 completely eliminated the heavy stuttering and long loading times, that would always occur on first boot or first entering a new area and would usually smooth out after first encountering them with only occasional bouts of stuttering afterwards and the rare crash or freeze when quickly switching between in-game and sub-menus (e.g. via leyline font services). Still managed to play the game until halfway into the second Netherworld area, but the stuttering on first boot did become worse further into the game, lasting longer and being more frequent.
> 
> Post-update performance is so smooth that it almost seems like black magic. Using graphic upgrade mods to test this new level of performance (increased LOD, etc.) gives a very playable FPS across the board without bouts of stuttering.
> 
> Already reported visual bugs, like some characters occasionally flashing during cutscenes or some surfaces flickering in the World of Shadows, are still there, but do not detract from gameplay in the slightest.

Literally has nothing to do with the latest update of the emu. Its just shaders being made, its always gonna be like that.

**Comment by JoriaanNL** [comment]
I think you're misunderstanding me because I didn't explain it with the right terminology ("first boot" is probably wrong; I meant *every time the game is booted up* and loads into the game proper), but to confirm my case I downgraded back to version 1.1.1336 and all described issues were back. Went back to 1.1.1337, issues gone again. Loading times were especially noticeable: from approx. a minute and a half to load my savegame, to barely eleven seconds. Since no other variables changed, I can only think of the emulator's update being the reason why.

**Comment by GamerzHell9137** [comment]
### Game Name

SHIN MEGAMI TENSEI V: Vengeance 

### Game Update Version

v1.0.1

### Emulator Build Version

1.1.1337

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 7800X3D*
- ##### GPU: *NVIDIA RTX 3060 TI*
- ##### GPU Driver version: *551.76*
- ##### RAM: *16GB*


### Game State

Game runs fine with some graphical issues.

> [!NOTE]  
>The game is using Unreal Engine 4 and has issues with flickering objects. Stuff comes in and out of existence during cutscenes and during gameplay. 

Video of issue:

https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/dac43194-4a2a-423c-b0f4-ae30654ff504

### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/27e17c84-397c-48fd-a436-081bc99a01fd)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/43ecaba7-ff89-4914-ad02-342d9a4b66c9)


### Log File

[Ryujinx_1.1.1337_2024-06-25_17-38-10.log](https://github.com/user-attachments/files/15974044/Ryujinx_1.1.1337_2024-06-25_17-38-10.log)

**Comment by GamerzHell9137** [comment]
> I think you're misunderstanding me because I didn't explain it with the right terminology ("first boot" is probably wrong; I meant _every time the game is booted up_ and loads into the game proper), but to confirm my case I downgraded back to version 1.1.1336 and all described issues were back. Went back to 1.1.1337, issues gone again. Loading times were especially noticeable: from approx. a minute and a half to load my savegame, to barely eleven seconds. Since no other variables changed, I can only think of the emulator's update being the reason why.

Yeah its not the update, seems like W11 is doing stuff differently than W10 is.

**Comment by Icarus170303** [comment]
> Game Version: 1.0.1 Emulator Version: 1.1.1334 Backend: Vulcan
> 
> Specs: CPU: Intel i5-9300H Ram: 16 GB GPU: Nvidia GTX 1660Ti
> 
> The game boots up, however upon selecting New Game option on the main menu, the game gets frozen on the following screen and then the emulator crashes. ![image](https://private-user-images.githubusercontent.com/40916331/340812773-aaf69eea-883b-4061-8b9b-b68759991529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjkxODUsIm5iZiI6MTcxOTgyODg4NSwicGF0aCI6Ii80MDkxNjMzMS8zNDA4MTI3NzMtYWFmNjllZWEtODgzYi00MDYxLThiOWItYjY4NzU5OTkxNTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEwMTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNjA0NzUzYjYyNDY4MTViYzU2OTlhOTU1OWE2Yzg2YjM0N2ZhMDg1NzBlODc3OWZhNGFmNGRiY2ZmMjdhYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TYTxpoZrG0mjazWN-YLvvsJQyH_QG2p7XdiWR5Qli9c)
> 
> Log: [Ryujinx_1.1.1334_2024-06-19_01-12-25.log](https://github.com/user-attachments/files/15891886/Ryujinx_1.1.1334_2024-06-19_01-12-25.log)

UPDATE
Deleting your save data for the game seems to make it start working.

**Comment by dirtycasual36** [comment]
### **Game Name**
SHIN MEGAMI TENSEI V: Vengeance

### **Game Update Version**
v1.0.1

### **Emulator Build Version**
1.1.1340

### **Graphics Backend**
Vulkan

### **Hardware Specs**
CPU: Ryzen 5 4600G
GPU: NVIDIA RTX 2060
GPU Driver version: 552.44
RAM: 16GB


### **Game State:**
Game runs mostly stable at 30fps, only stutters when loading new textures, but that's to be expected.  The only issue so far is that the game freezes, then crashes when entering Cadaver's Hollow sometimes for some reason. This only happens specifically when entering Cadaver's Hollow after playing for 30 mins to 1 hour. I also sometimes pause the emulation when I take a smoke break then un-pause when I get back, I'm not sure if that has anything to do with it but there's that.

### **Log file:**
[Ryujinx_1.1.1340_2024-07-03_13-27-06.log](https://github.com/user-attachments/files/16088270/Ryujinx_1.1.1340_2024-07-03_13-27-06.log)

**Comment by stepsy** [comment]
`` 00:04:06.544 |S| HLE.OsThread.47 ServiceAm SetExpectedMasterVolume: Stubbed. 
00:04:31.999 |I| .NET TP Worker Ptc Save: Saved Profiling Info (size: 387763 bytes, profiled functions: 137760).
00:04:34.800 |E| GUI.RenderThread Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 290
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 259
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreateGraphicsPipelineIfNeeded() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1569
   at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32 indexCount, Int32 instanceCount, Int32 firstIndex, Int32 firstVertex, Int32 firstInstance) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 454
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 987
   at System.Threading.Thread.StartCallback()``

Occurred after inputting and skipping cutscene.
[Ryujinx_1.1.1343_2024-07-08_22-55-17.log](https://github.com/user-attachments/files/16131184/Ryujinx_1.1.1343_2024-07-08_22-55-17.log)


Version: 1.1.1343
CPU: Ryzen 5 7535hs
GPU: Nvidia RTX 4050
GPU Driver Version: 556.12
Ram: 16GB

**Comment by katsuragiayato** [comment]
Game Name
Shin Megami Tensei V: Vengeance

Game Version
1.0.1

Emulator Build Version
1.1.683

OS
Windows 10 Home 22H2

Graphics Backend
Vulkan

Hardware Specs
CPU: i5-10400
GPU: AMD RX 6400
GPU Driver version: 23.2.2
RAM: 16GB

Anyone who experience texture flickering in World of Shadows  or crashes when entering Cadaver's Hollow try 30fps_DisableDynamicRes patch or 1080p60fps patch, it resolved those troubles for me.

**Comment by Ghaleon7771** [comment]
> Anyone who experience texture flickering in World of Shadows or crashes when entering Cadaver's Hollow try 30fps_DisableDynamicRes patch or 1080p60fps patch, it resolved those troubles for me.

Can confirm enabling the 30fps_DisableDynamicRest patch fixes the flickering textures in World of Shadows... thanks for the info.

**Comment by time-axis** [comment]
While the 30fps_DisableDynamicRes patch does fix the flickering, I'm still experiencing crashes. It crashed upon finishing the third tutorial battle for me (with the slimes).
[Ryujinx_1.1.1345_2024-07-11_18-09-24.log](https://github.com/user-attachments/files/16184430/Ryujinx_1.1.1345_2024-07-11_18-09-24.log)

**Comment by katsuragiayato** [comment]
> While the 30fps_DisableDynamicRes patch does fix the flickering, I'm still experiencing crashes. It crashed upon finishing the third tutorial battle for me (with the slimes). [Ryujinx_1.1.1345_2024-07-11_18-09-24.log](https://github.com/user-attachments/files/16184430/Ryujinx_1.1.1345_2024-07-11_18-09-24.log)

Try older emulator build. I'm use 1.1.683 for a long time, cleared original SMT V 4 times, 140+ hours without single crash. Vengeance crushed only when entering Cadaver's Hollow, but after enabling 30fps_DisableDynamicRes patch no crashes anymore.

**Comment by cannon9009** [comment]
> The game is using Unreal Engine 4 and has issues with flickering objects. Stuff comes in and out of existence during cutscenes and during gameplay.

Hopefully this gets resolved. I'm having this issue too and it's a bit annoying to constantly have characters (including MC) disappear during a cutscene.
