### ISSUE TITLE
World of Goo 2 - 010061F01DB7C800

### ISSUE THREAD

**Issue by ZeSHFiRKa** [Ryujinx/Ryujinx-Games-List#5021]
### Game Name

World of Goo 2

### Game Update Version

1.0.1

### Emulator Build Version

1.1.1364

### Graphics Backend

OpenGL

### Hardware Specs

- ##### CPU: *Ryzen 9 5950X*
- ##### GPU: *RTX 3080*
- ##### GPU Driver version: *560.70*
- ##### RAM: *64GB*

### Game State

The game starts, the splash screen comes on and when the hand appears, the game freeze and crashes the emulator.

### Log File

00:00:24.666 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.683 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.700 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.716 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.733 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.750 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.766 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.796 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.800 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.816 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.833 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.850 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.866 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.883 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.900 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.916 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.933 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.950 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.966 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:24.992 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:25.013 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.013 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.013 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.013 |S| HLE.OsThread.3 ServiceHid IsSixAxisSensorAtRest: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65543 ; isAtRest: True}
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000008 (0x00000024000005FF).
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000010 (0x0000000000000000).
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000018 (0x000000655C09DC20).
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000028 (0x0000000000000000).
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000030 (0x0000000000061462).
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000038 (0x0000000000000000).
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000048 (0x0000000000000000).
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000050 (0x0000000000000000).
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000058 (0x0000000000000000).
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000068 (0x0000000F00000000).
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000070 (0x0000000000000000).
00:00:25.034 |W| GPU.MainThread Gpu Log: Shader translator: Invalid instruction at 0x000078 (0x000000000000000F).
00:00:25.038 |W| GPU.MainThread Gpu Log: Shader translator: Attribute offset 0xD0 (UserDefined) is not valid for stage Compute.
00:00:25.039 |W| GPU.MainThread Gpu Log: Shader translator: Attribute offset 0xD4 (UserDefined) is not valid for stage Compute.
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.075 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x25FD0 (sRGB: True).
00:00:25.099 |W| GUI.RenderThread Gpu CheckProgramLink: Shader linking failed: 
Compute info
------------
0(26) : error C3011: layout qualifier 'local_size_z', requires 'a non-negative integer'
0(26) : error C3011: layout qualifier 'local_size_y', requires 'a non-negative integer'
0(26) : error C3011: layout qualifier 'local_size_x', requires 'a non-negative integer'

00:00:25.113 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000001
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 84
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 289
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 226
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(ShaderDefinitions definitions, IGpuAccessor gpuAccessor, Context context, Block block, UInt64 limitAddress, UInt64 startAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 275
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(ShaderDefinitions definitions, IGpuAccessor gpuAccessor, UInt64 startAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Shader\Decoders\Decoder.cs:line 129
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 40
   at Ryujinx.Graphics.Shader.Translation.Translator.CreateContext(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 26
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.DecodeComputeShader(IGpuAccessor gpuAccessor, TargetApi api, UInt64 gpuVa) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 692
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetComputeShader(GpuChannel channel, Int32 samplerPoolMaximumId, GpuChannelPoolState poolState, GpuChannelComputeState computeState, UInt64 gpuVa) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 223
   at Ryujinx.Graphics.Gpu.Engine.Compute.ComputeClass.SendSignalingPcasB(Int32 argument) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\Compute\ComputeClass.cs:line 144
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 233
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 110
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 229
   at Ryujinx.Ava.AppHost.<RenderLoop>b__115_1() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 1011

**Comment by kukukuan2023** [comment]
Same here with RTX4060 using Vulkan.
Crash at startup.

[Ryujinx_1.1.1364_2024-08-03_07-20-22.log](https://github.com/user-attachments/files/16476096/Ryujinx_1.1.1364_2024-08-03_07-20-22.log)

**Comment by thilichoom** [comment]
Same issue for me RX 6700XT. Crash at startup. Some sounds start stuttering but the loading screen never changes and it crashes. 

[Ryujinx_1.1.1364_2024-08-02_22-18-39.log](https://github.com/user-attachments/files/16477791/Ryujinx_1.1.1364_2024-08-02_22-18-39.log)

**Comment by jimbo1111** [comment]
Crashes before splash screen on Mac M1 Max, newest ryujinx version, newest system software, 1.0.0 or 1.0.1. Goes to "loading world of goo 2" and then 'quit unexpectedly'

[Ryujinx_1.1.1368_2024-08-03_19-00-53.log](https://github.com/user-attachments/files/16484496/Ryujinx_1.1.1368_2024-08-03_19-00-53.log)
[Ryujinx_1.1.1368_2024-08-03_18-57-06.log](https://github.com/user-attachments/files/16484497/Ryujinx_1.1.1368_2024-08-03_18-57-06.log)

**Comment by Ionstrom00** [comment]
same on M3 Macbook air

**Comment by vantiss** [comment]
Same on Windows 11 with a 7800XT on Vulkan. On OpenGL it gets a *bit* further ("iodizing..."), but still crashes at that point,. Version 1.0.1 (but happens on V1 as well), latest ryujinx, latest firmware.

[Ryujinx_1.1.1373_2024-08-08_15-49-43.log](https://github.com/user-attachments/files/16554019/Ryujinx_1.1.1373_2024-08-08_15-49-43.log)
