### ISSUE TITLE
Ryujinx crash - Animal Crossing New Horizon

### ISSUE THREAD

**Issue by Woopti** [Ryujinx/Ryujinx-Games-List#504]
Animal Crossing: New Horizons 

Ryujinx Build Version 9.2.0

When starting up the game I get an error at the end of the load in, after which Ryujinx crashes.

```
Last error returned.
System.NotImplementedException: android.gui.IGraphicBufferProducer 2
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.NvFlinger.ProcessParcelRequest(ServiceCtx context, Byte[] parcelData, Int32 code) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\NvFlinger.cs:line 88
   at Ryujinx.HLE.HOS.Services.Vi.RootService.ApplicationDisplayService.IHOSBinderDriver.TransactParcelAuto(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Vi\RootService\ApplicationDisplayService\IHOSBinderDriver.cs:line 83
```
[Ryujinx_2020-03-30_20-35-22.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4404840/Ryujinx_2020-03-30_20-35-22.log)

**Comment by AcK77** [comment]
Closed in favor of #250
