### ISSUE TITLE
The Legend of Zelda Echoes of Wisdom - 01008CF01BAAC000

### ISSUE THREAD

**Issue by piplup55** [Ryujinx/Ryujinx-Games-List#5070]
### Game Name

The Legend of Zelda Echoes of Wisdom

### Game Update Version

1.0.1

### Emulator Build Version

1.1.1398

### Graphics Backend

OpenGL and Vulkan

### Hardware Specs

- ##### CPU: AMD Ryzen 9 7900X3D
- ##### GPU: AMD RX 6600 XT / NVIDIA 3060
- ##### GPU Driver version: Mesa 24.2.1-arch1.1 / NVIDIA 555.85
- ##### RAM: 64GB

### Game State

Game is playable but has some rendering issues on AMD didn't notice any on NVIDIA

<details close>
<summary>AMD</summary>
<br>

Vulkan:
![AMD](https://github.com/user-attachments/assets/9572166e-f992-4b3e-9f0c-caa49f049732)

OpenGL:
![image](https://github.com/user-attachments/assets/9aca20a7-0a7e-4d17-8bcb-37733c3cda5e)
![image](https://github.com/user-attachments/assets/a02bdb87-95fd-4ac7-a982-d8e0f26f4847)
![image](https://github.com/user-attachments/assets/fbaca5e6-37ff-4e73-b84f-3bea801bb4d2)

Switch:
![image](https://github.com/user-attachments/assets/9cbf0bc9-2156-4a65-8042-a3b7bd1c71c6)
![image](https://github.com/user-attachments/assets/50572cae-fe10-4643-bb6c-39eb33e6b98d)
![image](https://github.com/user-attachments/assets/0fa7a736-ac85-48bf-a3c2-c7b236b3b74b)

</details>

### Screenshots

![1yZHpeUdPD](https://github.com/user-attachments/assets/0c522ba1-0a67-4f6b-8d40-773a88ecba6d)
![3rE7bneXCk](https://github.com/user-attachments/assets/84d37fb9-20a7-4914-b815-27bdae50ef63)
![QZPCcxivuV](https://github.com/user-attachments/assets/36395e42-f664-497d-a717-5a0997703d23)
![ZWSTjQnI3t](https://github.com/user-attachments/assets/7dc31393-0dc0-4734-a395-0108337d253b)

<details close>
<summary>AMD</summary>
<br>

![AMD](https://github.com/user-attachments/assets/e8aecc50-c1f9-47d9-b92b-20f70062ac79)
![image](https://github.com/user-attachments/assets/3a6d5b08-1d75-4b12-a654-e0273b0ae306)
![image](https://github.com/user-attachments/assets/ba898dc6-6887-4739-bbd4-feaf9a663080)
![image](https://github.com/user-attachments/assets/df87e8ef-565f-4967-b376-f7efc72e1ec7)
![image](https://github.com/user-attachments/assets/1a040fa3-e79b-487a-9237-33935e21a525)

</details>

### Log File

[Ryujinx_1.1.1398_2024-09-25_13-00-41.log](https://github.com/user-attachments/files/17130568/Ryujinx_1.1.1398_2024-09-25_13-00-41.log)

**Comment by Moinito42** [comment]
MacBook Mini M1, it crash after the small introduction, when Zelda meets her knights....

**Comment by EuphoricBaZ** [comment]
Hiya, when using Vulcan I can't see the main game, its all black and only the icons are showing. When using OpenGL everything is fine apart from dialogue not showing in the boxes

**Comment by cszhe** [comment]
> MacBook Mini M1, it crash after the small introduction, when Zelda meets her knights....

Same with M1 Pro MacBook Pro.

**Comment by BorisBartkowski** [comment]
> MacBook Mini M1, it crash after the small introduction, when Zelda meets her knights....

Me too on Windows 11 (intel 9900k // nvidia 2080ti)

**Comment by tolgacanatan** [comment]
I have similar graphice issues on both Vulkan and OpenGL.

System: cpu 5800x3d, gpu asus/amd 7800xt, 32gb ram, windows 11
Ryujinx version 1.1.1398
Game version: 1.0.1


OpenGL :

![2024-09-26_11-38_1](https://github.com/user-attachments/assets/fcfe21c4-400f-4f9f-899e-312bbdd8446a)
![2024-09-26_11-38](https://github.com/user-attachments/assets/cf994b75-27c6-4071-ad37-f81ead3ac738)

+ dark scenes are not same with the Switch version like described in the first comment above.


Vulkan:

![2024-09-26_11-45](https://github.com/user-attachments/assets/63c968e4-a882-42e5-9324-40cab2c16df5)
![2024-09-26_11-46](https://github.com/user-attachments/assets/f7627ca5-0234-4d66-9375-b584dee6d8b0)


Logs: 

[Ryujinx_1.1.1398_2024-09-26_11-36-43.log](https://github.com/user-attachments/files/17145570/Ryujinx_1.1.1398_2024-09-26_11-36-43.log)

**Comment by erujp** [comment]
> MacBook Mini M1, it crash after the small introduction, when Zelda meets her knights....

I'm using a Mac Mini M1, 16 GB of ram, MacOS Sequoia 15.0, Ryujinx 1.1.1398, Firmware 18.1.0 and same version of Prod Keys, and I don't have your problems. Make sure you have everything updated.

The only problems on my machine: it slows down heavily in the cut scenes, and in the same scenes the audio goes out of synch, but the game is playable overall.

**Comment by Greenl1zard** [comment]
Can confirm that it has its problems on Steamdeck, not working (graphics dark) on vulkan but works with OpenGL and with stutters

**Comment by garrett16r** [comment]
Game Version: 1.0.1
Ryujinx Version: 1.1.1398
Graphics Backend: Vulkan
OS: Windows 11 Home (10.0.22631 Build 22631)

CPU: Ryzen 7 7800x3D
GPU: Nvidia RTX 4070
Nvidia Driver Version: 560.94 (08/20/2024)
RAM: 32GB DDR5 6000MHz

Game State: Fully playable so far
Notes: 

- I'm using the disable blur/depth of field mod from [StevensND](https://github.com/StevensND/switch-port-mods/tree/main/The%20Legend%20of%20Zelda%20Echoes%20of%20Wisdom/%5B01008CF01BAAC000%5D)
- There are stutters when an animation that hasn't been seen before plays, but that's a consistent thing I see with Ryujinx on Vulkan. Not a huge deal.

**Comment by mj2k23** [comment]
On Mac (sequoia, FW 18.1), game is visually perfect for me. No glitches. Only issue is the it randomly freezes (sometimes 5 min after launch, sometimes 20), and requires a force quit. Which is quite annoying when in a dungeon, etc.

**Comment by PaulEins** [comment]
Hello, I have everything on the current version. Everything starts fine on my **MacBook Air m2 with 8GB**. There are slight sound problems that are asyncronous. But above all, it crashes occasionally. Rarely after 3 or 5 minutes. Often after 40 minutes, rarely after up to 70 minutes. If you save often, you can still play well. 

Then I switched the memory manager mode to software and deactivated Hypervisor. Since then it always runs for about 60 minutes and then crashes with Ryujinx. But it flickers more often. But this is the most stable and best way to play.

**Comment by mitchellmebane** [comment]
It runs perfectly fine on my M2 Max MacBook Pro, except it often hard-locks the machine when switching between windowed and fullscreen.  The screen completely freezes, the audio sometimes keeps running for a while, and the machine reboots after a minute or two.

I've tried with Hypervisor enabled and disabled.

**Comment by mj2k23** [comment]
I can confirm no more crashing with hypervisor enabled on Mac. Wish I knew this previously, would have prevented suffering!

**Comment by Rugalb2K** [comment]
it crashes after the small introduction, when Zelda meets her knights....
Game Version: 1.0.1
Ryujinx Version: 1.1.14
Graphics Backend: Vulkan/opengl
CPU: Ryzen 7 5800x3D
GPU: Nvidia RTX 3080

**Comment by antoniodesousa** [comment]
The game runs perfect on my PC. I didn't notice any graphic glitches or experience any crashes during the hour I was playing.

Game Version: 1.0.1
Ryujinx Version: 1.1.1398
OS: Windows 11 23H2 Pro
Graphics Backend: Vulkan
CPU: Ryzen 9 6900HX
GPU: Radeon RX 6600M
GPU Driver version: Adrenalin 24.7.1
RAM: 64 GB

### Screenshots

![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 22_59_11](https://github.com/user-attachments/assets/60d7a106-75d0-460b-89d7-aa3b033815f4)
![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 23_00_00](https://github.com/user-attachments/assets/6279a1d3-d3f8-4950-9bee-6d3f463ab703)
![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 23_01_18](https://github.com/user-attachments/assets/b27b09a0-c6c2-4305-8406-7cd2d811bb42)
![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 23_02_16](https://github.com/user-attachments/assets/173f8218-130d-4d66-b88c-1e7ac5eb8e4a)
![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 23_05_30](https://github.com/user-attachments/assets/d29f7668-5e2d-4197-bf77-d8619833f0f6)
![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 23_10_52](https://github.com/user-attachments/assets/9f6ffa7a-f41f-40b6-a532-202e4dfcada0)
![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 23_12_16](https://github.com/user-attachments/assets/c82195e8-9906-4d12-aec3-afcc654581a7)
![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 23_12_54](https://github.com/user-attachments/assets/669d106f-0559-4173-8006-ae96031f0af0)
![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 23_16_57](https://github.com/user-attachments/assets/6a8810bd-046c-4635-8fd2-6a9280cec822)
![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 23_23_24](https://github.com/user-attachments/assets/e7e90621-b160-467b-a274-da14699f2168)
![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 23_38_11](https://github.com/user-attachments/assets/2bcfb906-b6ac-4006-8029-92ffb0f6f231)
![Ryujinx 1 1 1398 - The Legend of Zelda_ Echoes of Wisdom v1 0 1 (01008CF01BAAC000) (64-bit) 26_09_2024 23_41_05](https://github.com/user-attachments/assets/f3df2543-c99a-4f01-8942-aca5df1d756c)

### Log File

[Ryujinx_1.1.1398_2024-09-26_22-58-39.log](https://github.com/user-attachments/files/17156410/Ryujinx_1.1.1398_2024-09-26_22-58-39.log)

**Comment by RupeeClock** [comment]
Game features webm format VP9 encoded video for use of pre-rendered cutscenes. They do not contain audio, instead using the game engine for audio playback.
Examples include the title screen, and the opening cutscene that plays after the prologue's escape sequence.

Details from MediaInfo of the title screen video:
```
Format                      : WebM
Format version              : Version 2
File size                   : 66.0 MiB
Duration                    : 2 min 0 s
Overall bit rate            : 4 610 kb/s
Frame rate                  : 60.119 FPS
Encoded date                : 2024-06-07 14:25:12 UTC
Writing application         : fnord WebM for Premiere, built Apr  9 2015
Writing library             : libwebm-0.2.1.0

Video
ID                          : 1
Format                      : VP9
Format profile              : 0
Codec ID                    : V_VP9
Duration                    : 2 min 0 s
Bit rate                    : 4 421 kb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 60.119 FPS
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Bits/(Pixel*Frame)          : 0.035
Stream size                 : 63.3 MiB (96%)
Language                    : English
Default                     : Yes
Forced                      : No
Color range                 : Limited
```

**Comment by erujp** [comment]
> I can confirm no more crashing with hypervisor enabled on Mac. Wish I knew this previously, would have prevented suffering!

You mean "disabled", right?

**Comment by HouseYeung** [comment]
> > I can confirm no more crashing with hypervisor enabled on Mac. Wish I knew this previously, would have prevented suffering!
> 
> You mean "disabled", right?

I’m not entirely sure how to prevent crashes completely, but the best settings for my Mac are to disable PPTC and enable Hypervisor.

**Comment by iMonZ** [comment]
After playing this game for a few minutes, it crashes. Restarting solved and is giving me another few minutes.
That way I can progress, but not much.
[ryulogs.log](https://github.com/user-attachments/files/17174652/ryulogs.log)

**Comment by HouseYeung** [comment]
> > > I can confirm no more crashing with hypervisor enabled on Mac. Wish I knew this previously, would have prevented suffering!
> > 
> > 
> > You mean "disabled", right?
> 
> I’m not entirely sure how to prevent crashes completely, but the best settings for my Mac are to disable PPTC and enable Hypervisor.

While I played more, I can confirm that all settings will crash the game. However, after a crash you can change the settings (like Hypervisor) and play for a bit longer. I don’t know why, but if you leave all the settings the same, restarting the game will crash very soon.

**Comment by DayBreakShifter** [comment]
I keep getting crashes every 5-10 minutes, if even that. Though for some reason, this time it occurred after enough time for me to get one of the rifts fixed. I'm not sure the extra time was thanks to me disabling PPTC since when I initially disabled it, it crashed less than two minutes after loading into the game.

Just for added measure, I turned on the main variants of logging to see if it'd help in fixing the general instability.
[Ryujinx_1.1.1401_2024-09-28_09-48-23.log](https://github.com/user-attachments/files/17174692/Ryujinx_1.1.1401_2024-09-28_09-48-23.log)

**Comment by Azyzraissi** [comment]
Works perfectly on macOS Sequoia 15.0 on the M1 MacbookPro

**Comment by L1ttleFlyyy** [comment]
Crashes on macOs Sequoia 15.0, M1 Macbook Pro
Game runs fine at intro scene but crashes after the title show up where Zelda left with 2 soldiers.

[Ryujinx_1.1.1401_2024-09-28_12-31-41.log](https://github.com/user-attachments/files/17176014/Ryujinx_1.1.1401_2024-09-28_12-31-41.log)

**Comment by tolgacanatan** [comment]
After updating [1.1.1401](https://github.com/Ryujinx/Ryujinx/wiki/Changelog#111401---2024-09-28), the game is much better  with Vulkan now. No black screen or any other issues for now.

**Comment by gdkchan** [comment]
@DayBreakShifter There is some information missing at the start of the log, did you remove it? Also, did you change the memory manager mode?

**Comment by TaciteOFF** [comment]
> Works perfectly on macOS Sequoia 15.0 on the M1 MacbookPro

I have M1 Pro and MacOS 15.0 too but I have huge FPS loss and random crash...

**Comment by Darekens** [comment]
![image](https://github.com/user-attachments/assets/3bae8429-1c13-462c-b927-5bff63d75be5)

Can you help me ?
I can't play

**Comment by ekuland** [comment]
> ![image](https://private-user-images.githubusercontent.com/183301168/371870667-3bae8429-1c13-462c-b927-5bff63d75be5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzE3NDQsIm5iZiI6MTcyNzYzMTQ0NCwicGF0aCI6Ii8xODMzMDExNjgvMzcxODcwNjY3LTNiYWU4NDI5LTFjMTMtNDYyYy1iOTI3LTViZmY2M2Q3NWJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxNzM3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2I0NWIwMmVlNjQ4ODY5YzRiY2VkNzA3MzgyYTA4ZTNiZTJmOWEyZThmZmJiODNlMDZkZDIzMDY4MmQ3NzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tJnjha501HqgpYL4jEBIa5mEk7oqg-B2Tw7eHvYtGNM)
> 
> Can you help me ? I can't play

You have either too many or not enough players setup. Disable all but player 1.
Join the discord if further support is needed.

**Comment by Darekens** [comment]
Wow Ekuland, I love you mate.
Thanks

**Comment by clockworkred458** [comment]
Game is running well for me on Steam Deck. I have it capped at 40 FPS and at 720p. Very minor stutters during gameplay, cutscenes stutter a lot almost like I’m watching a slide show. Anyone else have that issue or even a solution. Game is still brand new so it will probably get fixed in an upcoming update.

**Comment by Megatronus27** [comment]
Nah it still crashes after intro

**Comment by rslanna** [comment]
crash when Zelda meets her knights...
00:03:21.100 |E| HLE.OsThread.2 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at LibHac.Util.Lz4.Decompress(ReadOnlySpan`1 cmp, Span`1 dec)
   at LibHac.Tools.FsSystem.CompressedStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination)
   at LibHac.Tools.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1)
   at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 35
   at InvokeStub_IStorage.Read(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo)
   at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 372
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254
   at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1255
   at System.Threading.Thread.StartCallback()

**Comment by prince-rakeem** [comment]
> crash when Zelda meets her knights... 00:03:21.100 |E| HLE.OsThread.2 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. at LibHac.Util.Lz4.Decompress(ReadOnlySpan`1 cmp, Span`1 dec) at LibHac.Tools.FsSystem.CompressedStorage.Read(Int64 offset, Span`1 destination) at LibHac.Tools.FsSystem.CachedStorage.GetBlock(Int64 blockIndex) at LibHac.Tools.FsSystem.CachedStorage.Read(Int64 offset, Span`1 destination) at LibHac.Tools.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count) at System.IO.Stream.Read(Span`1) at LibHac.Tools.FsSystem.StreamStorage.Read(Int64 offset, Span`1 destination) at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 35 at InvokeStub_IStorage.Read(Object, Span`1) at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo) --- End of inner exception stack trace --- at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object, BindingFlags, Binder, Object[], CultureInfo) at Ryujinx.HLE.HOS.Services.IpcService.CallCmifMethod(ServiceCtx context) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\IpcService.cs:line 126 at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 372 at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 254 at Ryujinx.HLE.HOS.Services.ServerBase.Main() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 172 at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1255 at System.Threading.Thread.StartCallback()

Same here, running in Linux.

**Comment by SocialSophia** [comment]
![unknown_2024 10 01-16 04](https://github.com/user-attachments/assets/5fb56666-fa90-40ef-b367-5abd06594c28)
I got this classic error when trying to load it, it could be that its not in the yuzu title keys. Any idea how to fix it?
