### ISSUE TITLE
Monster Hunter Generation Ultimate

### ISSUE THREAD

**Issue by Xiaraz** [Ryujinx/Ryujinx-Games-List#511]
Game Name

Current on `master` : 1.0.4047

Crash on launch game , with all version update , don't start .

[Ryujinx_2020-03-31_17-14-41.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4407085/Ryujinx_2020-03-31_17-14-41.log)
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Could you make it start?

**Comment by B3astTech** [comment]
This was not done properly but I made it proper format. Please Fill out the Template more carefully

**Comment by Xiaraz** [comment]
Hi , i'am so sorry thank for the For having put it back correctly!

**Comment by B3astTech** [comment]
Np. Thanks for testing

**Comment by riperiperi** [comment]
The game is playable, but requires an existing save. When trying to start a new save, the game will softlock when entering a name. In LDN-1, local wireless multiplayer is playable, but it has a tendancy to leave rooms open after you leave them. Closing ryujinx will make these rooms disappear.

**Comment by xxmoon** [comment]
The game runs at fullspeed for me, but the audio desyncs with the video, eventually becoming like 3-4 full seconds delayed.

I have tried multiple audio devices, reinstalling audio drivers, openAL, soundIO, even trying with and without vsync. Nothing has any effect.

**Comment by Deol853** [comment]
If the game softlock how can i play if i want to create a new save then? is there any way to ignore the name entering or maybe creating a new save in the files directly?

**Comment by HiHiKazumaDesu** [comment]
Hello, quick question, I get visual artifacts (squares) around some of the textures, like flowers for example, is this happening to anyone else or is it just me?

**Comment by fbreno** [comment]
> If the game softlock how can i play if i want to create a new save then? is there any way to ignore the name entering or maybe creating a new save in the files directly?

You can dump you savefile from swtich. Also can be done dumping a 3ds save file from MHXX and converting using this https://github.com/Dawnshifter/MHXXSwitchSaveEditor

**Comment by Desmondchaser27** [comment]
Does Ryujinx have shader cache implementation?  I'm running a PC plenty powerful enough for this game but am getting some pretty egregious drops in places.

Build:
Ryzen 7 3700X
NVIDIA RTX 2600 Super 8 GB
32 GB DDR4
And I'm running the game via SSD.

**Comment by Denadan** [comment]
i3-3220/16Gb/NV1050 with 2GB vram/ssd
4h ingame, 9 hunts with 2 play sessions

perfomance spikes on first load locations/models/effects (shader cache update?)
intro video lagging 

otherwise stable 30fps
with virtual keyboard implementation able to create character/rename palico and other stuff

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Armorio** [comment]
> 
> 
> The game runs at fullspeed for me, but the audio desyncs with the video, eventually becoming like 3-4 full seconds delayed.
> 
> I have tried multiple audio devices, reinstalling audio drivers, openAL, soundIO, even trying with and without vsync. Nothing has any effect.

I'have same problem and i find no answer

**Comment by mazen123123** [comment]
excuse me... im here because im playing monster hunter generation ultimate... the game play well... but it happen when the game is saving... its freeze and force me to restart the emulator... after i restart the emulator the save file data is corrupted... my GF also play this but nothing happend to her game... can anyone give me an advice? please :(

**Comment by Mojavve** [comment]
> 
> 
> The game runs at fullspeed for me, but the audio desyncs with the video, eventually becoming like 3-4 full seconds delayed.
> 
> I have tried multiple audio devices, reinstalling audio drivers, openAL, soundIO, even trying with and without vsync. Nothing has any effect.

I'm on Ryujinx 1.0.7063 and as you say the game runs perfect but audio desyncs.  I've tried **OpenAL** as well as **SDL2**.  Using the 60 FPS mod.  

In the console I do get this error repeatedly: 

`HLE.OsThread.6 AudioRenderer Update: Unmap of memory pool (address: 0x50361000, size 0x5a000) failed!`

However I'm not sure if this is relevant or not.

**Comment by Mojavve** [comment]
> I have the same issue as @Mojavve with the audio. Is there any fix yet?
> 
> Thanks.

My issue just sorta stopped happening after a certain point in the game.  Basically after a few hours of progress it never happened again.  No idea exactly when it stopped though or why.

**Comment by xDuwang** [comment]
It got worse for me. It is making even Discord crashing when I am on voice chat.

AudioRenderer Update: Unmap of memory pool

**Comment by Eduzito** [comment]
Cara tem um jogo que estou tentando faser funcionar (Monster Hunter generations ultimeide ) que quando vou entrar aparece (there is no data o load) porfavor me ajuda estou tentando faser funcionar a 3 meses porfavor me ajuda

**Comment by Eduzito** [comment]
Dude has a game I'm trying to faser work (Monster Hunter generations ultimeide ) that when I enter appears (there is no data the load) please help me I'm trying to faser run for 3 months please help mew

**Comment by MavericK99966** [comment]
I have this same issue, audio desyncs fairly quickly (after only one quest or so).

**Comment by tanukiOnGitHub** [comment]
Any fix for the audio desync or work around yet?

**Comment by MavericK99966** [comment]
I have to use a different audio mode in the emulator settings for it to work properly.  I can't recall which one but not the default one.

**Comment by ljn917** [comment]
I had the audio desync issue with the default SDL2 backend on linux. After switching to the OpenAL backend, the issue was fixed.

**Comment by aureelionn** [comment]
The audio desync persists in MacOS Ryujinx 1.1.0. I tried switching multiple audio modes. 

Right now the only thing that works is restart the game until the audio works properly and restart again if it starts to desync

**Comment by JesR2043** [comment]
can someone help me out cause this is my first time doing this and i dont really understand how to do it
