### ISSUE TITLE
Beyblade Burst Battle Zero

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#527]
#### Current on `master` : 1.0.4107

Game sits at title screen actively rendering, but inputs do not register whether on keyboard, controller, or touch.

#### Screenshots :

![2020-03-31 10_35_02-Ryujinx 1 0 4107 _ ベイブレードバースト バトルゼロ _ 010068600AD16000](https://user-images.githubusercontent.com/62343878/78051999-bbd84900-733b-11ea-961b-2f606ed6ea40.png)
![2020-03-31 10_35_45-Ryujinx 1 0 4107 _ ベイブレードバースト バトルゼロ _ 010068600AD16000](https://user-images.githubusercontent.com/62343878/78052020-c561b100-733b-11ea-84df-273215bb58e6.png)
![2020-03-31 10_36_16-Ryujinx 1 0 4107 _ ベイブレードバースト バトルゼロ _ 010068600AD16000](https://user-images.githubusercontent.com/62343878/78052022-c561b100-733b-11ea-9b05-489519b3fd1b.png)

#### Log file :

[BBBZ.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4410378/BBBZ.zip)

**Comment by gdkchan** [comment]
Needs retesting.

**Comment by Seker-0** [comment]
Update........

#### Current on `master` : 1.0.4142

You can now press (a) to enter the game and can touch
Is because pr # 1003 is able to click into the game
game still crashes after starting to name the characters in the tutorial in story mode
You must use save to skip the tutorial in order to play
There are no visible errors in the log

#### Screenshots : 
![BB1](https://user-images.githubusercontent.com/35269098/78622718-17608480-78b0-11ea-8f18-f3899afa6025.jpg)
![BB2](https://user-images.githubusercontent.com/35269098/78622731-21828300-78b0-11ea-9ef6-a0b5b700018c.jpg)
![BB3](https://user-images.githubusercontent.com/35269098/78622737-25aea080-78b0-11ea-8cc9-569b71480338.jpg)
![BB4](https://user-images.githubusercontent.com/35269098/78622741-28a99100-78b0-11ea-9a12-c6d65a638302.jpg)
![BB5](https://user-images.githubusercontent.com/35269098/78622744-2ba48180-78b0-11ea-8173-f7d8e4374f0a.jpg)
![BB6](https://user-images.githubusercontent.com/35269098/78622749-2e9f7200-78b0-11ea-8afe-92628fa08738.jpg)
![BB7](https://user-images.githubusercontent.com/35269098/78622751-3101cc00-78b0-11ea-887b-e24eaa373b1e.jpg)
![BB8](https://user-images.githubusercontent.com/35269098/78622756-33642600-78b0-11ea-91f6-6d7154760453.jpg)

### LOG :
[BB 7.4.20.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4441670/BB.7.4.20.log)

**Comment by EmulationFanatic** [comment]
@Cronos-0 can you re-test please on current master?

**Comment by Cronos-0** [comment]
@EmulationFanatic Nothing has changed from the previous one I tested. The game still crashes when I name my character. With the original error `Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region`

- Save is still necessary for this game. Tutorial can be skipped

Logs : 
[Ryujinx_1.0.6341_2021-01-19_01-51-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5831998/Ryujinx_1.0.6341_2021-01-19_01-51-33.log)

![bandicam 2021-01-19 01-54-34-060](https://user-images.githubusercontent.com/35269098/104954058-2dcc6c80-59fa-11eb-8901-691d128c2db9.jpg)
![bandicam 2021-01-19 01-54-44-395](https://user-images.githubusercontent.com/35269098/104954068-30c75d00-59fa-11eb-9283-f5cef4228d4c.jpg)

**Comment by wickedr0se** [comment]
The game works fine now, no problem so far
vulkan build bd79647

![Screenshot_239](https://user-images.githubusercontent.com/32614215/167177912-f5d5963e-d6b1-4d25-9604-ca8d53f470dc.png)
![Screenshot_240](https://user-images.githubusercontent.com/32614215/167177923-bd215309-0846-46a0-a7fd-4bdf6a0c5442.png)

[Ryujinx_1.1.0+bd79647_2022-05-06_23-49-52.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8642308/Ryujinx_1.1.0%2Bbd79647_2022-05-06_23-49-52.log)

**Comment by Cronos-0** [comment]
latest update @EmulationFanatic 

#### Game Update Version : 1.0.0 / JP

#### Current on `master` : 1.1.199

The game still crashes in the latest version. Saves are still needed for this game. Even when using the save game still crashes. But can be played in vs mode. Story mode still crashes as before.

```
Process: Application, PID: 92
   0x00000000080c4040	main:0xc0040	
   0x00000000080c3dd0	main:0xbfdd0	
   0x00000000080c39f8	main:0xbf9f8	
   0x0000000008210348	main:0x20c348	
   0x00000000082103d0	main:0x20c3d0	
   0x0000000008204ce8	main:0x200ce8	
   0x00000000082dbf2c	main:0x2d7f2c	
   0x00000000082d69b4	main:0x2d29b4	
   0x00000000082d67f0	main:0x2d27f0	
   0x00000000082d7308	main:0x2d3308	
   0x00000000082c15fc	main:0x2bd5fc	
   0x00000000082c2554	main:0x2be554	
   0x000000000802b978	main:0x27978	nnMain:0x0ff8
   0x000000000a83f92c	sdk:0x8492c	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)()):0x004c
   0x00000000080000ac	rtld:0x00ac	


00:00:43.697 |I| HLE.GuestThread.15 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0xa45054a6c60eabf7
	X[02]:	0x49bd5d01d88137c3
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000073
	X[05]:	0x0000000000000350
	X[06]:	0x0000000000000002
	X[07]:	0x0000000000000001
	X[08]:	0x49bd5d01d88137d1
	X[09]:	0x0000000000000000
	X[10]:	0x0000000000000000
	X[11]:	0x0000000000000100
	X[12]:	0x0000000000000002
	X[13]:	0x0000000000000000
	X[14]:	0x0000000000000000
	X[15]:	0x000000100b400a48
	X[16]:	0x000000000b2b1ef0
	X[17]:	0x000000000ac44890 (sdk:0x489890)	=> memcpy
	X[18]:	0x0000000000000000
	X[19]:	0x0000000000000000
	X[20]:	0x49bd5d01d88137c3
	X[21]:	0xa45054a6c60eabf7
	X[22]:	0x49bd5d01d88137d0
	X[23]:	0x0000001094b91aa0
	X[24]:	0x000000100d3bbf80
	X[25]:	0x000000118b503788 (SP:-0x02d8)
	X[26]:	0x000000118b503808 (SP:-0x0358)
	X[27]:	0x000000100d299450
	X[28]:	0x0000000008c08e60
	FP:	0x000000118b5034d0 (SP:-0x0020)
	LR:	0x000000000abed7d8 (sdk:0x4327d8)	=> std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&):0x0090
	SP:	0x000000118b5034b0 (SP)
	PC:	0x000000000ac44890 (sdk:0x489890)	=> memcpy


00:00:43.697 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x00000026C60EA000.
00:00:43.751 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 252
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
```

#### Hardware Specs :

GPU : GTX 1660 SUPER 6GB
CPU : INTEL I5 8400
RAM : KINGSTON DDR4 16GB

#### Outstanding Issues :



#### Screenshots :

![bandicam 2022-07-30 05-54-25-037](https://user-images.githubusercontent.com/35269098/181856632-c9a1d073-5a61-432e-ae90-2b152493a90a.jpg)


#### Logs : 

[Ryujinx_1.1.199_2022-07-30_05-53-14.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9223765/Ryujinx_1.1.199_2022-07-30_05-53-14.log)

**Comment by EmulationFanatic** [comment]
Needs update. Should be working without a save file now.
