### ISSUE TITLE
Pokken Tournament DX

### ISSUE THREAD

**Issue by AcK77** [Ryujinx/Ryujinx-Games-List#53]
Current State on `master`: 
```
System.NotImplementedException : 'acc:u0 IManagerForApplication: 130'
```

Who is : 
```
[130] GetNintendoAccountUserResourceCacheForApplication() -> (nn::account::NintendoAccountId, buffer<nn::account::nas::NasUserBaseForApplication, 0x1a, 0x68>, buffer<unknown, 6, 0>)
```

If you stub it, you will get : 
```
System.NotImplementedException : 'B5G6R5Unorm'
```

**Comment by HorrorTroll** [comment]
https://github.com/Ryujinx/Ryujinx/pull/417

Try this for fix B5G6R5Unorm and BGR5A1Unorm @AcK77

**Comment by AcK77** [comment]
Updated feedback!

**Comment by HorrorTroll** [comment]
OMG many service need to be stub XD

**Comment by AcK77** [comment]
Updated.

**Comment by AliGamerFTW659** [comment]
is this going to be finished soon

**Comment by Seker-0** [comment]
Update.......................................

#### Current on `master` : 1.0.4532

- You must select the controller as a Pro controller only so that it doesn't go wrong
- Because nvdec has not been used Causing the menu page to not be able to see the video but hear the sound
- can be played if not all white ( Only in the fight scene )
- Some broken graphics such as icon pokemon

```
00:00:01.590 | SurfaceFlinger.Composer Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.SurfaceFlinger.HandleComposition() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\SurfaceFlinger.cs:line 201
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :
![bandicam 2020-05-10 02-14-55-425](https://user-images.githubusercontent.com/35269098/81483145-0ebfed00-9266-11ea-9da5-4b52895303dd.jpg)
![bandicam 2020-05-10 02-16-22-248](https://user-images.githubusercontent.com/35269098/81483155-1c757280-9266-11ea-9ca8-b0151b5cc083.jpg)
![bandicam 2020-05-10 02-15-27-799](https://user-images.githubusercontent.com/35269098/81483159-26977100-9266-11ea-837a-ceff8d7f4b7f.jpg)
![bandicam 2020-05-10 02-15-34-601](https://user-images.githubusercontent.com/35269098/81483161-29926180-9266-11ea-91a5-c4c99c1608b8.jpg)
![bandicam 2020-05-10 02-16-09-405](https://user-images.githubusercontent.com/35269098/81483164-2b5c2500-9266-11ea-9749-219daa227983.jpg)
![bandicam 2020-05-10 02-16-34-612](https://user-images.githubusercontent.com/35269098/81483166-2d25e880-9266-11ea-8a0a-16ffb50e83b9.jpg)

#### Issue  :
![bandicam 2020-05-10 02-14-24-459](https://user-images.githubusercontent.com/35269098/81483088-b2f56400-9265-11ea-87cf-ea86719e4162.jpg)
![bandicam 2020-05-10 02-14-32-440](https://user-images.githubusercontent.com/35269098/81483090-b5f05480-9265-11ea-9c27-79869180e5ad.jpg)
![bandicam 2020-05-10 02-16-39-589](https://user-images.githubusercontent.com/35269098/81483093-bb4d9f00-9265-11ea-9ed4-9bea159af278.jpg)
![bandicam 2020-05-10 02-17-23-998](https://user-images.githubusercontent.com/35269098/81483095-c0125300-9265-11ea-8f7d-a79411a5ddb8.jpg)
![bandicam 2020-05-10 02-17-31-113](https://user-images.githubusercontent.com/35269098/81483098-c43e7080-9265-11ea-9117-d9a568e04ac5.jpg)

## Log issue :
[PKT.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4604340/PKT.log)
## Log no issue :
[PKT.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4604343/PKT.log)

**Comment by GoffyDude** [comment]
Updated

**Comment by mantazzo** [comment]
Just wanted to add in some current results.
---
System Info:
Laptop
Operating System: Microsoft Windows 10.0.19042 (X64)
Processor: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
RAM: 16GB (16276 MB)
GPU: Geforce 1050Ti 4GB, Drivers 457.30
System is set to run ryujinx on the 1050Ti
Using Xbox One Gamepad for playing

*If I need to specify anything else I'll add in as requested*
---
ryujinx Info:
Current version: 1.0.5915
System Version: 10.2.0
Game version: 1.3.3
---
Results:
Intro video runs, but is a bit laggy. Not sure if that's due to game running on HDD and not on SSD.
Menus run fine, some rare hiccups of FPS, but solid 60 FPS in the menus. Rare graphical glitches, but I think the "shader cache" introduced recently fixed most of those.
Battle loads and plays fine. FPS drops experienced (can drop to 20-40 FPS, depending on arena and certain actions). Graphics are not white anymore (as above), but the characters themselves are wrongly colored (mostly accent of blue, like Pikachu is lightly blue while Scizor is darker blue).
With recent updates it started strangely crashing:

```
00:00:41.945 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access a invalid memory region.
   at Ryujinx.Memory.MemoryBlock.ThrowInvalidMemoryRegionException() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 288
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 535
   at Ryujinx.Cpu.MemoryManager.ReadImpl(UInt64 va, Span`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 434
   at Ryujinx.Cpu.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 257
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Read[T](UInt64 gpuVa) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 58
   at Ryujinx.Graphics.Shader.Translation.ShaderHeader..ctor(IGpuAccessor gpuAccessor, UInt64 address) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\ShaderHeader.cs:line 114
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, TranslationCounts counts, ShaderConfig& config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 138
   at Ryujinx.Graphics.Shader.Translation.Translator.CreateContext(UInt64 address, IGpuAccessor gpuAccessor, TranslationFlags flags, TranslationCounts counts) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 34
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.DecodeGraphicsShader(GpuState state, TranslationCounts counts, TranslationFlags flags, ShaderStage stage, UInt64 gpuVa, UInt64 gpuVaA) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 688
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 417
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 989
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 123
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 149
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 41
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 141
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 65
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 174
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 378
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()
```
And also it spams the ServiceHid GetPlayerLedPattern in the Log:
```
<...>
00:09:04.248 |S| HLE.HostThread.6 ServiceHid GetPlayerLedPattern: Stubbed. {npadId: Player1 ; ledPattern: 1}
00:09:04.273 |S| HLE.HostThread.6 ServiceHid GetPlayerLedPattern: Stubbed. {npadId: Player1 ; ledPattern: 1}
00:09:04.292 |S| HLE.HostThread.6 ServiceHid GetPlayerLedPattern: Stubbed. {npadId: Player1 ; ledPattern: 1}
00:09:04.313 |S| HLE.HostThread.6 ServiceHid GetPlayerLedPattern: Stubbed. {npadId: Player1 ; ledPattern: 1}
00:09:04.338 |S| HLE.HostThread.6 ServiceHid GetPlayerLedPattern: Stubbed. {npadId: Player1 ; ledPattern: 1}
00:09:04.359 |S| HLE.HostThread.6 ServiceHid GetPlayerLedPattern: Stubbed. {npadId: Player1 ; ledPattern: 1}
00:09:04.383 |S| HLE.HostThread.6 ServiceHid GetPlayerLedPattern: Stubbed. {npadId: Player1 ; ledPattern: 1}
00:09:04.412 |S| HLE.HostThread.6 ServiceHid GetPlayerLedPattern: Stubbed. {npadId: Player1 ; ledPattern: 1}
<...> (etc...)
```
Otherwise, it's somewhat playable.

![Ryujinx Screenshot 2020 12 03 - 18 54 27 22](https://user-images.githubusercontent.com/9445013/101063214-3debd200-359b-11eb-95c2-aad7116ee775.png)
![Ryujinx Screenshot 2020 12 03 - 18 54 57 98](https://user-images.githubusercontent.com/9445013/101063376-64117200-359b-11eb-825b-399eaa24b7c8.png)

(If I needed to use a certain template, I'm sorry - I'm new to reporting something like this.)

**Comment by mantazzo** [comment]
As of 1.0.7000, the game seems to run mostly fine now (even performance wise), though the BGRA textures on characters are still a problem.

**Comment by GitHubDan01** [comment]
> As of 1.0.7000, the game seems to run mostly fine now (even performance wise), though the BGRA textures on characters are still a problem.
> 
> EDIT: Trying it out now with 1.0.7008 and the characters are now fixed. Seems to be fully playable now.

using vulkan or opengl a lot is invisible all white in the fight scenes

**Comment by EmulationFanatic** [comment]
Updated

**Comment by antonioflaviotc** [comment]
I'm trying to play the game but the characters aren't showing. Would you help me?

Screenshot:

![image](https://user-images.githubusercontent.com/96091438/185460919-ffb124ad-973b-4fa3-8065-1bb3c8257c89.png)

**Comment by MetrosexualGarbodor** [comment]
@antonioflaviotc join [discord](https://discord.gg/ryujinx) for help.

**Comment by AER2K04** [comment]
Does anyone know how to fix the invisible characters problem in the game I tried discord but it ain't working

**Comment by EmulationFanatic** [comment]
> Does anyone know how to fix the invisible characters problem in the game I tried discord but it ain't working

Only AMD GPUs in Windows are afflicted with this issue. Your options, until it's fixed in the emulator, are to use Linux or switch to Nvidia.

**Comment by Chocdino** [comment]
UH crashing on Vulkan. 
[Ryujinx_1.1.596_2023-01-26_22-22-18.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/10515186/Ryujinx_1.1.596_2023-01-26_22-22-18.log)

**Comment by mrTerryBogard** [comment]
Good day!

Ryujinx: 1.1.1202
Fifmware: 17.0.0
Vulcan: Crash after startup when the screen is black.
OpenGL: During training or not, it is impossible to fight. It lags so much that it barely loads, showing a slideshow.

P.S. Vulkan in CEMU POKKÉN TOURNAMENT has no problems. I understand that the systems are different, but... This is not the first game that lags from 1.1.1100 and earlier. And I am 100% sure that YUZU will not have problems, as was the case with МАРИО И СОНИК НА ОЛИМПИСКИХ ИГРАХ 202 В ТОКИО.

**Comment by mrTerryBogard** [comment]
> 1.1.1202

I already wrote about the problem with the game, but then Ryujinx had version 1.1.1202. Now on version 1.1.1214 I checked it even better - like Mario + Rabbids: Kingdom Battle. Yes, exactly, OpenGL now hangs stupidly on the loading screen and it’s impossible to enter the menu. This time the game is without update.

**Comment by mrTerryBogard** [comment]
> Good day!
> 
> Ryujinx: 1.1.1202 Fifmware: 17.0.0 Vulcan: Crash after startup when the screen is black. OpenGL: During training or not, it is impossible to fight. It lags so much that it barely loads, showing a slideshow.
> 
> UPDATE: Now explain your crappy emulation! WHY IN YUZU ON VULKAN THE BATTLE IS CARRIED OUT WITH PURE EMULATION??? WHAT DO YOU UPDATE THERE SEVERAL TIMES A DAY?

I already wrote about the problem with the game, but then Ryujinx had version 1.1.1202. Now on version 1.1.1214 I checked it even better - like Mario + Rabbids: Kingdom Battle. Yes, exactly, OpenGL now hangs stupidly on the loading screen and it’s impossible to enter the menu. This time the game is without update.

**Comment by KayLilac** [comment]
Ryujinx version: 1.1.1217

Integrated GPU: Intel(R) Iris(R) Xe Graphics (driver version: 31.0.101.5333)

Issue:
everytime i try to start up the game it "kills" my gpu (i can't find a good way to describe it but basically it gets messed up) and ryujinx crashes

Screenshots:
![Captura de tela 2024-03-02 115022](https://github.com/Ryujinx/Ryujinx-Games-List/assets/149713452/dae93860-d104-4aa6-b805-e7e950e10be4)

**Comment by P0W3** [comment]
The game runs way too fast with VSync off.

**Game Update Version:** 1.3.3
**System Version:** 17.0.1
**Version of Ryujinx:** 1.1.1217
**Graphics Backend:** Vulkan
**CPU:** AMD Ryzen 5 3600X 6-Core Processor 3.80 GHz
**RAM:** 16 GB
**GPU:** NVIDIA GeForce GTX 1650 (12 GB of GPU Memory)

**Log File:** [Ryujinx_1.1.1217_2024-03-06_17-21-40.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/14516470/Ryujinx_1.1.1217_2024-03-06_17-21-40.log)

**Comment by Manostion** [comment]
Hello everyone,

I hope this is the right place to post this, but I have a very specific issue with the game that is unrelated to performance or visuals:

While it worked perfectly fine the first day or two, I now am unable to play the daily challenges due to an issue regarding the system time. I tried several different time zones and other settings, including turning `VSync`, `FS Integrity Checks` and `Ignore Missing Services` on/off, as well as starting the game both in Docked and Handheld modes, but to no avail. This has been persistent for about a week at this point.

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/21081028/318b28a2-2ab9-4289-aaed-ed9b9ccf753b)

**Game Version:** 1.3.3.130531
**System Version:** 18.0.0
**Ryujinx Version:** 1.1.1332
**Graphics Backend:** Vulkan
**GPU:** NVIDIA GeForce RTX 4060 Ti (dGPU - 16 GB)
**CPU:** AMD Ryzen 7 3700X 8-Core Processor, 3600 MHz, 16 Logical Processors
**Main Board:** B450 TOMAHAWK MAX

**Log File:** [Ryujinx_1.1.1332_2024-06-15_23-26-20.log](https://github.com/user-attachments/files/15856635/Ryujinx_1.1.1332_2024-06-15_23-26-20.log)

**Comment by KayLilac** [comment]
> Ryujinx version: 1.1.1217
> 
> Specs:
> 
> CPU:11th Gen Intel(R) Core(TM) i5-1135G7
> 
> RAM: 8gb
> 
> Integrated GPU: Intel(R) Iris(R) Xe Graphics (driver version: 31.0.101.5333)
> 
> Issue: everytime i try to start up the game it "kills" my gpu (i can't find a good way to describe it but basically it gets messed up) and ryujinx crashes
> 
> Screenshots: ![Captura de tela 2024-03-02 115022](https://private-user-images.githubusercontent.com/149713452/310219388-dae93860-d104-4aa6-b805-e7e950e10be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNDQzMzcsIm5iZiI6MTcyMTM0NDAzNywicGF0aCI6Ii8xNDk3MTM0NTIvMzEwMjE5Mzg4LWRhZTkzODYwLWQxMDQtNGFhNi1iODA1LWU3ZTk1MGUxMGJlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQyMzA3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTVlOTYwNTc0NmZhMjM3ODZhZmZiNzE1NzE0MTEwZDYzZTNkNmQzMjczODcwNGE2YTU2MTBhYWMwMmExMjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Isgc-wFOXp43DCPYftXGnFsXwzOkQbiFrcYljQZnup0)

my dumbass has forgotten to provide a log file, i remembered this today XD

[Ryujinx_1.1.1353_2024-07-18_20-04-28.log](https://github.com/user-attachments/files/16289936/Ryujinx_1.1.1353_2024-07-18_20-04-28.log)

also, my system specs have changed since then, i now have 24gb of ram
