### ISSUE TITLE
Untitled Goose Game

### ISSUE THREAD

**Issue by r3ntonboy** [Ryujinx/Ryujinx-Games-List#535]
### **Untitled Goose Game**

**Current on master:** 1.0.4114

Game runs pretty nice. Just slow.

**Screenshots:**

![1](https://user-images.githubusercontent.com/35672114/78098183-ab17e980-73b4-11ea-86c0-d0193990b5a8.jpg)
![2](https://user-images.githubusercontent.com/35672114/78098187-ac491680-73b4-11ea-9251-00530e5fee82.jpg)
![4](https://user-images.githubusercontent.com/35672114/78098190-ace1ad00-73b4-11ea-88cc-089b6768710c.jpg)
![5](https://user-images.githubusercontent.com/35672114/78098193-ae12da00-73b4-11ea-9888-35bcde172314.jpg)
![6](https://user-images.githubusercontent.com/35672114/78098194-af440700-73b4-11ea-97a9-124dfa11e78e.jpg)

**Log File:**

[Untitled Goose Game.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4412721/Untitled.Goose.Game.zip)

**Comment by syberphunk** [comment]
Game Update Version : 1.0.7
Current on Build Version : 1.0.0-ldn1 and 1.0.5428
ryujinx GUI crashes when adding game update 1.0.7, freezes and then have to force close - update is then not added.

Last error returned.
00:00:09.986 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at LibHac.FsSystem.StorageExtensions.ToArray[T](IStorage storage)
   at LibHac.FsSystem.RomFs.RomFsDictionary`1..ctor(IStorage bucketStorage, IStorage entryStorage)
   at LibHac.FsSystem.RomFs.HierarchicalRomFileTable`1..ctor(IStorage dirHashTable, IStorage dirEntryTable, IStorage fileHashTable, IStorage fileEntryTable)
   at LibHac.FsSystem.RomFs.RomFsFileSystem..ctor(IStorage storage)
   at LibHac.FsSystem.NcaUtils.Nca.OpenFileSystem(IStorage storage, NcaFsHeader header)
   at Ryujinx.Ui.TitleUpdateWindow.AddUpdate(String path, Boolean showErrorDialog) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx\Ui\TitleUpdateWindow.cs:line 101
   at Ryujinx.Ui.TitleUpdateWindow.AddButton_Clicked(Object sender, EventArgs args) in Z:\Data\Dev\Switch\Ryujinx\Ryujinx\Ui\TitleUpdateWindow.cs:line 162
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

Hardware Specs :
CPU: i7 8700k
GPU: NVIDIA 1080
RAM: 32GB

Log file :

[Ryujinx_2020-09-25_22-49-15.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5286719/Ryujinx_2020-09-25_22-49-15.log)

[Ryujinx_2020-09-26_09-56-25.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5286721/Ryujinx_2020-09-26_09-56-25.log)
