### ISSUE TITLE
Sonic Forces

### ISSUE THREAD

**Issue by AcK77** [Ryujinx/Ryujinx-Games-List#56]
Current State on `master`: 

You will get here https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Graphics/Gal/Shader/GlslDecompiler.cs#L866: 

```
System.InvalidOperationException : 'Shader attribute offset 480 is invalid.'
```

**Comment by AcK77** [comment]
```Unhandled Exception: ChocolArm64.Exceptions.VmmPageFaultException: Tried to access unmapped address 0xfffffffffffff000!
   at ChocolArm64.Memory.MemoryManager.HandleNullPte(Int64 position) in C:\projects\ryujinx\ChocolArm64\Memory\MemoryManager.cs:line 520
   at ChocolArm64.Memory.MemoryManager.GetPhysicalAddress(Int64 virtualAddress) in C:\projects\ryujinx\ChocolArm64\Memory\MemoryManager.cs:line 470
   at ChocolArm64.Memory.MemoryManager.EnsureRangeIsValid(Int64 position, Int64 size) in C:\projects\ryujinx\ChocolArm64\Memory\MemoryManager.cs:line 695
   at Ryujinx.Graphics.NvGpuEngine3d.UploadVertexArrays(NvGpuVmm Vmm, GalPipelineState State) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 715
   at Ryujinx.Graphics.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 126
   at Ryujinx.Graphics.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 84
   at Ryujinx.Graphics.MacroInterpreter.Send(NvGpuVmm Vmm, Int32 Value) in C:\projects\ryujinx\Ryujinx.Graphics\MacroInterpreter.cs:line 415
   at Ryujinx.Graphics.MacroInterpreter.Step(NvGpuVmm Vmm, Int32[] Mme) in C:\projects\ryujinx\Ryujinx.Graphics\MacroInterpreter.cs:line 192
   at Ryujinx.Graphics.MacroInterpreter.Execute(NvGpuVmm Vmm, Int32[] Mme, Int32 Position, Int32 Param) in C:\projects\ryujinx\Ryujinx.Graphics\MacroInterpreter.cs:line 82
   at Ryujinx.Graphics.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 188
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 120
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

[SonicF.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/2567118/SonicF.txt)

Updated state by @frykillr

**Comment by HorrorTroll** [comment]
Updated

**Comment by HorrorTroll** [comment]
Updated

**Comment by AcK77** [comment]
Need an update.

**Comment by AcK77** [comment]
Updated.

**Comment by AcK77** [comment]
Updated

**Comment by B3astTech** [comment]
Updated

**Comment by benderscruffy** [comment]
using 1.0.6020
nothing but a black screen now

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Anoahel** [comment]
it crashed after it showed the sonic team logo

**Comment by zanewelch661** [comment]
zanewelch

**Comment by sanchezanto** [comment]
como se descarga
