### ISSUE TITLE
Megaton Rainfall

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#562]
#### Current on `master` : 1.0.4123

After ~5 minutes of loading, a black screen with crackly audio intro begins. A couple of minutes later Ryujinx crashes with the error below.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.VoiceContext.GetBufferData(MemoryManager memory, Int32 maxSamples, Int32& samplesCount) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\VoiceContext.cs:line 70
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.AppendMixedBuffer(Int64 tag) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 354
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.UpdateAudio() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 330
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.IAudioRenderer.RequestUpdateAudioRenderer(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager\IAudioRenderer.cs:line 224
   --- End of inner exception stack trace ---
```

#### Log file :

[MegatonRainfall.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4420920/MegatonRainfall.zip)

**Comment by benderscruffy** [comment]
black screen but i can hear music and sound fx

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6846

**Comment by EmulationFanatic** [comment]
Same status on 1.1.206
