### ISSUE TITLE
One Piece Pirate Warriors 3

### ISSUE THREAD

**Issue by AcK77** [Ryujinx/Ryujinx-Games-List#57]
Current State on `master`: 

```
ChocolArm64.Exceptions.VmmPageFaultException : 'Tried to access unmapped address 0xffffffffffffffff!'
```

After a call to `IAudioRenderer: RequestUpdateAudioRenderer`.

Same state inside `sched` but the execution is faster.

**Comment by AcK77** [comment]
Need an update.

**Comment by AcK77** [comment]
Updated.

**Comment by B3astTech** [comment]
One Piece Pirate Warriors 3
Current on master :

*It booted and was able to create a save and go into intro but as soon as it hit the loading screen it crashed and Turning Stubs on doesn't help it get in-game*


```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'position')
   at ARMeilleure.Memory.MemoryManager.ReadBytes(Int64 position, Int64 size) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 529
   at ARMeilleure.Memory.MemoryManager.GetSpan(UInt64 address, UInt64 size) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 558
   at Ryujinx.Graphics.Gpu.Engine.Methods.CopyBuffer(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodCopyBuffer.cs:line 70
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 74
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 189
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 309
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 200
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 336
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![Annotation 2020-03-20 142929](https://user-images.githubusercontent.com/45114656/77207835-a3546d00-6ab7-11ea-8033-f400f5382376.png)

![Annotation 2020-03-20 142951](https://user-images.githubusercontent.com/45114656/77207842-a7808a80-6ab7-11ea-94fa-ed7594bc7531.png)


#### Log file :

[Non Stub.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4361866/Non.Stub.log)

**Comment by GoffyDude** [comment]
## One Piece Pirate Warriors 3

#### Current on `master` : 1.0.4532

Game is now fully playable. Cutscenes still suffer from nvdec bug.

#### Screenshots :

![2020-05-09 23_59_55-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492257-bf70c100-9253-11ea-8eac-17780b20bcb5.png)
![2020-05-10 00_00_08-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492258-c0a1ee00-9253-11ea-855d-e7559dad9bc3.png)
![2020-05-10 00_00_15-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492259-c0a1ee00-9253-11ea-9631-3f73757a2095.png)
![2020-05-10 00_00_19-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492260-c5ff3880-9253-11ea-957d-299fd89fc685.png)
![2020-05-10 00_00_33-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492262-cb5c8300-9253-11ea-805c-c466cc4c8ee0.png)
![2020-05-10 00_00_46-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492263-cbf51980-9253-11ea-9570-aaf9f85ce622.png)
![2020-05-10 00_01_12-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492267-d3b4be00-9253-11ea-9a85-7c30d8fea2df.png)
![2020-05-10 00_01_31-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492284-de6f5300-9253-11ea-9149-355dfa22f9c4.png)
![2020-05-10 00_02_03-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492307-e929e800-9253-11ea-8002-ba6490ad59e2.png)
![2020-05-10 00_03_17-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492309-e929e800-9253-11ea-8c3a-c52c0a2aec51.png)
![2020-05-10 00_03_37-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492330-f3e47d00-9253-11ea-86a6-54abb9572a38.png)
![2020-05-10 00_03_52-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492338-fe9f1200-9253-11ea-8481-67f767a15b24.png)
![2020-05-10 00_04_37-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492341-0959a700-9254-11ea-902d-ca0dfeabc530.png)
![2020-05-10 00_04_50-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492345-124a7880-9254-11ea-9d53-220187db7f45.png)
![2020-05-10 00_04_58-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492353-1b3b4a00-9254-11ea-9747-fe9125e83d2f.png)
![2020-05-10 00_06_08-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492357-21312b00-9254-11ea-9e05-115cd75b9b54.png)
![2020-05-10 00_06_56-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492362-2aba9300-9254-11ea-8e99-d1f2fa126081.png)
![2020-05-10 00_07_27-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492365-3312ce00-9254-11ea-896a-450ca4c8329f.png)
![2020-05-10 00_08_02-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492366-3c039f80-9254-11ea-90eb-043b1ee00804.png)
![2020-05-10 00_08_17-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492369-402fbd00-9254-11ea-8b03-29f7ecd373f4.png)
![2020-05-10 00_09_19-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492377-4756cb00-9254-11ea-99ea-cfda4db2c259.png)
![2020-05-10 00_10_18-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492382-4f166f80-9254-11ea-8656-ba11ce33a824.png)
![2020-05-10 00_15_07-Ryujinx 1 0 4532 - One Piece_ Pirate Warriors 3 Deluxe Edition v1 0 0 (010077400](https://user-images.githubusercontent.com/62343878/81492385-56d61400-9254-11ea-886f-0917a25888ef.png)


#### Log file :

[OPPW3.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4605241/OPPW3.zip)

**Comment by GoffyDude** [comment]
Updated
