### ISSUE TITLE
Manticore - Galaxy on Fire

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#603]
#### Current on `master` : 1.0.4142

Crashes on launch.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: android.gui.IGraphicBufferProducer 2
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/716

#### Log file :

[Manticore.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4435415/Manticore.zip)

**Comment by GoffyDude** [comment]
Needs update

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by benderscruffy** [comment]
using 1.1.26
crashes out at the same spot but now with a different error
[Ryujinx_1.1.26_2022-02-13_11-40-21.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8054910/Ryujinx_1.1.26_2022-02-13_11-40-21.log)
0:01:30.945 |E| GUI.RenderLoop Gpu GLERROR: DebugSeverityHigh: glBufferData parameter <size> has an invalid value '-173015040': must be greater than or equal to 0 (GL_INVALID_VALUE)
CallStack=   at System.Environment.get_StackTrace()
   at Ryujinx.Graphics.OpenGL.Debugger.GLDebugHandler(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.OpenGL\Debugger.cs:line 66
   at Ryujinx.Graphics.OpenGL.Buffer.Create(Int32 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.OpenGL\Buffer.cs:line 40
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_2(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 59
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131

**Comment by matrixvk** [comment]
The game works fine on 1.1.1125 and I finished it on Ryujinx. Seems we can change the tag to status-playable now.
![屏幕截图 2024-02-04 120739](https://github.com/Ryujinx/Ryujinx-Games-List/assets/33417241/5111d99a-666a-4e4a-a358-403d1b854ce3)
