### ISSUE TITLE
Mahjong Solitaire Refresh

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#607]
#### Current on `master` : 1.0.4142

Crashes on launch with the below error in the console. Note: this error did not show up in the log.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.TranslatedFunction.Execute(ARMeilleure.State.ExecutionContext)
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass129_0.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[MSR.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4438133/MSR.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6846

**Comment by EmulationFanatic** [comment]
Same status on 1.1.205

**Comment by EmulationFanatic** [comment]
Same status on 1.1.451
