### ISSUE TITLE
Titan Quest

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#622]
#### Current on `master` : 1.0.4142

Crashes on launch or shortly after getting to the initial menus.

1st launch:
```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: Unable to delete file C:\Users\[redacted]\AppData\Roaming\Ryujinx\bis\user\save\000000000000016e\1
   at LibHac.FsSystem.LocalFileSystem.EnsureDeleted(FileSystemInfo entry)
   at LibHac.FsSystem.LocalFileSystem.DeleteDirectoryInternal(DirectoryInfo dir, Boolean recursive)
   at LibHac.FsSystem.LocalFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.SubdirectoryFileSystem.DeleteDirectoryRecursivelyImpl(U8Span path)
   at LibHac.Fs.FileSystemBase.DeleteDirectoryRecursively(U8Span path)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.SynchronizeDirectory(U8Span dest, U8Span src)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.Initialize(Boolean isPersistentSaveData, Boolean isUserSaveData)
   at LibHac.FsSystem.DirectorySaveDataFileSystem.CreateNew(DirectorySaveDataFileSystem& created, IFileSystem baseFileSystem, Boolean isPersistentSaveData, Boolean isUserSaveData)
   at LibHac.FsService.Creators.SaveDataFileSystemCreator.Create(IFileSystem& fileSystem, ISaveDataExtraDataAccessor& extraDataAccessor, IFileSystem sourceFileSystem, UInt64 saveDataId, Boolean allowDirectorySaveData, Boolean useDeviceUniqueMac, SaveDataType type, ITimeStampGenerator timeStampGenerator)
   at LibHac.FsService.FileSystemProxyCore.OpenSaveDataFileSystem(IFileSystem& fileSystem, SaveDataSpaceId spaceId, UInt64 saveDataId, String saveDataRootPath, Boolean openReadOnly, SaveDataType type, Boolean cacheExtraData)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystemImpl(IFileSystem& fileSystem, UInt64& saveDataId, SaveDataSpaceId spaceId, SaveDataAttribute& attribute, Boolean openReadOnly, Boolean cacheExtraData)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystem3(IFileSystem& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute, Boolean openReadOnly)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystem2(IFileSystem& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute, Boolean openReadOnly)
   at LibHac.FsService.FileSystemProxy.OpenSaveDataFileSystem(IFileSystem& fileSystem, SaveDataSpaceId spaceId, SaveDataAttribute& attribute)
   at Ryujinx.HLE.HOS.Services.Fs.IFileSystemProxy.OpenSaveDataFileSystem(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Fs\IFileSystemProxy.cs:line 244
```

2nd launch:
```
ServiceAm SetTerminateResult: Result = 0x000002a2 (2162-0001).
00:06:17.726 | HLE.HostThread.8 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x000444a8 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   sdk:0x00044560 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, char const*, ...)
   sdk:0x000445f0 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   main:0x0027f768 Sub0000000008283768
   sdk:0x00091b48 Sub000000000a796b48
   sdk:0x00095b24 Sub000000000a79ab24
   ??? Sub0000000000000000
```
3rd launch it gave a memory access violation that did not write to the log.

#### Screenshots :

![2020-04-06 16_27_05-Ryujinx 1 0 4142 _ Titan Quest _ 0100605008268000](https://user-images.githubusercontent.com/62343878/78611323-ecc8ea00-7823-11ea-8fdf-0ebf55101e0b.png)
![2020-04-06 16_27_16-Ryujinx 1 0 4142 _ Titan Quest _ 0100605008268000](https://user-images.githubusercontent.com/62343878/78611332-f2263480-7823-11ea-938e-d2e2d2878737.png)

#### Log file :

[TitanQuest.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4441121/TitanQuest.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6906

**Comment by EmulationFanatic** [comment]
Updated. Playable and LAN mode works.
