### ISSUE TITLE
Trials Rising

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#633]
#### Current on `master` : 1.0.4154

Crashes on launch with the below error.

```
HLE.HostThread.0 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x00175f00 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   sdk:0x00175fc4 Sub0000000011b0afc4
   sdk:0x00176060 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   sdk:0x00306dc8 Sub0000000011c9bdc8
   sdk:0x0030c364 nn::nifm::detail::GetNetworkConnectionPointer(nn::nifm::NetworkConnection**)
   sdk:0x0030d414 nn::nifm::SubmitNetworkRequest()
   main:0x01b3d8d0 Sub0000000009b418d0
   main:0x01b3cdec Sub0000000009b40dec
   main:0x00c21088 Sub0000000008c25088
   main:0x01ff4edc Sub0000000009ff8edc
   main:0x020275dc Sub000000000a02b5dc
   main:0x02027400 Sub000000000a02b400
   main:0x00ce01b8 Sub0000000008ce41b8
   main:0x017b360c Sub00000000097b760c
   main:0x000007a0 Sub00000000080047a0
   main:0x000003c4 Sub00000000080043c4
   main:0x0000035c nnMain
   sdk:0x00289ddc nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0


00:00:14.397 | HLE.HostThread.3 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:00:14.397 | HLE.HostThread.2 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:00:14.397 | HLE.HostThread.4 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:00:14.423 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcSystem.cs:line 285
   at Break64(SvcHandler , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcHandler.cs:line 23
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 96
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1144
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 162
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[TrialsRising.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4444427/TrialsRising.zip)

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6455

**Comment by zemzema** [comment]
![ryujinx_capture_2021-09-30_16-31-59](https://user-images.githubusercontent.com/33085810/135475782-754cf8d2-82a9-4dc8-8115-7b1461026133.png)
![ryujinx_capture_2021-09-30_16-33-10](https://user-images.githubusercontent.com/33085810/135475798-f5d48dae-f0f5-4727-b960-5ff5935bfa7e.png)
![ryujinx_capture_2021-09-30_16-33-23](https://user-images.githubusercontent.com/33085810/135475818-1465384a-da0e-4a1c-9460-10dc5e292b36.png)
![ryujinx_capture_2021-09-30_16-33-34](https://user-images.githubusercontent.com/33085810/135475830-c3d8abfd-dc0f-43a6-b751-8676551876d9.png)
![ryujinx_capture_2021-09-30_16-33-45](https://user-images.githubusercontent.com/33085810/135475840-9a0f9914-70e3-4d82-86e4-e0a512ee66fe.png)
![ryujinx_capture_2021-09-30_16-34-12](https://user-images.githubusercontent.com/33085810/135475842-9793c26b-abc0-4771-a37d-f5bd5714866a.png)

[trials_rising.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7260288/trials_rising.log)

(status-ingame)

**Comment by jonas418** [comment]
It seems that the graphics issues has been resolved.
Not sure which version fixed this, but at least working good since 1.1.80.

Here's some screenshots:
![ryujinx_capture_2022-03-21_04-47-22](https://user-images.githubusercontent.com/5829163/160328259-f18fc77f-ebde-4469-b8c8-61b1c0e8a883.png)
![ryujinx_capture_2022-03-21_04-47-59](https://user-images.githubusercontent.com/5829163/160328280-f8b2672c-d834-460c-b251-986e9f38035d.png)
![ryujinx_capture_2022-03-21_04-48-25](https://user-images.githubusercontent.com/5829163/160328294-a8b584a8-bd09-4af0-9734-5fc7a54a937c.png)
![ryujinx_capture_2022-03-21_04-56-44](https://user-images.githubusercontent.com/5829163/160328308-e16ec434-4fd9-40c9-a821-f4a0dd212d2e.png)

**Comment by MutantAura** [comment]
Are the crashes reported above still a concern? If both the gfx issues and the crashes are resolved I can mark this as playable.

**Comment by jonas418** [comment]
> Are the crashes reported above still a concern? If both the gfx issues and the crashes are resolved I can mark this as playable.

I can't personally recall any crashes in the game so far.
Since the game was more or less unplayable prior to 1.1.80 due to the graphical issues I didn't do much testing in the past.

I think it's safe to mark the game as playable and remove the crash label.

**Comment by Eli0t77** [comment]
Needs rechecking as missing in game gfx make the game unplayable

Ryujinx version 1.1.80
Base game crashes
Endless black screen with game update 1.0.13

Ryujinx version 1.1.109
Base game crashes
With game update it launches but 90% of the in game gfx are missing
Only error in the log is about votevtg not being implemented 
![ryujinx_capture_2022-07-18_23-35-34](https://user-images.githubusercontent.com/99099894/179629396-e92d0272-9bfa-46ee-aa21-6fe2cfdbabae.png)

![ryujinx_capture_2022-07-18_23-34-54](https://user-images.githubusercontent.com/99099894/179629463-323e12dd-432b-4041-afff-f3a6d1c324df.png)

**Comment by gdkchan** [comment]
Does it print some message in the console when it crashes? If so it would be useful to know what's the message.

**Comment by Eli0t77** [comment]
Sorry I just deleted everything. Something about an illegal opcode or instruction. Since I can't test this on the latest build or any possible fix untill I get a new pc I'll leave it for someone else

**Comment by jonas418** [comment]
I just re-tested the game.
Game update version 1.0.12 and 1.0.13 using Ryujinx versions 1.1.160 and 1.1.182.
Both of which are working flawless for me. No noticeable graphic issues.
However, it does crash when only using the base game without updates.

Logs using base game only:
[Ryujinx_1.1.182_2022-07-19_03-22-55.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9136699/Ryujinx_1.1.182_2022-07-19_03-22-55.log)

**Comment by AcK77** [comment]
Reported in: https://github.com/Ryujinx/Ryujinx/issues/6125

> hroughout the game shadows are flashing constantly which makes the lighting incorrect aswell
here is a few renderdocs to look at
https://mega.nz/file/1iAEVY4B#aYA9BrTJ1d-fiPnBaBWReNZDVup8A4Qsfkg3IH9-TOU
https://mega.nz/file/Aj4H1J7b#af4VSYbjA00tw9NYMB2qILIhbFpy0Nzb_nblli0g_-o
https://mega.nz/file/I2okVZ7A#9nZVgCRFhd07yq6KbKHjuCEZauisU2K0mf1QnQr5g3c

### Log file

[Ryujinx_1.1.1109_2024-01-14_15-53-26.log](https://github.com/Ryujinx/Ryujinx/files/13930779/Ryujinx_1.1.1109_2024-01-14_15-53-26.log)

### OS

Windows 10

### Ryujinx version

1.1.1106

### Game version

1.0

### CPU

Ryzen 5 5700X

### GPU

NVIDIA RTX 2060

### RAM

16gb
