### ISSUE TITLE
Rogue Trooper Redux

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#647]
#### Current on `master` : 1.0.4160

Crashes while loading initial splash screens.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'position')
   at ARMeilleure.Memory.MemoryManager.ReadBytes(Int64 position, Int64 size) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 529
   at ARMeilleure.Memory.MemoryManager.GetSpan(UInt64 address, UInt64 size) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 558
   at Ryujinx.Graphics.Gpu.Memory.MemoryAccessor.ReadInt32(UInt64 gpuVa) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryAccessor.cs:line 73
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 187
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 332
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-04-08 05_05_38-Ryujinx 1 0 4160 _ Rogue Trooper Redux _ 01001CC00416C000](https://user-images.githubusercontent.com/62343878/78777396-afb14480-7956-11ea-837c-074c3ac304a0.png)

#### Log file :

[RogueTrooperRedux.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4450072/RogueTrooperRedux.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6906

**Comment by EmulationFanatic** [comment]
Updated
