### ISSUE TITLE
Higurashi no Naku Koro ni Hō

### ISSUE THREAD

**Issue by gdkchan** [Ryujinx/Ryujinx-Games-List#66]
Needs ISelfController 62 (SetIdleTimeDetectionExtension).
After that, it shows some logos, then eventually it shows this message:

![image](https://user-images.githubusercontent.com/5624669/45668333-b8cb8e00-baf2-11e8-8314-f939176394c7.png)

After that it needs nvdec and vic.

**Comment by HorrorTroll** [comment]
Updated, the games is nearly playable

**Comment by HorrorTroll** [comment]
Build Version : 1.0.4224

Crash when boot the game, so no longer in-game any more
```
00:00:57.701 | GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Runtime.InteropServices.Marshal.CopyToManaged[T](IntPtr source, T[] destination, Int32 startIndex, Int32 length)
   at ARMeilleure.Memory.MemoryManager.ReadBytes(Int64 position, Int64 size) in D:\Games\Ryujinx-HorrorTroll\ARMeilleure\Memory\MemoryManager.cs:line 549
   at ARMeilleure.Memory.MemoryManager.GetSpan(UInt64 address, UInt64 size) in D:\Games\Ryujinx-HorrorTroll\ARMeilleure\Memory\MemoryManager.cs:line 564
   at Ryujinx.Graphics.Gpu.Memory.PhysicalMemory.GetSpan(UInt64 address, UInt64 size) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\Memory\PhysicalMemory.cs:line 32
   at Ryujinx.Graphics.Gpu.Memory.Buffer.Invalidate() in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 160
   at Ryujinx.Graphics.Gpu.Memory.Buffer..ctor(GpuContext context, UInt64 address, UInt64 size) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 52
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CreateBuffer(UInt64 address, UInt64 size) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 350
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.TranslateAndCreateBuffer(UInt64 gpuVa, UInt64 size) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 290
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.SetGraphicsUniformBuffer(Int32 stage, Int32 index, UInt64 gpuVa, UInt64 size) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 202
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferBind(GpuState state, Int32 argument, ShaderType type) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferBind.cs:line 81
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferBindVertex(GpuState state, Int32 argument) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferBind.cs:line 15
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 84
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, GpuState shadowState, Int32 value) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 511
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state, GpuState shadowState) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 185
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state, GpuState shadowState) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 103
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CachedMacro.Execute(Int32[] mme, ShadowRamControl shadowCtrl, GpuState state, GpuState shadowState) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 73
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 230
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 320
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in D:\Games\Ryujinx-HorrorTroll\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 225
   at Ryujinx.Ui.GLRenderer.Render() in D:\Games\Ryujinx-HorrorTroll\Ryujinx\Ui\GLRenderer.cs:line 337
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by Tsu-S** [comment]
Still broken

**Comment by DemiurgeZ** [comment]
Audio is still broken. The game crashes at the home menu and does not make it into main gameplay. The label should be "status-menus".

**Comment by EmulationFanatic** [comment]
> Audio is still broken. The game crashes at the home menu and does not make it into main gameplay. The label should be "status-menus".

Can you upload the log file containing the crash?

**Comment by DemiurgeZ** [comment]
> Can you upload the log file containing the crash?

Sure. Here is the log. [Ryujinx_1.0.6732_2021-02-27_02-54-30.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/6051949/Ryujinx_1.0.6732_2021-02-27_02-54-30.log)

**Comment by RabbidHype** [comment]
I've tried this, and it seems like my main issues are:

Laggy/choppy audio (Which is known and common already), though I noticed that setting the Audio backend to dummy makes the game run smoother some reason. (Also it seems the opening movie doesn't play if there's no audio to sync up to/with apparently, as with audio on, it does play, albeit choppily though.)

There's something I'm doing when I'm in-game that's causing a crash as well, but I haven't the slightest idea what it could be either, so I'm not sure how to repeat it in any way.

But this noted, for the most part again, with the Audio Backend set to just dummy, the game runs smoother, and I have pretty low specs (not to mention playing on a laptop as well) so this was a surprise to me.

**Comment by ooa113y** [comment]
As of Ryujinx 1.0.6969, the audio is no longer broken and the game is seemingly playable now. However, this requires the game to be updated to at least v1.1.0. The original release still exhibits the choppy audio issues.

**Comment by lu2905363** [comment]
> As of Ryujinx 1.0.6969, the audio is no longer broken and the game is seemingly playable now. However, this requires the game to be updated to at least v1.1.0. The original release still exhibits the choppy audio issues. The OpenAL backend still exhibits audio issues even on the latest update, however SDL2 and SoundIO are both fine with an up-to-date game.

Thank you very much. Been able to launch the game without any annoying audio issue as what you've instructed.
