### ISSUE TITLE
Touhou Kobuto V: Burst Battle

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#670]
#### Current on `master` : 1.0.4168

Game renders all menus and intro cutscenes perfectly, and then crashes as the in-game play is about to begin.

```
HLE.HostThread.2 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcSystem.cs:line 285
   at Break64(SvcHandler , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcHandler.cs:line 23
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 96
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1144
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 162
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```
#### Screenshots :

![2020-04-10 06_57_29-Ryujinx 1 0 4168 _ Touhou Kobuto V_ Burst Battle _ 010010F004022000](https://user-images.githubusercontent.com/62343878/78992582-c1cae880-7af8-11ea-84a8-7e6a8f60bc44.png)
![2020-04-10 06_57_37-Ryujinx 1 0 4168 _ Touhou Kobuto V_ Burst Battle _ 010010F004022000](https://user-images.githubusercontent.com/62343878/78992586-c8596000-7af8-11ea-9587-e78efaec0a7d.png)
![2020-04-10 06_58_07-](https://user-images.githubusercontent.com/62343878/78992597-cee7d780-7af8-11ea-8c9b-33145b2f8e98.png)

#### Log file :

[TKVBB.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4461605/TKVBB.zip)

**Comment by EmulationFanatic** [comment]
Updated
