### ISSUE TITLE
Blades of Time

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#678]
#### Current on `master` : 1.0.4168

Crashes on launch.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: android.gui.IGraphicBufferProducer 2
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/716

#### Log file :

[BladesofTime.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4462228/BladesofTime.zip)

**Comment by GoffyDude** [comment]
Needs update

**Comment by GoffyDude** [comment]
## Blades of Time

#### Current on `master` : 1.0.4532

Game gets a little further than it used to now, and crashes with the error below.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 12

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x0036976c nn::sf::hipc::client::Hipc2ClientCoreProcessor<(nn::sf::hipc::detail::MessageType)6, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 34, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<4, 33, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 12l> >, 16ul, 16ul, true>, std::__1::tuple<nn::sf::cmif::detail::InRawArgumentInfo<8ul, 8ul, 8l>, nn::sf::cmif::detail::BufferArgumentInfo<0, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<1, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<2, 5, 0ul>, nn::sf::cmif::detail::BufferArgumentInfo<3, 34, 0ul>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 0l>, nn::sf::cmif::detail::BufferArgumentInfo<4, 33, 0ul>, nn::sf::cmif::detail::InRawArgumentInfo<4ul, 4ul, 4l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 8l>, nn::sf::cmif::detail::OutRawArgumentInfo<4ul, 4ul, 12l> > >::Process(nn::sf::hipc::client::Hipc2ClientProxyBaseObject*, nn::sf::cmif::client::InRawClientArgumentType<8ul, 8ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::BufferClientArgumentType, nn::sf::cmif::client::InRawClientArgumentType<4ul, 4ul, void>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, nn::sf::cmif::client::OutRawClientArgumentType<4ul, 4ul>, unsigned int)
   sdk:0x0036823c Sub000000000bef023c
   sdk:0x003671cc Sub000000000beef1cc
   main:0x00039b38 telegraf::internal::Connection::setAddr(String const&, int)
   main:0x000399ec telegraf::internal::Connection::Connection(String const&, int)
   main:0x00039858 _ZN5eastl15allocate_sharedIN8telegraf8internal10ConnectionENS_9allocatorEJR6StringRiEEENS_10shared_ptrIT_EERKT0_DpOT1_
   main:0x00039474 _ZN5eastl11make_sharedIN8telegraf8internal10ConnectionEJR6StringRiEEENS_10shared_ptrIT_EEDpOT0_
   main:0x00037a30 telegraf::internal::ConnectionMgr::create(telegraf::Config&)
   main:0x0003791c telegraf::create(telegraf::Config&, bool)
   main:0x0014937c telegraf::startup(DataBlock const*)
   main:0x0014803c Application::startup()
   main:0x00095c54 DagorWinMain(int, bool)
   main:0x000152a8 nnMain
   sdk:0x00289ddc nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Buffer Information:
	PtrBuff:
	[0] Position: 0x000000000a16b0b0 Size: 0x0000000000000000
	SendBuff:
	Position: 0x0000001012fca180 Size: 0x000000000000001e Flags: 0
	Position: 0x000000000c905a38 Size: 0x0000000000000006 Flags: 0
	Position: 0x000000000a16b0d8 Size: 0x0000000000000400 Flags: 0
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
	ReceiveBuff:
	Position: 0x0000000000000000 Size: 0x0000000000000000 Flags: 0
	RecvListBuff:
	Position: 0x000000000a16b4f8 Size: 0x0000000000001000

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  0C 00 00 00 00 00 00 00   SFCI············
00000010   01 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················
00000020   00 00 00 00 00 00 00 00  00 10 00 00 F8 B4 16 0A   ············ø´··
00000030   00 00 00 10                                        ····            

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
#### Log file :

[BladesofTime.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4604299/BladesofTime.zip)

**Comment by GoffyDude** [comment]
Updated

**Comment by AcK77** [comment]
Needs update

**Comment by EmulationFanatic** [comment]
Updated

**Comment by benderscruffy** [comment]
using 1.1.21
nothing but a black screen
[Ryujinx_1.1.21_2022-02-09_16-58-26.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8031114/Ryujinx_1.1.21_2022-02-09_16-58-26.log)

**Comment by EmulationFanatic** [comment]
Updated
