### ISSUE TITLE
Away: Journey to the Unexpected

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#686]
#### Current on `master` : 1.0.4168

Game loads slowly and then has such a low FPS and graphical corruption/artifacting that it is not playable at this time.

#### Screenshots :

![2020-04-10 19_02_08-Ryujinx 1 0 4168 _ Away_ Journey to the Unexpected _ 01002F1005F3C000](https://user-images.githubusercontent.com/62343878/79031846-2456cf80-7b5f-11ea-83a8-eddb197c6d1d.png)
![2020-04-10 19_03_02-Ryujinx 1 0 4168 _ Away_ Journey to the Unexpected _ 01002F1005F3C000](https://user-images.githubusercontent.com/62343878/79031847-24ef6600-7b5f-11ea-8ac8-0b83b4e93007.png)
![2020-04-10 19_04_48-Ryujinx 1 0 4168 _ Away_ Journey to the Unexpected _ 01002F1005F3C000](https://user-images.githubusercontent.com/62343878/79031850-2751c000-7b5f-11ea-94d1-38dd0bb57172.png)
![2020-04-10 19_08_20-Ryujinx 1 0 4168 _ Away_ Journey to the Unexpected _ 01002F1005F3C000](https://user-images.githubusercontent.com/62343878/79031855-2fa9fb00-7b5f-11ea-9eea-d8b1b2edb81e.png)
![2020-04-10 19_08_43-Ryujinx 1 0 4168 _ Away_ Journey to the Unexpected _ 01002F1005F3C000](https://user-images.githubusercontent.com/62343878/79031856-38023600-7b5f-11ea-918c-bac9be7241ff.png)
![2020-04-10 19_10_11-Ryujinx 1 0 4168 _ Away_ Journey to the Unexpected _ 01002F1005F3C000](https://user-images.githubusercontent.com/62343878/79031861-3d5f8080-7b5f-11ea-9e0b-b9912fe86e56.png)
![2020-04-10 19_10_18-Ryujinx 1 0 4168 _ Away_ Journey to the Unexpected _ 01002F1005F3C000](https://user-images.githubusercontent.com/62343878/79031866-44868e80-7b5f-11ea-9196-e72cd3ff50e0.png)
![2020-04-10 19_11_05-Ryujinx 1 0 4168 _ Away_ Journey to the Unexpected _ 01002F1005F3C000](https://user-images.githubusercontent.com/62343878/79031869-4bad9c80-7b5f-11ea-8eb1-7c54e0be06b6.png)

#### Log file :

[AJttU.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4463841/AJttU.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by F1ReB4LL** [comment]
Works fine under OpenGL, but crashes when leaving the initial location under Vulkan:

```
Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 227
   at Ryujinx.Graphics.Vulkan.TextureView.GetData(Int32 layer, Int32 level) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\TextureView.cs:line 849
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataSliceFromGpu(Span`1 output, Int32 layer, Int32 level, Boolean blacklist, ITexture texture) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 1115
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.FlushTextureDataSliceToGuest(Boolean tracked, Int32 sliceIndex, ITexture texture) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 419
   at Ryujinx.Graphics.Gpu.Image.TextureGroup.<>c__DisplayClass66_0.<FlushAction>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureGroup.cs:line 1409
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_0(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 54
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 130
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 107
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 399
   at System.Threading.Thread.StartCallback()
```

[Ryujinx_1.1.272_2022-09-17_02-17-12.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9590515/Ryujinx_1.1.272_2022-09-17_02-17-12.log)

**Comment by F1ReB4LL** [comment]
I believe it doesn't happen anymore. Retested 1.1.272 - crashes there when in fullscreen at the moment I've described, tested a couple of times on 1.1.327 (the version before a specific ErrorDeviceLost fix) and on 1.1.328 - no crash for me.
