### ISSUE TITLE
Blade Strangers

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#704]
#### Current on `master` : 1.0.4168

Emulation begins with a black screen/choppy audio cutscene (due to nvdec) that crashes as soon as it's over or is skipped.
Note: the below error only showed up in the console; it was not found in the logfile.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.TranslatedFunction.Execute(ARMeilleure.State.ExecutionContext)
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass129_0.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```
#### Log file :

[BladeStrangers.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4466419/BladeStrangers.zip)

**Comment by benderscruffy** [comment]
goes ingame now
lots of broken and inverted graphics

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Less corruption but still upside down in 1.0.6906

**Comment by EmulationFanatic** [comment]
Updated
