### ISSUE TITLE
Sphinx and the Cursed Mummy™

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#710]
#### Current on `master` : 1.0.4189

Crashes on launch with the below error. Note: this error only showed up in the console; it did not appear in the logfile.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(System.Object, ARMeilleure.State.InstUndefinedEventArgs)
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64, Int32)
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64, Int32)
   at ARMeilleure.Translation.TranslatedFunction.Execute(ARMeilleure.State.ExecutionContext)
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass129_0.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

```
#### Log file :

[SatCM.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4466514/SatCM.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Djipi71** [comment]
Test on Rev 1.0.6935

Long time to start the game. Always black screen...

**Comment by Djipi71** [comment]
Test on Build 1.0.7058

Long time to start , we listen music and can press button, we listen it work but there is no graphicals at all , only a black screen.

LOG :
[Ryujinx_1.0.7058_2021-09-29_08-08-00.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/7249312/Ryujinx_1.0.7058_2021-09-29_08-08-00.zip)

**Comment by Djipi71** [comment]
Test on Build 1.1.65

The game now isn't slow , 60FPs but not graphics
![ryujinx_capture_2022-03-12_12-49-23](https://user-images.githubusercontent.com/35375131/158016875-66b97476-dd34-4a17-97b6-e6ce0d3d177b.png)

**Comment by Djipi71** [comment]
Now Test with 1.1.139 Build:

We show graphics but menu's and texts are invisible. Plus i think there is a problem on logo (many a problem of decompression...)
![ryujinx_capture_2022-06-06_09-34-52](https://user-images.githubusercontent.com/35375131/172117482-51353573-2bfa-4a90-8f36-3e04ce93199b.png)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Djipi71** [comment]
Test on 1.1.417
 Same probleme , text are not visible.
Plus i dee that game have wrong dark color and Upscaling not working.
![ryujinx_capture_2022-12-04_11-17-01](https://user-images.githubusercontent.com/35375131/205485335-1a3eb6e8-a694-4956-9d27-fdd4e5541a1a.png)

**Comment by Djipi71** [comment]
Test on 1.1.476

Now there is text on the screen !!! finally!!
BUT now there is explode vertex :(
![ryujinx_capture_2022-12-17_09-15-08](https://user-images.githubusercontent.com/35375131/208232729-00e33f7e-f719-452e-8280-80018ad18ae8.png)

Plus the game have black screen on VULKAN

**Comment by Djipi71** [comment]
Test on 1.1.484 with OPENGL 

Now all is ok. I think the game is too dark but now no glitch.

Vulkan always have black screen and Upscale not working at all.
![ryujinx_capture_2022-12-21_21-04-39](https://user-images.githubusercontent.com/35375131/208993967-a0c7c0d0-c545-4ca6-a558-c9b223a4d91b.png)

![ryujinx_capture_2022-12-21_21-06-42](https://user-images.githubusercontent.com/35375131/208993977-5eeb1331-77ce-442b-9bc4-6f9c187a2e94.png)

**Comment by Djipi71** [comment]
Test on 1.1.1202

Game Work well but really too dark :(
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/35375131/63c3ed8a-923a-4fac-81ad-d871520e0bb2)

**Comment by Djipi71** [comment]
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/35375131/d1d392dd-c1b9-4fb2-a299-979808cc1ed4)
look

**Comment by Djipi71** [comment]
Test on 1.1.1242

Same result , In Vulkan now it work too but really too dark...
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/35375131/e4b556e1-a76a-4d51-ac52-2d484ae1cf69)

**Comment by Djipi71** [comment]
Test on 1.1.1317
In both openGL or Vulkan , the game is too dark.
