### ISSUE TITLE
Baseball Riot

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#712]
#### Current on `master` : 1.0.4189

Crashes while pressing A through splash screens.

```
ServiceLm Log: Guest log:
 Log level: Info
 Line: 0
 Filename: ''
 Function: ''
 Module: ''
 Thread: 'Thread_0x0000000009F5A268'
 Message: 'Corrupt JPEG data: bad Huffman code'

00:01:02.980 | HLE.HostThread.15 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at ARMeilleure.Memory.MemoryManager.ReadUInt64(Int64 position) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 502
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 96
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1142
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 162
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-04-12 09_04_03-Ryujinx 1 0 4189 _ Baseball Riot _ 01004860080A0000](https://user-images.githubusercontent.com/62343878/79072151-bb757180-7c9c-11ea-875c-739bae3d0c91.png)
![2020-04-12 09_04_18-Ryujinx 1 0 4189 _ Baseball Riot _ 01004860080A0000](https://user-images.githubusercontent.com/62343878/79072155-c16b5280-7c9c-11ea-8114-f6d7d257cdd3.png)

#### Log file :

[BaseballRiot.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4466528/BaseballRiot.zip)

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
