### ISSUE TITLE
BINGO for Nintendo Switch

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#732]
#### Current on `master` : 1.0.4193

Played one game flawlessly and then crashed when selecting a second game.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Graphics.Texture.LayoutConverter.ConvertLinearToBlockLinear(Int32 width, Int32 height, Int32 depth, Int32 levels, Int32 layers, Int32 blockWidth, Int32 blockHeight, Int32 bytesPerPixel, Int32 gobBlocksInY, Int32 gobBlocksInZ, Int32 gobBlocksInTileX, SizeInfo sizeInfo, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Graphics.Texture\LayoutConverter.cs:line 215
   at Ryujinx.Graphics.Gpu.Image.Texture.GetTextureDataFromGpu() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 473
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 324
   at Ryujinx.Graphics.Gpu.Image.TextureManager.FindOrCreateTexture(RtDepthStencilState dsState, Size3D size, Int32 samplesInX, Int32 samplesInY) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureManager.cs:line 436
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateRenderTargetState(GpuState state, Boolean useControl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 290
   at Ryujinx.Graphics.Gpu.Engine.Methods.Clear(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodClear.cs:line 17
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 74
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, GpuState shadowState, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 497
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 131
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 98
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 154
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 212
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 187
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 337
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-04-13 07_27_55-Ryujinx 1 0 4193 - BINGO for Nintendo Switch v1 0 0 (010087D008D64000) (64-bit)](https://user-images.githubusercontent.com/62343878/79124363-66e3fc00-7d59-11ea-84cd-cdffc9c530a5.png)
![2020-04-13 07_28_13-Ryujinx 1 0 4193 - BINGO for Nintendo Switch v1 0 0 (010087D008D64000) (64-bit)](https://user-images.githubusercontent.com/62343878/79124365-68152900-7d59-11ea-8704-b7f09d0d0636.png)
![2020-04-13 07_28_28-Ryujinx 1 0 4193 - BINGO for Nintendo Switch v1 0 0 (010087D008D64000) (64-bit)](https://user-images.githubusercontent.com/62343878/79124366-6a778300-7d59-11ea-9cfc-a65194af27df.png)
![2020-04-13 07_28_57-Ryujinx 1 0 4193 - BINGO for Nintendo Switch v1 0 0 (010087D008D64000) (64-bit)](https://user-images.githubusercontent.com/62343878/79124367-6b101980-7d59-11ea-8bde-5b38dc61850d.png)
![2020-04-13 07_29_25-Ryujinx 1 0 4193 - BINGO for Nintendo Switch v1 0 0 (010087D008D64000) (64-bit)](https://user-images.githubusercontent.com/62343878/79124371-6cd9dd00-7d59-11ea-8c1d-71a35f248e1a.png)
![2020-04-13 07_32_39-Ryujinx 1 0 4193 - BINGO for Nintendo Switch v1 0 0 (010087D008D64000) (64-bit)](https://user-images.githubusercontent.com/62343878/79124378-6f3c3700-7d59-11ea-915e-960f8bb2634c.png)
![2020-04-13 07_34_19-Ryujinx 1 0 4193 - BINGO for Nintendo Switch v1 0 0 (010087D008D64000) (64-bit)](https://user-images.githubusercontent.com/62343878/79124383-706d6400-7d59-11ea-9fd6-e64c49af8da8.png)

#### Log file :

[BINGO.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4469692/BINGO.zip)

**Comment by EmulationFanatic** [comment]
Updated
