### ISSUE TITLE
Dead Cell

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#74]
Current on `master`:
`Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.NvGpuEngine2d.WriteRegister(NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine2d.cs:line 139
   at Ryujinx.Graphics.NvGpuEngine2d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine2d.cs:line 58
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 119
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104`

**Comment by AcK77** [comment]
Game need 2D Register `0x1fd4` & `0x1fe0`, I'm not able to find more informations.

**Comment by AcK77** [comment]
Need an update.

**Comment by HorrorTroll** [comment]
Updated!

**Comment by EmulationFanatic** [comment]
## Dead Cells

#### Current on `master` : 1.0.4683

Game now loads and plays smoothly, after some shader stutter.

#### Screenshots :

![2020-06-08 16_56_14-Ryujinx 1 0 4683 - Dead Cells v1 0 0 (0100FC000AEF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84088552-f8fb3000-a9a9-11ea-8571-24a6639ade97.png)
![2020-06-08 16_56_59-Ryujinx 1 0 4683 - Dead Cells v1 0 0 (0100FC000AEF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84088554-f993c680-a9a9-11ea-8d71-2f12dfd08abe.png)
![2020-06-08 16_58_01-Ryujinx 1 0 4683 - Dead Cells v1 0 0 (0100FC000AEF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84088558-fdbfe400-a9a9-11ea-9ce6-aee26ac26457.png)
![2020-06-08 16_58_28-Ryujinx 1 0 4683 - Dead Cells v1 0 0 (0100FC000AEF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84088560-ff89a780-a9a9-11ea-86e4-1c5c68a5db1b.png)
![2020-06-08 16_59_27-Ryujinx 1 0 4683 - Dead Cells v1 0 0 (0100FC000AEF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84088562-00bad480-a9aa-11ea-89ac-94b422b1575d.png)
![2020-06-08 17_00_04-Ryujinx 1 0 4683 - Dead Cells v1 0 0 (0100FC000AEF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84088565-031d2e80-a9aa-11ea-8083-4e69c00ff2d0.png)
![2020-06-08 17_00_35-Ryujinx 1 0 4683 - Dead Cells v1 0 0 (0100FC000AEF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84088566-04e6f200-a9aa-11ea-8665-11def90d7028.png)
![2020-06-08 17_01_40-Ryujinx 1 0 4683 - Dead Cells v1 0 0 (0100FC000AEF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84088567-06181f00-a9aa-11ea-9faa-985d55a9e084.png)
![2020-06-08 17_01_44-Ryujinx 1 0 4683 - Dead Cells v1 0 0 (0100FC000AEF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84088569-07e1e280-a9aa-11ea-9690-5ca05fbcfef1.png)
![2020-06-08 17_02_02-Ryujinx 1 0 4683 - Dead Cells v1 0 0 (0100FC000AEF0000) (64-bit)](https://user-images.githubusercontent.com/62343878/84088572-09aba600-a9aa-11ea-8af0-cf8e8766c180.png)


#### Log file :

[DC.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4749016/DC.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by r3ntonboy** [comment]
Current on master : 1.0.7047

I recorded a small video to show the problem

https://youtu.be/Z-8p4P4ggeA
