### ISSUE TITLE
Hyper Light Drifter - Special Edition

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#749]
#### Current on `master` : 1.0.4193

After 10 minutes of steady console output, the game never displays or shows signs of life.

#### Log file :

[HLDSE.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4475474/HLDSE.zip)

**Comment by HorrorTroll** [comment]
This game it need around 20 or 30 minutes to load, and then crash for missing service:

`nvdrv INvDrvServices: 6 (GetStatus)`

It use same engine to Undertale, Deltarune

**Comment by B3astTech** [comment]
Updated

**Comment by AcK77** [comment]
Needs update

**Comment by EmulationFanatic** [comment]
Updated

**Comment by JWayn596** [comment]
Version 1.0.7106
Still Black screen, no boot

**Comment by Keiichibaka** [comment]
Version 1.0.7151
Hyper Light Drifter special edition v1.3.1
Switch firmware Version 13.1.0

Game is loading. I am able to create a new game and it successfully ran through the opening cinematic to the starting bonfire. The game appears to be running normally, more testing needed.

**Comment by Keiichibaka** [comment]
I have played through the entirety of the game and it is perfectly playable. 
The only issue I ran into was after hitting switches to make platforms appear, they would intermittently take on the shading of the background making them trickier to see.

**Comment by MutantAura** [comment]
I'll update the status but some screenshots would be helpful for others to test against.

**Comment by Keiichibaka** [comment]
Here are some in game screenshots:
![ryujinx_capture_2022-01-23_17-22-50.png](https://user-images.githubusercontent.com/66572683/150700995-55982066-9184-4523-84b9-24972981e197.png)
![ryujinx_capture_2022-01-23_17-30-37.png](https://user-images.githubusercontent.com/66572683/150701010-444859c4-e57d-49a2-9cd2-e6c5bce89f8d.png)
![ryujinx_capture_2022-01-23_17-30-34.png](https://user-images.githubusercontent.com/66572683/150701023-fcfbd43f-2e47-49f6-869c-54cec9564796.png)
![Window.png](https://user-images.githubusercontent.com/66572683/150701032-8d38038f-8c31-43bc-a2f3-8bd048ae7189.png)
![ryujinx_capture_2022-01-23_17-32-45.png](https://user-images.githubusercontent.com/66572683/150701038-fb5a7624-91d1-4401-a4c7-6b9f97c471c7.png)
![ryujinx_capture_2022-01-23_17-30-07.png](https://user-images.githubusercontent.com/66572683/150701046-8d22ef95-545b-4ffb-85d8-2b7ad4d7728c.png)
![ryujinx_capture_2022-01-23_17-30-13.png](https://user-images.githubusercontent.com/66572683/150701053-ce9e8ff3-c52a-48bb-9b4f-7d1268d644d6.png)
![ryujinx_capture_2022-01-23_17-37-37.png](https://user-images.githubusercontent.com/66572683/150701062-e22fc4b5-15ee-48af-8a4d-dd090a6f9f5c.png)
![System.png](https://user-images.githubusercontent.com/66572683/150701067-d8f737e7-daac-4af1-a256-2e9ffd4cfa5d.png)
![Graphics.png](https://user-images.githubusercontent.com/66572683/150701071-21e448b6-15f8-4eaa-8b4a-8ad182073fc9.png)

**Comment by EmulationFanatic** [comment]
@Keiichibaka can you re-test on the latest build to see if the switches are properly rendered now? With OpenGL as the GPU backend, please (since Vulkan has some flashing boxes on this game).

**Comment by EmulationFanatic** [comment]
Updated, pending confirmation about the switches' rendering.

**Comment by Oshir1** [comment]
Game was working fine. But after updating Ryujinx there seems to be a problem. 

After using a previous save the game restarts as normal but Ryujinx will crash immediately after dying in game (where the game tries to restart a save).

This is the last error from the log file:

00:07:29.950 |E| HLE.GuestThread.19 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000c30ed14 (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(IExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1106
   at Ryujinx.Cpu.Jit.JitExecutionContext.UndefinedHandler(ExecutionContext context, UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitExecutionContext.cs:line 104
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\State\ExecutionContext.cs:line 150
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 59
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 150
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1270
   at System.Threading.Thread.StartCallback()

I'm using the following:
Ryujinx v1.1.552
Hyper Light Drifter special edition v1.3.1
