### ISSUE TITLE
Horizon Chase Turbo

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#754]
#### Current on `master` : 1.0.4193

Crashes in early menus.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2
```

#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/629

#### Screenshots :

![2020-04-14 08_13_44-Ryujinx 1 0 4193 - Horizon Chase Turbo v1 0 0 (01009EA00B714000) (64-bit)](https://user-images.githubusercontent.com/62343878/79234944-3919b880-7e28-11ea-96cd-580132a2118c.png)
![2020-04-14 08_14_44-Ryujinx 1 0 4193 - Horizon Chase Turbo v1 0 0 (01009EA00B714000) (64-bit)](https://user-images.githubusercontent.com/62343878/79234956-3cad3f80-7e28-11ea-9fb0-f5c1c2dc202e.png)
![2020-04-14 08_14_58-Ryujinx 1 0 4193 - Horizon Chase Turbo v1 0 0 (01009EA00B714000) (64-bit)](https://user-images.githubusercontent.com/62343878/79234989-45057a80-7e28-11ea-8fcb-6ba272056f9c.png)

#### Log file :

[HorizonChaseTurbo.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4475794/HorizonChaseTurbo.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by tonyunreal** [comment]
## Horizon Chase Turbo (01009EA00B714000)

#### Game Update Version : 1.9.6 and 1.0.0

#### Current on `master` : 1.0.6604

The game always crashes upon loading any level.

```
00:02:13.096 |E| HLE.OsThread.5 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Ryujinx.HLE.HOS.Services.Nifm.StaticService.IGeneralService.IsAnyInternetRequestAccepted(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nifm\StaticService\IGeneralService.cs:line 115
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 114
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 208
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 132
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1031
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Hardware Specs : 

##### CPU: i7-8700B
##### GPU: AMD Radeon RX Vega 64
##### RAM: 32GB

#### Log file :

[horizon_chase_turbo_crash.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/6010650/horizon_chase_turbo_crash.txt)

**Comment by EmulationFanatic** [comment]
@tonyunreal the issue has been fixed on the latest master build. Thanks for the heads up!
