### ISSUE TITLE
Penny-Punching Princess

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#78]
Current on `master`:

```
00:00:09.398 | 0008 Cpu PrintStackTrace: Guest stack trace:
 main:0x0016a204 Sub0000000008170204
 main:0x001692ec Sub000000000816f2ec
 main:0x0019668c Sub000000000819c68c
 main:0x00029050 Sub000000000802f050
 main:0x0003b51c main
 main:0x001a58c8 nnMain
 sdk:0x000686b4 nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
 rtld:0x000000ac Sub00000000080000ac

Unhandled Exception: ChocolArm64.Exceptions.VmmPageFaultException: Tried to access unmapped address 0x00000000000000c8!
   at ChocolArm64.Memory.AMemory.HandleNullPte(Int64 Position) in C:\projects\ryujinx\ChocolArm64\Memory\AMemory.cs:line 520
   at Sub000000000950ca1c(AThreadState , AMemory , UInt64 , UInt64 )
   at ChocolArm64.ATranslator.ExecuteSubroutineA64(AThreadState State, AMemory M
emory, Int64 Position) in C:\projects\ryujinx\ChocolArm64\ATranslator.cs:line 69

   at ChocolArm64.AThread.<>c__DisplayClass14_0.<.ctor>b__0() in C:\projects\ryujinx\ChocolArm64\AThread.cs:line 36
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()```

**Comment by HorrorTroll** [comment]
Updated

**Comment by GoffyDude** [comment]
## Penny-Punching Princess

#### Current on `master` : 1.0.3975

Pops and clicks in the audio during intro cutscenes. Otherwise fully playable.

#### Screenshots :

![2020-03-24 05_52_25-Ryujinx 1 0 3975 _ Penny-Punching Princess _ 0100C510049E0000](https://user-images.githubusercontent.com/62343878/77423114-477a3480-6d94-11ea-82ec-424e92563a13.png)
![2020-03-24 05_52_29-Ryujinx 1 0 3975 _ Penny-Punching Princess _ 0100C510049E0000](https://user-images.githubusercontent.com/62343878/77423116-4812cb00-6d94-11ea-95dd-5ff0307a639c.png)
![2020-03-24 05_52_48-Ryujinx 1 0 3975 _ Penny-Punching Princess _ 0100C510049E0000](https://user-images.githubusercontent.com/62343878/77423121-48ab6180-6d94-11ea-9f4f-b151384919d9.png)
![2020-03-24 05_53_05-Ryujinx 1 0 3975 _ Penny-Punching Princess _ 0100C510049E0000](https://user-images.githubusercontent.com/62343878/77423138-4e08ac00-6d94-11ea-8447-ea469548a9e6.png)
![2020-03-24 05_53_10-Ryujinx 1 0 3975 _ Penny-Punching Princess _ 0100C510049E0000](https://user-images.githubusercontent.com/62343878/77423156-53fe8d00-6d94-11ea-9df1-3e5c0fdde37a.png)
![2020-03-24 05_53_25-Ryujinx 1 0 3975 _ Penny-Punching Princess _ 0100C510049E0000](https://user-images.githubusercontent.com/62343878/77423172-58c34100-6d94-11ea-86a8-76660f5927af.png)
![2020-03-24 05_53_35-Ryujinx 1 0 3975 _ Penny-Punching Princess _ 0100C510049E0000](https://user-images.githubusercontent.com/62343878/77423173-59f46e00-6d94-11ea-88c4-29390ee3411e.png)
![2020-03-24 05_55_20-Ryujinx 1 0 3975 _ Penny-Punching Princess _ 0100C510049E0000](https://user-images.githubusercontent.com/62343878/77423196-6082e580-6d94-11ea-9f68-c280731e1aa5.png)
![2020-03-24 05_55_52-Ryujinx 1 0 3975 _ Penny-Punching Princess _ 0100C510049E0000](https://user-images.githubusercontent.com/62343878/77423208-65e03000-6d94-11ea-99dc-8c69d3285433.png)


#### Log file :

[Penny-PunchingPrincess.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4375071/Penny-PunchingPrincess.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
