### ISSUE TITLE
Mushroom Quest

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#789]
#### Current on `master` : 1.0.4206

Crashes on launch.
```
Last error returned.
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.HLE.Exceptions.ServiceNotImplementedException: The service call is not implemented.

Service Command: Ryujinx.HLE.HOS.Services.Nv.INvDrvServices: 6 (GetStatus)

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x003d3210 Sub000000000b2ee210
   sdk:0x003d15c4 Sub000000000b2ec5c4
   sdk:0x003d4c78 Sub000000000b2efc78
   sdk:0x003d0e24 nv::GetGraphicsMemoryInfo(nv::MemoryInfo*)
   main:0x0006c50c Sub000000000807050c
   main:0x000ac60c Sub00000000080b060c
   main:0x000a0e50 Sub00000000080a4e50
   main:0x000a135c Sub00000000080a535c
   main:0x00000ac4 Sub0000000008004ac4
   main:0x00001034 nnMain
   sdk:0x0029da2c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  06 00 00 00 00 00 00 00   SFCI············
00000010   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.Nv.INvDrvServices.GetStatus(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nv\INvDrvServices.cs:line 386
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```
#### Log file :
[mushroom-quest.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4482668/mushroom-quest.log)

**Comment by GoffyDude** [comment]
Needs update

**Comment by SeraUX** [comment]
## Mushroom Quest

#### Current on `master` : 1.0.4573

Game runs fine without any problems

#### Screenshots :
![2020-05-17-103359_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82139758-81af0200-982a-11ea-8662-11deb588672d.png)
![2020-05-17-103430_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82139761-84a9f280-982a-11ea-8f49-a9b36b20f81c.png)
![2020-05-17-103427_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82139763-8673b600-982a-11ea-96fd-06badd946272.png)

#### Log file :
[mushroom-quest.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4639918/mushroom-quest.log)

**Comment by GoffyDude** [comment]
Updated
