### ISSUE TITLE
Infernium

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#790]
#### Current on `master` : 1.0.4206

Tried a couple times to launch.
1st try made it to the menu but then crashed as button inputs were being made. 
2nd try crashed on its own.

1st launch:
```
UI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Runtime.InteropServices.Marshal.CopyToManaged[T](IntPtr source, T[] destination, Int32 startIndex, Int32 length)
   at ARMeilleure.Memory.MemoryManager.ReadBytes(Int64 position, Int64 size) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 549
   at ARMeilleure.Memory.MemoryManager.GetSpan(UInt64 address, UInt64 size) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 558
   at Ryujinx.Graphics.Gpu.Image.Texture.SynchronizeMemory() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\Texture.cs:line 320
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 37
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 219
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 158
   at Ryujinx.Graphics.Gpu.Engine.Methods.CommitBindings() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 235
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 96
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 74
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, GpuState shadowState, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 497
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 131
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 103
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 154
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 212
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 187
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 337
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

2nd launch:
```
HLE.HostThread.2 Cpu PrintGuestStackTrace: Guest stack trace:
Process: InferniumSw, PID: 81
   sdk:0x0004305c nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   sdk:0x00043114 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, char const*, ...)
   sdk:0x0008f7fc nn::os::detail::InternalConditionVariableImplByHorizon::TimedWait(nn::os::detail::InternalCriticalSection*, nn::os::detail::TimeoutHelper const&)
   sdk:0x00086824 nn::os::WaitEvent(nn::os::EventType*)
   main:0x0001cc38 Sub0000000008020c38
   main:0x000293fc Sub000000000802d3fc
   main:0x0002904c Sub000000000802d04c
   main:0x00028620 Sub000000000802c620
   main:0x019fa914 Sub00000000099fe914
   main:0x019f882c Sub00000000099fc82c
   main:0x01600f48 Sub0000000009604f48
   main:0x014f3cd8 Sub00000000094f7cd8
   main:0x0000e570 Sub0000000008012570
   main:0x00001780 Sub0000000008005780
   sdk:0x0008a8a8 Sub000000000dba38a8
   sdk:0x0008e958 Sub000000000dba7958
   ??? Sub0000000000000000
```

#### Screenshots :
![2020-04-15 11_32_15-Ryujinx 1 0 4206 - Infernium v1 4 (0100D4300A4CA000) (64-bit)](https://user-images.githubusercontent.com/62343878/79369768-b91a4e00-7f0e-11ea-8824-08e5b2156157.png)

#### Log file :

[Infernium.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4482828/Infernium.zip)

**Comment by EmulationFanatic** [comment]
Updated
