### ISSUE TITLE
Minecraft - Nintendo Switch Edition

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#80]
Current on `master`:
```
00:01:31.483 | 0010 Cpu PrintStackTrace: Guest stack trace:
 sdk:0x00040b38 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
 sdk:0x00040bf0 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, char const*, ...)
 sdk:0x00040c80 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
 sdk:0x00161b74 nn::audio::SetAudioRendererRenderingTimeLimit(nn::audio::AudioRendererHandle, int)
 main:0x00931c3c Sub0000000008939c3c
 main:0x009304e0 Sub00000000089384e0
 main:0x00931008 Sub0000000008939008
 main:0x00941184 Sub0000000008949184
 sdk:0x00082eb0 Sub000000000a160eb0
 sdk:0x00085c38 Sub000000000a163c38```

**Comment by HorrorTroll** [comment]
Updated

**Comment by AcK77** [comment]
Need an update.

**Comment by HorrorTroll** [comment]
Updated again

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## Minecraft: Nintendo Switch Edition

#### Current on `master` : 1.0.3937

Crashes on launch. Including debug log here.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000008937cdc (opcode 0xe7ffdefe) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1132
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 127
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 70
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 96
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1144
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 162
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```



#### Log file :

[Minecraft_debug.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4365214/Minecraft_debug.zip)

**Comment by Spillebulle** [comment]
Just launched minecraft on version 1.0.4593 and it works perfectly, between 40-50 fps on 50% utilization on a i7-6700 and 10% on a gtx 1080. No bugs or glitches encountered

**Comment by GoffyDude** [comment]
> Just launched minecraft on version 1.0.4593 and it works perfectly, between 40-50 fps on 50% utilization on a i7-6700 and 10% on a gtx 1080. No bugs or glitches encountered

You must have ignore missing services enabled. The game still crashes on launch with a missing service error on default settings.

**Comment by Spillebulle** [comment]
> > Just launched minecraft on version 1.0.4593 and it works perfectly, between 40-50 fps on 50% utilization on a i7-6700 and 10% on a gtx 1080. No bugs or glitches encountered
> 
> You must have ignore missing services enabled. The game still crashes on launch with a missing service error on default settings.

I have not changed any settings. Just set up the correct folder for my games library and launched the game

**Comment by GoffyDude** [comment]
Can you upload your log file? Neither the eshop nor retail version of the game is booting.

**Comment by B3astTech** [comment]
I don't really see any evidence supporting, "it boots" if you would upload a log and a screenshot it would be appreciated other than it goes ingame

**Comment by Spillebulle** [comment]
Here is everything, just let me know if you need more proof
![2020-05-22 07_03_47-Ryujinx 


1 0 4593 - Minecraft v1 2 12 0 (0100D71004694000) (64-bit)](https://user-images.githubusercontent.com/46653946/82633266-f69f8480-9bfa-11ea-9165-c2c28d46897f.png)
![2020-05-22 07_06_26-Ryujinx 1 0 4593 - Minecraft v1 2 12 0 (0100D71004694000) (64-bit)](https://user-images.githubusercontent.com/46653946/82633279-ff905600-9bfa-11ea-9bff-3990bfcc1d41.png)
![2020-05-22 07_06_49-Ryujinx 1 0 4593 - Minecraft v1 2 12 0 (0100D71004694000) (64-bit)](https://user-images.githubusercontent.com/46653946/82633288-07e89100-9bfb-11ea-8899-117d578e1807.png)
[Ryujinx_2020-05-22_06-58-36.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4666176/Ryujinx_2020-05-22_06-58-36.log)

**Comment by GoffyDude** [comment]
From your log:
```
00:00:26.891 | KernelIpc CallMethod: Missing service Ryujinx.HLE.HOS.Services.Nifm.StaticService.IGeneralService: 5 ignored
```
1. This means you have ignore missing services enabled, as I stated earlier.

2. Your log shows you are using the retail version of the game whereas this page/gamedb entry is for the eshop version. They are in fact quite different. You can tell by the title "Minecraft: Nintendo Switch Edition" in the title of this page where yours is simply "Minecraft".

**Comment by EmulationFanatic** [comment]
Updated

**Comment by NIKstudios** [comment]
Download Game folder?

**Comment by GiltFountain790** [comment]
how to install it?

**Comment by TGNick** [comment]
w
