### ISSUE TITLE
Hungry Shark World

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#804]
#### Current on `master` : 1.0.4215

Crashes on launch. Error below shows up in console but not in logfile.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.TranslatedFunction.Execute(ARMeilleure.State.ExecutionContext)
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass129_0.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[HungrySharkWorld.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4487951/HungrySharkWorld.zip)

**Comment by EmulationFanatic** [comment]
Updated
