### ISSUE TITLE
FINAL FANTASY IX

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#811]
#### Current on `master` : 1.0.4215

Game loads initially with black screen/distorted audio but is able to be skipped a game started.
Once you get to the in-game intro fight scene the game crashes with the error below.

```
CPU.BackgroundTranslatorThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentException: Failed to encode constant 0x0.
   at ARMeilleure.CodeGen.X86.Assembler.WriteInstruction(Operand dest, Operand source, OperandType type, X86Instruction inst) in C:\projects\ryujinx\ARMeilleure\CodeGen\X86\Assembler.cs:line 876
   at ARMeilleure.CodeGen.X86.Assembler.Cmpxchg(MemoryOperand memOp, Operand src) in C:\projects\ryujinx\ARMeilleure\CodeGen\X86\Assembler.cs:line 343
   at ARMeilleure.CodeGen.X86.CodeGenerator.GenerateOperation(CodeGenContext context, Operation operation) in C:\projects\ryujinx\ARMeilleure\CodeGen\X86\CodeGenerator.cs:line 187
   at ARMeilleure.CodeGen.X86.CodeGenerator.Generate(CompilerContext cctx) in C:\projects\ryujinx\ARMeilleure\CodeGen\X86\CodeGenerator.cs:line 174
   at ARMeilleure.Translation.Compiler.CompileAndGetCf(ControlFlowGraph cfg, OperandType[] argTypes, OperandType retType, CompilerOptions options) in C:\projects\ryujinx\ARMeilleure\Translation\Compiler.cs:line 43
   at ARMeilleure.Translation.Translator.Translate(UInt64 address, ExecutionMode mode, Boolean highCq) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 147
   at ARMeilleure.Translation.Translator.TranslateQueuedSubs() in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 54
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```
#### Screenshots :

![2020-04-16 13_11_17-Ryujinx 1 0 4215 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/79497255-978b9600-7fe4-11ea-9d83-b6d3b60fc06a.png)
![2020-04-16 13_11_27-Ryujinx 1 0 4215 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/79497260-98bcc300-7fe4-11ea-8862-8fd2aea8d42e.png)
![2020-04-16 13_13_35-Ryujinx 1 0 4215 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/79497266-9d817700-7fe4-11ea-8917-644b8e2b598c.png)
![2020-04-16 13_13_57-Ryujinx 1 0 4215 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/79497280-a1ad9480-7fe4-11ea-846b-50aa8597c462.png)
![2020-04-16 13_14_13-Ryujinx 1 0 4215 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/79497283-a2dec180-7fe4-11ea-8e23-ed11b103841f.png)
![2020-04-16 13_14_38-Ryujinx 1 0 4215 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/79497287-a5411b80-7fe4-11ea-9c55-5ce5055c476b.png)
![2020-04-16 13_15_21-Ryujinx 1 0 4215 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/79497300-ab36fc80-7fe4-11ea-8fa9-35eda03c8c88.png)

#### Log file :

[FFIX.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4489325/FFIX.zip)

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## FINAL FANTASY IX

#### Current on `master` : 1.0.4345

Game is now playable in-game including battles, though there remains occasional missing graphics/upside down graphics/graphical corruption as battles begin and some battles themselves are black screen.
Cutscenes are still black screen (nvdec).
Saving the game is confirmed working.
FPS stayed steady at 30 for nearly all situations.

#### Screenshots :

![2020-04-25 14_25_07-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293082-88f65a80-8719-11ea-9b1f-36532f0276aa.png)
![2020-04-25 14_25_23-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293083-8ac01e00-8719-11ea-8b58-63da6acbf443.png)
![2020-04-25 14_25_27-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293085-8bf14b00-8719-11ea-9c94-6ea75c3c7aa3.png)
![2020-04-25 14_25_31-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293086-8d227800-8719-11ea-96c0-284297bfe013.png)
![2020-04-25 14_26_44-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293088-8dbb0e80-8719-11ea-8d5c-84116bf82bc7.png)
![2020-04-25 14_27_08-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293092-93185900-8719-11ea-82a1-49ac7f282df3.png)
![2020-04-25 14_27_19-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293095-957ab300-8719-11ea-8ce1-a693dd15b272.png)
![2020-04-25 14_27_39-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293102-9a3f6700-8719-11ea-9a2d-4f3bbee7a8c4.png)
![2020-04-25 14_28_23-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293103-a62b2900-8719-11ea-85e0-0a6356d27ef9.png)
![2020-04-25 14_28_59-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293107-b5aa7200-8719-11ea-8b9e-ec68ceb88cc9.png)
![2020-04-25 14_29_07-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293115-bd6a1680-8719-11ea-99a2-b0d74b9728a0.png)
![2020-04-25 14_29_28-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293122-c955d880-8719-11ea-882d-cde6033593f1.png)
![2020-04-25 14_29_39-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293127-d246aa00-8719-11ea-8987-e24d24d78a16.png)
![2020-04-25 14_30_58-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293131-d70b5e00-8719-11ea-87eb-2b11eb29c89f.png)
![2020-04-25 14_31_57-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293137-e4284d00-8719-11ea-870a-d9ebb8a2724c.png)
![2020-04-25 14_32_18-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293138-e5597a00-8719-11ea-8950-bc5ec51ad4de.png)
![2020-04-25 14_32_47-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293142-f0140f00-8719-11ea-91c1-fe1854c9cc7b.png)
![2020-04-25 14_35_34-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293144-f609f000-8719-11ea-9d38-1783ba3e0ab8.png)
![2020-04-25 15_03_39-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293146-fdc99480-8719-11ea-8ad7-bf61d440ec5e.png)
![2020-04-25 15_03_49-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293148-00c48500-871a-11ea-898f-0ab5cdc9cb08.png)
![2020-04-25 15_04_17-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293149-0621cf80-871a-11ea-98e9-8bfa20d8d0ed.png)
![2020-04-25 15_06_19-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293153-0de17400-871a-11ea-8979-079af6632b46.png)
![2020-04-25 15_06_27-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293155-0f12a100-871a-11ea-9f79-fe2846a63932.png)
![2020-04-25 15_07_55-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293159-15a11880-871a-11ea-8cb7-e1da8de514c1.png)
![2020-04-25 15_12_32-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293161-1cc82680-871a-11ea-9cfa-e66b4911065c.png)
![2020-04-25 15_12_49-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293165-23569e00-871a-11ea-899a-55225197c7d2.png)
![2020-04-25 16_58_06-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293166-2a7dac00-871a-11ea-8cf5-cfeff32fd1e1.png)
![2020-04-25 17_15_29-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293175-3bc6b880-871a-11ea-9534-d15c676bcaeb.png)
![2020-04-25 17_16_10-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293177-42edc680-871a-11ea-9c6e-7b8fc3c8a8e6.png)
![2020-04-25 17_16_13-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293178-441ef380-871a-11ea-8ec1-ca396b2a9fbc.png)
![2020-04-25 17_16_20-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293181-45e8b700-871a-11ea-9eab-f1b492f603cb.png)
![2020-04-25 17_16_51-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293182-4719e400-871a-11ea-9a6a-1a47bd62d6b4.png)
![2020-04-25 17_22_07-Ryujinx 1 0 4345 - FINAL FANTASY IX v1 0 0 (01007EF00B094000) (64-bit)](https://user-images.githubusercontent.com/62343878/80293183-484b1100-871a-11ea-8ef9-c088b183b16f.png)


#### Log file :

[FFIX.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4534363/FFIX.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
