### ISSUE TITLE
[010078D000F88000] Dragon Ball Xenoverse 2

### ISSUE THREAD

**Issue by jduncanator** [Ryujinx/Ryujinx-Games-List#82]
Out of the box, the game requests a region change using an applet. Applets are not yet supported so the game (eventually) crashes.

By changing the system language to Japanese ([SystemStateMgr.cs:55](https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.HLE/HOS/SystemState/SystemStateMgr.cs#L55)), you can bypass the request and region change screen.

Crashes with an unsupported texture exception.

```
Unhandled Exception: System.NotImplementedException: Per component types are not implemented!
   at Ryujinx.Graphics.Texture.ImageUtils.ConvertTexture(GalTextureFormat Format, GalTextureType RType, GalTextureType GType, GalTextureType BType, GalTextureType AType, Boolean ConvSrgb) in Ryujinx.Graphics\Texture\ImageUtils.cs:line 154
   at Ryujinx.Graphics.Texture.TextureFactory.GetImageFormat(Int32[] Tic) in Ryujinx.Graphics\Texture\TextureFactory.cs:line 98
   at Ryujinx.Graphics.Texture.TextureFactory.MakeTexture(NvGpuVmm Vmm, Int64 TicPosition) in Ryujinx.Graphics\Texture\TextureFactory.cs:line 15
   at Ryujinx.Graphics.NvGpuEngine3d.UploadTexture(NvGpuVmm Vmm, Int32 TexIndex, Int32 TextureHandle) in Ryujinx.Graphics\NvGpuEngine3d.cs:line 533
   at Ryujinx.Graphics.NvGpuEngine3d.UploadTextures(NvGpuVmm Vmm, GalPipelineState State, Int64[] Keys) in Ryujinx.Graphics\NvGpuEngine3d.cs:line 506
   at Ryujinx.Graphics.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in Ryujinx.Graphics\NvGpuEngine3d.cs:line 118
   at Ryujinx.Graphics.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in Ryujinx.Graphics\NvGpuEngine3d.cs:line 79
   at Ryujinx.Graphics.MacroInterpreter.Send(NvGpuVmm Vmm, Int32 Value) in Ryujinx.Graphics\MacroInterpreter.cs:line 415
   at Ryujinx.Graphics.MacroInterpreter.Step(NvGpuVmm Vmm, Int32[] Mme) in Ryujinx.Graphics\MacroInterpreter.cs:line 192
   at Ryujinx.Graphics.MacroInterpreter.Execute(NvGpuVmm Vmm, Int32[] Mme, Int32 Position, Int32 Param) in Ryujinx.Graphics\MacroInterpreter.cs:line 87
   at Ryujinx.Graphics.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in Ryujinx.Graphics\NvGpuFifo.cs:line 188
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in Ryujinx.Graphics\NvGpuFifo.cs:line 120
   at Ryujinx.Graphics.NvGpuFifo.Step() in Ryujinx.Graphics\NvGpuFifo.cs:line 104
```

**Comment by AcK77** [comment]
Need an update.

**Comment by jduncanator** [comment]
AFAIK, the status regarding applet support hasn't changed? Happy to test again, but doubt much will have changed!

**Comment by AcK77** [comment]
`the game requests a region change using an applet.` there is no applet to change the region...

See https://switchbrew.org/wiki/Applet_Manager_services#AppletId

**Comment by jduncanator** [comment]
Updated.

**Comment by GoffyDude** [comment]
Needs update.

**Comment by EmulationFanatic** [comment]
## Dragon Ball Xenoverse 2

#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*

Has nvdec cutscene issue after intro splash screens/autosave indicator. This can be skipped.
Game crashes after skipping the cutscene.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Ryujinx.Memory.MemoryBlock.ThrowArgumentOutOfRange() in C:\projects\ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 274
   at Ryujinx.Cpu.MemoryManager.GetPhysicalAddressInternal(UInt64 va) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 423
   at Ryujinx.Cpu.MemoryManager.Write(UInt64 va, ReadOnlySpan`1 data) in C:\projects\ryujinx\Ryujinx.Cpu\MemoryManager.cs:line 143
   at Ryujinx.Graphics.Gpu.Memory.MemoryAccessor.Write(UInt64 gpuVa, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryAccessor.cs:line 107
   at Ryujinx.Graphics.Gpu.Engine.Methods.UniformBufferUpdate(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodUniformBufferUpdate.cs:line 14
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Screenshots :

![2020-06-03 21_49_20-Ryujinx 1 0 4675 - DRAGON BALL XENOVERSE 2 FOR NINTENDO SWITCH v1 07 00 (010078D](https://user-images.githubusercontent.com/62343878/83713055-5ecf6c80-a5e4-11ea-9f65-1cca8be21d01.png)
![2020-06-03 21_49_26-Ryujinx 1 0 4675 - DRAGON BALL XENOVERSE 2 FOR NINTENDO SWITCH v1 07 00 (010078D](https://user-images.githubusercontent.com/62343878/83713056-60009980-a5e4-11ea-82be-180b952719ba.png)
![2020-06-03 21_49_30-Ryujinx 1 0 4675 - DRAGON BALL XENOVERSE 2 FOR NINTENDO SWITCH v1 07 00 (010078D](https://user-images.githubusercontent.com/62343878/83713058-60993000-a5e4-11ea-9d7c-553c7178225b.png)
![2020-06-03 21_49_57-Ryujinx 1 0 4675 - DRAGON BALL XENOVERSE 2 FOR NINTENDO SWITCH v1 07 00 (010078D](https://user-images.githubusercontent.com/62343878/83713060-61ca5d00-a5e4-11ea-95b9-0e0752fa0c6e.png)


#### Log file :

[DBX2.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4727409/DBX2.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6895

**Comment by alejoelconejo737** [comment]
h

**Comment by wickedr0se** [comment]
#### Game Update Version : *(e.g. 1.0.0 or 1.1.3)*
#### Current on `master` : 6a1a035

#### Screenshots :
![Screenshot_212](https://user-images.githubusercontent.com/32614215/165949906-ed38f4f3-b2c0-4414-bb5a-7a0f66861378.png)
![Screenshot_211](https://user-images.githubusercontent.com/32614215/165949916-7fd68b1c-657b-4304-be90-23c022c47585.png)

I think it's playable but I didn't test any further due to weird text

[Ryujinx_1.0.0-dirty_2022-04-29_19-54-30.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/8590980/Ryujinx_1.0.0-dirty_2022-04-29_19-54-30.log)

**Comment by EmulationFanatic** [comment]
Updated
