### ISSUE TITLE
Nights of Azure 2: Bride of the New Moon

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#84]
```
00:02:04.177 | 0008 Cpu PrintStackTrace: Guest stack trace:
 main:0x00adde58 Azure::Layout::detail::System::~System()
 main:0x007a3460 Lily::NXSaveLoad::detail::Actor::Initialize()
 main:0x007a2cec Lily::NXSaveLoad::detail::Actor::onEnter()
 main:0x00a74254 Azure::Engine::Actor::Enter()
 main:0x00a74268 Azure::Engine::Actor::Enter()
 main:0x003e1c44 GameFramework::onInitialize()
 main:0x00a80dc4 Azure::Framework::Impl::onInitialize()
 main:0x00a80880 Azure::Framework::Impl::Loop()
 main:0x003e3d30 nnMain
 rtld:0x000000dc Sub00000000080000dc


Unhandled Exception: ChocolArm64.Exceptions.VmmPageFaultException: Tried to access unmapped address 0x0000000000000018!
   at ChocolArm64.Memory.AMemory.HandleNullPte(Int64 Position) in C:\projects\ryujinx\ChocolArm64\Memory\AMemory.cs:line 520
   at Sub0000000008ae6ba0(AThreadState , AMemory , UInt64 )
   at ChocolArm64.ATranslator.ExecuteSubroutineA64(AThreadState State, AMemory Memory, Int64 Position) in C:\projects\ryujinx\ChocolArm64\ATranslator.cs:line 69

   at ChocolArm64.AThread.<>c__DisplayClass14_0.<.ctor>b__0() in C:\projects\ryujinx\ChocolArm64\AThread.cs:line 36
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by HorrorTroll** [comment]
Updated

**Comment by HorrorTroll** [comment]
Updated!

**Comment by GoffyDude** [comment]
## Nights of Azure 2: Bride of the New Moon

#### Current on `master` : 1.0.4536

Has nvdec cutscene issue. Seemed to have higher FPS than previous tests, but then crashed almost immediately when going through the tutorial.

```
00:05:05.646 | GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.OverflowException: Array dimensions exceeded supported range.
   at Ryujinx.Graphics.Gpu.Memory.Buffer..ctor(GpuContext context, UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\Buffer.cs:line 43
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CreateBufferAligned(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 362
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.TranslateAndCreateBuffer(UInt64 gpuVa, UInt64 size) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 278
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.SetVertexBuffer(Int32 index, UInt64 gpuVa, UInt64 size, Int32 stride, Int32 divisor) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 116
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateVertexBufferState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 663
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 123
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 118
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth, ShadowRamControl shadowCtrl) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 78
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 498
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 129
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 97
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 183
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GlRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 326
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-05-11 07_13_10-Ryujinx 1 0 4536 - Nights of Azure 2_ Bride of the New Moon v1 0 0 (0100628004BC](https://user-images.githubusercontent.com/62343878/81566162-bc5ef900-9357-11ea-819a-1da9be0c4603.png)
![2020-05-11 07_13_50-Ryujinx 1 0 4536 - Nights of Azure 2_ Bride of the New Moon v1 0 0 (0100628004BC](https://user-images.githubusercontent.com/62343878/81566163-bcf78f80-9357-11ea-8e22-425d6d4eef86.png)
![2020-05-11 07_14_06-Ryujinx 1 0 4536 - Nights of Azure 2_ Bride of the New Moon v1 0 0 (0100628004BC](https://user-images.githubusercontent.com/62343878/81566168-bd902600-9357-11ea-9bab-7d728a0749b0.png)
![2020-05-11 07_15_08-Ryujinx 1 0 4536 - Nights of Azure 2_ Bride of the New Moon v1 0 0 (0100628004BC](https://user-images.githubusercontent.com/62343878/81566194-c680f780-9357-11ea-88a6-5e2ce9a6d2bc.png)
![2020-05-11 07_17_21-Ryujinx 1 0 4536 - Nights of Azure 2_ Bride of the New Moon v1 0 0 (0100628004BC](https://user-images.githubusercontent.com/62343878/81566196-c680f780-9357-11ea-81c9-ab466c0c52aa.png)
![2020-05-11 07_17_31-Ryujinx 1 0 4536 - Nights of Azure 2_ Bride of the New Moon v1 0 0 (0100628004BC](https://user-images.githubusercontent.com/62343878/81566215-cd0f6f00-9357-11ea-9ea6-24e558e34314.png)

#### Log file :

[NoA2BotNM.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4609793/NoA2BotNM.zip)

**Comment by GoffyDude** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by AntiGrieferGames** [comment]
This "status-playable" is misleading here because it still crashes when I press start on menu

Using a:
i5 6500
Rx 480
16gb ram

Doesnt matter while i tweaking settings or set the Graphic API to Vulkan or OpenGL


[Ryujinx_1.1.323_2022-10-22_23-23-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9845282/Ryujinx_1.1.323_2022-10-22_23-23-33.log)

**Comment by EmulationFanatic** [comment]
> still crashes when I press start on menu
> 
> Using a: i5 6500 Rx 480 16gb ram
> 
> Doesnt matter while i tweaking settings or set the Graphic API to Vulkan or OpenGL
> 
> [Ryujinx_1.1.323_2022-10-22_23-23-33.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9845282/Ryujinx_1.1.323_2022-10-22_23-23-33.log)

Thanks, I confirmed on this end. It does indeed appear that the game has suffered a regression.

**Comment by EmulationFanatic** [comment]
Updated
