### ISSUE TITLE
Finding Teddy 2

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#841]
#### Current on `master` : 1.0.4252

when its loading, before it gets to the menu it crashes.
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ARMeilleure.Memory.MemoryManager.ReadUInt16(Int64 position) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 482
   at ARMeilleure.Memory.MemoryManager.ReadUInt32(Int64 position) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 489
   at ARMeilleure.Memory.MemoryManager.ReadUInt64(Int64 position) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManager.cs:line 502
Aborted (core dumped)
```
#### Log file :
[Finding-Teddy.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4499766/Finding-Teddy.zip)

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by SeraUX** [comment]
Uodated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6906

**Comment by GamerzHell9137** [comment]
### Game Name

Finding Teddy 2: Definitive Edition

### Game Update Version

v3.0.5b

### Emulator Build Version

1.1.1287

### Graphics Backend

Vulkan

### Hardware Specs

- ##### CPU: *Ryzen 3600*
- ##### GPU: *NVIDIA RTX 3060 TI*
- ##### GPU Driver version: *546.33*
- ##### RAM: *16GB*

### Game State

Plays and runs with no issues.


### Screenshots

![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/d8825b81-4f37-448b-8e25-c2988ece0595)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/eced157c-da74-475b-83cc-61644617c3c3)
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/2002038/6244c520-9c50-44c5-9034-6dcace9951e7)


### Log File

_No response_
