### ISSUE TITLE
ACNH issue

### ISSUE THREAD

**Issue by Razills** [Ryujinx/Ryujinx-Games-List#844]
every time i try to start the game i get this error 
00:00:00.005 | Application Glib_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at ARMeilleure.Memory.MemoryManagementWindows.AllocateWriteTracked(IntPtr size) in C:\projects\ryujinx-nvrll\ARMeilleure\Memory\MemoryManagementWindows.cs:line 86
   at ARMeilleure.Memory.MemoryManagement.AllocateWriteTracked(UInt64 size) in C:\projects\ryujinx-nvrll\ARMeilleure\Memory\MemoryManagement.cs:line 43
   at Ryujinx.HLE.DeviceMemory..ctor() in C:\projects\ryujinx-nvrll\Ryujinx.HLE\DeviceMemory.cs:line 18
   at Ryujinx.HLE.Switch..ctor(VirtualFileSystem fileSystem, ContentManager contentManager, IRenderer renderer, IAalOutput audioOut) in C:\projects\ryujinx-nvrll\Ryujinx.HLE\Switch.cs:line 49
   at Ryujinx.Ui.MainWindow.InitializeSwitchInstance() in C:\projects\ryujinx-nvrll\Ryujinx\Ui\MainWindow.cs:line 271
   at Ryujinx.Ui.MainWindow.LoadApplication(String path) in C:\projects\ryujinx-nvrll\Ryujinx\Ui\MainWindow.cs:line 309
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in C:\projects\ryujinx-nvrll\Ryujinx\Ui\MainWindow.cs:line 666
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by B3astTech** [comment]
This has nothing to do with the games currently state nor does it have anything important in it. Go into our discord and send a log there please.
