### ISSUE TITLE
RXN -Raijin-

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#85]
Current on `master`:
```
System.NotImplementedException: /dev/nvhost-nvdec 40044801
   at Ryujinx.HLE.HOS.Services.Nv.INvDrvServices.Ioctl(ServiceCtx Context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Nv\INvDrvServices.cs:line 88
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx Context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 96
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch Ns, Process Process, AMemory Memory, KSession Session, IpcMessage Request, Int64 CmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 33
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.ProcessIpcRequest(Object State) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by AcK77** [comment]
Need an update.

**Comment by HorrorTroll** [comment]
Updated

**Comment by GoffyDude** [comment]
## RXN -Raijin-

#### Current on `master` : 1.0.4168

Game loads through black screen cutscene (due to nvdec) that can be skipped. Joystick input is too sensitive and menu options change on their own, making it impossible to use a controller to navigate; you must use the keyboard.
Once selecting a new game, it crashes with the below error. NOTE: this error only showed in the console, not in the logfile.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ARMeilleure.Translation.Translator.Execute(ARMeilleure.State.ExecutionContext, UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread+<>c__DisplayClass129_0.<Initialize>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-04-09 11_19_03-Ryujinx 1 0 4168 _ RXN -RAIJIN- _ 010022900B516000](https://user-images.githubusercontent.com/62343878/78922941-a1e1e900-7a54-11ea-87b4-766eb3807990.png)
![2020-04-09 11_20_16-Ryujinx 1 0 4168 _ RXN -RAIJIN- _ 010022900B516000](https://user-images.githubusercontent.com/62343878/78922943-a27a7f80-7a54-11ea-99f3-410a1b13ab92.png)
![2020-04-09 11_22_09-Ryujinx 1 0 4168 _ RXN -RAIJIN- _ 010022900B516000](https://user-images.githubusercontent.com/62343878/78922945-a3131600-7a54-11ea-8278-08e9de85691a.png)


#### Log file :

[RXNRaijin.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4457715/RXNRaijin.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
