### ISSUE TITLE
The Messenger

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#87]
Current of `master`:
```
Unhandled Exception: System.NotImplementedException: fsp-srv IStorage: 4
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx Context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 83
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch Ns, Process Process, AMemory Memory, KSession Session, IpcMessage Request, Int64 CmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 33
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.ProcessIpcRequest(Object State) in C:\pr
ojects\ryujinx\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by B3astTech** [comment]
Need's Updated

**Comment by GoffyDude** [comment]
## The Messenger

#### Current on `master` : 1.0.3937

Game is fully playable.

#### Screenshots :

![2020-03-22 07_40_08-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77250989-5ab0c700-6c11-11ea-9c5f-4ce9c955c803.png)
![2020-03-22 07_40_17-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77250990-5be1f400-6c11-11ea-8fb4-a8782864a535.png)
![2020-03-22 07_40_37-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77250992-5c7a8a80-6c11-11ea-8518-a7c393f450af.png)
![2020-03-22 07_40_55-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77250993-5d132100-6c11-11ea-896c-888a8d223366.png)
![2020-03-22 07_42_12-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77250995-5dabb780-6c11-11ea-8540-5162901ab37a.png)
![2020-03-22 07_42_38-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77250996-5e444e00-6c11-11ea-94d0-5f0f890d680b.png)
![2020-03-22 07_43_02-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77250998-5edce480-6c11-11ea-9fc2-d34e6dbf72fc.png)
![2020-03-22 07_43_22-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77251001-5f757b00-6c11-11ea-9fc4-db45ab818743.png)
![2020-03-22 07_43_57-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77251003-600e1180-6c11-11ea-88e4-85dd5248629a.png)
![2020-03-22 07_44_13-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77251005-60a6a800-6c11-11ea-8d41-d0c9c6a14c54.png)
![2020-03-22 07_44_58-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77251007-613f3e80-6c11-11ea-90cd-4ffc909d0e68.png)
![2020-03-22 07_45_41-Ryujinx 1 0 3937 _ The Messenger _ 0100DC300AC78000](https://user-images.githubusercontent.com/62343878/77251008-61d7d500-6c11-11ea-913e-d283f3f95f51.png)


#### Log file :

[TheMessenger.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4365325/TheMessenger.zip)

**Comment by B3astTech** [comment]
Updated
