### ISSUE TITLE
Riddled Corpses EX

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#887]
#### Current on `master` : 1.0.4312

Crashes on launch.

```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.HLE.Exceptions.ServiceNotImplementedException: The service call is not implemented.

Service Command: Ryujinx.HLE.HOS.Services.Nv.INvDrvServices: 6 (GetStatus)
```
#### Outstanding Issues:

https://github.com/Ryujinx/Ryujinx/issues/635

#### Log file :

[Uploading RiddledCorpsesEX.zip…]()

**Comment by GoffyDude** [comment]
Needs update

**Comment by SeraUX** [comment]
## Riddled Corpses EX
#### Current on `master` : 1.0.4613

Game crashes in arcade and survival mode with the same missing service error, while in story mode game works. The game also has some graphical bugs, but its nothing gamebreaking.

```
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Account.Acc.IManagerForApplication: 2

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00061990 nn::sf::cmif::client::CmifDomainProxyClientCoreProcessor<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> >, nn::sf::cmif::detail::CoreMethodInfo<std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> >, 0ul, 0ul,
false>, std::__1::tuple<nn::sf::cmif::detail::OutObjectArgumentInfo<0, 0> > >::ProcessWithOutObjects(nn::sf::cmif::client::CmifDomainClientMessage<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >::ProxyBaseObject*, nn::sf::cmif::client::OutObjectClientArgumentType, unsigned int, nn::sf::SharedPointer<nn::sf::IServiceObject>*)
   sdk:0x000df024 nn::sf::cmif::client::detail::CmifProxyImpl<nn::account::baas::IManagerBase, nn::sf::cmif::client::CmifDomainProxy<nn::sf::hipc::client::Hipc2ClientSessionManagedProxyKindBase<nn::sf::hipc::client::Hipc2ProxyKindBase<(nn::sf::hipc::detail::MessageType)6> > >, nn::sf::StatelessAllocationPolicy<nn::sf::ExpHeapStaticAllocator<2048ul, nn::account::detail::ObjectHolder::ObjectHolderAllocatorTag> >, nn::account::baas::IManagerForApplication>::_nn_sf_sync_EnsureIdTokenCacheAsync(nn::sf::Out<nn::sf::SharedPointer<nn::account::detail::IAsyncContext>, void>)
   sdk:0x000e9828 nn::account::EnsureNetworkServiceAccountIdTokenCacheAsync(nn::account::AsyncContext*, nn::account::UserHandle const&)
   main:0x0000c73c Sub000000000801073c
   main:0x00026be0 Sub000000000802abe0
   main:0x000292c4 Sub000000000802d2c4
   main:0x00028ef0 Sub000000000802cef0
   main:0x00019388 Sub000000000801d388
   main:0x0001949c Sub000000000801d49c
   main:0x001a228c Sub00000000081a628c
   main:0x001a24ac Sub00000000081a64ac
   main:0x001f1bec Sub00000000081f5bec
   main:0x000f919c Sub00000000080fd19c
   main:0x000f9690 Sub00000000080fd690
   main:0x00001348 nnMain
   sdk:0x0008492c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000ac Sub00000000080000ac

Raw Request Data:
00000000   01 00 10 00 02 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 01 00 00 00  02 00 00 00 00 00 00 00   SFCI············
00000020   01 00 00 00 00 00 00 00  00 FA CD 0B 00 00 04 00   ·········úÍ·····

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Screenshots :

![05_26_25-19:25:20](https://user-images.githubusercontent.com/62521228/82931446-3b267980-9f87-11ea-9b14-5bc4b7ff8cb1.png)
![05_26_25-19:25:25](https://user-images.githubusercontent.com/62521228/82931449-3c57a680-9f87-11ea-9138-19dc28a3be89.png)
![05_26_25-19:25:35](https://user-images.githubusercontent.com/62521228/82931452-3d88d380-9f87-11ea-9fb5-c067947adc30.png)
![05_26_26-19:26:01](https://user-images.githubusercontent.com/62521228/82931456-3e216a00-9f87-11ea-8828-6b2f21062e96.png)
![05_26_26-19:26:57](https://user-images.githubusercontent.com/62521228/82931458-3eba0080-9f87-11ea-86d0-00e0095063c9.png)


#### Log file :

[riddled-corpses.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4683947/riddled-corpses.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
