### ISSUE TITLE
Nintendo Labo - Toy-Con 01: Variety Kit

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx-Games-List#89]
Current on `master`:
`Unhandled Exception: System.NotImplementedException: irs IIrSensorServer: 311`

**Comment by frykillr** [comment]
also Megaman 11 has the Sensor error.

Unhandled Exception: System.NotImplementedException: irs IIrSensorServer: 311
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx Context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 83
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch Ns, Process Process, MemoryManager Memory, KSession Session, IpcMessage Request, Int64 CmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 33
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.ProcessIpcRequest(Object State) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---

**Comment by AcK77** [comment]
Need an update.

**Comment by HorrorTroll** [comment]
Updated

**Comment by benderscruffy** [comment]
gets to the next screen now

**Comment by HorrorTroll** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
