### ISSUE TITLE
Fate/EXTELLA LINK

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#893]
#### Current on `master` : 1.0.4312

Crashes on launch.

```
GUI.RenderLoop Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.Shader.StructuredIr.AstOperation.GetSource(Int32 index) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\StructuredIr\AstOperation.cs:line 37
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions.InstGenMemory.<TextureSample>g__Src|12_0(VariableType type, <>c__DisplayClass12_0& ) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\Instructions\InstGenMemory.cs:line 299
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions.InstGenMemory.TextureSample(CodeGenContext context, AstOperation operation) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\Instructions\InstGenMemory.cs:line 428
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions.InstGen.GetExpression(CodeGenContext context, AstOperation operation) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\Instructions\InstGen.cs:line 159
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.Instructions.InstGen.GetExpression(CodeGenContext context, IAstNode node) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\Instructions\InstGen.cs:line 25
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.TypeConversion.ReinterpretCast(CodeGenContext context, IAstNode node, VariableType srcType, VariableType dstType) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\TypeConversion.cs:line 24
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.PrintBlock(CodeGenContext context, AstBlock block) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 130
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.PrintMainBlock(CodeGenContext context, StructuredProgramInfo info) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 65
   at Ryujinx.Graphics.Shader.CodeGen.Glsl.GlslGenerator.Generate(StructuredProgramInfo info, ShaderConfig config) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\CodeGen\Glsl\GlslGenerator.cs:line 21
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(Operation[] ops, ShaderConfig config, Int32 size) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 75
   at Ryujinx.Graphics.Shader.Translation.Translator.Translate(ReadOnlySpan`1 code, TranslatorCallbacks callbacks, TranslationFlags flags) in C:\projects\ryujinx\Ryujinx.Graphics.Shader\Translation\Translator.cs:line 43
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.TranslateGraphicsShader(GpuState state, ShaderStage stage, UInt64 gpuVa, UInt64 gpuVaA) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 377
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(GpuState state, ShaderAddresses addresses) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Shader\ShaderCache.cs:line 130
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateShaderState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 822
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 123
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 103
   at Ryujinx.Graphics.Gpu.State.GpuState.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\State\GpuState.cs:line 74
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Send(GpuState state, GpuState shadowState, Int32 value) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 497
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Step(Int32[] mme, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 131
   at Ryujinx.Graphics.Gpu.MacroInterpreter.Execute(Int32[] mme, Int32 position, Int32 param, ShadowRamControl shadowCtrl, GpuState state, GpuState shadowState) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\MacroInterpreter.cs:line 98
   at Ryujinx.Graphics.Gpu.NvGpuFifo.CallMethod(MethodParams meth) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\NvGpuFifo.cs:line 189
   at Ryujinx.Graphics.Gpu.DmaPusher.CallMethod(Int32 argument) in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 314
   at Ryujinx.Graphics.Gpu.DmaPusher.Step() in C:\projects\ryujinx\Ryujinx.Graphics.Gpu\DmaPusher.cs:line 206
   at Ryujinx.Ui.GLRenderer.Render() in C:\projects\ryujinx\Ryujinx\Ui\GLRenderer.cs:line 337
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Log file :

[FateEXTELLALINK.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4523634/FateEXTELLALINK.zip)

**Comment by gdkchan** [comment]
Needs update.

**Comment by GoffyDude** [comment]
## Fate/EXTELLA LINK

#### Current on `master` : 1.0.4345

#### 1st attempt:
Sits at black screen but is apparently at an invisible menu screen of some kind. Pressing A twice triggers console output to show life again, but it crashes after a few seconds.

```
ServiceNv EventWait: Invalid Event at index 0 (isWaitEventAsyncCmd: True, isWaitEventCmd: False)
00:03:47.630 | ServiceNv EventWait: 
NvHostEvent 0:
	State: Signaled

00:03:47.955 | HLE.HostThread.14 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x0004d824 Sub000000000c78f824
   main:0x00aa690c Sub0000000008aaa90c
   main:0x006b358c Sub00000000086b758c
   main:0x006d7434 Sub00000000086db434
   main:0x0063e3c8 Sub00000000086423c8
   main:0x0063fb74 Sub0000000008643b74
   main:0x00673f04 Sub0000000008677f04
   sdk:0x000af8f8 Sub000000000c7f18f8
   sdk:0x000b3c58 Sub000000000c7f5c58
   ??? Sub0000000000000000
```
#### 2nd attempt:
Started pressing A and+ buttons earlier (30 second mark or so), and this time heard music. Still black screen only. Pressed A a few times, each with audio cues, and then crashed with the error below.

```
ServiceAm .ctor: Applet 'SoftwareKeyboard' created.
00:02:09.764 | KernelIpc CallMethod: Missing service Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor: 160 ignored
00:02:09.936 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Input data empty.
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AppletSession.Pop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AppletSession.cs:line 58
   at Ryujinx.HLE.HOS.Applets.SoftwareKeyboardApplet.Start(AppletSession normalSession, AppletSession interactiveSession) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Applets\SoftwareKeyboard\SoftwareKeyboardApplet.cs:line 44
   at Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.LibraryAppletCreator.ILibraryAppletAccessor.Start(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Am\AppletAE\AllSystemAppletProxiesService\LibraryAppletCreator\ILibraryAppletAccessor.cs:line 72
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

#### Log file :

[FateEXTELLALINK.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4535232/FateEXTELLALINK.zip)

**Comment by B3astTech** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
