### ISSUE TITLE
Fall Of Light - Darkest Edition

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#902]
#### Current on `master` : 1.0.4314

Intro cutscenes are black screen with subtitle text (due to nvdec), but can be skipped with the A button.
Once in-game, graphics render at less than 1 FPS, making the game unplayable.

#### Screenshots :

![2020-04-24 07_00_36-Ryujinx 1 0 4314 - Fall Of Light - Darkest Edition v1 0 0 (01005A600BE60000) (64](https://user-images.githubusercontent.com/62343878/80215584-f8752880-85f9-11ea-9b64-069d1f154d0a.png)
![2020-04-24 07_03_28-Ryujinx 1 0 4314 - Fall Of Light - Darkest Edition v1 0 0 (01005A600BE60000) (64](https://user-images.githubusercontent.com/62343878/80215593-fc08af80-85f9-11ea-80aa-8d7b22b58fe2.png)
![2020-04-24 07_04_45-Ryujinx 1 0 4314 - Fall Of Light - Darkest Edition v1 0 0 (01005A600BE60000) (64](https://user-images.githubusercontent.com/62343878/80215607-0165fa00-85fa-11ea-8512-ba50fe4bd64e.png)

#### Log file :

[FOLDE.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4529019/FOLDE.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by benderscruffy** [comment]
using 1.0.7172
still goes slow
but it keeps spamming this in the log

00:07:06.637 |E| GUI.RenderLoop Gpu GLERROR: DebugSeverityHigh: glUseProgram has failed because the operation requires the referenced program object '83' to be successfully linked (GL_INVALID_OPERATION)
CallStack=   at System.Environment.get_StackTrace()
   at Ryujinx.Graphics.OpenGL.Debugger.GLDebugHandler(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Debugger.cs:line 66
   at Ryujinx.Graphics.OpenGL.Pipeline.SetProgram(IProgram program) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Pipeline.cs:line 1014
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_68(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in C:\projects\ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 199
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in C:\projects\ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131
00:07:06.638 |E| GUI.RenderLoop Gpu GLERROR: DebugSeverityHigh: glUseProgram has failed because the operation requires the referenced program object '89' to be successfully linked (GL_INVALID_OPERATION)
CallStack=   at System.Environment.get_StackTrace()
   at Ryujinx.Graphics.OpenGL.Debugger.GLDebugHandler(DebugSource source, DebugType type, Int32 id, DebugSeverity severity, Int32 length, IntPtr message, IntPtr userParam) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Debugger.cs:line 66
   at Ryujinx.Graphics.OpenGL.Pipeline.SetProgram(IProgram program) in C:\projects\ryujinx\Ryujinx.Graphics.OpenGL\Pipeline.cs:line 1014
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_68(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in C:\projects\ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 199
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in C:\projects\ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131
[Ryujinx_1.0.7172_2022-01-15_08-28-35.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7873930/Ryujinx_1.0.7172_2022-01-15_08-28-35.log)

**Comment by EmulationFanatic** [comment]
Same status on 1.1.193

**Comment by cddude** [comment]
Game works on 1.1.1359 and game version 1.0.1
