### ISSUE TITLE
Unable to start Animal Crossing

### ISSUE THREAD

**Issue by handsomeLC** [Ryujinx/Ryujinx-Games-List#916]
## Game Name
Animal Crossing: New Horizons
#### Current on `master` : Commit Id *or* Build Version : *(e.g. 0a41a3ff or 1.0.1952)*
1.0.4345
*Describe the current game state here.*
Unable to start
```
Last error returned.
Application Glib_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at ARMeilleure.Memory.MemoryManagementWindows.AllocateWriteTracked(IntPtr size) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManagementWindows.cs:line 86
   at ARMeilleure.Memory.MemoryManagement.AllocateWriteTracked(UInt64 size) in C:\projects\ryujinx\ARMeilleure\Memory\MemoryManagement.cs:line 43
   at Ryujinx.HLE.DeviceMemory..ctor() in C:\projects\ryujinx\Ryujinx.HLE\DeviceMemory.cs:line 18
   at Ryujinx.HLE.Switch..ctor(VirtualFileSystem fileSystem, ContentManager contentManager, IRenderer renderer, IAalOutput audioOut) in C:\projects\ryujinx\Ryujinx.HLE\Switch.cs:line 49
   at Ryujinx.Ui.MainWindow.InitializeSwitchInstance() in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 273
   at Ryujinx.Ui.MainWindow.LoadApplication(String path) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 347
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 705
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.Invoke(ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```

**Comment by B3astTech** [comment]
1. This game already has its own issue
2. In-proper format

Closing in favor of https://github.com/Ryujinx/Ryujinx-Games-List/issues/250
