### ISSUE TITLE
World of Final Fantasy Maxima

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#919]
#### Current on `master` : 1.0.4345
Crashes on boot
```
Last error returned.
Unhandled exception. Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x00000000086a3748 (opcode 0x6e30c863) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1132
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 127
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line
70
Aborted (core dumped)
```

#### Log file :
[world-of-final-fantasy.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4536221/world-of-final-fantasy.log)

**Comment by EmulationFanatic** [comment]
## World of Final Fantasy Maxima

#### Current on `master` : 1.0.4683

Game now loads and plays perfectly, pegged at the 30FPS cap. Even cutscenes are working.

#### Screenshots :

![2020-06-07 07_30_31-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970358-97946d80-a892-11ea-983a-77c841685682.png)
![2020-06-07 07_30_34-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970359-982d0400-a892-11ea-8547-37717c8c62ed.png)
![2020-06-07 07_30_36-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970360-98c59a80-a892-11ea-87d7-0001cc823e33.png)
![2020-06-07 07_30_51-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970361-995e3100-a892-11ea-8829-0405b67dc47e.png)
![2020-06-07 07_30_56-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970364-9b27f480-a892-11ea-90d4-3d547ff6d5e6.png)
![2020-06-07 07_31_03-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970365-9cf1b800-a892-11ea-895d-89f385fc604d.png)
![2020-06-07 07_31_46-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970366-9d8a4e80-a892-11ea-8f46-6d91c28fe4bf.png)
![2020-06-07 07_31_48-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970367-9e22e500-a892-11ea-96fa-44b4f96f4502.png)
![2020-06-07 07_32_33-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970370-a2e79900-a892-11ea-8a94-32701d1fa6b0.png)
![2020-06-07 07_33_23-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970373-a7ac4d00-a892-11ea-814b-cef7dc960aa5.png)
![2020-06-07 07_33_53-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970381-b135b500-a892-11ea-9d99-eaadc66532dc.png)
![2020-06-07 07_35_06-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970387-b98df000-a892-11ea-9e7b-8af50c037564.png)
![2020-06-07 07_36_05-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970394-c0b4fe00-a892-11ea-946d-40d56c2524e3.png)
![2020-06-07 07_36_14-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970399-c4488500-a892-11ea-9b3e-9c98d4d66703.png)
![2020-06-07 07_37_48-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970403-cca0c000-a892-11ea-81c3-95229bb51d8f.png)
![2020-06-07 07_38_33-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970413-d62a2800-a892-11ea-897b-e61c74424cc6.png)
![2020-06-07 07_38_58-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970417-daeedc00-a892-11ea-8713-5813ebef1263.png)
![2020-06-07 07_39_08-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970422-e3471700-a892-11ea-9fbf-da074caa5b72.png)
![2020-06-07 07_39_24-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970425-e3dfad80-a892-11ea-9bb1-dececaed3436.png)
![2020-06-07 07_39_30-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970428-e80bcb00-a892-11ea-98fa-aa9193d92175.png)
![2020-06-07 07_40_39-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970432-f22dc980-a892-11ea-9240-1b63d750e04b.png)
![2020-06-07 07_42_30-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970439-f78b1400-a892-11ea-8606-914d08bf4423.png)
![2020-06-07 07_42_38-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970447-fb1e9b00-a892-11ea-96be-90fbd147accc.png)
![2020-06-07 07_43_03-Ryujinx 1 0 4683 - WORLD OF FINAL FANTASY MAXIMA v1 0 0 (010072000BD32000) (64-b](https://user-images.githubusercontent.com/62343878/83970452-007be580-a893-11ea-80a3-6fa1ba7bfc12.png)

#### Log file :

[WoFFM.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4742167/WoFFM.zip)
