### ISSUE TITLE
Brawlhalla doesn't boot

### ISSUE THREAD

**Issue by frykillr** [Ryujinx/Ryujinx-Games-List#92]
getting this error when trying to load the NSP.

Unhandled Exception: System.NotImplementedException: hwopus
   at Ryujinx.HLE.HOS.Services.ServiceFactory.MakeService(Horizon System, String Name) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServiceFactory.cs:line 193
   at Ryujinx.HLE.HOS.Services.Sm.IUserInterface.GetService(ServiceCtx Context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Sm\IUserInterface.cs:line 70
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx Context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 96
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch Ns, Process Process, MemoryManager Memory, KSession Session, IpcMessage Request, Int64 CmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 33
   at Ryujinx.HLE.HOS.Kernel.SvcHandler.ProcessIpcRequest(Object State) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SvcSystem.cs:line 231
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[brawl.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/2566479/brawl.txt)

**Comment by AcK77** [comment]
Updated

**Comment by jduncanator** [comment]
Updated

**Comment by AcK77** [comment]
Updated

**Comment by EmulationFanatic** [comment]
## Brawlhalla

#### Current on `master` : 1.0.4683

Game now loads and plays in offline mode at a high FPS, but there are game-breaking texture issues that make it impossible to play. See screenshots.

#### Screenshots :

![2020-06-08 17_50_34-Ryujinx 1 0 4683 - Brawlhalla v3 28 (0100C6800B934000) (64-bit)](https://user-images.githubusercontent.com/62343878/84091620-39f74280-a9b2-11ea-8333-86d7b20d7736.png)
![2020-06-08 17_51_40-Ryujinx 1 0 4683 - Brawlhalla v3 28 (0100C6800B934000) (64-bit)](https://user-images.githubusercontent.com/62343878/84091635-44194100-a9b2-11ea-9066-01dace7b0d75.png)
![2020-06-08 17_52_35-Ryujinx 1 0 4683 - Brawlhalla v3 28 (0100C6800B934000) (64-bit)](https://user-images.githubusercontent.com/62343878/84091639-47acc800-a9b2-11ea-8154-9880c4e08cec.png)
![2020-06-08 17_52_47-Ryujinx 1 0 4683 - Brawlhalla v3 28 (0100C6800B934000) (64-bit)](https://user-images.githubusercontent.com/62343878/84091652-4ed3d600-a9b2-11ea-9fd8-21fc5f1b82cf.png)
![2020-06-08 17_53_02-Ryujinx 1 0 4683 - Brawlhalla v3 28 (0100C6800B934000) (64-bit)](https://user-images.githubusercontent.com/62343878/84091658-54312080-a9b2-11ea-80ef-37565af39154.png)
![2020-06-08 17_53_22-Ryujinx 1 0 4683 - Brawlhalla v3 28 (0100C6800B934000) (64-bit)](https://user-images.githubusercontent.com/62343878/84091664-5a270180-a9b2-11ea-802e-ae63e9a6585e.png)
![2020-06-08 17_58_17-Ryujinx 1 0 4683 - Brawlhalla v3 28 (0100C6800B934000) (64-bit)](https://user-images.githubusercontent.com/62343878/84091671-601ce280-a9b2-11ea-993b-d46f87e168c9.png)
![2020-06-08 17_58_58-Ryujinx 1 0 4683 - Brawlhalla v3 28 (0100C6800B934000) (64-bit)](https://user-images.githubusercontent.com/62343878/84091687-6ca13b00-a9b2-11ea-8625-4cf7d2d381c1.png)
![2020-06-08 17_59_03-Ryujinx 1 0 4683 - Brawlhalla v3 28 (0100C6800B934000) (64-bit)](https://user-images.githubusercontent.com/62343878/84091714-788cfd00-a9b2-11ea-8a73-cbf3fe9c5186.png)


#### Log file :

[Brawlhalla.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4749156/Brawlhalla.zip)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Updated
