### ISSUE TITLE
ITTA

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#920]
#### Current on `master` : 1.0.4345

Game crashes on boot

```
Last error returned.
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.HLE.Exceptions.ServiceNotImplementedException: The service call is not implemented.

Service Command: Ryujinx.HLE.HOS.Services.Nv.INvDrvServices: 6 (GetStatus)

Guest Stack Trace:
Process: Application, PID: 81
   sdk:0x00399530 Sub000000000b2b3530
   sdk:0x003978e4 Sub000000000b2b18e4
   sdk:0x0039af98 Sub000000000b2b4f98
   sdk:0x00397144 nv::GetGraphicsMemoryInfo(nv::MemoryInfo*)
   main:0x0006c50c Sub000000000807050c
   main:0x000ac60c Sub00000000080b060c
   main:0x000a0e50 Sub00000000080a4e50
   main:0x000a135c Sub00000000080a535c
   main:0x00000ac4 Sub0000000008004ac4
   main:0x00001034 nnMain
   sdk:0x0009857c nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)())
   rtld:0x000000c0 Sub00000000080000c0

Raw Request Data:
00000000   53 46 43 49 01 00 00 00  06 00 00 00 00 00 00 00   SFCI············
00000010   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ················

   at Ryujinx.HLE.HOS.Services.Nv.INvDrvServices.GetStatus(ServiceCtx context) in /home/space/Documents/Games/Switch/master-git/Ryujinx.HLE/HOS/Services/Nv/INv
DrvServices.cs:line 386
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in /home/space/Documents/Games/Switch/master-git/Ryujinx.HLE/HOS/Services/IpcService.c
s:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request,
 Int64 cmdPtr) in /home/space/Documents/Games/Switch/master-git/Ryujinx.HLE/HOS/Ipc/IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in /home/space/Documents/Games/Switch/master-git/Ryujinx.HLE/HOS/Kernel/
SupervisorCall/SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```

#### Log file :
[itta.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4537223/itta.log)

**Comment by GoffyDude** [comment]
Needs update

**Comment by SeraUX** [comment]
## ITTA

#### Current on `master` : 1.0.4573
Game runs a little bit on the slow side, but its playable and the it has some graphical glitches like the weapon wheel always being present and not rendering correctly

#### Screenshots :
![2020-05-17-100007_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82139333-4bbc4e80-9827-11ea-8e62-5f5459cd0e9d.png)
![2020-05-17-100206_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82139336-4fe86c00-9827-11ea-9e31-dff3ca961c1e.png)
![2020-05-17-100343_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82139339-54ad2000-9827-11ea-962f-164f5a34e402.png)
![2020-05-17-100524_1920x1080_scrot](https://user-images.githubusercontent.com/62521228/82139340-5676e380-9827-11ea-9c6c-acfccb25c541.png)


#### Log file :
[itta.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4639901/itta.log)

**Comment by GoffyDude** [comment]
Updated

**Comment by EmulationFanatic** [comment]
Same status on 1.0.6575.

**Comment by EmulationFanatic** [comment]
Updated
