### ISSUE TITLE
Sengoku Cannon for Nintendo Switch

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#929]
#### Current on `master` : 1.0.4354

All menus/graphics are rendered upside down, and after character select the game crashes.

```
HLE.HostThread.2 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 81
   sdk:0x00175ec0 nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   sdk:0x00175f84 Sub000000000f78df84
   sdk:0x00176020 nn::diag::detail::OnAssertionFailure(nn::diag::AssertionType, char const*, char const*, char const*, int, char const*, ...)
   main:0x0000f2f4 AudioRendererThread::DecodeFunc(int)
   main:0x0000e960 AudioRendererThread::ThreadEntry(void*)
   sdk:0x0031d4d8 Sub000000000f9354d8
   sdk:0x00321938 Sub000000000f939938
   ??? Sub0000000000000000


00:02:55.222 | HLE.HostThread.2 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.Break(UInt64 reason) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcSystem.cs:line 285
   at Break64(SvcHandler , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcHandler.cs:line 23
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 62
   at ARMeilleure.Instructions.NativeInterface.GetFunctionAddress(UInt64 address) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 390
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 96
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

#### Screenshots :

![2020-04-27 08_27_55-Ryujinx 1 0 4354 - Sengoku Cannon for Nintendo Switch v1 0 0 (0100A2300DB78000) ](https://user-images.githubusercontent.com/62343878/80383860-62433b80-8861-11ea-811b-3907011bab27.png)
![2020-04-27 08_28_12-Ryujinx 1 0 4354 - Sengoku Cannon for Nintendo Switch v1 0 0 (0100A2300DB78000) ](https://user-images.githubusercontent.com/62343878/80383866-63746880-8861-11ea-83a0-3ce10120ccf7.png)
![2020-04-27 08_29_03-Ryujinx 1 0 4354 - Sengoku Cannon for Nintendo Switch v1 0 0 (0100A2300DB78000) ](https://user-images.githubusercontent.com/62343878/80383869-64a59580-8861-11ea-8503-4f82f044c25d.png)
![2020-04-27 08_29_09-Ryujinx 1 0 4354 - Sengoku Cannon for Nintendo Switch v1 0 0 (0100A2300DB78000) ](https://user-images.githubusercontent.com/62343878/80383877-6707ef80-8861-11ea-9e7b-c9452fd0451a.png)
![2020-04-27 08_29_34-Ryujinx 1 0 4354 - Sengoku Cannon for Nintendo Switch v1 0 0 (0100A2300DB78000) ](https://user-images.githubusercontent.com/62343878/80383897-6e2efd80-8861-11ea-8550-83fc238bc6f6.png)

#### Log file :

[SCforNS.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4540234/SCforNS.zip)

**Comment by EmulationFanatic** [comment]
Updated
