### ISSUE TITLE
Sonic Force crash after a while of 'loading'

### ISSUE THREAD

**Issue by frykillr** [Ryujinx/Ryujinx-Games-List#94]
after launching ryujinx with Sonic Forces NSP black screen and after awhile it crashes

Unhandled Exception: ChocolArm64.Exceptions.VmmPageFaultException: Tried to access unmapped address 0xfffffffffffff000!
   at ChocolArm64.Memory.MemoryManager.HandleNullPte(Int64 position) in C:\projects\ryujinx\ChocolArm64\Memory\MemoryManager.cs:line 520
   at ChocolArm64.Memory.MemoryManager.GetPhysicalAddress(Int64 virtualAddress) in C:\projects\ryujinx\ChocolArm64\Memory\MemoryManager.cs:line 470
   at ChocolArm64.Memory.MemoryManager.EnsureRangeIsValid(Int64 position, Int64 size) in C:\projects\ryujinx\ChocolArm64\Memory\MemoryManager.cs:line 695
   at Ryujinx.Graphics.NvGpuEngine3d.UploadVertexArrays(NvGpuVmm Vmm, GalPipelineState State) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 715
   at Ryujinx.Graphics.NvGpuEngine3d.VertexEndGl(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 126
   at Ryujinx.Graphics.NvGpuEngine3d.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuEngine3d.cs:line 84
   at Ryujinx.Graphics.MacroInterpreter.Send(NvGpuVmm Vmm, Int32 Value) in C:\projects\ryujinx\Ryujinx.Graphics\MacroInterpreter.cs:line 415
   at Ryujinx.Graphics.MacroInterpreter.Step(NvGpuVmm Vmm, Int32[] Mme) in C:\projects\ryujinx\Ryujinx.Graphics\MacroInterpreter.cs:line 192
   at Ryujinx.Graphics.MacroInterpreter.Execute(NvGpuVmm Vmm, Int32[] Mme, Int32 Position, Int32 Param) in C:\projects\ryujinx\Ryujinx.Graphics\MacroInterpreter.cs:line 82
   at Ryujinx.Graphics.NvGpuFifo.Call3dMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 188
   at Ryujinx.Graphics.NvGpuFifo.CallMethod(NvGpuVmm Vmm, NvGpuPBEntry PBEntry) in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 120
   at Ryujinx.Graphics.NvGpuFifo.Step() in C:\projects\ryujinx\Ryujinx.Graphics\NvGpuFifo.cs:line 104
   at Ryujinx.GlScreen.RenderLoop() in C:\projects\ryujinx\Ryujinx\Ui\GLScreen.cs:line 67
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

[SonicF.txt](https://github.com/Ryujinx/Ryujinx-Games-List/files/2567118/SonicF.txt)

**Comment by AcK77** [comment]
Please, post a comment inside https://github.com/Ryujinx/Ryujinx-Games-List/issues/56 instead of open a new issue. Thanks.
