### ISSUE TITLE
Piczle Lines DX

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#962]
#### Current on `master` : 1.0.4362

Appears to hang forever but crashes 15 minutes in to emulation.

```
-----FILE SYSTEM STARTUP-----'

00:14:51.053 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> LibHac.HorizonResultException: ResultFsInvalidIvfcHash (2002-4604): Hash error!
   at LibHac.ThrowHelper.ThrowResult(Result result, String message)
   at LibHac.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination, IntegrityCheckLevel integrityCheckLevel)
   at LibHac.FsSystem.IntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination)
   at LibHac.Fs.StorageBase.Read(Int64 offset, Span`1 destination)
   at LibHac.FsSystem.CachedStorage.ReadBlock(CacheBlock block, Int64 index)
   at LibHac.FsSystem.CachedStorage.GetBlock(Int64 blockIndex)
   at LibHac.FsSystem.CachedStorage.ReadImpl(Int64 offset, Span`1 destination)
   at LibHac.Fs.StorageBase.Read(Int64 offset, Span`1 destination)
   at LibHac.FsSystem.HierarchicalIntegrityVerificationStorage.ReadImpl(Int64 offset, Span`1 destination)
   at LibHac.Fs.StorageBase.Read(Int64 offset, Span`1 destination)
   at LibHac.FsSystem.StorageStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at LibHac.FsSystem.StreamStorage.ReadImpl(Int64 offset, Span`1 destination)
   at LibHac.Fs.StorageBase.Read(Int64 offset, Span`1 destination)
   at Ryujinx.HLE.HOS.Services.Fs.FileSystemProxy.IStorage.Read(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Fs\FileSystemProxy\IStorage.cs:line 35
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 50
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 157
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

#### Log file :

[PLDX.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4548397/PLDX.zip)

**Comment by benderscruffy** [comment]
goes ingame now

**Comment by EmulationFanatic** [comment]
Updated

**Comment by benderscruffy** [comment]
there must be a problem with your graphics card or drivers
as you can see it goes ingame 
![piczle](https://user-images.githubusercontent.com/2696404/99159936-b853cf80-271c-11eb-807e-38adcfec31ec.PNG)

**Comment by EmulationFanatic** [comment]
My card and drivers are fine and work on other games without issue. The game is likely not happy with Nvidia GPUs, which are the majority of GPUs out there. The gamedb entries should be indicative of the typical end user experience so we will keep the labels as is.

**Comment by gdkchan** [comment]
The log indicates a HID issue rather than a GPU issue. It might only work on specific controller configurations.

**Comment by EmulationFanatic** [comment]
HID changes didn't make a difference. However my PC with the AMD graphics card booted the game fine.

**Comment by benderscruffy** [comment]
so it is a Nvidia driver problem then

**Comment by EmulationFanatic** [comment]
Updated
