### ISSUE TITLE
Ni No Kuni Wrath of the White Witch

### ISSUE THREAD

**Issue by SeraUX** [Ryujinx/Ryujinx-Games-List#980]
#### Current on `master` : 1.0.4362

Game crashes on boot
```
Last error returned.
00:00:03.494 | HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x0000000000215090 (opcode 0xe101c040) is undefined!
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.UndefinedInstructionHandler(Object sender, InstUndefinedEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 1132
   at ARMeilleure.State.ExecutionContext.OnUndefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 127
   at ARMeilleure.Instructions.NativeInterface.Undefined(UInt64 address, Int32 opCode) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line
70
```

#### Log file :

[ni-no-kuni-wrath-of-the-white-witch.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/4552442/ni-no-kuni-wrath-of-the-white-witch.log)

**Comment by riperiperi** [comment]
Required to boot menu:

- VABS fix
- VTST
- VFMA, VFMS, VFNMA, VFNMS (similar to MLA and pals, but explicitly fused)
- VPMIN, VPMAX
- VRINTX (round with inexact exception)
- VMVN (register)

- Browser applet: game uses LibAppletOff to display a EULA that the user must accept. Expects `LastUrl` exit code, with LastUrl equivalent to `http://localhost?id=0`. id is 1 for decline.

When attempting to go ingame, a function is called in thumb mode, so it's likely we need to add lots of thumb encodings to go further.

**Comment by raintrija** [comment]
## Ni No Kuni Wrath of the White Witch - 0100E5600D446000

#### Game Update Version : 1.0.2

#### Current on `master` : 1.0.7047

Game Boots in some minute but intro loops and freezes

```
Last error returned.
00:00:42.241 |S| HLE.OsThread.15 ServiceMm SetAndWait: Stubbed. {id: 7 ; frequenceHz: 4294966296 ; timeout: -1}
00:00:42.241 |S| HLE.OsThread.15 ServiceMm Get: Stubbed. {id: 7}
00:00:42.241 |S| HLE.OsThread.15 ServiceMm SetAndWait: Stubbed. {id: 7 ; frequenceHz: 4294966296 ; timeout: -1}
00:00:42.241 |S| HLE.OsThread.15 ServiceMm Get: Stubbed. {id: 7}
00:00:42.243 |S| HLE.OsThread.15 ServiceMm SetAndWait: Stubbed. {id: 7 ; frequenceHz: 3875766000 ; timeout: -1}
00:00:42.243 |S| HLE.OsThread.15 ServiceMm Get: Stubbed. {id: 7}
00:00:42.507 |S| HLE.OsThread.15 ServiceMm SetAndWait: Stubbed. {id: 7 ; frequenceHz: 3497366000 ; timeout: -1}
00:00:42.507 |S| HLE.OsThread.15 ServiceMm Get: Stubbed. {id: 7}
00:00:42.509 |S| HLE.OsThread.9 ServiceNv SetNvMapFd: Stubbed. 
00:00:42.509 |I| HLE.OsThread.9 ServiceNv Create: Created map 241 with size 0x00008000!
00:00:42.509 |I| HLE.OsThread.9 ServiceNv Create: Created map 242 with size 0x00008000!
00:00:42.510 |I| HLE.OsThread.9 ServiceNv Create: Created map 243 with size 0x00003000!
00:00:42.510 |I| HLE.OsThread.9 ServiceNv Create: Created map 244 with size 0x00001000!
00:00:42.510 |I| HLE.OsThread.9 ServiceNv Create: Created map 245 with size 0x00001000!
```

#### Hardware Specs : 

##### CPU:  Intel i5-10500@4.2GHz
##### GPU: AMD R9 290 4GB
##### RAM: 32 GB DDR4@3GHz

#### Pull requests needed :

none

#### Outstanding Issues:

Crashed when running "Ni no Kuni: Wrath of the White Witch"

#### Screenshots :

![image](https://user-images.githubusercontent.com/89759173/135010213-b9368a85-3ca9-43c3-a84d-93f5a734d0a0.png)

#### Log file :
[Ryujinx_1.0.7047_2021-09-28_08-58-35.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7240396/Ryujinx_1.0.7047_2021-09-28_08-58-35.log)

**Comment by codbugpatrol** [comment]
Same status on 1.0.7066

**Comment by taiwan-king** [comment]
Same status on 1.1.136

**Comment by Djipi71** [comment]
Test on 1.1.213 , The game work but the text ars not readable...
![ryujinx_capture_2022-08-13_18-38-58](https://user-images.githubusercontent.com/35375131/184503011-8415c089-49b6-4461-82b4-29058aa0f211.png)
[Ryujinx_1.1.213_2022-08-13_18-38-05.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9331830/Ryujinx_1.1.213_2022-08-13_18-38-05.log)

**Comment by EmulationFanatic** [comment]
Updated

**Comment by B00MST3R** [comment]
I'm getting this issue with the Mac Vulkan/Molten Version too.

**Comment by EmulationFanatic** [comment]
> I'm getting this issue with the Mac Vulkan/Molten Version too.

A save file and version 1.0.0 should work.

**Comment by LukeWarnut** [comment]
> > I'm getting this issue with the Mac Vulkan/Molten Version too.
> 
> A save file and version 1.0.0 should work.

It's likely crashing because of https://github.com/Ryujinx/Ryujinx/issues/3951

**Comment by EmulationFanatic** [comment]
It's not crashing on Windows (and I haven't heard of it crashing on Mac either)...it hangs on boot because it's trying to pop the web applet.

**Comment by GoranXXV** [comment]
After bypassing EULA Contract and starting a new game, I have a texture bug after the initial cutscenes
![Screenshot_20230223_142727](https://user-images.githubusercontent.com/101893515/220920731-4cdc9c70-2939-4b06-abae-06011c9da457.png)

### Log file

[Ryujinx_1.1.637_2023-02-23_14-25-18.log](https://github.com/Ryujinx/Ryujinx/files/10813959/Ryujinx_1.1.637_2023-02-23_14-25-18.log)


### OS

Windows 11

### Ryujinx version

1.1.637

### Game version

1.0.2

### CPU

i5-8250U

### GPU

NVIDIA MX 130

### RAM

8GB

### List of applied mods

_No response_

### Additional context?

If I start a new game with no patch I don't have any texture bugs 
![Screenshot_20230223_144045](https://user-images.githubusercontent.com/101893515/220923509-4aba0a32-97be-4f41-ad9f-f3dd0876df58.png)

**Comment by Triton3a** [comment]
Game Update Version : 1.0.1 (same for 1.0.0)
Current on master : 1.0.6852 till 1.1.955

Hardware Specs :
AMD Ryzen 7 5700G
GPU: radeon 550 rx
RAM: 16GB

Game runs perfect, but it cant load or create save file.
Log this after pressing «Start» in menu for save
00:04:17.651 |S| HLE.OsThread.22 ServiceAm Start: Stubbed. DocumentPath: s.htdocs/s.htm?eAElTkFqwzAQ/MpUl15MoQ09RFdT0kNoSxvowfJBJJtKZb0bJMXBD8gf8r68JApmYZYZZpjpOrMJhN8QS8VYtsE05ov9RMnik+NIycn8HzPWNBJbLJdO1rr1JapYfCtzlD+8R+bspD2mRFKwUl+tb/KvE2osTSXcXRUzTpp4h+AzikL3e0oPTu6t2MSBLJ4Xr/Zl4eR6OaPV4cBUaIeVHwg/fiTTN535oNNMGtMm8nW+h1QtV+3JyXym7282hE7y
![01-Ni no kuni](https://github.com/Ryujinx/Ryujinx-Games-List/assets/139051389/a43056dd-79de-4a89-88d6-f85f34cdf1c5)
[Ryujinx_1.1.955_2023-07-09_15-22-35.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11995169/Ryujinx_1.1.955_2023-07-09_15-22-35.log)

**Comment by joseramosdarias** [comment]
Now it works perfectly, with Ryujinx 1,1,1051....but I can´t save the game

**Comment by Djipi71** [comment]
No it not working even in Vulkan or OpenGL
![image](https://github.com/Ryujinx/Ryujinx-Games-List/assets/35375131/f9db62e1-f1b2-4484-ba3c-844eeb8a3635)

**Comment by Ern-Ani** [comment]
The title screen loops on 1.1.1247 , using Vulkan or openGL.

**Comment by foctober** [comment]
Infinite Loop of Title Screen, can't proceed/play/save, problem has persisted for me for maybe the last 20 Ryujinx versions, currently on:

Ryujunx Version 1.1.1248 - 2024-03-27
Using XCI Game File
Game Update 1.0,2

I have never been able to play this game in Ryujinx.

**Comment by Ern-Ani** [comment]
Version 1.1.1254 title screen loops still continue, using Vulkan or openGL version 1.0.0 or 1.0.2

**Comment by joseramosdarias** [comment]
<img width="1494" alt="Captura de pantalla 2024-04-06 a las 11 53 31" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/32616105/68448db9-6446-4187-a1ac-16e6010f8c37">
<img width="1496" alt="Captura de pantalla 2024-04-06 a las 11 52 35" src="https://github.com/Ryujinx/Ryujinx-Games-List/assets/32616105/8b70a931-8c85-46d6-a822-859fa465c861">

The only problem is when I save a game, I can not use the option continue from the main menu.

**Comment by Ern-Ani** [comment]
Version 1.1.1262 title screen loops still continue, using Vulkan or openGL version 1.0.0 or 1.0.2 in windows 10 and windows 11 both 64bit versions.

**Comment by joseramosdarias** [comment]
Try to update the game

**Comment by Ern-Ani** [comment]
here I will rewrite it in more detail then:
 Use the version of Ryujinx 1.1.1262, the title screen loops still continue, using Vulkan or OpenGL, game in versions 1.0.0 or update to the latest version 1.0.2 tested in the windows 10 and windows 11 both 64bit of the system.

**Comment by Seppi2k** [comment]
> here I will rewrite it in more detail: I used Ryujinx version 1.1.1262, the title screen loops still continue, using Vulkan or OpenGL, game on versions 1.0.0 or update to the latest version 1.0.2 tested on windows 10 and windows 11 both 64-bit versions.

same here. Ryujinx 1.1.1297. Win11 24H2 64Bit -> title screen loops

[Ryujinx_1.1.1297_2024-05-06_19-43-01.log.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/15224505/Ryujinx_1.1.1297_2024-05-06_19-43-01.log.zip)

**Comment by Ern-Ani** [comment]
Used Ryujinx version 1.1.1318, the title screen loops still continue, using Vulkan or OpenGL, game on versions 1.0.0 or update to the latest version 1.0.2 tested on windows 10 and windows 11 both 64-bit versions.

**Comment by Ern-Ani** [comment]
Same old, nothing new! Used Ryujinx version 1.1.1330, the title screen loops still continue, using Vulkan or OpenGL, game on versions 1.0.0 or update to the latest version 1.0.2 tested on windows 10 and windows 11 both 64-bit versions.

**Comment by Triton3a** [comment]
> Same old, nothing new! Used Ryujinx version 1.1.1330, the title screen loops still continue, using Vulkan or OpenGL, game on versions 1.0.0 or update to the latest version 1.0.2 tested on windows 10 and windows 11 both 64-bit versions.

use my config.bin file (u can play this game with banned emulator)
[ninokuni.zip](https://github.com/user-attachments/files/15757288/ninokuni.zip)

**Comment by Ashitaaka** [comment]
@Triton3a  it helps avoiding the loop screen, but i still cannot save and continue from a save.. Any idea?

**Comment by joseramosdarias** [comment]
Nop…the game can´t save…idk why…I´ve play the game with RPCS3 (playstation 3 emulator), and it works.

**Comment by Triton3a** [comment]
> @Triton3a it helps avoiding the loop screen, but i still cannot save and continue from a save.. Any idea?

last EA yuzu build can open save menu (also need conf-Bin file.
