### ISSUE TITLE
Outlast 2

### ISSUE THREAD

**Issue by GoffyDude** [Ryujinx/Ryujinx-Games-List#996]
#### Current on `master` : 1.0.4383

Crashes immediately on launch.

```
HLE.HostThread.0 Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.InvalidOperationException: The LinkedList node does not belong to current LinkedList.
   at System.Collections.Generic.LinkedList`1.ValidateNode(LinkedListNode`1 node)
   at System.Collections.Generic.LinkedList`1.AddBefore(LinkedListNode`1 node, T value)
   at Ryujinx.HLE.HOS.Kernel.Memory.KMemoryManager.InsertBlock(UInt64 baseAddress, UInt64 pagesCount, MemoryState state, MemoryPermission permission, MemoryAttribute attribute) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Memory\KMemoryManager.cs:line 2506
   at Ryujinx.HLE.HOS.Kernel.Memory.KMemoryManager.UnmapPhysicalMemory(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Memory\KMemoryManager.cs:line 1445
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.UnmapPhysicalMemory(UInt64 address, UInt64 size) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcMemory.cs:line 451
   at UnmapPhysicalMemory64(SvcHandler , ExecutionContext )
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.SvcCall(Object sender, InstExceptionEventArgs e) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcHandler.cs:line 34
   at ARMeilleure.State.ExecutionContext.OnSupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\State\ExecutionContext.cs:line 122
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in C:\projects\ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 61
   at ARMeilleure.Translation.TranslatedFunction.Execute(ExecutionContext context) in C:\projects\ryujinx\ARMeilleure\Translation\TranslatedFunction.cs:line 27
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\projects\ryujinx\ARMeilleure\Translation\Translator.cs:line 96
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart(UInt64 entrypoint) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1146
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.<>c__DisplayClass129_0.<Initialize>b__0() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 164
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

#### Log file :

[Outlast2.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/4558210/Outlast2.zip)

**Comment by EmulationFanatic** [comment]
Needs update

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Doctorwho1909** [comment]
[Ryujinx_2020-09-01_00-16-19.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5153758/Ryujinx_2020-09-01_00-16-19.log)
Crashing on videos at the start

**Comment by Doctorwho1909** [comment]
[Ryujinx_1.0.6020_2020-12-11_00-10-28.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/5677022/Ryujinx_1.0.6020_2020-12-11_00-10-28.log)
1.0.6020 master still crashes

**Comment by EmulationFanatic** [comment]
Updated

**Comment by Djipi71** [comment]
Test on RyujiNX Build : REV 7065

The game now go ingame but when you read the first text on the house when you see the first man dead , the game crash.

LOG :
[Ryujinx_1.0.7065_2021-10-08_10-40-01.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7309818/Ryujinx_1.0.7065_2021-10-08_10-40-01.log)

SCREEN : 
![ryujinx_capture_2021-10-08_10-48-30](https://user-images.githubusercontent.com/35375131/136527051-6b099c79-bb80-415f-88fa-60e9674b44e3.png)

SAVE : 
[save.zip](https://github.com/Ryujinx/Ryujinx-Games-List/files/7309847/save.zip)

**Comment by Djipi71** [comment]
Test on Build : 1.1.4  Same problem. The game freeze after taking the file with the camera

LOG:
[Ryujinx_1.1.4_2022-01-22_23-22-15.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/7919409/Ryujinx_1.1.4_2022-01-22_23-22-15.log)
